### ISSUE TITLE
Feature Request: Auto-discard messages after set time

### ISSUE THREAD

**Issue by Kilvoctu** [Chatterino/chatterino2#1010]
I'm using Chatterino as an onscreen chat overlay due to its regex commands to filter messages.

However, one feature that would be helpful is the ability to set a length of time after a message appears before it is discarded. I'm aware that there is a "Clear messages" option, but this does not fulfill the needed use case. An example usage would be something like, "Discard message 30 seconds after it's received".

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
