### ISSUE TITLE
resub messages are not shown in /mentions

### ISSUE THREAD

**Issue by TranRed** [Chatterino/chatterino2#1013]
Highlight and custom sound is working in resub-messages, but it does not show up in the /mentions tab. Having it there would make the message that pings you easier to identify, when it comes from a huge channel (e.g. forsen)

![grafik](https://user-images.githubusercontent.com/16636423/56460520-55fde600-63a4-11e9-9c11-4d013d2ad351.png)

![grafik](https://user-images.githubusercontent.com/16636423/56460529-79289580-63a4-11e9-97d7-c709a6f40fd3.png)

**Comment by Felanbird** [comment]
I noticed that resub messages don't light up anymore either 🤔 
![image](https://user-images.githubusercontent.com/41973452/89616121-cd83ad00-d855-11ea-8ab3-b399841ca0cc.png)

Possibly because of the highlight overhaul?

**Comment by jammehcow** [comment]
Still occurs in chatterino 2.3.0 even though the username is clickable.
