### ISSUE TITLE
Twitch Sub emote channel location? and another emote thing

### ISSUE THREAD

**Issue by Zanuh** [Chatterino/chatterino2#1015]
Make it possible to when you hover on a sub emote, to see which channel the emotes comes from. At this moment, it's just possible to see name of the emote, but not which channel it comes from. 

Would be kinda nice to have a feature that when you hover over an emote, it makes the emote bigger so you more easily can check how emotes look, just like in normal Twitch Chat.

**Comment by TranRed** [comment]
Sounds like this is a combination of #917 and #976 if I understand correctly
