### ISSUE TITLE
Add a message separating days after 12 am

### ISSUE THREAD

**Issue by savabozo** [Chatterino/chatterino2#1016]
Some messages may have been sent weeks or days apart.
When loading chat history and encountering such, i suggest to add a date label split.

<details>
  <summary>Currently at Ch2 (screenshot)</summary>
  
![2019-04-21_15-25-06](https://user-images.githubusercontent.com/47025788/56469454-0de5ce80-644b-11e9-9bf9-55ead5779ae5.png)

</details>

<details>
  <summary>Desirable behaviour (screenshot of example in another app)</summary>
  
![2019-04-21_15-30-05](https://user-images.githubusercontent.com/47025788/56469465-35d53200-644b-11e9-8295-d7207d0f18ab.png)

(it is Telegram Desktop)
</details>

**Comment by RAnders00** [comment]
Other option is to show an additional date in the timestamp place if the message is older than 24 hours

**Comment by RAnders00** [comment]
Saw this today on mixer, definitely a nice way of doing it too:

![image](https://user-images.githubusercontent.com/1629196/62388081-addbe980-b55c-11e9-89b5-bdc160d0100c.png)

**Comment by RAnders00** [comment]
Adding this to merge duplicate issue #1158 by @Zanuh:

Another option is to show timestamps only in "slow" channels (by some kind of measure), and have that be a setting:

Zanuh wrote:
> It is possible to enable/disable timestamps in Chatterino 2. However, I would like to be able to have timestamps automatically in some channels that has fewer chatters, etc. I would like to have a setting where you could enable timestamps on specific channel(s) while other channels doesn't get it enabled. Currently now you can just disable/enable it for either all channels or none.
