### ISSUE TITLE
PubSub doesn't connect after a disconnect/reconnect

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1022]
This also applies when switching accounts

**Comment by apa420** [comment]
Also doesn't connect after being modded

**Comment by TETYYS** [comment]
Now it works correctly after https://github.com/fourtf/chatterino2/pull/1049 , but still doesn't if I hibernate my PC with chatterino open and come back to it.

**Comment by apa420** [comment]
It does not work correctly after #1049 the only thing #1049 did was make it so pubsub messages would appear in the right channel. This has nothing to do with the pubsub connecting or reconnecting issue.

**Comment by savabozo** [comment]
Might be the cause of #937

**Comment by alazymeme** [comment]
I just reconnected on d1d17d4e4 and it worked just fine. Does this still happen? Or am I missing a certain step?

**Comment by TETYYS** [comment]
Can you try hibernating and resuming your PC?

**Comment by alazymeme** [comment]
I will test when I get home tonight - I disabled hibernation on my pc a while ago so I'll have to re-enable it.

**Comment by fourtf** [comment]
@pajlada do you know if this still happens?

**Comment by TETYYS** [comment]
i personally still encounter it after every day `Chatterino Nightly 2.2.1 (commit 63c167f1d, )`

**Comment by Felanbird** [comment]
I have been asked by a mysterious person to bump this. 😱

**Comment by zneix** [comment]
This is happening very often as of recently, @pajlada could you look into this? thank you :heart:

**Comment by karl-police** [comment]
It's happening too much

**Comment by karl-police** [comment]
Does this work properly? https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchChannel.cpp#L169

**Comment by Mm2PL** [comment]
> Does this work properly? https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchChannel.cpp#L783

That reconnects to pubsub, it just re-listens on an existing connection.

**Comment by apa420** [comment]
Does this only happen when hibernating your pc?
Because it's properly connecting for me otherwise.

**Comment by Mm2PL** [comment]
Pubsub connection still breaks after suspending my laptop. ![dank](https://cdn.frankerfacez.com/emote/536927/1)

**Comment by Felanbird** [comment]
Fixed by #3643
