### ISSUE TITLE
Add the ability to turn on and off red lines when msg deleted

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#1023]

**Comment by TranRed** [comment]
didn't the red line meme get removed?

**Comment by Dolev24** [comment]
It did, thats why im forced to use an older version because it helps me mod, thats why i want the ability to have it on

**Comment by TranRed** [comment]
So you basically need a high visible indicator for messages that got already removed?
Maybe someone can come up with something that's more pleasant looking :)

**Comment by fourtf** [comment]
I don't understand this but I assume you mean this: https://github.com/Chatterino/chatterino2/issues/1984
