### ISSUE TITLE
Emote menu unresponsive after closed

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1027]
If you open the emote menu (ctrl+e) and then close it with the Windows window manager it will become unusable the next time you open it, only options is to resize and fullscreen the window.
The emote window will only start working after a restart or if you open an emote window for another chat.

![](https://i.imgur.com/HpbiBMs.png)
![](https://i.imgur.com/TOISBQA.gif)

**Comment by pajlada** [comment]
@wigoor running latest-ish nightly I'm assuming?

**Comment by wigoor** [comment]
Yes, and been having this problem for months, have tried to reinstall, problem persists

**Comment by pajlada** [comment]
Will test it out next time I'm on Windows

**Comment by pajlada** [comment]
I can't reproduce this
Your operating system is Windows 10, and you're not running any special software that messes with window or desktop management?
