### ISSUE TITLE
Opening emote menu, slow first time

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1028]
The first time you open an emote menu it takes a few seconds for it to load in, this started when emojis were made to load instantly instead of when you pressed the emoji menu.

![](https://i.imgur.com/K88xebl.gif)

**Comment by alazymeme** [comment]
I think this was fixed at some point, just can't find the PR. Are you able to still reproduce this on the latest nightly?

**Comment by apa420** [comment]
This has been fixed in the latest nightly and normal version as well I think.
