### ISSUE TITLE
Bits on twitch not showing in chatterino

### ISSUE THREAD

**Issue by TheSigge989** [Chatterino/chatterino2#1031]
I have seen alot of pepole do cheer15 for example but i cant see the bit animation/gif in chatterino.

**Comment by RAnders00** [comment]
Relevant documentation from twitch:

https://dev.twitch.tv/docs/irc/tags/#privmsg-twitch-tags

https://dev.twitch.tv/docs/v5/reference/bits/#get-cheermotes
