### ISSUE TITLE
Vip button

### ISSUE THREAD

**Issue by Patiro2** [Chatterino/chatterino2#1035]
I think that making a vip button just like the mod/unmod button would be really good. There is even some place to the rigth of mod/unmod buttons.
![image](https://user-images.githubusercontent.com/26751657/56855927-7273c280-6950-11e9-8c93-662dfe7aaa8d.png)

**Comment by TranRed** [comment]
I personally think Ban/Unban Mod/Unmod and VIP/unVIP should become only one button each, displaying the new state they will toggle when pressed.
