### ISSUE TITLE
Feature Request: Hide messages containing mentions of other users

### ISSUE THREAD

**Issue by devthena** [Chatterino/chatterino2#1040]
It would be nice to have an option to hide messages that contains @ mentions of users that are not me -- this is for the situation where some people start their own conversation by @-ing each other and I want to ignore it, then it would be easier if I can hide it.

**Comment by apa420** [comment]
If you have a big brain (unlike me) you can probably figure out a regex that will do that.

**Comment by RAnders00** [comment]
Here's some regexes that might work well for you:

https://regex101.com/r/b0QHUi/1

Or if you only want the start of the message: https://regex101.com/r/zuP8uQ/1

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
