### ISSUE TITLE
Linux AppImage Package

### ISSUE THREAD

**Issue by Prikith** [Chatterino/chatterino2#1042]
It would be nice to have a universal package of Chatterino using AppImage and having it automatically compiled and packaged.

This would be nice so that you don't have to compile it on every system you want to use it on.

Something like [OpenBuildService](https://openbuildservice.org/) or the publicly hosted version [openSUSE Build Service](https://build.opensuse.org/) could be used.

**Comment by notheowner** [comment]
I believe this issue can be closed since we have automatic AppImage Packages now.
https://github.com/Chatterino/chatterino2/releases

**Comment by Prikith** [comment]
correct although i would like to know how they are being built.
for now i'll go ahead and close this.
