### ISSUE TITLE
Extension not working on Mozilla Firefox

### ISSUE THREAD

**Issue by Megaaa1503** [Chatterino/chatterino2#1056]
I have just downloaded chatterino 2, I logged in, downloaded the extension on Firefox and it's not working. Instead of the chat in the channel, there is a message: "The extension could not connect to chatterino. Please focus the window or refresh the page." 
(I have chatterino open the whole time)
Already tried logging out, closing the app, opening it again and logging in and didn't worked.
![Screenshot_2](https://user-images.githubusercontent.com/50279022/57186043-8d918580-6eae-11e9-80a1-46703eac3668.png)

**Comment by notheowner** [comment]
#745

**Comment by fourtf** [comment]
should be fixed
