### ISSUE TITLE
explanation of a line of code, mutex

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#1061]
What does this mutex protect? I don't see any resources being protected by it https://github.com/fourtf/chatterino2/blob/411502de4430be3381f3658db9807cd2700037e8/src/controllers/commands/CommandController.cpp#L248

**Comment by RAnders00** [comment]
This is the commit that introduced the lock: https://github.com/fourtf/chatterino2/commit/71db0297b9a88cf1ac6b83967433cbffafe8e49b Seems useless even back then...

**Comment by fourtf** [comment]
it does nothing
