### ISSUE TITLE
Add an option to ban and timeout in the "ctrl+f" search box

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#1065]
in chat = https://i.imgur.com/fUhzGpV.png
in search box = https://i.imgur.com/Wj87AAY.png

**Comment by Robert123124** [comment]
I agree this would make it much easier to ban during streams

**Comment by fourtf** [comment]
I would prefer https://github.com/Chatterino/chatterino2/issues/1089 since it uses the moderation button settings
