### ISSUE TITLE
OSX contextual program menus lacks details

### ISSUE THREAD

**Issue by coral** [Chatterino/chatterino2#1077]
![Screenshot 2019-05-18 at 15 43 10](https://user-images.githubusercontent.com/2163363/57975722-ace6e300-7983-11e9-826c-03bf648da2a1.png)

should contain a link to program settings and the other good stuff.

**Comment by jammehcow** [comment]
Brainstorming here:

```
chatterino
  |-- About Chatterino
  |-- *separator*
  |-- Preferences
  |-- *default stuff added by macOS*

View
  |-- Zoom In
  |-- Zoom Out
  |-- Actual Size

Window:
  |-- Minimise
  |-- Zoom
  |-- *separator*
  |-- Bring all to front

Help
  |-- Chatterino Wiki
  |-- Chatterino GitHub
  |-- Chatterino Discord
```

I'm hesitant to add chatterino features like "New Split," "Close Tab" etc. for now unless someone has a good way to tie them to our keybinds in `Window.cpp` and be able to control context actions like "Cut," "Paste" where text fields don't exist.

**Comment by pajlada** [comment]
I think this is completed since #5266
