### ISSUE TITLE
Chatterino 2 crashes when adding and removing a Notification channel on OSX

### ISSUE THREAD

**Issue by coral** [Chatterino/chatterino2#1078]
recorded it here:

https://www.youtube.com/watch?v=_2Y8pTu7GZ0

**Comment by apa420** [comment]
Does this issue still occur?

**Comment by Murkur** [comment]
> Does this bug still occur?

I can confirm this bug still occurs and also happens when removing highlight phrases

**Comment by gempir** [comment]
Cannot reproduce on 6d5ba0c442681fb30afd01f787a10cd3922c10aa and Catalina 10.15.4
