### ISSUE TITLE
bump OSX c++ version to c++17

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#1082]
It's almost already past the half of year 2019, shouldnt OSX already have c++17?

(https://github.com/fourtf/appbase/blob/e6a31d5228ed8969596d6fdbd030f71a7a17f30d/appbase/main/main.pro#L23-L26)

**Comment by pajlada** [comment]
I have tried enabling C++17 on my MacBook Pro (Retina, 13-inch Early 2015) running macOS Mojave (10.14.4) and it works properly. It might not work on previous macOS versions (like High Sierra or Sierra), but we currently only provide automated Mojave builds

**Comment by Leppunen** [comment]
Chatterino2 runs on macOS High Sierra 10.13.6 with Xcode 10.1 using c++17 without issues.

**Comment by pajlada** [comment]
I made a PR to AppBase for this https://github.com/fourtf/appbase/pull/2

**Comment by hemirt** [comment]
fixed
