### ISSUE TITLE
Cyrylic etc. to latin alphabet conversion.

### ISSUE THREAD

**Issue by tolekk** [Chatterino/chatterino2#1084]
Add a feature so, when there are chinese, cyrylic etc. characters in chat, or when a user has them in their nickname, there's an option to display a phonetic translation into the latin alphabet.

**Comment by apa420** [comment]
How would that work, since certain combinations of characters can mean certaint phonetic sounds in comparison to if they were all single characters

**Comment by tolekk** [comment]
Exactly, there's got to be a database with phonetic sounds and how the different sounds are written down. It's just an idea that i thought of.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
