### ISSUE TITLE
Chatterino Browser Exstenstion

### ISSUE THREAD

**Issue by MozartWolfgang** [Chatterino/chatterino2#1086]
The Chatterino Browser Extension cant connect to the Chatterino thing and just gives the msg:

"The extension could not connect to chatterino.
Please focus the window or refresh the page."

and i have tried to Restart my browser and Chatterino to see if anything happened but it didnt do a thing

**Comment by Felanbird** [comment]
#745

**Comment by RAnders00** [comment]
fixed, see #745
