### ISSUE TITLE
Can't do moderation actions in the logpopup window

### ISSUE THREAD

**Issue by VulpesHD** [Chatterino/chatterino2#1089]
There are no moderation buttons when I open up someone's popup window in the search tab.
Usercards or online logs do not work here either.

![Screenshot_15](https://user-images.githubusercontent.com/28871321/58767548-09a1ea80-858d-11e9-8205-ceabcedd64e6.jpg)

**Comment by TranRed** [comment]
kinda duplicate of #1065

**Comment by fourtf** [comment]
duplicate of https://github.com/Chatterino/chatterino2/issues/550
