### ISSUE TITLE
[Bug] Emote preview & title area

### ISSUE THREAD

**Issue by savabozo** [Chatterino/chatterino2#1100]
Can speculate on what happens, but it will be easier to look at
<details>
  <summary>screenshot 1</summary>
  
![2019-06-16_16-59-37](https://user-images.githubusercontent.com/47025788/59564463-2d1e6800-9058-11e9-89fc-aa07860d8567.png)

</details>
<details>
  <summary>screenshot 2</summary>
  
![2019-06-16_17-00-50](https://user-images.githubusercontent.com/47025788/59564472-635be780-9058-11e9-8242-79e93421be7a.png)

</details>

Reproduction:
1. Any title of live streamer
2. Hover over emote at chat
3. Hover over title

**Comment by pajlada** [comment]
Thanks for the detailed issue post, I am able to reproduce and I'm pretty sure I know what causes this

**Comment by pajlada** [comment]
Fixed by #1108
