### ISSUE TITLE
[suggestion for a possible feature] minimize channels from view (add a button that would expand/minimize) for those who farm lots of subs but only watch a few people

### ISSUE THREAD

**Issue by hzah1** [Chatterino/chatterino2#1105]
:) hi i just had an idea for ur next update in chatterino. a feature that would allow u to minimize specific channels so you wouldnt see them in ur tab but they are still there in the backround and a button on maybe the top right that would expand & minimize it to what it is right now (for those who put alot of channels to farm gifted subs) mine currently takes up half the screen LUL

**Comment by apa420** [comment]
Chatterino is not made for sub gift farming channels.

**Comment by fourtf** [comment]
You can rename tabs if the name is too long.
