### ISSUE TITLE
Add /marker command (from twitch chat)

### ISSUE THREAD

**Issue by rexim** [Chatterino/chatterino2#1109]
Context: https://help.twitch.tv/s/article/creating-highlights-and-stream-markers?language=en_US#Add

### Steps to reproduce

- Go to a channel you own
- Start streaming
- Send `/marker` command 

### Observed

System message that says `Sorry, "/user" is not available through this client.`

![2019-06-22-220115_611x141_scrot](https://user-images.githubusercontent.com/165283/59965507-48e2ac00-9539-11e9-998f-b0738457a903.png)

### Expected

Stream marker is successfully added.

**Comment by pajlada** [comment]
This looks to be a response produced by Twitch through any third party client if that message is sent straight as-is. I tried connecting to irc with netcat and got the same response.
I'm assuming the Twitch chat client sends a pubsub message or something when the user types /marker, so /marker is actually never supposed to be sent to TMI

**Comment by pajlada** [comment]
Looks like there's an Helix API endpoint for this: https://dev.twitch.tv/docs/api/reference/#create-stream-marker
