### ISSUE TITLE
Add a keybinding for Clear messages

### ISSUE THREAD

**Issue by TJT811** [Chatterino/chatterino2#1110]
Adding the Chatterino Clear messages button as a keybind. I often clear a chat so I know where I left off or seeing a new message in /mentions when its clear is much better, its like my way to mark messages as read.

**Comment by pajlada** [comment]
There really needs to be some time spent looking into fully customizable hotkeys, especially for these "non-standard" actions

**Comment by fourtf** [comment]
closed into favor of https://github.com/Chatterino/chatterino2/issues/1592
