### ISSUE TITLE
Ping audio duration limit // Enhancement?

### ISSUE THREAD

**Issue by radva** [Chatterino/chatterino2#1112]
Few days ago I've put a song as my ping sound by accident.
I honestly don't know anything QML audio, but from research I found that you can get file info and duration with it. 
It would be great to put some kind of limit to duration of ping sounds.

![chatterino_PsljR3YjYj](https://user-images.githubusercontent.com/45208722/60087410-4355b380-973d-11e9-9057-7efeb4e0f472.png)

**Comment by RAnders00** [comment]
Could be a prompt when you set the custom audio file - "The audio file you selected is 5m20s long, do you really want to set this as your highlight sound?"

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
