### ISSUE TITLE
"Open in streamlink" not working on Windows 7

### ISSUE THREAD

**Issue by bapsaru** [Chatterino/chatterino2#1114]
chatterino: fe69dfb
streamlink: [1.1.1+32.gb146deb](https://github.com/streamlink/streamlink/issues/2402#issuecomment-480455258)
mpv: [0.29.0-341-gc9e7473d67](https://sourceforge.net/projects/mpv-player-windows/files/)
os: Windows 7 Pro 64 bit

expectation:
1. select a channel, click "Open in streamlink"
2. select quality unless configured default
3. mpv starts with stream

reality:
1. select a channel, click "Open in streamlink"
2. select quality unless configured default
3. nothing at all, no error

tested:
1. streamlink (official & low latency) using cmd; working as expected
2. streamlink using [streamlink-twitch-gui;](https://github.com/streamlink/streamlink-twitch-gui/releases/tag/v1.7.1) working as expected
3. streamlink using chatterino2 in Windows 10 Pro 64 bit; working as expected
4. streamlink (official & low latency) using chatterino2; not working

notes:
this is the second windows 7 install i'm on where this is an issue,
attached mpv and streamlink config files below
[bapsaru-config.zip](https://github.com/Chatterino/chatterino2/files/3332477/bapsaru-config.zip)

**Comment by pajlada** [comment]
More information potentially found for debugging in #860 
Thanks for the detailed report!

**Comment by Mm2PL** [comment]
Windows 7 is not supported anymore
