### ISSUE TITLE
Emote rendering discrepancy between chatterino and webchat

### ISSUE THREAD

**Issue by rexim** [Chatterino/chatterino2#1115]
Not sure if a duplicate, but I have no idea how to check (the wording of other related issues may be completely different, so it's hard to find).

### Steps to reproduce

1. Open vanilla webchat
1. Send `Kappa.png`
1. Observe `Kappa.png` is sent and displayed as a text.

![2019-06-28-205408_403x146_scrot](https://user-images.githubusercontent.com/165283/60347183-f72d9c00-99e6-11e9-8191-0b5054dd102f.png)
![2019-06-28-205419_409x144_scrot](https://user-images.githubusercontent.com/165283/60347188-f85ec900-99e6-11e9-94b7-20abb0ccc98d.png)

1. Open Chatterino
1. Send `Kappa.png`
1. Observe the ![kappa](https://static-cdn.jtvnw.net/emoticons/v1/25/1.0) emote image without any `.png` suffix.

![2019-06-28-204417_522x85_scrot](https://user-images.githubusercontent.com/165283/60347043-b0d83d00-99e6-11e9-8771-9e6566d63b9b.png)
![2019-06-28-204430_386x117_scrot](https://user-images.githubusercontent.com/165283/60347046-b2a20080-99e6-11e9-954d-469adbf7fdb7.png)

### Expected behavior

I guess it should be more or less compliant with the webchat behavior.

**Comment by RAnders00** [comment]
So this came up again today, finding great amounts of abuse, because apparently highlights are parsed before this parsing corner case occurs (the `.png` being removed). Messages like `Kappa.fourtf` Would show up as just the emote in chat (no `.fourtf` suffix), but would highlight the message for fourtf.

**Comment by fourtf** [comment]
Was fixed in a committi https://github.com/Chatterino/chatterino2/commit/84b1efcd242565283c03d8f67f11983f4fb5f1e6
