### ISSUE TITLE
Allow Sending Duplicate Messages Doesn't Seem to Work

### ISSUE THREAD

**Issue by slovakid** [Chatterino/chatterino2#1119]
I've looked around the github and can't find anything recent. I have the option enabled but it doesn't seem to work, it keeps coming up with "Your message was not sent because it is identical to the previous one you sent, less than 30 seconds ago." I've tried adding a space at the end of the message like it says but still doesn't seem to work. 
Thanks.

**Comment by Felanbird** [comment]
Chatterino doesn't technically add a "space" to the end of a message, it adds an invisible character. 
A month or two ago twitch messed with the invisible character Chatterino used to send duplicate messages, so all versions of Chatterino before GH-1021 cannot spam. 
Updating to the newest nightly will fix your issue https://github.com/Chatterino/chatterino2/releases/tag/nightly-build 👍

**Comment by slovakid** [comment]
> Chatterino doesn't technically add a "space" to the end of a message, it adds an invisible character.
> A month or two ago twitch messed with the invisible character Chatterino used to send duplicate messages, so all versions of Chatterino before [GH-1021](https://github.com/Chatterino/chatterino2/pull/1021) cannot spam.
> Updating to the newest nightly will fix your issue https://github.com/Chatterino/chatterino2/releases/tag/nightly-build 👍

Thank you, its working now.
