### ISSUE TITLE
[Feature Request][Tabs] Stream info on hover over tab

### ISSUE THREAD

**Issue by savabozo** [Chatterino/chatterino2#1124]
In short, copy/paste onHover on chat header to tab.

In long.
1. I can see stream title, game, viewers, uptime, etc on hover on chat header of stream that is live. 
2. I have an option turned on "Show live inicator in tabs".
3. I want to see stream info on the "live tabs".

**Comment by savabozo** [comment]
I dont care but /should be answered before implementing questions/:

-  As included with "Show live inicator in tabs" or separate checkbox in options?
-  If multiple chats in 1 tab - show info for each with separator or only for the first one?

**Comment by pajlada** [comment]
How do you envision this working with tabs where multiple streams are live?

**Comment by savabozo** [comment]
Vertical stack of existing live notification.
In a shared backdrop.
With streamer name added though.
As much as will fit vertically, could go outside the screen.

* Previously wrote about first livestream only - dont think its a correct thing though.

**Comment by alazymeme** [comment]
Would you say this is somewhat fixed by the `Chat title` option in the settings? 
![image](https://user-images.githubusercontent.com/12804673/83132219-6a262200-a124-11ea-8715-9105e6942408.png)

**Comment by apa420** [comment]
No, this is for the tabs. Not splitheaders.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project. You can check it for individual channels but this will not be added for tabs.
