### ISSUE TITLE
Add UI control to open settings directory

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1129]
This would be easier than guiding users to enter ` %APPDATA%/Chatterino2/Settings` into their windows explorer address bar + it's compatible with all platforms automatically and can reflect special cases such as portable installations.

(similar to how the `Open Resource packs folder` button works in Minecraft, it launches `explorer.exe` on the directory)

**Comment by pajlada** [comment]
This could also easily respect the users portable settings, since it should know exactly what folder to open. :+1:

**Comment by fourtf** [comment]
This was added
