### ISSUE TITLE
Completely pause chat while hovering whenever the mouse is over the chat.

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#1130]
without having to move the mouse to pause the chat

**Comment by Dolev24** [comment]
Or just add keybind to pause chat

**Comment by fourtf** [comment]
available in nightly

**Comment by Dolev24** [comment]
Yeah, but you have to move your mouse for it to pause, i think a better
idea would be to add a bind that stops the chat, just like twitch added
recently for mods

‫בתאריך יום ב׳, 29 ביולי 2019 ב-20:11 מאת ‪fourtf‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by fourtf** [comment]
it is fixed
