### ISSUE TITLE
Sidebar highlighting

### ISSUE THREAD

**Issue by riizm** [Chatterino/chatterino2#1132]
The colored highlights on the scroll bar are 1 pixel tall for subs and mentions which can get annoying when looking for a mention after being AFK or something. Maybe a color changing and size changing option for sub notifications, mentions, and whispers could make things a little cleaner.

The top 3 highlights are mentions and the bottom 2 are sub notifications. 
![Capture](https://user-images.githubusercontent.com/52833288/61144215-4a512580-a4a2-11e9-918f-c74c2277f7f0.PNG)

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project. We will not add cosmetic settings for this.
