### ISSUE TITLE
Mod, VIP and other hardcoded badges are not high-DPI

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1138]
See for example:

VIP and mod for example are blurry-ish at high DPI:
![image](https://user-images.githubusercontent.com/1629196/61184241-b327d180-a64b-11e9-90a2-fa90cb9aa18a.png)
![image](https://user-images.githubusercontent.com/1629196/61184248-cb97ec00-a64b-11e9-8176-e0ebc18d1044.png)
compare for example the sharpness of the sub emote and bits one vs the VIP one:
![image](https://user-images.githubusercontent.com/1629196/61184258-fc782100-a64b-11e9-8a87-d189103ba46f.png)

The twitch badges API even offers a SVG version if that can be implemented.

**Comment by pajlada** [comment]
This was fixed in https://github.com/Chatterino/chatterino2/commit/bcc53c9aa7966baa9051feda0aaee6458d8ab73c
