### ISSUE TITLE
Unable to select emotes in the emote picker window

### ISSUE THREAD

**Issue by andred44** [Chatterino/chatterino2#1142]
Sometimes the emote picker window will spawn with a vertical and/or horizontal resize cursor and emotes aren't able to be selected, it's only able to resize the window and scroll, the window buttons are also unclickable

![example](https://andred.s-ul.eu/0JlyL62e.gif)

**Comment by pajlada** [comment]
Are you using the latest version of Chatterino 2 nightly downloaded from https://github.com/Chatterino/chatterino2/releases/tag/nightly-build?

**Comment by andred44** [comment]
Yes, the latest version at the time of posting the issue.

**Comment by alazymeme** [comment]
Is this still reproduceable?

**Comment by Mm2PL** [comment]
Unable to reproduce on Linux on ch2 `Chatterino 2.1.7 (commit d9aab1f6e)`

**Comment by alazymeme** [comment]
Also unable to reproduce on Windows 10 Chatterino Nightly 2.1.7 (commit 6d5ba0c44, 24.05.2020)

**Comment by andred44** [comment]
It was an issue on 2.0.4 4e4c7d4

**Comment by alazymeme** [comment]
Ok, but is it an issue in 2.1.7?

**Comment by andred44** [comment]
I haven’t had the issue occur on 2.1.7 so probably not.

**Comment by pajlada** [comment]
Thanks for the update @andred44 - please let us know in this issue if it still occurs :slightly_smiling_face:
