### ISSUE TITLE
Enhance /user to be able to show the Chatterino 2 Usercard

### ISSUE THREAD

**Issue by TranRed** [Chatterino/chatterino2#1143]
There should be an option to open the Chatterino 2 Usercard without clicking a user name.
My suggestion would be to enhance /user by a parameter i.e. ```-ch```
Alternatively make a new command like /chuser or /ch2user or similar.

Idea by dyeoxyde on discord:
![grafik](https://user-images.githubusercontent.com/16636423/61284056-7b8d6680-a7be-11e9-9b93-b6547b72b76f.png)

**Comment by Mm2PL** [comment]
I'm in the process of making this a reality :)
