### ISSUE TITLE
Ascii art display issue

### ISSUE THREAD

**Issue by helppluk000** [Chatterino/chatterino2#1146]
For some reason, in chatterino 2.0.4 nightly, with default font size (12) and default ui size (1.0) and same width as twitch chat (it'd be 340 but that's not a setting i can change in chatterino, but I did drag it to same width visually), ascii arts only show up properly up to a width of 26 while regular twitch chat with default font size (12) ,default chat width (340), and default settings can show asciis up to width 33 properly.

To see asciis form width 26 to 33 width would require resizing the chatterino window width or changing font size or ui size settings, and i'd want chatterino to display those correctly without needing to do so.

Example 26 width ascii: ⣴⣿⢿⣛⣯⣭⣭⣭⣝⣛⢿⢶⣿⣿⣿⣿⣟⣛⡛⠦⠄⠄⠄⠄⠄⠄
⣿⣿⣿⣿⣿⣿⡿⠯⠽⠿⠧⢺⢏⣽⣋⢝⢭⠉⠙⠥⡶⠄⠄⠄⠄⠄
⣽⣿⣿⣿⣯⠶⣚⣛⣿⣟⣛⡌⣎⢿⡫⠷⢶⡤⠄⣠⣤⡌⣭⣂⠄⠄
⣿⣿⣿⣿⣿⡯⢉⠩⠅⢀⣢⣴⡽⠮⢿⣷⣒⣮⣵⡿⢟⣁⢭⣿⣷⣄
⣿⠿⣮⡿⠋⣀⣴⡷⠯⢝⣻⡿⢸⣽⣷⠿⣉⣩⣥⣶⠶⠶⣒⠄⠙⣿
⣿⣿⣽⣥⣾⣠⣿⣟⣻⣭⡵⢊⣪⣵⡶⠟⣛⡋⢵⣦⡙⣷⡌⠄⠄⢹
⣿⢿⣿⣿⣶⣪⣭⡍⠭⣢⡾⠟⣋⡅⢶⣬⠻⣿⣆⢻⠿⠘⣃⠄⠄⣎
⡏⣾⣿⣟⣧⡿⢾⠇⣚⣍⢲⣧⡙⣿⡆⠿⣓⡨⣥⣦⢾⣷⢹⢰⡇⣿
⣿⣿⣿⡇⣿⣧⡜⣆⠙⢿⣦⠛⣣⡱⣾⣆⢻⣇⢻⣿⡎⠿⠎⣾⣼⣿
⣿⣿⣿⣷⡈⠿⣷⣝⣷⣤⡔⠧⢻⣇⣹⠿⠌⣛⣪⣭⡶⢟⣼⣿⣿⣿
⣿⣿⣿⣿⣿⣦⣈⡻⠿⠿⠿⣷⣦⣔⣒⣛⣻⣯⣽⣷⣾⣿⣿⣿⣿⡿
⣭⣛⠿⢿⣿⣿⣿⣿⣿⣿⣿⣶⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⣛⣭⢱⣾

Example 33 width ascii: ⣴⣾⣿⡿⠟⣋⣭⣭⣭⣭⣛⡛⢿⣿⣧⣾⣿⣿⣿⣿⠿⠿⠿⠿⢦⠄⠄⠄⠄⠄⠄⠄⠄
⣿⣿⣷⣾⣿⣿⣿⣿⣿⣿⣻⣿⣷⡜⢵⣿⢟⣿⠿⣻⠿⣛⣛⣻⠦⣀⠄⠄⠄⠄⠄⠄⠄
⠿⣿⣿⣿⣿⣿⢟⣛⣭⣭⣤⣤⣤⣬⠸⢣⣿⣷⣾⠔⣋⣂⠄⠈⠙⠙⠙⠣⠤⡄⠄⠄⠄
⣾⣿⣿⣿⣿⡿⣛⣫⣭⣶⣶⠶⠶⣿⡗⣯⡜⣻⣵⡟⠿⠮⣓⡢⣴⣿⣶⠇⣶⣧⣄⠄⠄
⣿⣿⣿⣿⣿⣿⣿⠟⡀⠤⠒⠄⣈⣡⣾⡎⠿⠶⢿⣿⣛⣭⣥⣶⣿⠿⣋⣀⠦⡿⣿⣿⣆
⣿⣭⡥⢭⣿⠟⠄⣀⣴⣷⣟⡫⠝⣿⣿⡂⣭⣽⣿⣭⠭⢍⣉⣡⣤⣤⡤⠶⠆⠈⠘⢻⣿
⣿⣷⣞⣿⠁⣴⠏⢹⣿⣷⡶⠶⢛⣫⡅⠰⢛⣫⣭⣶⣾⡿⢛⣉⣩⠰⣶⣧⠙⡆⠄⠄⢻
⣿⣿⣿⣿⣯⣙⡲⠿⠿⠿⠾⠿⠛⣡⣴⣾⡿⠟⣋⠱⣶⣿⣦⠉⣿⣷⡈⢿⡇⠇⠄⢀⢸
⣿⢏⣿⣿⣿⣿⢫⣿⣿⠇⢝⣥⡾⠟⡋⢥⣶⡌⢻⣷⣄⠻⣿⡷⠘⠛⣛⡈⣭⡀⢀⠄⣧
⡟⢸⣿⣿⡟⣭⣿⢣⣿⠄⣫⣵⡄⢻⣿⡌⢻⣿⡆⠛⣛⣠⠱⣶⣶⡘⣿⣧⢻⡇⣾⢠⣿
⣿⣾⣿⣿⡇⣿⣿⣤⠹⣆⠙⢿⣿⣎⠻⠟⡈⢵⣾⣆⠹⣿⡇⢿⣿⣷⢹⣿⠞⣸⣧⣼⣿
⣿⣿⣿⣿⣧⠙⢿⣿⣦⢿⣦⣀⣛⠥⣆⢻⣿⡈⢿⣿⣆⢿⠿⠸⢛⣫⣬⡶⣠⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣷⣄⠙⢿⣷⣿⣿⣿⣧⣍⠘⣛⣓⣺⣭⣭⣴⣶⡿⢟⣛⣭⣶⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣶⣤⣉⣉⣉⣛⣛⠿⢿⣶⣶⣾⣷⣶⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⡿⢋
⣮⣍⣛⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⢟⣋⣥⡄⣾⣿

Here is the website i used to convert pictures to asciis: https://505e06b2.github.io/Image-to-Braille/

Here's the example picture i was using: https://imgur.com/NMJq9mC

**Comment by fourtf** [comment]
Font rendering can unfortunately not be changed 😞
