### ISSUE TITLE
/mentions not working

### ISSUE THREAD

**Issue by 8right** [Chatterino/chatterino2#1148]
nothing is showing up in mentions when i get @ on any channel. please help

**Comment by TranRed** [comment]
Did you by any chance uncheck this option in the settings?
![grafik](https://user-images.githubusercontent.com/16636423/61359753-472caf80-a87d-11e9-8ef2-431f847fb10c.png)

**Comment by 8right** [comment]
no i dont have that unchecked.
![2a470de96d40635a912f98490675b6a8](https://user-images.githubusercontent.com/52980518/61364372-0c506900-a8c9-11e9-9e54-3ae6b05b4ac7.png)

**Comment by 8right** [comment]
pls help. really was keen on using chatterino but /mentions dont work on either chatterino (1 & 2)

**Comment by TranRed** [comment]
There is an Issue about problems with names containing underscores. See #362
Maybe you have an similar problem.

Or are we maybe talking about a localized name? I honestly do not know if they are working currently.
Would be nice to have more information about the specific case, since it seems to work for most people.

**Comment by Felanbird** [comment]
As @TranRed stated if you have a localized name, the "Your username (automatic)" phrase could be using your localized name. Even if you don't have a a localized name, try adding your username manually below the two default phrases you already have.

**Comment by 8right** [comment]
@TranRed my name is the same as it is here and I'm not sure what you mean by localized name?

@Felanbird i added my name underneath and got my friend to @ me in chat and still nothing.
![0e9bd1926d4b49fd48942ac2f2e274f1](https://user-images.githubusercontent.com/52980518/61441846-cb6c5900-a989-11e9-9fe0-2183c82ef566.png)

**Comment by TranRed** [comment]
Works fine for me:
![grafik](https://user-images.githubusercontent.com/16636423/61442380-cab2d300-a947-11e9-9dff-f1526dafbda0.png)

![grafik](https://user-images.githubusercontent.com/16636423/61442470-fafa7180-a947-11e9-8bad-bb1f62cd9854.png)

**Comment by 8right** [comment]
should i take off enable regex? i might have to just reinstall, will see how i go and let you know

**Comment by 8right** [comment]
i managed to get it to work, i added my name into the users and that seemed to fix it.
