### ISSUE TITLE
FrankerFaceZ - Support "Featured channel" emotes

### ISSUE THREAD

**Issue by Trung0246** [Chatterino/chatterino2#1150]
Currently the channel that's have FFZ featured emotes is [ESAMarathon](https://twitch.tv/esamarathon)

Example: [Image 1](https://i.imgur.com/k75TZNe.png), [Image 2](https://i.imgur.com/YgWE90v.png)

Comparing emotes menu (currently on Window 10 1803):

- [Chrome 75.0.3770.142 with FFZ (1.57) + FFZ:AP (3.1.1) installed](https://i.imgur.com/avCQ1Gv.png)
    - [Different runner](https://i.imgur.com/wz8jIxu.png)
- [Chatterino Beta 2.0.4](https://i.imgur.com/8dfbl2R.png)
- [Chatterino Nightly 2.0.4 3ef77f4-1](https://i.imgur.com/f2kACAZ.png) (download from [here](https://i.imgur.com/5r5hkyH.png))

I had tried "Reload Channel Emotes", "Manual reconnect", created new tabs, closing the Chatterino window and open again; but nothing worked.

P.S: ESA mods often live update featured FFZ emotes for current runner's stream emote without warning, is it possible to know when its time to update emotes list?

**Comment by pajlada** [comment]
It looks like the FrankerFaceZ makes a websocket connection when joining a channel, which spits out a "follow_sets" command, that instructs the extension to also load emotes from the other streamer.

Do you know how ESA mods go about updating featured FFZ emotes for current runner's stream?

**Comment by Trung0246** [comment]
Probably they ran a command (starts with ! ), I saw they did that once before, but unsure if that would be true.

**Comment by pajlada** [comment]
Thanks, will try to follow up with FFZ people to see what this feature is and how/if we can support it

**Comment by pajlada** [comment]
Got help from some FFZ people, and with a bit of investigating the protocol seems really straight forward.

Messages are structured like this:
`nonce command arguments`
**nonce** is a signed integer
**command** is a string command
**arguments** is a JSON value (e.g. `["chatterino", "test"]` or `{"randers":["lol"]}`)

1. Connect with a WebSocket client to a random endpoint from https://github.com/FrankerFaceZ/FrankerFaceZ/blob/21ee6fcfb7e5ab843c5052dddac587177bb18a2f/src/utilities/constants.js#L70
1. Send the **hello** command with a string array as arguments. The string array should contain two string values. First value is the version of our app (we'd send chatterino-2.0.4-dfkjghjsg). Second value is our Client ID. We would most likely just randomize a UUID and send this all the time.
1. Send the **ready** command, with a number as the argument. I think this should just be 0. Not sure what it means
1. Subscribe to channels we're interested in. Command is **sub**, arguments is a string in the form of "room.pajlada" (replacing pajlada with the channel name you're interested in)
1. You will now receive messages about what extra emote sets can be used in this channel. Nonce will be -1, command will be **follow_sets**, arguments will be a JSON object. The JSON object (`map<string, vector<string>>`). The value of the member is a list of what extra emote sets to load.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
