### ISSUE TITLE
Badge scaling is broken for HI-DPI screen for different 2.0.4 versions

### ISSUE THREAD

**Issue by Trung0246** [Chatterino/chatterino2#1151]
Assuming both programs shared same configuration (in this case both are opened on same computer and have UI scaling changed to x0.5)
![2019-07-20 16_27_44-chatterino](https://user-images.githubusercontent.com/11626920/61585212-71939c80-ab0b-11e9-9df6-264104ba749a.png)
![CYz3Y2B](https://user-images.githubusercontent.com/11626920/61585214-735d6000-ab0b-11e9-9afc-170db56c7a3d.png)
![eBEHGRy](https://user-images.githubusercontent.com/11626920/61585193-22e60280-ab0b-11e9-8eee-9dbdc336b879.png)

**Comment by pajlada** [comment]
Badges were recently removed from the "emote" tag, which caused this behaviour to change.
Would a separate slider for "Badge scale" suit your needs?

Somewhat related issue: some badges aren't high-dpi https://github.com/Chatterino/chatterino2/issues/1138

**Comment by Trung0246** [comment]
Could work I think

**Comment by pajlada** [comment]
After further investigation, badges should just scale to be the same size as the username, which they are if your UI scale and font size are certain values, but not with yours (0.5x UI scale and 20pt font size)

**Comment by Trung0246** [comment]
So with my understanding from reading your comments: is there some settings I changed in the program that caused this?

If so I could send my config.

**Comment by pajlada** [comment]
You have your UI scale set low, and font size set high. that combination just causes the badges to not be the same size as the emotes. I consider this a bug

**Comment by fourtf** [comment]
I would imagine this is fixed now
