### ISSUE TITLE
Ghosting issues with emote preview

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#1154]
The current implementation did not find a way to resolve this issue, that I had with my implementation, due to which i scrapped it. (Took a look and it is implemented the same way, except gifs are different.)

Old tooltip sticks and ghosts the new one for a tick before it changes to new one.

**Comment by pajlada** [comment]
oh yeah, I see that now. my old man eyes must not have noticed that at first

**Comment by hemirt** [comment]
still exists

**Comment by fourtf** [comment]
I don't understand what this means but if it's the popup jumping around then that was fixed
