### ISSUE TITLE
Timestamps in selected channels

### ISSUE THREAD

**Issue by Zanuh** [Chatterino/chatterino2#1158]
It is possible to enable/disable timestamps in Chatterino 2. However, I would like to be able to have timestamps automatically in some channels that has fewer chatters, etc. I would like to have a setting where you could enable timestamps on specific channel(s) while other channels doesn't get it enabled. Currently now you can just disable/enable it for either all channels or none.

**Comment by savabozo** [comment]
#1016

**Comment by RAnders00** [comment]
Closing in favour of #1016, I posted your wanted solution in the conversation over there
