### ISSUE TITLE
Highlight matching is applied before ignores are applied

### ISSUE THREAD

**Issue by juanfra684** [Chatterino/chatterino2#1160]
I've always open "mentions" and a few tabs with channels. One of that channels has a command which send a message to a randomly selected user. The message is something like "something something mynick". The "user" who sends the message is streamelements, so I don't want to ignore the user.

I've the phrase in "Ignores/Phrases" and the text is replaced correctly, however the (now empty) message is still highlighted in the channel and in the mentions. I would like ignore this message and keep it out of "mentions" or any kind of highlighted text.

Any idea?. Thanks for the software, it's really great.

**Comment by RAnders00** [comment]
Can confirm this issue. Highlight matching is applied before ignores are applied.

Maybe you could edit the issue with the title "Highlight matching is applied before ignores are applied" @juanfra684 ? Makes it easier to search for this issue.
