### ISSUE TITLE
Some channel-specific notices are shown in all channels.

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1163]
E.g:

```
user> /w forsen test
(in all channels): That user's settings prevent them from receiving this whisper.
```

That notice should only appear in the channel where the whisper was sent i think?

**Comment by RAnders00** [comment]
Also affects the `This room is in subscribers only mode. To talk, purchase a channel subscription at https://www.twitch.tv/products/jtv/ticket?ref=subscriber_only_mode_chat` notice

**Comment by RAnders00** [comment]
also this is a bug not an enhancement in my opinion since the underlying IRC command specifies a channel, even for the whisper notice originally reported

```
@msg-id=whisper_restricted_recipient :tmi.twitch.tv NOTICE #testchannel :That user's settings prevent them from receiving this whisper.
```

I suppose it gets harder when whispers are sent in the `/whispers` split, and re-routing the message from whatever channel it really goes to to the `/whispers` split would be an `enhancement`.

**Comment by Mm2PL** [comment]
> Also affects the `This room is in subscribers only mode. To talk, purchase a channel subscription at https://www.twitch.tv/products/jtv/ticket?ref=subscriber_only_mode_chat` notice

This happens only with the `#jtv` channel. A comment in the code mentions that `NOTICE #jtv` is a global notice, is that still the case?

**Comment by jupjohn** [comment]
Retested post #4052 merge, whisper failures now only show in the channel they were sent from. Subscriber mode is also per-channel. If there aren't any other cases we can think of, this issue could probably be closed :+1:

**Comment by Felanbird** [comment]
Tested both whispers and subscribers and as mentioned the error is only printed in the correct channel :+1:
