### ISSUE TITLE
Unable to send whispers

### ISSUE THREAD

**Issue by rezow** [Chatterino/chatterino2#1165]
When sending a whisper I get the message: "Your settings prevent you from sending this whisper." The account I'm sending to doesn't block whispers. I'm using v2.0.4 and my twitch username is rezowx.

**Comment by pajlada** [comment]
I would guess it's still related to https://discuss.dev.twitch.tv/t/unable-to-have-my-bot-send-whispers/21120 - I see your account is less than a day old. I'd say just wait a bit and maybe you can whisper soon?

**Comment by rezow** [comment]
I have another account that's a week old and I still can't send whispers with that account. When you had this problem, was waiting the solution?

**Comment by RAnders00** [comment]
@rezow Is your email verified?

**Comment by fourtf** [comment]
Seems to be related to twitch and not chatterino
