### ISSUE TITLE
'Always on Top' not working as it should

### ISSUE THREAD

**Issue by akumar95** [Chatterino/chatterino2#1166]
Hello,

On macOS Mojave I have installed the latest version of Chatterino2. Upon selecting the option 'Always on Top', I notice when clicking away the program does not float as it should. When using Chatty and selecting 'Float on Top', it works as it should and floats on every window that is being used. Any ideas?

Thank you.

**Comment by fourtf** [comment]
Have you restarted Chatterino?

**Comment by akumar95** [comment]
Oh of course, plenty of times.

**Comment by alazymeme** [comment]
Is this still reproducible?

**Comment by gempir** [comment]
Yup. Doesn't work. Window goes in the background

Confirmed on  6d5ba0c442681fb30afd01f787a10cd3922c10aa and Catalina 10.15.4

**Comment by dnsge** [comment]
This feature only works on Windows:
https://github.com/Chatterino/chatterino2/blob/a230bc7c8980ba190c3091539100c358dfb39a25/src/widgets/BaseWindow.cpp#L201-L216

**Comment by fourtf** [comment]
> This feature only works on Windows:
> 
> https://github.com/Chatterino/chatterino2/blob/a230bc7c8980ba190c3091539100c358dfb39a25/src/widgets/BaseWindow.cpp#L201-L216

Uncommenting the code below that might fix it

**Comment by ErikAGriffin** [comment]
Hi, @pajlada I have the "Always on Top" setting on, running Mac OS Catalina 10.15.6, but it's still getting put behind other windows.  I've enabled the setting, restarted Chatterino, and it's not working at all it seems

**Comment by dnsge** [comment]
@ErikAGriffin Are you using the nightly build? "Always on Top" works for me on macOS 10.15.6 on nightly.
