### ISSUE TITLE
Fast emote search with ":"

### ISSUE THREAD

**Issue by Qureneko** [Chatterino/chatterino2#1168]
this search function that gets triggered by ":" in the beginning.
![Screenshot_4](https://user-images.githubusercontent.com/40634631/62042482-e0a57b00-b206-11e9-9165-8b6442ca605c.png)

**Comment by Qureneko** [comment]
and for "@" users too. Not tab. Arrows+enter

**Comment by fourtf** [comment]
Duplicate of #591
