### ISSUE TITLE
Get chat suggestions when writing

### ISSUE THREAD

**Issue by OlemcDEV** [Chatterino/chatterino2#1171]
Say you @ someone in chat. Make it show up a list of potential names you are trying to @.
@g gives you a list of all usernames that starts with g. Tabbing is a feature, but it's not as good as a list sometimes.

Also
You should also be able to get a list of emotes you are trying to write whenever u do ":" before the emote.
F.example:
:t shows trihard

These are both features the standard twitch chat has, that also would be nice to see in chatterino 2.0.4 👍 Hope what i said was understandable and likable.

**Comment by pajlada** [comment]
The : emote completion method is already suggested in #591 
#375 kind of implies the similar kind of list, except for emotes only and when pressing a key, but it could definitely be expandable once implemented to support your specific use case.
Will close this issue as a duplicate, but please keep an eye out on the issues listed above.
