### ISSUE TITLE
Any chance of adding Mixer?

### ISSUE THREAD

**Issue by omperus** [Chatterino/chatterino2#1177]
Hey, i was wondering if it could be possible to add mixer to the program? I would greatly appreciate it, thanks.

**Comment by oldLucke** [comment]
adding this feature is not trivial, because Mixer doesn't use IRC like twitch does.

**Comment by omperus** [comment]
> 
> 
> adding this feature is not trivial, because Mixer doesn't use IRC like twitch does.

But Mixer does have an API for this doesn't it?

**Comment by oldLucke** [comment]
It does and it's well documented, but still they are using WebSocket not IRC. It still some work to implement that and make it work with other features like BTTV / FFZ emotes. If no one is willing to do that work or if @fourtf or @pajlada say the don't want this, this feature will not come.

**Comment by omperus** [comment]
> 
> 
> It does and it's well documented, but still they are using WebSocket not IRC. It still some work to implement that and make it work with other features like BTTV / FFZ emotes. If no one is willing to do that work or if @fourtf or @pajlada say the don't want this, this feature will not come.

And why are you saying all of this if you are not a contributor to the project? Whats the point of stating the obvious?

**Comment by oldLucke** [comment]
Because the people who do contribute to this project have strong bias to twitch. At the current time I personal don't believe this feature will be added, so don't get you hope up.

**Comment by hemirt** [comment]
There is (was?) a structural division for "providers" (e.g. TwitchChannel inheriting from Channel), but I don't know if it could be used to "reuse" already written parts of the program, and just implementing the messages receiving/sending.

Would be nice to be able to use more providers, be it mixer, dlive, or custom irc servers.

**Comment by apa420** [comment]
Will close this since Mixer has shut down operations.
