### ISSUE TITLE
Some twitch emotes not being displayed in latest nightly

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1182]
For reference, I'm running commit c578cd47e12a0292918e369086c176b4f79a413a

For example:

![image](https://user-images.githubusercontent.com/1629196/62425778-79dc0200-b6dd-11e9-92ff-242a9b23ae31.png)

![image](https://user-images.githubusercontent.com/1629196/62425782-806a7980-b6dd-11e9-8294-24c33464c4c5.png)

![image](https://user-images.githubusercontent.com/1629196/62425814-d3dcc780-b6dd-11e9-9e98-6f89aa4a0486.png)

I'm not sure what the common denominator is between all the missing emotes, although I know i haven't seen it happen with ffz or bttv emotes.

**Comment by andred44** [comment]
same issue here, although I've also noticed ffz/bttv emotes only appear as text a lot more now than before. F5 seems to only refresh ffz/bttv emotes for the selected channel instead of all channels.

some subscriber emotes aren't appearing at all after refreshing as well
![imageimageimageweewooweewoo](https://andred.s-ul.eu/gze8VvYO.png)

**Comment by TurtleCatt** [comment]
![chatterino issue picture](https://user-images.githubusercontent.com/50277020/62461216-2952bc00-b752-11e9-9db6-93bbb88d45cf.png) I'm having the same issues.

**Comment by Strencher** [comment]
same issue here.. 
![image](https://user-images.githubusercontent.com/46447572/62545508-20e9a680-b862-11e9-999c-ed9545f965e1.png)
and also with Prime and Turbo emotes :) :D ;) etc.

**Comment by pajlada** [comment]
I have narrowed it down to being caused by fff979b3c0f6b16ad1076056aa9b04780ebd5d31 aac27c2a0d8fca560e4daa184075bb871e41f968 or e7d942243110f1c3140833cd9284358cd41b68ae

**Comment by pajlada** [comment]
Fixed
