### ISSUE TITLE
Automod prompt not appearing

### ISSUE THREAD

**Issue by andred44** [Chatterino/chatterino2#1186]
The automod implementation #925 stopped appearing in chatterino

I tested it and it appears on webchat though

Currently on the latest commit c578cd4

![imagetest](https://andred.s-ul.eu/BZaoCb3e.png)
![imagetest](https://andred.s-ul.eu/WzUODOme.png)

**Comment by pajlada** [comment]
Might be related to pubsub connection not being created properly? How many chats are you in?

**Comment by pajlada** [comment]
Probably related to #1189

**Comment by andred44** [comment]
I think this is resolved for now, seems to be working again
