### ISSUE TITLE
Account deletion makes Chatterino crash

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#1187]
Built latest commit version on Debian and Manjaro. If Chatterino has only one account saved and the user tries to delete that account the application crashes and needs to be force-closed. Don't know if this will happen too with multiple saved accounts.

**Comment by pajlada** [comment]
More people have reported this, yet I've never been able to reproduce it myself unfortunately

**Comment by fourtf** [comment]
is this fixed now?

**Comment by bennyhillthebest** [comment]
It looks like it! I think we can close!
