### ISSUE TITLE
Manage accounts button is broken

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#1188]
Built latest commit version on Debian and Manjaro. I saw also that a PR was made about it, unfortunately it seems that something changed and the button is once again broken.

**Comment by RAnders00** [comment]
What is "broken" in this case? Does pressing it not do anything or what's the exact issue?

**Comment by bennyhillthebest** [comment]
Exactly, pressing it does not open the preferences window.

**Comment by pajlada** [comment]
I have the same issue on Arch with i3

**Comment by RAnders00** [comment]
We can close this, the fix for this has been merged via #1208! 🎉
