### ISSUE TITLE
Pubsub not working in all channels.

### ISSUE THREAD

**Issue by aidenwallis** [Chatterino/chatterino2#1189]
If you are in more than 50 or so channels (past the pubsub limit) some channels appear to not have properly connected to pubsub (ie. no timeout reasons showing as moderator and such). Also they don't always reconnect properly, especially when switching accounts or when it gets disconnected.

**Comment by Felanbird** [comment]
a portion of this is mentioned in #1022 👍

**Comment by pajlada** [comment]
We don't handle >50 connections properly

**Comment by fourtf** [comment]
should be fixed
