### ISSUE TITLE
Window save fullscreen/windowed state

### ISSUE THREAD

**Issue by Stealthdashpow** [Chatterino/chatterino2#1193]
![image](https://user-images.githubusercontent.com/53970510/62821335-f9008880-bb6a-11e9-800a-f1991ba4f6f7.png)

App never opens window in same position and never remembers full screen. I was going to use the app but this puts me off straight away. I thought I would take the time to make a github account to provide you with this info. Note that the monitor is in portrait.

**Comment by fourtf** [comment]
I'm not taking feature requests for chatterino 1 since we are working on chatterino 2 (which is in this repo).
