### ISSUE TITLE
Trackpad scrolling through tabs is broken

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#1194]
Might need to somehow respect the trackpad speed and somehow stop "decelleration"?

**Comment by fourtf** [comment]
Could just add a deb-ounce by checking the last scroll time.

Congratulations you have the job to add it!

**Comment by zneix** [comment]
@pajlada Maybe #2647 fixed this issue? Do you remember if you created this issue for someone else who had this problem?
Since this was created almost 2 years ago lots has changed and can someone confirm this is no longer an issue?

**Comment by sando** [comment]
Works fine on Windows as far as I remember. Just tested again now with two-finger gesture on Windows 10 with precision touchpad support, e352d7b31. Might need to verify on Linux/macOS?

**Comment by zneix** [comment]
> Might need to verify on Linux/macOS?

I use my touchpad on daily basis and it works fine on i3 on GNU/Linux,

By the way, it's worth mentioning that after #2647 you can only scroll vertically to "scroll through tabs" - scrolling horizonally used to "scroll through tabs", but it isn't supported anymore after #2647.

**Comment by pajlada** [comment]
on macOS horizontal scrolling (left to right) on a trackpad does not work. vertical scrolling (up and down) works though
