### ISSUE TITLE
AppImage builds have no build hash like the Windows builds

### ISSUE THREAD

**Issue by notheowner** [Chatterino/chatterino2#1203]
Top bar on Ubuntu 19.04 as of commit 2143a8c
![8iP2g](https://user-images.githubusercontent.com/25968992/62917265-40258e00-bda4-11e9-8e58-f34a28f19d9f.png)

**Comment by 23rd** [comment]
But this is completely unclear to non-developers and takes up extra space in the title. =(

**Comment by notheowner** [comment]
Not exactly. People who have issues and want to report them, can use this to make sure they are running the latest builds since there is no other way to identify within the application, which build you are running.

**Comment by pajlada** [comment]
I think adding the hash inside the about part of settings might be the better way forwarding

**Comment by notheowner** [comment]
Makes sense, gives us something to identify a build, seperate/compare it with other ones.

**Comment by alazymeme** [comment]
I think this was fixed? I'm on WIndows 10 btw
![image](https://user-images.githubusercontent.com/12804673/83131498-42828a00-a123-11ea-838b-ffd477b11c29.png)

![image](https://user-images.githubusercontent.com/12804673/83131520-49110180-a123-11ea-8056-05d0714021e4.png)

**Comment by pajlada** [comment]
Thanks @alazymeme :+1: You're right
