### ISSUE TITLE
Highlight sound plays on startup

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1205]
To reproduce, in my case, just start latest chatterino nightly.

**Comment by leon-richardt** [comment]
Could this be related to the "Notify when live" feature? I can't reproduce on the latest nightly otherwise.

**Comment by alazymeme** [comment]
Are you still able to reproduce this?

**Comment by pajlada** [comment]
The "notify when live" feature can produce this effect, yes.
I have confirmed that messages that are fetched from the recent messages api do not trigger highlight sounds

**Comment by RAnders00** [comment]
Isn't that still an issue though, should the notify when live really play on startup?
