### ISSUE TITLE
Emote images are not changed to higher DPI if chatterino2 is zoomed in

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1212]
**Describe the bug**
When you press Ctrl Plus or shift-scroll to zoom in, emote images stay blurry.

**To Reproduce**
- Open chatterino2 at normal zoom level
- Zoom in

**Expected behavior**
Like before, chatterino then starts using 2x images and 4x images at certain zoom levels.

**Screenshots**

![image](https://user-images.githubusercontent.com/1629196/63223919-04802f00-c1bd-11e9-8aed-51804dab0a28.png)
![image](https://user-images.githubusercontent.com/1629196/63223928-0d710080-c1bd-11e9-82e3-5f64f2063ce9.png)

**Chatterino version**

`2.0.4 (15.08.2019 c1afbd5-1)`

**Additional context**

When starting chatterino2 with a higher zoom level, 2x or 4x images are loaded in respectively.

This also seems to be related to the shift-to-view-image-as-large feature to show smaller popups since recent updates: (#1212)

![image](https://user-images.githubusercontent.com/1629196/63223936-3abdae80-c1bd-11e9-8b64-243387ba84ec.png)

**Comment by fourtf** [comment]
Can not confirm (on newest build18fb160) ![](https://i.imgur.com/UCcyHOo.png)

**Comment by RAnders00** [comment]
Just confirmed this again with `2.0.4 (18.08.2019 18fb160-1)`

![image](https://user-images.githubusercontent.com/1629196/63226716-da8b3480-c1dd-11e9-8f15-d8da8fd5311f.png)

**Comment by RAnders00** [comment]
This only seems to affect already-posted/loaded emotes. New emotes being created as a result of incoming chat messages have the 1x/2x/4x image associated with the current zoom level.

**Comment by RAnders00** [comment]
Related to #1211

**Comment by fourtf** [comment]
should be fixed
