### ISSUE TITLE
🎶 Multiple differentping sounds

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1216]
**Is your feature request related to a problem? Please describe.**
No ability to distinguish which highlight plays ping sound. Having multiple ping sounds would solve this. For moderation you might want to get notified on certain patterns which have nothing to do with normal pings.

**Describe the solution you'd like**
Allow selecting Ping sounds per highlight.

**Describe alternatives you've considered**

Don't do it.

**Additional context**

**Comment by Mavvi87** [comment]
An alternative could be adding another fan inside "Moderation" section called  "Blacklisted" which would basicly be the same as highlights, but only available in chats you got sword.
