### ISSUE TITLE
Main window can hide update popup when "Always on top" setting is enabled.

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1219]
**Describe the bug**
When you start chatterino and your window layout makes it cover the part where the little dialog prompting for the update pops up AND you have the setting to have Chatterino 2 always on top enabled, then it's not possible to interact with Chatterino 2 or the update box easily.

Input to Chatterino 2 is disabled because a dialog box is open, and you cannot bring the update dialog to the front because Chatterino 2 is always on top.

**To Reproduce**

(presumably you have to be on windows too)

1. Download old chatterino2
2. Open it, resize it to cover the center of your primary screen
3. Enable "Always on top" in settings
4. Close chatterino2
5. Re-open chatterino2

**Expected behavior**

Either "always on top" is enabled after initial dialogs are dismissed, or the dialog is like the "chatterino2 did not exit properly the last time" popup, which has to be dismissed before Chatterino2 starts (although I could see this becoming annoying for people who cannot/don't want to update and have to dismiss this on every start)

Or just detach that popup from the main window and allow interaction with the main window while that popup is active.

**Screenshots**

**Chatterino version**

2.0.4 (18.08.2019 67eb16d-1)

**Additional context**

**Comment by fourtf** [comment]
This popup was removed in 2.1.0
