### ISSUE TITLE
[Question] Gifted sub eligibility

### ISSUE THREAD

**Issue by ITALIA195** [Chatterino/chatterino2#1223]
From my understanding of how twitch gifted subs work, they prioritize currently watching followers, then watching users then followers then people that have watched the stream in the past.
When using chatterino2 do I fall into the "watching followers" category?
Does this apply for all the tabs or only for the one open at the moment?

**Comment by fourtf** [comment]
Chatterino is a chat client not a tool to farm gift subs and we will not give support for that use case. Thank you for your understanding.

**Comment by ITALIA195** [comment]
Wow that's an aggressive answer for no reason...
I'm not asking this because I want to farm subs or anything, I was watching a stream earlier today and there were a lot of gifted subs, I was wondering if I had to open the chat in the browser to be eligible for a gifted sub or if I could just continue using chatterino.
Usually people in github are pretty professional so I did not add the reasoning behind my question, I guess I have to in this repo tho!

**Comment by Defman21** [comment]
Was it aggressive though?

**Comment by fourtf** [comment]
Looks like it was a misunderstanding on my part. However, the insult was uncalled-for.

**Comment by Felanbird** [comment]
Your question was out of the scope of this project, it would be a question better suited on the twitch forums, but I can tell you my personal experience on the "issue".

Chatterino is a client that connects you directly to twitch IRC, which, like all other IRC clients sticks you directly in the chat & viewer list at all times you have it open. If your query is whether or not Chatterino could be used for sub farming, the answer is yes.

That being said, the specifics of twitch's gifted subscriptions algorithm is unknown, as there was recently a minor drama involving a streamer and multi-year old troll accounts receiving gifted subs.

Just a general misunderstanding on both parties side. 😄

**Comment by ITALIA195** [comment]
I'm not sure twitch uses the IRC chat users for that as that would probably mean that using player.twitch.tv wouldn't count you as neither a viewer nor as a eligible sub (given that they share the same user pool)

I also owe an apology to @fourtf , I got a bit overly defensive there, sorry about that

**Comment by Felanbird** [comment]
I can confirm personally I have gotten gifted subs in channels I only joined on an IRC client specifically for logging purposes, and never actually opened their stream page, (live or offline) prior to the gift.

I assume twitch uses the wording "watch" in a sense because they assume if you are watching you will be connected to the chat either way. 🤔

**Comment by ITALIA195** [comment]
There is a chance you've been gifted when not considered online, A while ago I've been gifted a sub to a channel I didn't watch for a long time. Even if possible it's still unluckily and the more followers the channels has the less chances you have to get one, that probably settles the question, closing the issue.
