### ISSUE TITLE
Message history not loading

### ISSUE THREAD

**Issue by flubbabub** [Chatterino/chatterino2#1224]
**Describe the bug**
Up until today, whenever I launched chatterino it would show me the chat history for the past few hours, now it doesn't show anything previous even though I have "Load message history on connect" ticked.

**To Reproduce**
Launch Chatterino

**Expected behavior**
I expect to be able to see the chat history when i load into chatterino.

**Screenshots**
https://imgur.com/a/fR0ZDr4

**Chatterino version**
2.1.0 (21.08.2019 3079765-1)

**Comment by Felanbird** [comment]
Issue has been resolved, just a small death on the recent messages bot/server. 😄
