### ISSUE TITLE
Manually set priority of emote tab-completion

### ISSUE THREAD

**Issue by ShadoPandauin** [Chatterino/chatterino2#1225]
Basically in some chats I end up tab-completing to the wrong emote because they have an emote enabled that takes alphabetical priority. For example, "OMEGALAUGHING" takes priority over "OMEGALUL". It would be nice if we had a way to set manually set the priority of emotes in order to avoid this.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
