### ISSUE TITLE
Removing accounts crashes chatterino

### ISSUE THREAD

**Issue by 161134050** [Chatterino/chatterino2#1226]
**Describe the bug**
Clicking "remove" on the Accounts tab in the settings makes Chatterino crash

**To Reproduce**
Click "remove" on an Account in the Accounts tab in Chatterino settings

**Expected behavior**
Chatterino does not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/39843740/63511208-265a1880-c513-11e9-91cf-09562b4d2f8e.png)

**Chatterino version**
2.1.0 nightly (21.08.2019 3079765-1)

**Comment by Felanbird** [comment]
I can confirm, I can replicate on newest nightly and older forked commits. 

I'm surprised this issue report didn't already exist it was well known. 🤔
