### ISSUE TITLE
Messages received while recent messages load are grey and with no badges

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1229]
**Describe the bug**
While the recent messages load (or, in other words, before they are loaded in) messages received via the normal IRC connection are missing color and badges.

**To Reproduce**

Open chatterino2, and look at a fast chat around the time of the connect.

**Expected behavior**

Messages load in with color and badges.

**Screenshots**
![image](https://user-images.githubusercontent.com/1629196/63535079-e5610480-c510-11e9-88c6-6bae288832ce.png)
![image](https://user-images.githubusercontent.com/1629196/63535096-f14cc680-c510-11e9-8a83-3890d8bdf03c.png)

**Chatterino version**
2.1.0 (21.08.2019 59b3242-1) which is equivalent to commit c81e1929c9dffab64f58e5e676dc5623c14036b0

**Additional context**

**Comment by apa420** [comment]
I can't reproduce exactly. The color of the names were not changing to grey, but there was duplicate messages and badges were not properly loading. Emotes seem to be working properly as well (even sub emotes). In your image personal sub emotes don't seem to load (nymnHmm).


![](https://i.nuuls.com/JvslW.png)

**Comment by RAnders00** [comment]
Can confirm, this is fixed by #1232
