### ISSUE TITLE
Issue with logging in

### ISSUE THREAD

**Issue by Wittyseal** [Chatterino/chatterino2#1231]
When launching an updated version of chatterino2 it repeatedly comes up with "login expired! Try logging in again." x2 then saying I am disconnected and proceeding to repeat this until the end of time. I've tried going into the settings and removing my twitch, this only makes chatterino2 freeze.

**Comment by fourtf** [comment]
You do not need to sign out, re-adding the account will replace the old one.

 The issue you are describing is fixed in code and will be released in a couple days!
