### ISSUE TITLE
🤠 Chatterino to create window-layout.json backups 🤠

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1233]
**Is your feature request related to a problem? Please describe.**

A problem some people face with Chatterino is losing their settings folder when updating/installing a new version, but more importantly their window-layout.json which holds their list of channels sometimes gets overridden. 

**Describe the solution you'd like**

If Chatterino could generate working backups of the window-layout.json file, it could have something to pull from, or even if the backup were generated they could be manually placed back into the folder, instead of having to manually backup your settings.

**Comment by fourtf** [comment]
It uses a QSaveFile so this shouldn't be an issue anymore.

**Comment by Felanbird** [comment]
I'm re-opening this issue as your window-layout.json can still be lost via forced shutdown. 

Despite this being user error, it would be extremely useful still if the suggested enhancement existed for usage to re-obtain an old window-layout.json if the issue arises.

![image](https://user-images.githubusercontent.com/41973452/65375238-214acf00-dc61-11e9-8756-04368587da33.png)

Chatterino version b06918e
