### ISSUE TITLE
tab emote autocorrect scuffed

### ISSUE THREAD

**Issue by trihardseven** [Chatterino/chatterino2#1235]
basically it worked fine first time I used the app yesterday, today it autocompletes to names

**Comment by apa420** [comment]
What is scuffed?
How do you replicate?
Maybe a video to show what's wrong?
What version of chatterino are you using? (Stuff at the top of the chatterino window e. g. Chatterino Nightly 2.1.0 (22.08.2019 0c...))

**Comment by fourtf** [comment]
Closing this for now since there is not enough information and the post is 5 days old. Please either edit this post with more information or create a new issue.
