### ISSUE TITLE
Searching for only usernames in chat history (Ctrl + F)

### ISSUE THREAD

**Issue by Zanuh** [Chatterino/chatterino2#1236]
**Is your feature request related to a problem? Please describe.**

When searching in chat history for a channel (Ctrl + F) it is not possible to search for only usernames. For example, if I want to search for my own username "Zanuh", it will reveal all users AND messages that contain that word.

**Describe the solution you'd like**

To be able to put an "@" before a word should only display usernames. For example, "@Zanuh" should only reveal messages from that specific user or users that contains that word.

**Describe alternatives you've considered**

Make it a preference in settings to have it on or off.

**Additional context**

Might already be a way to do this that I just don't know of.

**Comment by SLCH** [comment]
What would be the result of searching `@Zanuh @slch @admin` or `mail@domain`?

Searching by user should be an additional field in form, i think.

**Comment by ITALIA195** [comment]
I feel like you should be able to search for mentions and having an additional field is not that pretty either imo (maybe can work, need to see how it would look like)

At the moment you can search for a user's messages by suffixing his name with `:` as the search is tested against the whole line and not the only name and message.

**Comment by fourtf** [comment]
Couldn't you search for `Zanuh:` and 99% of the messages would be yours?

**Comment by Zanuh** [comment]
@fourtf, yeah, actually that works very good, then no need for me to having to add @ before.
