### ISSUE TITLE
Mod/VIP status does not update when modded/VIPed

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1239]
**Describe the bug**
When you join a channel, chatterino2 currently determines whether you are mod/VIP. The mod/VIP status however does not update when you are modded or unmodded. (Which is easily detectable via the received `PRIVMSG`, `USERSTATE` or even PubSub messages for the own user).

**To Reproduce**
- Join channel where you are neither mod or VIP
- Have the broadcaster mod/VIP you
- You can not spam without the global delay (if VIP or mod) and mod button does not appear (if modded)

**Expected behavior**
VIP/Mod status updates.

**Screenshots**

**Chatterino version**
3079765a0cb8d81721b1812901b55c38d3624c41

**Additional context**

**Comment by fourtf** [comment]
Detecting the changes didn't really work reliably, the events didn't get sent properly in chat afaik

**Comment by RAnders00** [comment]
@fourtf if you mean the IRC `MODE` stuff.. yeah that's unreliable. Listening for changes in badges in `USERSTATE` (which is received on channel join and on every sent message) should be perfectly stable though, from my experience with the chat service. ymmv. It's never 100% perfect at detecting of course.

**Comment by Mm2PL** [comment]
Mod/vip `USERSTATE` detection works. There is still improvement to be made here. The moderation actions PubSub topic actually sends information when you are modded/unmodded. It might send similar ones for vip, however I'm not sure.
