### ISSUE TITLE
Chatterino google chrome extension doesn't work

### ISSUE THREAD

**Issue by CreeperChief** [Chatterino/chatterino2#1240]
**Describe the bug**
Chatterino can't connect to the extension and google chrome's console shows 
that the extension tries to install events a lot of times

**To Reproduce**
simply run chatterino and have the extension installed on google chrome

**Expected behavior**
As described in the bug description

**Screenshots**
https://gyazo.com/634bb4cd378178eb6c79b177a7232ba2
https://gyazo.com/886ff521e2c48cbec92ae76d670ce565

**Chatterino version**
2.1.0

**Comment by Zanuh** [comment]
For me it works. I'm running the newest nightly version. The only thing is that sometimes it doesn't actually work, but then I just redownload the extension and it works as normal again. Might just be a problem on your version. I would suggest you to redownload extension, and see if it works then.

**Comment by CreeperChief** [comment]
Thanks, it worked. Kinda bad it doesn't work in the official version yet though.
