### ISSUE TITLE
Add an option to show user ids in user cards

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1243]
**Is your feature request related to a problem? Please describe.**

I would like for the client to have an option to show user ids in user cards.

**Describe the solution you'd like**

 * Add a checkbox to the settings UI.
 * If the checkbox is checked user IDs will be displayed in user cards on another line, otherwise nothing will be changed compared to the current user card.

**Describe alternatives you've considered**

* A command to show the user ID

**Additional context**

Photoshop of how it could look like.
![screencap_temp](https://user-images.githubusercontent.com/25011746/63655397-1f334480-c777-11e9-982c-28b1a1781f3b.png)

Possibility of adding a copy button to the user ID as well

**Comment by TranRed** [comment]
Maybe it should be possible to copy the ID aswell.

**Comment by Mm2PL** [comment]
Yeah I was thinking of that as well
