### ISSUE TITLE
Allow Shift+Home/End to select to start/end

### ISSUE THREAD

**Issue by KillerQ13** [Chatterino/chatterino2#1244]
During my convoluted way of deleting a message I changed my mind on (Shift+Home, Delete), I was disappointed to find the selection didn't work.  Ctrl+A, Delete still works but sometime I want to trim off the end from the middle (Shift+End, Delete).

**Comment by fourtf** [comment]
Fixed in latest commit

**Comment by fourtf** [comment]
https://github.com/Chatterino/chatterino2/commit/748920e8fdd0d63b3023dbe1197408487637c1b7
