### ISSUE TITLE
at sig not working on Mac

### ISSUE THREAD

**Issue by Eraneva** [Chatterino/chatterino2#1246]
**Describe the bug**
 On MacOs with the Client the @ is not working, so you cane not take Users in Chat window .
**Screenshots**
https://www.youtube.com/watch?v=p4bbKHG3qls

**Chatterino version**
2.1.1

**Comment by fourtf** [comment]
Seems to happen on the german keyboard layout where you type @ using Alt+L

**Comment by Eraneva** [comment]
yep tryring the US layout @ is works. 
I don't know exactly what you cane /(could)do to fix it. 
but it would be nice

anyway thanks

**Comment by fourtf** [comment]
we don't have enough information to fix this

**Comment by DK-Web** [comment]
Why closed? @ sign not working on german Keyboard. How can wie fix it?

**Comment by LosFarmosCTL** [comment]
> Why closed? @ sign not working on german Keyboard. How can wie fix it?

This was broken due to chatterino having default vim keybindings on Option+H/J/K/L to switch between open splits and overwriting the Option+L shortcut for @ 

This is no longer the case since #2340, you have to update your chatterino and use the [nightly release](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build)

**Comment by DK-Web** [comment]
> > Why closed? @ sign not working on german Keyboard. How can wie fix it?
> 
> This was broken due to chatterino having default vim keybindings on Option+H/J/K/L to switch between open splits and overwriting the Option+L shortcut for @
> 
> This is no longer the case since #2340, you have to update your chatterino and use the [nightly release](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build)

Nice worked perfectly thanks !
