### ISSUE TITLE
Browser extension overlay window is offset if chrome is showing download bar

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1248]
**Describe the bug**
If you are using the browser extension with chrome and the download bar is showing, the overlaid chat window is offset.

**To Reproduce**
- Start chrome
- Install chatterino native host
- Download any file, e.g. http://speedtest.tele2.net/1MB.zip
- Start chatterino
- Go to a twitch channel page

**Expected behavior**
The chat overlay is put in the correct place and sized correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/1629196/63727970-677b6100-c862-11e9-9de9-000b771fc896.png)

**Chatterino version**
browser extension v1.1
chatterino version: a831c1d5d8523f5a5802b7e4236d737af197ffbe

**Additional context**

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
