### ISSUE TITLE
Notices not being displayed in chat. (fixed)

### ISSUE THREAD

**Issue by cineafx** [Chatterino/chatterino2#1252]
**Describe the bug**
Notices not being displayed in chat after using a command like `/mods` or `vips`

**To Reproduce**
1. Be on v2.1.1 or v2.1.2
2. Type `/mods` or some other notice producing command in chat
3. See no response

**Expected behavior**
See the notice in chat.

**Screenshots (gif)**
https://i.nuuls.com/zkyvS.gif

**Chatterino version**
2.1.2 (https://github.com/Chatterino/chatterino2/commit/7b43f0a30a2e9ec2e5498213a23c66da8d354df2) and [v2.1.1](https://user-images.githubusercontent.com/7873738/63770762-1efd8b00-c8d6-11e9-9732-9587288c3379.png)

**Additional context**
Still works fine on [v2.1.0](https://user-images.githubusercontent.com/7873738/63770500-9e3e8f00-c8d5-11e9-8c6c-89597235e489.png)

**Comment by fourtf** [comment]
Fixed in https://github.com/Chatterino/chatterino2/commit/671c9ed6544ca776079b53d4234f80923fed3f66

I will keep this issue open until an official update is out.

**Comment by pajlada** [comment]
reopening until official release :name_badge:

**Comment by Evanito** [comment]
@pajlada  it's happening again with the pubsub on 2.1.3

**Comment by fourtf** [comment]
Closed as I said above
