### ISSUE TITLE
Chatterino closes after agreeing to update

### ISSUE THREAD

**Issue by Julianhey** [Chatterino/chatterino2#1257]
**Describe the bug**
Upon startup of Chatterino, when the update window pops up, if I agree to the update, the program closes about a second later. No update seems to be installed, because the update prompt returns upon starting again.

**To Reproduce**
Start Chatterino, select 'Yes' when prompted with the question to download and install the update. As usual, another window appears explaining that the update will be downloaded in the background, but shortly after both the main window and the popup close without further interaction.

**Expected behavior**
After selecting 'Yes', a prompt appears explaining background download. Both this prompt and the main window stay open unless closed by the user and the update is downloaded in the background. (The program isn't closed automatically)

**Screenshots**
Gif of the behaviour attached
![2019-08-27_20-30-21](https://user-images.githubusercontent.com/17022272/63798065-a0224580-c909-11e9-8170-700289b36872.gif)

**Chatterino version**
Chatterino Nightly 2.0.4 (3ef77f4-1)

**Additional context**
Windows 10, version 1903, build 18362.295. Happens when run as admin as well. Also happens when 'ok' is selected in the followup prompt. Chatterino remains functioning as normal if 'No' is selected during the update prompt.

**Comment by fourtf** [comment]
Chatterino nightly 2.0.4 can't update. You can either the official release on https://chatterino.com or a newer nightly build.
