### ISSUE TITLE
Timeout timer 

### ISSUE THREAD

**Issue by RIFLABACONBBX** [Chatterino/chatterino2#1258]
Currently there is no way of knowing that ur timed out in a channel. Would be very nice if there was a feature which says how long ur timeouted or if ur banned in a channel.  👨🏿👍🏿

**Comment by Dolev24** [comment]
Adding to this that slowmode timer isnt a thing

**Comment by TETYYS** [comment]
dupe https://github.com/Chatterino/chatterino2/issues/870

**Comment by fourtf** [comment]
as mentioned above, this is a duplicate
