### ISSUE TITLE
Problem with autocompleting emotes

### ISSUE THREAD

**Issue by mitakto** [Chatterino/chatterino2#1262]
Describe the bug
Autocomplete only completes one emote. Typing for example fors and pressing tab fors autocompletion only gives forsen1.

Expected behavior
Typing fors and autocompleting should give me forsen2 if i press tab twice and all the other forsen emotes if tab is pressed repeadetly.

Chatterino version
2.1.2 

Additional context
This problem first occured yesterday 28.08.19. Restarting chatterino and redownloading it didnt fix this problem.

Tanks for every help in advance FeelsOkayMan

**Comment by leon-richardt** [comment]
Does this only occur for forsen/other sub emotes or for other emotes as well? For example, try completing after typing `Kappa` and check whether this cycles through all the different Kappa emotes.

**Comment by mitakto** [comment]
This happens with all emotes. I just used forsen emotes as an example. And it sometimes works when i hold tab pressed but after a few seconds it breaks again and wont complete the cycle.

**Comment by leon-richardt** [comment]
I can't reproduce unfortunately. Have you tried on the latest [nightly](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build)?

**Comment by mitakto** [comment]
Nightly doesnt work either for me.

**Comment by pajlada** [comment]
Can you try downloading Chatterino 2.1.0 and see if you can reproduce it? <https://chatterino.com/download/2.1.0/Chatterino%20Installer.exe>

**Comment by mitakto** [comment]
Problem fixed itself after i enabled the browser version for chatterinio. It sometimes still bugs out but restarting chatterino fixes it. Thanks for the help!
