### ISSUE TITLE
Can't see when you're banned in a channel

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1265]
**Describe the bug**

Typing in a channel no longer tells you that you are banned. It also tells you that you are sending messages too fast after a couple of messages.

**To Reproduce**

1. Get banned from a channel
2. Type something
3. Notice that it doesn't tell you that you're banned

**Expected behavior**

I expect it to tell you that you are banned from the channel - alternatively turning off the ability to type in a channel if you are banned.

**Screenshots**

![image](https://user-images.githubusercontent.com/12804673/64014333-33a38280-cb65-11e9-85a0-5c1ae2f015a3.png)
![image](https://user-images.githubusercontent.com/12804673/64014496-9a28a080-cb65-11e9-85ed-3d8864d73940.png)
![image](https://user-images.githubusercontent.com/12804673/64014505-a01e8180-cb65-11e9-92fe-095347ada0ab.png)

Images representing of:
1. User sending too many messages
2. User typing a message
3. User "sending the message", but it not sending as the user is banned

**Chatterino version**
2.1.2

**Additional context**

**Comment by Felanbird** [comment]
I believe this is a pubsub issue #1189 #1022 as I have previously replicated (and still can) the same issue on 4b7bfc0 which is equivalent to feef6c6

**Comment by Dolev24** [comment]
#1258

**Comment by alazymeme** [comment]
Dupe issue, it's here for records I guess.

**Comment by Felanbird** [comment]
This issue was deemed not to be a pubsub issue, but it is unclear if it can be fixed as no message is received if you are banned from a channel and try to execute a message. 🤷‍♂
