### ISSUE TITLE
Tabs are too wide after changing zoom

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1266]
**Describe the bug**

After resetting the zoom some elements are misplaced and some others have size problems.

**How to Reproduce**

Zoom Chatterino as far as you can by holding control and scrolling up. Press Ctrl+0 to reset the zoom. Text boxes will be bigger than normal, tab headers will be bigger than needed, hints where the subs/notifs are will be moved towards the middle.

**Expected behavior**

The zoom will be reset like it is done with scrolling the wheel.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/25011746/64066650-25f50800-cc0c-11e9-99b2-33040e52dcc4.png)

**Chatterino version**

2.1.2 671c9ed
Edit: stupid mistake

**Additional context**

If you change the zoom by ctrl scrolling the wheel everything will be back to normal.

**Comment by pajlada** [comment]
Confirmed also happening on my Arch Linux setup. I can't find what's different about the scroll wheel and CTRL+0 events. calling updateScale manually seems to fix this but idk if that's the right solution
