### ISSUE TITLE
[Chat history] "User subscribed" incorrect timestamp

### ISSUE THREAD

**Issue by savabozo** [Chatterino/chatterino2#1269]
**Describe the bug**
Message "_username_ subscribed at _tier_ ..." from chat history shows timestamp of ch2 being opened. See screenshots.

**To Reproduce**
Close and open ch2 after someone subscribed/gifted a sub (1-2 minutes after)

**Expected behavior**
Show correct timestamp

<details>
  <summary>Screenshots</summary>
  
![2019-09-01_14-34-43](https://user-images.githubusercontent.com/47025788/64075246-df181880-ccc6-11e9-8c61-5b0bab487dbc.png)
![2019-08-23_21-28-43](https://user-images.githubusercontent.com/47025788/64075247-df181880-ccc6-11e9-80e4-04e94dbc6142.png)
![2019-08-23_21-23-31](https://user-images.githubusercontent.com/47025788/64075248-df181880-ccc6-11e9-8189-dd1efb772e4e.png)

</details>

**Chatterino version**
![2019-09-01_14-40-18](https://user-images.githubusercontent.com/47025788/64075217-8ba5ca80-ccc6-11e9-9616-5cb397370235.png)
PS How do you copy pasta that?

**Comment by RAnders00** [comment]
Closing in favour of #1286
