### ISSUE TITLE
Updater error 2.1.2 --> 2.1.3

### ISSUE THREAD

**Issue by Grydds** [Chatterino/chatterino2#1276]
**Describe the bug**
 Error with the updater from 2.1.2 to 2.1.3, it did seem to update to the right version but not quite i guess

**To Reproduce**
 update

**Expected behavior**
 for me to update to 2.1.3

**Screenshots**
 https://gyazo.com/47fe0e6627430b67ac24f2389787dafa

**Chatterino version**
 chatterino 2.1.3 updater

**Additional context**
<!-- Add any other context about the problem here --!> i click on arrow to update

**Comment by mateossh** [comment]
I tried to update from 2.1.0 to 2.1.3 and got "Permissions denied" error while installing new version

![image](https://user-images.githubusercontent.com/17083034/64205143-96fc2000-ce97-11e9-9607-2b2ebbb9de0b.png)

**Comment by fourtf** [comment]
I cannot reproduce this but I've updated the setup software in case that fixes it.

@mateossh make sure that the uninstaller isn't running, that the installer is running in administrator mode and if that doesn't work restart your computer and try again. If that doesn't work then manually delete C:\Program Files\Chatterino and reinstall.
