### ISSUE TITLE
Open popup chat (for resubs) duplication

### ISSUE THREAD

**Issue by StephanBruh** [Chatterino/chatterino2#1282]
**Describe the bug**
When in automatic theater mode if I go to another streamer and close theater mode the extension will add another "open popup chat" link instead of keeping just one

**To Reproduce**
Enable automatic theather mode go to a streamer close out of theater mode go to another streamer in your follow list. close out theater mode and you will now see 2 link with "open popup chat (for resubs)"
**Expected behavior**
Just 1 link 

**Screenshots**
https://koeleplaatjes.nl/scr/Pseudodynerusquadrisectus-SljiHVFuUv.mp4

**Chatterino version**
2.1.3

**Additional context**
I did try to disable all my other extension but still the same result

**Comment by CreeperChief** [comment]
The bug also happens when automatic theater mode is disabled

**Comment by notheowner** [comment]
I can not reproduce this issue with the latest Chatterino commit and latest Twitch UI update.
Me trying to reproduce it: https://i.nuuls.com/e3Ip2.mp4
The one that stays there, opens the correct active chat as well.
Need more people to confirm though.

**Comment by lawmake444** [comment]
X

**Comment by StephanBruh** [comment]
Yeah it fixed with the latest chatterino and twitch ui update for me

> I can not reproduce this issue with the latest Chatterino commit and latest Twitch UI update.
> The one that stays there, opens the correct active chat.
> Need more people to confirm though.
> 
> **Me trying to reproduce it:** https://i.nuuls.com/e3Ip2.mp4

Yeah it fixed for me with the latest Chatterino and the new twitch UI update

**Comment by pajlada** [comment]
@StephanBruh Please close the issue if this is no longer a problem
