### ISSUE TITLE
Modifying an emote with Channel Points removes all sub emotes from Chatterino 2

### ISSUE THREAD

**Issue by Setekh79** [Chatterino/chatterino2#1283]
Twitch has a new channel Points feature: https://help.twitch.tv/s/article/channel-points-guide?language=en_US
With it you can earn channel points in selected channels and do things with them. One of the ways to spend the points is to modify a sub emote.

I modified an emote to flip it horizontally, as soon as I did this and reloaded my emotes tab to see it, I lost all access to sub emotes from every channel within the Chatterino program.

**Expected behavior**
Refresh emote page and see new emote

**Screenshots**
https://imgur.com/EefxiX1

**Chatterino version**
Chatterino 2 v 2.1.3

**Additional context**
These emote modifications are only for 24 hours, I expect that as soon as it goes away all my other emotes will return to the emote menu within Chatterino 2.

**Comment by Setekh79** [comment]
Additional, this also actually happens in Chatterino 1 too, even Global emotes are not visible in the emote window, they are still visible in the chat itself and you can still type them out manually but tab/autocomplete does not work.

**Comment by Setekh79** [comment]
Additional Additional lol

This is definitely a Twitch API thing, it even happens to BTTV's alternate emote menu on the site itself.

**Comment by alazymeme** [comment]
All works for me, might've been a twitch api thing: https://i.nuuls.com/Es82g.gif
