### ISSUE TITLE
Load the new emotes when the user got a subscription to the channel

### ISSUE THREAD

**Issue by juanfra684** [Chatterino/chatterino2#1285]
**Is your feature request related to a problem? Please describe.**
If while the users are watching a stream they got a new subscription, the new emotes are not available in the emotes picker. It only loads the emotes available at the start of chatterino.

**Describe the solution you'd like**
There are a couple of possible fixes. Reload the list of subscriptions every minute or so, then force the reload of the emotes in the picker if there are new subscriptions.

The alternative is parse the messages on every channel and force the reload only when there are new subs. The picker could check a shared variable like `new_subscriptions` or similar and when it is true, then reload the emotes.

**Describe alternatives you've considered**
Restart chatterino but sometimes you don't want to miss messages.

**Comment by Evanito** [comment]
Note: you can hit F5 to refresh your sub emotes in chatterino

**Comment by juanfra684** [comment]
I tried with F5 in the picker before of open the bug. I didn't think in the main window. Thanks!.

**Comment by RAnders00** [comment]
This can be done if an update to `emote-sets` is detected on incoming `GLOBALUSERSTATE` or `USERSTATE`, which will happen on the next message the user types, or when they join a channel.

**Comment by fourtf** [comment]
Should be straight forward to trigger a reload on the update

**Comment by zneix** [comment]
I am very happy to announce that with the implementation of #2857 this is actually working.
I even managed to test this as I got gifted a sub to forsen (by @bathtubtv :heart:) and I was able to see forsen's emotes without having to press F5 ![forsenE](https://static-cdn.jtvnw.net/emoticons/v2/521050/default/dark/1.0)
