### ISSUE TITLE
⛔⚔ Unable to disable mod buttons ⚔⛔

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1288]
**Describe the bug**

![image](https://user-images.githubusercontent.com/41973452/64441292-9633db80-d09b-11e9-8e70-a7fa829567db.png)
![image](https://user-images.githubusercontent.com/41973452/64441324-a77ce800-d09b-11e9-8d29-d8cb771427a7.png)
When your mod buttons are toggled on and you are un-modded (while chatterino is closed), the buttons stick and you cannot disable them

**To Reproduce**

I replicated this issue by downloading 2.1.4-beta-1, added a portable folder, opened chatterino & logged in, created and toggled on my mod buttons, closed chatterino, un-modded myself via another chatterino client, re-opened it and the mod button sword is gone but the mod buttons are still toggled on.

**Expected behavior**

This is technically the expected behavior because I assume the "check" sees if you are a mod and if not the button isn't generated, but your setting of having the buttons toggled on is saved internally. but I can see why it would be annoying to be unable to disable the buttons.

I assume the preferred behavior would be still being able to disable the mod buttons somehow. 

**Screenshots**

![image](https://user-images.githubusercontent.com/41973452/64442137-49e99b00-d09d-11e9-9f60-ecb7dc6c3b2b.png)

**Chatterino version**
2.1.4-beta-1

**Additional context**

This is partially mentioned in #847 but this issue is specific to the setting change from #983

**Comment by Mm2PL** [comment]
imo the fix for this should be showing the mod mode toggle button always if the mod buttons are enabled.
