### ISSUE TITLE
Add settings to make highlights case sensitive

### ISSUE THREAD

**Issue by ydyote** [Chatterino/chatterino2#1289]
**Describe the bug**
I enabled the regex in highlights and it somehow didn't match the regex correctly
In settings -> Highlights ->  enable regex checkbox

**To Reproduce**
check the enable regex checkbox
put into the pattern this regex: \s[M][E][G][A][L][U][L]\s

**Expected behavior**
I would expect it matches " MEGALUL " and not " MegaLUL " but it matches both

**Chatterino version**
2.1.3

**Screenshot**

![image](https://user-images.githubusercontent.com/54998537/64450206-e897eb00-d0e1-11e9-8f44-edd7588a54c8.png)

**Comment by ydyote** [comment]
its a pretty crappy regex pattern but still

**Comment by leon-richardt** [comment]
This occurs because highlight phrases are currently matched case-insensitively.

#1295 adds a setting to choose between modes.

By the way, `\sMEGALUL\s` describes the same Regex.
