### ISSUE TITLE
Preview on Hover: Not showing the correct size of a FrankerFaceZ custom mod badge + preview of vip, regular moderator, and broadcaster badge not appearing

### ISSUE THREAD

**Issue by rvdog815** [Chatterino/chatterino2#1291]
Describe the bug
The Preview on Hover feature is not displaying the correct size preview for custom FrankerFaceZ moderator badges. also after initially opening this issue i have noticed that the preview for the Broadcaster badge and the VIP badge aren't showing up

To Reproduce
Go to settings turn on Preview on Hover and then go to a channel that has a custom FrankerFaceZ moderator badge larger than 18x18 for example Trihex

Expected behavior
The Preview on Hover would show the correct size preview of the custom FrankerFaceZ moderator badge

Screenshots
image of preview viewed on twitch website: ![image](https://user-images.githubusercontent.com/35497363/64466655-f771a400-d0c7-11e9-9711-7413009e3800.png)

image of preview on the latest nightly: ![image](https://user-images.githubusercontent.com/35497363/64466749-79fa6380-d0c8-11e9-8d88-0e0e8371793d.png)

image of preview of VIP badge on the latest nightly: ![image](https://user-images.githubusercontent.com/35497363/64468396-33613500-d0d9-11e9-826f-00ef558d3772.png)

image of preview of Broadcaster badge on the latest nightly: ![image](https://user-images.githubusercontent.com/35497363/64468439-86d38300-d0d9-11e9-8ecb-06e395567393.png)

image of preview of regular Moderator badge on the latest nightly: ![image](https://user-images.githubusercontent.com/35497363/64469208-e5512f00-d0e2-11e9-9f01-054cf8c390a6.png)

Chatterino version
2.1.4-beta-1 (03.09.2019 9ee286f)

**Comment by pajlada** [comment]
Currently looking into fetching the FFZ mod badge more intelligently

**Comment by pajlada** [comment]
#1293 should solve the issue of the FFZ mod badges not scaling properly.
For the other badges (VIP, Broadcaster, Moderator) we just need to make them into `BadgeElement`s instead of `ImageElement`s for them to be "hoverable".

**Comment by Mm2PL** [comment]
Can confirm, broken on 2.1.4 ce56653e. This happens also with the `Twitch Prime Subscriber` badge.

**Comment by fourtf** [comment]
can;t reproduce
