### ISSUE TITLE
CTRL breaks badge descriptions

### ISSUE THREAD

**Issue by tolekk** [Chatterino/chatterino2#1292]
**Describe the bug**
Pressing CTRL makes badge descriptions stop appearing when hovering over them.

**To Reproduce**
Press CTRL, hover over the channel badge while still pressing CTRL.

**Expected behavior**
The description should appear even when pressing CTRL.

**Screenshots**
![pepega](https://user-images.githubusercontent.com/48994738/64473955-7e2c8c80-d16d-11e9-874f-04689ac64002.png)

**Chatterino version**
2.1.3

**Additional context**
Not sure it it's planned behaviour. Seems like a bug to me.

**Comment by apa420** [comment]
It's any kind of tooltip, emotes, links, etc
(at least on arch)

**Comment by tolekk** [comment]
Just noticed it, happens both on windows and arch. Thanks apa
