### ISSUE TITLE
Extension didn't work on Chromium browsers

### ISSUE THREAD

**Issue by m-k-t** [Chatterino/chatterino2#1294]
**Describe the bug**
Chatterino extension didn't replace Twitch chat on Chromium browsers. It works in Chrome.

**To Reproduce**
Install the Chatterino extension on Chromium browsers.

**Expected behavior**
The extension should work on Chromium browsers as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/32346347/64476584-36d4e900-d1cb-11e9-895d-ce09a5e69f7f.png)

**Chatterino version**
2.1.3 (Extension version 1.1)

**Additional context**
While extension didn't replace Twitch chat on Chromium browsers, "Watching" tab interwork on Chatterino is active.

Chromium browsers that I checked:
Brave 0.68.132
Microsoft Edge Beta 77.0.235.20
Vivaldi 2.7.1628.33

**Comment by fourtf** [comment]
Opera as well

**Comment by Predain** [comment]
same for Brave browser as well

**Comment by Golfi1337** [comment]
Same on Vivaldi

**Comment by fourtf** [comment]
some chromium browsers and a setting to work with all has been added
