### ISSUE TITLE
I dont see any messages while connected to dorm internet

### ISSUE THREAD

**Issue by RevanSakero** [Chatterino/chatterino2#1296]
Hello,
When I am at dorm, I cant see any messages in chatterino. Its probably because they block some ports at dorm (game ports, discord voice chat ports, etc.). Is it any way how to fix it without using VPN?
Thanks

**Comment by SLCH** [comment]
#450 should solve this.
Btw, do you see messages in usual twitch chat?

**Comment by RevanSakero** [comment]
Yes, I do

**Comment by RAnders00** [comment]
This can be solved by connecting to `irc.chat.twitch.tv:443`, but connecting on port 443 is undocumented.

**Comment by RevanSakero** [comment]
Can you please tell me how to do it? Thank you

**Comment by RAnders00** [comment]
It's a change chatterino would have to make, so unless you want to get into compiling chatterino yourself, you can't do it currently I'm afraid.

In the meantime, a solution like a VPN will most likely work.

**Comment by RevanSakero** [comment]
Ok, thank you
