### ISSUE TITLE
Adding title and game category in the notification.

### ISSUE THREAD

**Issue by mambans** [Chatterino/chatterino2#1297]
Possible to add stream title and game category in the notification?

**Comment by savabozo** [comment]
Duplicate of #1124 ?

**Comment by mambans** [comment]
Not exactly, I mean in the windows 10 notification where it currently says the streamers channel name and "Click to open in browser".

**Comment by ALazyMeme** [comment]
Closing in favour of https://github.com/Chatterino/chatterino2/issues/3196
