### ISSUE TITLE
Potential /settitle and /setgame command implementation

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1300]
**Is your feature request related to a problem? Please describe.**

Not that I'm aware of

**Describe the solution you'd like**

The potential for channel editors to use /setgame and /settitle commands to change the title and game of the channel

**Describe alternatives you've considered**

Obvious alternative would be editing using the channel page or using a bot

**Additional context**

This feature is already implemented on mixer, since chatterino is already heavily used for moderation I feel this would be an excellent feature.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project. I suggest using a chat bot instead.
