### ISSUE TITLE
Log out of individual tabs

### ISSUE THREAD

**Issue by Jalidonfox** [Chatterino/chatterino2#1301]
It would be a nice feature to be able to log in and out of each tab individually so you don't show as lurking offline channels

**Comment by TETYYS** [comment]
This is now more relevant with the fact that you can't join chat rooms that you are banned in --- you can with anonymous user

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project. Making logins per split would be a lot of effort.
