### ISSUE TITLE
Not parting "twitch watching" channel when closing tab/browser

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1302]
**Describe the bug**

Mentions lit up even when I'm not in their channel. I was however in their channel earlier; but no longer have twitch open.

**To Reproduce**

1. Install chatterino extension
2. Open mentions tab
3. Open stream
4. Close stream
5. Get another person to ping you - it should show in your mentions tab despite you not being in the channel

**Expected behavior**

It should the person should not be able to ping you. You should not be in the channel once it is closed.

**Screenshots**

**Chatterino version**

2.1.3

**Comment by notheowner** [comment]
Duplicate of issue #1282

**Comment by alazymeme** [comment]
I don't believe it is a duplicate, but now that chatterino's updated, I will test it again.

**Comment by alazymeme** [comment]
Still an ongoing bug, looks like chatterino still maintains the connection to that chat, despite the browser being closed. This could have something to do with the "watching" tab, but I don't use the watching tab

**Comment by alazymeme** [comment]
Chatterino extension is being phased out, I don't see a fix coming so I'll close it.
