### ISSUE TITLE
Implementation of a search tag that behaves like the older search function

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#1303]
**Problem:** i understand that a lot of people like that the search function mimics the one Discord uses, but i liked the old search function because of its filtering conversations capabilities. 

For example, if i searched "poke" in a channel i could see people talking to Pokelawls, Pokelawls's possible replies and also Pokelawls's emotes. If there are too many people using his emotes i could then search "pokelawls" to better filter his conversations. 

Or maybe i want to see if a particular user has sent one or more messages but i don't remember very well his name i can search part of his name to find him.

Very simple but very granular at the same time.

**Solution:** in my opinion the simplest and most effective solution would be to implement a search tag to use the old search function. I propose as a possible tag "searchall:".

**Comment by fourtf** [comment]
it's not intended that users don't get matches anymore

**Comment by leon-richardt** [comment]
> it's not intended that users don't get matches anymore

Could you elaborate on what you consider a bug? I'm not quite sure I understand.

Is it that messages by a user aren't shown when searching for their user name?
