### ISSUE TITLE
10+ Instances Lagging/Freezing computer.

### ISSUE THREAD

**Issue by Glass47** [Chatterino/chatterino2#1307]
**Describe the bug**
 Whenever i open over 10 or 15 instances of Chatterino it starts lagging, my pc feels laggy too.

**To Reproduce**
Open over 10 or 20 and that is how to reproduce that bug/unoptimization.

**Expected behavior**
I expect to be working as it would with only 1 or 2 instance opened.  Smooth and lagless.

**Screenshots**
 /

**Chatterino version**
Chatterino (v.2.1.3)

**Additional context**
 I feel like this is either bad optimization when you do that or a bug, since i have medium to high end pc, i dont have issues with other programs when i do the same as i do with Chatterino.

**Comment by fourtf** [comment]
Can confirm that the cpu per instance grows as more instances are opened. Windows also becomes less responsive as stated.

![https://i.imgur.com/0hGTnAh.png](https://i.imgur.com/0hGTnAh.png)

**Comment by fourtf** [comment]
Changed title to better reflect that it only happens when multiple instances are opened

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
