### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1310]
I got the icon that i need to update chatterino.
![](https://i.imgur.com/CdHzscK.png)
I tried to do the update.
It prompted me to install it on all users (*need admin, so allowed that), selected the folder i wanted to install in. "Z:\Chatterino 2" and removed the extra folder it wanted to create "Z:\Chatterino 2\Chatterino2"
The install was about to start and i got this error into a crash.
![](https://i.imgur.com/1x4TJ7O.png)

--
Updated from Github nightly and now it works but the icon still shows it wants me to update:
![](https://i.imgur.com/s2QDl8I.png)

**Comment by fourtf** [comment]
https://github.com/Chatterino/chatterino2/commit/7cbbd72e7fa49803070ded44266bdc6e8b12e808 Nightly on windows now won't show updates anymore.

**Comment by fourtf** [comment]
This issue has been fixed and will be deployed in the next  update
