### ISSUE TITLE
Bad chat scaling on HiDPI monitor (Manjaro 18.0.4 KDE)

### ISSUE THREAD

**Issue by Galiullinko** [Chatterino/chatterino2#1312]
**Describe the bug**
Installed Chatterino2 from AUR and it has bad chat scaling (fonts and emotes) on Lenovo ThinkPad X1 Yoga 4th gen (WQHD). UI is scaled normally. Tried to play with Chatterino settings, didn't work.

**To Reproduce**
Have Manjaro 18.0.4 KDE, HiDPI monitor. Install Chatterino2 from AUR, system force font DPI at 160 and make screen scaling on 1.7

**Expected behavior**
Want to have clear chat window.

**Screenshots**
![screenshot](https://i.imgur.com/DmgfDDA.png)

**Chatterino version**
2.1.4-beta-2

**Additional context**
Other apps work with system scaling without problems

**Comment by fourtf** [comment]
Upgrading from AUR should work right away. Emotes might be blurry, that's an issue for another commit.
