### ISSUE TITLE
Custom badge colours

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1314]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add the same/similar options for badge colours as ffz

**Describe alternatives you've considered**

Using web chat 4Head

**Additional context**

![image](https://user-images.githubusercontent.com/12804673/64946083-6794dc80-d8b5-11e9-9d40-bdb6c2d10a82.png)

I think these transparent badges look nice FeelsOkayMan
![image](https://user-images.githubusercontent.com/12804673/64946135-7f6c6080-d8b5-11e9-87b5-2593ee9c5ab4.png)

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
