### ISSUE TITLE
Current nightly build doesn't support portable instance

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1317]
**Describe the bug**
Adding a Portable folder to chatterino no longer opens it with no settings.

**To Reproduce**
Download b06918e , add portable folder, open chatterino, chatterino opens with all %appdata% settings

**Expected behavior**
Chatterino to open as if it's a clean install

**Screenshots**

**Chatterino version**
b06918e | Windows 10

**Additional context**

**Comment by fourtf** [comment]
Make a text file called "modes" and write "portable" into it
