### ISSUE TITLE
Ctrl + 9 doesn't open the 9th tab anymore

### ISSUE THREAD

**Issue by Karabast** [Chatterino/chatterino2#1319]
**Describe the bug**

Ctrl + 1-9 Used to open the corresponding tab but now only Ctrl + 1-8 works while Ctrl + 9 opens the last tab.

**To Reproduce**

Press Ctrl + 9

**Expected behavior**

The 9th tab is supposed to open

**Screenshots**

**Chatterino version**

Chatterino 2.1.4

**Additional context**

**Comment by leon-richardt** [comment]
This is intended and was added in #1180.

**Comment by fourtf** [comment]
As noted it's intended
