### ISSUE TITLE
Suggestion : Option to be anonymously logged into certain chats

### ISSUE THREAD

**Issue by PSlopp** [Chatterino/chatterino2#1322]
I'd think it would be useful to have an option to log out/be anonymously in certain chatrooms. I do not know of a way you can do it currently besides logging out/switching accounts for the entire client. I know BTTV has a feature to be anonymous in a chat in twitch

**Comment by PSlopp** [comment]
This suggestion is per channel, like a toggle for each chat room so you can be logged in some and anonymous in others

**Comment by leon-richardt** [comment]
Is this the same as #1301?

**Comment by pajlada** [comment]
Duplicate of #1301
