### ISSUE TITLE
Travis Builds fail on macOS

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#1327]
Currently, Travis builds fail on macOS. The last [passing build](https://travis-ci.com/Chatterino/chatterino2/jobs/237283272) was triggered by https://github.com/Chatterino/chatterino2/commit/758a6bb41c8ca8ab382915dd75a09143b6a2218a, whereas the first [failing build](https://travis-ci.com/Chatterino/chatterino2/jobs/237780011) was triggered by https://github.com/Chatterino/chatterino2/commit/452b65b4dd52a440f14953d0b9dad779ca2236f3.

Therefore, the only possible change in the building process could have been introduced by [this diff](https://github.com/Chatterino/chatterino2/commit/452b65b4dd52a440f14953d0b9dad779ca2236f3#diff-5034672736a9f9fae71571babe82c490) in the project file. I'm not sure why this would break the build though.

When checking the build logs, the issue seems to lie in the linker command: Where the passing builds use the arguments `-framework Security` and `-framework Foundation`, the failing builds use `-framework\ Security` and `-framework\ Foundation`. Otherwise, there seem to be no differences.

**Comment by fourtf** [comment]
Assuming that it's fixed now
