### ISSUE TITLE
Split pages for whispering specific users

### ISSUE THREAD

**Issue by Robinlemon** [Chatterino/chatterino2#1329]
**Is your feature request related to a problem? Please describe.**
It is somewhat frustrating having to keep `/w <name>` in my clipboard when whispering people frequently.

**Describe the solution you'd like**
When creating a new split, there should be a text box option for a username where you can then explicitly whisper that individual without prefixing messages with `/w <name>`.

**Describe alternatives you've considered**
I don't think there is a more concise alternate solution to this enhancement.

**Additional context**
Should effectively behave the same as the TTV whispers panel.

**Comment by Robinlemon** [comment]
I would be happy to submit a PR for this request given it is accepted as something you would like to introduce to Chatterino.

**Comment by apa420** [comment]
An already existing feature is `/r ` which will autocomplete to `/w <user you last got whispered by> `.
I guess it's not exactly what you want though.

**Comment by Robinlemon** [comment]
@apa420 Thanks for letting me know, I will use that for the time being! You are correct though, this is still not ideal since there is no distinct message log or auto command prefixing.

**Comment by fourtf** [comment]
Twitch doesn't provide an API to get the previous messages in a whisper conversation. So since that is the case I believe that there is not much point in adding more complex ui for whispers.

I'll close this so it doesn't get stale.
