### ISSUE TITLE
Bad emote picker window scaling on 1280 x 1024 monitors (window too tall)

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1331]
**Describe the bug**
when you click on the emote menu when you have chaterino at the top of the screen and click on the emote menu you can't move it until you rescale it

**To Reproduce**
https://streamable.com/5hso4

**Expected behavior**
 to be able to move the emote menu 

**Screenshots**
https://streamable.com/5hso4 

**Chatterino version**
 2.1.4

**Additional context**
 just move it 4Head

**Comment by fourtf** [comment]
Just so I don't go insane: Your screen is 1280x1024 without windows scaling. You have recorded the top right corner of your screen and then the video was upscaled to match 1280x1024 again. Is this correct?
