### ISSUE TITLE
Option to quickly add a channel to a Chatterino tab from browser overlay.

### ISSUE THREAD

**Issue by Monopally** [Chatterino/chatterino2#1333]
World make adding channels much faster and pretty much a way to avoid making typos when adding them for pepegas like me.

**Comment by alazymeme** [comment]
From the chatterino extension? Have you tried the Watching tab?

**Comment by Monopally** [comment]
From the Chatterino extension yeah. The watching tab isn't exactly what I'm looking for. Mostly just a way to add a channel so it stays on your tab list, like a "Add to Chatterino" button from the context menu, pretty much the same as if you manually add a channel but just 1-2 click(s).

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
