### ISSUE TITLE
First line of emotes are shifted a bit in emote window

### ISSUE THREAD

**Issue by SaDiablo** [Chatterino/chatterino2#1334]
**Describe the bug**
1. First line of emotes are shifted a bit on every tab in emote window
2. Every restart emote window size gets reset (same as in #351)

**To Reproduce**

**Expected behavior**
1. Emotes having the same margin from both sides of a window
2. Emote window position/size should be remembered same as main window is.

**Screenshots**
1. 
![image](https://user-images.githubusercontent.com/24566138/65472979-2e8cd700-de76-11e9-8925-0492486023fe.png)
![image](https://user-images.githubusercontent.com/24566138/65472986-364c7b80-de76-11e9-8c6d-659535afc54f.png)

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 367b1970f, 22.09.2019)

**Comment by RAnders00** [comment]
Two things I would appreciate, to make fixing the issue easier for everyone:

- Please create a separate issue for the second bug you described (one bug per GitHub issue please 🙃)
- Then update the issue title to `First line of emotes are shifted a bit in emote window` or something similar to that, so the issue title is more descriptive.
