### ISSUE TITLE
Pause chat keybind, disables clicking

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1338]
If you use a hotkey to stop the chat from scrolling, you can no longer select users/use commands on users.
![](https://i.imgur.com/Nlqdvm7.png)
https://streamable.com/lxpd7

Chatterino Nightly 2.1.5 (commit 367b1970f, 22.09.2019)

**Comment by fourtf** [comment]
Description is inaccurate. Clicking still works but the cursor does not change. Also it is unrelated to pausing.

**Comment by fourtf** [comment]
Now I noticed that it's a duplicate of https://github.com/Chatterino/chatterino2/issues/1292
