### ISSUE TITLE
Duplicate "Streamerman is live" notification toasts while using extension

### ISSUE THREAD

**Issue by pphop** [Chatterino/chatterino2#1341]
**Description**
"Live" notification toast fires every time the chat "window" gets recreating with the browser extension for channels that you have notification turned on for, but dont actually have in any split. 

**To Reproduce**
1. Turn on the "notify on live" thing for any live channel that you dont have in any of your chatterino splits.
2. Open the stream in the browser.
3. Switch between two different twitch tabs back and forth for window to be "recreated".
4. Observe the bug. 

**Expected behavior**
Should only fire the toast single time.

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 367b1970f, 22.09.2019)
Extension version is 1.2

**Additional context**
May have apeared in the latest extension update(1.2), but not sure.

**Comment by cinemassacres** [comment]
video would be nice :)

![unnamed](https://user-images.githubusercontent.com/16343162/65891644-1fb88f80-e362-11e9-8951-4b98344fe28b.png)

**Comment by pajlada** [comment]
Can't reproduce
