### ISSUE TITLE
Chatterino wont connect

### ISSUE THREAD

**Issue by fabZeef** [Chatterino/chatterino2#1342]
Tried every single version of Chatterino, firewall/antivirus isnt blocking it.

**Comment by SLCH** [comment]
#1296

**Comment by fabZeef** [comment]
installed VPN, activated it, chatterino started working, uninstalled VPN and chatterino is still working, thanks for help.

**Comment by fabZeef** [comment]
after reinstaling windows the problem completly dissapeared.

**Comment by SLCH** [comment]
Just reinstall windows 4HEad

Seems to be a problem with your system then with ch2. You could close the issue.
