### ISSUE TITLE
Extension swaps line colors

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1343]
This problem have started to happen from time to time, if i after doing something else tabs to a twitch window that have the chatterino extension active, the chat start to swap chat line colors back and forth until i change to another window or target the specific chat.
https://streamable.com/cegcz

Chatterino Nightly 2.1.5 (commit 367b1970f, 22.09.2019)
Extension v 1.2

**Comment by fourtf** [comment]
Is this still an issue?

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/34
