### ISSUE TITLE
Copy User ID button includes "ID:" text

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1344]
**Describe the bug**
Using the Copy User ID button includes the text "ID:" along with the user id

**To Reproduce**
Press copy user id button, paste

**Expected behavior**
ID number only to be copied

**Screenshots**
![image](https://user-images.githubusercontent.com/41973452/65807896-dc420380-e15e-11e9-9bdc-01713e819f44.png)

**Chatterino version**
9874bd7

**Comment by Felanbird** [comment]
@Mm2PL 😄

**Comment by leon-richardt** [comment]
I also prefer this be changed. I can't really imagine a scenario where having the `ID: ` part would be useful.

**Comment by Mm2PL** [comment]
This is a side effect of how I made it. And makes sense that it should be changed. The way that the copying currently works is: the label is set to `"ID: " + userId` and then when the copy button is pressed the text is copied. 
I see three ways of changing this:
 * getting rid of `"ID :" (TEXT_USER_ID)`, that would mean the interface would be less readable,
 * changing `addCopyableLabel()` to only copy text that is meant to be copied,
 * splitting the `userIDLabel` into two, one that would contain the `"ID :"` text the other one would contain the user id we meant to copy.

**Comment by leon-richardt** [comment]
> * changing `addCopyableLabel()` to only copy text that is meant to be copied,

Personally, I like the idea of adding an additional parameter to `addCopyableLabel` that determines the text that should be copied. We could also use a `boost::optional` and default to the label text if `boost::none` is passed but I think that is too much effort.

I propose something like this:
```cpp
void addCopyableLabel(LayoutCreator<QHBoxLayout> box, Label **assign, const QString &copyText)
    {
        auto button = box.emplace<Button>();
        button->setPixmap(getResources().buttons.copyDark);
        button->setScaleIndependantSize(18, 18);
        button->setDim(Button::Dim::Lots);
        QObject::connect(button.getElement(), &Button::leftClicked,
                         [&copyText] {
                             qApp->clipboard()->setText(copyText);
                         });
    };
```

And the calls would then look like this:
``` cpp
addCopyableLabel(box, &this->ui_.nameLabel, this->userName_);
// [...]
addCopyableLabel(box, &this->ui_.userIDLabel, this->userId_);
```

**Comment by fourtf** [comment]
Fix it by optionally storing a string in the properties of the label.

@leon-richardt In your solution the `copyText` shouldn't be a const reference since everywhere in the code this means copying the element, but instead a pointer since it means that there is unsafe access to an address. However I chose this approach over yours since it is fail safe and doesn't create invisible relations between the member variable and the callback.
