### ISSUE TITLE
Crashes upon launching.

### ISSUE THREAD

**Issue by Silvia-Rose** [Chatterino/chatterino2#1346]
sorry if im hard to understand

**Describe the bug**
When i try to launch chatterino, it stays up for a few seconds and then crashes, there is not crash log after

**To Reproduce**
Launch chatterino on the newest version? (idk, it doesn't seem others are having the same issue)

**Expected behavior**
Launches and doesn't crash

**Chatterino version**
It doesn't stay open long enough to get to the version, but the website said 2.1.4

**Additional context**

**Comment by Silvia-Rose** [comment]
i'm newer to github, i didn't add the tags, sorry if they're wrong?

**Comment by leon-richardt** [comment]
> i'm newer to github, i didn't add the tags, sorry if they're wrong?

Don't worry, tags are automatically applied when filing bug reports and feature requests. Makes searchh/organization easier.

**Comment by fourtf** [comment]
Can you download a version from today and see if it works?

**Comment by Silvia-Rose** [comment]
Can confirm the newer version works, thank you <3

**Comment by pajlada** [comment]
Closing this issue then,feel free to re-open if my closing was pre-emptive @Silvia-Rose

**Comment by Silvia-Rose** [comment]
@pajlada, i would like to re-open it but i do not know how

it seems after having it installed for a bit, that it stopped working in the same way again, just crashes right when i open it not leaving logs like before. perhaps i should not have rejoiced so early.

**Comment by fourtf** [comment]
@Silvia-Rose should be fixed in 2.1.5 which is currently on beta and will be released to everybody in a few days.

**Comment by fourtf** [comment]
@Silvia-Rose Perhaps you could already try installing https://chatterino.com/download/2.1.5-4/Chatterino%20Installer.exe and see if it works.

**Comment by Silvia-Rose** [comment]
Version 2.1.5 also keeps crashing for me upon launching.

**Comment by leon-richardt** [comment]
I can reproduce, all of a sudden. Last time I ran Chatterino on Windows (approx. two days ago), it ran fine as always.

Today, it just crashes on start-up, like described by @Silvia-Rose. I tried the nightly build, as well as the 2.1.4 and 2.1.5 installers.

**Comment by fourtf** [comment]
@Silvia-Rose Have you restarted your PC after installing Chatterino and have you tried doing a clean install https://i.imgur.com/PGoplb8.png

**Comment by Silvia-Rose** [comment]
I will try what @leon-richardt said and have it be fresh install as well

**Comment by Silvia-Rose** [comment]
It has now been 2 days of it working with plenty of closing it, re-opening it, pc restarts

and it still works
so unless it decides to just stop working our of nowhere to spite me, it should be safe to close this

weird that it was windows fault
