### ISSUE TITLE
Chatterino extension ovelaps in Theatre mode

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1348]
If you enter the Theatre mode with the Chatterino extension the chat overlaps the stream slightly, 
![](https://i.imgur.com/lznmw6w.png)
![](https://i.imgur.com/s4RYBQr.png)

Extension 1.2
Chatterino Nightly 2.1.5 (commit 367b1970f, 22.09.2019)

**Comment by pphop** [comment]
This has nothing to do with theatre mode, it always overlaps.

**Comment by wigoor** [comment]
ok.
*The chat overlaps the stream based on aspect ratio.

**Comment by fourtf** [comment]
I think this is fixed. Otherwise please add an issue in the extension repo: https://github.com/Chatterino/chatterino-browser-ext/issues
