### ISSUE TITLE
Option to show vod time Instead of local time

### ISSUE THREAD

**Issue by KauzDs** [Chatterino/chatterino2#1349]
Pretty much title. Instead of showing local time like in the [picture](https://i.imgur.com/wq7qpa9.png) maybe add an option to show the time of the vod when the comment was made?

**Comment by pajlada** [comment]
@KauzDs What do you mean by vod time?

**Comment by KauzDs** [comment]
Like this: https://www.twitch.tv/videos/470027119?**t=11h30m0s**
Instead of showing my local time e.g 10:56pm, show at which point in time on the vod the comment was made. In this case, at 11h:30m:00s

**Comment by pajlada** [comment]
are you watching a vod with chatterino? it looks like you're watching live chat

**Comment by KauzDs** [comment]
The live chat SS was just used as an example.  its mainly for the mentions tab since its pretty hard to track down **when** during the vod  I (or something I highlighted) got mentioned.

**Comment by pajlada** [comment]
oooooooooh, so you would like the ability to have a timestamp that resets to 0 when the stream goes live, so a message that was sent 1 hour and 10 minutes into the stream would show `01:10 pajlada: Pepega`?

**Comment by KauzDs** [comment]
yessssss exactly

**Comment by SLCH** [comment]
why tho

**Comment by fourtf** [comment]
This feature is too niche to be added. The only way I see this happening is if there is a generalized solution that allows you to add custom elements to the messages.
