### ISSUE TITLE
I disabled the "mention user with a comma" setting. But he is still mentioned with a comma.

### ISSUE THREAD

**Issue by Strencher** [Chatterino/chatterino2#1352]
**Describe the bug**

I disabled the "mention user with a comma" setting. But he is still mentioned with a comma.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/46447572/66125424-2c014e80-e5e7-11e9-8f4d-01f0136d7389.png)

**Chatterino version**

latest

**Additional context**

**Comment by leon-richardt** [comment]
What does "latest" mean? Latest stable version? Latest nightly?

**Comment by Strencher** [comment]
Chatterino Nightly 2.1.5 (commit 375aa221e, 03.10.2019) @leon-richardt

**Comment by leon-richardt** [comment]
I can't reproduce unfortunately. Could you maybe walk me through how you managed to observe the described behavior?

Alternatively, you could also attach a GIF/video of the bug occurring. :smile:

**Comment by Strencher** [comment]
![test gif](https://user-images.githubusercontent.com/46447572/66129854-f9f4ea00-e5f0-11e9-82b4-8a43b8995e72.gif) @leon-richardt

**Comment by leon-richardt** [comment]
Ah okay, it's important to note that you're not tab-completing but right-clicking user names. :+1:
