### ISSUE TITLE
I'm not seeing subscriptions in chat ("[user] has subscribed ...")

### ISSUE THREAD

**Issue by PSlopp** [Chatterino/chatterino2#1354]
I can't see the purple messages in chat saying that someone has subscribed.

**Comment by PSlopp** [comment]
Note : I'm not sure how they greyed out chat works, (I believe its the chat of the last stream?), but subs will show up in there, but not in the live chat.

**Comment by apa420** [comment]
What version of chatterino are you on, what os etc. We need more info to explore the issue, since it works right now on latest chatterino. Preferrably you should've used one of the templates for creating the issue.

**Comment by fourtf** [comment]
Should work with 2.1.5 ( https://chatterino.com/download/2.1.5-4/Chatterino%20Installer.exe ) which will be released in a couple of days so I'm closing this for now. Please try the version I posted and report if it works there.
