### ISSUE TITLE
Limit your own spamrate if you're mod/vip

### ISSUE THREAD

**Issue by Fawcan** [Chatterino/chatterino2#1356]
**Is your feature request related to a problem? Please describe.**
No, or maybe one-mod/vip spam.

**Describe the solution you'd like**
A new function where you can limit the rate you can spam if you're VIP or Mod to same rate as a regular user has, simple as that.

**Describe alternatives you've considered**
Just don't one-mod/vip spam  4HEad

**Additional context**
.

**Comment by fourtf** [comment]
So this would be for mods that don't want to upset people by sending more messages than a normal user?

If so then what keeps them from simply sending less messages?

**Comment by TETYYS** [comment]
@fourtf as a vip you might want to use ctrl+enter feature but dont want to spam too much

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
