### ISSUE TITLE
Clicking top right navbar collapses into hide chat mode

### ISSUE THREAD

**Issue by dozzzz02** [Chatterino/chatterino2#1357]
**Describe the bug**
If you click any of the top right navbar buttons (prime, get bits etc)
You will collapse the chat and get the black bars.

**To Reproduce**
Click any of the buttons in non theatre mode. (You can't see them inside theatre mode anyway)

**Expected behavior**
Have the buttons' modal appear above the chat.

**Screenshots**
https://giphy.com/gifs/JTyTtSrzfQ3DcUlEXB

**Chatterino version**
2.1.4 , cant find the current info in about. (Probably not here at all?)

**Additional**
I hear the notification for streamers online a few times extra sometimes.
For example I have 'xQcOW' and 'itsSlikeR' but I heard it 5 times only while the second streamer was live. 

Also, the collapse chat button is above the resubscribe button.

**Comment by fourtf** [comment]
This needs to be done for technical reasons
