### ISSUE TITLE
Minimize Chatterino to system tray

### ISSUE THREAD

**Issue by dozzzz02** [Chatterino/chatterino2#1358]
**Is your feature request related to a problem? Please describe.**
Basically, you have to have chatterino open, even if you dont want to use it directly. This is used for the window inside the stream which replaces the normal chat.

**Describe the solution you'd like**
Either:

- Minimize main chatterino window and remove it from the taskbar and show only the icon in the system tray. Only show the chatterino windows used in browsers ( if you have more than 1 window ) 
- Have the chatterino (program) window be the one that replaces the chat window in the browser.

**Describe alternatives you've considered**
Closing the window by clicking (X) but that also closes the window in the browser.

**Additional context**
Kinda like spotify, which has a 'if you click close, minimize to system tray.'

**Comment by fourtf** [comment]
Duplicate of https://github.com/Chatterino/chatterino2/issues/393 but this has an actual description so I'm closing the other one.

**Comment by fourtf** [comment]
Also fixed your markdown in the description

**Comment by cinemassacres** [comment]
is there any progress ?

**Comment by leon-richardt** [comment]
> is there any progress ?

No one is working on it AFAIK.

**Comment by Akakeshaa** [comment]
this is still pending please implement this

**Comment by zerogott** [comment]
Any update on this?

**Comment by ZjemCiKolege** [comment]
Any progress?

**Comment by ZjemCiKolege** [comment]
Any update on this?

**Comment by pajlada** [comment]
Closing this as a wont-fix because this is a big lift for something I don't want to force on others, and making it optional is not fun. Happy to explore this again in the future, but for now this just isn't feasible.
