### ISSUE TITLE
Have a seperate tab for a user

### ISSUE THREAD

**Issue by rypeedawgz** [Chatterino/chatterino2#1359]
*I feel chat bots/users can get too spammy**

**Have a seperate tab where you see what they type.**

**If it concerns privacy, that have it up to 2-3 channels of where you see them. (e.g: A tab for rypeedawgz in channels: sodapoppin, forsen, xqcow**
Could be helpful for chat bots and users that spam.

**Comment by leon-richardt** [comment]
If something like this is implemented, I think it should provide more general options than just messages by a specific user. Maybe the concept of `MessagePredicates` could be leveraged or expanded upon in that case.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

You can see the recent messages of users when you click on their name. Soon they will auto update as well.

**Comment by apa420** [comment]
You can use /usercard username for the popup
