### ISSUE TITLE
Add "stay on top" option to keep Chatterino over all other windows

### ISSUE THREAD

**Issue by 5E7EN** [Chatterino/chatterino2#1360]
When using Chatterino, it can be a bit annoying to constantly reopen the chat window whenever I interect with the Twitch site/any other programs on my computer.

If there was a setting/button that allowed the Chatterino window to stay "on top" at all times (stay above all other applications, including the browser), that would fix the issue and make it much easier to work with.

**Comment by fourtf** [comment]
There is a setting for that

**Comment by 5E7EN** [comment]
I took a brief look over the settings page but couldn't find it... Where in the menu is it?

**Comment by 5E7EN** [comment]
Found it. Thanks anyway
