### ISSUE TITLE
Rightclick on a empty split crashed chatterino2

### ISSUE THREAD

**Issue by Strencher** [Chatterino/chatterino2#1362]
**Describe the bug**

Chatterino2 crash

**To Reproduce**

**Expected behavior**

**Screenshots**

![chatterinocrash0 gif](https://user-images.githubusercontent.com/46447572/66578909-3b027680-eb7c-11e9-8705-9c2dd05c0cab.gif)

**Chatterino version**

![image](https://user-images.githubusercontent.com/46447572/66578984-5a999f00-eb7c-11e9-9d1e-66c5689f8c2c.png)

**Additional context**

**Comment by leon-richardt** [comment]
Can also be reproduced on 6f710823e. Note that this only happens when opening a new split via the `Ctrl + Alt` overlay. It does not occur when opening an empty split via the dialog.
