### ISSUE TITLE
Pressing middle mouse button on links to open in new tab without it being focused

### ISSUE THREAD

**Issue by m1lado** [Chatterino/chatterino2#1364]
**Is your feature request related to a problem? Please describe.**
 Maybe better for those with poor internet to open the tab, let it load, and then click on the tab themselves

**Describe the solution you'd like**
Like in browsers, when you press the middle mouse button on a link/yt video etc. another tab gets opened while you're remaining in the same tab when you pressed the link.

**Describe alternatives you've considered**
 Dealing with it? eShrug.

**Comment by leon-richardt** [comment]
After some mild googling around, it seems that there is no "nice" way to do this with `QDesktopServices::openUrl`. What works (albeit somewhat hacky) is something like this:

``` cpp
void openUrlInBackground(const QUrl &link)
{
    QDesktopServices::openUrl(link);
    // Re-request focus after opening the web browser
    QTimer::singleShot(700, [this] { QWidget::activateWindow(); });
}
```

700 ms is the lowest I could go without losing focus but this is probably system-dependent. This is also only tested on i3, other window managers and desktop environments might behave differently.

**Comment by fourtf** [comment]
Since it is uncommon for programs to support this and there is no proper way of doing this I'm closing this issue.
