### ISSUE TITLE
[Fedora 30] Running AppImage complains about libboost_system.so.1.65.1

### ISSUE THREAD

**Issue by mavjs** [Chatterino/chatterino2#1365]
**Describe the bug**
Running the AppImage produces the following error:
`/tmp/.mount_ChatteICexAD/usr/bin/chatterino: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory
`

**To Reproduce**
* Download the [AppImage](https://chatterino.com/download/Chatterino-x86_64.AppImage) from the website.
* Make the AppImage executable: `chmod +x Chatterino-x86_64.AppImage`
* Run the AppImage: `./Chatterino-x86_64.AppImage`

**Expected behavior**
Chatterino application window start up as expected.

**Screenshots**
N/A

**Chatterino version**
N/A

**Additional context**
OS: `Fedora release 30 (Thirty)`

**Comment by fourtf** [comment]
Try installing it in your package manager

**Comment by pajlada** [comment]
@mavjs Please try with the nightly release here: https://github.com/Chatterino/chatterino2/releases/tag/nightly-build
the boost library file was not included properly in the appimage file

**Comment by mavjs** [comment]
@pajlada thanks for the quick fix! It works now :+1:

Closing out the issue. Cheers!
