### ISSUE TITLE
Show x amount of subbed months when mouse is hovering over the badge

### ISSUE THREAD

**Issue by m1lado** [Chatterino/chatterino2#1368]
Self-explanatory title

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/66964333-42c28f00-f044-11e9-95ba-036e0de7eeec.png)

![image](https://user-images.githubusercontent.com/41973452/66964399-81584980-f044-11e9-96f6-4018731683c2.png)
Browser Chat Examples

**Comment by m1lado** [comment]
A newer version then i guess, thanks.
