### ISSUE TITLE
Add alias feature / tagging users

### ISSUE THREAD

**Issue by nvalis** [Chatterino/chatterino2#137]
Like mentioned in [Issue #110 of chatterino](https://github.com/fourtf/chatterino/issues/110) an Alias feature would be nice.

With the alias feature you can give another user a permanent alias, to be able to keep track of users who change their displayed names.

**Comment by alazymeme** [comment]
Linked issue no longer exists, but something similar to bttv's nickname feature would be cool:

![image](https://user-images.githubusercontent.com/12804673/77837587-1d6aad00-71ae-11ea-8610-555bdea45105.png)
