### ISSUE TITLE
Stream status panel looks weird sometimes (most likely when chat mode is set to something)

### ISSUE THREAD

**Issue by ydyote** [Chatterino/chatterino2#1373]
**Describe the bug**
The stream status panel doesn't indicate that some text was clipped off - check screenshot.

**To Reproduce**
Not exactly sure, maybe go to chat which is set to follow mode. Or maybe use the chrome plugin for the "WATCHING" support - the one which switches the desktop chatterino chat channel based on the channel you are currently viewing, but I'm not sure about this.

**Expected behavior**
It should end with three dots "..." or it should be multiline or optionally multiline.

**Screenshots**
![image](https://user-images.githubusercontent.com/54998537/67143684-3457bb80-f26e-11e9-89cf-e402a2d2024a.png)

**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Comment by fourtf** [comment]
Unfortunately this is not easily achievable with the framework which we are using. Because of that I will close it. However I added some spacing to make it more obvious.
