### ISSUE TITLE
Extension shows in fullscreen, bug/feature?

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1374]
**Describe the bug**
With the new twitch player the chat is not removed when you go into fullscreen, then again i can see this as a feature also! I really like being able to have the chat on the side while in fullscreen ![](https://i.imgur.com/L80rxnz.jpg) 

**To Reproduce**
New twitch player -> fullscreen

**Expected behavior**
Depends if you want is as a feature or not, but it used to remove the chat when you go into fullscreen.

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 367b1970f, 22.09.2019)
Extension 1.2

**Feature**
If it was to be added as a feature it would be nice to be able to move/resize the window :)

**Comment by alazymeme** [comment]
Can confirm this bug. Windows 10 Nightly 2.1.7 (commit 6d5ba0c44, 24.05.2020)

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/33
