### ISSUE TITLE
SASL auth is broken in IRC (beta)

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1377]
**Describe the bug**
SASL login method doesn't work, it behaves like "Server Password" login method, except it sends `PASS` after `NICK` and `USER` messages.

**To Reproduce**
Connect to server that drops you if you don't authenticate successfully, it will always drop you.

**Expected behavior**
*connection begins*
`CAP LS 302`
`CAP * LS :...` (from server)
`NICK ...`
`USER ...`
`CAP REQ :...`
`CAP * ACK :...` (from server)
`AUTHENTICATE PLAIN`
`AUTHENTICATE +` (from server)
`AUTHENTICATE nick.nick.password` (`nick.nick.password` in base64)
`900 ...` (from server)
`903 ...` (from server)
`CAP END`

**Chatterino version**
Chatterino Nightly 2.1.5 (commit d200f12f4, 27.09.2019) (randers minimod fork)

**Comment by pajlada** [comment]
There are two parts to this issue:
1) libcommuni does not parse the SASL-capability properly from servers that respond in the format of `sasl=PLAIN,EXTERNAL`
A patch has been made here, and I'll figure out the right way to PR this into libcommuni. For now, we will go towards using our own fork of libcommuni.
```
diff --git a/src/core/ircprotocol.cpp b/src/core/ircprotocol.cpp
index 8ce044c..2111773 100644
--- a/src/core/ircprotocol.cpp
+++ b/src/core/ircprotocol.cpp
@@ -306,8 +306,24 @@ void IrcProtocolPrivate::handleCapabilityMessage(IrcCapabilityMessage* msg)
             }
             const QStringList params = msg->parameters();
             if (params.value(params.count() - 1) != QLatin1String("*")) {
-                if (!connection->saslMechanism().isEmpty() && availableCaps.contains(QLatin1String("sasl")))
-                    requestedCaps += QLatin1String("sasl");
+                if (!connection->saslMechanism().isEmpty()) {
+                    // CAP LS 302 enables servers to send sasl in the format of sasl=...
+                    // this means we can't do a simple "contains" check.
+                    // we also get to check which sasl mechanisms the server allow and only request sasl cap if it supports our mechanism
+                    foreach (const QString& cap, availableCaps) {
+                        QStringList capParts = cap.split('=');
+                        if (capParts.length() == 2) {
+                            QStringList serverSaslMethods = capParts[1].split(',');
+                            if (serverSalsMethods.contains(connection->saslMechanism())) {
+                                requestedCaps += QLatin1String("sasl");
+                            }
+                        } else {
+                            if (cap.compare(QLatin1String("sasl"), Qt::CaseInsensitive) == 0) {
+                                requestedCaps += QLatin1String("sasl");
+                            }
+                        }
+                    }
+                }
             }
             if (!requestedCaps.isEmpty())
                 connection->sendRaw("CAP REQ :" + QStringList(requestedCaps.toList()).join(" "));
```
2) Chatterino's insecure credentialstore does not save credentials properly (Fixed in d4474c4ed4a8a2dd48f186fcf7fc8cd5220f7eeb)

**Comment by pajlada** [comment]
@TETYYS A new nightly build is being built right now, please give that a try at your earliest convenience.

**Comment by TETYYS** [comment]
Works 👍
