### ISSUE TITLE
Ability to bind certain twitch channel emote set to an IRC server

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1378]
**Describe the solution you'd like**
A field when setting up IRC channel where you can enter twitch channel to use emotes from.

**Describe alternatives you've considered**
Twitch rooms, but they are being discontinued

**Comment by Mm2PL** [comment]
IRC support was removed

###### F

**Comment by TETYYS** [comment]
![1411585995346](https://github.com/user-attachments/assets/7393af0a-5a40-4584-bd73-8a44ea00c802)
