### ISSUE TITLE
Colors do not work in IRC channels

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1379]
**Describe the bug**
Symbols that should paint text in certain color are displayed literally

**To Reproduce**
Write a colored message with hexchat using Ctrl+K and typing a number, ex. 5

**Expected behavior**
Text to be colored

**Screenshots**
![vvNX5Xh 1](https://user-images.githubusercontent.com/3091645/67165608-e5a24280-f38f-11e9-9fec-6f0af5e8aed7.png)

**Chatterino version**
Chatterino Nightly 2.1.5 (commit d200f12f4, 27.09.2019) (randers minimod fork)

**Comment by zneix** [comment]
@pajlada just noticed that "doesn't fix" in commit message in e4af009fda9f277d6eacaa3d29b6f5a557409359 triggered a keyword and closed this issue but I think that wasn't the intention. Just pointing that out.

**Comment by pajlada** [comment]
eh, fixes it well enough :+1: #1 irc user tetyys can create another issue if there's problems with the irc coloring
