### ISSUE TITLE
missing file while installing and invalid csrf token while trying to auth

### ISSUE THREAD

**Issue by omfgdahoe** [Chatterino/chatterino2#1382]
**Describe the bug**
First bug is I get this error while installing.
Second bug is that logging in or the auth doesn't work.

**To Reproduce**

**Expected behavior**
No error while installing and being able to add my account to chatterino.

**Screenshots**
Install error: https://i.imgur.com/YzifYjh.png

log in / auth error: https://i.imgur.com/pe8jXQr.png

**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Additional context**

**Comment by cinemassacres** [comment]
try nightly :)

**Comment by RAnders00** [comment]
Please create separate issues for separate problems @omfgdahoe - You can edit this one to be about the first problem, and please create a separate issue for the login auth problem.
