### ISSUE TITLE
Copy message doesn't copy /me

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1383]
**Bug description**

Copy message function found in the context menu of a message doesn't copy `/me`.

**How to reproduce**

 1. Post a `/me` message to any channel.
 1. Copy it.
 1. Look at what was copied.

**Expected behavior**

`/me` should be copied with the message.

**Chatterino version**

Chatterino 2.1.5 (commit e267eb67f)

**Comment by tolekk** [comment]
I believe the "Copy full message" option should copy /me . This also happens on 2.1.4 btw.
![image](https://user-images.githubusercontent.com/48994738/67411871-9a21ab80-f5be-11e9-93fa-92086c046633.png)

**Comment by cinemassacres** [comment]
> I believe the "Copy full message" option should copy /me . This also happens on 2.1.4 btw.
> ![image](https://user-images.githubusercontent.com/48994738/67411871-9a21ab80-f5be-11e9-93fa-92086c046633.png)

nope it copys your name and the message but not /me

**Comment by tolekk** [comment]
> > I believe the "Copy full message" option should copy /me . This also happens on 2.1.4 btw.
> > ![image](https://user-images.githubusercontent.com/48994738/67411871-9a21ab80-f5be-11e9-93fa-92086c046633.png)
> 
> nope it copy's your name and the message but not /me

Should, doesn't mean it does.

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
