### ISSUE TITLE
BTTV Global emote sets API parsed incorrectly

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1386]
**Describe the bug**
showing "bttv pro" emotes when they really aren't global emote and will not show up for web chat users except if you are a "bttv pro" user .

**To Reproduce**

type BlackKappa, motnahP, DogeWitIt, BadAss,  Kaged,  SoSerious, (chompy),  BatKappa,
**Expected behavior**

they not to show
**Screenshots**
http://web.archive.org/web/20160305071910/https://nightdev.com/betterttv/faces.php archived version of the bttv emotes https://i.imgur.com/ADgaQSM.jpg
**Chatterino version**
N/A

**Additional context**
you show "bttv pro" emotes in the emote picker as there listed in the bttv api as shown [here ](https://api.betterttv.net/2/emotes)  emote listed in the bttv api like  BlackKappa motnahP, DogeWitIt, BadAss,  Kaged,  SoSerious, (chompy),  BatKappa, will not show up for web chat users [example ](https://i.imgur.com/ADgaQSM.jpg)  The global API endpoint specifies a number of sets (54faa50d01e468494b85b578, 55288e390fa35376704a4c7a, 54faa52f01e468494b85b579, 54faa4f101e468494b85b577, 54fbf11001abde735115de66, 5514afe362e6bd0027aede8, 550b225fff8ecee922d2a3b2, 550b6b07ff8ecee922d2a3e7 ) but all of them are bttv pro as explained by this [archived link ](http://web.archive.org/web/20160305071910/https://nightdev.com/betterttv/faces.php)  all are global as specified by the "global" array. For example this causes the Kaged emote to be shown in chatterino when it really isn't a global emote and will not show up for web chat users except if you are a bttv pro user .

**Comment by Slikrick** [comment]
They have been removed from the BetterTTV global emotes list and are now handled by the emote websocket server for BetterTTV Pro personal emotes. I _believe_ that means this bug is no longer relevant but haven't tested chatterino myself. To properly render them would mean to implement the BetterTTV websocket server for personal emotes.

**Comment by cinemassacres** [comment]
@Slikrick it's [gone](https://i.imgur.com/r54LdeH.png)

**Comment by RAnders00** [comment]
this issue was fixed by https://github.com/Chatterino/chatterino2/issues/1279, fyi
