### ISSUE TITLE
Settings menu is dark in light mode and dark in black mode

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1387]
**Describe the bug**

The settings window is dark when using light mode and dark when using black mode

**To Reproduce**

1. Go to settings
2. Set theme to light or white or black
3. Open the settings menu

**Expected behavior**

Settings window should be light/white/black when using their respective theme

**Screenshots**

https://i.nuuls.com/vFuXy.png

**Chatterino version**

2.1.5 (commit c6e1a1de2)

**Comment by fourtf** [comment]
Settings should always have the same theme so there can never be issue with users of some theme/scaling/other setting not being able to access things

**Comment by alazymeme** [comment]
It doesn't look right :/
