### ISSUE TITLE
emote menu broke "twitch" emotes like rpg, pride, and the rest

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1389]
**Describe the bug**

the emote menu shows  limited time emotes on separate lines instead of 1 line
**To Reproduce**

open emote menu go to sub emote menu
**Expected behavior**
the emotes to be all on one line

**Screenshots**
https://i.imgur.com/X1kmOLV.png
**Chatterino version**
N/A

**Additional context**

they also break on the web version of [twitch](https://i.imgur.com/XhhknPN.png)

**Comment by Felanbird** [comment]
This is technically not a Chatterino issue, as seen in your web screenshot, these emotes just show up in their own personal emote sets for some reason 🍝

That being said I would be a nice issue to fix if somebody could 😉

**Comment by pajlada** [comment]
As @Felanbird mentioned - this is not really a Chatterino issue. Our api over at https://github.com/Chatterino/api could combine these, but that would require someone to get all emote sets for all emote ids and combine them under each RPG/Pride sets and make a PR or issue request in the api repo
