### ISSUE TITLE
Mentioning users with tab defaults to all lowercase letters

### ISSUE THREAD

**Issue by Bucket69** [Chatterino/chatterino2#1390]
Using tab to mention a user doesn't copy the uppercase letters in their name and that used to be a working feature before these major updates. If I wanted to @ someone with the name "TestUser" with tab and type something like @tes and hit tab  then it would show up as @testuser rather than @TestUser

**Comment by cinemassacres** [comment]
https://github.com/Chatterino/chatterino2/issues/1199

**Comment by fourtf** [comment]
duplicate of #1199
