### ISSUE TITLE
Windows installer automatically restarts computer WITHOUT PROMPTING THE USER.

### ISSUE THREAD

**Issue by petercunha** [Chatterino/chatterino2#1391]
**Describe the bug**

After doing a fresh install of Chatterino on windows, the installer automatically reboots the computer WITHOUT prompting the user.

**To Reproduce**

Use the official Windows installer from the Chatterino website, complete steps, and you will get rebooted.

**Expected behavior**

I'd expect the software to prompt first

**Chatterino version**

Chatterino 2.1.5 (commit c6e1a1de2)

**Comment by fourtf** [comment]
Cannot confirm, tried on Windows 10 machine and fresh VM

**Comment by petercunha** [comment]
Must not be reproducible, closing ticket

**Comment by fourtf** [comment]
Does it happen again if you reinstall, or have you perhaps missed a prompt by accident?

**Comment by affyneur** [comment]
I have this same problem. With a fresh Windows 10 install, the last step of the Chatterino install will reboot the system without warning.

**Comment by affyneur** [comment]
I tried to replicate the problem with a re-install on my PC as well as with a fresh install into a virtual machine. Neither of the produced the restart. For some reason, it only happens in a truly fresh install on physical hardware.

The next time I reset my PC (in a matter of weeks or months), I will try to take a video of exactly what happens.

**Comment by affyneur** [comment]
Hi. I actually needed to re-install Windows this morning and had the opportunity to re-install Chatterino on a fresh, physical system. I made a video of the process and uploaded it to YouTube: https://www.youtube.com/watch?v=zqieort5BKk

The automatic restart occurs in the video at 2m 15s.

The automatic restart occurs a split-second after the final installation screen shows up. My guess is there is a bug that triggers the restart here without waiting for the user to click "Finish."

After re-watching the video, I did notice that my mouse cursor just happened to be over the "Finish" button, but I can assure you my hands were not on my mouse or keyboard at the time as I was adjusting my grip on the iPad I was using to record.

**Comment by affyneur** [comment]
I don't program C++ or QT or desktop apps for that matter. But I did try to search for some of the text strings in the code base of this repo and was not able to find them. So I'm guessing the installer is generic and set up with a configuration file. Where might the code for this exist? I don't see anything like it in this repo.

Sorry for the newb questions. I'd love to get this bug fixed as I've now invested significant time into it.

**Comment by RAnders00** [comment]
Same thing happened to forsen on stream, his PC was restarted without prompt

**Comment by fourtf** [comment]
Installer will now prompt

**Comment by RAnders00** [comment]
Only screen I got was this: 
![image](https://user-images.githubusercontent.com/1629196/75625609-1147fb80-5bc0-11ea-8da8-521f69e2eb3d.png)
