### ISSUE TITLE
Tab sizes resetting (somewhat)

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1393]
**Describe the bug**

I use Ctrl + Click/Drag to adjust window sizes, upon restart the tab sizes have reset

**To reproduce**

1. Use Ctrl + Click/Drag to adjust tab sizes
2. Restart chatterino

**Screenshots**

https://i.nuuls.com/RlKa1.gif

**Chatterino version**

Chatterino 2.1.5 (commit c6e1a1de2)

**Operating system**

Windows 10

**Comment by TETYYS** [comment]
Same here well, happens with resized tabs vertically. also, i think tab/window resizing should snap to width that displays ascii art same as web chat does, but thats another issue

**Comment by fourtf** [comment]
can replicate
