### ISSUE TITLE
FFZ Emotes Not Showing 

### ISSUE THREAD

**Issue by theAnggell** [Chatterino/chatterino2#1397]
**Describe the bug**
<-- When you go to a chat the FFZ Emotes do not show up and show as text -->

**Screenshots**
<--[jbBByK8](https://user-images.githubusercontent.com/57189538/67881925-b2a34000-fb41-11e9-9a94-3218702df66b.png) -->

**Chatterino version**
<-- Chatterino 2.1.5 (commit c6e1a1de2) -->

**Operating system**
<-- Windows 10 -->

**Additional information**
<It worked fine 3d ago and has been for months back. I tried reinstalling it couple of times,refreshing still not working..-->

**Comment by cinemassacres** [comment]
reinstall https://i.imgur.com/hIzquCd.png :)

**Comment by pajlada** [comment]
@theAnggell on the same computer, can you try opening https://api.frankerfacez.com/v1/room/id/26301881 in a browser? and let us know what the response looks like? (e.g. with a screenshot)

**Comment by Trung0246** [comment]
Apparently I got this bug too from portable version 2.1.5 Win 10
JSON for `https://.../room/id/26301881`: https://pastebin.com/XDQ2hQXm

**Comment by pajlada** [comment]
I don't see anything wrong with the settings file you posted. There is a setting to disable all emotes, but not only FFZ emotes. so this behaviour still smells like FFZ api to me

**Comment by itsnotoger** [comment]
FFZ api and website is loading very slowly for me, taking over a minute, or getting all kinds of 5xx errors sometimes.
That's probably why it's also not working in C2 for me.

**Comment by apa420** [comment]
Does this still occur?
