### ISSUE TITLE
Modified BW channel sub emote looks different in chatterino than in webchat

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1400]
**Describe the bug**
vadiPressed_BW emote looks different compared how its displayed in webchat

**To reproduce**
be very depressed, post vadiPressed_BW

**Screenshots**
![pSlmWuG 1](https://user-images.githubusercontent.com/3091645/67941847-35c6a380-fbdf-11e9-98bc-2d443f824fb6.png) (webchat on the left)

**Chatterino version**
Chatterino Nightly 2.1.5 (commit d200f12f4, 27.09.2019) (randers minimod fork)

**Operating system**
Win 10 1903 18362.356

**Comment by pajlada** [comment]
also looks different in gimp, just seems to be rendered differently in some libraries. color experts could look into this to see if there's more information I've missed

**Comment by ldesgoui** [comment]
Running imagemagick identify on the BW version returns `3.0.png PNG 112x112 112x112+0+0 8-bit Grayscale LinearGray 6259B 0.000u 0:00.000`, the keyword that jumps up to me is "Linear", it denotes the color space in which color/images are processed, as opposed to the common color space in which images are stored, which is gamma compressed.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project. We can't change the way these images get rendered.
