### ISSUE TITLE
Disconnecting and Reconnecting issue

### ISSUE THREAD

**Issue by ghost** [Chatterino/chatterino2#1401]
Chatterino keeps disconnecting and reconnecting, anyone know whats wrong. Everytime I try to remove my account, the program crashes.

**Comment by TETYYS** [comment]
Try to remove any chatrooms (if you have those) and if you have too many channels, it might cause the reconnect loop too

**Comment by cinemassacres** [comment]
https://i.imgur.com/he9B17X.png

**Comment by apa420** [comment]
Closing of #1831
