### ISSUE TITLE
Highlights don't work for IRC channels

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1405]
**Describe the bug**
Highlights do nothing for IRC channels

**To reproduce**
Set up highlight, get a message that matches highlight, nothing happens

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 556c2aef2, 02.11.2019)

**Operating system**
Win 10 1903 18362.356

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/95678320-e122fb00-0b99-11eb-9732-36c47ae609d3.png)

this was fixed at some point 🤷
