### ISSUE TITLE
All nicks in IRC channels are white

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1407]
**Describe the bug**
All nicks in IRC channels are white, it's hard to distinguish who is writing, you have to read the nick every time.

**To reproduce**
Post in IRC channel

**Screenshots**
![chatterino_59n7E1JA0W](https://user-images.githubusercontent.com/3091645/68083452-525a1a00-fe31-11e9-948b-e051620db173.png)

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 556c2aef2, 02.11.2019)

**Comment by TETYYS** [comment]
they are all gray now

**Comment by Mm2PL** [comment]
When colored nicks are enabled, username-based colors are assigned. I would consider this fixed.

**Comment by GXTX** [comment]
This was fixed at some point, users are random colors now. Should ideally be colored based on their usermode, but I'd consider that a separate issue.

**Comment by Mm2PL** [comment]
This has been dependent on `Colorize users without color set (gray names)` for a while.

**Comment by Felanbird** [comment]
Fixed by #3206

**Comment by ALazyMeme** [comment]
Fixed by #3206
