### ISSUE TITLE
Ping sounds stop after a certain amount of time

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#1409]
This is fairly basic, not so much a bug report as I need clarification. I've started leaving my pc on overnight; now either it's because the displays turn off or something - but by the morning, the ping sounds no longer work. Will get to testing at some point.

**Comment by alazymeme** [comment]
I've figured it out. In the power options in windows (10?), set the screen off time to a value. Leave the screen to turn off, one fully off; wiggle the mouse and get someone to ping you. Your ping sound should no longer make a sound. Now restart chatterino and they should work again.

v2.1.5 (commit 556c2aef2, 02.11.2019)

**Comment by ALazyMeme** [comment]
I don't really use sounds anymore and I don't see anyone else who has reported this. I'll just assume this was a Windows bug.
