### ISSUE TITLE
Chatterino extension causes disconnecting and reconnecting

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#1411]
**Describe the bug**
Chatterino extension causes disconnecting and reconnecting when switching channels on chrome with chatterino extension.

if you switch tabs really fast ur chatterino will crash.

**To reproduce**
open 2 tabs of 2 different channels, focus chat and switch between the 2

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 556c2aef2, 02.11.2019)

**Operating system**
Windows 10

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/32
