### ISSUE TITLE
Chatterino extension loses text after switching between tabs

### ISSUE THREAD

**Issue by Defman21** [Chatterino/chatterino2#1412]
**Describe the bug**
When switching between tabs, the extension loses any text I wrote.

**To reproduce**
Write something without sending the message, switch between tabs, go back to the tab with the Chatterino extension window. Everything I wrote is gone.

**Chatterino version**
nightly v1275 built :point_right: 2019-11-02T15:34:51.0000000Z :point_left: 

**Operating system**
Windows 10.

**Additional information**
Firefox 70.

**Comment by Dolev24** [comment]
Adding to this that you lose your message history too (up arrow).

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/31
