### ISSUE TITLE
Some emotes doesn't work (BTTV)

### ISSUE THREAD

**Issue by mambans** [Chatterino/chatterino2#1413]
Some emotes for example (KEKW, LULW) doesn't work. Tried reinstalling and clearing cache/settings.

Tried both normal 2.1.5 and nightly 2.1.5 versions.

**Comment by Dolev24** [comment]
Are you sure they're BTTV? because FFZ have been having some issues, not BTTV.

**Comment by mambans** [comment]
Might be FFZ instead, get them confused.

**Comment by Dolev24** [comment]
FFZ have been having issues lately with their servers, im 99% sure theres nothing to do with chatterino.
they should fix that soon on their part

**Comment by mambans** [comment]
Ah oke, but I could see the emotes in Twitch's site. 
They seem to be working in Chatterino atm tho so you might be right about server issues.
