### ISSUE TITLE
Add a way to vote in the new polls from the app

### ISSUE THREAD

**Issue by doximanman** [Chatterino/chatterino2#1414]
**Is your feature request related to a problem? Please describe.**
Whenever a streamer makes a pole, I have to use the site's chat to vote, which means I have to exit from full screen and unhide chat to vote. It would if nice if it could be avoided.
**Describe the solution you'd like**
Have a way to vote from the chatterino app (maybe have it pop up on the top of the chat as it does in the chrome chat)

**Comment by RAnders00** [comment]
Unfortunately I don't think twitch provides a way for third-party apps to integrate with polls so it's unlikely this will be implemented

**Comment by Robinlemon** [comment]
You can also vote with `/vote 1`. Might be worthwhile looking to see if it's in pubsub or irc.

**Comment by RAnders00** [comment]
/vote 1 most likely gets interpreted client-side and then results in a GraphQL call, but we can investigate it.

**Comment by Mm2PL** [comment]
It is possible to implement read-only poll support using the Pubsub topic `polls.[channel id]`.

**Comment by fourtf** [comment]
Since there is no public api for this feature it can't be implemented. Since it is unfixable I will close this issue.
