### ISSUE TITLE
Constant Reconnecting when logged in

### ISSUE THREAD

**Issue by Shoebug** [Chatterino/chatterino2#1416]
**Describe the bug**
In the last month or longer Chatterino(1) has been stuck in the reconnecting loop on every channel chat added. Strangely, when I log out everything starts working perfectly

**To reproduce**
By logging in and out within the client. 

**Screenshots**
Example in [Gif](https://i.imgur.com/NTwonmU.gifv)

**Chatterino version**
Chatterino for Twitch (v1.3.3)

**Operating system**
Windows 10

**Additional information**
I have tried re adding my account. Chatterino2 does the same to me. Having all the chats or just 1, It's still the same result.

**Comment by Felanbird** [comment]
@Shoebug reduce your channel count to >101 (100 or less) (not including /whispers or /mentions)

**Comment by Shoebug** [comment]
Having it reduced doesn't help. The problem still persists.

**Comment by SLCH** [comment]
Most likely your auth token expired.
Try adding it new (don't know if deleting one works rn).

**Comment by Felanbird** [comment]
> Strangely, when I log out everything starts working perfectly

I missed this part, @SLCH should be correct about your auth token being expired

**Comment by cinemassacres** [comment]
@Shoebug https://i.imgur.com/zvutYSG.png

**Comment by pajlada** [comment]
Not really a Chatterino issue (other than that we don't advertise any limits).
There are limits set to how many channels you can join, and you've exceeded that limit. Not much we can do, sorry.

**Comment by Felanbird** [comment]
@Shoebug Although this issue is closed, try lowering your channels to >36. I've been told 35 works on c1. 🤷
