### ISSUE TITLE
Show x amount of subbed months when mouse is hovering over the badge 

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1418]
**Describe the bug**

when you hover over a badge it does not show sub age
**To reproduce**
hover over a badge
**Screenshots**
https://i.imgur.com/aLEsJPn.png

**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Operating system**
Windows 10 also browser version

**Comment by pajlada** [comment]
The lack of a feature is not a bug.

This information is available in each information in the `badge-info` irc tag.
Example messages:
https://paste.ivr.fi/yiwoqadamu
https://paste.ivr.fi/imavojenit
https://paste.ivr.fi/ifokihamul
