### ISSUE TITLE
Option to hide "unmod" button

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1419]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/41973452/69015327-d26b9e00-0960-11ea-9d09-e1c63e978c58.png)
Personally I've almost clicked this button a bunch of times as well 🌵 

**Describe the solution you'd like**
Option to disable the unmod button, could have the option itself disable the mod button as well

Probably put it under Miscellaneous "Disable (Mod)?/Unmod buttons"

Also if this is created the option would have to be disabled by default (to keep mod/unmod buttons enabled by default)

**Additional context**

![image](https://user-images.githubusercontent.com/41973452/69015373-28404600-0961-11ea-91be-732765b447b1.png)

**edit:** 
This entire issue should probably say show/hide instead of disable

**Comment by pajlada** [comment]
agreed, this feature seems a bit nonsensical in the first place. no need to make it this easy to unmod yourself

**Comment by Mm2PL** [comment]
I would like to take care of this one :) 
How do I self assign? 
[pajaDent](!https://static-cdn.jtvnw.net/emoticons/v1/301129322/3.0)

**Comment by fourtf** [comment]
Remove the button completely. This setting will add more confusion than use.

**Comment by fourtf** [comment]
Alternatively we can make it harder to click, e.g. by putting it in a drop-down menu.

**Comment by Mm2PL** [comment]
thanks :)

**Comment by Mm2PL** [comment]
Maybe the buttons could insert the command into chat, so the user would have to press enter to send it manually.

**Comment by pajlada** [comment]
then I agree with fourtf's solution: just remove the button 4HEad
