### ISSUE TITLE
can't clip  streams

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1420]
**Describe the bug**
can't clip streams
**To reproduce**
click on clip or ctrl x
**video**
https://streamable.com/rah6j
**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Comment by TurtleCatt** [comment]
This has been happening and I don't use the extension I think this is a twitch problem.

**Comment by pajlada** [comment]
@cinemassacres Please try disabling the extension and checking if clipping works without it. I want to confirm this is an extension-related problem. It seems unlikely though.
![image](https://user-images.githubusercontent.com/962989/70848099-eb3a7700-1e6c-11ea-8156-2bd48be2499f.png)

**Comment by RAnders00** [comment]
I cannot replicate this issue
