### ISSUE TITLE
Search doesn't work in IRC channels

### ISSUE THREAD

**Issue by Fawcan** [Chatterino/chatterino2#1422]
**Describe the bug**
Not possible to get search hits with CTRL+F or click Search in IRC channels, just shows nothing.

**To reproduce**
Have IRC channel open, search for a phrase

**Screenshots**
[GIF showing it](https://i.imgur.com/nvLPX0L.gifv)

**Chatterino version**
2.1.5

**Operating system**
Windows 10

**Additional information**
No :)

**Comment by leon-richardt** [comment]
I suppose this is due to the same reason as described in https://github.com/Chatterino/chatterino2/issues/1440#issuecomment-566548661.

**Comment by Felanbird** [comment]
This was partially implemented at some time, as you can search for everything that isn't your own message currently.

**Comment by Mm2PL** [comment]
neither does filtering and usercards

**Comment by Mm2PL** [comment]
Unable to reproduce on 0db52012716d5ba75ff50d25471b6dcaf51e5561 (upstream: 8a0ed79e)

**Comment by Felanbird** [comment]
> Unable to reproduce on [0db5201](https://github.com/Chatterino/chatterino2/commit/0db52012716d5ba75ff50d25471b6dcaf51e5561) (upstream: [8a0ed79](https://github.com/Chatterino/chatterino2/commit/8a0ed79eca91c54098e37c1db72e9eabb8eb719d))

Still can replicate being unable to search your own message specific to the client you sent them from. 
If the message is from you, on another instance of Chatterino, (or any IRC client) it is searchable. 
Same with messages from you in history, but not messages you sent on the specific client. 

Tested on both 24aee4217 & ad89b5d23
