### ISSUE TITLE
Cant search for automod pubsub messages

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1423]
**Describe the bug**
Cant use the search function to search for automod/channel blacklist messages.

**To reproduce**
Add/Remove channel blacklisted phrase, search for phrase

**Screenshots**
[gif](https://i.nuuls.com/EVDWj.gif)

**Chatterino version**
9cb973ac6 which is equivalent to 556c2ae

**Comment by leon-richardt** [comment]
Might be an applicable use case for search tags and `MessagePredicate`s.

**Comment by Mm2PL** [comment]
Also happens for redeeming channel points.

**Comment by zneix** [comment]
You are also unable to search for messages that are "custom-built", for example the "system message" sent if token has expired, code snippet: https://github.com/Chatterino/chatterino2/blob/a6e23e246864458c9d00c469c3b7306086b8d0ed/src/providers/twitch/IrcMessageHandler.cpp#L702-L713

**Comment by erkston** [comment]
filters and highlights also do not work on automod messages, i assume for the same reasons (was trying to recreate the automod queue from the web mod view)
