### ISSUE TITLE
White bars in main window and the join window

### ISSUE THREAD

**Issue by Leppunen** [Chatterino/chatterino2#1428]
**Describe the bug**
After commit e3d3f1242558965c7e300e382fbc610737b37813 Appveyor started using Qt 5.13.2 that started causing chatterino to display white bars in the main window and the join window

**To reproduce**
Open chatterino or the channel join window.

**Screenshots**
![chatterinowhitebars](https://user-images.githubusercontent.com/11699619/69914582-9b13eb80-144e-11ea-9e74-514a7930f7b4.png)

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 624c578b0, 16.11.2019)

**Operating system**
Windows 10 1909 18363.476

**Additional information**

**Comment by th3an7** [comment]
Resizing both windows (main chat and joining one) fixes white bars - this happens only when those windows appear

**Comment by holysnipz** [comment]
Happen on ***Emote Menu*** and ***Popup Chat*** too 

![image](https://user-images.githubusercontent.com/9103583/70368256-faed1500-18da-11ea-8824-d09cbb528831.png)

**Comment by KeppanaD3sti** [comment]
![chatterino_jXoPDgFy02](https://user-images.githubusercontent.com/8891380/70822558-89cfc500-1de6-11ea-994b-377358ca9345.png)
is there a fix for this? :(

**Comment by fourtf** [comment]
@KeppanaD3sti 

If you are a developer: use a different version of At

If you are a user: use the official download from chatterino.com

**Comment by pajlada** [comment]
Qt 5.14 has been released, once it's [out on AppVeyor](https://www.appveyor.com/docs/windows-images-software/#qt) we can try upgrading to that and see if it helps.

**Comment by alazymeme** [comment]
I no longer have this issue. Is anyone able to reproduce this bug?

**Comment by apa420** [comment]
We've updated to qt 5.14 and issue is gone.
