### ISSUE TITLE
Chatterino2 doesn't correctly handle MacOS special character inputs (via keyboard) 

### ISSUE THREAD

**Issue by 554923619** [Chatterino/chatterino2#1430]
**Describe the bug**
Currently, on MacOS, attempting to type a special character the MacOS way (holding down a key, and selecting the special deviant from the list) will just spam the key, instead of waiting for the user to select a special character and inputting that

**To reproduce**
In Chatterino on MacOS, hold down the 'a' key.

**Screenshots**
![image](https://user-images.githubusercontent.com/41973452/233731025-e000a3ed-4aee-46eb-9404-a9156e05c975.png)

**Chatterino version**
Chatterino 2.1.5 (commit 624c578b0)

**Operating system**
MacOS Mojave v10.14.6

**Additional information**

**Comment by RAnders00** [comment]
sounds like something Qt should fix honestly, but I can't judge that properly

**Comment by 554923619** [comment]
Perhaps, Telegram Desktop seems to implement this correctly, I wonder how they achieve it

**Comment by 554923619** [comment]
Duplicate of #1425

**Comment by 12932** [comment]
> Duplicate of #1425

that issue is 404?

**Comment by Felanbird** [comment]
> that issue is 404?

Very interesting

**Comment by Mm2PL** [comment]
I think that's because of discussion changes, github might have deleted some discussions in our repo after a category change.

29 sie 2022 04:02:10 12932 ***@***.***>:

**Comment by Mm2PL** [comment]
Is this still replicatable on Qt 6? I think this might be a not-our-bug. I looked at our code for split input we don't do special key repeat logic there. I'd like to also know if this is replicatable with other line and text edits all around the app:
 - `Search all emotes` or `Find in all settings` inputs (plain `QLineEdit`)
 - commands/highlights/nicknames/ignores (`QTableView`)

**Comment by ashugg** [comment]
I've just tried this in Chatterino 2.5.1 on macOS 12.7.6 (Monterey) and 14.7 (Sonoma) and the long-press keyboard shortcut to access alternate characters is working for me as expected. It seems likely that Qt 6.x fixed the issue.

Chatterino 2.5.1 (commit eafcb941) built with Qt 6.5.0
Running on macOS Monterey (12.7), kernel: 21.6.0

Chatterino 2.5.1 (commit eafcb941) built with Qt 6.5.0
Running on macOS 14.7, kernel: 23.6.0

**Comment by pajlada** [comment]
@ashugg Thank you for taking the time to test this! Closing this as resolved for now then.
