### ISSUE TITLE
BTTV Christmas Emotes don't overlap other emotes

### ISSUE THREAD

**Issue by Zanuh** [Chatterino/chatterino2#1431]
**Describe the bug**
BTTV's christmas emotes doesn't overlap other emotes like they do in WebChat, they instead appear next to the emote, on the right. For example, the Sosnowy GIF emote should go over other emotes but doesn't, it appears next to it. Its confusing.

**To reproduce**
Just open Chatterino, and when you see people use these christmas emotes they appear next to other emotes. You can compare it to WebChat if you want to see the difference.

EDIT: In webchat it doesnt work with FFZ:AP or FFZ, it has to be the BTTV chrome extension for it to work properly.

**Screenshots**

CHATTERINO:
![chatterino sosnowy emote](https://user-images.githubusercontent.com/48422085/70133794-1bbd2c80-1687-11ea-8afd-ce35fc51aa91.png)

WEBCHAT:
![sosnowy works](https://user-images.githubusercontent.com/48422085/70133875-41e2cc80-1687-11ea-8a58-116a7f4fcd1e.png)

**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Operating system**
Windows 10

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/70137197-6aed6800-165b-11ea-9fe9-aac311e07af8.png)

**Comment by SLCH** [comment]
Works (with (dank) bugs) in latest nightly

**Comment by Felanbird** [comment]
Fixed in 2d3fb89
