### ISSUE TITLE
Username colors are shown as gray in Chatterino 2, even though it's not the case for web chat

### ISSUE THREAD

**Issue by agenttud** [Chatterino/chatterino2#1432]
**Describe the bug**
Some username colors are shown as gray in Chatterino, even though they appear normally in web chat.

**To reproduce**
Open a pretty active chat and have web chat and Chatterino side-by-side, then check if the usernames that are gray in Chatterino are also gray in web chat.

**Screenshots**
![chatterino color](https://user-images.githubusercontent.com/18105477/70373641-10b60680-18ea-11ea-9efc-f7f232e5a61e.png)

![chatterino clor 2](https://user-images.githubusercontent.com/18105477/70373645-17447e00-18ea-11ea-80c5-b100d17fabdd.png)

**Chatterino version**
2.1.5 (if you are confused by the theme in the second screenshot, it's just a visual modification made by TETYYS; I don't think he changed anything)

**Comment by fourtf** [comment]
There's a setting to enable colored names for people who never chose one
