### ISSUE TITLE
Zero-width emotes overlap with text

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1433]
**Describe the bug**
Zero-width emotes overlap with the name or previous text if they are placed behind non-emote things.

**To reproduce**
Type just plain `IceCold` or `<some text> IceCold` in chat

**Screenshots**
![image](https://user-images.githubusercontent.com/1629196/70376989-330e4b00-190f-11ea-9e68-5cd906abb238.png)

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 2d3fb8950, 06.12.2019)

**Operating system**
Windows 10

**Additional information**

**Comment by SLCH** [comment]
That's a feature

**Comment by Setekh79** [comment]
This is a feature of these seasonal emotes so you can stack them over normal emotes or text. Try 4head SoSnowy in chat.

**Comment by RAnders00** [comment]
They only stack over emotes, not over text when using them in the browser

**Comment by pajlada** [comment]
While I agree this isn't the intended way to use the feature, I don't want to "complicate" the feature needlessly while it's really simple right now

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
