### ISSUE TITLE
Multiple Instances of Chatterino don't open on Windows Start-up

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1434]
**Describe the bug**

When using a portable instance of Chatterino along with a "normal" version toggling on the "Start-up with windows" setting only starts up the "normal" version and the portable version does not.

**To reproduce**

- Enable "Start-up with windows" on "normal" Chatterino and a portable instance
- Restart Windows

**Screenshots**

**Chatterino version**

- "normal" version 9cb973a which is equivalent to 556c2ae
- portable version(s) 556c2ae & ce90253

**Operating system**

Windows 10 - Version 1903 (OS Build 18362.476)

**Additional information**

![image](https://user-images.githubusercontent.com/41973452/70388380-e2ced180-197e-11ea-9226-f1c1c90f32e8.png)

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
