### ISSUE TITLE
Streamer profile picture in the live notification in chatterino is broken

### ISSUE THREAD

**Issue by ricketycricket69** [Chatterino/chatterino2#1435]
**Describe the bug**
Since 2.1.5 whenever a streamer goes live it's just the standard "broken" profile picture, it works flawlessly in 2.1.4

**To reproduce**
Install 2.1.5, go to settings and then "notifications", activate "Enable Toasts" and add a channel in the tab "Channel going live"

**Screenshots**
2.1.4 
![2 1 4](https://user-images.githubusercontent.com/58735499/70535654-b6bd7700-1b5d-11ea-9778-6051b31beebf.JPG)

2.1.5 
![2 1 5](https://user-images.githubusercontent.com/58735499/70535665-bb822b00-1b5d-11ea-9ffb-96c5e10ef81c.JPG)

**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Operating system**
Windows 10 Pro Version 1909 OS Build 18363.476

**Additional information**
I also tried the latest nightly versions, it's also broken there.

**Comment by Felanbird** [comment]
Can confirm but I had completely forgotten the logo used to be there 🤔

**Comment by Nerixyz** [comment]
Fixed with #4899.
