### ISSUE TITLE
Change the volume at which the highlight sounds will be played at.

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1436]

**Comment by fourtf** [comment]
You can change the volume of chatterino in Windows

**Comment by cinemassacres** [comment]
@fourtf in Chatterino 2.1.5 (commit c6e1a1de2 ?

**Comment by fourtf** [comment]
In the windows soundmixer, yes

**Comment by cinemassacres** [comment]
@fourtf https://i.imgur.com/ihaQmVR.png

**Comment by fourtf** [comment]
I don't have a windows instance right now to check but I thought that it showed there. Maybe there needs to be a sound first before it is recognized? Or maybe I am misremembering

**Comment by fourtf** [comment]
Did this work? If it did then we should definitely make it show from the start.

**Comment by cinemassacres** [comment]
@fourtf yes
