### ISSUE TITLE
Emote AutoComplete suggestion

### ISSUE THREAD

**Issue by SPONGSPong** [Chatterino/chatterino2#1438]
is it possible to make emote autocomplete to be like this?
like when you type ":forsenh" and then emote will show like forsenHappy, forsenHobo, and else.. 

![image](https://user-images.githubusercontent.com/58819884/70724537-6137c480-1d2d-11ea-81b4-df4584450b4f.png)

**Comment by apa420** [comment]
Duplicate of #591
