### ISSUE TITLE
Adjust volume by scrolling with the mouse wheel.

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1448]
**Is your feature request related to a problem? Please describe.**
Adjust volume by scrolling with the mouse wheel.

**Describe the solution you'd like**
to Adjust volume by scrolling with the mouse wheel.
**Describe alternatives you've considered**
adjust the volume by hand

**Additional context**

have a Volume scroll amount to show How much the volume level is changed per individual scroll input.

**Comment by pajlada** [comment]
Please elaborate - we don't have any volume controller of any kind in Chatterino

**Comment by cinemassacres** [comment]
@pajlada have it in the browser extension to control the volume

**Comment by apa420** [comment]
The extension is supposed to only replace chat, not change the player.
Try ffz or bttv for these features.
