### ISSUE TITLE
Include Bit emotes in the Emote Menu

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1450]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/41973452/71301708-dbd99300-2370-11ea-9eaa-d62ba843dcbe.png)

Twitch has recently implemented emotes via bit badge tiers and they do not show up in the Chatterino Emote Menu

**Additional context**
I assume somebody smarter than me has an endpoint/api information laying around (if one exists yet)

**Screenshots**

Chatterino 
![image](https://user-images.githubusercontent.com/41973452/71301955-bb5f0800-2373-11ea-8273-c272b29778c0.png)
Browser Chat
![image](https://user-images.githubusercontent.com/41973452/71301981-fcefb300-2373-11ea-9b1e-b5192df646d9.png)

![image](https://user-images.githubusercontent.com/41973452/71301997-29a3ca80-2374-11ea-9ec5-fd266cf69ed9.png)

![image](https://user-images.githubusercontent.com/41973452/71302107-8358c480-2375-11ea-9b0d-48a3bd0a123a.png)

**Comment by fourtf** [comment]
Since there is no public API endpoint for bit emotes we can't add support for this.

**Comment by zneix** [comment]
I dislike the idea of closing issues with blocked label, so difficult to find these.

**Comment by RAnders00** [comment]
Since an implementation is now underway for this I will reopen this
