### ISSUE TITLE
clicking on anything closes the chat

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1454]
**Describe the bug**

when you clicking on anything the chat closes
**To reproduce**

click on following, browse, videos, etc will close the chat
**Screenshots**

https://streamable.com/2fars
**Chatterino version**

Chatterino 2.1.5 (commit c6e1a1de2)
**Operating system**
N/A

**Additional information**

**Comment by pajlada** [comment]
did you try selecting and reselecting the tab?

**Comment by cinemassacres** [comment]
@pajlada yes

**Comment by cinemassacres** [comment]
https://streamable.com/cyywv

**Comment by apa420** [comment]
link doesn't work. No idea what the issue is.

**Comment by cinemassacres** [comment]
@apa420 new link https://streamable.com/vpzn0p

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/36
