### ISSUE TITLE
Channel points support

### ISSUE THREAD

**Issue by Luke8498** [Chatterino/chatterino2#1455]
Add support to the new channel point system, so that you gain points for the channels that are open in your tabs. 

This could also include a way to spend points, maybe a button similar to twitch's own, that shows the current amount of channel points and when clicked opens a new window, that shows the rewards the current channel you have open has.

**Comment by pajlada** [comment]
> Add support to the new channel point system, so that you gain points for the channels that are open in your tabs.

This is not possible in Chatterino.


> This could also include a way to spend points, maybe a button similar to twitch's own, that shows the current amount of channel points and when clicked opens a new window, that shows the rewards the current channel you have open has.

If an API is made for the Channel Points, then we could implement these things. For now, there's no API for it so we are unable to do any of the things you mentioned.
I'll mark this as "blocked" pending any future updates from Twitch.

**Comment by sadlyfell** [comment]
> > Add support to the new channel point system, so that you gain points for the channels that are open in your tabs.
> 
> This is not possible in Chatterino.
> 
> > This could also include a way to spend points, maybe a button similar to twitch's own, that shows the current amount of channel points and when clicked opens a new window, that shows the rewards the current channel you have open has.
> 
> If an API is made for the Channel Points, then we could implement these things. For now, there's no API for it so we are unable to do any of the things you mentioned.
> I'll mark this as "blocked" pending any future updates from Twitch.

Its possible through hidden twitch API, Im tested it and successfully claim channel points. But it might risk a ban because this is discouraged method to use hidden twitch API.

**Comment by cinemassacres** [comment]
https://github.com/Chatterino/chatterino2/issues/1455

**Comment by Mm2PL** [comment]
@cinemassacres why did you link this issue under itself? Did you mean to post this somewhere else?

**Comment by fourtf** [comment]
There is no API for spending points so this cannot be done.

**Comment by txtsd** [comment]
> Its possible through hidden twitch API, Im tested it and successfully claim channel points. But it might risk a ban because this is discouraged method to use hidden twitch API.
@sadlyfell Where can I contact you about the mechanism?

**Comment by Mm2PL** [comment]
@fourtf Could you please open these blocked issues so they are more easily searchable? There are so many dupes of these lately. IMO even if these issues were to hang around open essentially forever, it's better to have one issue for the problem than lots of closed duplicates.

**Comment by leon-richardt** [comment]
> more easily searchable?

Could even pin them :eyes:

**Comment by Mm2PL** [comment]
https://twitch.uservoice.com/forums/310213-developers/suggestions/39185878-polls-api
https://twitch.uservoice.com/forums/310213-developers/suggestions/41966401-api-support-for-predictions

looks like this issue or #2553 needs a reopen as there will be an api

**Comment by alazymeme** [comment]
> https://twitch.uservoice.com/forums/310213-developers/suggestions/39185878-polls-api
> https://twitch.uservoice.com/forums/310213-developers/suggestions/41966401-api-support-for-predictions
> 
> looks like this issue or #2553 needs a reopen as there will be an api

Realistically, how long do you think it'll take twitch to add this?

**Comment by Mm2PL** [comment]
I don't really know and I don't think they will give an ETA, but I'll give them about a month or two.

**Comment by djanatyn** [comment]
I was just looking into this support myself, it seems there is a new API for Polls and Predictions (released May 03, 2021):
* https://discuss.dev.twitch.tv/t/announcing-apis-and-eventsub-for-polls-and-predictions/31539

> The UserVoice suggestions for a Polls API and a Channel Points Predictions API have been two of the most upvoted and discussed posts we’ve seen in the developer category. That’s one of the many reasons we are pleased to announce that Polls and Predictions are now available via the Twitch API and EventSub as a public beta.

There are several new APIs:
* Get Polls
* Create Poll
* End Poll
* Get Predictions
* Create Prediction
* End Prediction

**Comment by Mm2PL** [comment]
Even the `get ...` ones require BROADCASTER (or editor) authorization, thus these are not suitable for usage in a chat client like Chatterino.
