### ISSUE TITLE
Add a filter for channels you want to save logs for

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#1456]
**Is your feature request related to a problem? Please describe.**

I have a lot of channels joined in my Chatterino. I mod some of those, logging chat history is often really helpful, but I often end up having too many useless logs for big channels like forsen and I obviously don't need those, so that spam only takes more of my disk space.

---

**Describe the solution you'd like**

I thought of few things:
 - A table, may be a similar thing like the one with Highlights
 - Input field(s) that will let you type channel names separated by commas (e.g. "pajlada, zneix, normiestreamer123,")
 - In case you have **a lot** of those channels, then you can maybe include an option to select .txt file with channel names separated by newlines or commas

Selected channels would be logged, others not.
There could be also a tick box for enabling/disabling channel filtering in this feature.

---

**Describe alternatives you've considered**

There might be also an option to only "blacklist" certain channels but I think it is not *that* necessary to have.

---

**Additional context**
Not really, Have a good Christmas :)

**Comment by leon-richardt** [comment]
If this is implemented, it might make sense to provide an interface for generic channel-specific settings. Options like "Notify when live" or "Mute highlight sound" could then be consolidated into a common place.
Designing such an interface might be quite a bit of work though.

**Comment by apa420** [comment]
I don't think it would be that hard, you could get all open channels, create a table and have tabs with checkboxes for each of the settings

**Comment by leon-richardt** [comment]
> I don't think it would be that hard, you could get all open channels, create a table and have tabs with checkboxes for each of the settings

The "quite a bit of work" was referring to generic channel-specific settings. This feature in isolation shouldn't be too hard, I agree.

**Comment by apa420** [comment]
So you mean reworking the way the current implementations are done in a new common place for it? Just using the ones we have now and connecting the checkboxes would be easy.

**Comment by leon-richardt** [comment]
This issue might not be the right place to have this discussion, but essentially yes.

For example, the channel-specific settings "Notify when live" or "Mute highlight sound" are currently implemented in the `NotificationController` and `PingController`, respectively.
I'm wondering whether it would make sense to introduce a new interface for managing channel-specific settings in a common place rather than spreading functionality over different classes. In that case, this feature request could be implemented there.

I'm open to discussion though.

**Comment by apa420** [comment]
I do think implementations of issues is the right place to have discussions over it, where else would it be?

So yea that's what I was trying to get at.

It does make sense to introduce such an interface since it would also make it easier to implement some new channel-spefic feature.

**Comment by leon-richardt** [comment]
> I do think talking implementations of issues should be talked in the issue, where else would it be?

Maybe in a separate discussion thread as this would not only concern this specific feature.

**Comment by apa420** [comment]
I guess that's fair

**Comment by pijcab** [comment]
Any news on this feature request ? 
I was about to post about it.

**Comment by zneix** [comment]
Nope, but since I created this issue I've improved my c++ skills a bit, so I can try implementing that.  
I think that another setting in Moderation page should do the thing for this issue, however. When I look back to first @leon-richardt 's comment I'm not sure whether I should start trying to make that or just wait for a feature that will cover channel-specific settings.  

I'll try to make something anyway, but I do like the idea of channel-specific settings a lot!

**Comment by pijcab** [comment]
@zneix I'd say do it, good practice for your skills AND (not 100% sure of this but) your code could be reused for the unified channel-specific settings if it gets implemented down the road.

**Comment by leon-richardt** [comment]
Yes, I agree as well. I don't think it makes sense to postpone this for a feature that might never get implemented at all (or that is far away, at least).

Also, I feel like this should be fairly easy to port to channel-specific settings when/if they are added at some point in the feature.

**Comment by gzachariadis** [comment]
Will this be implemented? Any updates?
