### ISSUE TITLE
Add support for leppunen logs

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1457]
**Describe the solution you'd like**
Log integration: https://logs.ivr.fi
Example log link: https://logs.ivr.fi/channel/pajlada/user/fourtf

**Describe alternatives you've considered**
Cbenni, but it's down a lot

**Comment by alazymeme** [comment]
@Felanbird suggested I run this past @leppunen

@leppunen is this ok?

**Comment by cinemassacres** [comment]
@alazymeme 1 ping should do it

**Comment by alazymeme** [comment]
> @alazymeme 1 ping should do it

Please keep irrelevant discussion out of the issue

**Comment by cinemassacres** [comment]
> > @alazymeme 1 ping should do it
> 
> Please keep irrelevant discussion out of the issue

you said his name twice once should be sufficient

**Comment by Leppunen** [comment]
I'm okay with this.

**Comment by alazymeme** [comment]
> > > @alazymeme 1 ping should do it
> > 
> > 
> > Please keep irrelevant discussion out of the issue
> 
> you said his name twice once should be sufficient

Ok buddy - as per my first request, don't post irrelevant shit on my issue.

**Comment by fourtf** [comment]
Please keep it civil

**Comment by alazymeme** [comment]
This functionality was removed. Given the reasoning for twitch's takedown request on overrustle and commanderroot, I don't think this should be reimplemented.
