### ISSUE TITLE
if you have a video in picture in picture mode it takes the chat with it

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1459]
**Describe the bug**

if you have a video in picture in picture mode it takes the chat with it
**To reproduce**

a 1 in 100 chance to reproduce but have a  video in picture in picture mode then open a twitch chat and it will try to load the chaterino chat on top of the video
**Screenshots**
https://streamable.com/63sqi
https://i.imgur.com/qu5CkaM.png
**Chatterino version**
Chatterino 2.1.5 (commit c6e1a1de2)

**Operating system**
N/A

**Additional information**

**Comment by fourtf** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/29
