### ISSUE TITLE
Use Displayname for Mention

### ISSUE THREAD

**Issue by SFFan123** [Chatterino/chatterino2#1464]
If you @ a user the username is lowercase. It throws some people off if you don't match the captilazation for their name.

Use the Displayname propperty for mentions, maybe make it a setting if you want to use it.

**Additional context**

![grafik](https://user-images.githubusercontent.com/38184195/71544759-557e0c00-2983-11ea-9d6f-752029b7ef00.png)
in this example it should be `@Spaenny`

**Comment by leon-richardt** [comment]
Duplicate of #1199.
