### ISSUE TITLE
Words with ellipsis being parsed as links

### ISSUE THREAD

**Issue by fourst4r** [Chatterino/chatterino2#1466]
**Describe the bug**

Words with an ellipsis at the end are being incorrectly parsed as links.

**To reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/27849911/71555396-bc3d1b80-2a90-11ea-83bd-a89a2ce82281.png)

**Chatterino version**

Chatterino 2.1.6 (commit c5e8c5396)

**Operating system**

Windows 10

**Additional information**

**Comment by leon-richardt** [comment]
This is currently being worked on in #1462.

**Comment by fourtf** [comment]
fixed in https://github.com/Chatterino/chatterino2/commit/e12f76387a28b2d01ae5109ecd9e7b8413719f9a
