### ISSUE TITLE
Update fmtlib version to 6.0.0

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#1467]
Would make it easier to compile using system fmt on modern systems.

**Comment by fourtf** [comment]
Can we reasonably get rid of fmtlib?

**Comment by pajlada** [comment]
> Can we reasonably get rid of fmtlib?

Very reasonably - just a matter of swapping out to using qDebug everywhere (which makes sense since we're deep in qt land anyway).
I'll make a PR
