### ISSUE TITLE
chat window bugs out trying to load 2 chats in 1 channel

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1469]
**Describe the bug**

chat window bugs out trying to load 2 chats in 1 channel
**To reproduce**

eShrug
**Screenshots**

https://streamable.com/s1r6b
**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)
**Operating system**
N/A

**Additional information**

WAYTODANK

**Comment by fourtf** [comment]
can't reproduce
