### ISSUE TITLE
the chat follows you even if you not in a channel

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1470]
**Describe the bug**

the chat follows you even if you not in a channel
**To reproduce**

eShrug
**Screenshots**

https://i.imgur.com/K0aBrfo.png
**Chatterino version**

**Operating system**

the chat follows you even if you not in a channel
**Additional information**

**Comment by alazymeme** [comment]
According to my previous issue on this, this **should** be fixed. Do you still have the issue? https://github.com/Chatterino/chatterino2/issues/944

**Comment by cinemassacres** [comment]
yea https://i.imgur.com/XOYnsmc.png

**Comment by pajlada** [comment]
@cinemassacres Please recreate under https://github.com/Chatterino/chatterino-browser-ext/issues since this is an entirely extension issue
