### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by snokey** [Chatterino/chatterino2#1471]
nothing happens when pressing login (open in Browser), no tab in browser pops up

**Comment by Felanbird** [comment]
@snokey https://chatterino.com/client_login

**Comment by pajlada** [comment]
the link Felanbird posted can be used for now, however to be able to try to diagnose the issue we need more information from you about your system.

What's your Operating System?

What's your default browser?

Are you able to click links in Chatterino and have them open in your browser?

**Comment by leon-richardt** [comment]
In addition to what pajlada said, also consider using the [bug report template](https://github.com/Chatterino/chatterino2/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md&title=) when reporting future issues.

**Comment by alazymeme** [comment]
I cannot reproduce this in Chatterino Nightly 2.1.7 (commit 6d5ba0c44, 24.05.2020)
Can someone please confirm if they can reproduce this?
