### ISSUE TITLE
Instant Crashes

### ISSUE THREAD

**Issue by EhrleMirror** [Chatterino/chatterino2#1475]
Since a week now my chatternino intantly crashes after starting it. I uninstalled it (with revo uninstaller) multible times and tried older Versions too but nothing seemed to help. I didnt change anything with my hardware or software

This is how it always looks:
https://gyazo.com/779bec09f54c74761eca15b00360c71f

**Comment by apa420** [comment]
Try deleting the %APPDATA%/chatterino2/ folder

**Comment by apa420** [comment]
Also would be nice if you used the premade templates for bugs since it's
a) Easier for us to help
b) Easier for us to recreate and maybe fix

**Comment by EhrleMirror** [comment]
Im sorry im new to this, where can i add labels? 
I also deleted everything with chatterino in the %appdata% folder

**Comment by apa420** [comment]
No it's fine, but please write your os and how you installed it.

**Comment by EhrleMirror** [comment]
OS: Windows 10 1809 
Chatternino version: Tried the newest one down to 2.1.4
Installation: Chatternino installer exe from the official chatterino.com website

**Comment by tolekk** [comment]
Which version do the crashes occur at? I've had a couple of my friends mention crashes on the newest builds but I can't point out which versions crash, maybe we should figure out what changed in 2.1.0 and forward.

**Comment by EhrleMirror** [comment]
Im not 100% sure but i think every version after 2.1.0 gives me that problem. Its weird because it worked for a while, like i was always on the newest version it just recently stopped working suddenly.

**Comment by fourtf** [comment]
can't reproduce
