### ISSUE TITLE
Non links recognized as links?

### ISSUE THREAD

**Issue by dozzzz02** [Chatterino/chatterino2#1479]
**Describe the bug**
If you type just anything with 3 dotss behind it, it gets recognized as a link

**To reproduce**
^

**Screenshots**
https://i.imgur.com/WZGXvcn.png

**Chatterino version**
2.1

**Operating system**
Win 10

**Comment by pajlada** [comment]
@dozzzz02 This has been fixed in release 2.1.7 which you should be able to update to in the top right corner (or a fresh install from https://chatterino.com)
