### ISSUE TITLE
Mixer settings don't save

### ISSUE THREAD

**Issue by Superfraggle** [Chatterino/chatterino2#1480]
In order to prevent pings coming through on stream,  I need to route the audio to specific audio devices. currently it is only the default. 

I would like an option in the main menu to choose an audio device from the available out puts, and then I could choose one to direct the audio alerts to. 

Whilst I can do this within windows, the app somehow manages to not honour it after   a restart (possible bug)

**Comment by pajlada** [comment]
I believe the best way forward is to fix the bug you mentioned in the third paragraph. There are two steps to it:
1) Ensure we have an always-on audio output so Chatterino is always visible in the operating system's mixer
2) Ensure the mixer settings are saved after a restart

**Comment by fourtf** [comment]
This issue would require big changes to the internals (including an audio library just for the sound) of the program. As the payoff for this is small I don't think this is worth fixing.
