### ISSUE TITLE
Make chat printable using CTRL+P

### ISSUE THREAD

**Issue by tolekk** [Chatterino/chatterino2#1482]
**Is your feature request related to a problem? Please describe.**
I hate how i can't print out my conversation with randers, i want to hang them all on my wall.
**Describe the solution you'd like**
Make it so CTRL+P shortcut opens up a page to print the chat log :)

**Describe alternatives you've considered**
It could also screenshot the chat and print that :)

**Additional context**
![image](https://user-images.githubusercontent.com/48994738/71765125-fb37fa80-2ef0-11ea-8b72-0d2c8beb2804.png)

**Comment by Mm2PL** [comment]
I'd deny this or delay it until customizable shortcuts are a thing.

**Comment by apa420** [comment]
Why did this get closed, seemed like a good feature

**Comment by zneix** [comment]
> I'd deny this or delay it until customizable shortcuts are a thing.

Now that #2340 is on its way to be soon implemented, maybe we can reopen this and consider adding a print function?

**Comment by Mm2PL** [comment]
![pepeLaugh](https://cdn.betterttv.net/emote/5d652c36375afb1da9a691ab/1x)

**Comment by MrAuro** [comment]
#2340 got merged in so maybe this could be reopened? ![ApuThink](https://cdn.7tv.app/emote/60ae4105aee2aa5538457ba1/1x)
