### ISSUE TITLE
Collapsable chat tabs.

### ISSUE THREAD

**Issue by tolekk** [Chatterino/chatterino2#1484]
**Is your feature request related to a problem? Please describe.**
I hate how half of my chatterino screen is taken up with chat tabs, I want to be able to see more of the actual chat. Also I'm technically limited on the amount of chats I can join due to this.

**Describe the solution you'd like**
Make the chat tabs collapse into a scroll-down or a differently navigated menu so that more chat can fit on the screen. 

**Describe alternatives you've considered**
I have no alternatives on my mind at the moment.

**Additional context**
As most people are probably as lazy as I am, the chat adding menu is not perfect, you have to type in, or copy the whole name which takes more time than optimal in my opinion, that's why I keep all the tabs open. This feature is also helpful for people like me, who host multiple bots for people whose chats I want to keep open so people can ping me.
![image](https://user-images.githubusercontent.com/48994738/71765259-95e50900-2ef2-11ea-9034-5f3803b78d5f.png)

**Comment by pajlada** [comment]
Related issue: #388 
Other ways of displaying tabs could also be explored, maybe a single line horizontal scrollable tab list reasonable (this would hide tabs, so another feature like CTRL+K would help)

**Comment by apa420** [comment]
What about scrolling down and up rows on channels?

![](https://i.nuuls.com/Ds-No.png)

![](https://i.nuuls.com/dfLOA.png)
would be different scroll-things for example

**Comment by tolekk** [comment]
As apa imagined it seems really good, one row that would resize depending on the window width that would be scrollable vertically or horizontally, but in groups of how many tabs fit on the screen - not how it is currently implemented, as I believe current single-tab scrolling is inefficient.

**Comment by zneix** [comment]
@tolekk would hiding tabs be enough? I have a draft pr for it, you can check it out.

**Comment by ALazyMeme** [comment]
I can see @zneix mentioned in his pr that this issue was related. Is there some part of this issue that the pr didn't fix?

**Comment by pajlada** [comment]
Closing since I think #2600 solves for this use-case.

**Comment by mjeveritt** [comment]
if you have a lot of channels, and your window is docked to the side of the screen, you can end up with this scenario: 
<img width="474" height="857" alt="Image" src="https://github.com/user-attachments/assets/10f81f59-d3c3-4807-82d4-fa012541d737" />
where the bottom set of channels is .. Missing .. (hidden).

would it be a total nightmare to add a scrollbar for the channels list/notebook/thingy?
my original use case was indeed solved in https://github.com/Chatterino/chatterino2/pull/2600 nicely, but if you need to 'prune' some channels, you're gonna have to resize your window and reset it with this issue ..

[Edit]: Addendum, why doesn't the 'Sort channels by name alphabetically' have a check-box beside it .. how do you 'uncheck' or indeed, see if its enabled/disabled?!? 🤔 
[Edit2]: oh heck, it's a one-shot function isn't it .. 🙄

**Comment by Nerixyz** [comment]
> would it be a total nightmare to add a scrollbar for the channels list/notebook/thingy?

With the current implementation, I'd say yes - not impossible, but it's likely going to be 🍝. The main reason for this is that the tab layout is implemented manually and has to support all four locations (top, right, left, bottom). There are reasons for this (e.g. animations when a tab is moved). It would be great if we could improve on this. Maybe we could use a layout from Qt or subclass a `QLayout` (though some of the "interesting" size min/max functions are private afaik). 

> oh heck, it's a one-shot function isn't it .. 🙄

There are backups for your window layout in your settings ([Where is my Chatterino folder located?](https://wiki.chatterino.com/Settings/#where-is-my-chatterino-folder-located)).

**Comment by mjeveritt** [comment]
> > oh heck, it's a one-shot function isn't it .. 🙄
> 
> There are backups for your window layout in your settings ([Where is my Chatterino folder located?](https://wiki.chatterino.com/Settings/#where-is-my-chatterino-folder-located)).

Dude, that IS genius .. I had spotted these, but hadn't really thought of a decent use case.. 🤣
