### ISSUE TITLE
"Jump to" feature/shortcut

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1485]
**Is your feature request related to a problem? Please describe.**

When you have a lot of tabs it can be hard to locate a tab purely from looking at them and then clicking on the right one.

**Describe the solution you'd like**

I would like a quick navigator popup that can be activated with a keyboard shortcut that finds tabs for me, and can activate the found tab when pressing enter.
Similar to the navigator you can activate with Ctrl-K on discord:
![image](https://user-images.githubusercontent.com/1629196/71765380-4c95b900-2ef4-11ea-99f2-da4f066b6246.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by tolekk** [comment]
This would go nicely with #1484 if properly implemented. More navigation options with less clutter should be one of the priorities in my opinion.

**Comment by leon-richardt** [comment]
I think this can been closed with the merge of #1588.
