### ISSUE TITLE
Won't connect to chat

### ISSUE THREAD

**Issue by Kakernak** [Chatterino/chatterino2#1493]
Will not connect to a chat, despite message in the chat stating 'reconnected ' when I hover over chat tab I see 'offline' despite streams not being offline, no messages are seen and no users can be seen. 

How to replicate: Launching the application and it not working.

![chatterino uh](https://user-images.githubusercontent.com/59707991/72100566-25d7e800-3323-11ea-8226-091100b9b982.png)

Chatterino version: 2.1.7

Operating system: windows 10

Additional info: Clicking reconnect does nothing. I've read through everything over here and on reddit trying different things, nothing worked (relogging, adding exceptions to firewall etc.)

**Comment by pajlada** [comment]
This feels like an environment-based problem. Do you have any sort of firewall installed on your machine that might be interfering?

**Comment by fourtf** [comment]
May be resolved by https://github.com/Chatterino/chatterino2/pull/1513

Could you try the newest nightly and see if this fixes the issue?

**Comment by apa420** [comment]
Is this still an issue @Kakernak

**Comment by fourtf** [comment]
inactive
