### ISSUE TITLE
Sort the emtoes in the emote picker

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#1494]
**Is your feature request related to a problem? Please describe.**

The emotes in the emote picker aren't sorted :/
**Describe the solution you'd like**

Sort them alphabetically so they're easier to browse.
**Describe alternatives you've considered**

Searching 
**Additional context**

**Comment by pajlada** [comment]
Emote sets should probably be sorted as they are right now, and emotes within a set should be sorted by tier and then name
