### ISSUE TITLE
show how many timeouts a person has

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1495]
**Is your feature request related to a problem? Please describe.**

show how many timeouts a person has
**Describe the solution you'd like**

show how many timeouts a person has if mod
**Describe alternatives you've considered**

not using chaterino 
**Additional context**

**Comment by apa420** [comment]
There is no api for what you're suggesting from twitch.

**Comment by Mm2PL** [comment]
There probably is some GQL or other undocumented endpoint we can use, but that would mean that every time the API changes the client breaks.

**Comment by apa420** [comment]
Chatterino does not use GQL endpoints since they're only meant for twitch's 1st part applications

**Comment by alazymeme** [comment]
You can do this as a mod by doing `/user <user>` - should show exactly how many timeouts they have.

**Comment by pajlada** [comment]
The solution alazymeme posted is the supported one
