### ISSUE TITLE
Render chat to video

### ISSUE THREAD

**Issue by ldesgoui** [Chatterino/chatterino2#1501]
**Is your feature request related to a problem? Please describe.**
I would like to be able to stitch chat to the side of VODs with as little human assistance required as possible

**Describe the solution you'd like**
Chatterino2 seems like a decent codebase to implement this with, chat rendering is already implemented, rendering widgets to pixel buffers is available through QT (https://doc.qt.io/qt-5/qwidget.html#grab), there might even be possibility to do it headless (https://doc.qt.io/qt-5/qoffscreensurface.html), saving frames as images would be Good Enough

**Describe alternatives you've considered**
Using OBS to record Chatterino2 or Twitch web would be hard to script I reckon

**Additional context**
I expect to implement this feature myself
I'm mostly looking for feedback and/or ideas

**Comment by fourtf** [comment]
Easiest way is probably to require the user to have ffmpeg in the path pipe it into ffmpeg with a pipe (stdin/out)

**Comment by ldesgoui** [comment]
Related work: https://github.com/lay295/TwitchDownloader (I'm a Linux user though!!!)

**Comment by goldbattle** [comment]
Was there a reason this was closed?

**Comment by fourtf** [comment]
This issue is out of scope of the chatterino project.
