### ISSUE TITLE
the ffz api shows emotes that are not global

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1503]
**Describe the bug**

the ffz api shows emotes that are not global they cause a problem for  Chatterino
**To reproduce**

Go to https://api.frankerfacez.com/v1/set/global
See AndKnuckles OiMinna OBOY
**Screenshots**

N/A
**Chatterino version**
N/A
**Operating system**

N/A
**Additional information**

https://github.com/FrankerFaceZ/FrankerFaceZ/issues/723

**Comment by TranRed** [comment]
duplicate of #1116
