### ISSUE TITLE
open links  by clicking middle mouse button

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1506]
**Is your feature request related to a problem? Please describe.**

 Browsers start opening links when clicking the middle mouse button. Chatterino should do that also

**Additional context**

Behaviour should be similar to the implementation in browsers.

**Comment by fourtf** [comment]
I don't see why opening links should be bound to two mouse buttons

**Comment by gempir** [comment]
Personally I click almost all links with middle mouse button since it prevents the browser from opening it in the current tab.

Although Chatterino is not a website with the chrome extension it kinda feels that way sometimes and muscle memory kicks in.
