### ISSUE TITLE
Stream category in hover text is always lowercase

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#1508]
**Describe the bug**
When hovering over the split header, the stream category in always displayed in all lowercase.

**To reproduce**
Open a Twitch channel in a split and hover over the split header.
Observe that the category is set in all lowercase.

**Screenshots**

![lowercase_title](https://user-images.githubusercontent.com/35232120/72689458-eb83fd00-3b11-11ea-9586-dada89ea68d0.png)

**Chatterino version**

Chatterino 2.1.7 (commit 476825dc3)

**Operating system**

Arch Linux, i3

**Additional information**

n/a

**Comment by leon-richardt** [comment]
After some more analysis, it seems that the game title is already lowercase on the API response. For exxample, this is a current API response:
```json
{ 
    "_id":36717842928,
    "game":"escape from tarkov",
    "broadcast_platform":"live",
    "community_id":"",
    "community_ids":[ 

    ],
    "viewers":32086,
    "video_height":1080,
    "average_fps":60,
    "delay":0,
    "created_at":"2020-01-20T21:47:48Z",
    "is_playlist":false,
    "stream_type":"live",
    "preview":{ 
        "small":"https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-80x45.jpg",
        "medium":"https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-320x180.jpg",
        "large":"https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-640x360.jpg",
        "template":"https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-{width}x{height}.jpg"
    },
    "channel":{ 
        ...
    }
}
```

Note that the `game` field is already in all lowercase.

**Comment by apa420** [comment]
That's really weird. My chatterino shows the game properly capitalized. I'm using a week old build for arch (i3).

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/72903225-dd450500-3cfa-11ea-955a-6b5aa2621cff.png)
This issue was confirmed to be a twitch bug which is why an issue report was never opened, the issue was fixed a day or so ago which would explain why you were unable to replicate it @apa420
