### ISSUE TITLE
Suggestion: Channel organization

### ISSUE THREAD

**Issue by gauerrr** [Chatterino/chatterino2#1509]
Chatterino should have an option to organize the channel list by how long you spent in their chat, doesn't seem like something hard to do and would be better than having to organize them alphabetically in case you have OCD

**Comment by leon-richardt** [comment]
Personally, I think that letting users organize the channel list themselves is the most flexible solution overall.

**Comment by gauerrr** [comment]
> Personally, I think that letting users organize the channel list themselves is the most flexible solution overall.

I think you got me wrong, what I mean is I think they should let the user choose between the current organization method and the "how long you spent there" method, they should never throw away a method that's already working

**Comment by apa420** [comment]
Don't think tracking how long you've spent in a tab seems that nice to be honest. Either this doesn't really seem that useful overall.
I agree with @leon-richardt
