### ISSUE TITLE
some emotes don't show up in the chat

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1510]
**Describe the bug**

some emotes don't show up in the chat
**To reproduce**

post a emote in chat
**Screenshots**

https://i.imgur.com/kZAAlO8.png
**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)
**Operating system**

win 10
**Additional information**

**Comment by apa420** [comment]
Try and clear your cache, that might fix it

**Comment by alazymeme** [comment]
I haven't seen any issues on my end in regards to this. Are you still able to reproduce it?
