### ISSUE TITLE
the title can stretch father then needed when hovered over

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1514]
**Describe the bug**

the title can stretch father then needed when hovered over
**To reproduce**

hover over a long title
**Screenshots**

https://i.imgur.com/g45dYpD.png
**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)
**Operating system**

Win 10
**Additional information**

**Comment by fourtf** [comment]
I set a max width for it
