### ISSUE TITLE
Option to disable hotkeys or hotkey

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1515]
**Is your feature request related to a problem? Please describe.**
Sometimes I press Ctrl+W on accident (don't notice chrome isn't focused, cat walked on keyboard), which messes up whole layout :(

**Describe the solution you'd like**
Option to disable all hotkeys or only Ctrl+W. I don't ever use hotkeys.

**Describe alternatives you've considered**
Removing W key on my keyboard, this however has many downsides

**Comment by leon-richardt** [comment]
An option to disable hotkeys should also definitely be considered if custom hotkeys are ever going to be implemented in Chatterino.

**Comment by apa420** [comment]
Closed in favour of #1592
