### ISSUE TITLE
Tab completion breaks when completions include spaces.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1517]
**Describe the bug**

Tab completion will insert completions with spaces, but will never delete the first word.

**How to reproduce**

1. Create a command that has a space in the name.
2. Type the first word,
3. Press tab a couple times
4. Observe the first word not being deleted while the next words are inserted.

**Chatterino version**

`Chatterino 2.1.7 (commit a078d116d)`

**Operating system**

Ubuntu

**Additional information**

This could be fixed by storing the start position of the tab completion and not deleting the current word.
Usernames on Twitch never have spaces inside, so this could have not been tested. 

**Video of this bug**
https://i.nuuls.com/3kosd.mp4

**Comment by fourtf** [comment]
I don't think this is worth fixing.
