### ISSUE TITLE
Timeouts / Bans when you click on an user's name in the search bar

### ISSUE THREAD

**Issue by VulpesHD** [Chatterino/chatterino2#1520]
Since the usercard already knows what channel I search in, it would be nice if the timeout/ban buttons showed up as well, when I'm a moderator in the channel I searched in.
It would make it easy to timeout multiple people at once when I search for a keyword.
Image for reference: [https://imgur.com/a/unKwQai](https://imgur.com/a/unKwQai)

**Comment by apa420** [comment]
You opened this issue already
Duplicate of #1089
