### ISSUE TITLE
New highlight system: subscription colors gets affected by highlighted users colors

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1521]
**Describe the bug**
Subscription color is ignored and user highlight color is used.

**To reproduce**
![chatterino_rSNY4iZB39](https://user-images.githubusercontent.com/3091645/73140666-2ba02e00-4084-11ea-8551-617dbec8b678.png) 
![chatterino_q84CLDhUXI](https://user-images.githubusercontent.com/3091645/73140675-365ac300-4084-11ea-96a4-baecb21082f7.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit bfee75ec5, )

**Comment by leon-richardt** [comment]
I'm having a hard time reproducing this. Could you try walking me through the exact steps you took when adding the highlights?

**Comment by TETYYS** [comment]
i modified colors on some highlights in messages tab, dont remember which ones. then i set it all red on usernames

**Comment by leon-richardt** [comment]
Just to be sure: The user that triggered the subscription message was not part of your user highlights, correct?

**Comment by TETYYS** [comment]
thats correct

**Comment by TETYYS** [comment]
happens only when i set xqcow user highlight to red, not sure if thats because he's last or something

**Comment by leon-richardt** [comment]
Does the issue still occur when you remove and re-add the highlight for `xqcow`?

**Comment by TETYYS** [comment]
yes

**Comment by leon-richardt** [comment]
Okay, I managed to reproduce after restarting Chatterino; leading me to believe that this might be a serialization issue.

**Comment by leon-richardt** [comment]
Quick update: I believe I have found the issue but I would rather do some more testing before opening a PR.

**Comment by leon-richardt** [comment]
From what I can find, #1522 should resolve this problem.

Good catch @TETYYS, and thanks for the report!
