### ISSUE TITLE
Whispers showing in mentions when not pinged

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1523]
**Describe the bug**
When `Whispers` is enabled under highlights, all whispers show in your mentions box (regardless of if you were mentioned or not)

**To reproduce**
1. Settings > Highlights > Turn on Whispers
2. Make someone whisper you and it should show in your `/whispers` and `/mentions` box

**Screenshots**
https://i.nuuls.com/hWJ-q.png
https://i.nuuls.com/_Nb-F.png

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 497ce2d2f, )

**Operating system**
Windows 10

**Comment by leon-richardt** [comment]
Thanks for the report, this should be fixed by #1524.
