### ISSUE TITLE
"More messages below" only works from second time

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1525]
**Describe the bug**
"More messages below" sometimes needs to be clicked two times in order to get it working

**To reproduce**
https://i.nuuls.com/PeEwW.mp4

**Chatterino version**
Chatterino Nightly 2.1.7 (commit bfee75ec5, )

**Operating system**
Windows 10 18362.356

**Comment by fourtf** [comment]
can't reproduce

**Comment by apa420** [comment]
there's a delay before it goes down, because of the animation
