### ISSUE TITLE
Unable to send whispers

### ISSUE THREAD

**Issue by RIFLABACONBBX** [Chatterino/chatterino2#1526]
**Describe the bug**
I can not send whispers from chatterino. When sending whispers i get a message "Your settings prevent you from sending this whisper."

**To reproduce**
https://streamable.com/1jw42
https://i.imgur.com/11l8toI.png

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 2d3fb8950, 06.12.2019)

**Operating system**
win10

**Additional information**
sending whispers to friends also don't work, email is also verified

WideHardo

**Comment by alazymeme** [comment]
This was a spam protection measure put in place by twitch. This is not a chatterino bug.

Try sending a whisper to your friend from the twitch website, it will "send", but they'll never receive it. It just so happens that chatterino tells you that the whisper wasn't sent, whereas the twitch website doesn't. Only way to fix this is to add friends as friends on twitch (contacting twitch might also work)

**Comment by alazymeme** [comment]
@pajlada Can this one be closed?
