### ISSUE TITLE
Allow for certain users when pinging you to have custom Ping Sounds/Highlight Colors

### ISSUE THREAD

**Issue by DuskDarker** [Chatterino/chatterino2#1528]
**Is your feature request related to a problem? Please describe.**
Sometimes I get pinged, check my mentions and realize that it was not somebody trying to get my attention but instead a bot saying my name for some reason. 

**Describe the solution you'd like**
Add a new toggle-able option in the Highlights -> Users Tab where you can choose if the certain user has to say one of your pings for it to go off. Basically just so you can customize the sound of the ping and the highlight color. 

**Describe alternatives you've considered**
This feature could alternatively be placed in the Highlights -> Messages Tab instead.

**Comment by pajlada** [comment]
You can ignore highlights from bots, by clicking their name and pressing "Ignore Highlights". Does this solve your issue?

**Comment by DuskDarker** [comment]
I mean sort of but it would be nicer to just be able to distinguish what is pinging you instead. Like let's say someone set a reminder for you on a bot. I would appreciate it more to know that it was a bot than nothing at all.

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
