### ISSUE TITLE
Cannot see automod messages and who timed someone out when mod in Chatterino

### ISSUE THREAD

**Issue by DuskDarker** [Chatterino/chatterino2#1532]
**Describe the bug**
Chatterino basically treats me like a normal chatter even when mod in chats. I can still time things out and have no message delay but cannot see who timed a user out and any automod message.  

**To reproduce**
I do not remember exactly how it happened but it did around the time I opened the moderation tab in settings. Other than that I do not know how it happened. 

**Screenshots**
https://imgur.com/a/EnphjnL 
https://imgur.com/a/Az8kqRe

**Chatterino version**
I have had the same issue on multiple versions of chatterino (Nightly 2.1.7, Nightly 2.1.5, Nightly 2.1.0) 

**Operating system**
Windows 10 

**Additional information**
Yes I have tried closing and opening chatterino and have tried adding and removing my twitch account back to chatterino, and fully restarting my PC

**Comment by Dolev24** [comment]
i have the same problem

**Comment by 5E7EN** [comment]
This has become an issue due to a recent change to PubSub and oauth scopes. 
The topic on which moderator actions are relayed over, now needs an additional scope - one of which Chatterino hasn't been given access to during your initial login.

I believe the change has been implemented but has not yet been pushed to the website so sit tight for now.
Once it is updated, you'll just need to re-login over at https://chatterino.com/client_login and update your credentials in the application.

CC: @fourtf

**Comment by 5E7EN** [comment]
I've setup a temporary token generator that should fix the issue until the site is updated. Visit https://5e7en.me/chatterino/client_login_temp.html -> Login -> Copy the return string to your clipboard -> Go to your Chatterino settings and remove your current user account -> Click the Add button and select "Paste login info" -> Restart Chatterino.

Note that this is all done on the client-side meaning no info is processed on the server. The source code is available at view-source:https://5e7en.me/chatterino/client_login_temp.html

**Comment by RIFLABACONBBX** [comment]
> i have the same problem

dolv and ska are the nicest mods thumpSmile

**Comment by 5E7EN** [comment]
@RIFLABACONBBX 
Please keep this thread relevant to the conversation. 😄

**Comment by RIFLABACONBBX** [comment]
@5E7EN ok sorry brooo

**Comment by 5E7EN** [comment]
The main login page seems to have been updated. Simply re-login there and it should be working again.
