### ISSUE TITLE
Enable CTRL+END to scroll to bottom / resume scrolling (standard Windows shortcut)

### ISSUE THREAD

**Issue by pengowray** [Chatterino/chatterino2#1533]
In Chatterino you can click "More messages below" to resume scrolling. It would be nice to if you could use the standard shortcut `ctrl`+`end` to do this too. It doesn't look like there's a keyboard shortcut for this already, but would be good to have `ctrl`+`end` too even if there is.

`ctrl`+`end` works across all normal text fields in Windows, such as in this text box I'm writing in this in now, and in other chat apps (e.g. Discord). It's also used in KDE, Gnome and Emacs. On MacOS the equivalent is `Cmd`+`↓`.

The counterpart is `ctrl`+`home` to scroll to the top, which would make sense to implement too, but is less important.

* Reference: https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts
(listed under "Go to end of document")

**Comment by pengowray** [comment]
In Discord, the `esc` key also does a similar thing (it additionally resets the "new" red bar). I don't know if you want to copy their use of `esc`, or you might find a better use for the ESC key, but thought I'd mention it.

**Comment by Mm2PL** [comment]
`Page up` and `page down` could also be used to scroll the chat
