### ISSUE TITLE
Add an option to ask for confirmation when doing CTRL W

### ISSUE THREAD

**Issue by nitrousGranola** [Chatterino/chatterino2#1535]
I often find myself wait to close a browser tab with ctrl w, but forgetting that I'm tabbed into Chatternio and close that tab instead of whatever I had open in my browser.

**Comment by leon-richardt** [comment]
I feel like asking for confirmation goes against the idea of a key shortcut. Instead, like suggested in #1515, would an option to disable certain hotkeys solve your problem as well?

**Comment by fourtf** [comment]
To improve error tolerance I believe that we should ask for confirmation.

**Comment by Mm2PL** [comment]
Duplicates #339

**Comment by pajlada** [comment]
Closing as duplicate of #339
