### ISSUE TITLE
Is there a way to hide messages with a specific phrase on it?

### ISSUE THREAD

**Issue by gauerrr** [Chatterino/chatterino2#1536]
I'm aware that you can censor specific words/phrases, what I'm looking for is to completly ignore any message with a specific word/phrase on it (not even show the message), cause there are some really annoying spammers on twitch who mods don't seem to care about (specially on NYMN's chat). If this feature doesn't exist, take it as a feature request.

**Comment by 5E7EN** [comment]
Go to Settings -> Ignores -> Messages
Be sure to check "Block" to ignore the message completely. It's worth noting that this won't either show messages that you send which contain the phrase.
