### ISSUE TITLE
error while loading shared libraries: libboost_filesystem.so.1.71.0

### ISSUE THREAD

**Issue by jp1995** [Chatterino/chatterino2#1537]
**Describe the bug**
Launching chatterino after updating my manjaro system today results in 
`chatterino: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory`

**To reproduce**
Run chatterino with an up to date manjaro system

**Chatterino version**
Latest AUR release, tried rebuilding/reinstalling

**Operating system**
Manjaro, kernel 5.4.17-1

**Additional information**
pacman -Qs boost results in
```
local/boost 1.72.0-1
    Free peer-reviewed portable C++ source libraries - development headers
local/boost-libs 1.72.0-1
    Free peer-reviewed portable C++ source libraries - runtime libraries
```
Initially looks like I'm a version ahead of what chatterino is expecting to find.
However, `locate libboost_filesystem.so.1` results in
```
/usr/lib/libboost_filesystem.so.1
/usr/lib/libboost_filesystem.so.1.71
/usr/lib/libboost_filesystem.so.1.71.0
```
Is this a me problem or a you problem?

Cheers, love what you do.

**Comment by fourtf** [comment]
Reinstalling from AUR and selecting `clean build` worked for me. (Using yay)

**Comment by jp1995** [comment]
Ah, that did the trick for me. Thanks, sorry for the bother
