### ISSUE TITLE
Crashes when resizing the color picker dialog

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1538]
**Describe the bug**
Resizing the ColorPickerDialog to an extremely small size causes a crash. The size needs to be less than 100x100px. Probably due to a division by 0 or something similar.

**To reproduce**
Disable the minimum size of the dialog or use a window manager that allows resizing without limits like i3/sway. Keep resizing the dialog until it crashes.

**Comment by leon-richardt** [comment]
Maybe I'm doing something wrong but i3 does not let me resize below a certain size. :thinking:

**Comment by Mm2PL** [comment]
same

**Comment by fourtf** [comment]
who gives a fuck
