### ISSUE TITLE
Default message highlighting columns selectable

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1539]
**Describe the bug**
The columns "Custom sound" and "Color" of the default Patterns ("Your name", "whispers", "subscriptions") are selectable (highlighted blue) even though all the other columns aren't.

**To reproduce**
Select all columns using Ctrl+A in Settings->Highlights->Messages.

**Screenshots**
![20200210_15h43m00s_grim](https://user-images.githubusercontent.com/6320036/74159654-68d7f480-4c1c-11ea-86b6-1b1a6eb017f6.png)

**Comment by leon-richardt** [comment]
So should they all be selectable? Or all unselectable?

**Comment by fourtf** [comment]
Since they cannot be removed IMO unselectable
