### ISSUE TITLE
Highlight sound settings are confusing

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1540]
- "Play sound" and "Custom sound" are very far away. Columns need to be reordered to make more sense.
- "Cancel" in the file picker removes the custom sound. However there is no proper way to reset the custom sound appart from that.
- "Fallback sound" settings is hard to understand.
  - Why is it a checkbox? Can we remove the checkbox and call it "Default sound:"?

![20200210_16h28m32s_grim](https://user-images.githubusercontent.com/6320036/74163456-b48d9c80-4c22-11ea-9a9b-26981b1aec0e.png)

**Comment by Mm2PL** [comment]
The fallback sound check box should be removed imo, however the setting itself is really useful

**Comment by leon-richardt** [comment]
Yeah, I'm not content with the design of the sound settings either. If anyone comes up with a better design, feel free to either implement it yourself or drop the idea here so I can implement it at some point in the future.

**Comment by TomasTokaMrazek** [comment]
Let me try. I would personally get rid of the checkbox, implicitly enable it, and rename "fallback" to "default".

In other words:
* If no custom default sound is set, use the standard sound shipped with the app.
* If custom default sound is set, use that.

From the UX standpoint, there would be one button with text "Change default sound", and if changed, maybe have the filename label with X to remove it.

**Comment by Nerixyz** [comment]
How about this:

![](https://user-images.githubusercontent.com/19953266/193056731-6e9fc94d-1c7a-4483-8ae6-999025c75f3e.png)

<details><summary>Without custom/default sound</summary>

![](https://user-images.githubusercontent.com/19953266/193057157-96a31f5f-6518-4061-ac26-6bb10b4abd9e.png)

I'm not sure about the default name.
</details>

**Comment by 8thony** [comment]
@Nerixyz Your suggestion looks good. 
The name is fine IMO, but you can set a tooltip with further explanation if you think it's unclear.
