### ISSUE TITLE
Allow reordering elements in list settings

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1542]
**Is your feature request related to a problem? Please describe.**
Elements in lists in the settings cannot be reordered. However the order is relevant (highlight processing order/moderation button order).

**Describe the solution you'd like**
Add buttons that move the item one step up or down.

**Screenshot**
![20200210_17h35m53s_grim](https://user-images.githubusercontent.com/6320036/74169951-6e3d3b00-4c2c-11ea-8e2a-f61457765f0b.png)

**Comment by leon-richardt** [comment]
Being able to reorder elements via drag-and-drop would also be nice, if possible.
