### ISSUE TITLE
Use custom highlight colors in tabs

### ISSUE THREAD

**Issue by DuskDarker** [Chatterino/chatterino2#1543]
**Describe the solution you'd like**
Currently when a highlight goes off in a chat that you have been pinged in, the taskbar of that chat flashes red. Why not have it so the taskbar of that certain chat tab flashed the color of the highlight which pinged you.  

**Additional context**
If my explanation didn't make enough sense, here is a screenshot of what I am saying. https://imgur.com/a/KKHfq2X This tab would instead flash the color of your chosen highlight

**Comment by fourtf** [comment]
The color of the altert in the taskbar cannot be changed

**Comment by apa420** [comment]
#1557
