### ISSUE TITLE
Load message history on connect option seems bugged

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#1547]
**Describe the bug**
Chatterino 2.1.7 (commit 14427fe5a) does not load the messages history on connect

**To reproduce**
Open a channel on Chatterino 

**Chatterino version**
Chatterino 2.1.7 (commit 14427fe5a)

**Operating system**
Debian 10.3

**Comment by Mm2PL** [comment]
It's not Chatterino
it's the api Chatterino uses

**Comment by bennyhillthebest** [comment]
Sorry, i did not know
