### ISSUE TITLE
chatterino version 2.1.7 MacOS app crash by clicking mark all whisper as read

### ISSUE THREAD

**Issue by martinc527** [Chatterino/chatterino2#1550]
**Describe the bug**

chatterino version 2.1.7 MacOS app crash 

**To reproduce**

when i click mark all whisper as read on twitch page, app close crash and close.

**Screenshots**

[![Screenshot from Gyazo](https://gyazo.com/f6e926a520b036d39ea0cdffd2c039bd/raw)](https://gyazo.com/f6e926a520b036d39ea0cdffd2c039bd)

[![Screenshot from Gyazo](https://gyazo.com/6347e4d864c3f22e99d0f940d9037672/raw)](https://gyazo.com/6347e4d864c3f22e99d0f940d9037672)

**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**

macOS Catalina Version 10.15.3

**Additional information**

https://ghostbin.co/paste/r32yh

**Comment by pajlada** [comment]
The crash wasn't meant to occur in release builds - turns out the build you're using is a debug build. I will look into this in #1551 

@martinc527 Where did you download your macos build from?
