### ISSUE TITLE
Separating emote tabbing from user tabbing

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1552]
I'd like to see an option (similar to chatterino 1), but "religiously" follows those rules, with no lenience. In this case, in order for a user to be tab completed, they would **have** to prefix the username with @ - but emotes do not require any prefix (or maybe even an optional : or something)

![image](https://user-images.githubusercontent.com/12804673/74590097-0e44fb00-5057-11ea-8ddc-16b281ab76fc.png)

**Comment by pajlada** [comment]
I'd see a setting "Only tab usernames with an @" or something as useful :+1:
