### ISSUE TITLE
Reset frame of gif animations

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1556]
It would be useful to reset all gif emotes to frame 0 so they are synced. 
This is important for split emotes like pajaWalk1 pajaWalk2 pajaWalk3

To reproduce this the out of sync gif emotes they need to be typed in chat the first time emote by emote. So that It loads 1 emote and in the next message it loads the next one. Now they are likely out of sync.

A keyboard shortcut would be useful aswell, or maybe double bind it with F5.

**Comment by fourtf** [comment]
This approach has downsides which IMO make it impossible to add.
- It being a hotkey limits learnability. The majority of users who are displeased by the described issue will never learn about this fix. This means that the issue does not get solved for all users.
- With more effort we can automatically sync emotes of same length and speed.
