### ISSUE TITLE
Add the ability to resize the browser extension

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1564]
**Is your feature request related to a problem? Please describe.**
Could potentially solve any issues relating to "no channel points" or "no scam train" integration issues

**Describe the solution you'd like**
Exactly the same as chatterino: the ability to hold Ctrl and readjust the size of the window

**Comment by fourtf** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/38
