### ISSUE TITLE
Better highlights: When upgrading version, "migrated" notification settings have black as default color

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1565]
**Describe the bug**
When you upgrade chatterino2 to a version with the new highlighting updates, old phrases you had before the upgrade all have black set as their highlight color.
I don't think this should be the default experience for most users. I would expect the color to be the default "red" that was used before.

**To reproduce**
see above

**Screenshots**
example of my experience when upgrading

![image](https://user-images.githubusercontent.com/1629196/75114391-dd1b8a80-5655-11ea-8420-563ea89f0be4.png)
![image](https://user-images.githubusercontent.com/1629196/75114428-17852780-5656-11ea-9bbc-f55d93281095.png)

**Chatterino version**

`Chatterino Nightly 2.1.7 (commit 53e52e189, )`

**Operating system**
windows 10

**Additional information**

**Comment by leon-richardt** [comment]
Thanks for the report!

**Comment by RAnders00** [comment]
I propose default color should be `#4C2C31FF` (alpha 255) since that's what was used before, however it gets more complex if you apply color mixing

**Comment by leon-richardt** [comment]
Yeah, the current default color tries to strike a compromise between the different themes, that's why the Alpha channel is at 50%. Setting different defaults for different themes is also tricky at the time of color deserialization since `Application::getApp()` is not available yet.

**Comment by RAnders00** [comment]
so i did some math and the equivalent alpha=127 color that would get extremely close (or even exact, idk about the rounding) to the original color: R 127, G 63, B 73 (`#7f3f49`)

Here's the calculation for future reference: https://www.wolframalpha.com/input/?i=round%28%280x31%2F255+-+%281-127%2F255%29+*+0x19%2F255%29%2F%28127%2F255%29+*+255%29

In this case I was trying to find the "mixing" color at alpha=127 the would yield `#4C2C31` with a background of `#191919` (default background color). Substitute the 0x19 in the formula with the background's color, and 0x31 with the result color and do calculation channel-by-channel.
