### ISSUE TITLE
Pause chat doesn't work if the extension is not in focus

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1567]
**Describe the bug**
The chat pausing doesn't work when the extension is not in focus

**To reproduce**
1. scroll up in chat
2. click on twitch page
3. it should scroll back to the current point in time

**Screenshots**
https://i.nuuls.com/9I6Dj.gif

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 2b5c6ffe3, )

**Operating system**
Windows 10

**Comment by fourtf** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/39
