### ISSUE TITLE
Show new followers of the channel

### ISSUE THREAD

**Issue by VulpesHD** [Chatterino/chatterino2#1569]
Show every new followers of the channel you are connected to with account creation date and follow date (and let us export the selected ones by like holding shift/ctrl and clicking on the names or just the whole list). (like how chatty has it but without the 100 newest followers limit.)

![ZokUdkF](https://user-images.githubusercontent.com/28871321/75214551-443c5a80-578e-11ea-961c-8d245a89c466.png)

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
