### ISSUE TITLE
Make the duplicate message character configurable

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1572]
**Is your feature request related to a problem? Please describe.**

Yes, a streamer i watch has recently blacklisted `U+F000` and I would like to change it to something else or disable it for that channel.

**Describe the solution you'd like**

I would like channels to have an option to disable the duplicate message workaround and/or an option to change it.

**Describe alternatives you've considered**

Recompiling Chatterino every time I want to change the character 4HEad

**Additional context**

> Your message wasn't posted due to conflicts with the channel's moderation settings.

**Comment by apa420** [comment]
Just recompile chatterino with new character, it's that easy. 
Kapp

**Comment by RAnders00** [comment]
There should also be an option to disable the alternate-message mechanism altogether (which was suggested in #1933)

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
