### ISSUE TITLE
Bold @username option doesn't work

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1577]
**Describe the bug**
The bold username option does not work

**To reproduce**
1. Turn it on
2. notice it doesnt work when you try to @ someone

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/75607242-bb803e80-5b40-11ea-8d47-bbf9f009b78b.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 82354327e, )

**Operating system**
Windows 10

**Comment by Mm2PL** [comment]
can confirm with a custom font (Fira Code Light)

**Comment by fourtf** [comment]
try changing this 
![image](https://user-images.githubusercontent.com/6320036/75607646-96b4a880-5af9-11ea-84b9-7c835caf1c2e.png)

**Comment by Mm2PL** [comment]
no change for me
i reposted the @ for every screenshot

https://i.imgur.com/rFywesc.png
https://i.imgur.com/doH14e5.png
https://i.imgur.com/IOY2QoD.png
https://i.imgur.com/AQbGb1X.png

**Comment by alazymeme** [comment]
Ok so this seems to work for me, but due to the fact that I use 50 username font weight; I think it is incredibly faint. Are we able to have these two options separated? Like a mention font weight and username font weight? I like my 50 font weight, and dont particularly want to up that in order to see bolded mentions.

@Mm2PL Not sure why it's not working for you. Fira Code Light works just fine for me:
![image](https://user-images.githubusercontent.com/12804673/75615620-d4651000-5b91-11ea-9554-df857607fa2b.png)

**Comment by alazymeme** [comment]
I believe that this might be an issue specifically with this font. 50/Default actually does change things. Anything beyond that and no usernames change.

**Comment by pajlada** [comment]
Closing due to it just being a font issue.

**Comment by alazymeme** [comment]
The font weight of 50 nulls the @ bolding from even working. I think the font weight and @ bold weight should be two separate options.
