### ISSUE TITLE
Hovering some links gives odd error

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1579]
**Describe the bug**
Hovering some links says "too big". This is not a good error.

**To reproduce**
Hover a link to a large file, such as https://i.nuuls.com/WtquH.jpeg

**Screenshots**

![image](https://user-images.githubusercontent.com/6320036/75615977-0737e580-5b4b-11ea-9bb5-f23d1fee74f9.png)

**Comment by Mm2PL** [comment]
from what i understand this is an API issue, not chatterino it self.

**Comment by pajlada** [comment]
I'm tracking a github issue now in the api service to clarify some errors https://github.com/Chatterino/api/issues/11

**Comment by pajlada** [comment]
Error clarified to "Response too large (>5MB)" in https://github.com/Chatterino/api/commit/430f35655796c126b41f7da280edca536c6a1c25
