### ISSUE TITLE
Browser extension formatting issue

### ISSUE THREAD

**Issue by Borinius** [Chatterino/chatterino2#1581]
**Describe the bug**
When using the extension directly in the browser or when the [watching] tab is used on the desktop client the text seems to bug up and it cant decide what row to stay on. Its like something invis is changing size to the right or something with the chatbox so the text has to reformat to fit. Also while this issue is present the chat wont stop going to newest message when srcolling back in chat, the fix below will however solve this temporarily aswell.

**To reproduce**
This can be reproduced by having the chat open in client[watching tab] or directly on twitch and the text flickering will be there from when i click open the stream, this will refresh upon switching stream. And to fix it temporarily in client i need to switch tab then go back, and for the extension i need to interact with it in some way like ctrl + r(sometimes) and close it or clicking into the chatbox and it will stop trying to format and work until i repeat previous steps.
**Screenshots**
Two recordings showing both issues. this is from extension but the same thing is happening in the [watching] tab in the client aswell.
https://streamable.com/cwmbv
https://streamable.com/lbxtt
**Chatterino version**
client- Chatterino 2.1.7 (commit 845c8fa63)
browser- 1.2 Firefox

**Operating system**
Win10

**Additional information**
Did some more testing before i sent this and any focus to firefiox with chat open will make it start formatting flicker. And a loss of focus will fix it untill focus is given back. Also clicking the chatbox area will fix it as long its clicked waiting for me to write something. Clicking out again will resume the formatting flicker.

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/37
