### ISSUE TITLE
Emoji in tab title not centered

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1584]
**The Problem**
Emojis are not centered in the title of tabs. (More space on the left than the right)

**To reproduce**
Rename a tab and include an emoji

**Screenshots**
![image](https://user-images.githubusercontent.com/9765622/75624700-f329cd80-5bb6-11ea-9a60-ae5d70ecda90.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 5ad427bd6, )

**Operating system**
Windows 10

Edit: 
![image](https://user-images.githubusercontent.com/9765622/75624926-6f251500-5bb9-11ea-89af-ca6f2a493c0d.png)

In the input it looks like a space but I can't remove it. 

@apa420 confirmed its broken for him on win 8 aswell. Was working for pajlada on linux.

**Comment by fourtf** [comment]
Cannot the fixed unless Qt changes the way it renders emojis.
