### ISSUE TITLE
twitch badge tooltips are not consistent

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1585]
**Describe the bug**
Tooltips for tooltips originating from twitch are not consistent. Sometimes they indicate that they are from Twitch and sometimes they don't.

**Screenshots**
![image](https://user-images.githubusercontent.com/6320036/75625346-8b2ab580-5bbd-11ea-864b-45a5fb6d580e.png)

![image](https://user-images.githubusercontent.com/6320036/75625349-91209680-5bbd-11ea-958c-a05d03f1be12.png)

![image](https://user-images.githubusercontent.com/6320036/75625350-967de100-5bbd-11ea-9c2a-2ed9425709ba.png)

**Additional information**
I suggest that all badge tooltips from twitch start with "Twitch: ", e.g. "Twitch: Channel Moderator" and "Twitch: GLHF Pledge"

**Comment by pajlada** [comment]
The "Twitch Channel Moderator" is a hardcoded tooltip set in `FfzEmotes.cpp` - that could be changed to be in line with the response we get from the Twitch badges API which just specifies "Moderator" https://badges.twitch.tv/v1/badges/global/display?language=en

**Comment by Felanbird** [comment]
The inconsistency exists because of 6f5c4ca in which I didn't realize there was another hard-code effecting ffz custom badges, which #1619 will fix.
