### ISSUE TITLE
Animated emotes don't show up

### ISSUE THREAD

**Issue by Skyirox** [Chatterino/chatterino2#1589]
Hi,
All the emotes shows up except the animated ones like below with Clap :

![chatterino_2020-03-03_21-00-58](https://user-images.githubusercontent.com/38259937/75814837-ba465000-5d92-11ea-96af-bc7e87b71db3.png)

Here you can see my emotes settings in case you were wondering :

![chatterino_2020-03-03_21-02-32](https://user-images.githubusercontent.com/38259937/75814840-ba465000-5d92-11ea-97ff-ab7c8f771bb5.png)

I already cleared my cache once and I don't know what wrong,
Thanks for your help in advance :)

**Comment by Mm2PL** [comment]
bttv is currently dead,
not a chatterino issue.

**Comment by Skyirox** [comment]
Little detail, I'm talking about the app, I don't use chatterino's extension for twitch, and I see the animated emotes on twitch chat but not on chaterrino's app

**Comment by Skyirox** [comment]
Reinstalled Chatterino for the second time, now everything works perfectly
