### ISSUE TITLE
Keybind to Open Viewer List

### ISSUE THREAD

**Issue by ktc64** [Chatterino/chatterino2#1590]
Some sort of keybind to quickly open up the viewer list without having to dive 2 menus deep in the channel dropdown. 

![image](https://user-images.githubusercontent.com/61775978/75855862-2a6bca80-5dc1-11ea-9278-97575395764c.png)

**Comment by apa420** [comment]
#1592 related and will likely resolve your issue

**Comment by fourtf** [comment]
closing in favor of https://github.com/Chatterino/chatterino2/issues/1592
