### ISSUE TITLE
Question: Why can I not see shortcuts for SplitHeader menus?

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1591]
![img](https://user-images.githubusercontent.com/25011746/75998176-550c6f00-5ef8-11ea-88f2-0619bf2a853a.png)
I'm running `Chatterino 2.1.7 (commit 2e39dd4d9)` on Linux, with i3 as my window manager and compton as my compositor. What could be the cause of this behavior?

**Comment by fourtf** [comment]
Do you mean shortcuts or mnemonics? Either way, none of them exist.

**Comment by Mm2PL** [comment]
For example in https://user-images.githubusercontent.com/61775978/75855862-2a6bca80-5dc1-11ea-9278-97575395764c.png this image you can see that `Ctrl+R` is a shortcut for `Change channel`
I would like to see these.

**Comment by apa420** [comment]
There is a keybindings tab in the settings 

![](https://i.nuuls.com/yD7le.png)

**Comment by Mm2PL** [comment]
I updated my system and they weirdly started showing, closing the issue.
