### ISSUE TITLE
Custom hotkeys

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1592]
**Is your feature request related to a problem? Please describe.**

Unwanted hotkeys can be a problem see #1515. 

**Describe the solution you'd like**

I would like for the client to have a list of shortcuts, if none is found the default shortcuts are filled in. Hotkeys would be categorized by scope (this decides where the shortcut is registered and where it works). Each shortcut would need to contain the **scope**, **key_sequence** and **action**. These would be stored in a list in the `settings.json` file. All widgets would have to have a list of defined  **actions**, for example for a `split` that could be:
  - change_channel
  - close
  - open_popup
  - open_search
  - etc.

**Describe alternatives you've considered**

Not doing it and sticking to hard-coded shortcuts.

**Additional context**

Example hotkey:
```
{
  "scope": "split",
  "key_sequence": "Ctrl+L",
  "action": "clear"
}
```
I'm posting this because I didn't find the feature request, sorry if there is one for this already

**Possible implementation**
  1. Create a new controller for keybinds. That would store the currently registered actions and the scopes they belong in.
    1. Create a `Action` struct that would hold information about a particular keybind: the scope of it, the action name, the function connected to it and possibly the default key combo (this could be put in a separate file to make changing default hotkeys easier, but it would make adding new ones harder)
    2. The controller should save actions with the functions they are connected to.
  2. Find every single keybind in the program. **Note: My list is probably incomplete**
  3. Replace with appropriate calls to the controller.

**Comment by Mm2PL** [comment]
Here is a list of shortcuts' definitions:
```
Split.cpp
    // Initialize chat widget-wide hotkeys
    // CTRL+W: Close Split
    createShortcut(this, "CTRL+W", &Split::deleteFromContainer);

    // CTRL+R: Change Channel
    createShortcut(this, "CTRL+R", &Split::changeChannel);

    // CTRL+F: Search
    createShortcut(this, "CTRL+F", &Split::showSearch);

    // F5: reload emotes
    createShortcut(this, "F5", &Split::reloadChannelAndSubscriberEmotes);

    // F10
    createShortcut(this, "F10", [] {
        auto *popup = new DebugPopup;
        popup->setAttribute(Qt::WA_DeleteOnClose);
        popup->show();
    });


Window.cpp
    // Window::addDebugStuff
    createWindowShortcut(this, "F6", [=] {
        const auto &messages = miscMessages;
        static int index = 0;
        auto app = getApp();
        const auto &msg = messages[index++ % messages.size()];
        app->twitch.server->addFakeMessage(msg);
    });

    createWindowShortcut(this, "F7", [=] {
        const auto &messages = cheerMessages;
        static int index = 0;
        const auto &msg = messages[index++ % messages.size()];
        getApp()->twitch.server->addFakeMessage(msg);
    });

    createWindowShortcut(this, "F8", [=] {
        const auto &messages = linkMessages;
        static int index = 0;
        auto app = getApp();
        const auto &msg = messages[index++ % messages.size()];
        app->twitch.server->addFakeMessage(msg);
    });

    createWindowShortcut(this, "F9", [=] {
        auto *dialog = new WelcomeDialog();
        dialog->setAttribute(Qt::WA_DeleteOnClose);
        dialog->show();
    });

    // window::addshortcuts
    
    // Open settings
    createWindowShortcut(this, "CTRL+P", [] { SettingsDialog::showDialog(); });

    // Switch tab
    createWindowShortcut(this, "CTRL+T", [this] {
        this->notebook_->getOrAddSelectedPage()->appendNewSplit(true);
    });

    // CTRL + 1-8 to open corresponding tab.
    for (auto i = 0; i < 8; i++)
    {
        char hotkey[7];
        std::sprintf(hotkey, "CTRL+%d", i + 1);
        const auto openTab = [this, i] { this->notebook_->selectIndex(i); };
        createWindowShortcut(this, hotkey, openTab);
    }

    createWindowShortcut(this, "CTRL+9",
                         [this] { this->notebook_->selectLastTab(); });

    createWindowShortcut(this, "CTRL+TAB",
                         [this] { this->notebook_->selectNextTab(); });
    createWindowShortcut(this, "CTRL+SHIFT+TAB",
                         [this] { this->notebook_->selectPreviousTab(); });

    // Zoom in
    {
        auto s = new QShortcut(QKeySequence::ZoomIn, this);
        s->setContext(Qt::WindowShortcut);
        QObject::connect(s, &QShortcut::activated, this, [] {
            getSettings()->setClampedUiScale(
                getSettings()->getClampedUiScale() + 0.1f);
        });
    }

    // Zoom out
    {
        auto s = new QShortcut(QKeySequence::ZoomOut, this);
        s->setContext(Qt::WindowShortcut);
        QObject::connect(s, &QShortcut::activated, this, [] {
            getSettings()->setClampedUiScale(
                getSettings()->getClampedUiScale() - 0.1f);
        });
    }

    // New tab
    createWindowShortcut(this, "CTRL+SHIFT+T",
                         [this] { this->notebook_->addPage(true); });

    // Close tab
    createWindowShortcut(this, "CTRL+SHIFT+W",
                         [this] { this->notebook_->removeCurrentPage(); });

    // Reopen last closed split
    createWindowShortcut(this, "CTRL+G", [this] {
        if (ClosedSplits::empty())
        {
            return;
        }
        ClosedSplits::SplitInfo si = ClosedSplits::pop();
        SplitContainer *splitContainer{nullptr};
        if (si.tab)
        {
            splitContainer = dynamic_cast<SplitContainer *>(si.tab->page);
        }
        if (!splitContainer)
        {
            splitContainer = this->notebook_->getOrAddSelectedPage();
        }
        this->notebook_->select(splitContainer);
        Split *split = new Split(splitContainer);
        split->setChannel(
            getApp()->twitch.server->getOrAddChannel(si.channelName));
        splitContainer->appendSplit(split);
    });

    createWindowShortcut(this, "CTRL+H", [this] {
        getSettings()->hideSimilar.setValue(!getSettings()->hideSimilar);
        getApp()->windows->forceLayoutChannelViews();
    });


    // Window::addMenuBar

    // Window menu.
    QMenu *windowMenu = mainMenu->addMenu(QString("Window"));

    QAction *nextTab = windowMenu->addAction(QString("Select next tab"));
    nextTab->setShortcuts({QKeySequence("Meta+Tab")});
    connect(nextTab, &QAction::triggered, this,
            [=] { this->notebook_->selectNextTab(); });

    QAction *prevTab = windowMenu->addAction(QString("Select previous tab"));
    prevTab->setShortcuts({QKeySequence("Meta+Shift+Tab")});
    connect(prevTab, &QAction::triggered, this,
            [=] { this->notebook_->selectPreviousTab(); });

EmotePopup.cpp
    // constructor

    createWindowShortcut(this, "CTRL+Tab", [=] { notebook->selectNextTab(); });
    createWindowShortcut(this, "CTRL+Shift+Tab",
                         [=] { notebook->selectPreviousTab(); });
```

**Comment by Mm2PL** [comment]
A couple of non-obvious actions:
   - `split_input.undo`
   - `split_input.redo`
   - `split_input.copy`
   - `split_input.paste`
   - `split_input.delete` Deletes the selection
   - `split_input.select_all`
   - `split_input.clear` Clears the input box

**Comment by Mm2PL** [comment]
Actions could also be triggered by commands and such.

**Comment by Mm2PL** [comment]
I would like to add `arguments` to this proposal. Action arguments could be a list of `strings` that tell the actions the specifics of what to do.
Example:
```json
{
  "scope": "tab",
  "key_sequence": "Alt+H",
  "action": "focus",
  "arguments": [
    "left"
  ]
}
```

**Comment by rossbellingham** [comment]
Hey, got curious and started looking at custom keybinds... i'd like to be able to open the current tab in streamlink, either with a "keybind", or, sending a message in that chat (obviously the message would be totally truncated - was thinking more along the lines of a chatterino command?) 

Regardless i'd like to see this feature, and I could even offer help, i've had a look at the source to see if i can fudge a simple solution for what i want but, i got hungry and gave up...

**Comment by Mm2PL** [comment]
![ch2shortcuts2020-09-01_14-43](https://user-images.githubusercontent.com/25011746/91852940-03e3fa80-ec51-11ea-8c3e-4c54333e61ff.png)
:)

**Comment by fourtf** [comment]
also: keybinding to clear messages

**Comment by fourtf** [comment]
also: open viewer list

**Comment by leon-richardt** [comment]
Also: Open in web browser/player/streamlink

**Comment by zneix** [comment]
Also: turn on/off/toggle streamer mode.

**Comment by pdf** [comment]
Also: quit application, some platforms don't have a global keybind for this

**Comment by Mm2PL** [comment]
Also: change tab locations in notebook. 
![if you read](https://i.imgur.com/yU9wcXm.png)
![this i von](https://i.imgur.com/jfiOzM8.png)

**Comment by haltdev** [comment]
> Also: Open in web browser/player/streamlink

I'm too stupid to follow this thread and the linked https://github.com/Chatterino/chatterino2/pull/2340 page.  Is it possible to make a hotkey to open s stream in streamlink?

**Comment by MrAuro** [comment]
> > Also: Open in web browser/player/streamlink
> 
> I'm too stupid to follow this thread and the linked #2340 page. Is it possible to make a hotkey to open s stream in streamlink?

@haltdev You can add a hotkey that does this by clicking the Add button in the Hotkeys panel and select the "Split" category and select the "Open Stream in Streamlink" action. 

You may need the [Nightly version](https://github.com/Chatterino/chatterino2#nightly-build) if you are running a release that doesn't have this feature

![image](https://user-images.githubusercontent.com/35087590/148489169-0ec828c5-e186-42a1-8970-202d75786f2e.png)

**Comment by haltdev** [comment]
Thank you @MrAuro ! I needed the Nightly build - all I was seeing in Settings was "Keybindings" and it wouldn't let me change any of them.  Thanks for your help!

**Comment by Buggy12345** [comment]
Hi, I'm not sure if this is the right place to ask this, but hopefully it's not too wrong either

I was wondering how to set up custom hotkeys for the ban/unban/timeout buttons in the popout window, so that I can use my 1-12 keyboard/mouse buttons. It appears to be possible, but I have very low understanding of how programming/coding works, despite looking through pages here to try and figure it by myself. If it is something I have to figure out by myself still, I would appreciate if someone could point me in the right direction with some steps.

_If this is relevant, I do have the latest Nightly build._
(screenshot attached to clarify which buttons I'm talking about)
![image](https://user-images.githubusercontent.com/97466073/148821848-00a3b718-a65b-4587-afc3-cb9de9331370.png)

**Comment by Mm2PL** [comment]
> I was wondering how to set up custom hotkeys for the ban/unban/timeout buttons in the popout window, so that I can use my 1-12 keyboard/mouse buttons. 

@Buggy12345 This isn't yet possible. Thanks for the no-so-intended reminder on adding this feature!

**Comment by TheRealDadbeard** [comment]
Is there any way to have hotkeys globally so I can use them without having the windows being active? I pretty much have to have chatty and chatterino on at the same as as this one feature is missing.

**Comment by haltdev** [comment]
> Is there any way to have hotkeys globally so I can use them without having the windows being active? I pretty much have to have chatty and chatterino on at the same as as this one feature is missing.

I use AutoHotKey for this. If Chatterino is open, my hot key will open the current tab in Streamlink. If chatterino is not open, the hot key will launch chaterrtino and open the current tab in streamlink. I have the hot key mapped to a stream deck button.
