### ISSUE TITLE
Add the bttv graph timeout thing

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1593]
**Describe the solution you'd like**
When clicking on a user, display a graph for timeouts - this could show in the user card or become a right click feature: https://i.nuuls.com/4CGnc.png

**Describe alternatives you've considered**
Using web chat with the bttv extension

**Comment by alazymeme** [comment]
This is exactly what I'm talking about: https://i.nuuls.com/IFTs4.gif

**Comment by fourtf** [comment]
We already have buttons to time people out for different amounts of time. Thus this issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
