### ISSUE TITLE
Switch in split menu bar that hides messages from listed bots and the messages that contain their prefixes.

### ISSUE THREAD

**Issue by nitrousGranola** [Chatterino/chatterino2#1596]
My idea for this is a little switch that sits at the top where the channel name is. This would use a user defined list to hide messages from bots. Could also have a mode that hides messages with prefixes.

Another way to implement this would be a drop down menu with switches to turn individual bots on and off, with a master switch at the top. This could allow you to temporarily show a specific bot. Optional bot messages to show when they have mentioned your notify tags could be thrown into this as well. 

This would likely have to be enabled on a per channel basis for people that are moderators/mini mods.

**Comment by apa420** [comment]
How about a new issue with Channel-based user ignores and channel-based regex ignores, doesn't that sound so much better than your solution?

**Comment by fourtf** [comment]
You can already ignore certain users or block them from pinging you. A filter system that's being added may solve this issue. However this alone does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
