### ISSUE TITLE
Can only type in channel's im subbed to

### ISSUE THREAD

**Issue by bontalor** [Chatterino/chatterino2#1599]
**Describe the bug**

Can only type in channels I am subbed to

**To reproduce**

Type in one channel, comment doesn't come up. Type in another channel that I am subbed to, comment does come up.

**Screenshots**

https://i.imgur.com/hY1O8eW.gif

**Chatterino version**

2.1.7

**Operating system**

Win 10

**Comment by bontalor** [comment]
It randomly fixed idk why

**Comment by fourtf** [comment]
You were globally banned, this is unrelated to chatterino
