### ISSUE TITLE
Re-implement seconds for timestamp settings.

### ISSUE THREAD

**Issue by RightToBearArmsLOL** [Chatterino/chatterino2#1605]
**Is your feature request related to a problem? Please describe.**
Previously it was possible to have seconds in your timestamp settings. I am not sure exactly when this was removed but I found [this commit](https://github.com/Chatterino/chatterino2/commit/f3357cf0f49de6e2511aa2805d0e8395fdca855c#diff-0bf2c8237d2d93560d6c5013db818186R22) which includes multiple options to include seconds in the timestamp. 

**Describe the solution you'd like**
Ideally the previous options would return, adding `:ss` options to the current drop down box for timestamp selection. 

**Describe alternatives you've considered**
Alternatively, the dropdown option could remain the same (without seconds options) to keep the choices simple for the majority of users, but with the option to manually type a timestamp format into the box, allowing users to manually add `:ss` if they prefer. Currently if you do this, it is ignored (because it is considered an invalid option iirc).

**Additional context**
I am pretty sure it wasn't removed this long ago, but I found an [April 2018 issue](https://github.com/Chatterino/chatterino2/issues/313) that has a screenshot with seconds in the timestamp.

**Comment by pajlada** [comment]
You can add `:ss` in the text field to add seconds. However, I would like the seconds timestamp setting back as well. 👌

**Comment by RightToBearArmsLOL** [comment]
Strange, I did try that multiple times and it never stuck (including saving the settings and restarting chatterino). Managed to make it stick now, by adding `:ss` to settings.json timestamp string with chatterino closed, and deleting the settings backup files. Then on launch i have seconds in my timestamp again. Guess that sorts it for me ty :smile:.
