### ISSUE TITLE
Title's category resetting itself to ID after minute

### ISSUE THREAD

**Issue by holysnipz** [Chatterino/chatterino2#1606]
**Describe the bug**
Stream's category *(game name)* in chat title revert itself back into ID after around 1 minute, doesn't matter if current chatroom and/or Chatterino is in focus or not

**To reproduce**
 - Enable `Category` under Chat Title in settings
 - Either join new chatroom or reopen Chatterino
 - Wait until category id got resolved and changed into category name
 - Continue waiting until around a minute passed
 - Previously resolved category name change itself back into category id

**Screenshots**
![image](https://user-images.githubusercontent.com/9103583/76724022-04103c80-677c-11ea-9642-b671c0cc9315.png)

![image](https://user-images.githubusercontent.com/9103583/76724006-f5c22080-677b-11ea-9648-7b7bb454dfce.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 881c8892c, 14.03.2020)

**Operating system**
Windows 10 1909 Build 18363.720

**Comment by pajlada** [comment]
Thank you for the report! Fixed :smile:
