### ISSUE TITLE
FFZ emotes do not load in Chatterino

### ISSUE THREAD

**Issue by Vafarien** [Chatterino/chatterino2#1608]
Bug:
When opening up chatterino and letting it load the channel, FFZ emotes no longer load.

Steps:
Open Chatterino.exe , navigate to the channel tab, the emotes menu, see under FFZ "no emotes available"

Chatterino version:
Chatterino 2.1.7 (commit 845c8fa63)

OS:
Windows 7 Home Premium 64-bit SP1

Screenshot:
![chatterino](https://user-images.githubusercontent.com/2349950/77209087-984f0c00-6aba-11ea-9108-9207308ba649.png)

**Comment by 5E7EN** [comment]
This is a FFZ related issue. Nothing can be done on Chatterino's end, unfortunately.
https://i.imgur.com/ZXwYHkG.png
