### ISSUE TITLE
Formatting chat messages in Chatterino

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1610]
**Is your feature request related to a problem? Please describe.**

I would like to have formatting in Twitch chat.

**Describe the solution you'd like**

I would like for the `U+E0000 U+E0000` character combo to be treated as a pseudo escape character. This combined with markdown could be used for formatting that is invisible to other clients while leaving normal text intact.
A control sequence, like markdown syntax would be structured like this: `U+E0000 U+E0000 MARKDOWN_TOKEN U+E0000`, if special characters in non-escaped text should work like they do now, do nothing.

So for example, 
  - `U+E0000U+E0000__U+E000boldU+E0000U+E0000__U+E000` would result in __bold__,
  - `U+E0000U+E0000_U+E0000emphasisU+E0000U+E0000_U+E0000` would result in _emphasis_,
  - `U+E0000U+E0000~~U+E000strikethroughU+E0000U+E0000~~U+E0000` would result in ~strikethrough~,
  - etc.

It might be possible to emulate new lines using this technique, so `ESC SPACE U+E0000` could be rendered as `\n` but this feature could be abused to spam the chat even more.

**Things that cannot be done right now**
These are features of Markdown that are impractical or outright impossible in Twitch chat
  - inline images using markdown syntax
  - multiline code blocks (` ```[...]``` `)
  - tables
  - horizontal rules

**Describe alternatives you've considered**

Not doing it

**Additional context**

Extensive wiki about terminal escape codes that could be an inspiration: https://www.xfree86.org/4.5.0/ctlseqs.html

**Comment by fourtf** [comment]
Since this is not supported in twitch chat this would be irritating to other users.
