### ISSUE TITLE
Image scaling without interpolation

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1611]
**Describe the bug**
Profile pictures are scaled down in a bad way, I think this is because there is no interpolation used

**To reproduce**
Open user card of a user that has sharp lines in their profile picture. The effect is quite noticeable e.g. on manga-style drawings etc.

**Screenshots**
(Open the image in a new tab and set zoom level to 100% to see the effect properly)
![image](https://user-images.githubusercontent.com/1629196/77462717-cc049b80-6e04-11ea-884c-130e3d9d8a31.png)
The black border around the goat is all jagged and missing in some places.

Just the scaled-down profile picture from chatterino (cut from the screenshot above):
![image](https://user-images.githubusercontent.com/1629196/77463147-74b2fb00-6e05-11ea-8536-86ce111b3913.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 95c909b33, )

**Operating system**
windows 10

**Additional information**
on my computer the little preview thing on the usercard is 88 by 88 pixels.
I downloaded the profile picture from the example above and scaled it using GIMP with various interpolation algorithms.

Original image:
![image](https://user-images.githubusercontent.com/1629196/77462990-2dc50580-6e05-11ea-8100-6d3355deb986.png)

Scaled to 88x88 with Interpolation set to None:
![image](https://user-images.githubusercontent.com/1629196/77463008-361d4080-6e05-11ea-8eda-aff2be802681.png)

Linear:
![image](https://user-images.githubusercontent.com/1629196/77463032-433a2f80-6e05-11ea-8dad-093999728469.png)

Cubic:
![image](https://user-images.githubusercontent.com/1629196/77463051-49301080-6e05-11ea-8a63-da89f84148c7.png)

I think this illustrates the difference between no interpolation and linear/cubic well enough.

It's probably worth exploring whether there are other less noticeable places in Chatterino where images are scaled without interpolation, e.g. in emotes/emojis or possibly other places I can't think of in the moment.

**Comment by fourtf** [comment]
Unfortunately hard to do with Qt. This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.

**Comment by RAnders00** [comment]
I assume https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-18875 is relevant? Then since it‘s unresolved on Qt‘s end, good decision to close.
