### ISSUE TITLE
bttv's cvMask and cvHazmat are not going over other emotes as they should

### ISSUE THREAD

**Issue by SapTheseCasters** [Chatterino/chatterino2#1612]
**Is your feature request related to a problem? Please describe.**
BTTV added cvMask and cvHazmat so that they are "equipped" on other emotes for covid19 awareness and describe how they are used in this tweet and reply https://twitter.com/jacksacktwitch/status/1243261380695900167 and works on browser chat https://i.imgur.com/NHKm6hL.png

**Describe the solution you'd like**
Make them overlap other emotes like Christmas emotes did and as it works in browser chat

**Comment by Mm2PL** [comment]
here's why:
@pajlada made a list of zero-width emotes which are modifiers, the winter emotes. This list is not dynamic, so if BTTV adds a new emote that is a modifier, Chatterino doesn't know that the emote should be rendered as a modifier.

There are two ways we could go about fixing this:
  1. Find a way to get list all modifier emotes from BTTV.
  2. The quick fix: add the emotes to the list of zero-width emotes.
