### ISSUE TITLE
Add support for Highlighted Messages (Twitch Points)

### ISSUE THREAD

**Issue by akaKrypt** [Chatterino/chatterino2#1614]
Currently when someone redeems a highlighted message it shows as a normal message, when streaming this can be a turn off for using chatterino since people's highlights don't show up.
https://i.imgur.com/cPGCK5j.png
https://i.imgur.com/hzPrRhb.png

**Comment by apa420** [comment]
Your wording is terrible, is this what you meant?:
When someone highlights you in a message and it happens that the message is a redeemed message, this message won't show up in /mentions or trigger the mentions pings etc?

**Comment by akaKrypt** [comment]
No, the new channel points feature on twitch. When someone redeems "Highlight my message" it shows up as a highlighted message in normal twitch chat, but in chattering it shows as a completely normal message. The problem is that people spend points to highlight their messages, but the streamer can't even see they highlighted it if using chatterino.

**Comment by cinemassacres** [comment]
#1455

**Comment by fourtf** [comment]
fixed in next version
