### ISSUE TITLE
Transparent background on program

### ISSUE THREAD

**Issue by pepemaluza** [Chatterino/chatterino2#1618]
**Is your feature request related to a problem? Please describe.**
I'd like to get a transparent background on chat so I can have vlc windowed or borderless with streamlink and have the chat be on top of vlc. (Imagine chat with theatre mode on phone)
I'm wondering if it's possible, thanks

**Comment by pajlada** [comment]
Not 100% sure how viable this is, but I'll leave it up

**Comment by leon-richardt** [comment]
Linking #1501 for completeness, as an implementation of either feature might make use of the other one.

**Comment by alazymeme** [comment]
> Not 100% sure how viable this is, but I'll leave it up

- Streamer plays in borderless windowed
- Streamer has `Always on top` enabled so they can always see their chat
Allowing the transparency factor will allow them to see their game more, while also being able to see chat

**Comment by Holdo** [comment]
Not just for streamers but for viewers as well, I recently tried to adjust CSS to make chat background transparent with shadowed text and the viewing experience was **so much better** since I had the video fullscreen.

**Comment by codevenkat** [comment]
Hey, any updates on anyone working on this? I'm still looking for this feature.

**Comment by Holdo** [comment]
@codevenkat why don't you try it since you like C++? Hell I would try as well but it's a long time since I've done some C++ and I've never worked with Qt.

**Comment by codevenkat** [comment]
@Holdo 

Haha, I guess I could. I've not really worked too much with Qt either but I have tried it out to some amount in the past.

**Comment by Holdo** [comment]
Inspiration:

![transparentChat](https://user-images.githubusercontent.com/10115368/114285246-fc41cb00-9a55-11eb-8fbc-03d314c878e0.png)

**Comment by anon88391** [comment]
Any updates on this?
Transparency control is a feature I've been waiting for since the beginning of chatterino and I'm surprised it still hasn't been implemented.

**Comment by Mm2PL** [comment]
There were no comments in the meanwhile means no updates. It might get implemented by someone (that someone *probably* isn't going to be me). You can try doing it yourself, that's usually the most reliable option for getting a feature implemented.

**Comment by ArshhGill** [comment]
were there any updates on this feature?

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/191308589-40bffba8-a7e1-4e4f-b280-ca4eff8f84da.png)

**Comment by Kaspian-TC** [comment]
I'm definitely not knowledgeable enough about how one would implement this feature, but it does seem to be possible. The background colour is defined in RunGui.cpp by the QColor class, which according to the [documentation](https://doc.qt.io/qt-5/qcolor.html#alpha-blended-drawing) should allow for an alpha channel.

I just want to bounce this idea up to see if it's even realistic.

**Comment by Mm2PL** [comment]
> I just want to bounce this idea up to see if it's even realistic.

I think you also might need to enable something on all windows (see BaseWindow, BaseWidget, Split and Window classes). Widgets might need a little modifications to have all colors be of certain transparency. This got slightly easier as BaseTheme is no more. 

> The background colour is defined in RunGui.cpp by the QColor class

This is a good first step, just see what needs changing after.
