### ISSUE TITLE
Commands from mod buttons don't trigger custom commands.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1620]
**Describe the bug**

When clicking a moderation button, the command is not processed like a normal command from the chat box, instead custom commands made inside the client aren't triggered.

**To reproduce**

 - Add create a command, for this example, I'm gonna use `/test => Test 123 {1+}`,
 - Add a mod button like, `/test {user}`
 - Click it on a message
 - observe that the command wasn't processed inside Chatterino, it was send to Twitch.

**Chatterino version**

`Chatterino 2.1.7 (commit 175e41c58)`

**Comment by 5E7EN** [comment]
If this is intention behavior, it would be nice to see this as an added feature to make it work.
