### ISSUE TITLE
Please add the option to hide viewer count and duration of the stream when you hover on the title

### ISSUE THREAD

**Issue by MSPAIN3** [Chatterino/chatterino2#1621]
I use chatterino as a streamer, i already disabled the viewer count and the duration of the stream, but when i hover they're still there, i get kinda anxious when i lose or gain viewers and i don't want it to affect my performance, and when i see i've streamed close to 2 hours it usually just changes my mood instantly, i wish i couldn't see how much i've streamed.

So please add the option to disable the viewer count/duration of the stream when you hover on the title, it would be very useful!, thank you

**Comment by pajlada** [comment]
The options are there for this specific reason, will look into it.

**Comment by pajlada** [comment]
@MSPAIN3 This is fixed in the latest nightly, and will be part of the next stable release. Thanks for your feature request!
