### ISSUE TITLE
Add UI for the last read message indicator

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1622]
**Is your feature request related to a problem? Please describe.**

There is no UI for configuring the last message indicator.

**Describe the solution you'd like**

I would like to have controls added for the `showLastMessageIndicator`, `lastMessagePattern` and `lastMessageColor` settings.

**Describe alternatives you've considered**

Not do it, leave the user to find the settings on their own pepeLaugh

**Additional context**

Only way you can edit these settings now is via editing the file directly with a text editor.

**Comment by leon-richardt** [comment]
Duplicate of #964, I believe?

**Comment by Mm2PL** [comment]
That issue doesn't mention `lastMessageColor`, i will close this one and mention that there :)
