### ISSUE TITLE
Make chatterino spawn an extra anonymous connection to see chat even while banned

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1624]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/12804673/78670927-e02abb80-7921-11ea-9d21-ee4e3c4e4fd9.png)

**Describe alternatives you've considered**
Opening chat in an incognito window

**Comment by pajlada** [comment]
Not something I'm looking to add into Chatterino, seems out of scope to bypass Twitch's base moderation features.
