### ISSUE TITLE
Add . as an alias to / for in-built commands

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1628]
**Is your feature request related to a problem? Please describe.**
Using .user <user>, will return this error message: `Sorry, "/user" is not available through this client.`
Similar to .logs: `Unrecognized command: /logs`

**Describe the solution you'd like**
The ability to use . as a substitute to /

**Comment by pajlada** [comment]
No, we will leave the `.` prefix as a way to bypass any client command and send them directly to the server.
