### ISSUE TITLE
Add filters to channels.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1632]
**Describe the solution you'd like**

I would like for each channel to have filters, a search string that is matched to all messages. It could be specified like `channel_name filters filters filters...`. The channel change popup could be changed to make the filters a separate input box.

**Describe alternatives you've considered**

not doing it

**Additional context**

It would be pretty easy to reuse the existing search predicate system.

**Comment by cinemassacres** [comment]
https://github.com/Chatterino/chatterino2/issues/228

**Comment by fourtf** [comment]
there's another issue I think
