### ISSUE TITLE
Show video/image thumbnail when hovering over a link (like FrankerFaceZ)

### ISSUE THREAD

**Issue by thenamelessboss** [Chatterino/chatterino2#1633]

**Comment by pajlada** [comment]
This feature would also require work to be done in https://github.com/Chatterino/api to perform the screenshotting of websites and serving the images. pretty chunky feature, and not something I foresee happening in the near future

**Comment by Mm2PL** [comment]
If the data returned is an image, the link resolver could tell Chatterino to show the contents in the tooltip. 
For Youtube, BetterTTV emote links, FrankerFaceZ emote links this wouldn't be too hard, however for other links it would one hell of a pain in the ass.

**Comment by alazymeme** [comment]
Is there a chance ffz will let us use their servers (since they already have the data)? 🤔

**Comment by Mm2PL** [comment]
we could ask them politely and see what happens, there's no harm in that :thinking:

**Comment by SirStendec** [comment]
Letting other chat clients use FrankerFaceZ architecture for something like that isn't something I'm entirely against, but it also isn't something I can condone right now. With everyone staying at home thanks to the pandemic, our concurrent users are up significantly and the servers in charge of things like link lookups are overwhelmed.

I need to come up with a better way to handle pubsub and our microservices before I'd be willing to give anyone more the green light to start working with it. Not to mention, I'd like to clean up the link info a bit if someone else will be using it. Currently, it emits HTML which obviously isn't ideal.

**Comment by alazymeme** [comment]
This can probably be closed, it fixed [here](https://github.com/Chatterino/api/pull/34) (?)
