### ISSUE TITLE
Inline timeouts

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1634]
**Describe the solution you'd like**
Inline timeouts to make the chat look neater

![image](https://user-images.githubusercontent.com/12804673/79632825-13ccd780-81a5-11ea-876f-09fc0a49f38a.png)
![image](https://user-images.githubusercontent.com/12804673/79632829-1cbda900-81a5-11ea-8b1d-83c8f5eae12e.png)

**Comment by pajlada** [comment]
This would be a separate setting, or addition to the "stack setting" (which would just change to timeout style).
We would need to make sure that timeouts targeting you from pubsub should still be rendered, as seen in the second screenshot.

**Comment by alazymeme** [comment]
Another example for reference: https://i.imgur.com/pjDtRZ5.png

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
