### ISSUE TITLE
Add an option to disable highlight messages

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#1637]
**Is your feature request related to a problem? Please describe.**
I just dont want to see highlighted messages 
**Describe the solution you'd like**
add an option to disable it

**Comment by fourtf** [comment]
You can disable them right now. However it is planned to add the setting in the general tab for visibility, so I will leave this open for now 👍

**Comment by Dolev24** [comment]
> You can disable them right now. However it is planned to add the setting in the general tab for visibility, so I will leave this open for now 👍

how?

**Comment by fourtf** [comment]
Added the button in General Settings under Messages
