### ISSUE TITLE
SIGFPE or random crashes

### ISSUE THREAD

**Issue by SLCH** [Chatterino/chatterino2#1638]
**Describe the bug**
Ch2 crashing randomly (sometimes). Could be while i'm in chat, could be while pc is locked.
Could be 3 times a day, could be none during months.
At least now i (kinda) logged it.

**To reproduce**
eShrug

**Screenshots**
none

**Chatterino version**
Chatterino 2.1.7 (commit 175e41c58)

**Operating system**
<details>

![Screenshot_20200419_194815](https://user-images.githubusercontent.com/2884941/79692556-ea7c7c00-8276-11ea-88ab-aafc102a9bfc.png)

</details>

**Additional information**
<details>

<summary>
core dump
</summary>

Timestamp                     PID    UID   GID  SIG COREFILE  EXE
...
Fri 2020-04-17 22:57:46 +04    3376  1000  1000   8 present   /usr/bin/chatterino
Sat 2020-04-18 19:51:42 +04   18580  1000  1000   8 present   /usr/bin/chatterino
Sat 2020-04-18 21:17:32 +04   56202  1000  1000   8 present   /usr/bin/chatterino
Sat 2020-04-18 21:46:00 +04   61553  1000  1000   8 present   /usr/bin/chatterino
Sat 2020-04-18 22:39:57 +04   65593  1000  1000   8 present   /usr/bin/chatterino
Sun 2020-04-19 19:04:28 +04   68345  1000  1000   8 present   /usr/bin/chatterino
�  ~ git:(master) � coredumpctl info 68345          
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
           PID: 68345 (chatterino)
           UID: 1000 (slch)
           GID: 1000 (slch)
        Signal: 8 (FPE)
     Timestamp: Sun 2020-04-19 19:04:27 +04 (38min ago)
  Command Line: /usr/bin/chatterino
    Executable: /usr/bin/chatterino
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (slch)
       Boot ID: JustInCaseDeletingThis
    Machine ID: DeletingThisToo
      Hostname: myhostname
       Storage: /var/lib/systemd/coredump/core.chatterino.1000.JustInCaseDeletingThis.68345.1587308667000000000000.lz4
       Message: Process 68345 (chatterino) of user 1000 dumped core.
                
                Stack trace of thread 68345:
                #0  0x000055ad86cf6866 n/a (chatterino + 0x1b3866)
                #1  0x000055ad86cf6e79 n/a (chatterino + 0x1b3e79)
                #2  0x00007f0f84bcdaf3 n/a (libQt5Core.so.5 + 0x2deaf3)
                #3  0x00007f0f84bc19f5 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2d29f5)
                #4  0x00007f0f8599d352 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15b352)
                #5  0x00007f0f859a6829 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x164829)
                #6  0x00007f0f84b944f2 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a54f2)
                #7  0x00007f0f84bebc22 _ZN14QTimerInfoList14activateTimersEv (libQt5Core.so.5 + 0x2fcc22)
                #8  0x00007f0f84bec4fa n/a (libQt5Core.so.5 + 0x2fd4fa)
                #9  0x00007f0f862b56be g_main_context_dispatch (libglib-2.0.so.0 + 0x6b6be)
                #10 0x00007f0f862b7531 n/a (libglib-2.0.so.0 + 0x6d531)
                #11 0x00007f0f862b7571 g_main_context_iteration (libglib-2.0.so.0 + 0x6d571)
                #12 0x00007f0f84bec890 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd890)
                #13 0x00007f0f84b9305c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #14 0x00007f0f84b9b066 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2ac066)
                #15 0x000055ad86c85c80 n/a (chatterino + 0x142c80)
                #16 0x000055ad86e0411a n/a (chatterino + 0x2c111a)
                #17 0x000055ad86be3f20 main (chatterino + 0xa0f20)
                #18 0x00007f0f843e3023 __libc_start_main (libc.so.6 + 0x27023)
                #19 0x000055ad86be74ae n/a (chatterino + 0xa44ae)
                
                Stack trace of thread 68351:
                #0  0x00007f0f844b0abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f0f862b74a0 n/a (libglib-2.0.so.0 + 0x6d4a0)
                #2  0x00007f0f862b7571 g_main_context_iteration (libglib-2.0.so.0 + 0x6d571)
                #3  0x00007f0f84bec890 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd890)
                #4  0x00007f0f84b9305c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #5  0x00007f0f849b7c62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8c62)
                #6  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #7  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #8  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68353:
                #0  0x00007f0f844b0abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f0f862b74a0 n/a (libglib-2.0.so.0 + 0x6d4a0)
                #2  0x00007f0f862b7571 g_main_context_iteration (libglib-2.0.so.0 + 0x6d571)
                #3  0x00007f0f84bec8ac _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd8ac)
                #4  0x00007f0f84b9305c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #5  0x00007f0f849b7c62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8c62)
                #6  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #7  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #8  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68347:
                #0  0x00007f0f844b0abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f0f862b74a0 n/a (libglib-2.0.so.0 + 0x6d4a0)
                #2  0x00007f0f862b7571 g_main_context_iteration (libglib-2.0.so.0 + 0x6d571)
                #3  0x00007f0f84bec890 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd890)
                #4  0x00007f0f84b9305c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #5  0x00007f0f849b7c62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8c62)
                #6  0x00007f0f84e3db28 n/a (libQt5DBus.so.5 + 0x15b28)
                #7  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #8  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #9  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68352:
                #0  0x00007f0f848dccf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x000055ad86d704fd n/a (chatterino + 0x22d4fd)
                #2  0x000055ad86d709b9 n/a (chatterino + 0x22d9b9)
                #3  0x000055ad86d609e0 n/a (chatterino + 0x21d9e0)
                #4  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #5  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68349:
                #0  0x00007f0f844b0abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f0f8192c63b n/a (libxcb.so.1 + 0xc63b)
                #2  0x00007f0f8192e37b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
                #3  0x00007f0f800d1e01 n/a (libQt5XcbQpa.so.5 + 0x65e01)
                #4  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #5  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68346:
                #0  0x00007f0f844b0abf __poll (libc.so.6 + 0xf4abf)
                #1  0x00007f0f862b74a0 n/a (libglib-2.0.so.0 + 0x6d4a0)
                #2  0x00007f0f862b7571 g_main_context_iteration (libglib-2.0.so.0 + 0x6d571)
                #3  0x00007f0f84bec890 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fd890)
                #4  0x00007f0f84b9305c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a405c)
                #5  0x00007f0f849b7c62 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8c62)
                #6  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #7  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #8  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68359:
                #0  0x00007f0f848dccf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007f0f56d6dbfc n/a (iris_dri.so + 0x484bfc)
                #2  0x00007f0f56d6d7f8 n/a (iris_dri.so + 0x4847f8)
                #3  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 109277:
                #0  0x00007f0f848dd01a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x1001a)
                #1  0x00007f0f849bea48 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xcfa48)
                #2  0x00007f0f849beb69 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5 + 0xcfb69)
                #3  0x00007f0f849bc1dd n/a (libQt5Core.so.5 + 0xcd1dd)
                #4  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #5  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 109308:
                #0  0x00007f0f848dd01a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x1001a)
                #1  0x00007f0f849bea48 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xcfa48)
                #2  0x00007f0f849beb69 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5 + 0xcfb69)
                #3  0x00007f0f849bc1dd n/a (libQt5Core.so.5 + 0xcd1dd)
                #4  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #5  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68356:
                #0  0x00007f0f848dccf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007f0f56d6dbfc n/a (iris_dri.so + 0x484bfc)
                #2  0x00007f0f56d6d7f8 n/a (iris_dri.so + 0x4847f8)
                #3  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 109307:
                #0  0x00007f0f848dd01a pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x1001a)
                #1  0x00007f0f849bea48 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xcfa48)
                #2  0x00007f0f849beb69 _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5 + 0xcfb69)
                #3  0x00007f0f849bc1dd n/a (libQt5Core.so.5 + 0xcd1dd)
                #4  0x00007f0f849b8dd6 n/a (libQt5Core.so.5 + 0xc9dd6)
                #5  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #6  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68357:
                #0  0x00007f0f848dccf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007f0f56d6dbfc n/a (iris_dri.so + 0x484bfc)
                #2  0x00007f0f56d6d7f8 n/a (iris_dri.so + 0x4847f8)
                #3  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 68358:
                #0  0x00007f0f848dccf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007f0f56d6dbfc n/a (iris_dri.so + 0x484bfc)
                #2  0x00007f0f56d6d7f8 n/a (iris_dri.so + 0x4847f8)
                #3  0x00007f0f848d646f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007f0f844bb3d3 __clone (libc.so.6 + 0xff3d3)

</details>

or https://pastebin.com/M4qiCMb2

**Comment by fourtf** [comment]
I added checks for divisions and modulo here: https://github.com/Chatterino/chatterino2/commit/6052846bc3b8e659244e88a4f0f4ebaedaca6267

Hopefully this mitigates the issues.

**Comment by SLCH** [comment]
Alright, i'll try it and will report later.

**Comment by SLCH** [comment]
Works without crashes so far. Can close it.
This might have fixed other issues with random crashes: https://github.com/Chatterino/chatterino2/issues?q=is%3Aissue+is%3Aopen+crash
