### ISSUE TITLE
Sending whispers is not rate limited.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1639]
## Describe the bug

You can send whispers really fast leading to Twitch making you unable to talk.

## To reproduce

Just send a couple whispers quickly. Observe that the whispers were sent and you were not told to slow down.

## Chatterino version

Chatterino 2.1.7 (commit 3091842dd)

## Operating system

Ubuntu 19.04

## Additional information

**Don't Control+Enter whispers, it ~~can end~~ ends badly**

**Comment by alazymeme** [comment]
Reproducible on my end.

**Comment by fourtf** [comment]
add cooldown plox

**Comment by Mm2PL** [comment]
HTTP/1.1 429 Too Many Issues

We now have to use HTTP for sending whispers, doesn't apply anymore.
