### ISSUE TITLE
OverRustleLogs shutdown

### ISSUE THREAD

**Issue by dnsge** [Chatterino/chatterino2#1640]
OverRustleLogs will be shutting down on May 1st due to a C&D from Twitch ([see here](https://overrustlelogs.net/assets/twitch_email.png)). 

Chatterino currently has an "Online Logs" feature that pulls logs from OverRustle's public API. It seems that this feature will need to be modified/removed because their API will be disabled on May 1st.

Relevant code:
["Online Logs" button in user info popup](https://github.com/Chatterino/chatterino2/blob/354ad6a3624e73891b0961673a32eb0c0366069f/src/widgets/dialogs/UserInfoPopup.cpp#L116)
[/logs command](https://github.com/Chatterino/chatterino2/blob/9a8b85e338ba4fe3b2bb1eee81f3f6f05387959f/src/controllers/commands/CommandController.cpp#L417)
[LogsPopup](https://github.com/Chatterino/chatterino2/blob/9a8b85e338ba4fe3b2bb1eee81f3f6f05387959f/src/widgets/dialogs/LogsPopup.cpp)

At the moment it looks like there isn't any alternative, but maybe something equivalent can be found.

**Comment by Mm2PL** [comment]
sadly any big enough alternative will get shutdown as well
PepeHands

**Comment by gempir** [comment]
The only reasonable response IMO is respecting the dev agreement and disabling/removing the feature. Once Twitch offers real API for the user logs of Twitch we can use those in chats where a user is a moderator.

**Comment by alazymeme** [comment]
The alternative is `/user <user>` which will bring up the twitch logs

**Comment by dnsge** [comment]
Yeah. Seeing that the "Usercard" button is already right next to the "Online logs" button, the "Online logs" button can probably be removed without affecting moderators too much. Non-moderators won't be able to see logs, which really isn't that big of a deal.

**Comment by leon-richardt** [comment]
> Non-moderators won't be able to see logs, which really isn't that big of a deal.

Chatterino's feature to load message history upon joining a channel is a big deal to me. Guess there's no way around removing it though.

**Comment by gempir** [comment]
> Chatterino's feature to load message history upon joining a channel is a big deal to me. Guess there's no way around removing it though.

This API is different and is still maintained. It's also to possible to opt-out of that service. For now it's still online.

**Comment by leon-richardt** [comment]
> Also IMO the purpose is different. We it's not building a public database of logs of all people. Just a few recent messages in a chat.

I agree with that and would be very happy for the API to stay online. Hopefully Twitch shares that point of view as well.

**Comment by martinsstuff** [comment]
A little thought I had: Could it be possible to use the saved chat from VODs, instead? VODs of live streams have a delay before they catch up but I can imaging accessing the VOD chat independently to the actual VOD could allow us to catch up faster than the video to provide the previous messages. 

There is already an open source project for downloading VOD chat (I used it successfully before, although not for live chat): https://github.com/PetterKraabol/Twitch-Chat-Downloader

RIP Overrustle (it just got shut down completely) F

**Comment by pajlada** [comment]
Not really the same, one can't replace the other.
