### ISSUE TITLE
Application locale in Qt is not set.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1641]
## Describe the bug

The default application locale is not set to English. For example usage `QDateTime` will result in the locale appropriate date and time format, which does not mix well with English text around that.

## Chatterino version

b4a2ced1

## Fix
Use [`QLocale::setDefault()`](https://doc.qt.io/qt-5/qlocale.html#setDefault) at the start of the app, before any non-gui threads are started.

## Additional information
This can result in mishaps like: `User is AFK since poniedziałek, 20 kwietnia 2020 00:30:42 CEST`

**Comment by fourtf** [comment]
I would appreciate it if there were no more "... 4HEad" comments in the issues. Feel free to remove sections from the template if you feel like they do not serve any purpose. Thank you.

**Comment by fourtf** [comment]
do it

**Comment by fourtf** [comment]
actually this is supposed to be local to the user, right?

**Comment by fourtf** [comment]
yeah I think it should display time as the users locale
