### ISSUE TITLE
Filter Message by username color

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1643]
Some chats contain a lot of very new chatters which are mostly just spam and unintersting.

It would be nice to be able to filter messages by attributes of the user that posted them. 
My specific usecase is filtering users without a color. (Show up grey in chatterino by default)

I think on its own the feature is decent, but it would be way better to somehow make multiple conditions etc for a message to appear. So that maybe if a user with no color types a new message but he is actually a subscriber then his message will show up.

This doesn't have to be only for colors, it could be generally filtering of messages by attributes of the user like sub status, badges etc. 

I have had several people telling me they would love that feature, that's why I opened an issue.

**Comment by fourtf** [comment]
check filters issue instead
