### ISSUE TITLE
Add support for the smokemotes ffz addon

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1648]
**Describe the solution you'd like**
Enable smokemotes integration to get gif emotes - while not having to pay for bttv: https://www.smokey.gg/tutorials/using-smokemotes-with-frankerfacez/
Add-on code: https://github.com/FrankerFaceZ/Add-Ons/tree/master/src/smokemotes

**Describe alternatives you've considered**
Paying for bttv

**Comment by alazymeme** [comment]
Does this one still "need triage"? 🤔

**Comment by cinemassacres** [comment]
he removes that feature

**Comment by cinemassacres** [comment]
he is removing that feature https://i.imgur.com/9rUzvyc.jpg

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/91248057-1a90da00-e797-11ea-841b-86857a137126.png)
