### ISSUE TITLE
Middle Mouse Button on user can opens twitch usercard

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1651]
**Is your feature request related to a problem? Please describe.**
As a moderator I want a fast way to open a users usercard for logs and similar moderation information.

**Describe the solution you'd like**
A middle mouse button click on the username opens the twitch usercard in the Browser like to `/user <name>`

**Describe alternatives you've considered**
Typing `/user <name>` but it's a lot slower

**Comment by apa420** [comment]
This seems better now considering twitch wants to remove 3rd party logging sites.

**Comment by alazymeme** [comment]
Wasn't this fixed by https://github.com/Chatterino/chatterino2/pull/1669?

**Comment by apa420** [comment]
Fixed by #1669
