### ISSUE TITLE
commercial command doesn't work

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1652]
**Describe the bug**
I am not able to run an ad. Error is: `You don't have permission to perform that action. `

**To reproduce**
1. Type `/commercial` (being online/offline doesn't matter)

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/80297434-3a52ca00-87c6-11ea-8120-432213f63482.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 3091842dd, 19.04.2020)

**Operating system**
Windows 10

**Additional information**
I believe this has something to do with affiliates previously not being able to run ads.

**Comment by apa420** [comment]
This has to do with us not requesting the scope to run ads on the token I think.

**Comment by 5E7EN** [comment]
Nah, looks like the required scope is request on the login page too: https://i.imgur.com/tprYLOS.png
Must be something else. ¯\_(ツ)_/¯

**Comment by alazymeme** [comment]
Did anyone figure this one out? Does it still "need triage"?

**Comment by alazymeme** [comment]
@5E7EN Looks like it was removed in this commit: https://github.com/Chatterino/login/commit/1d9f81e6ce68d06ef81bc8771c1c6ebd13a4fefe
