### ISSUE TITLE
Qt5Core.dll Invalid Digital Signature in v.2.1.7 from chatterino.com

### ISSUE THREAD

**Issue by martinsstuff** [Chatterino/chatterino2#1653]
**Describe the bug**
The digital signature of the "Qt5Core.dll" file seems to be invalid.

**Screenshots**

![image](https://user-images.githubusercontent.com/29005772/80299140-05139100-8760-11ea-95d9-8545fa20f03c.png)

**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 1909

**Additional information**
https://www.virustotal.com/gui/file/cdde527ac62cfbd1221f387ae3bf1c4c9ebeaf371993c72cd6eb0ef304f5cb14/details

Other QT .dlls seem to be properly signed.

Edit: Portable version is also affected.

This isn't an immediate big issue but it's definitely something that should be addressed, although right now only one scanner on VirusTotal is detecting it, this definitely has a negative effect on threat scoring from anti-malware software and might in the future push it over the edge for a false malware detection.

**Comment by fourtf** [comment]
seems fixed
