### ISSUE TITLE
arabic script is reversed 

### ISSUE THREAD

**Issue by iabo0od** [Chatterino/chatterino2#1655]
arabic script is reversed in chatterino

example here is how  "one two three" in twitch chat appears which is correct  https://i.imgur.com/wTSIOO9.png

and here how it shows up in chatterino
https://i.imgur.com/XVhBbS5.png

text " واحد اثنين ثلاثه "

**Comment by cinemassacres** [comment]
https://github.com/Chatterino/chatterino2/issues/720

**Comment by apa420** [comment]
Duplicate of #720
