### ISSUE TITLE
Indicate When the Chat Is Paused by the User (Hover or Scroll)

### ISSUE THREAD

**Issue by martinsstuff** [Chatterino/chatterino2#1656]
**Is your feature request related to a problem? Please describe.**

It is sometimes not clear if the chat is frozen by hovering over it or is it bugged.

**Describe the solution you'd like**

A banner on the bottom of the chat window saying "Chat paused due to X" (X = Mouse Movement or Scroll) like FFZ, a click on the banner should unpause the chat and override hover detection until the cursor leaves the chat area.

**Additional context**

I also have the suspicion that the "un-hover" detection (only really an issue with indefinite pause timer) is kinda wonky, I had the chat freeze on me a couple times with the timer set to indefinite and having an indicator could further help with troubleshooting.

**Comment by fourtf** [comment]
There is a pause symbol on the top right of the splits, is that perhaps not visible enough?

**Comment by Mm2PL** [comment]
From my experience, highlights on the scrollbar cover up the pause symbol, it being transparent does not help.

**Comment by fourtf** [comment]
Ah I didn't notice that it was under the scrollbar
