### ISSUE TITLE
Add visual feedback on F5

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1665]
**Describe the bug**
No visual feedback when reloading emotes using F5

**Comment by thekalio** [comment]
#1671 adds visual feedback for BTTV and FFZ emote loading by showing a system message in the associated chat window (see the PR for examples). I've been using this for a while and it's very useful.

It doesn't show feedback for reloading Twitch emotes though; implementing this similar to BTTV and FFZ requires passing a `TwitchChannel` reference to `TwitchAccount::loadEmotes()`, which is possible in `Split::reloadChannelAndSubscriberEmotes()` and `SplitHeader::reloadSubscriberEmotes()`, but (seemingly) not in `Emotes::initialize()`. I suppose we could add it as a `boost::optional` parameter to `TwitchAccount::loadEmotes()`, and if not present, don't show any system message. Then we could print the message only in the first two cases. What do you think?

**Comment by gempir** [comment]
Since #1671 is merged and works great, I think we can close this.

**Comment by apa420** [comment]
Fixed by #1671
