### ISSUE TITLE
Use Websockets to connect to TMI

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1666]
**Is your feature request related to a problem? Please describe.**
In the recent weeks IRC endpoints of TMI have been really unstable for EU. While the websocket connections stayed stable. Webchat worked as usual and bots using websockets were more reliable.

**Describe the solution you'd like**
Either make it an option to use websockets instead of IRC or use websockets permanently everywhere since that is what webchat uses and IMO less people complain about chatterino when webchat also won't work.

**Describe alternatives you've considered**
Use webchat

**Comment by pajlada** [comment]
Closing since chat over EventSub will be an alternative instead, which would use websockets rather than IRC.
https://github.com/Chatterino/chatterino2/pull/4962
https://github.com/Chatterino/chatterino2/issues/5128
