### ISSUE TITLE
Chatterino cannot open after Windows account switch (even with full logout)

### ISSUE THREAD

**Issue by rbadin** [Chatterino/chatterino2#1667]
**Describe the bug**
If you use Chatterino with more than one Windows account, either sharing the user settings or not, if you close Chatterino, and logout one user account and logon on another account, the Chatterino will not open, only restarting Windows.

**To reproduce**
With Windows, create 2 user accounts, configure Chatterino with your user settings as usual. Close Chatterino, logout and login on the other account. Chatterino will not open.

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 1903

**Additional information**
- Chatterino is not set to open at startup on both profiles.
- Windows 10 has an option set as ON by default to pre-logon and open previous opened programs of the last login before logon under
Settings > Accounts > Sign-in options > Privacy, then
"Use my sign-in info to automatically finish setting up my device and reopen my apps after an update or restart."
I set that to OFF on both profiles, and the issue continues.

**Comment by pajlada** [comment]
To clarify, are the three following scenarios true for you?
Boot Computer -> Log in as User A -> Start Chatterino -> Shut off Chatterino -> Log out User A -> Log in User B -> Start Chatterino fails?
Boot Computer -> Log in as User A -> Start Chatterino -> Shut off Chatterino -> Log out User A -> Log in User A -> Start Chatterino succeeds?
Boot Computer -> Log in as User B -> Start Chatterino succeeds?

**Comment by rbadin** [comment]
Yes, all three are true. And likewise with User A as User B and vice-versa.
Also is true:

Boot Computer -> Log in as User A -> DO NOT Start Chatterino -> Log out User A - > Log in User B -> Start Chatterino -> Start Chatterino Succeeds.

**Comment by fourtf** [comment]
I don't see a reason why this would happen and I cannot reproduce this.
