### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by SLCH** [Chatterino/chatterino2#1673]
Scroll doesn't work when dragging scrollbar with mouse1.
Besides that works correctly - changes sizes depending on content, can scroll with mouse wheel, clicking on scrollbar works.

Chatterino 2.1.7 (commit ef9c631c6)

<details>
<summary>Operating system</summary>

![Screenshot_20200506_214249](https://user-images.githubusercontent.com/2884941/81210395-e07eab00-8fe2-11ea-96eb-16bb65a18ed6.png)

</details>

**Comment by 5E7EN** [comment]
Dup of #1694.
Appears to only occur in the latest nightly.

**Comment by SLCH** [comment]
As @5e7en pointed out, duplicate of #1654
