### ISSUE TITLE
Logging uploaded images

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1678]
**Is your feature request related to a problem? Please describe.**

It's easy to lose i.nuuls.com links for images uploaded through chatterino.

**Describe the solution you'd like**

I would like for all links for uploaded images to be saved in a file somewhere on the user's file system.

**Describe alternatives you've considered**

Searching the logs for all i.nuuls.com links coming from accounts registered in the client, that has an advantage of showing the context, while the disadvantage is that to find the links all the logs files would have to be searched, which takes a lot of CPU time.

**Additional context**

This could be done by opening a CSV file in *append* mode and writing a new line whenever uploading an image.

**Comment by leon-richardt** [comment]
I suggest it should also save the name of the channel that the link was sent in.

**Comment by apa420** [comment]
I mean it technically doesn't send the link anywhere, it just uploads the image and copies the image to clipboard and pastes it in that chat input box. I guess a system which saves all links you send would also be nice maybe?

**Comment by zneix** [comment]
Tried my best and created #1712 to add this feature.
