### ISSUE TITLE
Show emotes emojis after colon

### ISSUE THREAD

**Issue by Jckpt** [Chatterino/chatterino2#1682]
**What should be added?**
Show emotes and emojis after colon like in FFZ 
![Screenshot of feature](https://i.imgur.com/GFlwlrh.png)
**Why should it be added?**
Autocompletion with colon is more consistent than with tab

**Comment by Mm2PL** [comment]
Looks very similar to #591

**Comment by apa420** [comment]
Duplicate of #375
