### ISSUE TITLE
Tooltip under the mouse when at the edge of screen

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1683]
**Describe the bug**
Tooltips can grow pretty large now since Chatterino supports thumbnails for links now with up to 300px size. It can happen that the tooltip so big that it will clamp to the edge of the screen and cause it to go over/under the mouse and link itself causing visual bugs (sometimes the thumbnail disappears completely)

This is a problem with all kind of tooltips not just with thumbnails, but especially obvious with those.

**To reproduce**
Bring chatterino close to the edge of one of your screens and hover a tooltip that would go beyond the screen (it will then attach to the right/bottom of the screen and lay under/over the cursor)

**Screenshots**
![iBCmK](https://user-images.githubusercontent.com/9765622/81584513-1d67ea80-93b3-11ea-95ce-a7962804bb4b.gif)

**Chatterino version**
8532c6d3bca4e6c3e2da279df1224ebc489c2dc2

**Operating system**
Windows 10

**Comment by Mm2PL** [comment]
Can confirm on Linux.

**Comment by apa420** [comment]
This has been an issue for a very long time.
