### ISSUE TITLE
Spam merging (Suggestion)

### ISSUE THREAD

**Issue by ToRRent1812** [Chatterino/chatterino2#1684]
I have a suggestion, a feature where same message is displayed as one but with multiple nicknames in a line, so if chat spams LUL, we will see only 1 line of LUL with all the nicknames.

**Comment by leon-richardt** [comment]
Implementation of such a feature might be able to make use of #1496.

**Comment by Mm2PL** [comment]
I think this is a duplicate solved by #1496
![img](https://i.nuuls.com/opisI.png)
And please use the template, it's there to help you write a good issue.

**Comment by leon-richardt** [comment]
> I think this is a duplicate solved by #1496

As I understand it, #1496 only concerns messages of the same user. OP is asking for a feature hiding spam by different users.

**Comment by fourtf** [comment]
Try using the R9K feature instead.

This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
