### ISSUE TITLE
streamlink: unable to find streamlink executable (version 2.1.7 on macos)

### ISSUE THREAD

**Issue by NatalieGates** [Chatterino/chatterino2#1686]
I want to use chatterino to open a twitch stream. In chatterino, when I click on "open in streamlink" I am given a popup that says "unable to find streamlink executable Make sure your custom path is pointing to the DIRECTORY where the streamlink executable is located." I'm using macos and am not sure what to do. I do not know how to create a config file or even what that means. I am able to open a stream using terminal. I simply type `streamlink twitch.tv/my-fav-stream best` and it works magically. 

I realize I could simply open terminal each time, but like the ideal of having chatterino do that work for me.

I'm not very tech savvy so I'm wondering if someone could give me step-by-step instructions how to get this working in macos?

<img width="344" alt="Screen Shot 2020-05-14 at 9 59 12 AM" src="https://user-images.githubusercontent.com/47909481/81945954-c3427180-95cc-11ea-8373-f6bda538d842.png">

**Comment by dnsge** [comment]
You need to set the path for the streamlink executable in Chatterino settings:
<img width="927" alt="Screen Shot 2020-05-14 at 1 22 37 PM" src="https://user-images.githubusercontent.com/24928223/81965382-fc3b1000-95e5-11ea-8a03-81f31350a109.png">

To find the executable path, open Terminal and type in: `which streamlink`.
That will output the path to the streamlink executable. Copy the path and paste it into the "Custom streamlink path" field. Don't include the `streamlink` at the end.

Example:
```bash
$ which streamlink
/usr/local/bin/streamlink
```
You would copy `/usr/local/bin/` and paste it into the settings menu.

**Comment by NatalieGates** [comment]
worked like a charm. thanks so much for the detailed instructions <3
