### ISSUE TITLE
Channel Points - Message Highlights, Etc..

### ISSUE THREAD

**Issue by SoWhoYou** [Chatterino/chatterino2#1687]
**What should be added?**  

- Channel Points - Message Highlights

In general, a message should be shown when channel points are used.
Regardless of what the reward is that is being redeemed.
Message Highlights was just a good example.

**Why should it be added?**  

- Because Channel Points are something that is used on nearly all channels.
- A streamer should be able to see the rewards viewers redeemed with channel points.

Currently there is no visual indication at all in Chatterino when a user redeems channel points.
This makes Chatterino hard to keep using as a streamer since these indications are very valuable.

**The Twitch API > Channel Points Event Message > Exists:**
https://dev.twitch.tv/docs/pubsub#example-channel-points-event-message

**Screen Shots for further explanation:**

**_Stable Build:_**  
  
![channelPoints](https://user-images.githubusercontent.com/5152979/82058875-51812b00-9693-11ea-9cd6-d1d2de9ed22d.png)   
  
**_Nightly Build:_**  
  
![Screenshot_2](https://user-images.githubusercontent.com/5152979/82060322-38797980-9695-11ea-90fa-8d076e058e87.png)

**Comment by Mm2PL** [comment]
i'm pretty sure this is resolved in latest nightlies

**Comment by SoWhoYou** [comment]
Indeed it does, although there is no message about the channel points in general.
Which means a message is highlighted, with no explanation

![Screenshot_2](https://user-images.githubusercontent.com/5152979/82060322-38797980-9695-11ea-90fa-8d076e058e87.png)
 as to why.
It also does not add a message when other channel points are used either.

**Comment by alazymeme** [comment]
Probably fixed by https://github.com/Chatterino/chatterino2/pull/1809

**Comment by pajlada** [comment]
Fixes in #1809 
The only thing we do differently from Web Chat now really is the way we display "Highlight My Message" rewards - they're just highlighted with no header.
