### ISSUE TITLE
Pasting text from JetBrains IDEs tries to upload the text to i.nuuls.com instead of pasting text

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1688]
**Describe the bug**

**To reproduce**
1. copy text from a JetBrains IDE (IntelliJ IDEA, Android Studio, PyCharm, etc...) - text can be from the terminal, the editor area, or the execution console output, and probably other places too
2. Paste the text into the chatterino input box
3. Popup for nuuls image uploader opens and no text is pasted into the input box

**Screenshots**
https://streamable.com/44fcqk
![image](https://user-images.githubusercontent.com/1629196/82121798-08fb6780-9790-11ea-9ed4-5a60bfe2a1f0.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit d9aab1f6e, ) 

**Operating system**
Windows 10. Seems to only affect Windows

**Additional information**

Was confirmed to affect another user, using Android Studio.

**Comment by Mm2PL** [comment]
Could possibly be caused by `mimedata()->hasUrls()`
https://github.com/Chatterino/chatterino2/blob/master/src/widgets/splits/Split.cpp#L733

**Comment by RAnders00** [comment]
This is a screenshot of [InsideClipboard](https://www.nirsoft.net/utils/inside_clipboard.html):

![image](https://user-images.githubusercontent.com/1629196/82121905-b3738a80-9790-11ea-8438-8756e2b34679.png)


And as text, as the program exports it:
```
==================================================
Format ID         : 1
Format Name       : CF_TEXT
Handle Type       : Memory
Size              : 87
Index             : 4
==================================================

==================================================
Format ID         : 7
Format Name       : CF_OEMTEXT
Handle Type       : Memory
Size              : 87
Index             : 8
==================================================

==================================================
Format ID         : 13
Format Name       : CF_UNICODETEXT
Handle Type       : Memory
Size              : 174
Index             : 3
==================================================

==================================================
Format ID         : 16
Format Name       : CF_LOCALE
Handle Type       : Memory
Size              : 4
Index             : 7
==================================================

==================================================
Format ID         : 49295
Format Name       : Rich Text Format
Handle Type       : Memory
Size              : 337
Index             : 2
==================================================

==================================================
Format ID         : 49569
Format Name       : HTML Format
Handle Type       : Memory
Size              : 727
Index             : 1
==================================================

==================================================
Format ID         : 49574
Format Name       : UniformResourceLocator
Handle Type       : Memory
Size              : 87
Index             : 5
==================================================

==================================================
Format ID         : 50023
Format Name       : JAVA_DATAFLAVOR:application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
Handle Type       : Memory
Size              : 345
Index             : 6
==================================================
```

**Comment by Mm2PL** [comment]
> ```
> ==================================================
> Format ID         : 49574
> Format Name       : UniformResourceLocator
> Handle Type       : Memory
> Size              : 87
> Index             : 5
> ==================================================
> ```

This seems to cause this behavior. Could you post the data?

**Comment by RAnders00** [comment]
The data is exactly the text I copied.

![image](https://user-images.githubusercontent.com/1629196/82122218-7f00ce00-9792-11ea-8dcd-24a6a9cae271.png)

**Comment by Mm2PL** [comment]
note to self: solving this would require checking urls more before deciding if they should be accepted

**Comment by Mm2PL** [comment]
seems to not occur now on `Chatterino 2.1.7 (commit d9aab1f6e)` on Ubuntu.

**Comment by RAnders00** [comment]
When image uploader is disabled, the text is also not pasted like normal
![image](https://user-images.githubusercontent.com/1629196/92409296-6bfa7b00-f140-11ea-9d14-70130dc6a35e.png)

**Comment by zneix** [comment]
I encounter the same issue as randers do when trying to paste code from Android Studio on Windows 1909, using latest nightly.

**Comment by RAnders00** [comment]
I suppose the logic of this else block should change? https://github.com/Chatterino/chatterino2/blob/682caf6b693b0a6880b8fba6790e0b28a4befea2/src/util/NuulsUploader.cpp#L279-L286 Instead of printing the error message, insert the URL as text into the input field

**Comment by zneix** [comment]
> I suppose the logic of this else block should change?

Changing this won't work with Image Uploader disabled as the code above won't execute at all. Maybe this and/or something else should be changed.
