### ISSUE TITLE
Chatterino extension changes the site size

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#1689]
**Describe the bug**
Ever since the new layout came out the chatterino extension makes the whole site small when watching someone

**To reproduce**
Open a stream, its only bugged without theatre mode
**Screenshots**
![img](https://i.imgur.com/B9cidVW.jpg)

**Chatterino version**
<!-- Copy the version information from the "About" page in the Settings, e.g. `Chatterino 2.1.4 (commit 497ce2d2f, 26.01.2020)

**Operating system**
Windows 10, Chrome

**Comment by cinemassacres** [comment]
solution (swap watch_stunt_double_user from variant to control) in ffz

**Comment by gempir** [comment]
@fourtf offtopic but do you have any docs how to develop on the extension. I can't even get my qt creator build connected to the extension which makes it impossible to develop for me.

**Comment by fourtf** [comment]
@gempir there's a flag to enable it in debug mode

**Comment by alazymeme** [comment]
ffz has a new option (iirc) that allows you to swap back to the old site. Should c2 support both? Or just the new design?

**Comment by cinemassacres** [comment]
this is what you are talking about https://i.imgur.com/PV3nlrU.png

**Comment by xBlisser** [comment]
It seems FFZ has now removed this option

**Comment by Dolev24** [comment]
> solution (swap watch_stunt_double_user from variant to control) in ffz

This has been removed from FFZ, is there a way to fix this bug now?

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/40
