### ISSUE TITLE
Windows snapping without resizing

### ISSUE THREAD

**Issue by varrbacon** [Chatterino/chatterino2#1690]
**What should be added?**
Not sure if possible, but when moving streams/chatterino between monitors, it would be great to windows snap (windows key + right/left arrow keys) and have chatterino maintain its size/width so you don't have to resize/reposition manually. 

**Why should it be added?**
Not a critical, but a convenient update. Many people move streams between monitors for whatever reason. I start playing games and move streams to right monitor, then I'm done with the game and I'll move to main monitor. Or putting streams on main monitor when in queue for games, etc.

**Comment by gempir** [comment]
I don't think this is something Chatterino should or even can handle. Maybe look into a better window manager than the default one from Windows. 

I personally use fancyzones which is also a project from Microsoft.
https://github.com/microsoft/PowerToys/blob/master/src/modules/fancyzones/README.md

**Comment by alazymeme** [comment]
I'm unsure of the use case. Have you tried using Win + Shift + Arrow Keys?

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
