### ISSUE TITLE
Able to display any emote in any chat by using Kappa_/<some numbers>

### ISSUE THREAD

**Issue by JagwireSec** [Chatterino/chatterino2#1691]
**Describe the bug**
You can type random emotes that display poorly and aren't enabled in that chat by typing Kappa_/27272 where 27272 can be any number. Different numbers produce different emotes. This cannot be inputted in twitch chat (though it displays there if entered through Chatterino). 

**To reproduce**
Open up Chatterino and just type Kappa_/<random numbers>. In the attached screenshot, I used Kappa_/463235

**Screenshots**
![image](https://user-images.githubusercontent.com/36294287/82124884-3a505380-97e1-11ea-805e-979a0d5fbb39.png)

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63) (works on other versions I believe)

**Operating system**
Windows 10 (though works on any chatterino client irregardless of OS)

**Additional information**
Might want to fix this one fast, as I've seen people using it to input hitler emotes.

**Comment by Mm2PL** [comment]
not chatterino issue

**Comment by JagwireSec** [comment]
How so? I can't seem to trigger it through any other way than Chatterino.

**Comment by Mm2PL** [comment]
you might not be able to see it from webchat if you send it from webchat

**Comment by JagwireSec** [comment]
Is this confirmed? I will forward a bug report to Twitch if this is the case.

**Comment by JagwireSec** [comment]
This appears to now be patched by Twitch.
