### ISSUE TITLE
Chatterino still focused after minimizing

### ISSUE THREAD

**Issue by 405-Rep** [Chatterino/chatterino2#1694]
**Describe the bug**
After minimizing Chatterino, Windows still acts like Chatterino is the active window but knows it's minimized so instead it flashes the taskbar on the app that supposed to be focused next but doesn't focus to it. This can be annoying since a lot of times I minimize Chatterino and attempt to go to my browser but keyboard shortcuts aren't working because it's still on Chatterino. It also lets me type in the chat box after being minimized which is somewhat dangerous because I could typing something personal to someone while thinking I'm focused on Discord but I'm still focused in Chatterino, just an example. This works on all other different apps not just my browser. 

**To reproduce**
Minimize Chatterino
_Chatterino will still be focused_

**Screenshots**
https://i.nuuls.com/z02p7.mp4

**Chatterino version**
Chatterino 2.1.7 commit 845c8fa

**Operating system**
Windows 10

**Comment by cinemassacres** [comment]
![not reproducible ](https://user-images.githubusercontent.com/16343162/82521972-4a1fae80-9ae5-11ea-8b6f-6a61b053057e.gif)

**Comment by cinemassacres** [comment]
not reproducible  (https://user-images.githubusercontent.com/16343162/82521972-4a1fae80-9ae5-11ea-8b6f-6a61b053057e.gif)

**Comment by cinemassacres** [comment]
not reproducible ![2020-05-20 21-56-32](https://user-images.githubusercontent.com/16343162/82522035-76d3c600-9ae5-11ea-90cf-569192b4970c.gif)

**Comment by alazymeme** [comment]
Not reproducible on my end either. Windows 10; Nightly 2.1.7 (commit 6d5ba0c44, 24.05.2020). Could be a windows issue on your end.

**Comment by fourtf** [comment]
I don't think this is related to chatterino.
