### ISSUE TITLE
Badge based highlights

### ISSUE THREAD

**Issue by embrsword** [Chatterino/chatterino2#1696]
**What should be added?**
The ability to set highlights based on badges. This is a very useful feature in FFZ that I would like to see come to chatterino.
![image](https://user-images.githubusercontent.com/7378952/82294275-c7440a00-99a5-11ea-942c-448125145107.png)

**Why should it be added?**
In the 10k+ viewer streamers the streamer will normally be talking mostly to these people as much of the rest of the chat will be emote spam so it helps keep up with the flow of whats going on. These days I tend to put twitch on the TV but then still need to open popup chat on my pc or chatterino. It tends to be harder to keep up with chatterino.

**Comment by apa420** [comment]
Similar to #918

**Comment by embrsword** [comment]
The other mentioned issue is for a separate window/panel like the mentions window, Id guess that would be implemented by just saying a highlight rule goes into mentions, the new filtered window or both.

This is to enable highlights based on badge membership. Because you might not know who those people are and if you are in a few channels it would be unreasonable to keep up with it by manually adding individual highlights for everyone

I dont agree its similar. both of these things could be implemented because they dont overlap.

**Comment by apa420** [comment]
Can you look up the dictionary for the word similar. It's just a statement. I'm not going to remove this feature request. I just linked to another issue for whoever will look into implementing this feature.

**Comment by NYISLANDERFAN** [comment]
has this been implemented?

**Comment by Mm2PL** [comment]
No, the issue is still open for a reason. There's a PR that might make this happen though #1704.

**Comment by NYISLANDERFAN** [comment]
> No, the issue is still open for a reason. There's a PR that might make this happen though #1704.

ah, alright, gotcha!

**Comment by embrsword** [comment]
Looks like @zneix slipped in the ability to highlight on prediction badges too, looking forward to using that 👍
