### ISSUE TITLE
Chrome extension doenst work with portable version

### ISSUE THREAD

**Issue by xavasxxv** [Chatterino/chatterino2#1697]
**Describe the bug**
The integration with the chrome extension doenst work if using a portable build

**To reproduce**
Use a portable version without having a normal version installed

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 Pro (build 18363.720)

**Additional information**
If a normal version is installed but the portable version launched manually, it still works fine... Points to something being done at install that exposes the app to the browser, but thats over my head... hope it help

**Comment by fourtf** [comment]
It doesn't work with the portable version because it needs to modify the local system to work, which then makes it non-portable. However this isn't documented anywhere so I'll leave this open.

**Comment by alazymeme** [comment]
> It doesn't work with the portable version because it needs to modify the local system to work, which then makes it non-portable. However this isn't documented anywhere so I'll leave this open.

Where should this be documented? Perhaps on the chrome/firefox extension page?
