### ISSUE TITLE
Font anti-aliasing is broken for OTF fonts.

### ISSUE THREAD

**Issue by martinsstuff** [Chatterino/chatterino2#1698]
**Describe the bug**
The font antialiasing is broken when using a .otf format font, 

**Screenshots**

![chatterino_2020-05-20_09-17-39](https://user-images.githubusercontent.com/29005772/82450689-055f2d80-9a7b-11ea-91af-416f6721845d.png)
![chatterino_2020-05-20_09-18-24](https://user-images.githubusercontent.com/29005772/82450693-06905a80-9a7b-11ea-859a-0d8b87827493.png)

**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**

Windows 10 1909

**Additional information**

OTF is the successor to TTF and as such should be a focus for future proofing, fonts from sources like Adobe Fonts (formerly TypeKit) come as OTF files.

**Comment by fourtf** [comment]
Text Rendering ist handled by Qt and there is nothing we can change about that. Because of that I'll close this, perhaps at some point a QT upgrade will fix it.

**Comment by Mm2PL** [comment]
Could be related to the [StyleStrategies](https://doc.qt.io/qt-5/qfont.html#StyleStrategy-enum) not being used in Chatterino. This bug might be actually related to Ch2 code.
From my search `setStyleStrategy` is never called, which seems to be the function which allows the programmer to tell Qt that Anti-aliased fonts are preferred.
