### ISSUE TITLE
Add notification on streamer joins channel

### ISSUE THREAD

**Issue by EntityReborn** [Chatterino/chatterino2#1706]
**What should be added?**
A notification (toast, sound, etc) when the streamer joins their own channel.

**Why should it be added?**
Often I want to be one of the first people in the channel, even prior to the stream going live.

**Comment by apa420** [comment]
This is one of the dumbest stuff I've seen suggested, not going to lie.

**Comment by apa420** [comment]
There are already notifications on when a stream goes live, I don't see where this is ever useful.

**Comment by braintweak** [comment]
This is usefull if streamer joins for a pre-stream chat. Some do.
+1 this echancement.

**Comment by ALazyMeme** [comment]
> There are already notifications on when a stream goes live, I don't see where this is ever useful.

Please don't comment on old threads. If you are requesting a new feature, open a new issue.
