### ISSUE TITLE
Emote parsing bug

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1707]
**Describe the bug**
Chatterino seems to have some trouble parsing a certain combination of emotes in a message, seems to be related to the comma character

**To reproduce**
`Kreygasm, = DansGame / PogChamp pepeLaugh`

**Screenshots**
![chatterino_Clm12JCNEj](https://user-images.githubusercontent.com/3091645/83063219-79e03080-a068-11ea-9046-5e5b769cfaba.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 2e39dd4d9, )

**Operating system**
Win 10 1909 18363.720

**Comment by gempir** [comment]
In Webchat without any extensions it looks like this https://i.nuuls.com/QGMO1.png

**Comment by 5E7EN** [comment]
Webchat: https://i.imgur.com/pjBU5hm.png (with FFZ & BTTV)
Chatterino: https://i.imgur.com/a9Ya3VQ.png

**Comment by Supinic** [comment]
has using emotes with a trailing comma in web chat been around? seems like a recent change to me

**Comment by alazymeme** [comment]
> has using emotes with a trailing comma in web chat been around? seems like a recent change to me

I think emotes working with punctuation has worked for a long time on webchat (if that's what you mean)

**Comment by fourtf** [comment]
is this fixed?

**Comment by TETYYS** [comment]
no, you can write the message and see for yourself
