### ISSUE TITLE
Zooming in/out with Ctrl + Scroll switches tabs when mouse is on tabs

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#1711]
**Describe the bug**
When you try to use `Ctrl + ScrollUp / ScrollDown` chatterino sometimes changes tabs, but only when your mouse is in the area with channel tabs.
I think it should just stop switching tabs when you use `Ctrl + Scroll`, but maybe that's intended (?).

**To reproduce**
1. Open chatterino.
2. Move your mouse to the area with tabs.
3. Try either `Ctrl + ScrollUp` or `Ctrl + ScrollDown`

**Screenshots**
Scuffed GIF with proof https://cdn.zneix.eu/FLccwgx.gif
![](https://cdn.zneix.eu/FLccwgx.gif)

**Chatterino version**
Chatterino 2.1.7 (commit 50d669a1a 30.05.2020)

**Operating system**
Debian 10 Buster, but I'm pretty sure that happens on Windows 10 1909 as well

**Additional information**
If pajlada sees this on stream chat von

**Comment by alazymeme** [comment]
Consistent here on Windows 10 1909; Nightly 2.1.7 (commit 6d5ba0c44, 24.05.2020)

**Comment by SLCH** [comment]
Scroll through tabs is intended behavior. Ctrl + scroll - not sure. Works the same way in browser, so it's fine?

Related to tab scrolling PRs: 
https://github.com/Chatterino/chatterino2/pull/743
https://github.com/Chatterino/chatterino2/issues/1106

**Comment by alazymeme** [comment]
> Scroll through tabs is intended behavior. Ctrl + scroll - not sure. Works the same way in browser, so it's fine?
> 
> Related to tab scrolling PRs:
> #743
> #1106

Yes but Ctrl + Scroll should be bound to one action, not both. Either switching tab OR zooming. But I'm guessing it performing both actions is just a bug.

**Comment by zneix** [comment]
> But I'm guessing it performing both actions

Yep, exactly. And I think it should only change the UI scale, since it is a shortcut for that.
I think it could be handled by simply ignoring switching tabs, when Ctrl key is being held, so then you can only chanmge the UI scale.

**Comment by fourtf** [comment]
intended
