### ISSUE TITLE
Lowercase username autocompletion

### ISSUE THREAD

**Issue by Chomchaum** [Chatterino/chatterino2#1715]
It would be nice that autocompleting usernames lowercases them.
That would prevent auto timeouts for capslock or special characters abusing usernames

**Comment by leon-richardt** [comment]
Implementation of such a feature should take into account other feature requests like https://github.com/Chatterino/chatterino2/issues/1199. It probably makes sense to have a setting allowing users to select their preferred method of autocompletion.

**Comment by pajlada** [comment]
Not worth the extra setting, sorry.
