### ISSUE TITLE
Maximizing Chatterino creates a border on adjacent monitors

### ISSUE THREAD

**Issue by moe-ka** [Chatterino/chatterino2#1718]
**Describe the bug**
A white border appears on adjacent monitors when maximizing the main window on one monitor.
(sometimes contains a part of the chatterino frame instead of just white)

**To reproduce**
1. Have two or more monitors.
2. Maximize the base chatterino window on one of them.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/40538592/83446234-46c1e680-a446-11ea-9c30-0f3f9f9543bf.PNG)
![Capture1](https://user-images.githubusercontent.com/40538592/83446408-84bf0a80-a446-11ea-8b3d-d89ea15b8a7b.PNG)

**Chatterino version**
Occurs on release (2.1.5) and up to latest commit.

**Operating system**
Windows 10 v2004, successfully reproduced on v1904,

**Comment by Mm2PL** [comment]
Release 2.1.5 is old. Can you download 2.1.7 nightly and test on that? https://github.com/Chatterino/chatterino2/releases/tag/github-actions-nightly

**Comment by moe-ka** [comment]
> Release 2.1.5 is old. Can you download 2.1.7 nightly and test on that? https://github.com/Chatterino/chatterino2/releases/tag/github-actions-nightly

should've attached a 2.1.7 screenshot, it occurs on all versions since dd33e4e though.
![Capture](https://user-images.githubusercontent.com/40538592/83448576-111efc80-a44a-11ea-8e2d-6a7eabc891f5.PNG)

**Comment by apa420** [comment]
I see you have qt open. So I assume you're the one compiling chatterino. Please update qt to 5.14 since earlier versions have had the exact issue you're describing.

**Comment by moe-ka** [comment]
> I see you have qt open. So I assume you're the one compiling chatterino. Please update qt to version 5.14 since earlier versions have had the exact issue you're describing.
> Related issue: #1428

issue persists building with Qt 5.14.2.

**Comment by apa420** [comment]
Seems to be either qt or windows issue atm. So I'm marking it blocked for now.

**Comment by alazymeme** [comment]
@moe-ka Does [your fix](https://github.com/moe-ka/chatterino2/commit/c8286960f8f72de6646f57c200b0a1a4989c818d) fix this issue? Or was this to do with the Qt version?

**Comment by moe-ka** [comment]
> @moe-ka Does [your fix](https://github.com/moe-ka/chatterino2/commit/c8286960f8f72de6646f57c200b0a1a4989c818d) fix this issue? Or was this to do with the Qt version?

it does fix it but I think it might be an issue with the windows version.

**Comment by gempir** [comment]
Had a user report this bug again.  (Ignore the 1px border on top/left, that's my screenshot tool)
![image](https://user-images.githubusercontent.com/9765622/98873152-1d3acb80-2478-11eb-972e-9d007dfc7365.png)

Chatterino 2.1.7 (commit 845c8fa63)

Win10 2004
![image](https://user-images.githubusercontent.com/9765622/98873075-fe3c3980-2477-11eb-82a3-cc2d469e271b.png)

**Comment by alazymeme** [comment]
Speaking of which, why was this closed? I still have this issue daily.

**Comment by killertofus** [comment]
should be unclosed

**Comment by apa420** [comment]
It's closed because there is literally nothing we can do about it.

**Comment by hammy2899** [comment]
fyi, this is fixed on Windows 11

**Comment by Bobobaal** [comment]
For people that are following this or are new and searching for a fix.
Change the compatibility of the executable to windows 8 if you installed Chatterino with the windows installer.
The white border will be gone on your adjacent monitor.

**Comment by Felanbird** [comment]
> For people that are following this or are new and searching for a fix. Change the compatibility of the executable to windows 8 if you installed Chatterino with the windows installer. The white border will be gone on your adjacent monitor.

This is true, see https://github.com/Chatterino/chatterino2/issues/2205#issuecomment-868001183

**Comment by ALazyMeme** [comment]
> For people that are following this or are new and searching for a fix. Change the compatibility of the executable to windows 8 if you installed Chatterino with the windows installer. The white border will be gone on your adjacent monitor.

This also has the side effect of making the program quite slow. I'd suggest stretching the program to the size of the monitor without full maximizing it.
