### ISSUE TITLE
Moderation buttons not showing the correct time

### ISSUE THREAD

**Issue by LeviPorton** [Chatterino/chatterino2#1719]
When using moderation mode, the period for which timeouts are administered is displayed incorrectly when not using seconds as a time unit. Meaning the command /timeout {user} 1d will be displayed as a 1s timeout in modmode. The command will still administer a 1d timeout, though.

Enter a timeout command with any unit that isn't seconds in it, up to 2w of course.

Currently using Chatterino 2.1.7 for Win 10.

**Comment by Mm2PL** [comment]
still can reproduce
