### ISSUE TITLE
View emotion author on hover

### ISSUE THREAD

**Issue by TimaFrolov** [Chatterino/chatterino2#1720]
**What should be added?**
View emotion author on hover

**Why should it be added?**
I think it is convenient and useful.

**Comment by cinemassacres** [comment]
duplicate of #917

**Comment by TimaFrolov** [comment]
Ok, I should have put it more precisely. I meant the authors of emutes in bttv / ffz like this 
![brave_kYIIDhiIg1](https://user-images.githubusercontent.com/50910468/83720621-0f1f8e00-a642-11ea-856a-2dae447a45f9.png)
