### ISSUE TITLE
Closing search window does not focus previously focused chat

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1724]
**Describe the bug**
If you press Ctrl+F and close the window either with Alt+F or close button, previously focused chat does not become focused again and you can't search again

**To reproduce**
Focus a chat, press Ctrl+F, press Alt+F4, press Ctrl+F (last action doesn't work as no chat is focused)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 2e39dd4d9, )

**Operating system**
Win10 2004 19041.264

**Comment by alazymeme** [comment]
Not reproducible on Windows 10 1909; Nightly 2.1.7 (commit 6d5ba0c44, 24.05.2020)

**Comment by pajlada** [comment]
Can't reproduce - Arch Linux btw; v2.1.7-150-g50d669a1

**Comment by fourtf** [comment]
Can't reproduce
