### ISSUE TITLE
Add the Search window to every Usercard and auto-fill with username

### ISSUE THREAD

**Issue by 0xRainy** [Chatterino/chatterino2#1726]
**What should be added?**
Adding CTRL-F to open logs was great but what would be amazing is to have that whole search window also part of every usercard popup and auto-fill the search field with the username to get only their messages and those who mentioned them.

Nothing needs to change with the search window, just add it onto the bottom of the usercard window.

**Why should it be added?**
Clicking a user to instantly see and be able to search their logs and mentions from the usercard is 1000% faster than CTRL-F and type username.

This would add a ton of usability to the usercard itself, rather than having to further open other windows and clicking/typing. Very important when a chat is moving fast and you need to check a log and timeout/ban quickly.

**Comment by Mm2PL** [comment]
#1238 has some similar functionality to what you want, however there is no ETA on it.

**Comment by 0xRainy** [comment]
Agh, I wish I knew C++.. need to uncouple those two ideas imo since adding the logs to the usercard seems to be implemented great in that PR and close to mergable but again, I don't know C++ so maybe I'm wrong.
