### ISSUE TITLE
Commands don't trigger replacements

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1727]
**Describe the bug**

Commands don't trigger replacements like `/r` (only one currently implemented), as those are only expanded in the `SplitInput` when typing.

**To reproduce**

  1. Create a new command that uses `/r`.
  2. Execute it.
  3. Observe the `Unrecognized command: /r`.

**Screenshots**

![2020-06-09_12-04](https://user-images.githubusercontent.com/25011746/84134790-a3ba2f80-aa38-11ea-8a82-484886c0ce94.png)
![2020-06-09_12-04_1](https://user-images.githubusercontent.com/25011746/84134817-ad439780-aa38-11ea-8e58-d76f167f4b5b.png)

**Chatterino version**

`Chatterino 2.1.7 (commit d9aab1f6e)`

**Operating system**

Ubuntu 19.10 (Eoan Ermine)

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
