### ISSUE TITLE
Open player in browser broken with new Twitch update

### ISSUE THREAD

**Issue by mammothb** [Chatterino/chatterino2#1731]
**Describe the bug**
"Open player in browser" opens an invalid URL with the new Twitch layout/update.

**To reproduce**
If you have the new Twitch layout/update, click "Open player in browser" and wait for the page to load.

**Screenshots**
Webpage with error
![firefox_2020-06-11_08-19-53](https://user-images.githubusercontent.com/7960706/84332091-9169fe00-abbe-11ea-9edb-0a0da17d8273.png)

**Operating system**
Windows 10

**Additional information**
New embedding videos requires a `parent` parameter ([docs](https://dev.twitch.tv/docs/embed/video-and-clips/)). Currently, Chatterino only supplies the `channel` parameter ([code](https://github.com/Chatterino/chatterino2/blob/56d09ac198d48c481145b295fdc7fdc8161bdd9a/src/widgets/splits/Split.cpp#L545)). After brief testing, the value of `parent` can be any alphanumeric string without spaces and with at least 1 alphabet. For example, https://player.twitch.tv/?channel=xqcow&parent=OMEGALUL works on my browser.

So I think the fix can be something as simple as appending `parent=Chatterino` in `openBrowserPlayer()` but I'm unsure what string the Chatterino team would like to use.

**Comment by zneix** [comment]
There's already a pull request (#1730) which fixes this. That change went live today, so that's why it suddenly stopped working.

**Comment by mammothb** [comment]
Oh, sorry I forgot to check the PR before raising the issue.
