### ISSUE TITLE
Highlight sound repeats despite only being triggered once

### ISSUE THREAD

**Issue by killertofus** [Chatterino/chatterino2#1736]
**Describe the bug**

can keep pinging even in focus
**To reproduce**

get a ping, wait
**Screenshots**

https://streamable.com/ihb7y3
**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)
**Operating system**

win.10
**Additional information**

**Comment by Mm2PL** [comment]
Is the pinging sound new mentions coming in or is it playing over and over and over?

**Comment by cinemassacres** [comment]
over and over

**Comment by Mm2PL** [comment]
Can you reproduce it consistently or is it more random?

**Comment by cinemassacres** [comment]
more random

**Comment by pajlada** [comment]
Can confirm this has happened on a windows PC here too, no clue why
