### ISSUE TITLE
Add /unban all // /massunban support

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1737]
**What should be added?**
A command to unban all (originally a bttv feature)

**Why should it be added?**
It would allow streamers to run mass unbans from chatterino as opposed to opening web chat

**Comment by pajlada** [comment]
https://dev.twitch.tv/docs/api/reference#get-banned-users would be the API we'd want to use for this most likely

**Comment by TETYYS** [comment]
sounds like something that should be done by a dedicated tool as this would require a progress popup or bar too

**Comment by Mm2PL** [comment]
We could allow for integration with such tools, but implementing them into the client seems a bit out of scope.

**Comment by fourtf** [comment]
This is out of scope for the chatterino project. Consider using a bot that supports this or BTTV instead.
