### ISSUE TITLE
Search in all tab

### ISSUE THREAD

**Issue by Leeqo** [Chatterino/chatterino2#1738]
**What should be added?**
 option to ctrl+f for all channels open 

**Why should it be added?**
i want to be able to search either a user or a phrase in all my tabs open
my amazing design https://i.imgur.com/8a7ysPI.jpg :)

**Comment by apa420** [comment]
What about doing ctrl+shift+f for global search instead.

**Comment by jammehcow** [comment]
A default hotkey of `Ctrl + Shift + F` sounds good to me - the user can change hotkeys as of 2.3.5.

As for implementing this feature, I think passing a list of channels/`ChannelViews` to the search popup is the easiest solution. If a user has multiple splits of the same channel, only one should be snapshotted but filters from all splits for that channel should be applied.

Pretty keen to implement this, sounds useful.
