### ISSUE TITLE
Open emote links through the channel emotes page

### ISSUE THREAD

**Issue by Kraftium** [Chatterino/chatterino2#1740]
**What should be added?**
Ability to right click an emote in the emote menu and either open or copy a 1x/2x/3x or ffz/bttv links, similar to right clicking an emote in regular chat.

**Why should it be added?**
It makes it quicker to grab an emote link instead of having to type it in chat to get a link.

**Comment by Mm2PL** [comment]
Duplicate of #1735

**Comment by zneix** [comment]
Duplicate of #1735

**Comment by apa420** [comment]
Duplicate of #1735
