### ISSUE TITLE
"Open player in browser" link

### ISSUE THREAD

**Issue by trhntr** [Chatterino/chatterino2#1743]
**What should be added?**
ok so twitch changed the way player links work i guess, now it looks like this: https://player.twitch.tv/?channel=forsen&parent=twitch.tv but when i open a player from chatterino it still opens the old link without "&parent=twitch.tv"

**Comment by cinemassacres** [comment]
can confirm https://gfycat.com/spicyexhaustedgoitered

**Comment by leon-richardt** [comment]
Already fixed in #1730. To get it working immediately, you'd have to download the latest nightly. Alternatively, you can also wait for the next stable release of Chatterino.

**Comment by trhntr** [comment]
> Already fixed in #1730. To get it working immediately, you'd have to download the latest nightly. Alternatively, you can also wait for the next stable release of Chatterino.

Thank you!

**Comment by apa420** [comment]
Will keep open until it's rolled out into chatterino release
