### ISSUE TITLE
Custom buttons when clicking on name

### ISSUE THREAD

**Issue by Leeqo** [Chatterino/chatterino2#1744]
**What should be added?**
A way to customize the timeouts buttons when you click a name.

**Why should it be added?**
so i dont have 10 sortcut next to evey name. Button i would add ( perge, permit, 2m, 30m, untimeout, delete message)
mostly because a lot of people doesnt like the moderation buttons next to names.

**Comment by apa420** [comment]
Duplicate of #683 
Look at #1238
