### ISSUE TITLE
Emojis are broken

### ISSUE THREAD

**Issue by kehlery** [Chatterino/chatterino2#1745]
**Describe the bug**
Monkey emojis appear as default emojis there is a default analog available 

**To reproduce**
Simply enable monkey emojis 

**Screenshots**

![image](https://user-images.githubusercontent.com/40723238/85073976-a1f71700-b170-11ea-9068-70505c29c54c.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit c5f6fd756, 16.06.2020)

**Operating system**
Windows 10 

**Additional information**

**Comment by Mm2PL** [comment]
Looks like a problem with Twitch to me, since Chatterino itself doesn't parse/pick the emotes to display.

**Comment by apa420** [comment]
This is twitch' fault, we can't do anything about it.

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/85200128-18924100-b338-11ea-9bf5-eb736f1b1a9b.png)
This has been fixed
