### ISSUE TITLE
Cannot open user card from /whispers

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1749]
**Describe the bug**

Clicking a username in whispers yields an invalid user card.

**To reproduce**

  1. Get someone to whisper you, or alternatively use a bot's ping command.
  2. Click their username

**Screenshots**

N/A

**Chatterino version**

Chatterino 2.1.7 (commit d9aab1f6e)

**Operating system**

Ubuntu 19.10

**Additional information**

**Comment by zneix** [comment]
Can reproduce on Debian 10. However, only middle click takes you to invalid user card - left click does nothing.

**Comment by apa420** [comment]
The usercard needs a channel to open in and /whispers doesn't have one. In mentions the channel you were mentioned in is used for displaying the card. This has been discussed before in some other thread.

**Comment by Mm2PL** [comment]
Also affects in-browser user card, however in a different way: the channel is set to be `/whispers` which makes the URL `https://www.twitch.tv/popout//whispers/viewercard/<target>`, which is invalid.

**Comment by alazymeme** [comment]
Can't reproduce Windows 10 2004 Nightly 2.1.7 (commit 0e564065b, 21.06.2020) - doesn't show recent messages, but I'm fairly sure that's intended.

**Comment by alazymeme** [comment]
@Mm2PL Are you still able to consistently reproduce this?

**Comment by Mm2PL** [comment]
very weird, i cannot reproduce this now
nothing has changed about my setup

**Comment by RAnders00** [comment]
Feel free to reopen this if issue occurs again
