### ISSUE TITLE
Usercard changes broke /usercard

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1750]
**Describe the bug**

`/usercard [user]` command is broken.

**To reproduce**

Try using the command.

**Screenshots**

N/A

**Chatterino version**

`Chatterino 2.1.7 (commit d9aab1f6e)`

**Operating system**

Ubuntu 19.10

**Comment by zneix** [comment]
I noticed this weird behaviour on Debian 10, KDE as well - I just didn't know it wasn't only me.  
Either `/usercard` or left-clicking on username don't work. Looks like some specific Linux issue.

**Comment by dnsge** [comment]
Can't reproduce on macOS 10.15.3 with either d9aab1f (2.1.7) or 8e202c3 (latest commit).

**Comment by alazymeme** [comment]
Can't reproduce on Windows 10 2004 Nightly 2.1.7 (commit 0e564065b, 21.06.2020)

**Comment by gempir** [comment]
Can't reproduce on Windows 10 2004 8e202c37556ae969718d9be6e736e700be647bb1

Although usercards autoclose when refocusing chatterino and not the card. But only if done with /usercard if open it with a click it doesn't ever autoclose.

**Comment by alazymeme** [comment]
@Mm2PL Are you still able to consistently reproduce this?

**Comment by Mm2PL** [comment]
can reproduce on Chatterino 2.1.7 (commit d9aab1f6e)

**Comment by zneix** [comment]
Can reproduce on 2.1.7 0e564065bac470e6e711b60597b9a3b2b4822d90

https://cdn.zneix.eu/vwLfGn3.mp4
Here's a video with explanation of what's exactly happening. It sometimes works for the first time and then it never wants to appear again no matter what.

**Comment by alazymeme** [comment]
I wonder if its a linux only thing

**Comment by Mm2PL** [comment]
Could possibly be. @zneix was examining the code and found this FeelsDankMan https://github.com/Chatterino/chatterino2/blob/0e564065bac470e6e711b60597b9a3b2b4822d90/src/widgets/dialogs/UserInfoPopup.cpp#L95

**Comment by zneix** [comment]
I can also still reproduce on 8e202c375
Screen recording with the bug: https://cdn.zneix.eu/JNaOlsV.mp4

Yes, as @mm2pl said - it can be related to that but I'm not sure if that's that, because sometimes after commenting out that code section, chatterino crashed :(

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/85555532-5c06eb00-b669-11ea-85d0-e5a93212d238.png)
