### ISSUE TITLE
Crashes if you get a whisper from ignored highlight user

### ISSUE THREAD

**Issue by Fawcan** [Chatterino/chatterino2#1756]
**Describe the bug**
If I do a command that whispers me (example !debug command ping)  my chatterino crashes

**To reproduce**
Have a bot (tried with botnextdoor and streamelements) on Ignore Highlight, do a command that whispers reply and the client will crash.
You need to have _Highlight recieved inline whispers_ enabled.

**Chatterino version**
Chatterino Nightly 2.1.7 (commit b4a2ced18, 18.04.2020)
Crashes on latest nightly as well.
Chatterino Nightly 2.1.7 (commit 8e202c375, 21.06.2020)

**Operating system**
Windows 10

**Additional information**
@pajlada

**Comment by Mm2PL** [comment]
what are your settings regarding whispers?

**Comment by Fawcan** [comment]
If I have "_Highlight recieved inline whispers_" enabled I crash, if I turn it off its no problem.

I had Highlight as default, when I noticed I started crashing.

**Comment by Mm2PL** [comment]
can confirm on Ubuntu on Chatterino 2.1.7 (commit d9aab1f6e)

**Comment by pajlada** [comment]
Should be fixed in the latest nightly, thanks for reporting it
