### ISSUE TITLE
Tab context menu opens on mouse down already

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1758]
**Describe the bug**
When right clicking a tab to see the context menu the menu opens already after mouse down. Usally most interactions should only happen after mouse release.

This also can lead to the rename option being selected instantly when you just click shortly. It doesn't happenn 100% of the time but a lot.

The split header context menu has the same issue, but doesn't result in instantly selecting the top option when releasing the mouse button.

**To reproduce**
Hold down right click on a tab.

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 8e202c375, )

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
Looks good to me ![image](https://user-images.githubusercontent.com/12804673/85918346-5990d500-b8a5-11ea-97ca-853baf2e053b.png)

**Comment by pajlada** [comment]
Confirmed we're inconsistent in when we show menus on right click

**Comment by zneix** [comment]
I just wanted to note that context menu for Split Header also opens on mouse down.
Also, I don't know if it's just me, but I like when those menus open on mouse down already, so I was thinking about making all context menus open mouse release by default, but allowing to change that behavior to mouse down in settings.

**Comment by fourtf** [comment]
The dialog was moved so it doesn't get closed on mouse up.
