### ISSUE TITLE
"Login expired! Try logging in again." Error just now (fixed by signing in again)

### ISSUE THREAD

**Issue by martinsstuff** [Chatterino/chatterino2#1762]
**Describe the bug**
I just got the error, Chatterino was still showing as connected on my Twitch account. I haven't been watching Twitch a lot lately but it still worked, and chatted fine less than a week ago, this connection was created 2 months ago, I removed the old one and made a new one (I forgot to test if it would've worked without doing that).

I guess the issue is fixed but since there isn't an obvious reason it should'nt have been connected to my Twitch account I thought I'd just put it out there in case other people are seeing this and this is a bigger issue/event (change in Oauth at Twitch?).

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 2004 - Between the last time it worked and now I upgraded from 1909 to 2004, I wonder if that could have something to do with it?

**Comment by alazymeme** [comment]
Mine expired today. Might've been a change that twitch made. Wouldn't surprise me

**Comment by Mm2PL** [comment]
app tokens do that now even when being used* eShrug

*Twitch won't kick you from IRC, so you'll know only when you relog

**Comment by pajlada** [comment]
Because we store credentials on the client (your computer), there's no way that I know of to keep the token refreshed properly. Tokens expire after a while, and that will cause you to have to log in again.
Not a bug, just how tokens work.

**Comment by CaptainFlint** [comment]
Why do the tokens expire at all? When I wrote a simple IRC bot for Twitch, I created a token. It was over 3 years ago, and the token has never expired since then. Also, when oauth was still a requirement for livestreamer/streamlink, I've created one, and it too was working all the time. Why does Chatterino token expires every couple of months or so?

**Comment by pajlada** [comment]
newly generated OAuth tokens (or tokens generated from new oauth apps, can't remember which) have an expiry date. old ones don't

times change

**Comment by CaptainFlint** [comment]
That's a pity. You can open Twitch in browser and start interacting straight away, but cannot do the same in Chatterino, just because the token decided to expire today. :(

**Comment by leon-richardt** [comment]
> That's a pity. You can open Twitch in browser and start interacting straight away, but cannot do the same in Chatterino, just because the token decided to expire today. :(

It's unfortunate but Chatterino has no control over the security-vs-UX trade-offs Twitch makes. (See [here ](https://discuss.dev.twitch.tv/t/my-oauth-expires-every-day-how-do-i-make-it-permanent/16448/6)for additional context.)
In this case, Twitch decided that OAuth tokens expire after a set amount of time.

**Comment by pajlada** [comment]
There is a token refresh flow, but it would require us to store your access & refresh token. IMO the convenience does not outweigh the security responsibility put on us.
