### ISSUE TITLE
Add account name to window title on Linux

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#1764]
**What should be added?**
On Windows, you can clearly see the name of account that is currently logged in. I miss this feature on Linux and I wish I could have the account name visible next to min / max / close buttons - like on Windows.
I know it's rather not possible on Linux. Alternatively, I've been thinking about changing Header Bar / Application name to something like: `Chatterino 2.1.7 - zneix` and `Chatterino 2.1.7 - not logged in` (or just leave it untouched) for anonymous users.

I have no idea how's the situation on Mac, but if username there is also not visible, it can be added there as well.
I am not sure if my solution is good, so I ask for feedback and other alternative solutions :)

---

**Why should it be added?**
I often have to switch between few accounts and I sometimes forget to switch off of one to other. I find it annoying to click on "Accounts" button all the time to avoid posting something as a bot or friend. This change would make it a bit easier.

**Comment by zneix** [comment]
When i think of it, some Windows users might also want to have username in title bar, so is creating a setting to toggle that a good solution?

**Comment by apa420** [comment]
I don't see a reason for a toggle, having the name in the bar should be standard imo. Only time I wouldn't see this as viable was if chatterino was meant for crossplatform, which it right not doesn't fully support. (There is irc support but it's very limited)

**Comment by zneix** [comment]
I guess you're right, Windows users can't toggle the label with username so that makes sense.
