### ISSUE TITLE
Display owners username when hovering Twitch emotes

### ISSUE THREAD

**Issue by Roger-Chavez** [Chatterino/chatterino2#1765]
**What should be added?**

This has been added for BTTV and FFZ, but it would be nice to also have emote on-hover display the emote owners for twitch emotes.

Also BTTV & FFZ display names are inconsistent. 
"BTTV emotes show username (full-lowercase), FFZ ones show display-name with capital letters and sometimes 'japanese names', which I think should be changed to show username instead."

**Why should it be added?**

It's a feature that's already available for BTTV and FFZ it would be nice to have it be consistent across the board with twitch emotes too. 

I would like to work on this if you guys can please assign me to this I'd appreciate it.

**Comment by TETYYS** [comment]
I see this already implemented, at least on Chatterino Nightly 2.1.7 (commit e4af009fd, )

**Comment by zneix** [comment]
Currently it only works for ffz/bttv emotes only.

**Comment by leon-richardt** [comment]
I looked at this a while ago and to show the emote owner, it would require a separate API request for every emote displayed (which we could cache obviously) if i remember correctly. So personally, I'm not 100% sure it's worth the overhead but I would interested in hearing other people's opinion on this.

**Comment by fourtf** [comment]
duplicate of https://github.com/Chatterino/chatterino2/issues/917
