### ISSUE TITLE
Invalid line break behavior in message containing "🟪"

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1766]
**Describe the bug**
Chatterino breaks line for no reason for text "🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪 WAYTOODANK 🟪" where WAYTOODANK is an emote

**To reproduce**
Post "🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪🟪 WAYTOODANK 🟪" in a pane of 345px width (excluding gray lines delimiting panes)

**Screenshots**
![chatterino_vwVnDcLSSV](https://user-images.githubusercontent.com/3091645/85945429-6285b300-b946-11ea-9bc4-1c33b31f9b9c.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 2e39dd4d9, )

**Operating system**
Win10 2004 19041.264

**Comment by Felanbird** [comment]
Fixed in #1813
