### ISSUE TITLE
Copy text via CTRL-INS doesn't work

### ISSUE THREAD

**Issue by mattbuford** [Chatterino/chatterino2#1767]
**Describe the bug**
I'm in the habit of using CTRL-INS to copy and SHIFT-INS to paste.  This works universally in Windows, even more widely than CTRL-c CTRL-v (which can't be used in terminals, like ssh sessions).  The one place that CTRL-INS SHIFT-INS doesn't work for me is in Chatterino.

SHIFT-INS does actually work to paste , but CTRL-INS does not copy in Chatterino.  This has bitten me multiple times where I selected text in Chatterino, hit CTRL-INS SHIFT-INS ENTER (from muscle memory of decades of copy-pasting) only to be shocked when the CTRL-INS was ignored but the SHIFT-INS paste was not, causing me to paste the old contents of my buffer, potentially leaking private info into a public Twitch chat.

CTRL-INS to copy does actually work correctly to copy text selected in the text input box, but is ignored when text is selected in the chat window.

**To reproduce**
Select some text in the chat window.  Press CTRL-INS.  Expected behavior is that the selected text is now in my paste buffer, but it is not.  The old contents of the paste buffer remain.

To see expected behavior, repeat this same process, except select some text from the text input box instead of the chat window.  CTRL-INS does copy the text-box selection into the buffer.

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10

**Comment by Mm2PL** [comment]
Unable to reproduce on Ubuntu 19.10, Windows only bug?

**Comment by zneix** [comment]
Can reproduce on Debian 10. I am able to copy text via `Ctrl+Ins` from input box, but not from chat.

**Comment by fourtf** [comment]
Based github issue creator for teaching me that Ctrl+Ins copies text

We'll definitely implement this (at some point)!
