### ISSUE TITLE
Add "mark all tabs/splits as read" option

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#1773]
**What should be added?**
An option to mark all splits and tabs as read. Can be nicely connected with #1592 but before that will be implemented, there could be another keybind or an option added to split header context menu.

**Why should it be added?**
I often get many pointless pings (from bots for example) and and this could be a cool way to quickly clear all of them without having to click on every tab.

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
