### ISSUE TITLE
Edit display name.

### ISSUE THREAD

**Issue by NotQuinnNo** [Chatterino/chatterino2#1774]
**What should be added?**

An edit button next to a users name in their usercard, and upon clicking allows you to change the name that is displayed for that user. (This is already a bttv feature)
![name-change](https://user-images.githubusercontent.com/67676337/86360268-ba1e6a00-bc37-11ea-95a4-65b3b12a72b5.png) ![Usercard](https://user-images.githubusercontent.com/67676337/86360986-ca831480-bc38-11ea-87d9-4e87218f097b.png)
^ this is how a changed    󠀀󠀀 󠀀 󠀀 󠀀 󠀀 󠀀 󠀀  ^ this is my usercard
   name looks on twitch.tv

**Why should it be added?**

It would help me keep track of peoples real names in chats, and is a feature that I would just enjoy using!

**Comment by pajlada** [comment]
Duplicate of #137
