### ISSUE TITLE
Slow mode hint with progress bar 

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1776]
**What should be added?**
A hint that you can't send any messages in the chat until your slowmode timer is up. 
Progressbar or similar would be interesting aswell

![image](https://user-images.githubusercontent.com/9765622/86493800-2d78c680-bd73-11ea-994a-2a3547fa1dc2.png)

**Why should it be added?**
Better help users realize that they can't send messages

**Comment by TETYYS** [comment]
dupe https://github.com/Chatterino/chatterino2/issues/870
