### ISSUE TITLE
Message padding

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#1777]
**What should be added?**
A padding setting for messages (vertical) so you can increase the distance between individual messages

**Why should it be added?**
It's easier to read.
Webchat has a bit more distance on messages compared to Chatterino, which could be desired when switching.

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
