### ISSUE TITLE
Download of macOS Version always fails 

### ISSUE THREAD

**Issue by pixelskull** [Chatterino/chatterino2#1778]
**Describe the bug**
When Downloading the current build from the Website the Download proceeds till almost the end, than stops and never finishes.

**To reproduce**
Try downloading the dmg file from the Website 

**Operating system**
macOS 10.15.4
Safari 13.1
Firefox 78.0.1 (64bit)

**Comment by zneix** [comment]
@pixelskull Looks like that was a temporary internal server error but I now managed to download it (`md5sum af485e236361245664f18aee1a62583a`), so this should be resolved, can you confirm it works?

**Comment by pajlada** [comment]
Download works for me, please let me know if I need to re-open this @pixelskull
