### ISSUE TITLE
Open in browser fails

### ISSUE THREAD

**Issue by 736b** [Chatterino/chatterino2#1779]
**Describe the bug**
Clicking on "Log in (Opens in browser)" does nothing.

**To reproduce**
Open Settings, click on Accounts, click on Add, click on Log in (Opens in browser)

**Chatterino version**
2.1.7

**Operating system**
Gentoo stable

**Additional information**
It used to work at some point, but opening links has been broken for a long time. Now I got "Login expired! Try logging in again." though, so I removed my account and tried adding a new one, which led to this issue.

**Comment by alazymeme** [comment]
Can't reproduce, Windows 10 2004; Nightly 2.1.7 (commit 0f9a612c5, 04.07.2020)

**Comment by leon-richardt** [comment]
Is there any console output when clicking the button?

**Comment by 0bpm** [comment]
Console output:
````
open login in browser
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/tmp/.mount_ChatteTMghin/usr/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland-org.kde.kwin.qpa, minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/usr/bin/xdg-open: line 603: 23371 Aborted                 kde-open${KDE_SESSION_VERSION} "$1"
15:23:14.439 [WindowManager] Saving
````

xdg-open itself works, if I just type `xdg-open gentoo.org` in the terminal, a tab in my Firefox opens.

**Comment by pajlada** [comment]
`QDesktopServices::openUrl` should find `xdg-open` and use that.

The `xcb` load error must have to do with this, could you try `export QT_DEBUG_PLUGINS=1` before running Chatterino, try to log in, then post all logs in a pastebin/gist?

**Comment by leon-richardt** [comment]
Also, not sure if you are aware but meanwhile, you can manually open https://chatterino.com/client_login in your browser and copy and paste the token.

**Comment by 0bpm** [comment]
@leon-richardt I  managed to get the client configured manually, so the app is usable. Thanks.

I generated a complete log with QT_DEBUG_PLUGINS=1, it's available at:
https://gist.github.com/0bpm/8665e3b906edb68e8bc8ee085a64cf6d

**Comment by bjwest** [comment]
I get the following output on the console when I click the button:

open login in browser

(process:840310): GLib-CRITICAL **: 14:00:40.525: g_hash_table_contains: assertion 'hash_table != NULL' failed

(process:840310): GLib-CRITICAL **: 14:00:40.525: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
Segmentation fault

Here's the info from my duplicate report:

Describe the bug

Adding an new account, the 'Log in (Opens in browser)' button does not open browser when pressed.

To reproduce
Go to Chatterino Settings (cog in upper left of window) -> Accounts and press 'Add' button on top of dialog.
in next (unnamed) dialog 'Basic' tab, press 'Log in (Opens in browser)' button

Chatterino version
Chatterino 2.2.2 (commit 07fc0c3)

Operating system
Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.0
Kernel Version: 5.4.0-47-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 5600 XT

Additional information
Firefox is set as my system default browser and opens for other applications that call it.

**Comment by fourtf** [comment]
You can open https://chatterino.com/client_login manually if for some reason your system doesn't work

**Comment by bjwest** [comment]
You're closing a bug report with no explanation because there's a manual workaround?  A workaround that may or may not work, by the way.  How about fixing the bug so the application works as intended when, for some unknown reason, we have to delete the account and recreate it when it forgets it was logged in?

**Comment by alazymeme** [comment]
> for some unknown reason, we have to delete the account

Nope, just click the `Add` button, no need to remove the account.

> recreate it when it forgets it was logged in

This isn't necessarily a Chatterino issue. It could also be a twitch issue.

**Comment by leon-richardt** [comment]
> You're closing a bug report with no explanation because there's a manual workaround? A workaround that may or may not work, by the way. How about fixing the bug so the application works as intended when, for some unknown reason, we have to delete the account and recreate it when it forgets it was logged in?

Feel free to fix if it bothers you.

**Comment by fourtf** [comment]
I closed this issue since chatterino simply calls a qt api for opening links. Thus the issue is likely never going to be fixed so I closed it.

> How about fixing the bug so the application works as intended

Very impolite. Don't bring this kind of attitude to my issues page
