### ISSUE TITLE
Usercards in IRC channels display all messages

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1780]
**Describe the bug**
Despite clicking on a specific user, usercard shows all messages in the channel (for more than specific user)

**To reproduce**
have messages from more than 2 people in buffer, click on one of them

**Screenshots**
![chatterino_seDTl3wu9Y](https://user-images.githubusercontent.com/3091645/86515407-58215880-be21-11ea-9756-3d26feadb638.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit e4af009fd, )

**Operating system**
2004 19041.264

**Comment by alazymeme** [comment]
Can reproduce this issue

**Comment by Mm2PL** [comment]
Can reproduce
