### ISSUE TITLE
Line breaks that span whole line do not work in IRC channels

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1781]
**Describe the bug**
Messages that involve a line break that create a new line after produce a copyable empty space

**To reproduce**
Post AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA to fill your pane size from another client (posting a message works normally if ignoring colors)

**Screenshots**
![explorer_pEFOMmPiHC](https://user-images.githubusercontent.com/3091645/86516130-cc122f80-be26-11ea-9c6d-4f96f59afa8e.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit e4af009fd, )

**Operating system**
Win 10 2004 19041.264

**Comment by pajlada** [comment]
Introduced in https://github.com/Chatterino/chatterino2/commit/e4af009fda9f277d6eacaa3d29b6f5a557409359
