### ISSUE TITLE
Copy message crash

### ISSUE THREAD

**Issue by fourst4r** [Chatterino/chatterino2#1783]
**Describe the bug**
A crash occurs when you try to copy a message that has been gone from the chat for a while (with text selected?).
When it happened the first time I had some text selected accidentally (don't know for how long) then I tried to copy a new recent message and it crashed.

**To reproduce**
1. join a fast chat 
1. wait for the message buffer to fill 
1. scroll up to the very beginning of the message buffer
1. select some text (not sure if required but i did this the first time)
1. right click any message
1. wait a minute or so
1. click "copy message"

**Screenshots**
it was too long for gfycat (you can skip the middle) https://youtu.be/hXHsha01IME

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10

**Comment by cinemassacres** [comment]
can't confirm
![,](https://user-images.githubusercontent.com/16343162/86523100-9c622800-be24-11ea-9338-153b63866cce.gif)

**Comment by fourst4r** [comment]
make sure to select some text before-hand, it should say "copy selected" on the context menu

**Comment by cinemassacres** [comment]
still cant confirm https://gfycat.com/bouncyexcellentcanadagoose

**Comment by pajlada** [comment]
I can reproduce, thanks for the report
