### ISSUE TITLE
Mod option to highlight new accounts messages

### ISSUE THREAD

**Issue by Leeqo** [Chatterino/chatterino2#1784]
**What should be added?**
A mod option so new accounts messages get highlited.

**Why should it be added?**
for mods in trainwrecks chat EleGiggle

**Comment by skullsir** [comment]
Could possibly ask Trainwrecks to enable "New Chatter Announcements" on his TTV settings, then mods would be able to keep an eye on those individuals.

**Comment by pajlada** [comment]
The way I could see this work as a Chatterino solution is:
Each Chatterino client would cache each unique user they've seen, and if it's the first time they've seen the user they would poll the Twitch API for information about the user (e.g. the account age) and store that to be able to do operations like this on the user.

The "reasonable" way to do this is either:
a) Middleware cache users in [chatterino/api](/chatterino/api)
or
b) limit requests, and only run requests every 5 seconds if there are users. and ensure we bulk users as well as possible.

```
USER STARTS CLIENT (assuming 2 users per request is max)

 00:00 -> gempir: xd
 00:01 -> gempir: lol123
 00:01 -> pajlada: hello
 00:02 -> zneix: xd
 00:05 -- REQUEST gempir, pajlada TWITCH ACCOUNT AGE
 00:06 -> gempir (2y): hello
 00:06 -> pajlada (2y): hello
 00:07 -> zneix: xd
 00:08 -> newuserxd: hello
 00:10 -- REQUEST zneix, newuserxd TWITCH ACCOUNT AGE
 00:12 -> gempir (2y): hello
 00:12 -> pajlada (2y): hello
 00:13 -> zneix: (1y) xd
 00:14 -> newuserxd (1d): hello
```

This is, however, a lot of work both to write and for each client to do when the feature is implemented for a very small use case, so take my theorizing with a big heap of salt.

**Comment by zneix** [comment]
Extending https://github.com/chatterino/api to cache some user info, like timestamp of account creation sounds like an excellent idea to me. Might even contain more stuff if we'd plan to cache more user data in the future.

**Comment by fourtf** [comment]
I don't think that a system like this is feasible.
