### ISSUE TITLE
refuses to start

### ISSUE THREAD

**Issue by mustafapie** [Chatterino/chatterino2#1785]
**Describe the bug**
chatterino refuses to start, when it is launched, an error pops up (screenshot provided) and then stops running, multiple uninstalls and reinstalls, still doesnt work

**To reproduce**
i dont know

**Screenshots**
![Screenshot (137)](https://user-images.githubusercontent.com/67859561/86530453-359b4800-bed2-11ea-940b-2536c432cf7c.png)

**Chatterino version**
2.1.7
**Operating system**
windows 10 

**Additional information**

**Comment by KararTY** [comment]
What version of Chatterino 2 did you download, and where?

**Comment by mustafapie** [comment]
my apologies, it was an internal problem in my pc it worked after i did
multiple restarts of the pc, it was the windows version from chatterino.com
anyways
