### ISSUE TITLE
Chatterino crashes when opening any emote link

### ISSUE THREAD

**Issue by oldLucke** [Chatterino/chatterino2#1790]
**Describe the bug**

Chatterino crashes when opening any emote link.

**To reproduce**

1. Right click any emote.
2. Select the open option and then any size.
3. The link opens in the default browser, but chatterino crashes.

**Screenshots**

**Chatterino version**

Chatterino Nightly 2.1.7 (commit 682caf6b6, )

**Operating system**

Windows 10

**Additional information**

This seems to be a Windows specific bug. Bug was reproduced on another Windows 10 machine. Chatterino didn't crash on linux manjaro/arch/artix.

**Comment by alazymeme** [comment]
Can reproduce. Windows 10 2004 Nightly 2.1.7 (commit 682caf6b6, 05.07.2020)

**Comment by oldLucke** [comment]
bug was introduced in cdf85c50840825ed64bfae97fb4a25b8b11c6860

**Comment by oldLucke** [comment]
@pajlada https://github.com/Chatterino/chatterino2/commit/d25dee10b2f5d9491bdc32ed2e224b2066f6c647 seems to have resolved the issue
