### ISSUE TITLE
Channel Specific Mention Tabs 

### ISSUE THREAD

**Issue by mvnkey-twitch** [Chatterino/chatterino2#1791]
**What should be added?**
i would like a mention tab that is channel specific so that when i get pinged it wouldnt show up in other mention tabs.

**Why should it be added?**
 because personally i have a mention tab on every tab i have, so when i get pinged all my tabs become red which mean if someone talks in a chat that isnt spamy i wouldnt know cuase its already red.

**Comment by DuskDarker** [comment]
true

**Comment by leon-richardt** [comment]
Duplicate of #518, being worked on in #1748.

**Comment by apa420** [comment]
Duplicate of #518
