### ISSUE TITLE
Chatterino Supporter Badge

### ISSUE THREAD

**Issue by mvnkey-twitch** [Chatterino/chatterino2#1792]
**What should be added?**
A time based chatterino badge level, so that the longer you've been a chatterino supporter, you get a cooler badge Sub-Like Chatterino badge Which changes at a time interval of developers choosing. 

**Why should it be added?**
to incentivise uniqueness among chatterino badge users and could possibly increase chatterino funding

**Comment by DuskDarker** [comment]
great original idea bro well done 👍🏿 👍🏿 👍🏿

**Comment by apa420** [comment]
How would this work?
Chatterino badges aren't a subscription you pay for as for bttv where it might make sense.
Would it just be `Chatterino Supporter (2018/06)` or something like that?
I don't see the point of it.
If anything maybe there could be different tiers of badges depending on the amount you donate.

**Comment by mvnkey-twitch** [comment]
> 
> 
> How would this work?
> Chatterino badges aren't a subscription you pay for as for bttv where it might make sense.
> Would it just be `Chatterino Supporter (2018/06)` or something like that?
> I don't see the point of it.
> If anything maybe there could be different tiers of badges depending on the amount you donate.

it would be like just like the sub badge system, the more og the rarer your badge would be

**Comment by skullsir** [comment]
I think this would require the devs to sort out a subscription based system to go hand-in-hand with the StreamElements API. Really awesome idea to identify Chatterino supporters though.

Just to add some more context, Chatterino Donations are currently going through StreamElements, which means that you are essentially "donating to a streamer" as a way to show support. It would be a little time consuming to funnel the StreamElements API to add badges next to names on Chatterino, I believe. Not as easy as BTTV or FFZ for sure.

**Comment by apa420** [comment]
I don't see how it would work, donations are a one-time thing while subscriptions are not. I also don't see what benefit having a subscription would have since chatterino supporter doesn't provide any other features than a badge.

**Comment by fourtf** [comment]
Since we don't handle marketing on github I will close this
