### ISSUE TITLE
An in chat notification message for other channels going live

### ISSUE THREAD

**Issue by Yusuf-joe** [Chatterino/chatterino2#1797]
**What should be added?**
An in chat notification message across all channels that tells you if a channel in the "channels going live" list went live.

**Why should it be added?**
Twitch live notifications is usually much delayed than chatterinos live alerts, an informative live message in the chat for any channel in the list that goes live might be a good feature. I am imagining it would look the same as "hh:mm connected" or "hh:mm Now hosting shroud." messages and it would be something like "hh:mm shroud went live." to be displayed in forsens chat for example along with the sound alert.

**Comment by apa420** [comment]
A message in chat already exists when someone goes live.
For a pingsound you could add your channel in the toast notifications and only enable ping notification, then you'll get a pingsound that the channel has gone live (although you won't know what channel it is that has gone live).

I'll leave the issue open though since you're asking for a /live tab in chatterino (or similar)

**Comment by Yusuf-joe** [comment]
@apa420 

yeah /live tab would be ideal

A message in chat already exists when someone goes live, but only in that someones chat, right? not in other opened channels? my idea here is that people wouldnt have to switch to that /live tab even, they would get a message in whatever chat they have open, so if i have three tabs open /mizkif /nmplol /forsen and shroud went live, a message of "shroud went live" would appear in all of the three tabs i have open, given that i have shroud in the live notification list, does that already exist?

**Comment by apa420** [comment]
No, my suggestion for now would be to enable toast notifications for it (provided you are using windows) since they update within one minute of the stream going live.

**Comment by fourtf** [comment]
I can see a /live tab being useful
