### ISSUE TITLE
Chat message not sending during downtime

### ISSUE THREAD

**Issue by dozzzz02** [Chatterino/chatterino2#1798]
**Describe the bug**
So basically the chat messages are loaded in bulks. A very active stream sees a bulk of messages, a small pause (usually 1-3 seconds) and during this time any message you send is not actually sent.

**To reproduce**
Try to send a message after a bulk of chat messages are loaded.

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10

**Additional information**
Worth noting that normal twitch chat has the same thing where the bulk stuff happens, but there you can still send a message.

**Comment by zneix** [comment]
That often happens due to chat server dropping your messages in those "stressful" moments and I doubt there's anything we can do about that. Same thing happens in webchat, but your message is rendered as soon as you click enter to send it - that doesn't mean it actually goes through.

**Comment by Gallion** [comment]
I have the same issue however I don't think it has anything to do with there being a lot of chat traffic. On a stream where chat appears on screen, a message sent through the browser will work but a message sent through chatterino will not. Removing the tab, closing chatterino, reopening chatterino and readding the tab eventually fixes it.

**Comment by apa420** [comment]
that's a separate issue
