### ISSUE TITLE
Make image uploader warning check for deletion support

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1801]
**Why should it be added?**

The dialog is very scary:
> You are uploading an image to an external server.
> You may not be able to remove the image
> from the site. Are you okay with this?

**What should be added?**

If the user has filled out the Deletion link, we should not scare them that they might not be able to delete the image.

I would like to have the text changed to something like this:
> You are uploading an image to an external server.
> The server seems to have deletion support.
> Are you okay with this?

**Comment by zneix** [comment]
Thing is, the user defines whether the deletion link will be handled or not by filling deletion URL field, meaning, they can type anything in there (or misconfigure that one field) and image uploader won't provide a valid deletion link, thus, this might give a fair amount of false positivities.

**Comment by zneix** [comment]
I bet you want to have something like "dynamic warning" that would change based on whether we have deletion link specified or not, but how about just clarifying that with something that just says it's possible to configure deletion, for example:

> You are uploading an image to an external server. You won't be able to remove the image unless you have configured(/specified) deletion link in settings. Are you okay with this?

**Comment by pajlada** [comment]
> I bet you want to have something like "dynamic warning" that would change based on whether we have deletion link specified or not, but how about just clarifying that with something that just says it's possible to configure deletion, for example:
> 
> > You are uploading an image to an external server. You won't be able to remove the image unless you have configured(/specified) deletion link in settings. Are you okay with this?

seems good to me

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
