### ISSUE TITLE
Control+F should select the Find in settings input box

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1806]
**What should be added?**

I would like for `Control+F` to be able to select this input box.
![ch2-cf_2020-07-13_13-50](https://user-images.githubusercontent.com/25011746/87301444-1cf8e680-c4ff-11ea-8150-df8241a58cba.png)

**Why should it be added?**

Because `Control+F` is the find shortcut :)

**Comment by pajlada** [comment]
Please let me know if this hasn't been fixed in the latest Nightly once it's done building & pushing @Mm2PL :slightly_smiling_face:
