### ISSUE TITLE
Personal BTTV Emotes do not show on Chatterino

### ISSUE THREAD

**Issue by unclebeanbag7** [Chatterino/chatterino2#1808]
I rarely use Vanilla chat and the Personal Emotes feature for me is basically useless. 

**Screenshots**
Here is a comparison of what it looks like in vanilla and chatterino.
![image](https://user-images.githubusercontent.com/68268492/87394115-e52c8600-c574-11ea-8a3a-588dba02b3da.png)

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10

**Comment by zneix** [comment]
Duplicate of #12

**Comment by Mm2PL** [comment]
Not a bug, this is an unimplemented feature.

**Comment by apa420** [comment]
Duplicate of #12
