### ISSUE TITLE
Shift + arrow up not selecting text

### ISSUE THREAD

**Issue by cerib** [Chatterino/chatterino2#1816]
**Describe the bug**
In previous versions of chatterino, when you held shift and then arrow up (or down), it would move your cursor to the row above (or below) and select all the text on its way there. Now when I do this nothing happens. 

**To reproduce**
Type a word, hold shift and press arrow up. Your text won't be selected.

**Expected results**
Text should have been selected

**Operating system**
Windows 10 

**Additional information**
This selection behaviour is standard behaviour in almost every text input field, especially on web browsers, which leads me to believe this isn't intended behaviour. Also this makes spamming emotes much harder.

**Comment by apa420** [comment]
I can not replicate, I get desired outcome when shift+up arrow (it selects a row of text).
Chatterino Nightly 2.1.7 (commit 8e202c375, 21.06.2020)

**Comment by cerib** [comment]
> I can not replicate, I get desired outcome when shift+up arrow (it selects a row of text). (But only when holding shift)
> Chatterino Nightly 2.1.7 (commit [8e202c3](https://github.com/Chatterino/chatterino2/commit/8e202c37556ae969718d9be6e736e700be647bb1), 21.06.2020)

Can you please check with just one line of text? I noticed that if I have multiple lines of text it works fine until I reach the line on the top

**Comment by alazymeme** [comment]
Cannot reproduce using one or multiple lines. Selects text according to most other applications for me. Chatterino Nightly 2.1.7 (commit 214afc8fc, 25.07.2020)

**Comment by fourtf** [comment]
works for me
