### ISSUE TITLE
Suggestion for mentioning

### ISSUE THREAD

**Issue by Dinoslav** [Chatterino/chatterino2#1818]
Would be nice to have a fast way to mention the streamer. In BTTV chat you can just do @ and first nick that pops out in the menu is channel owner, so @ and enter quickly mentions the streamer.

**Comment by Mm2PL** [comment]
We currently don't have a popup menu for tab completion, how would you imagine this working without a popup like that?
P.S. The template is there to help.

**Comment by Dinoslav** [comment]
Maybe something like pressing TAB with no letters automatically choses¨the streamer. I think that could work fine

**Comment by Thehail** [comment]
Now that emote completion has been added, maybe adding this?

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
