### ISSUE TITLE
New usercard does not auto-close anymore

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1820]
**What should be added?**
In the nightly builds of chatterino the usercard with the added chat history now no longer closes automatically. It used to be that the popup would close automatically when its focus was removed.

**Why should it be added?**
I liked the old behaviour more. I don't think there is really much of a use case to keeping the user popup open. It's especially annoying when you click on a name accidentally, or when you want to give a user a ban/timeout quickly as a moderator. You now have to explicitly press the escape button or the close button, and god forbid you focus chatterino before closing the popup, because the you have to bring the popup back to focus using the task bar or alt-tabbing.

**Comment by rainstack** [comment]
It's probably a rare use-case, but the non-closing usercards have been helpful for modding. Makes it easier to follow and backtrack conversations to find the source of issues.

**Comment by dnsge** [comment]
Should this be a setting then? Chatterino could default to the old auto-close behavior and have a setting to keep them open.

**Comment by apa420** [comment]
I'd like this to be a toggleable setting imo.
I personally dislike the windows being open, but I can see the appeal for modding.
