### ISSUE TITLE
Twitch Emote Bug ( Silverhand ) smol

### ISSUE THREAD

**Issue by Space-Walrus** [Chatterino/chatterino2#1823]
**Describe the bug**
 Silver hand emote not appearing on chatterino, i've tried tab completing it, clicking on it though the emote menu, and typing it normally, I've also tried the non nightly build,  yet none of them work  Alazymeme (cunt)  also has the emote but is able to use it and visibly see it in chatterino. 

**To reproduce**
No idea , I'm the only that i've seen with this problem.

**Screenshots**
https://i.imgur.com/bSt5Qss.png 

**Chatterino version**
   Chatterino Nightly 2.1.7 (commit caa11dda3, 19.07.2020)

**Operating system**
Windows 10

**Comment by Space-Walrus** [comment]
idk im dank https://i.imgur.com/7KBjAOl.png

**Comment by pajlada** [comment]
Not a bug - Twitch doesn't send us the relevant emote data in the IRC message
See this raw IRC message you sent:
`@badge-info=subscriber/3;badges=subscriber/3,bits-charity/1;color=#A7F9F9;display-name=SPACEWALRUS;emotes=;flags=;id=232845e6-6e9f-49f4-8320-5d3c0af50489;mod=0;room-id=11148817;subscriber=1;tmi-sent-ts=1596288857725;turbo=0;user-id=175160053;user-type= :spacewalrus!spacewalrus@spacewalrus.tmi.twitch.tv PRIVMSG #pajlada :-tags Silverhand`

As Mm2pl explained in the above image, Twitch Web Chat does client-side rendering emotes where they see that you should indeed have access to the emote, but the Twitch chat servers disagree, so no one else can see your emote.
