### ISSUE TITLE
Windows CI bulid succeeds even though the build failed

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1829]
**Describe the bug**

Windows CI always says it succeeded.

**To reproduce**

  - Somehow trigger the CI with a syntax error in the code.
  - Observe that the Windows build still "worked".

**Screenshots**

![windomegalulws2020-07-28_12-12](https://user-images.githubusercontent.com/25011746/88653122-30897d00-d0bb-11ea-986d-38c1a9fc64bb.png)

**Commit**

Broken on `214afc8fc280320af68661d8b0ff833966a113f8`

**Additional information**

Yoinked the bug report template because it was the closest to a CI issue.

**Comment by alazymeme** [comment]
:rocket:

**Comment by fourtf** [comment]
is this still an issue?

**Comment by alazymeme** [comment]
> is this still an issue?

Yes iirc https://github.com/Chatterino/chatterino2/pull/2001#issuecomment-699624924

**Comment by Mm2PL** [comment]
No longer an issue
