### ISSUE TITLE
Dropping the write connection for twitch (Sending messages)

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#1831]
**Describe the bug**

Dropping connection the write connection for twitch (Sending messages).
Reading messages is fine, but randomly I can't send any messages anymore.
Restarting or reconnecting fixes this.

**To reproduce**

Wait for twitch to drop the connection...

**Screenshots**

**Chatterino version**

Chatterino Nightly 2.1.7 (commit 8e202c375, 21.06.2020)

**Operating system**

Windows 8.1 (Oops wrote win 10 before :P), pretty sure it also happens on arch

**Additional information**

It might be because I've been having packet loss issues with my internet.
Maybe there is a way to check if this connection dropped so we can reconnect?

**Comment by Mm2PL** [comment]
Sometimes happens for me too. It feels very random though.
My OS: Ubuntu Focal.

**Comment by gempir** [comment]
Can confirm I have had this happen to me multiple times aswell on Windows 10 and Ubuntu. Maybe once a week or so

**Comment by Felanbird** [comment]
Have it, friend complained as well. Both windows 10

**Comment by apa420** [comment]
Related #1500

**Comment by apa420** [comment]
Maybe it's an issue with twitch servers then? Is there some way we can hack a fix for it?

**Comment by Mm2PL** [comment]
> Maybe it's an issue with twitch servers then? Is there some way we can hack a fix for it?

Reconnecting after a dropped message is out of the question, since that can happen with spam filters. What else could be done?
If it is a Twitch issue we would have to bother them to fix it pepeLaugh

**Comment by gwua** [comment]
This has been happening for as long as I can remember. Last time it happened, I was downloading a file from Google Drive, which also caused a Twitch stream I was watching to stutter. OS is Windows 10.

**Comment by apa420** [comment]
I'm a bit unaware on how the connections work, but is it possible to send a PING on the write connection and see if we get a response? And if not try and reconnect? Or is this already something that exists.

**Comment by gempir** [comment]
This has been coming up recently a lot again. Lots of user complaints. Probably because TMI is dying a lot more, but still we could do a better job of reconnecting.

**Comment by pajlada** [comment]
Looking into this further in this PR: https://github.com/Chatterino/chatterino2/pull/2347

**Comment by SEAPUNK** [comment]
One thing I noticed is that it sometimes takes multiple reconnects before it "flushes" the writes - I get multiple "you're sending messages too quickly" messages upon reconnecting.

**Comment by apa420** [comment]
Closed by #2850
