### ISSUE TITLE
Rightclick emotes in emote popup

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1836]
**What should be added?**
Right clicking emotes in the emote popup
- copy image
- go to ffz/bttv page

**Comment by zneix** [comment]
Not sure, but isn't this a duplicate of #1735 ?

**Comment by cinemassacres** [comment]
also this https://github.com/Chatterino/chatterino2/issues/1740

**Comment by apa420** [comment]
Duplicate of #1735
