### ISSUE TITLE
Add the ability to search for Commands

### ISSUE THREAD

**Issue by zyfalls** [Chatterino/chatterino2#1839]
Add something that gives you the ability to search for trigger chat commands that you're trying to edit or delete

I have hundreds of commands that I edit very frequently and I have a hard time finding the certain command i'm trying to edit. I already trying going into the %appdata% but whenever I edit it there it doesn't save in chatterino2.

**Comment by apa420** [comment]
You need to close chatterino2 first before editing since when chatterino closes it will override that file (or keep chatterino open, edit stuff in file, close chatterino and then save the file and start chatterino again)

**Comment by fourtf** [comment]
This is unfortunately hard to implement.

This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
