### ISSUE TITLE
New player experience

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#184]
Chatterino isn't exactly very accessible to new users.

**Comment by TranRed** [comment]
I will write a "How to get started with chatterino 2" soon(tm). 

I think there should be two places for this: 

1. a file included in the deployed product
2. the FAQ page of chatterino.com

**Comment by fourtf** [comment]
I don't think that having a text file describing how to use the program is the right way to do it. I think the program needs to teach the user intuitively how it is supposed to be used. Nobody wants to read a manual do use a chat client.

**Comment by TranRed** [comment]
So like: Opens chatterino for the first time => pop up to connect your account --> into help/guiding opening your first channel ?

That seems really solid

**Comment by alazymeme** [comment]
Tracking - maybe a youtube video would make things easy to setup and we could link to that

**Comment by zneix** [comment]
Why was this closed? A good introduction guide for new users sounds like an excellent idea.

**Comment by alazymeme** [comment]
> Why was this closed? A good introduction guide for new users sounds like an excellent idea.

Documentation is out of scope for Chatterino
