### ISSUE TITLE
Sort Trigger Commands by alphabetical order

### ISSUE THREAD

**Issue by zyfalls** [Chatterino/chatterino2#1840]
Add the ability to sort trigger commands by alphabetical order

I find it hard to look through all the trigger commands in order to edit and delete them

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.

**Comment by Felanbird** [comment]
@zneix if ur bored :---)

**Comment by zneix** [comment]
I'll think about it, doesn't sound too difficult.

**Comment by Felanbird** [comment]
We even have this fancy clickable button that doesn't do anything https://i.imgur.com/T2wKEop.gif :)
