### ISSUE TITLE
Auto-open channel in browser when it goes live

### ISSUE THREAD

**Issue by mattman00000** [Chatterino/chatterino2#1841]
**What should be added?**
A checkbox in the channel menu and a list in the chatterino settings of channels that get opened automatically in a new browser window (open in new window might be nice alongside the open in browser button on channel menus too, but that's for another request)

**Why should it be added?**
It would enable chatterino to function as an alarm clock radio, for folks with a short (or as long as they can tolerate) list of channels they don't want to even miss the start of for lack of being at the keyboard.

and my c++ is a bit rusty but if someone points me in the direction of the browser opening and live notification sections of code i might try to take a whack at it

**Comment by apa420** [comment]
Right now you can click the live notifications to open the channel in browser. In my opinion this is sufficient and opening as soon as someone goes live seems very overkill. I in general dislike applications doing stuff when you're not directly commanding it. This would also mean that when someone goes live you'd lose focus of the current application and tab into the browser.

I personally don't see a use for this.

**Comment by Mm2PL** [comment]
This is probably something that could be made a mini mod or patch IMO. Any kind of automatic popup/focus stealer infuriates me, so I wouldn't use this.


The code handles the `channelName is live` chat\* notification, which might be the place to place this, lives here:
https://github.com/Chatterino/chatterino2/blob/e5f3bc9f3fcc0971f0e63102316ee8b72025abdf/src/providers/twitch/TwitchChannel.cpp#L479-L481

 - \* there is one more place that has a `is live` notification, that's for the system-wide one, but that only works on Windows atm

**Comment by mattman00000** [comment]
> Right now you can click the live notifications to open the channel in browser. In my opinion this is sufficient and opening as soon as someone goes live seems very overkill. I in general dislike applications doing stuff when you're not directly commanding it. This would also mean that when someone goes live you'd lose focus of the current application and tab into the browser.
> 
> I personally don't see a use for this.

I'm not sure how this all works, but i'm not familiar with why a minority use case is outright disqualifying. I notice there's some kind of triage system in place, and would be fine with this being low priority. And I absolutely detest focus-thieving apps too but i've gotten so used to them i've developed a tolerance for them when the feature benefits me. 

Also you've reminded me of a bug, which is that notifications that have expired into the notifications window won't open a browser when clicked. don't see it reported already so i'll make another issue for that.

> This is probably something that could be made a mini mod or patch IMO. Any kind of automatic popup/focus stealer infuriates me, so I wouldn't use this.
> 
> The code handles the `channelName is live` chat* notification, which might be the place to place this, lives here:
> https://github.com/Chatterino/chatterino2/blob/e5f3bc9f3fcc0971f0e63102316ee8b72025abdf/src/providers/twitch/TwitchChannel.cpp#L479-L481
> 
> * * there is one more place that has a `is live` notification, that's for the system-wide one, but that only works on Windows atm

didn't realize chatterino has mods or whatever, but thanks for the code location

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

**Comment by invalidhippo** [comment]
For anyone interested, I've written an application to fulfill this functionality. Launching in browsers isn't currently supported, but can be added later.
