### ISSUE TITLE
There is no way to paste clipboards that have URLs in it

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1842]
**Describe the bug**
When you press Ctrl+C while a track is in focus on foobar2000 playlist, it inserts special clipboard data, that can be interpreted as a song title or file name.
Here https://github.com/Chatterino/chatterino2/blob/682caf6b693b0a6880b8fba6790e0b28a4befea2/src/util/NuulsUploader.cpp#L223 it detects that clipboard contains some kind of URL, it fails to upload the file every time for obvious reasons, but it does not let me to actually paste the contents of clipboard into chat

**To reproduce**
press Ctrl+C while a track is in focus on foobar2000 playlist, try to paste into chat, expecting behavior before built-in image upload (song artist, album and title are pasted)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 515657be1, )

**Operating system**
Win 10 2004 19041.329

**Additional information**
If `askOnImageUpload` is enabled, it should try to determine clipboard contents first before asking and `Cannot upload file: %1. Not an image` path should be removed as it blocks pasting actual text stored in clipboard to the chat. If clipboard contents arent image, it should paste clipboard contents like it did before

**Comment by Mm2PL** [comment]
looks similar to #1688 
It's the fault of these functions:
https://github.com/Chatterino/chatterino2/blob/682caf6b693b0a6880b8fba6790e0b28a4befea2/src/widgets/helper/ResizingTextEdit.cpp#L261-L280

`canInsertFromMimeData` is a check for drag and drop that indicates if the Qt widget can support
`insertFromMimeData` pastes/uploads the image or w/e

The check for URLs is there to allow for uploading files from the file system.

**Comment by Mm2PL** [comment]
Fixed in #2855
