### ISSUE TITLE
Ubuntu Desktop Launch File

### ISSUE THREAD

**Issue by goldbattle** [Chatterino/chatterino2#1846]
I am not sure if this is already someplace, but I followed the [linux guide](https://chatterino.com/linux) for ubuntu 18.04.
I created a .desktop file that might be useful to others, and could be nice to add these instructions to the website page.
This will allow for quick searching for the program in the start menu.

## Install AppImage:
```
cd /usr/local/bin
sudo bash -c "curl https://chatterino.com/download/Chatterino-x86_64.AppImage > ./chatterino"
sudo chmod +x ./chatterino
```

## Create desktop entry:
```
sudo wget https://github.com/Chatterino/chatterino2/raw/master/resources/icon.png && sudo mv icon.png /usr/share/icons/chatterino.png
touch ~/.local/share/applications/chatterino.desktop
sudo chmod +x ~/.local/share/applications/chatterino.desktop
nano ~/.local/share/applications/chatterino.desktop
```

## Paste into chatterino.desktop:
```
[Desktop Entry]
Version=2.1.7
Name=Chatterino
Comment=Chatterino for Twitch
Exec=/usr/local/bin/chatterino
Icon=/usr/share/icons/chatterino.png
Terminal=false
Type=Application
Categories=Utility;Application;
```

**Comment by pajlada** [comment]
Could you try using this `chatterino.desktop` file instead and see if it works for you?
```
[Desktop Entry]
Type=Application
Version=1.0
Name=Chatterino
Comment=Chat client for Twitch
Exec=chatterino
Icon=chatterino
Terminal=false
Categories=Network;InstantMessaging;
```

**Comment by goldbattle** [comment]
That works for me if I download the icon file and have it named `chatterino.png` in `/usr/share/icons/`.

**Comment by zneix** [comment]
The example desktop file in `resources/` and the icon(s) should be enough to close this issue right now, right?
