### ISSUE TITLE
Chatterino chat history

### ISSUE THREAD

**Issue by analflute** [Chatterino/chatterino2#1849]
**Describe the bug**
I am unsure if this indeed is a bug, or if it's intended. Since maybe 2 weeks ago, chat history (shown in grey) after opening Chatterino shows maybe the last 20-30 minutes of past messages. 
I don't understand why it changed all of a sudden, but it used to show at least a couple of hours of past messages, when opening the application. 

**Chatterino version**
Chatterino Nightly 2.1.7 

**Operating system**
Windows 8.1

**Additional information**
I spent quite a lot of my time in active offline chat rooms when I'm home, so this change/bug? is quite inconvenient if you want to catch up on things since I can't spent all my time on my desktop. A solution or a fix would be greatly appreciated.

**Comment by Mm2PL** [comment]
Probably WaI. the amount of recent messages stored by the backend is lower. 

Relates to @randers00 's recent messages service, not chatterino per se.

**Comment by RAnders00** [comment]
It was always 24 hours maximum. It has been changed though to be 200 messages maximum, it was 800 messages before.

**Comment by RAnders00** [comment]
@analflute as of today the number of messages has been increased again, up to a maximum of 800 messages like it was before.
