### ISSUE TITLE
Copying Transparent Images does not keep transparency

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#1851]
**Describe the bug**
When you copy an image from the browser (I used chrome) that is transparent, and try to paste it into chatterino, it loses its transparency. When you copy the same clipboard to any upload page (imgur/nuuls) in chrome, it keeps its transparency. You can paste the image to Microsoft Word and it keeps its transparency. (Paint and Paint 3D e.g. loses it.)

**To reproduce**
Copy transparent image into clipboard (e.g. https://i.imgur.com/bhvDBEb.png )
Paste image into chatterino.
Click on the link - the image no longer has transparency.

**Chatterino version**
36dd640cd9da45aa8a9acdc75273c375159eca6b

**Operating system**
Windows 10

**Comment by cinemassacres** [comment]
this can happen if the image has [indexed colours](https://en.wikipedia.org/wiki/Indexed_color), and transparency is not one of the indexed colour values.

**Comment by hemirt** [comment]
do you have any examples that work then? (so that the person fixing it can test it, versus the frog picture in my comment)

**Comment by cinemassacres** [comment]
https://i.stack.imgur.com/5XeYV.png
https://i.stack.imgur.com/uKt3P.png

**Comment by cinemassacres** [comment]
https://i.imgur.com/VFQKp64.png
https://i.imgur.com/i4yzF9K.png

**Comment by hemirt** [comment]
those are just pictures without any transparencies ... ??? neither of them works

**Comment by apa420** [comment]
Tried on arch linux with firefox, brave (chromium) and qutebrowser (pyqtwebengine) and they all give a transparent image. [qutebrowser](https://i.nuuls.com/f3oU8.png) [firefox](https://i.nuuls.com/hZwIX.png) [brave](https://i.nuuls.com/mqmZI.png)

**Comment by pajlada** [comment]
Closing this as a can't-reproduce
