### ISSUE TITLE
Fedora RPM of Chatterino2 is available

### ISSUE THREAD

**Issue by komidore64** [Chatterino/chatterino2#1853]
Hi Chatterino!

I wanted to let you fine folks know that Chatterino is [available in Fedora](https://src.fedoraproject.org/rpms/chatterino2)! Please note that I am **not** the maintainer of this package and I have no influence over its building process.

I was recommended Chatterino and discovered it was already in Fedora. Cheers!

installation:

```
dnf install chatterino2
```

**Comment by cinemassacres** [comment]
needs to be put in here also https://chatterino.com/linux

**Comment by fourtf** [comment]
Glad to hear!

**Comment by cinemassacres** [comment]
make a pull request and link it https://github.com/Chatterino/chatterino2/blob/master/BUILDING_ON_LINUX.md

**Comment by fourtf** [comment]
> make a pull request and link it https://github.com/Chatterino/chatterino2/blob/master/BUILDING_ON_LINUX.md

That page is only for building, not installing

**Comment by apa420** [comment]
In the arch instructions it says you can use aur, so including the RPM one seems like it also fits.

**Comment by fourtf** [comment]
added here https://chatterino.com/linux

**Comment by fourtf** [comment]
I'll close now
