### ISSUE TITLE
Quick Switch: elements are dark even in light mode

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1854]
**Screenshots**
![image](https://user-images.githubusercontent.com/6320036/90171244-7889ee80-dda1-11ea-804a-10c476b394af.png)

**Comment by leon-richardt** [comment]
Related: The `SelectChannelDialog` shows a similar behavior.
![selectchanneldialog](https://user-images.githubusercontent.com/35232120/90233763-e7595d00-de1e-11ea-9df5-a65b1fd2b937.png)
