### ISSUE TITLE
Add an option to customize badges like FFZ does

### ISSUE THREAD

**Issue by bontalor** [Chatterino/chatterino2#1857]
**What should be added?**
Add an option to change the shape and use the old twitch badges like FFZ does: 
![ffz settings](https://user-images.githubusercontent.com/62087307/90234909-739f5c00-ddee-11ea-8ea9-7a19ee21121e.png)

**Why should it be added?**
It would allow for more customization

**Comment by leon-richardt** [comment]
Duplicate of https://github.com/Chatterino/chatterino2/issues/1461.

**Comment by alazymeme** [comment]
Duplicate of https://github.com/Chatterino/chatterino2/issues/1314

**Comment by apa420** [comment]
Duplicate of #1314
