### ISSUE TITLE
Windowed mode not supported in my recent windows update

### ISSUE THREAD

**Issue by Aesriyal** [Chatterino/chatterino2#1859]
Recent windows update (might've) messed with the chatterino interface 

**Screenshots**
https://gyazo.com/27cc9cc59cae6e16cf027840efd914c4

(idk if this is necessary)
https://gyazo.com/160c914a4b9870f39d91e95b0b8eb35c

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 1909v

**Comment by fourtf** [comment]
can't reproduce

**Comment by apa420** [comment]
Update to latest.
