### ISSUE TITLE
Unable to login via IRC with SASL auth

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1861]
**Describe the bug**
After the recent updates, I'm not longer able to log into an irc server with SASL auth (only tested with 1 server)

**To reproduce**
1. Try to join an IRC server with SASL auth
2. ??? xd
3. negative profit

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/90268513-79eb1200-de9a-11ea-973c-6e7417162cc9.png)

**Chatterino version**
Nightly 2.1.7 (commit 95d6be6bb, 13.08.2020)

**Operating system**
Windows 10

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/90309581-d14bab00-deb7-11ea-81c2-e7f93d3e5200.png)
a9080ceb

**Comment by alazymeme** [comment]
👍🏿
