### ISSUE TITLE
User cards are closed not only on explicit unfocus

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1866]
**Describe the bug**

User cards are closed on any unfocus event, not only ones triggered by clicking another window.

**Operating system**

Ubuntu 20.04, X11, i3
Bug might affect only Linux. I would like for someone with Windows to try to reproduce this :)

**To reproduce**

  - Make sure `Automatically close user popup when it loses focus` is checked.
  - Open a user card
  - Trigger an implicit unfocus event,
    - i3: Try to move it using $mod + left click
    - others: try pressing global WM shortcuts, like the mute/unmute, next/previous song buttons, move/resize/maximize keybinds
  - Observe that the user card gets deleted
  

**Screenshots**

![GIF of my dragging a user card with Super+left click](https://user-images.githubusercontent.com/25011746/90315752-6cbb3b00-df0d-11ea-8d52-904d2beb09d3.gif)

**Chatterino version**

Chatterino 2.1.7 (commit 95d6be6bb)
There's some weirdness with how Chatterino displays commits, my repo's HEAD is f1e12975 (`Revert changes to submodule libcommuni (#1864)`)

**Comment by apa420** [comment]
This is intended behaviour.
When you unfocus the popup, it should close.
If you do not want that I suggest you untick the checkbox :)

**Comment by Mm2PL** [comment]
> This is intended behaviour.
Is not being able to move the user card intended, that's what caught my attention, as it was a feature before? FeelsDonkMan

From what i recall before the changes to how user cards work it was fine and moving them worked.

**Comment by apa420** [comment]
I misread moving the usercard as moving from it.
I'm sorry.

**Comment by fourtf** [comment]
there's a setting?
