### ISSUE TITLE
Filter duplicate messages when loading recent messages

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1868]
**What should be added?**
When chatterino loads recent messages, it sometimes happens that you get a couple of messages "duplicated" because chatterino received the messages live, and then also fetches those messages from the recent messages service.

My suggestion is to consider the timestamp of the "oldest received message" when inserting recent messages, and to filter those recent messages that have a timestamp earlier or equal to that.

![image](https://user-images.githubusercontent.com/1629196/90318375-5672a680-df30-11ea-939a-5ad03244d222.png)

(Maybe use tmi-sent-ts, rm-received-ts or similar, or one could also compare messages for some kind of weak equality: IRC command, prefix and command must equal strictly, and all tags from the live message equal the tags present on the recent message)

**Why should it be added?**

**Comment by Mm2PL** [comment]
Blocks loading recent messages not on startup.

**Comment by leon-richardt** [comment]
> Can't find exact issue number

#1308?

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
