### ISSUE TITLE
Non-existent commands are announced as always lowercase

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1873]
**Describe the bug**
If you have a command that has uppercase letters, writing the command in chat with with wrong caseness, will always say "Unrecognized command: /pastorlul"

**To reproduce**
Add command "/pastorlul", write "/pastorLUL" in chat. "Unrecognized command: /pastorlul" will be written in chat despite it existing

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 515657be1, )

**Operating system**
Win 10 2004 19041.329

**Comment by TranRed** [comment]
maybe commands should just always be converted to lowercase. Or does anyone see a benefit in having a /pastorlul and a /pastorLUL command at the same time?

**Comment by TETYYS** [comment]
I see /MEGALUL and /MegaLUL having different meanings

**Comment by apa420** [comment]
The response you are getting is from twitch, not chatterino!
You are sending /pastorlul to the chat and twitch responds with that the command doesn't exist.
You can try typing /pastorlul in normal webchat, you will see the same response ;)

**Comment by TETYYS** [comment]
cool but kinda confusing
