### ISSUE TITLE
Open BTTV/FFZ link from emote menu

### ISSUE THREAD

**Issue by bontalor** [Chatterino/chatterino2#1877]
**What should be added?**
Add a link to the BTTV/FFZ page of an emote from the emote menu: 
![emotes 1](https://user-images.githubusercontent.com/62087307/90568214-734dea80-e179-11ea-9a35-5e49d77cce0f.png)

Like you can when they're already in chat: 
![emotes 2](https://user-images.githubusercontent.com/62087307/90568245-7f39ac80-e179-11ea-990d-816c2a9452b5.png)

**Why should it be added?**
This should be added so that a user is able to visit the page of an emote without having to type the emote in chat first.

**Comment by cinemassacres** [comment]
duplicate https://github.com/Chatterino/chatterino2/issues/1735

**Comment by apa420** [comment]
duplicate #1735
