### ISSUE TITLE
Always on Top window infection

### ISSUE THREAD

**Issue by mfmarlow** [Chatterino/chatterino2#1879]
**Describe the bug**
When using the "always on top" option and attaching Chatterino to a Chrome or Edge window via Window's split-screen feature, and then adjusting the split ratio, the attached Chrome/Edge window inherits the "always on top" property which persists after Chatterino is closed.

**To reproduce**
1. Move Chatterino to one edge of the screen to prompt Window's split-screen feature (may not prompt if "always on top" is already enabled)
2. Select a Chrome or Edge window to split the screen with Chatterino
3. Enable "always on top" in Chatterino general settings.
4. Select between the two windows to adjust the screen split ratio (don't necessarily have to adjust, just have to select)
5. Chome/Edge window will now be infected.

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 88f45a284, 15.08.2020)

**Operating system**
Windows 10 version 2004 build 19041.450

**Additional information**
Edge Version 84.0.522.61 (official build) (64-bit)
Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by apa420** [comment]
I'm very unsure how we can do anything to fix this issue, this seems to be either a windows or qt issue.

**Comment by fourtf** [comment]
Sorry I misread this. This doesn't seem like an issue that we can fix. Seems more like a windows bug on your system.
