### ISSUE TITLE
misconfigured embed

### ISSUE THREAD

**Issue by StephanBruh** [Chatterino/chatterino2#1882]
**Describe the bug**
When you click on "open player in browser" it gives you a error that the embed is misconfigured.

**To reproduce**
Click on the 3 dots next to the username and click on "open player in browser"

**Screenshots**
https://i.stephanbruh.nl/wEpi0/RUciDoWa54.png
https://i.stephanbruh.nl/wEpi0/VICoCiTI57.png

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 Pro

**Comment by Mm2PL** [comment]
Update to nightly. Broken by twitch.

**Comment by StephanBruh** [comment]
I see fixed now yes, Thanks
