### ISSUE TITLE
Add snapcraft building and publishing to a stable branch

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1887]
Here's the github action: https://github.com/snapcore/action-publish / https://github.com/snapcore/action-build
Might be something useful here as well (build params): https://snapcraft.io/
Channels: https://snapcraft.io/docs/channels (stable for stable branch, maybe also setup an edge channel as well on master?)

**Comment by fourtf** [comment]
This would be a great way to support all linux distributions at once without having to manually create packages for each repository. It might also be worth it to take a look at https://www.flatpak.org as an alternative. 

Personally, I've had issues with snap before (fonts not working, sound not working). However, I assume that we can manage to bundle things properly.

**Comment by leon-richardt** [comment]
Is worth supporting multiple packaging formats, i.e. AppImage, Flatpak, and Snap?
(Note that I have no real idea how much work maintaining these formats requires.)

**Comment by Mm2PL** [comment]
The current AppImage format is quite portable because it's just an ELF with libs and assets packed inside, however snaps have the advantage of having updates. Not really worth IMO since we have our own update mechanism which is required on Windows.

**Comment by alazymeme** [comment]
> Is it worth supporting multiple packaging formats, i.e. AppImage, Flatpak, and Snap?

Well the idea is that we find something that can automatic build, so maintaining them requires little work



> The current AppImage format is quite portable because it's just an ELF with libs and assets packed inside, however snaps have the advantage of having updates. Not really worth IMO since we have our own update mechanism which is required on Windows.

Not a big fan of appimage. I prefer to have things installed as opposed to being portable.



> This would be a great way to support all linux distributions at once without having to manually create packages for each repository. It might also be worth it to take a look at https://www.flatpak.org as an alternative.
> 
> Personally, I've had issues with snap before (fonts not working, sound not working). However, I assume that we can manage to bundle things properly.

What about ppa in apt? I only use ubuntu, so I'm not sure if that's available to other distros. Snap was really the only one I looked at (I think someone suggested it in pajlada's chat)

**Comment by alazymeme** [comment]
Flatpak resources:
https://www.flatpak.org/
https://github.com/marketplace/actions/flatpak-builder

PPA:
https://help.launchpad.net/Packaging/PPA
https://launchpad.net/+tour/ppa

Other:
https://docs.github.com/en/actions/publishing-packages-with-github-actions/about-packaging-with-github-actions#workflows-for-publishing-packages
https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/using-github-packages-with-github-actions#publishing-a-package-using-an-action

**Comment by alazymeme** [comment]
Snapcraft is terrible to work with and doesn't work for chatterino. If someone looks at this in the future, maybe look at ppa or flatpak

**Comment by alazymeme** [comment]
Just found out that a there's already a flatpak for it (released a few months ago): https://flathub.org/apps/details/com.chatterino.chatterino
