### ISSUE TITLE
Windows are brought back to life after closing the settings window

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#1892]
**Describe the bug**

Any popup window that was closed before closing the settings window will appear.

**To reproduce**

  1. Open a popup, like the `Search` popup.
  2. Close it.
  3. Open and close settings twice.
  4. Observe that the window popped-up again, even though it should have been destroyed.

**Screenshots**

N/A

**Chatterino version**

Head is `10692354` + my own patches. Using old Makefile, so Version display is bugged on my build.

**Operating system**

Ubuntu 20.04.1 LTS

**Additional information**

Using an emote picker popup (the one brought up using `:`) with an empty text box can crash, because of an assert. Be careful :).

**Comment by jammehcow** [comment]
Can reproduce (see #2551).

**Comment by pajlada** [comment]
Confirmed I can reproduce this. Will look into what causes this
