### ISSUE TITLE
2nd custom highlight color unchangeable 

### ISSUE THREAD

**Issue by AnsonX10** [Chatterino/chatterino2#1893]
When clicking the color for the 2nd highlight in the list, the color menu doesn't open. I've experienced it on Linux (KDE) and Windows. 

But I do love the new ability to change the color of highlights. Makes them infinitely more useful.

**Comment by dojima** [comment]
This bug still exists for me in 2.3.2.

**Comment by Mm2PL** [comment]
Looks like a faulty merge or @dnsge didn't incorporate this fix into their badge highlights feature
https://github.com/Chatterino/chatterino2/blob/master/src/widgets/settingspages/HighlightingPage.cpp#L356-L360
