### ISSUE TITLE
Windows out of bounds

### ISSUE THREAD

**Issue by maturz** [Chatterino/chatterino2#1896]
**Describe the bug**
Every time I start the application I get the dialog "Windows out of bounds" with the question "Some windows were detected out of bounds. Should they be moved into bounds?". It doesn't matter if I click yes or no the window will still have the same (not outside screen) position every time I start it.

**To reproduce**
I just start the application but I am using RDP while doing it (unable to test without because of GPU problems).

**Chatterino version**
I am using Chatterino 2.1.7 (commit 845c8fa63) "Chatterino Portable" from the site (tried downloading it and running a fresh version but had the same problem).

**Operating system**
Windows 7 Ultimate

**Additional information**

I could not find anyone else having this issue so maybe it is related to using RDP. I have tried multiple resolutions, also worth noting, the window position and size is always the same when I start it (e.g. a opening a folder will remember size and position). If I maximize the window it will start maximized but I still get the question about out of bounds. So my best guess is that this code

https://github.com/Chatterino/chatterino2/blob/11b894829072617b67d4ad06574e7c78c69d1def/src/singletons/WindowManager.cpp#L333-L337

Has an issue with screen size for RDP sessions. This issue is quite annoying both because you have to click a button every time and also because if you forget the client will not join any channels (so you might miss out on things happening). I realize this might not be a very high priority issue but maybe someone will see a very obvious solution or maybe someone already knows more about the problem. It could also be an indication that maybe the feature is not needed or has other problems since it doesn't seem to matter if I click yes or no.

**Update**, have replaced GPU and tried it without RDP but that didn't solve the problem did not seem to make any difference at all.

**Comment by fourtf** [comment]
Unfortunately there is not enough information to fix this issue. Also Windows 7 is not officially supported by Chatterino.
