### ISSUE TITLE
Staff changes to chatters list

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1900]
**Describe the bug**
Staff no longer appear in the chatters list - this should not be the case for mods

**To reproduce**
1. Be a mod
2. Have staff in chat
3. Can't harass staff anymore :/

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/90970377-a57b9580-e547-11ea-845b-2d9dbdb25dd5.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit f58450367, 22.08.2020)

**Operating system**
Windows 10

**Additional information**
If the user is a mod, their oauth should be sent to the chatters endpoint (to verify that they should see staff)

**Comment by RAnders00** [comment]
Does anything actually need to be changed in Chatterino. As a result, the users list just doesnt show staff anymore. We can't do anything about the API change. So what exactly are you requesting to be fixed @alazymeme?

**Comment by alazymeme** [comment]
> Does anything actually need to be changed in Chatterino? As a result, the users list just doesnt show staff anymore. We can't do anything about the API change. So what exactly are you requesting to be fixed @alazymeme?

Being logged in as a moderator should show the staff in the staff category - this is shown in the webchat screenshot bruv

**Comment by RAnders00** [comment]
It's only possible using the GraphQL api which we don't have access to

**Comment by alazymeme** [comment]
It's still a bug. Could probably have the blocked label to it.

**Comment by fourtf** [comment]
Since there is no public api for this feature it can't be implemented. Since it is unfixable I will close this issue.
