### ISSUE TITLE
When starting chatterino no split is selected

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#1911]
**Describe the bug**

When starting chatterino no split is selected.

**To reproduce**

Start Chatterino.
Try to type.
See that nothing is typed.
Make sure you have more than 1 tab though, since if you left off at the last tab that one will properly be selected.

**Screenshots**

**Chatterino version**

Chatterino 2.2.0 (commit 45a53bf0a)

**Operating system**

Arch
Windows 8.1

**Additional information**

**Comment by skullsir** [comment]
On Win 10 this ain't happening for me? Am I reproducing it incorrectly?

**Comment by apa420** [comment]
I just tested it on windows 10 as well to make sure.
And yes, it does still happen for me.

To reproduce:
1. Have at least two tabs  (Not two splits)
2. Select any tab except the very last tab before exiting
3. (If you don't click anything) No split (chat) is selected when opening chatterino again

**Comment by apa420** [comment]
I found something else out. The split that is selected is in the rightmost tab when starting chatterino. So if you start and nothing is selected and you start to type it will get typed in the rightmost tab's first split instead.
https://i.nuuls.com/xHz3Y.mp4

**Comment by fourtf** [comment]
fxied
