### ISSUE TITLE
When Chatterino starts it always fails to get version information (macOS Catalina)

### ISSUE THREAD

**Issue by ArthurGaliullin** [Chatterino/chatterino2#1913]
**Describe the bug**
When Chatterino starts it always fails to get version information.

**To reproduce**
Start Chatterino

**Screenshots**
<img width="515" alt="Screenshot 2020-08-24 at 09 30 21" src="https://user-images.githubusercontent.com/62056910/91011353-d3ff7c00-e5ec-11ea-931e-4fef85afd347.png">

**Chatterino version**
Chatterino 2.1.7 (commit 6229b2f43)

**Operating system**
macOS Catalina 10.15.6 (19G2021)

**Additional information**
I saw this bug a pretty long time ago but I didn't care much until new beta version of Chatterino. I have Bootcamp with Windows on the same machine and here this problem doesn't exists, I updated Chatterino on Windows to a new beta version. So it's not ISP or something like that. I've tried to reinstall Chatterino some time ago but it didn't help.

**Comment by herrhotzenplotz** [comment]
#1874 is related

**Comment by ArthurGaliullin** [comment]
So Chatterino doesn't officially supply builds for macOS too? Sounds strange for me, it's a pretty big platform.

**Comment by herrhotzenplotz** [comment]
> So Chatterino doesn't officially supply builds for macOS too? Sounds strange for me, it's a pretty big platform.

No, the issue seems to be, that macOS is not correctly detected.

**Comment by fourtf** [comment]
Could a mac user test two things for me?

1) check if the update information loading now works on the latest release'
2) check if it works on the newest nightly (it's currently building, will be ready in ~15 minutes) from here https://github.com/Chatterino/chatterino2/releases/tag/github-actions-nightly

**Comment by ArthurGaliullin** [comment]
1. Yep, it works on the latest release. Guess it was fixed somewhen between ~May and now.
2. Works here too as expected. Nice new arrow in .dmg :) 

Thanks a lot, closing issue
