### ISSUE TITLE
chatterino no longer able to pull stream online status while anonymous

### ISSUE THREAD

**Issue by nwff** [Chatterino/chatterino2#1915]
thinking this might be a recent twitch change but earlier today I was using 2.2.0 and this was working fine, then I used the builtin updater to update to 2.2.1 and now it doesn't show whether a stream is online or offline in the title bar at the top of the chat box. I suspect this also prevents 'stream has come online' desktop notifications

plugging in a twitch account and restarting chatterino causes this to function normally so it might be a twitch api change, idk

not sure if possible to fix but please investigate if you have time. you are probably already aware of the anonymous 'justinfan####' login twitch provides (provided?) as it seems to be common on google, maybe that could be made to work somehow

much appreciated

**Comment by Mm2PL** [comment]
Can't do anything. There is now a need for a valid oauth token which in this case should be attached to an account.

**Comment by cinemassacres** [comment]
should close this and add block

**Comment by iProdigy** [comment]
Could use kraken for anonymous connections while that API is still accessible

**Comment by cinemassacres** [comment]
@iProdigy  While you can [migrate from v3 to v5](https://dev.twitch.tv/docs/v5/guides/migration), know that v5 is deprecated and will be shutdown in the future. We prefer that you migrated directly to the [new Twitch API.](https://dev.twitch.tv/docs/api)

**Comment by iProdigy** [comment]
I'm well aware of v5 deprecation. Here's a summary of current api usage, and you can see other kraken usage: <https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/api/README.md>

I'd be happy to hear a scalable alternative from you on restoring this functionality for anonymous connections

**Comment by leon-richardt** [comment]
> Here's a summary of current api usage, and you can see other kraken usage:

As outlined in #1560, the idea is to move away from Kraken. I don't think it makes sense to invest time in implementing a feature using a deprecated API, well-knowing that it will be dropped in the near future.
