### ISSUE TITLE
Pop-up window with list of live channels you follow

### ISSUE THREAD

**Issue by Poggar** [Chatterino/chatterino2#1916]
**What should be added?**
A pop-up window that shows  which of the channels you follow are currently live

**Comment by leon-richardt** [comment]
Note for implementation: Getting the live channels should be reasonably simple with Kraken, using the [`Get Followed Streams` ](https://dev.twitch.tv/docs/v5/reference/streams#get-followed-streams) endpoint.

With Helix, it does not seem quite as straightforward. (Correct me if I'm wrong.)

**Comment by fourtf** [comment]
I recommend you turn on this setting instead: 
![image](https://user-images.githubusercontent.com/6320036/94325472-d7e13e00-ff9e-11ea-8a6e-0103d7c3643a.png)


This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
