### ISSUE TITLE
IRC Commands on connect doesn't work

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1917]
**Describe the bug**
`Send IRC commands on connect` doesn't work. It doesn't send the commands at all.

**To reproduce**
1. Setup an irc server with some connection commands
2. Notice it doesnt work

**Screenshots**
blacked out parts are just channels

![image](https://user-images.githubusercontent.com/12804673/91328000-a04d6d80-e809-11ea-8ae5-e708fa1773d5.png)

**Chatterino version**
Chatterino Nightly 2.2.1 (commit 63c167f1d, 24.08.2020)

**Operating system**
Windows 10

**Additional information**
xd

**Comment by Felanbird** [comment]
Like half the IRC issues, this randomly works now
tested on 5512437 & 508fea6 so it was fixed sometime before 508fea6 

![image](https://user-images.githubusercontent.com/41973452/121813443-16587f00-cc3a-11eb-8a68-8ad39a5d6a98.png)

**Comment by pajlada** [comment]
> Like half the IRC issues, this randomly works now
> tested on [5512437](https://github.com/Chatterino/chatterino2/commit/5512437f1bd5b2be7997b52bf36b04930446f3f1) & [508fea6](https://github.com/Chatterino/chatterino2/commit/508fea6382da5f05c21de9b62dda9ce22a6a3b79) so it was fixed sometime before [508fea6](https://github.com/Chatterino/chatterino2/commit/508fea6382da5f05c21de9b62dda9ce22a6a3b79)
> 
> ![image](https://user-images.githubusercontent.com/41973452/121813443-16587f00-cc3a-11eb-8a68-8ad39a5d6a98.png)

So you can confirm that this works in the commits you linked now?

**Comment by Felanbird** [comment]
> So you can confirm that this works in the commits you linked now?

yes
