### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by roomanoo** [Chatterino/chatterino2#1919]
**What should be added?**
An option to put multiple channel chats in one folder, once you click it will open the channels in that folder.

**Why should it be added?**
My chat is just a line because of the channels, adding a folder feature would really help!

**Comment by leon-richardt** [comment]
To me, this sounds similar to the idea suggested in https://github.com/Chatterino/chatterino2/issues/1484, would you agree?

**Comment by roomanoo** [comment]
Yes, actually it's the same thing
