### ISSUE TITLE
Recent commit to the ports tree

### ISSUE THREAD

**Issue by herrhotzenplotz** [Chatterino/chatterino2#1920]
I talked to a FreeBSD ports management team member and he commited a quick port. 

on FreshPorts: [https://www.freshports.org/net-im/chatterino2/](https://www.freshports.org/net-im/chatterino2/)

Note that issues during the build in the ports tree should not be reported to the Github issue tracker but rather to the [FreeBSD issue tracker](https://bugs.freebsd.org/bugzilla/buglist.cgi?component=Individual%20Port%28s%29&product=Ports%20%26%20Packages&resolution=---).
It can be installed by either:

`# cd /usr/ports/net-im/chatterino2/ && make install clean`
or
`# pkg install chatterino2`

I don't know where to add a note for that here, that's why I opened this issue.

**Comment by fourtf** [comment]
I will add this to the chatterino website shortly.

**Comment by herrhotzenplotz** [comment]
Sounds good to me! :+1:

**Comment by fourtf** [comment]
added here https://chatterino.com/freebsd and linked on https://chatterino.com/
