### ISSUE TITLE
Crash when new tab of Firefox is created

### ISSUE THREAD

**Issue by MrAuro** [Chatterino/chatterino2#1921]
**Describe the bug**
Chatterino crashes when a new Firefox tab is created

**To reproduce**
Takes a few tries to reproduce, but you just need to have Chatterino open and create a new tab in Firefox.

**Screenshots**
[Video of it crashing](https://youtu.be/OTF-YAkYBc4)

**Chatterino version**
Chatterino 2.2.1 (commit 63c167f1d)

**Operating system**
Windows 10, Firefox Version 80.0

**Additional Information**
I have the Chatterino browser extension installed just for the watching feature. The Chatterino seen in the video is the main client, not a clone by the extension

**Comment by apa420** [comment]
There is some issue related to this on the chatterino extension github page
