### ISSUE TITLE
Can't use Chatterino in any way, can't even interact with the window

### ISSUE THREAD

**Issue by dgva** [Chatterino/chatterino2#1923]
**Describe the bug**
When lauching, it opens the normal window, but only during 2-3 seconds, and can't interact with anything. It just closes itself with no error or warning. Already uninstalled completly and installed again (with Revo Uninstaller), reseting the cache and the old settings during install. Already checked the  VC++ 2017 Redistributable, it is installed properly too.

**To reproduce**
For me, just opening the program, even in admin mode. Nothing makes the program run.

**Screenshots**
 No images, the program doesn't show anything 

**Chatterino version**
 From the Chatterino page, i downloaded the 2.2.2 version 

**Operating system**
Windows 10 Home 

**Additional information**
Already tried to install 2.2.1 and 2.2.0, either won't work too.

**Comment by Mm2PL** [comment]
Can you please try the portable version, for example on your desktop?

**Comment by dgva** [comment]
Same behaviour, no difference at all.
Probably doesn't matter, but I'm on a laptop, MSI GL63 8SD.

**Comment by fourtf** [comment]
Since we can't really help you I'll close this.
