### ISSUE TITLE
Emote picker is only appearing on the primary screen

### ISSUE THREAD

**Issue by tollyx** [Chatterino/chatterino2#1926]
**Describe the bug**
Whenever I open the emote picker it always opens up on my primary screen, even when I have previously opened, moved over and closed the emote picker on my secondary screen where I have chatterino open.

**To reproduce**
1. Have two or more screens
2. Open up the emote picker
3. Move the emote picker to a secondary screen
4. Close the emote picker
5. Open the emote picker again

It should open back up on the same spot you closed it, but it appears on the edge of the primary screen instead.

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10 Pro (Version 2004, OS Build 19041.450)

**Additional information**
I've tried it with having the secondary screen on both the left and right sides of my primary screen and it does not seem to matter, neither does the fact that the primary and secondary screens have different resolutions (1440p and 1080p, tried having both on 1080p). The issue persists either way.

From a quick search around some the codebase and some issues and PRs, my initial guess would be that `desktop->availableGeometry(parent)` in this function (which ends up being called when the event picker tries to move to its previous position) does not consider my second monitor as available, somehow:
https://github.com/Chatterino/chatterino2/blob/07fc0c3ad7c2ea3495b3c3fafb97b16bff56fa36/src/widgets/BaseWindow.cpp#L587-L626

**Comment by pajlada** [comment]
Further information in the duplicate issue #2240

**Comment by emerysteele** [comment]
still broken

**Comment by emerysteele** [comment]
Still opening on wrong screen. 

Also further issues with a 3 monitor setup like this:
![ApplicationFrameHost_8TtmqLkB9W](https://user-images.githubusercontent.com/1169001/195219759-33d46269-63d7-4438-bada-94e637d136f2.png)


, having chatterino on the third monitor, the emote menu doesn't show up at all. I have to move chatterino to my primary or secondary monitor, close chatterino, re-open it, then the emote menu shows up. But if I move chatterino back to my third monitor, the emote menu stops showing again.

**Comment by Felanbird** [comment]
> Still opening on wrong screen.

That's why the issue is still open.

**Comment by emerysteele** [comment]
> 

Sorry, I figured I'd bump it incase forgotten 🥺

For the triple monitor emote menu issue I'm having, I think the emote menu is opening, just opening somewhere in the void. Was able to work-around it by using DisplayFusion to automatically move all Chatterino windows to the third monitor on Focus
