### ISSUE TITLE
Add a channel for Mod Actions

### ISSUE THREAD

**Issue by MIGI10** [Chatterino/chatterino2#1927]
**What should be added?**
The possibility to add a channel where all mod actions from a Twitch channel would appear (only if you're mod in that channel of course). Exactly like the Mod Actions widget from Mod View. You can popout that widget using this link: https://www.twitch.tv/popout/moderator/channel/moderator-actions and it looks like this: 
<img width="573" alt="Screenshot 2020-09-01 at 14 47 15" src="https://user-images.githubusercontent.com/33965011/91853114-0864df00-ec62-11ea-8610-febe5c3a7021.png">

**Why should it be added?**
It would be helpful for moderators as we could have the chat and a mod actions channel in the same place. Also, with this feature we can avoid depending on and having Mod View open in the background.

**Comment by Mm2PL** [comment]
Looks like it can be done with #1748. Loading actions that happened before starting the client with reasons is impossible because the twitch api requires broadcaster oauth, best possible is using recent-messages and getting all the CLEARCHATs.

**Comment by MIGI10** [comment]
> Looks like it can be done with #1748. Loading actions that happened before starting the client with reasons is impossible because the twitch api requires broadcaster oauth, best possible is using recent-messages and getting all the CLEARCHATs.

I use chatterino in Mac and I can't find any "Filters" settings.

**Comment by Mm2PL** [comment]
> > Looks like it can be done with #1748. Loading actions that happened before starting the client with reasons is impossible because the twitch api requires broadcaster oauth, best possible is using recent-messages and getting all the CLEARCHATs.
> 
> I use chatterino in Mac and I can't find any "Filters" settings.

That's because that Pull request is not yet merged. If you want to test it you can download a build of the code [here](https://github.com/Chatterino/chatterino2/suites/1109115758/artifacts/15568491) or use [my](https://github.com/Mm2PL/chatterino2/suites/1145232251/artifacts/16459639) build, which contains the code of this PR, some of my patches and is based on a new chatterino nightly.

**Comment by MIGI10** [comment]
> > > Looks like it can be done with #1748. Loading actions that happened before starting the client with reasons is impossible because the twitch api requires broadcaster oauth, best possible is using recent-messages and getting all the CLEARCHATs.
> > 
> > 
> > I use chatterino in Mac and I can't find any "Filters" settings.
> 
> That's because that Pull request is not yet merged. If you want to test it you can download a build of the code [here](https://github.com/Chatterino/chatterino2/suites/1109115758/artifacts/15568491) or use [my](https://github.com/Mm2PL/chatterino2/suites/1145232251/artifacts/16459639) build, which contains the code of this PR, some of my patches and is based on a new chatterino nightly.

Thank you for your build, the advanced filters option works perfectly but it seems like there's a bug, when pressing a username, in the user info popup, the mod actions for timeout/ban no longer appear.

In 2.2.2 stable version: 
<img width="431" alt="Screenshot 2020-09-07 at 00 44 39" src="https://user-images.githubusercontent.com/33965011/92336673-6733b980-f0a3-11ea-8a79-fee6802a19cb.png">

In your build:
<img width="424" alt="Screenshot 2020-09-07 at 00 44 19" src="https://user-images.githubusercontent.com/33965011/92336676-71ee4e80-f0a3-11ea-87ca-e01c24f27626.png">

**Comment by zneix** [comment]
Correct me if I'm wrong, but what @MIGI10 mentioned in their latest comment seems to work for me
![danks pajlada](https://cdn.zneix.eu/xQpQxQ6.png)

Also, @MIGI10 please tell me whether the current solution with filters is enough to close this issue, as I don't really see something like a special `#/modactions` channel coming to chatterino any time soon.

**Comment by MIGI10** [comment]
Yeah, it's okay with filters, the issue can be closed.
