### ISSUE TITLE
Migrate more endpoints from V5 to Helix

### ISSUE THREAD

**Issue by iProdigy** [Chatterino/chatterino2#1928]
**What should be added?**

- [x] [Kraken getChannel](https://github.com/Chatterino/chatterino2/blob/9a8b85e338ba4fe3b2bb1eee81f3f6f05387959f/src/providers/twitch/api/Kraken.cpp#L10) can be replaced by [Helix getChannelInformation](https://dev.twitch.tv/docs/api/reference#get-channel-information) (which also retrieves stream title/games for offline channels, but will not work for anonymous users)

- [x] [TwitchAccount followUser](https://github.com/Chatterino/chatterino2/blob/17aa3f71cd2b154c7016806dca4f03c606007c1c/src/providers/twitch/TwitchAccount.cpp#L291) can use [Helix createUserFollows](https://dev.twitch.tv/docs/api/reference#create-user-follows) instead of Kraken (note: this will require a new scope `user:edit:follows`).

- [x] [TwitchAccount unfollowUser](https://github.com/Chatterino/chatterino2/blob/17aa3f71cd2b154c7016806dca4f03c606007c1c/src/providers/twitch/TwitchAccount.cpp#L309) can use [Helix deleteUserFollows](https://dev.twitch.tv/docs/api/reference#delete-user-follows) instead of Kraken (note: this too requires `user:edit:follows`).

- [x] [TwitchChannel refreshCheerEmotes](https://github.com/Chatterino/chatterino2/blob/83b6fad8e6a6ed33972cefd6e9f6a09a773e1cb5/src/providers/twitch/TwitchChannel.cpp#L796) can use [Helix getCheermotes](https://dev.twitch.tv/docs/api/reference#get-cheermotes) instead of Kraken (note: I have heard some reports of this endpoint not returning all emotes in the past - may be fixed now. Also, this can break things for anonymous users).

- [x] [TwitchAccount loadIgnores](https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchAccount.cpp#L92) can use [Helix Get User Block List](https://dev.twitch.tv/docs/api/reference#get-user-block-list) instead of Kraken (note: this needs the `user:read:blocked_users` scope)

- [x] [TwitchAccount ignoreByID](https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchAccount.cpp#L166) can use [Helix Block User](https://dev.twitch.tv/docs/api/reference#block-user) instead of Kraken (note: this needs the `user:manage:blocked_users` scope)

- [x] [TwitchAccount unignoreByID](https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchAccount.cpp#L243) can use [Helix Unblock User](https://dev.twitch.tv/docs/api/reference#unblock-user) instead of Kraken (note: this needs the `user:manage:blocked_users` scope)

**Why should it be added?**
Good to get off deprecated APIs. If breaking things for anonymous users is a no-no, perhaps we could use the Kraken API in [one more place](https://github.com/Chatterino/chatterino2/issues/1915#issuecomment-684180177) while possible to retain the current featureset.

**Additional Information**
New scopes can be requested at a later date as twitch is providing a grace period where v5 scopes are accepted for helix: https://dev.twitch.tv/docs/api/migration#authentication-scopes

**Comment by RAnders00** [comment]
going forward, the only way to provide feature to anonymous users is to send the requests via a self-hosted service (https://github.com/Chatterino/api ?) that then uses an app access token.

**Comment by zneix** [comment]
Just letting you know I have already migrated follow/unfollow methods to helix already, I am in the process of migrating cheeremotes and could also do getChannel unless someone else wants to do it.

**Comment by pajlada** [comment]
More endpoints that can be migrated!!!
https://discuss.dev.twitch.tv/t/announcing-helix-endpoints-for-channel-editors-deleting-videos-and-managing-blocked-users/29947
