### ISSUE TITLE
Disconnection and reconnection

### ISSUE THREAD

**Issue by BrickCG** [Chatterino/chatterino2#1941]
**Describe the bug**
I will be using chatterino and I will get randomly disconnected for about 1-2 minutes no messages will show at all then says reconnected and starts to work in about another 10 seconds. My internet isn't going out either because the stream that I am watching continues.

Screenshots
https://imgur.com/a/dHuQ5Zt

**Chatterino [version**]
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
 Windows 10 

**Additional information**
I've tried reinstalling 2 different times I have also seen something where it says to not have more than 100 tabs I currently only have 4 so im not really sure what to try from here and have also added and removed my account several times which seems to work for about 5 min then the same problem occurs

**Comment by apa420** [comment]
All know issues.
Twitch drops connection randomly
You can't have more than 100 rooms open, twitch limit.
Close some tabs.
