### ISSUE TITLE
when you click on the version number at the top it should be copyable to paste

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1942]
**What should be added?**

when you click on the version number at the top it should be copyable to paste
**Why should it be added?**

when some one has a problem with chaterino we can easily copy it with out having to go to the about page

**Comment by leon-richardt** [comment]
I doubt this would be implementable without using client-side window decorations. And even with client-side decorations, I imagine it would be hard to get a consistent look-and-feel across all OS and window managers users run Chatterino on.

This was precisely the reason for #1315: having an unintrusive place to check the version on all setups.
