### ISSUE TITLE
Ability to see "Following since"/"Subbed for X months"

### ISSUE THREAD

**Issue by AEM7** [Chatterino/chatterino2#1946]
**What should be added?**
Title pretty much covers it. BTTV allows you to see how long someone (including yourself) has been following a particular channel and subbed to it including what tier on the user card.

**Why should it be added?**
 Follow since/Subbed for X months are convenient features that I mostly use on myself to see how long I've been following or subbing to a channel, but it's also something I'm used to when using BTTV chat in the past.

Sorry if these features were requested in the past, I didn't see them after a quick search and I'm new to Chatterino.

**Comment by AEM7** [comment]
Going to write an addendum on another suggestion as well here, the ability to customize how deleted messages are displayed, such as having the deleted message strikethrough'ed as well as grayed so it's more discernible in faster chats.

**Comment by leon-richardt** [comment]
> Also adding the ability to import/export Chatterino settings to quickly transfer between PC's.

In the settings under the "AppData" section, there is a button which will take you to the directory that contains your Chatterino settings (as well as automatically created backups). You can just copy-and-paste them from there.



> BTTV allows you to see how long someone (including yourself) has been [...] subbed to [a particular channel] including what tier [...]

This information is available when hovering a sub badge. (Although tooltips would need to be enabled, I assume.) I could definitely see this also being added to the user card as well, though.

**Comment by AEM7** [comment]
Thanks for the response. I figured CV'ing the settings folder was a backup method, but I guess a one click backup/restore option would be nice.

I knew about the hovering over the sub badge to see how many months someone was subbed, but I think have the exact follow/sub date on the cards would be a good feature.

**Comment by alazymeme** [comment]
The followage issue can be found here: https://github.com/Chatterino/chatterino2/issues/1122
The subage issue can be found here: https://github.com/Chatterino/chatterino2/issues/1145
BUT I believe this isn't correct anymore. @pajlada is there now a public API to get the subage?

Either way, this should be split into separate issues as these are three very different things.

**Comment by fourtf** [comment]
this contains two issues so I'll edit this

**Comment by zneix** [comment]
I am in the process of making a pull request closing this issue. Getting followage is entirely possible via Kraken, but for subage I would have to use @leppunen's subage API, but I am not sure whether he'd be okay with that.
