### ISSUE TITLE
Show own bit emotes in emote menu

### ISSUE THREAD

**Issue by 32803** [Chatterino/chatterino2#1947]
**What should be added?**
Noticed how your own bit emotes as an affiliate or partner, don't show up in the emote menu and as a result dont autocomplete either.

**Why should it be added?**
Just a bit annoying that you can't autocomplete them, hence why i put it as a low priority suggestion and not an actual issue with chatterino. 
Maybe i'm just danking up and there's some setting in chatterino that enables this but as far as i know that doesnt exist FDM

**Comment by apa420** [comment]
Duplicate of #1450
