### ISSUE TITLE
when using middle mouse button over chaterino the scroll wheel is bigger then intended

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1949]
**Describe the bug**

when using middle mouse button over chaterino the scroll wheel is bigger then intended
**To reproduce**

use the middle mouse button over chaterino
**Screenshots**

https://streamable.com/mw80br
**Chatterino version**
 N/A

**Operating system**

N/A
**Additional information**

**Comment by leon-richardt** [comment]
It is not "bigger than intended". We do not try to emulate Chrome's/Firefox's scroll wheel, Chatterino uses an own implementation.
