### ISSUE TITLE
File Sharing in IRC's?

### ISSUE THREAD

**Issue by iAmAnt1** [Chatterino/chatterino2#1950]
There's an IRC in the beta of Chatterino 2 and I think there should be file sharing so its much easier to get any downloads instead of having to put a link for a mega website and others like that. Images work but not mp4s or zip files.

**Comment by zneix** [comment]
That would basically require image uploader module to be more than just image uploader, I think it was suggested before and might be cool, but some destinations only support images and other might have an upload cap, so I don't know how is it possible to implement.

**Comment by cinemassacres** [comment]
what would be the cap at which we won't/can't upload a file?

**Comment by gempir** [comment]
I think it's kinda too much to for an IRC client to be a file uploader at the same time. The image uploader is already a stretch IMO. There are other very good tools to upload files and save you a link in the clipboard you can just post in chat.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project. Consider using a file uploader instead.
