### ISSUE TITLE
visual duplication

### ISSUE THREAD

**Issue by mvnkey** [Chatterino/chatterino2#1952]
**Describe the bug**
After doing a certain pattern of actions, the edge of my chatterino duplicates.

**To reproduce**
The way i replicate it, is by grabbing the chatterino tab and sticking it to the edge of the screan to auto fill, and then grab it from the top bar and push it towards the edge of the screan https://i.nuuls.com/W5Dz_.mp4 .

**Screenshots**
the process to make the bug work
https://i.nuuls.com/W5Dz_.mp4

end result
![](https://i.nuuls.com/FnBCe.png)

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10, Version 1903 (OS Build 18362. 1082)

**Additional information**
N/A

**Comment by alazymeme** [comment]
Can't reproduce. Windows 10, Chatterino Nightly 2.2.2 (commit 9ae79e650, 30.08.2020)

**Comment by RAnders00** [comment]
@mvnkey Could you also tell us about your exact version of Windows 10 used?
- Open the Windows Run dialog by pressing Windows Key+R
- type `winver` and press Enter
- Tell us about the version it says, e.g. in my case it says `Microsoft Windows, Version 2004 (Build 19041.508)`

**Comment by mvnkey** [comment]
Microsoft Windows Version 1903 (OS Build 18362. 1082)

**Comment by zneix** [comment]
@mvnkey does this still happen when using [latest nightly](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build)?

**Comment by zneix** [comment]
If it does, please re-open the issue. Pretty sure it could have something to do with Windows version as well. Try updating and see if the issue persists.
