### ISSUE TITLE
Como cambio la tipografia de mi chat?

### ISSUE THREAD

**Issue by astorrsuenn** [Chatterino/chatterino2#1953]
Tenia ganas de cambiar la tipografia de mi chat porque habia visto algunos streamers que lo tenian con otra fuente, si me ayudan les agradeceria un monton!! gracias<3

**Comment by cinemassacres** [comment]
en la configuración vaya a general y haga clic en la fuente

**Comment by cinemassacres** [comment]
can close this

**Comment by fourtf** [comment]
1) haga clic en el icono de la rueda dentada
2) haga clic en lo siguiente:
![image](https://user-images.githubusercontent.com/6320036/92803045-56db5180-f3b7-11ea-91d1-da33abf4a9a8.png)

I hope this helps. I'll close this since it is not a persistent issue
