### ISSUE TITLE
Cant run chatterino after recovering data

### ISSUE THREAD

**Issue by stellarakshay** [Chatterino/chatterino2#1954]
So my hard disk got corrupted and luckily i was able to recover the data, but after recovering, everytime i try to open chatterino i get these errors:
![explorer_vn8o0fiiId](https://user-images.githubusercontent.com/42245576/92897713-0dcce100-f43b-11ea-905c-922391c8bcd6.png)
![explorer_sulwXP9AQS](https://user-images.githubusercontent.com/42245576/92897753-145b5880-f43b-11ea-8185-08839458c716.png)
what should i do? I tried uninstalling and deleting everything but it doesnt work :/

**Comment by Mm2PL** [comment]
Looks like visual c++ runtime redistributables are missing

**Comment by stellarakshay** [comment]
> Looks like visual c++ runtime redistributables are missing

Where would those usually be located?

**Comment by zneix** [comment]
@stellarakshay you need to download vcredist packages from Microsoft's site and that should fix your issue. You can look those up, but if you want a solution that will surely work, download chatterino installer from https://chatterino.com, simply reinstall and while installing the application, make sure to check "install vcredist packages" (or something similar) - this way, correct vcredist package will be installed alongside chatterino.

This issue happens quite often when trying to start chatterino after fresh install etc.
If this fixes chatterino, make sure to close the issue :)

**Comment by stellarakshay** [comment]
That seemed to have worked, but every time i run it it just crashes after like 10 seconds. Im gonna keep trying tho

**Comment by stellarakshay** [comment]
![](https://i.imgur.com/qgAoTfj.png)
this is what keeps happening, dk what to do

**Comment by alazymeme** [comment]
Make sure you run both installers:
x86: https://aka.ms/vs/16/release/vc_redist.x86.exe
x64: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by stellarakshay** [comment]
still crashing after like 5 seconds

**Comment by zneix** [comment]
@stellarakshay You said your hard disk got corrupted, so I assume dll files in your system and some other stuff might've got corrupted as well and the best solution would be just reinstalling the operating system.
If you didn't have this issue before data corruption, then please try my advice and see if it helps.

**Comment by stellarakshay** [comment]
i was able to recover all of the settings and it eventually worked after restarting. Thanks for help @zneix @alazymeme @Mm2PL
