### ISSUE TITLE
Chatterino crashes sway when opening links

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#1955]
**Describe the bug**
In a particular situation (described below), Chatterino completely crashes [sway](https://github.com/swaywm/sway) when opening a link.

**To reproduce**

1. Have two monitors.
2. Open a browser instance on your first monitor, and another browser instance on your second monitor.
3. Open Chatterino on your second monitor, preferably on the **left edge**.
4. Focus the browser instance on the first monitor. Then switch focus to Chatterino (do not focus the browser instance on the second monitor while doing so!), and click a link.
5. This is where behavior differs: In some cases, sway crashes immediately. In other cases, it crashes after approx. 2 to 5 seconds.

**Chatterino version**
Tested on commit 36b9466f8985769489ed8b05d23fe057bbb75660.

**Operating system**
Arch Linux 5.8.8-arch1-1
sway version 1.5

**Additional information**
I am not 100% sure whether this is actually Chatterino's fault but I have not observed this behavior with other applications yet.

Tested with Firefox and Chromium.

**Comment by fourtf** [comment]
I don't see how opening a link would be a chatterino issue

**Comment by leon-richardt** [comment]
Actually, it's probably rather a Qt issue of some kind. Nonetheless, Chatterino is the only Qt app I observed this behavior in.

**Comment by leon-richardt** [comment]
Just wanted to give an update on this: sway version 1.5.1 seems to have fixed this in part. Chatterino still crashes on the situation described in the OP but at least sway continues running.
