### ISSUE TITLE
Add dictionary (Spell Check) Feature

### ISSUE THREAD

**Issue by Caldohhh** [Chatterino/chatterino2#1961]
**What should be added?**
Add a dictionary to be a part of Chatterino to allow spell check when sending a message.

**Why should it be added?**
Convenience feature that simply would be another enhancement. Also, the ability to have it enabled/disabled for user preference.

**Comment by leon-richardt** [comment]
Duplicate of #16.

**Comment by apa420** [comment]
Duplicate of #16
