### ISSUE TITLE
Completing emote name with "colon"-based autocomplete doesnt work right with different capitalizations

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1962]
**To reproduce**
- type `:pepela` in a channel which has both `pepeLaugh` and `PepeLaugh` enabled (e.g. currently https://twitch.tv/pajlada or https://twitch.tv/forsen)
- `pepeLaugh` should come before `PepeLaugh` in the list
- Use arrow keys to navigate to `PepeLaugh`
- Press Tab
- The text field becomes `pepeLaugh`

Expected would be that the input field is filled with `PepeLaugh`, since I had it selected.

Curiously, the input field is filled with `PepeLaugh` if I use Enter instead of Tab, or if I left-click the entry.

**Screenshots**
![image](https://user-images.githubusercontent.com/1629196/93001616-85c90300-f530-11ea-9eb3-6c16af9b8521.png)
![image](https://user-images.githubusercontent.com/1629196/93001627-97120f80-f530-11ea-9e33-efffa8437305.png)
![image](https://user-images.githubusercontent.com/1629196/93001637-a42efe80-f530-11ea-8676-9e5ff14310a2.png)

**Chatterino version**
Chatterino Nightly 2.2.2 (commit c7a2f4cc9, )

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
Can reproduce. I believe this is due to tab not actually selecting the selected emote, but rather reverting to the default tabbing behaviour of chatterino 2.
Chatterino Nightly 2.2.2 (commit 1baa2b266, 11.09.2020)

**Comment by RAnders00** [comment]
It doesn't seem like tab reverts to default behaviour. If you type `:pepel`:

![image](https://user-images.githubusercontent.com/1629196/93014949-88ba0700-f5b5-11ea-96c9-03992e4162df.png)

And then select one of the two `pepeLaugh`/`PepeLaugh` entries, then press tab, `pepeLaugh` is put into the input field. If you select `pepeL` from the list, `pepeL` is put into the input box.

If it reverted to default tab behaviour it would complete with `pepeL` on all of the three entries.

**Comment by fanway** [comment]
It's default tab behavior. What happens is when you press the tab in a colon menu, it will put PepeLaugh into the input and then will press tab on it. If you try to press tab on PepeLaugh in the input field, it will give you pepeLaugh in this example.
