### ISSUE TITLE
Change the color of names in messages to match the users name color

### ISSUE THREAD

**Issue by okhuntre** [Chatterino/chatterino2#1963]
Add an option to or just change the color of names in messages to match the users name color.

This should be added because it's a feature in web chat(not sure if its from ffz or bttv thought). It also makes it much easier to tell  when a message is directed towards a specific user rather than just in chat.

**Comment by pajlada** [comment]
Could you please attach an image of the feature you're referring to? I'm not familiar with it. Thanks!

**Comment by th3an7** [comment]
![image](https://user-images.githubusercontent.com/13398380/93652376-18780f00-fa15-11ea-96cc-7be542daf3b6.png)
I believe it's this (colored mentions)

It's FFZ option but according to SirStendec, Twitch does not provide username colors themselves so FFZ needs to cache them when someone sends message...
This creates an issue when someone is mentioned but didn't send message in chat yet - mentioned name is uncolored until that person says something and his username color gets cached...
