### ISSUE TITLE
Part of the title bar can't be dragged

### ISSUE THREAD

**Issue by hesoyam5** [Chatterino/chatterino2#1967]
**Describe the bug**
Part of the title bar can't be dragged, by title bar i mean the top bar that you hold-click and drag around the screen, the one with minimize, maximize and close buttons.
**To reproduce**
I click-hold to the left of 'tt' in Chatterino and i can't drag the chatterino window around, i click to the right of 'tt' in Chatterino and i can drag it around just fine.

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad), 14.09.2020

**Operating system**
Windows 10 Pro, Version 2004, OS Build 19041.508

**Additional information**
Also, can you add the ability to hide the account manager from the title bar? or at least make it possible to drag the window by hold-clicking on the account manager

**Comment by Felanbird** [comment]
Can replicate

Windows 10 | 214afc8fc

**Comment by TranRed** [comment]
Can reproduce with Windows 10 | 7eabba959

Could be default behaviour, because it seems to be roughly the place where the context menu normally is.
Example settings pop-up:
![grafik](https://user-images.githubusercontent.com/16636423/93250839-ac3aa880-f793-11ea-9b4c-e95a15c51e54.png)

**Comment by alazymeme** [comment]
Can reproduce. I agree that it may be the above, but other applications handle this just fine (eg discord, firefox, etc)

**Comment by jose-seabra** [comment]
This is a bigger issue if you have a long username. You have to resize the window to be able to drag it

![chatterinoi](https://user-images.githubusercontent.com/55154249/115960023-0f00d900-a507-11eb-9560-e2b5b52082ed.png)
