### ISSUE TITLE
Show the online status of channels while anonymous

### ISSUE THREAD

**Issue by karlk** [Chatterino/chatterino2#1968]
**What should be added?**

It would be very helpful to be able to see the online status (ex. red dot) of channels while connected as anonymous to chat. A second connection with a logged in twitch account could be used to check the status of channels.

**Why should it be added?**

I have 30+ channel tabs and would like to be able to quickly see which ones are live, but still connect to chat anonymously rather than with a logged in account in all of them.

**Comment by Felanbird** [comment]
Duplicate of #1915 , issue opened in chatterino/api#42

**Comment by apa420** [comment]
Duplicate of #1915
