### ISSUE TITLE
Add "open in streamlink" to tab contextual menu

### ISSUE THREAD

**Issue by jimbo1111** [Chatterino/chatterino2#1974]
**What should be added?**
"Open in streamlink" should be added as a contextual-menu item when clicking tabs, or possibly clicking a tab with a modifier key (alt-click or something) could open the stream in streamlink.

If tab has multiple splits open, then either "open all in streamlink" or disable functionality and only let it be used on single-split tabs.

**Why should it be added?**
To save a click!  Clicking on the tab and then clicking on the top bar of the tab is just a little annoying.

**Comment by TranRed** [comment]
I dislike the idea of adding a very specialized option to tabs, which is also not related to tabs (but channels or only to single channel tabs). Seems a bit over the top just to go from a 3-Click interaction to a 2-Click interaction. The current interaction works really well for me personally, especially in multi-channel tabs. You'd also need to consider, that not everyone is using streamlink.

**Comment by apa420** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.
