### ISSUE TITLE
Message highlights crash the application when choosing a new color 

### ISSUE THREAD

**Issue by Princeloris** [Chatterino/chatterino2#1975]
I noticed that the highlights supported a color change for different words when I tried selecting it, it opened a white box and closed the whole program shortly after. Edit: this is on 2.2.2 on a fresh install on windows. Edit: I seemed to have found the problem controlled folder access was enabled in the windows antivirus once disabled it allowed me to edit it after adding it to the allowed app list i am no longer having an issue.

**Comment by gempir** [comment]
^ Found on 2.2.2 on Windows

Can't reproduce on Chatterino 2.2.2 (commit cbcd5f386) Ubuntu 20.04 / i3

**Comment by leon-richardt** [comment]
Can't reproduce with Chatterino 2.2.2 (commit 913193f8b) on Arch Linux 5.8.9-arch2-1 and sway.

**Comment by alazymeme** [comment]
> I noticed that the highlights supported a color change for different words when I tried selecting it

Can someone explain this? It doesn't make any sense to me ![image](https://user-images.githubusercontent.com/12804673/93708857-fa2d2300-fb7c-11ea-808e-6a09fa8b0c22.png)

**Comment by RAnders00** [comment]
Cannot reproduce, however I don't have a fresh install as described above. Chatterino Nightly 2.2.2 (commit c7a2f4cc9, ); Windows 10

**Comment by zneix** [comment]
Can't reproduce with Chatterino 2.2.2 (commit 6d89465af) Windows 10 1909 18363.1082
However some tips on how to exactly reproduce the issue might've been helpful, maybe I am missing something.

**Comment by alazymeme** [comment]
Also where possible, please use the `Bug Report` issue template. It can assist greatly with trying to reproduce your issue :) 
https://github.com/Chatterino/chatterino2/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md&title=

**Comment by Mm2PL** [comment]
A video of the issue could give us hints on what causes it and how to reproduce the issue. Could you make one? :)

**Comment by Princeloris** [comment]
> Where possible, please use the `Bug Report` issue template; it can assist greatly with trying to reproduce your issue 😄

my bad first time i have ever had an issue

**Comment by fourtf** [comment]
Can't reproduce
