### ISSUE TITLE
Move (or add) the "Show viewer list" from the context menu to the title bar

### ISSUE THREAD

**Issue by KauzDs** [Chatterino/chatterino2#1978]
**What should be added?**
Move (or add a button) the "Show viewer list" from the context menu to the title bar more or less like this [https://i.imgur.com/RZMozlU.png](https://i.imgur.com/RZMozlU.png)

**Why should it be added?**
Makes it easier to see the viewer list

**Comment by zneix** [comment]
Related: #1273 #1590
