### ISSUE TITLE
Suggest viewers when user types @name

### ISSUE THREAD

**Issue by serg06** [Chatterino/chatterino2#1979]
**What should be added?**

When you type @ and start typing, it should suggest you names of people in chat.

Here's an example:

![image](https://user-images.githubusercontent.com/1350889/93916985-5b1d3e00-fcd8-11ea-8958-e17c0a584206.png)

**Why should it be added?**

I think it's a very common and very useful feature. Even as I write this Github issue, it has that feature. Even the emotes system has that feature using `:`.

Feature | Tab-completion | Instant search
------------ | ------------- | -------------
Emotes | ✔️ | ✔️ type `:` and start typing
Usernames | ✔️ | ❌

**Comment by apa420** [comment]
I can't read the code for the emote popup so someone else can do this :)

**Comment by talneoran** [comment]
I can try to work on this.
