### ISSUE TITLE
Autocompletion priority and shortcut 

### ISSUE THREAD

**Issue by Romybron** [Chatterino/chatterino2#1983]
**What should be added?**
Hey!

It would be nice to be able to 

- change to cycle emote list using tab and validating it with space.

- having a priority in :emote and @mentions completion like: 

In-tab channel emotes > other subbed channel emotes > Twitch emotes > (emojis)
and in-tab streamer > moderator > subscriber > non-sub

- or being able to change the priority ourselves.

**Why should it be added?**

Having the ability to interact faster with chat, instead of needing to rewrite a @username that starts with the same bunch of letters as someone else than the streamer/mod/sub or an emote that has a popular subParticle like chann**Hey** or chann**Sub** etc. The cycle emote shortcut would elimitate the need of two hands (the other one for arrows selecting the emote ...)

This actually makes me ryryRage 
![](https://user-images.githubusercontent.com/66818801/94252740-a75cbe00-ff24-11ea-873f-194c236175be.png)

Kappa

**Comment by fourtf** [comment]
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.

**Comment by Romybron** [comment]
If you don't feel like efficiency of writing emotes and usernames isn't useful enough to be part of Chatterino then I guess sure close it ...
