### ISSUE TITLE
Search box weird font issue

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#1991]
**Describe the bug**
When you right click the search box in the search window, the font looks weird - this seems specific to the currently disabled options.

**To reproduce**
1. Ctrl + F in a channel
2. Right click in search box

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/94342509-c2c6e680-0054-11eb-90ca-21053fe3903c.png)

**Chatterino version**
Chatterino Nightly 2.2.2 (commit 20e4d6b3d, 26.09.2020)

**Operating system**
Windows 10

**Comment by fourtf** [comment]
![FeelsDankMan](https://user-images.githubusercontent.com/6320036/94342560-195f0100-0012-11eb-87f9-7d2dcf3b5a41.png)

**Comment by leon-richardt** [comment]
Can reproduce on sway

**Comment by fourtf** [comment]
someone fix this with qss plox

**Comment by fourtf** [comment]
or maybe in the global dark theme thingy

**Comment by alazymeme** [comment]
> qss

> ![image](https://user-images.githubusercontent.com/12804673/94342632-a5dee300-0055-11eb-8e4d-b34ffd1773be.png)
