### ISSUE TITLE
Add more streamer mode options

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2003]
Add an option to:
- Mute pings while obs is open
- Only allow mentions from your own channel in your mentions window

All of these should be enabled by default.

Why?
- Someone can go into another channel and spam ping you as mod/vip (same concept as discord)
- Someone can go into another channel and mention you with racism or other tos shit

**Comment by fourtf** [comment]
> Mute pings while obs is open

sure

> Only allow mentions from your own channel in your mentions window

Filters will remove the needs for this since you can just open the mentions for you own channel.
