### ISSUE TITLE
Add a separate section for streamer mode

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2004]
Add a separated section for streamer mode option - where all options for streamer mode should be individualized.

Why?
Same concept as discord. I may want certain things enabled, but others not.

**Comment by fourtf** [comment]
There isn't even any options for it so the section would be empty. Settings will naturally be filled into categories if applicable.

**Comment by zneix** [comment]
I will just put them in a "subsection" as 4tf suggested in https://github.com/Chatterino/chatterino2/pull/2001#discussion_r495597395
