### ISSUE TITLE
Right click menu for chat messages only appears when right clicking text or emotes, not whitespace

### ISSUE THREAD

**Issue by azizLIGHT** [Chatterino/chatterino2#2005]
**Describe the bug**
When trying to copy a message in chat, right-clicking the whitespace in the line does nothing. In order to get the copy menu, you must right-click the letters in the text of the message or any emotes. This requires precision.

**To reproduce**
Open any active chat, the faster the better.
Right click whitespace, or space between words
Do not see a right click menu with options: `Copy message` and `Copy full message`

**Screenshots**

This is the menu I am expect to get but do not get, when I right click whitespace
![image](https://user-images.githubusercontent.com/8013867/94370088-c8a3e280-00bb-11eb-85f6-289b4fc43798.png)

**Chatterino version**

Chatterino 2.2.2 (commit 53b18d03c)

**Operating system**

Manjaro 20.1 Mikah

**Additional information**

The majority of the pixels in an individual chat line is whitespace (as opposed to text) and is not capable of causing right clicks at all, this narrows the pixels required for right click activation to half or even less. The space character between words doesn't count as right clickable either. It becomes worse if you use small fonts or zoom out or both, or if the channel moves extremely fast, and you don't enable hover mouse to pause the chat, or if the majority of the text messages are single emotes and hard to copy since everyone's nicks are random-length and the emote moves left and right on every line change as its spammed. Just difficult to copy messages unless you're the shroud of chatterino

**Comment by Mm2PL** [comment]
Fixed in #3566
