### ISSUE TITLE
Emote tooltip preview image not initially showing on mouse enter

### ISSUE THREAD

**Issue by jupjohn** [Chatterino/chatterino2#2006]
When the mouse moves ever an emote in a message for the first time (the first pixel into that emote) the tooltip window does not display the emote preview. Instead just the text displays. As soon as the mouse moves again the tooltip will redraw with the preview visible.

**Steps to reproduce:**
 1. Have a chat window open with a message containing an emote.
 2. Move the mouse 1 pixel into the emote's bounding box (causes tooltip show, this is where the preview fails to show)
 4. Move mouse a further 1 pixel into the box (Image draws onto the tooltip and causes a resize)

**Evidence:**
![chatterino_entrypixel_tooltip_bug](https://user-images.githubusercontent.com/4962764/94379765-e2781080-0121-11eb-9835-c88f9ad8e3bc.png)

**Chatterino version**
`Chatterino 2.2.2 (commit 07fc0c3ad)`

**Operating system**
Windows 10 Enterprise Build 18362

Happy to attempt to fix this myself - will link to this issue if I PR it. It also causes a bug when that previews loads that can cause the tooltop to go slightly offscreen if the window is near the edge. Will submit another issue for that soon.

**Comment by Nerixyz** [comment]
I can't reproduce this. The image always gets shown once it's loaded.

**Comment by pajlada** [comment]
We probably accidentally fixed this at some point - feel free to reopen if it happens again
