### ISSUE TITLE
Tooltips don't show in emote picker

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#2008]
**Describe the bug**

When hovering emotes in the emote picker you can't see the names of the emotes unless you have `Link information: enable` enabled. In normal chat you see the names of the emotes independent of the setting set.

**To reproduce**

Disable `Link information: enable`.

**Screenshots**

Can't screenshot properly, sorry :)

**Chatterino version**

Chatterino 2.2.2 (commit 8123a4789)

**Operating system**

Arch Linux Latest

**Additional information**

**Comment by gempir** [comment]
Can reproduce with the `Link information: enable` setting disabled on Ubuntu 20.04 i3

**Comment by Felanbird** [comment]
can replicate on windows
