### ISSUE TITLE
Login data deleted after PC restart

### ISSUE THREAD

**Issue by shifty24** [Chatterino/chatterino2#2009]
**Describe the bug**

Everytime I restart my PC, I have to setup the login again.
**To reproduce**

**Screenshots**

**Chatterino version**

Chatterino 2.2.2 (commit 07fc0c3ad)
**Operating system**

Windows 10
**Additional information**

I have looked into the settings since it probably is because I accidentally clicked some checkmark somewhere, but I didn't find such an option yet. Or maybe it's windows and after restart it wipes some cache or temporary data, which is needed? I don't know and I'm not sure where to find such a setting.

kind regards

**Comment by apa420** [comment]
Your settings file inside of %appdata% is probably set to read-only mode, which makes chatterino unable to write to it.

**Comment by shifty24** [comment]
> Your settings file inside of %appdata% is probably set to read-only mode, which makes chatterino unable to write to it.

yea that would make sense, but if its the one I think you mean, its not set to that or anything else :> it's also empty 

![Untitled](https://user-images.githubusercontent.com/72022015/94479086-8b7f4380-01d4-11eb-83d8-a1159fd126e1.png)

**Comment by apa420** [comment]
I would try deleting the entire %appdata%chatterino2 folder then. (You can back up settings and such first though)

**Comment by shifty24** [comment]
aw its working now, thanks for the help =) good day buddy
