### ISSUE TITLE
Moderation Mode not saying enabled after relaunch

### ISSUE THREAD

**Issue by Caldohhh** [Chatterino/chatterino2#2032]
**Describe the bug**
After enabling moderation mode it does not stay enabled.

**To reproduce**
Simply enable moderation mode for a channel, close your Chatterino, relaunch Chatterino and moderation mode is not enabled.

**Chatterino version**
Chatterino Nightly 2.2.2 (commit 42daac088, 04.10.2020)

**Operating system**
Windows 10

**Comment by zneix** [comment]
Iirc, that's intended but sure, this does sound like a good enhancement.

**Comment by Caldohhh** [comment]
I have checked and settings do update and stay in `%appdata%` . The files in `/Chatterino2/Settings` do in fact update when settings are changed. In the JSON file for window layout moderation mode is set to `True` yet still does not stay enabled after restart. This happened to me on previous release and current.
