### ISSUE TITLE
Very large space showing in usercards

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2033]
Click on a usercard, there is now a very large amount of whitespace.
Windows 10, Chatterino Nightly 2.2.2 (commit 42daac088, 04.10.2020)
Possibly introduced by https://github.com/Chatterino/chatterino2/pull/2023

![image](https://user-images.githubusercontent.com/12804673/95030875-eb567c80-06f5-11eb-9f5f-1118952ee61c.png)

**Comment by zneix** [comment]
It was indeed introduced in the said PR, I tried using only 1 Label object for both Followage and Subage, but setting size hint to it made it very big on Windows, I'll try to fix that later today.
