### ISSUE TITLE
Never finds link info

### ISSUE THREAD

**Issue by HugoSkx** [Chatterino/chatterino2#2034]
Hello,

In Chatterino settings, Link information is enabled but it never ever finds link information. Whatever the link, it doesn't find any info.

I did a fresh install of Chatterino multiple times, nothing changes.
I tried with youtube, twitch and twitter links.

Please tell me anything that comes to your mind to fix things.
Ask me anything you need to know about the settings if you need.
Thanks in advance

Chatterino 2.2.2 (commit 07fc0c3ad)

Windows 10

**Comment by alazymeme** [comment]
Could you please provide a screenshot of what appears when you hover over the link?

**Comment by leon-richardt** [comment]
In addition to what ALazyMeme said, it would also be helpful if you provided the links you tested. 😄

**Comment by HugoSkx** [comment]
I tried with every link I found on a stream I was watching, none of them worked, but I'll put some examples : 
https://www.twitch.tv/sodapoppin/clip/BashfulLightZebra4Head
https://www.youtube.com/watch?v=7KqvkMQVQhc
https://www.youtube.com/watch?v=UEAS1zYvxIk

for each of them when I put my mouse on it it doesn't do anything for a bit, I assumed it was loading the info and after a little bit , maybe less than 30 sec, I get what's on the pic below

![image](https://user-images.githubusercontent.com/38259937/95076751-a3921e00-0712-11eb-8482-0b6149526200.png)

And about the template to follow, I followed it, but I thought screenshots were not useful in this case and I have no way of reproducing it, I install Chatterino and the problem is here, so to reproduce it just put your cursor on the link, which is obviously not the way to reproduce it if I'm the only one with problems. I didn't want to just say put your cursor on the link.

**Comment by MIGI10** [comment]
I have the same issue on macOS Big Sur. "No link info found" always appears, I've tested YouTube (shortened/not shortened) and Discord invite links.

**Comment by leon-richardt** [comment]
It looks to me like the link resolver of the Chatterino API cannot be reached for some reason so the request times out.
If this problem occurs regularly, it would be interesting to see whether you can access the link resolver's server via [this link](https://braize.pajlada.com/chatterino/health/uptime).

If that link works for you, please also post the contents of [this link](https://braize.pajlada.com/chatterino/link_resolver/https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ) in a reply on this issue. Thank you! :smile:

**Comment by HugoSkx** [comment]
@leon-richardt 
"This site can't be reached"
I don't have access to the link, let me restart my router

**Comment by HugoSkx** [comment]
My router was blocking it in some way, I restarted it and it works
That's a problem I have sometimes, my router just stop some things from working like twitch for example but I didn't think about it

Thank you for all your help and sorry for the inconvenience 😅

**Comment by leon-richardt** [comment]
> My router was blocking it in some way, I restarted it and it works
> That's a problem I have sometimes, my router just stop some things from working like twitch for example but I didn't think about it
> 
> Thank you for all your help and sorry for the inconvenience

Great to hear! I would suggest you leave this issue open until he heard back from @MIGI10 as well.

**Comment by MIGI10** [comment]
> > My router was blocking it in some way, I restarted it and it works
> > That's a problem I have sometimes, my router just stop some things from working like twitch for example but I didn't think about it
> > Thank you for all your help and sorry for the inconvenience
> 
> Great to hear! I would suggest you leave this issue open until we hear back from @MIGI10 as well.

Fixed, I had the same issue, router was blocking access. Thank you anyway!
