### ISSUE TITLE
Limit the input field length

### ISSUE THREAD

**Issue by fanway** [Chatterino/chatterino2#2038]
**What should be added?**
Option to limit the input field length

**Why should it be added?**
TMI doesn't allow to send messages longer than 500 characters, so it'll be convenient to have not only characters count, but also an option to limit the input field length.

**Comment by apa420** [comment]
Sometimes I paste a message that's more than 500 chars, I see that and split it up to two messages instead. You wouldn't be able to do this if the max length of the input field was 500 chars. 
Something like highlight characters over the max length of 500 chars would be better imo.

**Comment by fanway** [comment]
If you are talking about copypasting messages, i think it can be cut at 500 mark.

**Comment by apa420** [comment]
I'm not talking about copypasting messages. More about copying info from some website and posting it in chat.

**Comment by fanway** [comment]
I see. My idea was that you could paste info longer, but cut it to 500 characters. Would you think implementing both will be a good idea?

**Comment by apa420** [comment]
The issue is that if you aren't mod/vip/broadcaster/etc... you can't post message that are longer than 250 chars.
It could still work if you remove either 250 or 500 chars after you press enter.
But straight up limiting the text input area is dumb imo.

**Comment by apa420** [comment]
If you change this issue or create a new one with `splitting messages bigger than twitch accepts` (or similar) I'll leave that open.

**Comment by fanway** [comment]
> The issue is that if you aren't mod/vip/broadcaster/etc... you can't post message that are longer than 250 chars.

Oh, i didn't know that. I've tested, without some user-type i was able to get to 270 characters separating words with spaces (216 characters without spaces) and when i tried to send a wall of text without any spaces, i was limited to only 49 characters for some reason.

> But straight up limiting the text input area is dumb imo.

I wouldn't say that it's dumb, considering that you could drop in a larger text and it will be cut at a needed mark, and you wouldn't be able to write more characters, imo it's always better to not allow to do something (if it's restricted), than showing that you are not supposed to do something. But that's fine because implementing that would be a total shitshow because of how inconsistent twitch is.
