### ISSUE TITLE
Previews/popup info appearing behind app when "Always on top" enabled

### ISSUE THREAD

**Issue by MIGI10** [Chatterino/chatterino2#2039]
**Describe the bug**
When the "Always on top" option is enabled, previews for emotes/links appear behind the app 

**To reproduce**
Enable "Always on top" and hover mouse on top of an emote or link (nothing will seem to appear because it's behind the app)

**Screenshots**
<img width="311" alt="Screenshot 2020-10-06 at 13 12 10" src="https://user-images.githubusercontent.com/33965011/95194471-9be77d80-07d5-11eb-9e1d-eccbcc59b1f2.png">

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
macOS Big Sur 11.0

**Comment by apa420** [comment]
Someone else also confirmed that this is a bug. Highly doubt we will fix this though since it's mac only.

**Comment by alazymeme** [comment]
@gempir Could you please test this when you get the chance? :)

**Comment by gempir** [comment]
Yeah confirmed on Chatterino 2.2.2 (commit d56187fda)
![image](https://user-images.githubusercontent.com/9765622/95459934-91afb580-0974-11eb-823f-80a05e18ff74.png)

**Comment by tintinmaster** [comment]
Happens for me too on Linux Mint 20 with Chatteriono 2.2.2 (commit 98762fdfa) when opening usercards, but not on emote hover

**Comment by apa420** [comment]
@tintinmaster That's a completely different issue.

**Comment by alazymeme** [comment]
![animelel4](https://i.alazymeme.com/CondemnedEmbarrassedImage.png)

**Comment by revolter** [comment]
> Highly doubt we will fix this though since it's mac only.

I could try to help with this issue. It'll help me if you'd point me to the code block that handles the tooltip.

**Comment by leon-richardt** [comment]
> I could try to help with this issue. It'll help me if you'd point me to the code block that handles the tooltip.

Potentially interesting is the [`TooltipWidget`](https://github.com/Chatterino/chatterino2/blob/master/src/widgets/TooltipWidget.hpp) class as well as this block of code: https://github.com/Chatterino/chatterino2/blob/a9b1af60de00dc22078ba58adf12bfdfa69a9310/src/widgets/helper/ChannelView.cpp#L1414-L1490
