### ISSUE TITLE
Add placeholder text that says what channel you are sending to

### ISSUE THREAD

**Issue by MrAuro** [Chatterino/chatterino2#2041]
**What should be added?**
Add placeholder text for the message box that says what channel you are sending in.
![image](https://user-images.githubusercontent.com/35087590/95378067-63b56d00-08b1-11eb-8119-04b29a5d4f33.png)

**Why should it be added?**
When switching between multiple chats you can sometimes send a message to the wrong chat

**Comment by leon-richardt** [comment]
The channel name is displayed in the split header so I don't think this is necessary.

**Comment by cinemassacres** [comment]
should close this
