### ISSUE TITLE
extension is not working on the Opera GX browser

### ISSUE THREAD

**Issue by dinoramaner** [Chatterino/chatterino2#2045]
Issues for the extension are tracked here: https://github.com/chatterino/chatterino-browser-ext
whenever i open up a stream all i see in the chat is "chatterino should show up here. Try deselecting and selecting the page. Chatterino also needs to be running.

**Comment by alazymeme** [comment]
As per the issue template, chatterino extension issues are tracked here: https://github.com/chatterino/chatterino-browser-ext

Please re-create your issue on the [browser extension repo](https://github.com/chatterino/chatterino-browser-ext).

**Comment by dinoramaner** [comment]
ok ty
