### ISSUE TITLE
Chocolatey packaging instructions

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#2049]
Would be great if you could detail what the process is maintaining/updating the Chocolatey package
@alazymeme 

maybe in the wiki? decide @alazymeme

**Comment by alazymeme** [comment]
Sure - all my Chatterino stuff will be found here: https://github.com/alazymeme/chocolatey-packages/tree/master/manual/chatterino
So it should be fairly easy to explain.

**Comment by fourtf** [comment]
transfer the repo to chatterino org and make alazymeme a maintainer for it?

**Comment by fourtf** [comment]
I just deleted the wrong comment by accident xd
