### ISSUE TITLE
Link preview always shows "link was not loaded" on hover over previous messages

### ISSUE THREAD

**Issue by fanway** [Chatterino/chatterino2#2054]
**Describe the bug**
Link preview always shows "No link info loaded" on hover over previous messages, when you set `Link information` setting to enabled.

**To reproduce**

1. Start app with `Link information` setting disabled
2. Post message with a link (or recent-messages would do too)
3. Enable setting, and it will always show "No link info loaded" on hover.

**Chatterino version**
Chatterino 2.2.2 (commit 84613187e)

It happens because link information is fetched in `TwitchMessageBuilder.cpp` only once ( on message build :) )
https://github.com/Chatterino/chatterino2/blob/84613187e1bda102ac72a207dfdf9c51ea416f80/src/providers/twitch/TwitchMessageBuilder.cpp#L455
And setting is checked here
https://github.com/Chatterino/chatterino2/blob/8532c6d3bca4e6c3e2da279df1224ebc489c2dc2/src/providers/LinkResolver.cpp#L18-L22
And it never gets updated afterwards. So you need to restart the app to get previous links resolved.

**Comment by alazymeme** [comment]
Can reproduce.
- Windows 10
- Chatterino Nightly 2.2.2 (commit 92040896f, 10.10.2020)
