### ISSUE TITLE
Show Hype Train Information

### ISSUE THREAD

**Issue by Y0dax** [Chatterino/chatterino2#2061]
**What should be added?**
Hype train information including:

- Some sort of status bar indicating one is occurring.
- A timer for the remainder time left to participate.
- The current level and percent completion.
- The current hype train conductors and their status.

**Why should it be added?**
Hype trains are an integral part of many streams and users should know when they are happening. They often lead to bursts of support for streamers.

Info:
https://help.twitch.tv/s/article/hype-train-guide?language=en_US

API:
https://dev.twitch.tv/docs/api/reference#get-hype-train-events

**Comment by leon-richardt** [comment]
Is there a pubsub topic we could subscribe to to catch the start of a hype train? Or would we have to poll the API continuously?

**Comment by Y0dax** [comment]
> Is there a pubsub topic we could subscribe to in order to catch the start of a hype train? Or would we have to poll the API continuously?

There is I believe, though I'm not very familiar with their pub/sub API's: https://dev.twitch.tv/docs/api/webhooks-reference#topic-hype-train-event

Another idea if that does not work would be to query the hype train API after any sub, gift, or bit as those are the triggers, but that is not very efficient.

**Comment by Mm2PL** [comment]
There's no **documented** pubsub topic for this. This needs broadcaster's tokens, making it unfeasible to implement for a chat client which you should be able to use in any chat without the broadcaster giving you explicit permission.
