### ISSUE TITLE
Add an option to avoid creating redundant tabs

### ISSUE THREAD

**Issue by 12932** [Chatterino/chatterino2#2064]
**What should be added?**
An option in the settings to avoid creating redundant tabs

**Why should it be added?**
An option to avoid creating redundant tabs would help me manage my tabs more efficiently, i.e. if I try to open a tab with a channel I already have open, it would instead put that tab into focus. I see this as being helpful because i'm the type of person to have way too many tabs open and sometimes it's a struggle to find them

**Comment by Mm2PL** [comment]
Try the `Ctrl+K` shortcut.

**Comment by 12932** [comment]
> Try the `Ctrl+K` shortcut.

Thanks I did not know about this!
