### ISSUE TITLE
Option to hide subscriptions

### ISSUE THREAD

**Issue by c0ldplasma** [Chatterino/chatterino2#2066]
**What should be added?**
It would be nice to have an option to hide subscriptions, including gift subs.
**Why should it be added?**
Sometimes chat gets cluttered with subsciptions. Especially with up to 100 gift subs at once.

**Comment by Felanbird** [comment]
This will be possible with #1748

**Comment by alazymeme** [comment]
Relevant: https://github.com/Chatterino/chatterino2/issues/2068

**Comment by Mm2PL** [comment]
#1748 
Filter: `!flags.sub_message`
