### ISSUE TITLE
Crash on updating (regex) after commit 0cbddf7

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#2069]
**Describe the bug**

https://github.com/Chatterino/chatterino2/commit/0cbddf7e9bad60da4af73a762f59f3cd05f04724 changed the way regexes are stored in the settings. Thus updating chatterino to this version or later might cause chatterino to stop working when it's trying to run certain regexes.
Old:
`"pattern": "alien([a-zA-Z0-9]{1,10})+",`
New:
`"pattern": "alien[A-z1-9]+",`

**To reproduce**

(I'm not sure which regex broke it, but some regexes should not work properly)
https://pastebin.com/3X6nxViC

**Screenshots**

**Chatterino version**

Chatterino Nightly 2.2.2 (commit 3be62c929, )

**Operating system**

Windows 10

**Additional information**

**Comment by apa420** [comment]
This is really strange, even after removing the old regex things and writing them new again it still crashes sometimes (on startup).

**Comment by pajlada** [comment]
I'm unable to reproduce - if you figure out a proper way to reproduce it feel free to re-open the issue
