### ISSUE TITLE
Automated macOS releases are broken

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#2077]
**Describe the bug**
GitHub Action fails to package/upload the macOS release. Checking the Action log, the `biplist` Python module appears to be missing during the "Package" step, see e.g. [this run](https://github.com/Chatterino/chatterino2/runs/1263123660#step:17:407).

Note that the "Package" step appears to be exiting with `0`, although this is where the `ModuleNotFoundError` occurs.

**To reproduce**
1. Push something to `master`
2. Wait for GH Actions to execute

**Comment by pajlada** [comment]
Looking into this in the `chore/2020-10-17-ci` branch

**Comment by pajlada** [comment]
Fixed in #2079
