### ISSUE TITLE
Notarised builds for macOS 10.14+?

### ISSUE THREAD

**Issue by Shirk** [Chatterino/chatterino2#2085]
**What should be added?**

Chatterino2 Mac builds should - if possible - be code signed and notarised for macOS 10.14+.

**Why should it be added?**

Gatekeeper already refuses to open Chatterino2 on first start via regular double click.
It can still be opened by right-click "Open" from the context menu but Apple mentioned that this support will go away too.
Having a code signed and notarised build would be super helpful for user that are not as tech-savvy or fear opening malware.

**Comment by fourtf** [comment]
I've looked into this and I've not been able to get a certificate. I might look into it again in the future.

However there is no point in tracking this issue here so I'll close this.

**Comment by Shirk** [comment]
If it helps.. I am a registered developer and I'd be happy to help out in the meantime to get notarised release builds at least.
