### ISSUE TITLE
When channel name of a mention is clicked, two broken webpages open

### ISSUE THREAD

**Issue by Y0dax** [Chatterino/chatterino2#2087]
**Describe the bug**
Double clicking on the channel name to the left of a message in the /mentions channel opens two web pages. One is just the name of the channel and the other appears to be a guid. Neither are real sites.

**To reproduce**
Double click the channel name to the left of a mention message

**Screenshots**
![image](https://user-images.githubusercontent.com/5025171/96389750-31dcba00-117f-11eb-8f0d-c57fc54139d4.png)

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)
Chatterino Nightly 2.2.2 (commit 48a3506d7, 17.10.2020)

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
Cannot reproduce | Chatterino Nightly 2.2.3-beta (commit ec9486948, 24.10.2020) | Windows 10
**BUT** if I do Right Click > Open link incognito, I can reproduce
