### ISSUE TITLE
Immediate crash when attempting to remove highlighted phrase or user

### ISSUE THREAD

**Issue by MohnJadden7** [Chatterino/chatterino2#2092]
**Describe the bug**
Chatterino crashes immediately when attempting to remove a highlighted phrase pattern or user. Tested various different phrases and users with the same result.

**To reproduce**
Settings>Highlights>Messages/Users tabs>Click phrase pattern/user>Click "Remove" ⟶ Chatterino crashes.

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10 Pro

**Additional information**
N/A

**Comment by apa420** [comment]
Duplicate of #2055
