### ISSUE TITLE
Thumbnails for stream inside of the splitheader tooltip shows a different stream

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#2093]
**Describe the bug**

Thumbnails for stream inside of the splitheader tooltip shows a different stream then the one you are watching
**To reproduce**

open a stream hover over the splitheader tooltip then go to another stream and hover over the splitheader tooltip 
**Screenshots**

![,](https://user-images.githubusercontent.com/16343162/96520821-25af3600-122d-11eb-9120-b3074e467942.gif)

**Chatterino version**

Chatterino 2.2.2 (commit 07fc0c3ad)
**Operating system**

windows 10
**Additional information**

**Comment by Y0dax** [comment]
This might be fixed already in the nightly build with https://github.com/Chatterino/chatterino2/pull/2080
