### ISSUE TITLE
Add an option to disable "Streamer Mode"

### ISSUE THREAD

**Issue by 12932** [Chatterino/chatterino2#2098]
**What should be added?**
Add an option to disable "streamer mode"

**Why should it be added?**
Clicking a user's avatar while having OBS open will display "Streamer Mode" instead of the user's avatar. However I do not wish for this functionality, and was surprised there's no option to disable this.

**Comment by SLCH** [comment]
There is already an option for this in settings
<details>
![Screenshot_20201020_170305](https://user-images.githubusercontent.com/2884941/96589803-527b5000-12f6-11eb-93a1-8568e831bebb.png)

</details>

**Comment by sando** [comment]
Dupe of #1997, already fixed in 2232c6d925d217d40bd077433566979131ab13e5

Try the latest nightly, or wait for 2.2.3
