### ISSUE TITLE
Nightly built releases and notification

### ISSUE THREAD

**Issue by bbigras** [Chatterino/chatterino2#2099]
When using the github "watch releases" feature we receive an email every day because of the nightly build.

Could something be done to prevent those notifications?

**Comment by TranRed** [comment]
you can change your watch settings for this repository, see: https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository

you can also unsubscribe from all watch e-mails in your personal settings:
![notification settings](https://user-images.githubusercontent.com/16636423/96628273-4c936800-1312-11eb-8e68-af9d5ed3483d.png)

**Comment by bbigras** [comment]
I think we misunderstood each other.

I'm currently using "releases only".
![image](https://user-images.githubusercontent.com/24027/96628710-1fd75480-1302-11eb-90e7-c954612d4da0.png)

I need those to update a Linux distro package asap when there's a new release.

But I also receive emails about the nightly build:

![image](https://user-images.githubusercontent.com/24027/96628891-5dd47880-1302-11eb-899c-c291b4840e89.png)

I would like to avoid those.

I might have read that some project build nightly and push the artifacts but without tagging it as a release. One something like that.

**Comment by TranRed** [comment]
Is the release name mentioned in the e-mail? If so the eaiest solution/workaround for now should be to a rule in your e-mail client based on it.

**Comment by bbigras** [comment]
Fair enough.

**Comment by TranRed** [comment]
I just had another idea: maybe you could automate your process, querying the json chatterino uses to detect updates from time to time. Sounds like you are updating it manually right now :) idk if @fourtf is fine with this. I would assume so. Can't hurt to ask.
