### ISSUE TITLE
Tables not rendering properly in Wiki

### ISSUE THREAD

**Issue by NotNotQuinn** [Chatterino/chatterino2#2102]
**Describe the bug**
The tables on the chatterino wiki are not rendering properly.

**To reproduce**
Visit the wiki, in the [filters section](https://wiki.chatterino.com/Filters/#values), and 

**Screenshots**
![Image](https://cdn.discordapp.com/attachments/459650160658481152/768247852479545344/unknown.png "Tables on the chatterino wiki not rendering properly.")

**Chatterino version**
N/A

**Operating system**
Windows 10

**Additional information**
I am trying out Chrome force dark, thus the site may look different then you see it. `chrome://flags/#enable-force-dark`

**Comment by cinemassacres** [comment]
looks good here https://github.com/Chatterino/wiki/blob/master/docs/Filters.md

**Comment by TranRed** [comment]
should be an issue over here: https://github.com/Chatterino/wiki/issues 
If you know basic markdown I'd suggest to PR the change directly yourself :)

**Comment by fourtf** [comment]
Closing since it's related to the chatterino wiki and not chatterino
