### ISSUE TITLE
Something i noticed with unrecognized characters 

### ISSUE THREAD

**Issue by benjiPKS** [Chatterino/chatterino2#2104]
So with whats happening in chats now theres a spam where we do this https://gyazo.com/f4cab53a88c8b8424403f7a9fb678e3a and it seems to be with that you cant go past 50 on chatterino only. it works in native chat but not chatterino. is that so we dont clutter the normal chat or is it a bug? sorry this is the first time ive ever done something like this so itll be shit 

benjiPKS

**Comment by benjiPKS** [comment]
it looks like this in chatterino. sorry i completely forgot https://gyazo.com/cb458082f539a9381be3644987f7b47a

**Comment by leon-richardt** [comment]
This happens because we handle certain Unicode characters different than web chat. It is probably reasonable to call this a bug so thank you for reporting!

**Comment by Mm2PL** [comment]
Webchat works differently than Chatterino, webchat will not wait for any confirmation of the message going through or being seen by others. Chatterino uses two connections to see if the message got sent or silently dropped.

**Comment by Mm2PL** [comment]
Closing in favor of #2771
