### ISSUE TITLE
Chatterino crashes when clicking on 'Move up' or 'Move down' on the Accounts section in settings

### ISSUE THREAD

**Issue by SiddarthPatelLOL** [Chatterino/chatterino2#2106]
**Describe the bug**

- Experienced an unexpected crash when clicking upon 'Move up' or 'Move down' button press in alteration.

- It also occurs after a few initial clicks (either 'Move up' or 'Move down') and then randomly selecting an account and continue clicking the same button initially toggled. 

**To reproduce**

Go to the Accounts section in the settings

- **In alteration**
1. Select an account.
2. Press 'Move down' and then 'Move up'.
3. Crashes on the next alteration when you press 'Move down' again.
4. Occurs even on vice-versa.

- **Also occurs without any alteration**
1. Select an account and give a few initial clicks on either the 'Move up' or 'Move down' button.
2. Randomly select any other account and continue pressing the same button initially chosen, client crashes right after.

**Chatterino version**

Chatterino 2.2.3-beta (commit 3c6e6446c)

**Operating system**

Windows 10

**Additional information**

![f8puBbQsl0](https://user-images.githubusercontent.com/54808675/96718609-e36d2c80-13c5-11eb-91df-c765d7ecdd7b.gif)

**Haven't confirmed if this is an issue for anybody else.**

**Comment by zneix** [comment]
Can reproduce on Arch Linux 5.9.1, Chatterino 2.2.3-beta 406e00df4

**Comment by fourtf** [comment]
@zneix fellow fish user 
![2](https://user-images.githubusercontent.com/6320036/96908714-4ed5fd80-149d-11eb-8e37-678658be8b04.png)
