### ISSUE TITLE
Strikeout and underline options don't work

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2111]
**Describe the bug**
Both the strikeout and underline options dont work

**To reproduce**
1. Go into the font options
2. Turn on font underline/strikeout
3. Notice it doesn't work

**Screenshots**
![lol, shit's fucked](https://i.alazymeme.com/RealVariousImage.gif)

**Chatterino version**
Chatterino Nightly 2.2.3-beta (commit 5f54b1b49, 23.10.2020)

**Operating system**
Windows 10

**Additional information**
I don't see a good reason for these to be fixed, what are people's thoughts on just removing them as opposed to fixing it? Seems out of scope for Chatterino.

**Comment by leon-richardt** [comment]
Most likely a side effect of using Qt's font picker. I don't think strikeout and underline have a use case anyway so https://github.com/Chatterino/chatterino2/issues/2114#issuecomment-715653019 probably also applies here.

**Comment by alazymeme** [comment]
> Most likely a side effect of using Qt's font picker. I don't think strikeout and underline have a use case anyway so [#2114 (comment)](https://github.com/Chatterino/chatterino2/issues/2114#issuecomment-715653019) probably also applies here.

Not really. This issue refers to a feature that is broken - the solution of which is (in my opinion) to remove it. #2114 refers to a feature that works perfectly fine, but can be improved.

**Comment by leon-richardt** [comment]
I was particularly referring to this part of https://github.com/Chatterino/chatterino2/issues/2114#issuecomment-715653019:
> 4. Realistically, what does it take to fix this? It requires a full reimplementation of the font dialog. [...] Adding an external dependency is not worth it compared to the payoff in any capacity. It is simply out of scope to "fix" this. [...]

**Comment by pajlada** [comment]
There's no easy way to hide those options, and we're not looking to render those right now so I'm closing this as a wont-fix.
