### ISSUE TITLE
Font options aren't saved

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2112]
**Describe the bug**
When trying to re-adjust your font, any custom option that may be set reverts back to another font choice

**To reproduce**
1. Choose custom font
2. Click ok and ok again
3. Go back into the custom font settings
4. Notice that it's changed

**Screenshots**
![lol fonts broken](https://i.alazymeme.com/CoastalRoughImage.gif)

**Chatterino version**
Chatterino Nightly 2.2.3-beta (commit 5f54b1b49, 23.10.2020)

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
Also broken for @SLCH 
![xd](https://user-images.githubusercontent.com/12804673/96981457-fa955100-1562-11eb-93c9-c3b8dcb8553a.png)
