### ISSUE TITLE
Option to disable tab closing button

### ISSUE THREAD

**Issue by SLCH** [Chatterino/chatterino2#2116]
**What should be added?**
Option to disable/remove/hide tab closing "x" button.

![Screenshot_20201023_132057](https://user-images.githubusercontent.com/2884941/96987355-f3a31a00-1533-11eb-8a0a-e02ee403a27e.png)

**Why should it be added?**
Having a lot of tabs, renamed them to short names that consist of 2-5 symbols.
Upon navigating between tabs using a mouse misclick on closing button a lot (~10% of hits)

**Comment by alazymeme** [comment]
You mean this option? 🤔 
![xd](https://i.alazymeme.com/RivalNosyImage.png)

**Comment by sando** [comment]
![image](https://user-images.githubusercontent.com/58441/96987729-1c94d080-156f-11eb-8e87-a1a1dfeecb1d.png)

:)

**Comment by SLCH** [comment]
Yes FeelsDankMan
But now all my rows of tabs are wrong cause of different padding forsenY . But it's ok i guess.
Thanks :+1: @alazymeme @sando
