### ISSUE TITLE
Font is not consistent with the usercard

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2118]
**Describe the bug**
The font used in the usercard is not consistent with the font selected in chatterino

**To reproduce**
1. Select a font
2. Open a usercard

**Screenshots**
![xd](https://i.alazymeme.com/CharmingNormalImage.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta (commit 11525e626, 23.10.2020)

**Operating system**
Windows 10

**Comment by fourtf** [comment]
The font is only supposed to be for the chat and not the rest of the ui.
