### ISSUE TITLE
Update prompt displays outside the current safe zone

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2123]
**Describe the bug**
Can't click the install button when chatterino is full screen

**To reproduce**
1. Fullscreen chatterino
2. Click install button
3. Notice that it appears off the current monitor

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/125618679-8399d516-e1a0-4ef2-94ad-b97bc2a3d795.png)

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10

**Comment by Mr0ll3** [comment]
Can reproduce | Chatterino 2.2.2 (commit 07fc0c3) | Windows 10

With multiple monitors it appears on the next display to the right. If Chatterino is on furthest right display, the prompt is show up as it does with 1 display.

Tested with 1 display, screenshot below.

![chatterino_2020-10-25_16-19-51](https://user-images.githubusercontent.com/11009616/97109817-afe81600-16d5-11eb-9b24-a1758f3150e3.png)
