### ISSUE TITLE
Leaving patterns blank in Ignores can crash Chatterino

### ISSUE THREAD

**Issue by ReactionAndy** [Chatterino/chatterino2#2125]
**Describe the bug**
The problem is that when i make a new ignore pattern and set the pattern to nothing then enable Regex it freezes the window as if it's stuck in a while loop forever.

**To reproduce**
Chatterino->Settings->Ignores->
Add->Pattern[EMPTY]-> Regex[X]

**Screenshots**
https://imgur.com/a/XDEuRdH

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
Can reproduce | Chatterino Nightly 2.2.3-beta (commit 3ee08b9ff, 25.10.2020) | Windows 10

**Comment by Mr0ll3** [comment]
Can reproduce | Chatterino 2.2.2 (commit 07fc0c3) | Windows 10
