### ISSUE TITLE
Windows nightlies are built in debug while macOS and Linux builds in release

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#2140]
**Describe the bug**
The GitHub Action workflow builds Windows builds in `debug` mode while  macOS and Linux build in `release`. This can lead to different behavior and inconsistencies.

**To reproduce**
1. Push something to master
2. Wait for GH Actions to build
3. Check the build logs/artifact produced

**Example**
GH Actions builds for 05469d1:
- [Windows run](https://github.com/Chatterino/chatterino2/runs/1309853774#step:9:82) on line 82 (**debug**)
- [Linux run](https://github.com/Chatterino/chatterino2/runs/1309853796#step:12:16) on line 16 (**release**)
- [macOS run](https://github.com/Chatterino/chatterino2/runs/1309853823#step:16:16) on line 16 (**release**)

**Additional information**
"Suspicious" part in the build setup I could think of are these lines:
https://github.com/Chatterino/chatterino2/blob/05469d1bbadbef9269705057830680745bf64c1d/chatterino.pro#L87-L96
(Since Conan is only used on Windows and it's kind of opaque what that macro/include does.)

**Comment by pajlada** [comment]
Yeah this is related to conan somehow - fun!

**Comment by AnotherFoxGuy** [comment]
Is this still an issue? If it still is then I will take a look at this

**Comment by leon-richardt** [comment]
AFAICT, the CI build logs show no mention of a debug build being built anymore. Might still be nice to get a Windows user to confirm this with an up-to-date nightly build though

**Comment by Felanbird** [comment]
Chatterino Nightly 2.4.0 (commit [b7888749](https://github.com/Chatterino/chatterino2/commit/b7888749) modified) built on 2022-12-04 with Qt 5.15.2, Windows SDK, MSVC 193431933
Running on Windows 10 Version 2009, kernel: 10.0.19045

vs

Chatterino 2.4.0 DEBUG (commit [e2213df1](https://github.com/Chatterino/chatterino2/commit/e2213df1) modified) built with Qt 5.15.2, Windows SDK, MSVC 192930038
Running on Windows 10 Version 2009, kernel: 10.0.19045

So I believe we are 🆒
