### ISSUE TITLE
Issue with setting for finding usernames without @ prefix

### ISSUE THREAD

**Issue by CycloneYT** [Chatterino/chatterino2#2144]
The setting "Try to find usernames without @ prefix" is unchecked for me. Yet when i try @ ing someone without the @ it still works.

1. Check if the setting "Try to find usernames without @ prefix" is unchecked
2. Try typing someones names halfway then use the tab key to auto complete their name

https://i.imgur.com/kfFOXhq.png

Chatterino 2.2.2 (commit 07fc0c3ad)

Windows 10

**Comment by zneix** [comment]
The setting you mentioned is meant to enable / disable autocompletion for usernames without using `@` symbol - by just typing their username in chat (e. g. `zn + Tab` would resolve to `zneix`) and it's working as intended for me.
To answer your problem, I don't think there's a setting for disabling username autocompletion with `@` character.

**Comment by CycloneYT** [comment]
> 
> 
> The setting you mentioned is meant to enable / disable autocompletion for usernames without using `@` symbol - by just typing their username in chat (e. g. `zn + Tab` would resolve to `zneix`) and it's working as intended for me.
> To answer your problem, I don't think there's a setting for disabling username autocompletion with `@` character.

So there's no point in that setting why is it on there?

**Comment by daiexd** [comment]
just check 'Only search for username autocompletion with an @' 4HEad

**Comment by zneix** [comment]
Oh yeah, I misunderstood your request at first - thoguht you wanted to disable username autocompletion with `@` - sorry for confusion. And yes, just do what daniexd suggested.

**Comment by CycloneYT** [comment]
> 
> 
> Oh yeah, I misunderstood your request at first - thoguht you wanted to disable username autocompletion with `@` - sorry for confusion. And yes, just do what daniexd suggested.

My question is why is "Try to find usernames without @ prefix" a setting if it doesn't do any. OMEGALUL

**Comment by Mm2PL** [comment]
That setting toggles whether or not the client should search for usernames without @ in text, if you have bolded usernames enabled, you'll see it.
Setting on: ![2020-10-31_19-24](https://user-images.githubusercontent.com/25011746/97786866-52a50680-1ba6-11eb-92bf-c9f51f6c4e13.png)

Setting off: ![2020-10-31_19-24_1](https://user-images.githubusercontent.com/25011746/97786865-520c7000-1ba6-11eb-81a5-f042cbd2cd3c.png)

**Comment by CycloneYT** [comment]
> 
> 
> That setting toggles whether or not the client should search for usernames without @ in text, if you have bolded usernames enabled, you'll see it.
> Setting on: ![2020-10-31_19-24](https://user-images.githubusercontent.com/25011746/97786866-52a50680-1ba6-11eb-92bf-c9f51f6c4e13.png)
> 
> Setting off: ![2020-10-31_19-24_1](https://user-images.githubusercontent.com/25011746/97786865-520c7000-1ba6-11eb-81a5-f042cbd2cd3c.png)

Looks like it still works on or off. I'm not sure what the point of it is?

**Comment by daiexd** [comment]
> Looks like it still works on or off. I'm not sure what the point of it is?

I don't think you are understanding the setting, this has nothing to do with tabbing names. All it does is tell the system whether or not this message should be searched against the system to see if it is a user. if you tick this setting, and the system notices a message without an @ is a user, the name can be right clicked to form a message at this user, or you can left click it to pull up the user card. if this option is unticked, the message would just show up as an ordinary chat message. sorry if this is kinda dank to understand

**Comment by CycloneYT** [comment]
> 
> 
> > Looks like it still works on or off. I'm not sure what the point of it is?
> 
> I don't think you are understanding the setting, this has nothing to do with tabbing names. All it does is tell the system whether or not this message should be searched against the system to see if it is a user. if you tick this setting, and the system notices a message without an @ is a user, the name can be right clicked to form a message at this user, or you can left click it to pull up the user card. if this option is unticked, the message would just show up as an ordinary chat message. sorry if this is kinda dank to understand

Yes I'm in pajlada chat they told me what it does thanks though
