### ISSUE TITLE
Description when you hover over a setting

### ISSUE THREAD

**Issue by CycIoneTM** [Chatterino/chatterino2#2146]
**What should be added?**
A feature that adds a description when you hover over a setting. This would look something like when you hover over a link in chat. I understand that most settings are self explanatory but for the ones that aren't it's really troubling to figure out what they do. Without reading through the source code someone may be missing out and a great feature that they didn't even know existed. I personally struggled to know what some of the settings do. I had to ask the chat for help. 

**Why should it be added?**
This feature would allow for the user to understand what each setting does. For the users that come from using something like bttv they want something where they can easily add all they're settings back without the trouble of figuring out what each setting does. So this could end up with them not like the experience of Chatterino and never using it again. In my option this feature is just a necessary quality of life aspect that should to be added.

**Comment by CycloneYT** [comment]
I have made a list of Settings that I think need Descriptions. As well as made a rough description of them: https://pastebin.com/yhuLN0yF Remember these are always up for change and in no way are finished. This is only a step in the right direction in making this feature a reality.

**Comment by acdvs** [comment]
The language in the tooltips should be "active" to provide the most clarity for the setting. Also, complete sentences.

- Always on top: "Always keep Chatterino as the top window."
- Start with Windows: "Start Chatterino when your computer starts."

etc.
