### ISSUE TITLE
Anonymous user gets pinged by justinfan64537

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#2156]
**Describe the bug**
We anonymously log in using the username `justinfan64537`. However this allows users to ping all anonymous Chatterino users by typing that name.

It's declared here:
https://github.com/Chatterino/chatterino2/blob/e4af009fda9f277d6eacaa3d29b6f5a557409359/src/providers/twitch/TwitchCommon.hpp#L8

**Comment by Mr0ll3** [comment]
![image](https://user-images.githubusercontent.com/11009616/98169068-e13dbe80-1eeb-11eb-837e-b9f8860d7de1.png)

Solution for now.

**Comment by Y0dax** [comment]
Would it be possible to generate a random number postfix on app load rather than static 64537? At least that way users will be pseudo-unique

**Comment by pajlada** [comment]
> Would it be possible to generate a random number postfix on app load rather than static 64537? At least that way users will be pseudo-unique

There is an easier solution so we don't have to go this route
