### ISSUE TITLE
Automatically reload emotes when changing a tab, button to reload all emotes in all tabs

### ISSUE THREAD

**Issue by Kraftium** [Chatterino/chatterino2#2159]
**What should be added?**
1 Automatically reload ffz, bttv, and sub emotes when you switch to a different, pre-existing tab

2 Add a button (and keybind) to reload all emotes in all tabs

**Why should it be added?**
1 It makes it easier to see current emotes without having to reload emotes manually

2 Sometimes emotes fail to load in many tabs on Chatterino startup, so adding this would be useful without having to restart Chatterino completely, also it would be an easy way to reload all the emotes for channels without having to do it individually, one by one.

**Comment by alazymeme** [comment]
> Automatically reload ffz, bttv, and sub emotes when you switch to a different, pre-existing tab

I don't agree with this, it will probably result in spamming the ffz and bttv apis.

> 2 Add a button (and keybind) to reload all emotes in all tabs

I like this, but due to the way splits work, I think it'd be better if this was per tab, not all tabs

> Sometimes emotes fail to load in many tabs on Chatterino startup

This is most likely the result of ffz/bttv api

**Comment by daiexd** [comment]
I've thought about this aswell, but I think if an addition was implemented that refreshed many tabs at once this may result in emotes not reloading as you mentioned, like on startup. the best option now is to just restart Chatterino until the emotes properly reload in every channel.

**Comment by Kraftium** [comment]
> it will probably result in spamming the ffz and bttv apis.

Yeah I was thinking about that. Maybe it is possible to only reload emotes after you’ve been in a tab for a certain amount of seconds/time, like 5 seconds

**Comment by zneix** [comment]
> >Sometimes emotes fail to load in many tabs on Chatterino startup
>
> This is most likely the result of ffz/bttv api

About that, it's worth noting that sometimes global emotes for 3rd party don't load and when such issue occurs, there's no other way to (re)load emotes than just restarting chatterino which is quite annoying.

**Comment by zneix** [comment]
Given the reasoning in the issue body I'll close this in favour of #2924 and try implementing an option to easily reload Global 3rd-party emotes without having to restart the whole application.
