### ISSUE TITLE
Chatterino doesn't work with Alternate Player for Twitch.tv

### ISSUE THREAD

**Issue by dozzzz02** [Chatterino/chatterino2#2161]
Title basically. The chat doesn't latch onto the window. I suspect its because it only does that on twitch.tv and not necessarily any chat visible on any website.

**Comment by alazymeme** [comment]
Please close this issue and repost your issue here: https://github.com/Chatterino/chatterino-browser-ext

**Comment by cinemassacres** [comment]
https://github.com/Chatterino/chatterino-browser-ext/issues/46

**Comment by zneix** [comment]
@cinemassacres can you reproduce the issue and/or can provide some additional information about it that could help the issue? If no, then please don't open issues for someone else without any information and context about what's happening.

**Comment by dozzzz02** [comment]
> @cinemassacres can you reproduce the issue and/or can provide some additional information about it that could help solving ir? If no, then please don't open issues for someone else without any information nor context about what's happening and close the open you've opened.

In this case its the same thing. It just doesn't work.
