### ISSUE TITLE
adding support for youtube channels would be cool

### ISSUE THREAD

**Issue by petterio** [Chatterino/chatterino2#2162]
don't know if it is easy to implement a channel going live on youtube. 
but having the option to join a live channels chat would be cool. with bttv and ffz emote support ofc :--)

**Comment by alazymeme** [comment]
I don't agree, I think this is out of scope for chatterino.

**Comment by apa420** [comment]
How would bttv and ffz emote support make sense for youtube?

**Comment by cinemassacres** [comment]
duplicate of #357

**Comment by fourtf** [comment]
Youtube support is unfortunately very hard to do so I would say this is out of scope.

**Comment by itzklyde** [comment]
> How would bttv and ffz emote support make sense for youtube?

Looks like they work great on YouTube now eh

**Comment by Felanbird** [comment]
Locking this to prevent random spam bumping, the current conversation about youtube support has most recently been discussed in #3298
