### ISSUE TITLE
Searching in misc channels gives weird window names

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2166]
**Describe the bug**

The title of the search window for whispers is `Searching in /whisperss history`, which looks bad and doesn't make much sense. I would expect the window title to be `Searching in whispers history`.

**To reproduce**

  1. Have a `/whispers` (or `/mentions` or an empty `/watching`) split open
  2. Open search window, observe popup title

**Screenshots**

![2020-11-07_23-52](https://user-images.githubusercontent.com/25011746/98452956-f153d900-214b-11eb-8fc8-0ff7b335756e.png)

**Chatterino version**

c3ff98d

**Operating system**

20.04.1 LTS (Focal Fossa)

**Additional information**
For an empty `/watching` split the title doesn't have a channel name at all.

**Comment by alazymeme** [comment]
Can reproduce, Windows 10 Chatterino Nightly 2.2.3-beta (commit c3ff98da8, 07.11.2020)
