### ISSUE TITLE
User card issue

### ISSUE THREAD

**Issue by CycIoneTM** [Chatterino/chatterino2#2170]
User cards only dragging on certain areas.

1) Open someones user card
2) Try to drag the user card anywhere but outside the red box i show in the screenshot

https://i.imgur.com/ZcVQapX.jpeg

Chatterino Nightly 2.2.3-beta (commit 0eed45ae6, )

Windows 10

I'm not sure if this is how its supposed to be or if its a bug.

**Comment by alazymeme** [comment]
Cannot reproduce, Windows 10 Chatterino Nightly 2.2.3-beta (commit 0eed45ae6, 08.11.2020)

Are you using Windows scaling? Do you have a high DPI monitor?

**Comment by CycloneYT** [comment]
> Are you using Windows scaling? Do you have a high DPI monitor?
I use a TV as my monitor.

**Comment by alefbeo** [comment]
Also an issue for me, Windows 10, same commit as well as any later releases 
On a 1920x1080 monitor with standard settings

**Comment by Mm2PL** [comment]
> Back in 2.2.2, it was possible to use any portion of the top of the user card for dragging the box around.
> At some point, this was unfortunately broken.

> ![https://user-images.githubusercontent.com/41973452/117794190-00ab0080-b21b-11eb-989e-e249cd810fd7.png](https://user-images.githubusercontent.com/41973452/117794190-00ab0080-b21b-11eb-989e-e249cd810fd7.png)
> OS and Chatterino Version
> Windows 10
> d59bb80 current | only had f191de2 to test it's original existance

Felanbird in #2768.

**Comment by Void48** [comment]
Same issue as me. Almost impossible to drag the usercard because you have to click on 1 pixel to be able to move it around ![3x (1)](https://user-images.githubusercontent.com/85196642/132109176-2e7cb988-cc75-4cc3-9130-666f974acf90.png)
