### ISSUE TITLE
Split with only highlighted messages

### ISSUE THREAD

**Issue by eschultze** [Chatterino/chatterino2#2175]
**What should be added?**
Split section with only highlighted messages

**Why should it be added?**
I'm monitoring common words that are highlighted very often. I've already customized the highlight color inside the chat, but the highlight color at the tab section is confusing (I'm colorblind) and can't be changed. I have trouble checking which chats rooms have a new highlight match.

**Comment by Mm2PL** [comment]
![2020-11-11_22-05](https://user-images.githubusercontent.com/25011746/98864348-a4c91000-2461-11eb-936f-4db6d8de8602.png)
Is a /mentions tab what you are after? As it shows all highlighted messages from all channels.

**Comment by eschultze** [comment]
Sorry that I wasn't clear. I mean a place with all highlighted messages using keywords and regex from the Highlight >> Messages menu.

Filters seem to do what I'm looking for, but I can't find them on the settings page.
![image](https://user-images.githubusercontent.com/12034548/98952672-7cc9c300-24da-11eb-9c4f-0b53b5c6d876.png)

I'm using osx version.

**Comment by leon-richardt** [comment]
What version of Chatterino are you using? (See the page "About" in the settings.)

Filters are not part of a stable release yet and are only available in the 2.2.3-beta or nightly builds.

**Comment by eschultze** [comment]
Thanks @leon-richardt I've updated here. Is there a way to filter regex values?

**Comment by leon-richardt** [comment]
I'm afraid there is not. Feel free to make a feature request for this if it's something you'd like to see.

In the meanwhile, there is not much I can suggest unless maybe trying to convert your regex into the [grammar supported by filters](https://wiki.chatterino.com/Filters/#operators). (Although I realize that might not be feasible depending on your use case.)

Another "new" feature that might of interest is the ability to exclude certain highlight phrases from the mention tab, introduced in #2036.

**Comment by Felanbird** [comment]
As mentioned by mm2pl originally, the `/mentions` tab does this. 

Also as mentioned [filters](https://wiki.chatterino.com/Filters/) can be used to specifically have a tab that only show's the highlighted messages `flags.highlighted`

I personally have a split that only shows first-messages.
![image](https://github.com/Chatterino/chatterino2/assets/41973452/257d524d-204c-4e72-a7bd-15c20d3a3237)
