### ISSUE TITLE
clicking "Ignore highlights" does nothing, only for 1 user. Stuck with their highlights being ignored.

### ISSUE THREAD

**Issue by ghost** [Chatterino/chatterino2#2178]
**Describe the bug**
This is only happening with schnozebot for some reason. Clicking ignore highlights does nothing, and I'm stuck as having their highlights ignored, even though it's not checked.

**To reproduce**
No idea. Been an issue for months and haven't been able to fix it or identify a cause.

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
> Opened issue
> Deletes account

Good one

**Comment by Felanbird** [comment]
If the button doesn't work you could always remove schnozebot manually from settings.json
