### ISSUE TITLE
Fixed Line Height option

### ISSUE THREAD

**Issue by miltrath** [Chatterino/chatterino2#2181]
**What should be added?**

An option that allows the user to specify a maximum height for chat lines, to include behavior that adds any configured spacing into wrapped lines. 

**Why should it be added?**

It would look a fair bit cleaner in split screen configuration, to a lesser extent in an unsplit configuration.   Currently,  lines that feature default scale emotes are taller than lines that do not, and lines that are wrapped due to message length are shorter than 2 lines of separate messages.

**Comment by pajlada** [comment]
I'm having a hard time following your feature request - could you please include mockups of how this would look like?

**Comment by apa420** [comment]
Is this setting not sufficient?
![](https://i.nuuls.com/Lxgvo.png)

**Comment by miltrath** [comment]
@pajlada 

I am no good with graphical programs, but the goal is to create a regular, grid-like appearance when using a split configuration.  A way to make all lines of the same height, and to make multi-line messages an integer-scaled height based on height of a single line.

@apa420 

As I read it that is simply to keep a long message from taking up too many lines of chat, and isn't related to the features I am describing.  

Some emotes are taller (SourPls for instance) than usual and I would like a way to prevent them from messing up the uniformity of the line height.

**Comment by pajlada** [comment]
As it stands, this is not functionality I think we'd want to add to Chatterino.
