### ISSUE TITLE
--channels and/or -c args not working

### ISSUE THREAD

**Issue by Sukid** [Chatterino/chatterino2#2190]
**Describe the bug**
The command line arguments for launching certain channels aren't working. I've tried every variant I can think of, including
`chatterino -c t:joviandragon`
`chatterino --channels joviandragon`
`chatterino --channels t:joviandragon`

I've also tried changing capitalization, using quotation marks, removing spaces, adding colons... as much as I could think of. the most I got was getting an error message if I tried something like -Ctheemster, although it just says those are unhandled options. Otherwise, I never even get an error message. The application just completely ignores the arguments.

**To reproduce**
Just try to use the --channels command line switch with any given twitch channel. The window will either come up empty or with the channels you were already in and that's it.

**Chatterino version**
Chatterino 2.2.3-beta (commit 7d2b64087)
I've also tried it in the stable 2.2.2 release as well.

**Operating system**
Both Arch Linux and Windows 10

**Additional information**
--version and --help aren't working in Windows 10, but they are working in Linux. --help-all doesn't work in either. --version and --help on Windows just seem to print out nothing, whereas with --help-all the application just launches as though there were no arguments just like with -c.

**Comment by pajlada** [comment]
Confirmed this is a bug - it was lost in some merge conflict. I think @zneix will be looking into this.

Thanks for the report

**Comment by zneix** [comment]
@pajlada correct, sorry for slacking on this one but some code responsible for this function got lost in a merge conflict. I looked into this and I am in the process of restoring that :+1:

**Comment by pdf** [comment]
Behaviour here is slightly different to the original report - no CLI arguments work at all here on Linux (Arch pkg chatterino2-git) as of a6e23e246864458c9d00c469c3b7306086b8d0ed: `--help` and `--version` simply exit with no output, and `--channels` starts the application with no effect.
