### ISSUE TITLE
chaterino crashes when opening 

### ISSUE THREAD

**Issue by SquilliamFancys0n** [Chatterino/chatterino2#2193]
**Describe the bug**

as soon as i open chatterino 2.0 and normal chatterino on mac it just crashes ive opened it in terminal and this is the error its giving me "Assertion failed: (emote.isString()), function getEmoteLink, file ../src/providers/ffz/FfzEmotes.cpp, line 20.
zsh: abort      /Applications/chatterino.app/Contents/MacOS/chatterino"

**Comment by qubidt** [comment]
duplicate of #2191

**Comment by sthic** [comment]
> duplicate of #2191

How can I put the fixed code into terminal?

**Comment by coral** [comment]
SAMEEEEEEEE
