### ISSUE TITLE
All tabs are highlighted when starting chatterino

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#2195]
**Describe the bug**

When starting chatterino now almost all tabs are highlighted.

**To reproduce**

Start chatterino :upside_down_face: .

**Screenshots**

![](https://i.nuuls.com/sYCBe.png)

**Chatterino version**

Chatterino 2.2.3-beta (commit 7d2b64087)

**Operating system**

Arch Linux latest

**Additional information**

**Comment by leon-richardt** [comment]
Interesting: this problem does not occur when building Chatterino in debug mode.

**Comment by apa420** [comment]
Actually this doesn't even have anything to do with historical messages. I have a tab without any historical messages and that one lit up...

**Comment by leon-richardt** [comment]
I believe it is related to the `connected` system message posted when you join a channel. The message flags do not seem to be applied correctly in release mode.

**Comment by leon-richardt** [comment]
I ran `git bisect` and nailed it down to 4199a01b96a222d72db98017c6599e858d9ef472 which is the commit that merged in #1748.

**Comment by apa420** [comment]
This also seems to apply to hosting messages.

**Comment by SLCH** [comment]
Then could it be the `connected` message?
