### ISSUE TITLE
Highlights no longer working in other tabs

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2196]
**Describe the bug**
If I get highlighted in one tab, it won't appear red for other tabs

**To reproduce**
1. Get someone to mention you in another tab where you have a mentions split 

**Screenshots**
![lol](https://i.nuuls.com/uk0EX.gif)

**Chatterino version**
Chatterino Nightly 2.2.3-beta (commit 3c6e6446c, )

**Operating system**
Windows 10

**Additional information**
![image](https://user-images.githubusercontent.com/12804673/99372484-f5ca7f80-290b-11eb-8d15-6d1e543c8d98.png)
![image](https://user-images.githubusercontent.com/12804673/99372509-fc58f700-290b-11eb-8b0d-f46ce90eb31d.png)

**Comment by Felanbird** [comment]
As a note this isn't fixed by e7c2e1b
