### ISSUE TITLE
ChannelFilterEditorDialog Spawns in Tiling Mode

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#2202]
**Describe the bug**
In #1843, @pajlada enforced consistent behavior for many popups used throughout the app. We missed the `ChannelFilterEditorDialog` class though, and it does not spawn in floating mode on sway in the current state.

Therefore, `ChannelFilterEditorDialog` should also be fixed and tested on the OS mentioned in #1843.

**To reproduce**
Open the dialog on sway ("Settings" -> "Filters" -> "Add").

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 60d5c5d99)

**Operating system**
Arch Linux 5.9.8-arch1-1
sway version 1.5.1

**Comment by zneix** [comment]
Don't want to comment on already closed PR, but I can say here that it spawn in floating mode on i3 4.19 with Xorg on arch 5.8.10. I will test it on Windows later when I install it again.
