### ISSUE TITLE
Maximizing Chatterino creates a border on adjacent monitors

### ISSUE THREAD

**Issue by Pr0mises** [Chatterino/chatterino2#2205]
**Describe the bug**
check #1718 #1428 #1734 
A white border appears on adjacent monitors when maximizing the main window on one monitor.
Not sure why all got closed, even if the problem still exists.

**To reproduce**
Toggle fullscreen mode in Chatterino.

**Screenshots**
check the issues

**Chatterino version**
Chatterino 2.2.2-fix (commit [a82f57f94)](https://github.com/Chatterino/chatterino2/commit/a82f57f94)
(no selfbuild)

**Operating system**
Windows 10 Pro 2004 (OS Build 19041.630)

**Additional information**
I read about a problem with QT < 5.14. The install uses 5.12.9 (maybe that's the problem?)
Chatterino About: Built with Qt 5.12.9, Windows SDK, MSVC 192729112

**Comment by alazymeme** [comment]
Fresh Windows 10 install, I also have this issue

**Comment by Pr0mises** [comment]
Chatterino version 2.3.0 (commit  c65a893 , problem still exists. 
Chatterino About: Built with Qt 5.14.0, Windows SDK, MSVC 191627043

**Comment by 0xf0f** [comment]
also having this issue, Chatterino 2.3.1 (commit cf33566fd)

**Comment by talneoran** [comment]
After looking into it, it seems this may be an issue with Windows, and I couldn't find any potential fix that can be implemented.
However, I may have found a workaround for this, we might want to instruct users to do it somehow until another fix is known.
The workaround:
Right click `chatterino.exe` -> Properties -> Compatibility -> Enable "Run this program in compatibility mode for:" -> Select Windows 8 in the drop-down menu.
![image](https://user-images.githubusercontent.com/43518924/123340869-a14c4a00-d555-11eb-8ab5-60d851ff49de.png)
After applying this the app seems to maximize with no white bar on the second monitor (on f605221).

**Comment by Pr0mises** [comment]
This actually fixed it for me as well. Great Job!

**Comment by jammehcow** [comment]
Can confirm this is a Windows bug as Firefox has been showing the same behaviour for me. Probably worth closing :+1:

**Comment by ALazyMeme** [comment]
Yes, this issue should have the blocked label added and issue closed.
