### ISSUE TITLE
Option to hide all messages from grey names.

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [Chatterino/chatterino2#2209]
**What should be added?**
I would love for an option to hide all upcoming messages from grey names ie. new users who have yet to set a color for their usernames.

**Why should it be added?**
Some are oblivious to what's going on, but most of them are simply the worst. My chat experience will be greatly enhanced (with them out of sign) for the following reasons:
- They tend to be incredibly toxic at times. For example: K-Pop stans making new accounts for the sole purpose of insulting streamers for having difference of opinion.
- Some mistake twitch for some other website and think of female streamer as camgirls who are yet to start stripping their clothes...
- They don't even know what bttv/ffz is and to fit in, start spamming inexistent emotes such as "PeppersprayLaugh" and "white pepper happy" lol.
- And overall, just pollute the chat with their incoherent nonsense.

I'm aware that this isn't a permanent solution for the beforementioned issues by any means, but it can at least filter 50% of these nuisances then I'm happy.

Thank you for taking my suggestion into consideration.

**Comment by leon-richardt** [comment]
This is easily achievable with the [Filters](https://wiki.chatterino.com/Filters/) feature available in the nightly or Beta builds :)

**Comment by DestroyTargetNonBasicLand** [comment]
I absolutely had no idea that this feature existed due to me always avoiding the beta/nightly builds for stability reasons.. So thanks for the heads up Leon! 

Cheers!

![Screenshot 2020-11-19 173214](https://user-images.githubusercontent.com/36361031/99702021-34d40e80-2a8d-11eb-8ee7-592d59f299f2.png)
