### ISSUE TITLE
Clicking on emote selection menu scrollbar closes said menu

### ISSUE THREAD

**Issue by ncla** [Chatterino/chatterino2#2211]
**Describe the bug**
You should be able to use the scrollbar in the emote completion menu. But when you click on the scrollbar, menu closes.  

**To reproduce**
1. Open streamers chat
2. Start typing to get the emote autocompletion menu, e.g. `:T`
3. Click on scrollbar

**Screenshots**
![ezgif-2-d57ddb35bd98](https://user-images.githubusercontent.com/5507083/99878050-52c77d80-2c0b-11eb-820b-c576fb43486a.gif)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 529f19a2d, 17.11.2020)

**Operating system**
Windows 10

**Additional information**
None.

**Comment by leon-richardt** [comment]
Cannot reproduce on 529f19a2d / 5.9.9-arch1-1 / sway 1.5.1

**Comment by zneix** [comment]
Cannot reproduce on 529f19a2d / 5.9.9-arch1-1 / i3 4.19 / Xorg 1.20.9, possible windows-only bug (?)

**Comment by alazymeme** [comment]
Can reproduce | Windows 10 | Chatterino Nightly 2.2.3-beta2 (commit 529f19a2d, 17.11.2020)

**Comment by leon-richardt** [comment]
Reproducible on Windows apparently:
![image](https://user-images.githubusercontent.com/35232120/99879558-13e6f700-2c0e-11eb-859b-b2508e27b7f5.png)

**Comment by fanway** [comment]
Can reproduce | macOS Big Sur 11.0.1 | commit 98035c5c83475ce13828d0090bc0b8c7bd77cc6d

**Comment by cinemassacres** [comment]
should remove the windows tag as @fanwayCan reproduce on macOS Big Sur

**Comment by leon-richardt** [comment]
> should remove the windows tag as @fanway Can reproduce on macOS Big Sur

Could also add the `mac` tag 😉

**Comment by fanway** [comment]
I've also found some odd behavior:

1. Start a new chatternino instance
2. Type something like :t
3. Try to click on the arrows or the scrollbar (it'll disappear)
4. When add one more character, for example it'll became :te (or delete t)
5. In the new emote selection, i'm able to use the scrollbar and the arrows to navigate

But after that, i've no longer be able to reproduce this behavior, only on a new instance.
