### ISSUE TITLE
Key modifier to open a link in non-incognito mode

### ISSUE THREAD

**Issue by Defman21** [Chatterino/chatterino2#2218]
**What should be added?**

Key modifier I'll hold when clicking on a link to open it in non-incognito mode.

**Why should it be added?**

While I'd prefer most of the links to be opened in incognito, I want to open some links (mostly twitch.tv and other sites where I'm logged in) to open in non-incognito.

**Comment by TranRed** [comment]
I think the existing option in the context menu should be good enough for occasionally opening a link in incognito.

**Comment by Defman21** [comment]
I wanted the opposite of that, but "Open link" does exactly what I want when "Open links in incognito/private mode" is enabled.
