### ISSUE TITLE
The ignore feature crashes Chatterino.

### ISSUE THREAD

**Issue by Sypticle** [Chatterino/chatterino2#2219]
**Describe the bug**
Adding something to the ignore list will crash Chatterino after some time (not sure how long it takes but I find it to take around 20 minutes and sometimes quicker when minimized.) 

**To reproduce**
Simply add something to the ignore list, something that might get spammed a lot, not exactly sure if that matters or not but for me it crashes when adding KEKW, and does not matter if it's case sensitive, I would also assume the replacement can be anything and would still reproduce the crash. Again, minimizing the window seems to cause the crash to happen quicker.
(also another bug, the window to choose fonts is stuck behind every other window and cannot be accessed.)

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 6499b7c12) also happens on the latest release.

**Operating system**
Windows 10

**Comment by pajlada** [comment]
Would love help in getting full reproduction steps for this issue (preferably a stack trace)

**Comment by pajlada** [comment]
@Sypticle Could you give the latest nightly a try to see if that fixes your issue?
I managed to find a case where Chatterino would freeze completely (but not crash) and that's been fixed in the latest nightly.

You can find the latest nightly here: https://github.com/Chatterino/chatterino2/releases/tag/github-actions-nightly (no installer unfortunately)

**Comment by Sypticle** [comment]
@pajlada Sorry, I actually meant freezes, it totally went over my head when writing the issue.
But I have tested it for about 2 hours now and have had no issues with it.

**Comment by alazymeme** [comment]
Close it ![PAJJED](https://user-images.githubusercontent.com/12804673/102008800-e90c4080-3d7e-11eb-9564-7e50b2c18372.png)
