### ISSUE TITLE
Automatically change account when in a certain channel

### ISSUE THREAD

**Issue by bontalor** [Chatterino/chatterino2#2221]
**What should be added?**
The option to automatically change accounts when swtiching from tab to tab, or to assign a certain account whenever a certain channel is open.

**Why should it be added?**
Many times I accidentally type something on one account when I want to type it on another, this would help reduce the chance of this happening.

**Comment by cinemassacres** [comment]
This issue is out of scope of the Chatterino project. Making logins per split would be a lot of effort.

**Comment by alazymeme** [comment]
I think the new addition of `Send a message as bonta1...` in the current build should cover this sufficiently. I don't see a good reason to implement this idea.

**Comment by MohamadFtah** [comment]
> I think the new addition of `Send a message as bonta1...` in the current build should cover this sufficiently. I don't see a good reason to implement this idea.
> 
> Not to mention that this is a great way to evade bans/timeouts, [which is not what Chatterino is for; nor is it something we want to "market" Chatterino towards](https://github.com/Chatterino/chatterino2/issues/1624#issuecomment-612844809).

how can do this? I cand find the option to add this "Send a message as ..."

**Comment by pajlada** [comment]
> > I think the new addition of `Send a message as bonta1...` in the current build should cover this sufficiently. I don't see a good reason to implement this idea.
> > Not to mention that this is a great way to evade bans/timeouts, [which is not what Chatterino is for; nor is it something we want to "market" Chatterino towards](https://github.com/Chatterino/chatterino2/issues/1624#issuecomment-612844809).
> 
> how can do this? I cand find the option to add this "Send a message as ..."

This is available in any release since 2022 - it looks like this

![Image](https://github.com/user-attachments/assets/691bf345-bacf-427e-9b04-dae1b78c295a)
