### ISSUE TITLE
Cannot Move Chat Windows inside or between tabs

### ISSUE THREAD

**Issue by wtmollj** [Chatterino/chatterino2#2223]
**Describe the bug**
When trying to move a chat window (including mentions, whispers, etc) around in a tab or between tabs, it does not move. The selected panel disappears as if it is being moved, but it goes back to the original location.

It is important to note that you can still resize chat windows, just not move them.

**To reproduce**

1. Navigate to a tab with multiple chats
2. hit CMD and click the top of the chat window
3. attempt to move the chat window within the tab or to another tab
4. see that the available locations for the chat window (the blue outlined area) do not appear
5. release the mouse button and/or CMD and see that the chat window was returned to the original location 

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 6499b7c12)

**Operating system**
macOS Big Sur v 11.0.1

**Comment by wtmollj** [comment]
FWIW, I check on Chatterino 2.2.2 (commit 07fc0c3ad) and moving chat windows is working as expected in this build.

**Comment by wtmollj** [comment]
Okay, I may have a really weird issue now....

I just relaunched Chatterino 2.2.3-beta2 (commit 6499b7c) and it is working as expected now.

Would it be possible that something in the download modified a config that stopped this from working? When the FFZ update occurred a few days ago, I removed everything for chatterino from %APPDATA% to have a clean install, and that is when the issue started.

**Comment by alazymeme** [comment]
@gempir ![image](https://user-images.githubusercontent.com/12804673/100198083-136c9a00-2f47-11eb-8546-825088fecefd.png) 🔔


Can you pls test

**Comment by gempir** [comment]
Yeah I am having the same issue. Forgot to create an issue for it. Not sure how long broken

**Comment by wtmollj** [comment]
Back to having this issue on 2.2.3-beta2 (commit 6499b7c) I guess it working for a blip was a fluke.

**Comment by pajlada** [comment]
I believe this has been fixed in the latest Qt6 release on macOS
