### ISSUE TITLE
Chatterino crashes with SIGSEGV after trying to load 1000 messages from recent-messages API

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#2226]
**Describe the bug**
I recently tried selfhosting [recent-messages service](https://github.com/zneix/) and after setting message limit to a "little" higher than original instance, but I encountered crashes. Narrowed it down to big channels with 1000 messages in cache crashing Chatterino. I know that I am first person to ever selfhost mentioned service, so this is not as important and probably nobody is as silly as I am to set message limit to 1000 or higher, but this is something that chatterino should handle on it's side and prevent from SIGSEGV'ing.

**To reproduce**
1. Set up recent-messages service on your own with message high limit (I encountered the issue with 1000).
2. Make sure you have channel that has 1000 messages in cache (like `#forsen`).
3. Run Chatterino with custom Environment: `CHATTERINO2_RECENT_MESSAGES_URL=https://recent-messages.zneix.eu/api/v2/recent-messages/%1`
4. Get an error `fish: “chatterino” terminated by signal SIGSEGV (Address boundary error)`.

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 05aab8684)

**Operating system**
Arch Linux 5.9.10-arch1-1

**Additional information**
[none](https://cdn.zneix.eu/q8Hh5mh.png)

**Comment by Mm2PL** [comment]
dupe or related to #1421 [<img src=https://static-cdn.jtvnw.net/emoticons/v1/300196486/1.0 alt=pajaM>](https://cdn.zneix.eu/q8Hh5mh.png)

**Comment by zneix** [comment]
I am honestly amazed and shocked I opened duplicated issue just after original one had it's anniversary few days ago. [xd](https://cdn.betterttv.net/emote/5e21fed68af14b5f1b43e909/1x)
