### ISSUE TITLE
Infinite scrolling in channelview with middle mouse button where messages are not fully populated

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2233]
**Describe the bug**
If a usercard is not fully populated with messages, the window will infinitely scroll with the middle click scroll

**To reproduce**
1. Find a usercard with few messages populated
2. Middle click to begin scrolling
3. Move mouse down

**Screenshots**
![xd](https://i.alazymeme.com/NationalAbleImage.gif)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 05aab8684, 22.11.2020)

**Operating system**
Windows 10

**Comment by zneix** [comment]
Can reproduce on Arch Linux 5.9.11 chatterino 5258ddd, worth noting that when I move mouse to the top, usercard messages scroll to top as well:
![](https://cdn.zneix.eu/SQOyR7k.gif)

**Comment by Mm2PL** [comment]
Unable to replicate, did something change since 5258ddd. I am using d59bb805

**Comment by Mm2PL** [comment]
Can still replicate on 74960bf4, the usercard is not supposed to be scrollable and you need to middle click on the message to get this to work.

**Comment by zneix** [comment]
Occurs in regular `ChannelView`s as well:

![FDM](https://cdn.zneix.eu/5A7yYaF.gif)
