### ISSUE TITLE
Custom user themes

### ISSUE THREAD

**Issue by zurrty** [Chatterino/chatterino2#2237]
**What should be added?**
Customizable user themes in addition to the four pre-existing themes already present in the program. Depending on which of these is easier to implement, these themes could either be written in a format like CSS, or in a way similar to how [Blender's themes](https://docs.blender.org/manual/en/dev/editors/preferences/themes.html) are managed.
**Why should it be added?**
To give users more freedom when customizing their Chatterino user interface.

**Comment by Mm2PL** [comment]
Related to #1041 and #1837

**Comment by pajlada** [comment]
Themes (beta) are implemented since v2.4.6 - you can read more about how it works here https://wiki.chatterino.com/Themes/

For further feedback on Themes you can make a new issue
