### ISSUE TITLE
FrankerFaceZ Channel-Specific Badge Assignments

### ISSUE THREAD

**Issue by SirStendec** [Chatterino/chatterino2#2241]
**What should be added?**
Recently, we (that is FrankerFaceZ) started letting users assign bot badges to users in their channels. This has been exposed in the API for some time, but between poor documentation and the inability for users to take advantage of it, I don't blame anyone for not catching it and/or implementing support. The feature is intended to let users easily flag their own custom bots without any form of approval, while the global bot badge will be limited to bots in widespread use across Twitch.

All single room endpoints now include arrays of usernames and user Twitch IDs for assigning badges to users in those specific rooms. When possible, clients should always use the Twitch ID rather than a username as usernames may be out of sync with Twitch after an account name change.

Data from the API looks something like:
```json
{
	"room": {
		...
		"user_badges": {
			"2": ["quoteconut"]
		},
		"user_badge_ids": {
			"2": [74024612]
		}
	}
}
```

`user_badges` and `user_badge_ids` are objects with keys that are the badge ID as a string (only a string due to the nature of JSON, and can be treated as integers) and the values are arrays of usernames or Twitch IDs.

In the future, this may support badges other than the bot badge. However, for now, it's limited to the bot badge with ID 2.

Side note: We now have automatically generated documentation available at https://api.frankerfacez.com/docs/ describing rooms and all other endpoints.

**Why should it be added?**
I don't know if you'd interested in this sort of feature for Chatterino, but I thought I'd bring it up as something new esp. since Chatterino recently added support for FrankerFaceZ's badges in a global sense.

**Comment by SputNikPlop** [comment]
@pajlada Does this still need to be done and are there any other considerations that need to be taken into account? I know this is a little bit of an older issue.

**Comment by pajlada** [comment]
> @pajlada Does this still need to be done and are there any other considerations that need to be taken into account? I know this is a little bit of an older issue.

This is still not implemented, correct. Nothing special that needs to be taken into account - the API is straight-forward
