### ISSUE TITLE
Link info + emote hover sometimes merge

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2243]
**Describe the bug**
If your mouse doesn't move and and hovers over a link after an emote, they will merge

**To reproduce**
1. Hover over an emote
2. Scroll to hover over a link (don't move your mouse)
3. Move mouse once hovered over the link

**Screenshots**
![xd](https://i.alazymeme.com/BottomCapitalistImage.gif)

**Chatterino version**
Nightly 2.2.3-beta2 (commit 05aab8684, 22.11.2020)

**Operating system**
Windows 10

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/100735698-62ba3b00-341d-11eb-993d-6f628f7bc466.png)

**Comment by zneix** [comment]
Just wanted to point out that's not only for emotes, basically every thumbnail from elements like badges remains when hovering over a link which has no thumbnail information. I think I might've introduced this slight issue myself when I added streamer mode settings by changing some properties of link resolver with a lazy hack. Will look into that.
