### ISSUE TITLE
Chatterino account switching

### ISSUE THREAD

**Issue by kokopuffs15** [Chatterino/chatterino2#2246]
A way to add multiple accounts

Suggestion: be able to sign in with multiple accounts and easily switch between them. I tried to do this, and when adding an account, you can only log in with one. When clicking 'Log In (Opens in browser)' it gives you the auth link to the same one. If you try the advanced tab I am unaware of a way to get the user ID, client ID, and OAuth token for another account.

It is a useful way of switching between accounts quickly.

**Comment by sando** [comment]
This already does work, but if you are still logged into Twitch with the same account in the default browser, it's going to present you with a login token for the same account.

Either log out of Twitch before logging in via Chatterino, or open https://chatterino.com/client_login in incognito mode.

**Comment by kokopuffs15** [comment]
ok thanks
