### ISSUE TITLE
Crash when moving split across windows

### ISSUE THREAD

**Issue by sando** [Chatterino/chatterino2#2249]
**Describe the bug**
A bit of a weird one here: if you popup a split, drag that split into another window, then close the popup window, a crash occurs. 

**To reproduce**
1. Popup a split (via CTRL+N)
2. From the popup window, drag that split back into another window
3. Close the window you dragged the split from
4. Wait for it to crash - opening another tab seems to make this occur quickly

**Screenshots**
![image](https://i.imgur.com/fKHCw1E.gif)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 9ebc448bc, ) (self-built)
Chatterino Nightly 2.2.3-beta2 (commit 05aab8684, 22.11.2020)

**Operating system**
Windows 10 20H2 (OS Build 10942.662)

**Additional information**
This crash seems to appear in a few different places in code depending on the timing, but these are the two I've been able to capture trying to repro while filing this issue.
![image](https://user-images.githubusercontent.com/58441/101244390-653ccd80-375a-11eb-8496-cf0057dcc3e9.png)
![image](https://user-images.githubusercontent.com/58441/101243685-ffe6dd80-3755-11eb-8344-ea5751c7c88a.png)
![image](https://user-images.githubusercontent.com/58441/101243691-06755500-3756-11eb-8008-bb983dc864eb.png)

**Comment by alazymeme** [comment]
Cannot reproduce: Windows 10 20H2 | commit a79081f44

**Comment by pajlada** [comment]
Can reproduce, looking into this now

**Comment by pajlada** [comment]
@sando Could you please try this PR out to see if it fixes your issue? https://github.com/Chatterino/chatterino2/pull/2259

**Comment by sando** [comment]
Can confirm #2259 fixes the issue. Tried the above example and a few other combinations of manipulating splits across windows, no crashes. :)
