### ISSUE TITLE
Placeholder text inconsistencies

### ISSUE THREAD

**Issue by sando** [Chatterino/chatterino2#2253]
**Describe the bug**
These two are minor as hell, so filing in the same issue

**To reproduce**
* New splits are missing the placeholder text
	1. Open new split 
![image](https://user-images.githubusercontent.com/58441/101244333-fa8b9200-3759-11eb-86be-6c8b06ee2351.png)

* Placeholder text colour isn't applied to last active split
	1. Have saved window layout with existing splits
	2. Open Chatterino
	3. Switch to another tab 
	4. Switch back to the previous tab, splits have the placeholder text in the lighter colour
![image](https://user-images.githubusercontent.com/58441/101244331-f1022a00-3759-11eb-9a31-42c40d877cc8.png)
![image](https://user-images.githubusercontent.com/58441/101244500-03309800-375b-11eb-86af-e7d6a59aa6b3.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 9ebc448bc, ) (self-built)
Chatterino Nightly 2.2.3-beta2 (commit 05aab8684, 22.11.2020)

**Operating system**
Windows 10 20H2 (OS Build 10942.662)

**Additional information**

**Comment by zneix** [comment]
I am aware of placeholder text not appearing on opening new splits, forgot to add an event listener there - will fix.
I noticed this and couple other edge-cases (like opening a new split, entering channel name in ^R dialog, changing split and pressing enter). Moving a function which applies placeholder text color to some other place (prob where split input is initialized) should fix it. I will take care of this later, thanks for reminding me :+1:
