### ISSUE TITLE
Chatterino on Mac not responding. 

### ISSUE THREAD

**Issue by vloted** [Chatterino/chatterino2#2258]
**Describe the bug**
When ever I open Chatterino on my mac, and I use if for a couple of minutes it freezes and I have to force quit to be able to use it again. I can't type, change tabs, or do anything when the problem happens. Ive cleared cache, cookies, and uninstalled and reinstalled and it still freezes. 
**To reproduce**
All I have to do is open Chatterino for the problem to happen. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41973452/233732020-98ff5a11-85f4-4d8a-94fb-b0722d618d78.png)

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 6499b7c12)

**Operating system**
Mac OS Big Sur

**Comment by pajlada** [comment]
Please re-open this issue if this still happens with the latest nightly build using the `Chatterino-universal-Qt-6.5.0.dmg` artifact
