### ISSUE TITLE
Remove buttons crash program

### ISSUE THREAD

**Issue by wormosteeze** [Chatterino/chatterino2#2262]
**Describe the bug**
When I click the Remove button on the top left of many of the settings pages, Chatterino crashes immediately without saving any of the changes I made.

**To reproduce**
Open Chatterino, open settings, navigate to Commands (for example), click Remove with any command selected, program crashes. One of the times I was playing with it the app re-opened itself, but still hadn't removed the command.

**Screenshots**
![Screenshot 2020-12-06 042912](https://user-images.githubusercontent.com/18333790/101297392-ab874080-37dd-11eb-8bb8-dc29e2f7dcdd.jpg)

**Chatterino version**
Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

**Additional information**

**Comment by fanway** [comment]
Duplicate of #1529

**Comment by fanway** [comment]
@wormosteeze it was fixed i think in 1ec1097. Try out [Chatterino 2.2.3-beta](https://chatterino.com/download/2.2.3-beta/Chatterino%20Installer.exe) or [Chatterino 2.2.3-beta2](https://chatterino.com/download/2.2.3-beta2/Chatterino%20Installer.exe).

**Comment by wormosteeze** [comment]
ah ok, I searched in issues but didn't find that one. thanks!
