### ISSUE TITLE
Normal users bypassing chat freeze

### ISSUE THREAD

**Issue by kokopuffs15** [Chatterino/chatterino2#2270]
In fast twitch chats when the chat freezes, normal users that send messages in that time will not have their messages sent through. Moderators/VIP members in chat bypass this. I have been seeing some normal users bypass this somehow (they dont have VIP or Moderator status) how are they doing this?

**Comment by alazymeme** [comment]
Never seen any user bypass that freeze and i only ever see this freeze occur in webchat. Regardless, it isn't a chatterino issue.

**Comment by kokopuffs15** [comment]
maybe it is from chatterino premium? anyone else know

**Comment by alazymeme** [comment]
> maybe it is from chatterino premium? anyone else know

No such thing as Chatterino premium. Chatterino is an IRC client in it's raw-est form and relies on Twitch's chat servers.

**Comment by pajlada** [comment]
The "users" bypassing this might be verified bots. Next time you see that happening, look at the name and think "hmm, could this be a bot? is the name coolmanbot? hmm"
