### ISSUE TITLE
Universal Emote refresh

### ISSUE THREAD

**Issue by stellarakshay** [Chatterino/chatterino2#2281]
**What should be added?**
Whenever typing f5 on a certain tab, it should refresh emotes in every chat that you have tabbed.  Could be a toggleable feature.
**Why should it be added?**
Allows the user to have updated BTTV/FFZ emotes in every chat with only one refresh, instead of going to each chat and typing f5.

**Comment by Mm2PL** [comment]
>  Could be a toggleable feature.
Would be better to have it as a separate shortcut, as you don't want to refresh all channels every time you want to refresh a single one. It's not very ergonomic to go to the settings change a thing, close the window, refresh emotes and then revert the setting.

> Whenever typing f5 on a certain tab, it should refresh emotes in every chat that you have tabbed.
Why not restart Chatterino if you need all emotes refreshed?

**Comment by Mm2PL** [comment]
#2159

**Comment by alazymeme** [comment]
> I don't agree with this, it will probably result in spamming the ffz and bttv apis.

https://github.com/Chatterino/chatterino2/issues/2159#issuecomment-722217065
