### ISSUE TITLE
Can't see letters

### ISSUE THREAD

**Issue by doggoaltr** [Chatterino/chatterino2#2283]
All letters are  changed to some type of rectangle.

Opened chatterino, and it was like that

![imagem_2020-12-15_095810](https://user-images.githubusercontent.com/69827295/102217917-085cb800-3ebc-11eb-8ceb-575555cfced6.png)

Can't copy the version because of the bug, but pretty sure it's 2.2.3 beta2

Windows 10

Tried re-opening and it stays the same.

**Comment by apa420** [comment]
This is most likely an issue with your font, try changing it.
(It's the second item in settings).
If you can't change it or it doesn't work, try deleting your setings config in %appdata% for chatterino

**Comment by apa420** [comment]
If the issue persists, please reopen the issue
