### ISSUE TITLE
Image uploader failing to upload. (ERROR: 202)

### ISSUE THREAD

**Issue by DarkVypr** [Chatterino/chatterino2#2287]
**Describe the bug**
When dropping an image into Chatterino using i.nuuls.com, I get an error: "An error happened while uploading your image: 202"
I have inputted the required info. 

![1](https://user-images.githubusercontent.com/70484211/102414715-ffa3d900-3fc4-11eb-9961-ac7f945b32f3.PNG)
![2](https://user-images.githubusercontent.com/70484211/102414716-ffa3d900-3fc4-11eb-8a1d-5b6ff4c6ce38.PNG)

**To reproduce**
1. Enter the details [here](https://wiki.chatterino.com/Image%20Uploader/) for i.nuuls.
 ![3](https://user-images.githubusercontent.com/70484211/102414784-19ddb700-3fc5-11eb-8412-2316d71e951f.PNG)

2. Drop an image.

3. voila

**Chatterino version**

Chatterino 2.2.3-beta2 (commit 6499b7c12)

**Operating system**
Win 10 Home

**Comment by alazymeme** [comment]
Cannot reproduce, sounds like a network or image issue to me; definitely nothing wrong.

**Comment by leon-richardt** [comment]
Do you also encounter an error when using the [web interface](https://nuuls.com/i)?

**Comment by Mm2PL** [comment]
Unable to reproduce with a file on disk using both imgur, i.nuuls. 
My OS is Ubuntu 20.04.01

**Comment by DarkVypr** [comment]
> Do you also encounter an error when using the [web interface](https://nuuls.com/i)?

works fine with the web.

**Comment by zneix** [comment]
@DarkVypr I think there might be some issue with those fields in settings. This might sound ridiculous, but go to each field, Ctrl+A, Delete, and try typing in the request link and form field by hand. I have no idea why that happens, but it may be some invisible character being appended once you paste stuff to those lines.

**Comment by DarkVypr** [comment]
> @DarkVypr I think there might be some issue with those fields in settings. This might sound ridiculous, but go to each field, Ctrl+A, Delete, and try typing in the request link and form field by hand. I have no idea why that happens, but it may be some invisible character being appended once you paste stuff to those lines.

Did this. Started working perfectly now. I don't know if this fixed it or maybe it just fixed itself. Thanks
