### ISSUE TITLE
Allow you to popout the entire tab instead of 1 split.

### ISSUE THREAD

**Issue by mmattbtw** [Chatterino/chatterino2#2288]
**What should be added?**

Allow you to popout the entire tab instead of 1 split, so if you have more then 1 channels in a specific layout you have, then you can easily have a popout window without having to setup the layout again.

**Why should it be added?**

Just a nice QOL change that would be nice.

**Comment by zneix** [comment]
Similar to how `Ctrl+W` and `Ctrl+Shift+W` work, I could see `Ctrl+Shift+N` being added for popping out the entire tab instead of just the current split.

**Comment by mmattbtw** [comment]
Any updates on this?
