### ISSUE TITLE
FFZ:AP Badges Support

### ISSUE THREAD

**Issue by Lordmau5** [Chatterino/chatterino2#2289]
**What should be added?**
FFZ:AP Supporter and Developer badges

**Why should it be added?**
FFZ:AP has a considerably huge user-base and a couple of people have asked if there could be support in Chatterino for it.

**API related info**
The main endpoint would be:
`https://api.ffzap.com/v1/supporters`

A list of users with their Twitch ID, tier, badge color and a flag called `badge_is_colored`.
The ID should be self-explanatory.
As for the tier:
- Tier 1 is the default badge color, `#755000`
- Tier 2 is the `badge_color` in the API (users can set a custom badge color)
- Tier 3 is the `badge_color` but only if `badge_is_colored` is set to 0. Set to 0 means that a custom color is applied to the badge (since the icon would be white and colored in the browser side), 1 means it's a custom image entirely (so just a colored PNG)

There are a few hardcoded helpers that have a different title, and me as the developer having a differen title, too.
Information about their IDs and titles can be found here:
https://github.com/FrankerFaceZ/Add-Ons/blob/master/src/ffzap-core/index.js#L11

As for the badge images themselves, they can be found on these URLs:
`https://api.ffzap.com/v1/user/badge/<user_id>/1`
`https://api.ffzap.com/v1/user/badge/<user_id>/2`
`https://api.ffzap.com/v1/user/badge/<user_id>/3`

Example:
https://api.ffzap.com/v1/user/badge/26964566/1
https://api.ffzap.com/v1/user/badge/26964566/2
https://api.ffzap.com/v1/user/badge/26964566/3

___
If there's more information necessary please do tell me

**Comment by alazymeme** [comment]
The only reason we have ffz and bttv badges in chatterino is because we use the service. I don't see a reason to add ffz ap badges if we don't use the service (or features for that matter).

**Comment by leon-richardt** [comment]
I agree with @alazymeme. Since we don't use any of the services FFZ:AP provides, there is no reason to show their badges. It would be akin to FFZ:AP adding support for Chatterino badges (for which I don't see any reason either).

Furthermore, I think implementing this could also set an uncomfortable precedent. Adding support for FFZ:AP badges would make it harder to argue against adding support for any kind of badges users might request.

**Comment by Lordmau5** [comment]
I can fully understand your reasoning behind not wanting to implement support, I didn't even think about that when being asked by some of my users a few times.

This issue / suggestion was mostly a relay of the users' requests over the past few months so there's that.

Anyway, thanks for the insightful information in regards to the reasoning on this 😁
