### ISSUE TITLE
Chatterino 2 login expired and asking for entirely new authorization? (not just pasting in the key again)

### ISSUE THREAD

**Issue by martinsstuff** [Chatterino/chatterino2#2292]
I know that Chatterino sometimes needs to be reauthorized but when I went to do it now, I got sent via the page from Twitch where it lists all the permissions Chatterino has and you have allow it, as if it was the first time authorizing it.

Is this known/intentional?

Edit: Chatterino 2 was still listed under the connected apps.

**Comment by sando** [comment]
Yes, this is expected - additional OAuth scopes have recently added to login (see Chatterino/login#4, Chatterino/login#8) which would cause the new permission prompt.

If you are unsure, you can always forcefully remove the connection from Twitch first, then relogin.

**Comment by martinsstuff** [comment]
> Yes, this is expected - additional OAuth scopes have recently added to login (see [Chatterino/login#4](https://github.com/Chatterino/login/pull/4), [Chatterino/login#8](https://github.com/Chatterino/login/pull/8)) which would cause the new permission prompt.
> 
> If you are unsure, you can always forcefully remove the connection from Twitch first, then relogin.

Thanks for clarifying, that's what I ended up doing.

**Comment by sando** [comment]
FYI, I just double-checked and it doesn't look like Chatterino/login#8 has been deployed to production yet, so don't be alarmed when your OAuth token expires, and it needs to request additional permissions again. 😄
