### ISSUE TITLE
I have an issue where some of the badges dont show up when using the Chatterino Browser Extension

### ISSUE THREAD

**Issue by eie357** [Chatterino/chatterino2#2293]
Im using the integrated browser extension https://i.imgur.com/rA9kDD2.png but moderator badges and verified checkmark badges dont show up in the chat at all.

 I also made sure to check all of these settings https://i.imgur.com/P5JQ5RI.png

Any ideas on what might have gone wrong? I've only noticed the badges starting to not show a few days ago and havent figured out what happened to them.

I haven't tried reinstalling the program or extension,  but i will probably do that if i dont think of anything else to try to fix it.

**Comment by cinemassacres** [comment]
cannot confirm https://i.imgur.com/wtFkyC6.png

**Comment by zneix** [comment]
First of all, issues regarding Chatterino's browser extension should be opened in https://github.com/chatterino/chatterino-browser-ext and second, twitch often bugs out and doesn't pass information about some badges in messages. Not sure if this is just that causing your issue, but I don't see any other cause for it.

**Comment by pajlada** [comment]
Do the badges *never* show up in any chat? or do they just disappear sometimes?

**Comment by apa420** [comment]
If you still have this issue @eie357 update chatterino if possible and submit an issue to https://github.com/chatterino/chatterino-browser-ext
