### ISSUE TITLE
Link in new tab

### ISSUE THREAD

**Issue by benjiPKS** [Chatterino/chatterino2#2294]
ive noticed how you cant right click a link and make it open up in a new tab?
only why i can think of it is you right click the link and below open link in open link in new tab?

in case you want to open a link and you dont trust someone and something like forsen doesnt happen again 

![image](https://user-images.githubusercontent.com/73210322/102675112-4e7f8780-41ec-11eb-945b-105b6f8f6eff.png)

**Comment by alazymeme** [comment]
The way I understand windows decides which window to open the link in, is based on which was focused last. I'm not sure if there's anything that can be done here.

**Comment by pajlada** [comment]
Yes, as far as I know the link you click will be opened in a new tab in the last focused default browser window.

If you want to open a link and not have it show on stream, you should either take care to last focus the off-stream browser window **or** you could just copy the link and paste it into a new tab/window in the place of your choosing.

Please elaborate on the issue and re-open it if this didn't cover your issue.
