### ISSUE TITLE
SASL auth not working on aur ch2

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2295]
**Describe the bug**
SASL auth isn't working on the aur build of chatterino

**To reproduce**
1. Add irc server
2. Add SASL auth
3. Notice it doesnt work

**Screenshots**
![RoastedAutomaticImage](https://user-images.githubusercontent.com/12804673/102687185-13577580-4239-11eb-8050-bb387135e7da.jpg)

**Chatterino version**
Chatterino 2.2.3-beta2 (commit f02e6acc2)

**Operating system**
Manjaro running KDE

**Comment by pajlada** [comment]
@alazymeme Have you tried compiling latest master and see if it works outside of AUR?

**Comment by alazymeme** [comment]
No I haven't, will try that now.

**Comment by alazymeme** [comment]
Closing because I'm retarded and can't spell my own username
