### ISSUE TITLE
Clicking on username hyperlink in UserInfoPopup no longer works

### ISSUE THREAD

**Issue by sando** [Chatterino/chatterino2#2297]
**Describe the bug**
In earlier builds, clicking username hyperlinks in UserInfoPopup recent messages used to bring up another UserInfoPopup for the user in question. This was helpful for following a conversation. It appears this functionality broke recently in 1ee1e8837f82cafb56fbffa1e4fe83dc2e41bced, but works fine in 523874dc210e41640986299d0b07c0fa6c6e76de.

**To reproduce**
1. *Automatically close user popup when it loses focus* option is enabled 
2. Open a UserInfoPopup
3. Click on a mentioned user in their recent messages
4. The first UserInfoPopup disappears, and a second one doesn't appear at all

**Screenshots**
Behaviour when working (523874dc210e41640986299d0b07c0fa6c6e76de):
![YHUPGjTgCf](https://user-images.githubusercontent.com/58441/102689058-663c2780-424f-11eb-802a-88ee95d8489b.gif)
Behaviour when broken (1ee1e8837f82cafb56fbffa1e4fe83dc2e41bced):
![yt99fFLVTM](https://user-images.githubusercontent.com/58441/102689042-50c6fd80-424f-11eb-9856-6fc041d5c754.gif)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit fea52faa6, 19.12.2020)

**Operating system**
Windows 10 20H2 (OS Build 10942.662)

**Comment by alazymeme** [comment]
Cannot reproduce | Manjaro | 2.2.3-beta2 (commit f02e6acc2)

**Comment by zneix** [comment]
@sando did you try fea52faa66435f073cd62c61c98d7418407364b9 (latest nightly as of now), does the issue occur on this version as well? I cannot reproduce this on Arch Linux 5.9.15-1. It must've been a temporary bug that got fixed later.

**Comment by sando** [comment]
Ah, that's embarassing - I didn't know that option even existed, thanks! I'll use that to workaround for now. 

Just to confirm, it still occurs for me on fea52faa66435f073cd62c61c98d7418407364b9 on Windows 10 20H2 (OS Build 10942.662).
