### ISSUE TITLE
Universal app for Mac (Apple silicon support)

### ISSUE THREAD

**Issue by r-j-w** [Chatterino/chatterino2#2300]
**What should be added?**
Build Chatterino as a universal app for intel + arm based macs.

**Why should it be added?**
Apple's ditching intel for apple's processors for future macs. Chatterino has run fine for me via rosetta but would have better performance as a native binary and apple will (probably) discontinue rosetta at some point.

Happy to test out any builds.

**Comment by leon-richardt** [comment]
Here is some [Apple documentation](https://developer.apple.com/documentation/xcode/porting_your_macos_apps_to_apple_silicon) regarding this

**Comment by Aayush9029** [comment]
I was wondering if there's any updates on this?
I'd be happy to contribute otherwise!

**Comment by LosFarmosCTL** [comment]
> I was wondering if there's any updates on this?

Not really, compiling into universal binaries requires a newer qt version than what c2 is currently using, it's officially supported starting with qt 6.2 and unofficially + untested with 5.15.4 (see this [qt blog post](https://www.qt.io/blog/qt-on-apple-silicon)

I am currently the only contributor even using macOS and don't own any Apple Silicon hardware to test this myself, so if you do and want to do anything in this regard you are very welcome to.

For now from what I can tell rosetta should work pretty good, but of course compiling native would always be better.

**Comment by charlie-niekirk** [comment]
I guess it probably doesn't help with a universal binary but following the macOS build instructions on an Apple Sillicon machine (with arm64 dependencies installed with brew) work great. qmake failed for some reason but cmake worked 100%. 
<img width="1512" alt="Screenshot 2022-03-11 at 17 33 53" src="https://user-images.githubusercontent.com/18074024/157918925-b407a320-7d21-4a97-bf7d-baedf41e5ad4.png">

**Comment by Aayush9029** [comment]
@charlie-niekirk do you mind uploading the arm64 binary? That'd be awesome!

**Comment by seanbperiod** [comment]
@Aayush9029 @charlie-niekirk Yes, please do! Thank you

**Comment by dieserRobin** [comment]
[chatterino.app.zip](https://github.com/Chatterino/chatterino2/files/8240662/chatterino.app.zip)
@Aayush9029 @seanbperiod Here's a Chatterino build for arm64.

**Comment by seanbperiod** [comment]
Hey @dieserRobin 

I just tried running it - M1 Pro 14" 12.2.1 - And I got file is "damaged and can't be opened" 😬

**Comment by dieserRobin** [comment]
> I just tried running it - M1 Pro 14" 12.2.1 - And I got file is "damaged and can't be opened" 😬

Ah, I forgot about macOS security measures. I'm sure you can find a command to work around it, but since I generally don't recommend using something like that, I won't post it here.

**Comment by seanbperiod** [comment]
@dieserRobin Messaged you on Twitter. 👍

**Comment by Aayush9029** [comment]
@seanbperiod 

You can remove the app from quarantine using
`xattr -c /PATH_TO_Chatterino.app`

Make sure to have all the dependencies for it as well!
`brew install boost openssl@3  qt@5`

Also, thanku @dieserRobin that worked pretty well!

**Comment by seanbperiod** [comment]
@Aayush9029 Perfect! That worked! Thank you!

**Comment by seanbperiod** [comment]
Hey 👋 @dieserRobin any chance for an update? 😬

**Comment by jammehcow** [comment]
As per [this CrystalIDEA article](https://github.com/crystalidea/macdeployqt-universal), Qt5 doesn't have official support for universal builds unless you're using the commercial LTS 5.15.9 release. I imagine this would need to wait for Qt6 unless we want to start using 3rd-party Qt5 distributions (like CrystalIDEA) which I wouldn't recommend. 

Could a maintainer tag this as blocked while we progress with the Qt6 migration?

**Comment by jammehcow** [comment]
On a side note, it would be good to gather up a group of both Apple silicon and Intel users to daily-drive the Qt6 builds when they're working. @aidenwallis you might be a goto for this as I believe you're using a M1 Mac.

**Comment by seanbperiod** [comment]
I just want to note - not sure if this is happening in current or nightly builds, but the chatterino app is stealing focus when switching spaces. I currently use it in split view / fullscreen mode with another app in a space, and when switching spaces, chatterino will often automatically switch the screen back to it's space, and I practically have to fight with switching spaces and quickly click on another app to prevent it from happening.

**Comment by leon-richardt** [comment]
> I just want to note - not sure if this is happening in current or nightly builds, but the chatterino app is stealing focus when switching spaces. I currently use it in split view / fullscreen mode with another app in a space, and when switching spaces, chatterino will often automatically switch the screen back to it's space, and I practically have to fight with switching spaces and quickly click on another app to prevent it from happening. 

Thanks for the report. Would you mind opening a new issue for that so that it can be tracked more easily?

**Comment by LosFarmosCTL** [comment]
> Would you mind opening a new issue for that so that it can be tracked more easily?

Also, please include a video when you do, I would like to try and find out how to replicate this since I never noticed anything like that myself.

**Comment by Brog33** [comment]
any progress on an universal/apple silicon build?

**Comment by LosFarmosCTL** [comment]
> any progress on an universal/apple silicon build?

As stated above, chatterino as a whole will have to switch to qt6 for that to happen, which is a big undertaking.

Definitely happening at some point, but don't hold out your breath for it, especially considering that afaik it runs absolutely fine through rosetta, this is not a priority atm.

**Comment by seanbperiod** [comment]
@Brog33 I've just been using the build @dieserRobin posted above: 

https://github.com/Chatterino/chatterino2/issues/2300#issuecomment-1066188036

I've had no issues with it so far. 

I won't install a layer that slows down the system for one app. I appreciate others have stepped in with a solution while we wait for an official solution.

**Comment by Brog33** [comment]
thanks @seanbperiod i'll use that for now :)

**Comment by LosFarmosCTL** [comment]
> I've had no issues with it so far.

@seanbperiod 
@Brog33 
Just dropping this here as a warning, from the 24th of february onwards you will no longer have access to /slash commands using that version (things like /timeout /ban /whisper /color etc.) due to twitch  moving that stuff to a different API and that migration obviously not being done inside of older version. See #4214 for more information.

I'd highly recommend to just use the Intel version of chatterino via Rosetta since it's just not possible for us right now to provide pre-built versions for Apple Silicon on GitHub. I have no idea where you got the information about Rosetta slowing down the rest of the system from, literally the only thing it does is run unsupported apps through a translation layer, which obviously affects their performance somewhat (it's still really efficient, somewhere around 75% of native performance) but does not affect the rest of the system in any other way.

**Comment by Brog33** [comment]
@LosFarmosCTL thanks for the heads-up! 
you're right.. the biggest resource-drain in chatterino is the lack of GPU-rendering, so even on a M1 Pro it uses ~35% cpu just by having the window open (regardless of x86 or arm - it's the same in linux). maybe qt6 will help with this.

**Comment by Mm2PL** [comment]
Possibly related issue: #4445

**Comment by pajlada** [comment]
Universal builds are now available in nightly if you look for the `Chatterino-universal-Qt-6.5.0.dmg` artifact, and will be available in the next stable release.

**Comment by Brog33** [comment]
Great work! I have a question about the renderer, though. Chatterino is still very CPU hungry, so I would assume it still does not use the GPU for rendering?

**Comment by blueglozz** [comment]
Hello, i tried the new universal installer on my silicon mac. it didn't work. is the arm64 still getting separate updates ? i'm worried.
