### ISSUE TITLE
follow button

### ISSUE THREAD

**Issue by souf-c** [Chatterino/chatterino2#2301]
**What should be added?**
A follow button should be added

**Why should it be added?**
This would be really helpful for following new streamers

**Comment by zneix** [comment]
@souf-c this is already an existing feature. You can either click on the tickbox in the usercard or use `/follow <username>` and `/unfollow <username>`. To open someone's usercard you can also just type `/usercard <username>`. Hope that helps

![xd](https://cdn.zneix.eu/VwCLBTj.png)

**Comment by alazymeme** [comment]
Good Day souf-c!

Thank you for your interest in Chatterino 2, your feedback is very helpful to us. I'm pleased to advise you that this is in fact already a feature! 😄 

As zneix mentioned above, you can use the follow feature by simply typing `/follow <user>` (without the square brackets) or click on the follow button on the user's usercard.

Further to this, we'd really appreciate if you took the time and effort to correctly fill out the feature request form. For your reference, you can find the feature request template when you file a new issue. This greatly assists us with fully understanding what new feature you would like in Chatterino 2. Please find the below image of the template filled out:

![feature request template](https://user-images.githubusercontent.com/12804673/102711891-b7f4b880-4308-11eb-9a99-6fe7f45ee608.png)

Once again, thank you for your interest in Chatterino 2 and we appreciate the feedback!

Kind Regards,
ALazyMeme

**Comment by souf-c** [comment]
> Good Day souf-c!
> 
> Thank you for your interest in Chatterino 2, your feedback is very helpful to us. I'm pleased to advise you that this is in fact already a feature! 😄
> 
> As zneix mentioned above, you can use the follow feature by simply typing `/follow <user>` (without the square brackets) or click on the follow button on the user's usercard.
> 
> Further to this, we'd really appreciate if you took the time and effort to correctly fill out the feature request form. For your reference, you can find the feature request template when you file a new issue. This greatly assists us with fully understanding what new feature you would like in Chatterino 2. Please find the below image of the template filled out:
> 
> ![feature request template](https://user-images.githubusercontent.com/12804673/102711891-b7f4b880-4308-11eb-9a99-6fe7f45ee608.png)
> 
> Once again, thank you for your interest in Chatterino 2 and we appreciate the feedback!
> 
> Kind Regards,
> ALazyMeme

done thank you 👍

**Comment by alazymeme** [comment]
Thank you, I appreciate the help!

Could you please advise where you wish for the suggested follow button to be?

Many thanks,
ALazyMeme

**Comment by zneix** [comment]
@alazymeme I don't think we need another follow button since we have soltions I've already explained in my first comment. Isn't that sufficient already?

**Comment by alazymeme** [comment]
> @alazymeme I don't think we need another follow button since we have soltions I've already explained in my first comment. Isn't that sufficient already?

Good point!

However without more information, we do not know how souf-c would like it implemented! 😄 
It would be wise to wait for souf-c's response in order to obtain more information about the request.

Kind Regards,
ALazyMeme

**Comment by pajlada** [comment]
Feel free to re-open if you have any other suggestions. Thanks!
