### ISSUE TITLE
Crash when attaching to browser and same chat is not in main window

### ISSUE THREAD

**Issue by c0ldplasma** [Chatterino/chatterino2#2302]
**Describe the bug**
When trying to attach a chat to browser which is not open in the main window chatterino crashes. When opening it first in the main window it works.

**To reproduce**
Try attaching to browser on a channel which is not open in the main chatterino window.

**Screenshots**
https://user-images.githubusercontent.com/14879514/102714504-3af91d00-42cf-11eb-9651-6eb522057009.mp4

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit cfa9e5903, )

**Operating system**
Windows 10 20H2

**Additional information**

**Comment by zneix** [comment]
I believe that this kind of issues with browser extension should be tracked under [extension's repository](https://github.com/chatterino/chatterino-browser-ext).

**Comment by cinemassacres** [comment]
should close

**Comment by c0ldplasma** [comment]
ok then i copy it to the extension repo
