### ISSUE TITLE
UI setting for placeholder text

### ISSUE THREAD

**Issue by IMNdi** [Chatterino/chatterino2#2305]
**What should be added?**
Would be great to have a setting to disable the newly added input box placeholder text.

**Why should it be added?**
Adds clutter to the UI for information that (presumably) the vast majority of the users doesn't need, duplicating the title bar info. This is especially confusing if you have set your Chatterino colors to be eye friendly and the text is already gray on black - the input window is just another line. Another example of low contrast would be a newly started/restarted client that loads old text in gray.

I think that de-clutter settings are a good idea, generally.

**Comment by apa420** [comment]
There is a setting to disable the input box showing up when empty. Maybe that's something you'd be interested in.

**Comment by IMNdi** [comment]
I am aware of the setting, I find it disorienting, especially if submitting consecutive lines and never being sure if the line has been submitted or not. Thank you for the suggestion, but it's not for me.

**Comment by zneix** [comment]
As an author of placeholder text, I thought this would be a nice addition to the UI, copying native webchat's 4placeholder and since it wasn't so big of a change I thought it would be nice to save ourselves addition of yet another very small setting to the already enormous pile of settings, but given your point I can see why some dislike this and I am down to add a toggle setting for it.

**Comment by TranRed** [comment]
Placeholder texts seem to be the universal standard for almost everything nowadays. Like text boxes, chat inputs, search bars etc. Examples: Firefox, Chrome, Discord, MS Teams, Twitch Webchat, Github Comment Input Box and many more.

And then there is ofc this in Chatterino Settings:
![grafik](https://user-images.githubusercontent.com/16636423/102908672-13918400-4478-11eb-9ed5-1fe20093d991.png)

But can't hurt to have this setting, right?

_"Just one more setting FeelsGoodMan"_ - Chatterino, 2020

**Comment by alazymeme** [comment]
> But can't hurt to have this setting, right?

Do we need more settings? This seems unnecessary in the grand scheme of things.

**Comment by apa420** [comment]
I also find this placeholder text annoying. But adding a setting to change it just seems unnecessary. Settings are already very cluttered and more settings don't do any good imo.

**Comment by pajlada** [comment]
I don't think a setting is the way to go to customize this feature.

If you think the contrast between the input background and placeholder text is off, then custom themes - if anything - should be the solution.
