### ISSUE TITLE
Instantly crashing - changelog

### ISSUE THREAD

**Issue by AGM1997** [Chatterino/chatterino2#2307]
**Describe the bug**

I downloaded the software multiple times, deleted it and tried to download it again.
I also reinstalled the Microsoft Visual application multiple times.
If I want to open Chatterino, I only get a small window, which asks me to show the changelog, I can select yes or no.
When selecting yes, I get redirected to: https://www.chatterino.com/changelog and a white window opens for 2 seconds, and closes again.

**Operating system**

Windows 10 Home

![2](https://user-images.githubusercontent.com/76499711/102940834-82d79a00-44b1-11eb-9f4c-7a8012a959d8.JPG)

**Comment by AGM1997** [comment]
If I download the 1.3.3 zip file, I can open the software via the .exe and a window appears. When I try to type something in, nothing appears, even though I connected my account.
When updating the software, I have the same issue, as described earlier, again.

**Comment by alazymeme** [comment]
What version of chatterino are you trying to use?

**Comment by AGM1997** [comment]
I tried downloading the current and the night buld version, sadly, both don't work for me.

**Comment by Tharaxis** [comment]
My Chatterino (latest Windows version) was working fine, but today it seems to have stopped working. I launch it, it shows a white window for a few seconds then just closes down. I tried deleting the Chatterino cache, but I still have the same behaviour.

**Comment by lazy2502** [comment]
I'm having this same issue. I've tried multiple different versions of Chatterino, including the nightly build and portable versions, I have reinstalled vcredists, cleared everything in Chatterino2 appdata folder, updated drivers, and I am on latest version of Windows 10. Still, when I launch it, it shows a blank window and then closes. Not really sure what else to do, but any updates or fixes would be appreciated.

**Comment by lizamz** [comment]
I am also having this same issue, I have already done all of the things above to try to fix it (reinstall Microsoft visual software, clear app data) and no matter what I do, when I reinstall and clear everything to do with the Chatterino application it crashes upon startup.

**Comment by lazy2502** [comment]
I reinstalled windows which fixed it up until about 2 days ago. I Installed Chatterino 2.1.0 and that seems to be working for me at the moment. I'd try that.

**Comment by Felanbird** [comment]
This unlikely happens anymore, since the Changelog prompt is just annoying enough (since people wont click yes), if it continued to crash you we'd definitely have heard about it.
