### ISSUE TITLE
Enable logging only for channels you moderate in

### ISSUE THREAD

**Issue by askhp** [Chatterino/chatterino2#2311]
**What should be added?**
There should be an option that allows you to only save logs for the channels you moderate in. (If the channel is in one of the tabs)

Options > Moderation > Logs > Enable logging only for channels you moderate in

![Concept](https://user-images.githubusercontent.com/62464821/103133971-4e80fb00-46b6-11eb-814c-e079f3d33538.png)

**Why should it be added?**
For example I don't want to log all of the channels that are in my tabs. I only want to log the channels that I moderate in.

**Comment by Mm2PL** [comment]
Duplicates #1456

**Comment by Felanbird** [comment]
The ability to do this was added in #4302 - though you'll have to add the channels yourself.
