### ISSUE TITLE
BTTV/FFZ emotes

### ISSUE THREAD

**Issue by vizkuel** [Chatterino/chatterino2#2312]
**What should be added?**

**Why should it be added?**

Alright so basically i would love for chatterino to recognize all / most used / most common FFZ and BTTV emotes in any chat, doesn't matter weather the streamer have them in the chat or not, chatterino will recognize it anyways. i just think this would be pretty dope to have.

**Comment by TranRed** [comment]
I'm very sorry, but I don't understand what functionality should be added exactly. Could you please rephrase this issue to make it more clear?

**Comment by vizkuel** [comment]
Sorry, So basically i would love for chatterino to show either ALL FFZ and BTTV emotes or atleast the more common ones, (widehardo, pepelaugh kekw etc.) in EVERY chat, even the ones that don't have the emotes or even any emotes from BTTV and FFZ.

**Comment by Mm2PL** [comment]
@vizkuel You're describing the (now defunct¹) smokEmotes project did. This will have the exact same flaws as that project did, mainly not all users seeing the emotes. Just the people who have opted in manually to have the support.

¹ it is no longer present on the [website](https://www.smokey.gg/)

**Comment by vizkuel** [comment]
i never heard of smokEmotes, i just feel like this would be really dope to have in chatterino, i don't really care if other people have chatterino or not, i just think it would be nice for chatterino users. you know? idk

**Comment by TranRed** [comment]
So you basically want every BTTV/FFZ emote to be global. We should not bypass the limits set in place by these services imho. Seems out of scope of what the chatterino project tries to do. And I also assume the BTTV/FFZ people will most likely not like that (understandably)

**Comment by Mm2PL** [comment]
> i just feel like this would be really dope to have in chatterino, i don't really care if other people have chatterino or not, i just think it would be nice for chatterino users. you know?

Emotes are meant to convey some meaning, be it an emotion, a reference to some meme etc. Other people that can't see the emotes probably won't be able to understand you. Yes this might be useful in some chats where the channel owner is too lazy/doesn't want to add emotes, but the community uses them anyway. **This feature would cause more confusion than do good.**

**Comment by vizkuel** [comment]
> > i just feel like this would be really dope to have in chatterino, i don't really care if other people have chatterino or not, i just think it would be nice for chatterino users. you know?
> 
> Emotes are meant to convey some meaning, be it an emotion, a reference to some meme etc. Other people that can't see the emotes probably won't be able to understand you. Yes this might be useful in some chats where the channel owner is too lazy/doesn't want to add emotes, but the community uses them anyway. **This feature would cause more confusion than do good.**

I guess that's true. idk

**Comment by fourtf** [comment]
We try to create a similar experience to bttv, ffz or vanilla chat and this strays away from that pretty far. I imagine it would also not be popular that you need specifically chatterino to see the emotes and that browser extensions like bttv and ffz aren't sufficient.
