### ISSUE TITLE
Channel Tab Panel Minimization

### ISSUE THREAD

**Issue by Alicyl** [Chatterino/chatterino2#2313]
### The Ability to Collapse/Minimize the Channel Tab Panel.

- There could be an option in the vertical ellipsis or directly left of the chat panel—maybe even a key combination—that can cause the chat panel to collapse towards the left which will hide all of the channel tabs until the chosen method is used again to reveal the channel tabs.

### Desktop Screen Management.

- I believe this feature should be added, or at least considered, because of how many favorite streamers people tend to have and how many of them they will have open; I have approximately fifty streamers (I know; it's probably a lot) I enjoy watching from time to time when my other favorite streamers are offline, and I tend to frequent some of their offline chats. Since I have so many channel tabs active, my Chatterino occupies almost half of my desktop's screen, and that space could be relinquished if I could somehow hide the panel for the channel tabs. While the channel tab panel is collapsed, there could be some sort of notification symbol on it that notifies us each time a streamer goes live until it is expanded.

Even if it's not to be considered, thanks for at least reading it. ღ

**Comment by alazymeme** [comment]
I like this idea, but not the use-case you suggest. Splits exist for the exact thing you're complaining about.

**Comment by leon-richardt** [comment]
If I understand correctly, I believe @zneix has looked at a similar feature in the past.

**Comment by Alicyl** [comment]
> ...but not the use-case you suggest. Splits exist for the exact thing you're complaining about.

Chatterino needs to be resized to make the chats of many splits legible thus making it worse than simply opening up additional channel tabs and scrolling (mouse wheel)/clicking through them, and before anyone suggests the 'Popup' feature, that has the potential to create too much clutter for ALT/Windows Key + Tabbing.

The splitting feature is fine for about four to six channels but not for any more beyond that, and not all of us have multiple monitors or panoramic monitors due to various circumstances to accommodate that many splits.

**Comment by leon-richardt** [comment]
> > If I understand correctly, I believe @zneix has looked at a similar feature in the past.
> 
> Then is it in some sort of "queue" for upcoming features or was it not feasible?

As I understand it, @zneix was in the protoyping phase when I last heard of it. Not sure what the current plans are, best wait for him to comment on it himself. ;)

**Comment by Alicyl** [comment]
> As I understand it, @zneix was in the protoyping phase when I last heard of it. Not sure what the current plans are, best wait for him to comment on it himself. ;)

-nudges @zneix with virtual stick- 👀

**Comment by zneix** [comment]
*Sees 5 GitHub notifications and starts to wonder what broke*

Yeah, I have some code implementing a way to toggle visibility of tabs with a keybinding (and optionally a button in context menu). I would have to improve it a little and it should be good to go. If that's what you want, then I'll try to continue works on this, if not - please elaborate below.

If any maintainer is reading this, feel free to assign this issue to me and I will do my best to implement this as I also want something similar in the project very badly.

**Comment by Alicyl** [comment]
> _Sees 5 GitHub notifications and starts to wonder what broke_
> 
> Yeah, I have some code implementing a way to toggle visibility of tabs with a keybinding (and optionally a button in context menu). I would have to improve it a little and it should be good to go. If that's what you want, then I'll try to continue works on this, if not - please elaborate below.
> 
> If any maintainer is reading this, feel free to assign this issue to me and I will do my best to implement this as I also want something similar in the project very badly.

Sorry, I went back to sleep after stuffing my face with more Christmas leftovers for breakfast. ;;

Yeah, that's precisely the feature I requested. ღ 

Thank you so much! Take all the time you need to improve it; I just don't want to deal with this anymore since I only have one monitor (and this is a laptop I'm using with no other space where I am to place any additional monitors for it):

![chatterino_0JqqcqhbZx](https://user-images.githubusercontent.com/13776859/103160086-80698e80-4796-11eb-8d0c-1d0a8a1e17bc.png)
