### ISSUE TITLE
Failed to deliver messages are being sent by another account after account switch

### ISSUE THREAD

**Issue by slch** [Chatterino/chatterino2#2320]
**Describe the bug**
If message is not delivered - ch2 tries to resend it later.
Then if you reconnect by switching to another account - it sends all failed messages with the new user. 
After switch to another account, failed to deliver messages should be flushed.

**To reproduce**
Not completely sure what steps to make in order for chatterino to have an unsent message queue.
Do that somehow.
Then switch accounts.
If you got the connection back, ch2 should send all messages from the account you switched to.

**Screenshots**
Will try to attach a gif later. Seem to connect properly now.

**Chatterino version**
Chatterino 2.2.3-beta2 (commit a539b821e)

**Operating system**
Arch linux
<details>

![Screenshot_20201229_133215](https://user-images.githubusercontent.com/2884941/103274137-5f917b00-49da-11eb-8847-72c9dba1f3cc.png)

</details>

**Additional information**
Encountered this after not being able to send messages on ch2 start.
Can see all new messages and history, but my messages are not delivered.

**Comment by Y0dax** [comment]
I was able to reproduce this on Windows 10.

**Comment by BIGDAWG-CUM** [comment]
yeah dawg take this out homie I keep getting temp banned from twitch cuh.

**Comment by Felanbird** [comment]
This should have been more-or-less resolved by #2850

It could still be POSSIBLE to happen, but should be extremely unlikely to happen by accident

**Comment by pajlada** [comment]
Re-open or create a new bug report if it happens again/you can recreate it
