### ISSUE TITLE
Sort channels alphabetically 

### ISSUE THREAD

**Issue by TroyDota** [Chatterino/chatterino2#2324]
**What should be added?**
Ability to sort channels alphabetically

**Why should it be added?**
So it is easier to find a channel in a long list of channels. I know about ctrl + k but sorting will allow for faster and more convenient access rather than having to press control + k each time to find a channel.

**Comment by TroyDota** [comment]
related to  #2177

**Comment by leon-richardt** [comment]
How does this differ from #2177? :stuck_out_tongue:

**Comment by RAnders00** [comment]
Duplicate of #2177
