### ISSUE TITLE
Add Ability to quickly toggle all Live Notifications while livestreaming

### ISSUE THREAD

**Issue by Praaug** [Chatterino/chatterino2#2325]
**What should be added?**

Ability to mute / unmute Live Notifications without the need to remove / add them again.

- Possibillity to toggle it in streamer mode

**Why should it be added?**

I want to be notified when people are going live. But when I'm streaming myself I want to turn off all Live Notifications so my stream is not Interrupt.

**Comment by zneix** [comment]
@Praaug would adding a toggle for Live Notifications in `General Settings -> Streamer Mode` suit your needs? I feel like this is something that would fall under this category and it can be used along with "Detect OBS" option in Streamer Mode.

**Comment by Praaug** [comment]
That would be totally fine.

I'm not 100% sure and need to test the sound muting.
But if you use desktop capture, you would still get the banner.

**Comment by zneix** [comment]
@Praaug I made a PR (#2342) for this issue. If you're on Windows, please try version from PR and let me know if it solves this (I don't trust myself that I've patched all kinds of notifications 🙂) as I can't test this because I'm on Linux.

**Comment by Praaug** [comment]
@zneix I have to setup my dev environment and get the sources. Will do it after work today and come back to you with the results

**Comment by leon-richardt** [comment]
> @zneix I have to setup my dev environment and get the sources. Will do it after work today and come back to you with the results

If you don't want to go through the hassle of setting up a dev environment, you could also download the [PR artifact](https://github.com/Chatterino/chatterino2/actions/runs/466777914) built by Github Actions.

**Comment by Praaug** [comment]
> > @zneix I have to setup my dev environment and get the sources. Will do it after work today and come back to you with the results
> 
> If you don't want to go through the hassle of setting up a dev environment, you could also download the [PR artifact](https://github.com/Chatterino/chatterino2/actions/runs/466777914) built by Github Actions.

I didn't think about that.
@zneix just testet it with 3 channels. Sound as well as Banner Notifications are not shown if the feature is enabled and OBS is running. If OBS is not running, I get the sound as well as the banner.
Works exactly like it should be.
