### ISSUE TITLE
Add "/localsub" and "/localsuboff" (from BTTV) equivalents

### ISSUE THREAD

**Issue by Cullen36** [Chatterino/chatterino2#2330]
**What should be added?**
Support for the chat commands "/localsub" and "/localsuboff" which are available with BTTV. These should either be added or an equivalent should be added. These commands allow the user to enable a local version of "Sub Only Mode", which displays only messages from subscribers of the given channel.

**Why should it be added?**
This feature is very useful with BTTV for filtering chat spam or bot messages. I would like to see it added to Chatterino 2 for the same reason.

**Comment by leon-richardt** [comment]
This can be achieved using [Filters](https://wiki.chatterino.com/Filters/) which will be available in the 2.2.3 release (and beta builds).
