### ISSUE TITLE
Unique Whispers tabs for users you choose

### ISSUE THREAD

**Issue by okaytestokaytest** [Chatterino/chatterino2#2332]
**What should be added?**
There is currently a /whispers tab which shows you all the whispers you are receiving, however, it doesn't seem like you can reply or even have a whisper tab for only a user you choose.
Just as you can open a new tab for a channel's chat, just open a whisper chat with a friend/user.

**Why should it be added?**
Twitch is so broken for me. Sometimes I can't and can send whispers to people, I can see the whispers I receive, but my replies don't go through and they don't see it. I want to believe that if whispers tab will be added to Chatterino, then I won't have to deal with the broken twitch.

**Comment by Mm2PL** [comment]
Duplicates #426. No official API from Twitch makes it pretty much impossible to implement this.

**Comment by apa420** [comment]
Twitch whispers are a total mess and there is very little support for it.
