### ISSUE TITLE
Only open the Chats in Chatterino that are live

### ISSUE THREAD

**Issue by R3LEA6Z** [Chatterino/chatterino2#2334]
a

**Comment by alazymeme** [comment]
This seems like a stupidly complicated feature for lazy individuals. If you want a feature like this, maybe try the extension.

I certainly don't think this should be added to the main build.

**Comment by SLCH** [comment]
It might make your experience better:
You can enable live indicators on tabs in ch2 settings.

Also is this proposal for visual clarity or less traffic usage?

**Comment by R3LEA6Z** [comment]
> It might make your experience better:
> You can enable live indicators on tabs in ch2 settings.
> 
> Also is this proposal for visual clarity or less traffic usage?

I dont know if its too hard for programming, Firstly i thought on less traffic usage. Visual Clarity is incidental.

**Comment by Mm2PL** [comment]
What if Helix decides to not show live status? There were situations like that before where it just decided to have extreme delay. This feature would break completely in a case like that.

**Comment by R3LEA6Z** [comment]
It doesnt even have to close the tabs. It could just disconnect from the chats and connect to them again if they come online. But for now i found a good solution for me. Now its fine for me.

**Comment by SLCH** [comment]
Not sure if anyone would implement this feature.
But you could do that easily with a small side program and chatterino cli. Program would track channels that are live and add/remove tabs in chatterino. But this is also not possible right now due to the bug #2190 .

**Comment by leon-richardt** [comment]
> But for now i found a good solution for me. Now its fine for me.

Would you mind sharing your current solution? 😃 That way, we could point people with similar requests to this issue in the future. Maybe your solution is adequate for them as well.

**Comment by R3LEA6Z** [comment]
> > But for now i found a good solution for me. Now its fine for me.
> 
> Would you mind sharing your current solution? 😃 That way, we could point people with similar requests to this issue in the future. Maybe your solution is adequate for them as well.

Its not that what i wanted completly, but i first opened all channels in one tab together and this was too full. Now i opened for 1 channel 1 tab and now i see red dots over the names. The Red Indocator. This is enough for me :)
