### ISSUE TITLE
Add a /chatters command

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2343]
**What should be added?**
Add a `/chatters` command, just shows a total of the current users in chat

**Why should it be added?**
We already have the data in chatterino, why not use it?

**Comment by sando** [comment]
This seems like an rather specific function to assign a command to. That said, I've also thought about the ability of seeing the number of chatters too when a stream is offline - perhaps it would be better to show the count in the viewer list and add a keybind/command for the dialog?

**Comment by alazymeme** [comment]
> This seems like an rather specific function to assign a command to

Fairly sure it's a bttv or ffz command, which is where the thought came from

**Comment by sando** [comment]
> Fairly sure it's a bttv or ffz command, which is where the thought came from

Ah yep, it's a BTTV command. In general, I agree that having that information available somewhere would be useful.

**Comment by TETYYS** [comment]
https://clips.twitch.tv/EphemeralBumblingBaguettePartyTime
"IT'S WEIRD" -a customer
