### ISSUE TITLE
Write connection dies and doesn't reconnect

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#2356]
**Describe the bug**
I stopped being able to write messages in chat.

This seems to me like the write connection dying, and the ping messages dying.

@pajlada add qDebug messages for when pings are sent and received and let connections be tagged READ/WRITE so we actually know which connection is sending what message

**To reproduce**
N/A

**Screenshots**

**Chatterino version**
commit a6e23e246864458c9d00c469c3b7306086b8d0ed

**Operating system**
Arch Linux btw

**Additional information**

**Comment by apa420** [comment]
Fixed by #2850
