### ISSUE TITLE
Option to Replace PogChamp with Original

### ISSUE THREAD

**Issue by vampiricwulf** [Chatterino/chatterino2#2358]
**What should be added?**
An option to use original PogChamp emote rather than the daily rotation.

**Why should it be added?**
The original one had an emotion that has failed to be conveyed by the new variants (with many clearly being made for self-promotional purposes rather than legitimate attempts at replacing the original). Since it would be client-side, it would be entirely for personal aesthetic.

**Comment by pajlada** [comment]
You can use the `Ignores` feature of Chatterino to block or replace emotes or text.
Set the `Pattern` to match the emote of your choice.
 * To block the emote, ensure `Block` is checked.
 * To replace the emote with text, ensure `Block` is unchecked and set `Replacement` with the text of your choice.
 * To replace the emote with another emote, ensure `Block` is unchecked and set `Replacement` to the code of another emote that's available in the chat. You could use another global Twitch emote, or a channel-specific emote (e.g. `KKona`)

**Comment by leon-richardt** [comment]
Relevant discussion has also been held in https://github.com/Chatterino/chatterino2/issues/2312
