### ISSUE TITLE
Can't Log in

### ISSUE THREAD

**Issue by Whaps** [Chatterino/chatterino2#2361]
When trying to log in I get an error saying it cant find my User ID. When I refresh the page the same error appears.

![image](https://user-images.githubusercontent.com/76618731/104682272-405f5100-572f-11eb-87a0-5bedb1ad188e.png)

Chatterino version: Chatterino 2.2.2-fix (commit a82f57f94)
Operating system: Windows 10

**Comment by sando** [comment]
What browser are you using to login? Can you try a different one?

**Comment by Whaps** [comment]
> What browser are you using to login? Can you try a different one? Do you have any privacy extensions installed?

Using Chrome, I'll try another.

**Comment by Whaps** [comment]
Didn't work. Same message

**Comment by Whaps** [comment]
> Do you have any privacy extensions installed?

The only 'privacy' extension I have is Ublock Origin

**Comment by Whaps** [comment]
Turns out it was my antivirus doing something. I turned it off and it worked.

**Comment by Mm2PL** [comment]
ref #487
