### ISSUE TITLE
Height of splits is not accurately loaded

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#2362]
**Describe the bug**
When having multiple splits in the same column so under another the sizes of these splits don't get saved into the config very accurately upon closing Chatterino.

Edit: They get saved correctly, Chatterino loads them and then changes them a bit for some reason and saves that new value into the config.

Maybe window size in general isn't saved very accurate either, because I think the width of my chatterino isn't saving perfectly either. 

Filters are really useful and I use vertical splits a lot with them to have little mini chats below, that's why the accurate size is important to me. Currently I resize every time I start chatterino.

**To reproduce**
Create a tab with atleast 2 splits vertically. (So in 1 column)
Adjust the size for to a very small split and wait for the layout to save. Then close and reopen chatterino.

**Screenshots**
Before closing:
https://i.imgur.com/zMunuES.png

After Closing:
https://i.imgur.com/x3ubDTu.png

**Chatterino version**
Chatterino 2.2.3-beta2 (commit d0deb44ab)

**Operating system**
Manjaro 20.2.1 with i3

**Comment by zneix** [comment]
Can confirm, I'm having the same issue on Arch Linux 5.10.7, i3 4.19

**Comment by alazymeme** [comment]
I could've sworn this was already an issue. I've been having issues with sizing resetting for ages

**Comment by gempir** [comment]
Fixed in #2554
