### ISSUE TITLE
Chatterino crashing upon open

### ISSUE THREAD

**Issue by Lifesillusions** [Chatterino/chatterino2#2363]
**Describe the bug**
chatterino attempts to load --> chatterino window opens (no text shown) --> chatterino widow closes

**To reproduce**
Not sure how to reproduce, just trying to open chatterino

**Screenshots**
https://gyazo.com/4d68780cb1f871ec4bf6ef99cc503d5a

**Chatterino version**
cannot access settings, but I have downloaded the lastest version (v2.2.2-fix)

**Operating system**
Windows 10

**Additional information**
N/A

**Comment by zneix** [comment]
There are already multiple Issues regarding chatterino crashing upon opening - #2127, #2198, #2229, #2307 and a couple closed ones I believe.
@pajlada can we close some of those to reduce useless threads and keep most relevant issue open?
@Lifesillusions please close this issue and for the future, check already existing issues before opening a new one, thanks!
