### ISSUE TITLE
Select the account to connect to a chat

### ISSUE THREAD

**Issue by JustAnotherTuga** [Chatterino/chatterino2#2364]
**What should be added?**
Instead of setting the account globally to all chat instances, it should be an option when selecting a channel do join to choose the account or anonymous login. Something like this in print screen:
![image](https://user-images.githubusercontent.com/61381714/104816806-50e9f700-5815-11eb-9404-30a219cc1dcf.png)

**Why should it be added?**
To be able to use different account logins in different chats or even connect as anonymous, so the user don't show up on the chatters list

**Comment by Mm2PL** [comment]
duplicate of #1301

**Comment by zneix** [comment]
Duplicate of #1301
