### ISSUE TITLE
Chatterino keeps closing at random

### ISSUE THREAD

**Issue by havoc19x** [Chatterino/chatterino2#2366]
**Describe the bug**
Chatterino runs just fine until it eventually just closes. I am in less than 40 channels.

**To reproduce**
Have Chatterino open (either just in the background or minimized, happens to both) and it'll eventually just close. Upon re-launching, if it was minimized at the time, it'd open into a minimized state.

**Chatterino version**
Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

**Comment by ImpalaPUA** [comment]
Happens to me too, same problem, to the point I think twitch told devs to put something in here to avoid people leaving chatterino open

**Comment by GodOfKnockers** [comment]
It happens to me as well but it's random. I only have 7 splits and it seems to do it when the program is minimized.

**Comment by pajlada** [comment]
Closing this one out since it's too generic, feel free to open a new issue if you find a pattern to the crashes or if you're able to attach a stacktrace with the crash
