### ISSUE TITLE
White column of pixels outside borders on second monitor when maximized

### ISSUE THREAD

**Issue by sugamg10** [Chatterino/chatterino2#2371]
Whenever Chatterino is open, maximized, and focused, there are about 8 white pixels that appears next to the window on the other monitor.

This can be seen below:

![Capture](https://user-images.githubusercontent.com/56144968/104862030-0beebf00-5900-11eb-94bf-00ce3870d82d.PNG)

(Those white pixels appear on the other monitor).

**Chatterino 2.2.2-fix (commit a82f57f94), Windows 10 Build 19042.746**

**Comment by alazymeme** [comment]
Please search for issues prior to making a new one in future.

Duplicate of https://github.com/Chatterino/chatterino2/issues/2205
