### ISSUE TITLE
Milliseconds timestamp format.

### ISSUE THREAD

**Issue by NotNotQuinn** [Chatterino/chatterino2#2372]
# What should be added?

An option under timestamp format to display milliseconds. 
( `00:00:00.000` & `00:00:00.000 am/pm` )
![](https://i.imgur.com/Fdd6Ypf.png)
I've seen zneix at least has a working version of something like this from the chatterino on his stream.
I would try to make this myself, but building chatterino seems like its complicated, and I only started learning C++ like a week ago
# Why should it be added?

Its useful information for people / developers making things that integrate with twitch chat, even if the typical user won't find any use for this I think I will, being able to easily see response times and compare them easily to other bots. 😃 And I like seeing information like this.  ( even though when you turn on logging this information is availible in the log files, it is very annoying to check through those )

**Comment by sando** [comment]
You can enter a custom timestamp format into that dropdown field if none of the prepopulated formats fit your needs. `hh:mm:ss.zzz` or `hh:mm:ss.zzz a` will do what you want. 

Timestamp format for reference: https://doc.qt.io/qt-5/qtime.html#toString

**Comment by zneix** [comment]
I wanted to add this myself to the master branch quite some time ago, but wasn't sure if it would be accepted, as many chatterino users often WutFace'd me in other chats for having "too nerdy shit" in my chatterino, so I assumed it's not useful, but I was wrong. Created a PR to add this :)

**Comment by zneix** [comment]
Why was this closed? there's a PR for this

**Comment by apa420** [comment]
Functionality is already in chatterino.

**Comment by alazymeme** [comment]
I believe they were asking for an option in the menu, which does not currently exist:

![image](https://user-images.githubusercontent.com/12804673/105775622-d0fd2300-5fb2-11eb-8dd0-b8f2e332a97f.png)
