### ISSUE TITLE
Filtered messages still show up in /mentions

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#2373]
**Describe the bug**
Using Filters, despite the fact that a filter properly removes the message from the chat, the message still shows up in your mentions tab if you are mentioned by it.

**To reproduce**
1. Add a filter
2. Add a highlight/mention involving that same filter
3. Have someone post a message containing said phrase
4. 🥒

**Screenshots**
![image](https://user-images.githubusercontent.com/41973452/104888124-4bd29800-593a-11eb-98a9-7762bb18bf25.png)

**Chatterino version**
cfcac99ae

**Operating system**

win10

**Comment by Felanbird** [comment]
This can be fixed by using a filter on the mentions tab as well.

`(channel.name != "hasanabi" && (message.content contains "felan"))`

**Comment by Mm2PL** [comment]
WAI IMO, a filter belongs to a split in the UI, not a channel
