### ISSUE TITLE
Open in mod view button not in hamburger menu for modded channels

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2379]
**Describe the bug**
Open in mod view button not in hamburger menu for modded channels, but is there for broadcaster channels

**To reproduce**
1. Click hamburger menu in a channel you mod, notice the button isnt there
2. Right click the streamer name bar thing and notice it's there
3. Do the same as step 1, but in your own channel - notice the button **IS** there

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/105164802-4f943380-5b61-11eb-8e38-683ddb2e7ed6.png)

![image](https://user-images.githubusercontent.com/12804673/105164821-558a1480-5b61-11eb-8a6d-c162dd8e265b.png)

**Chatterino version**
a9b1af60d

**Operating system**
Windows 10

**Comment by zneix** [comment]
Reproducible, I can fix it later.

**Comment by zneix** [comment]
Seems like I was too stupid / slow to fix it and it's been already done in #2590
