### ISSUE TITLE
Bring back an old C1 Feature "Switch username color like a rainbow after each message"

### ISSUE THREAD

**Issue by yosefsa7** [Chatterino/chatterino2#2385]
**What should be added?**

Bring back one of C1 good features "Switch username color like a rainbow after each message" ![nuuls](https://i.nuuls.com/9e8oW.png)
it should look like this  ![nuuls](https://i.nuuls.com/Yrk9O.png)

**Why should it be added?**

for fun i would say, and it really does look cool pajaCool.

**Comment by leon-richardt** [comment]
Duplicates https://github.com/Chatterino/chatterino2/issues/231.

**Comment by pajlada** [comment]
Duplicate of #231 
See https://github.com/Chatterino/chatterino2/issues/231#issuecomment-525441990
