### ISSUE TITLE
2.2.3-beta/beta2 crashes on launch

### ISSUE THREAD

**Issue by AS43G** [Chatterino/chatterino2#2392]
**Describe the bug**
Chatterino 2.2.3-beta/beta2 crashes on launch

**To reproduce**
1. Deleted cache folder as suggested by another user
2. Deleted Chatterino folder and then reinstalling 2.2.3-beta/beta2. Both crashes on launch
3. Uninstalled chatterino chrome extension

**Operating system**
macOS High Sierra Version 10.13.6

**Comment by pajlada** [comment]
Have you set up your dev environment to get me a stack trace yet?

**Comment by Felanbird** [comment]
Closing this because there's been no reply across 21 months.
