### ISSUE TITLE
White screen/Crashes on startup

### ISSUE THREAD

**Issue by StephanBruh** [Chatterino/chatterino2#2400]
**Describe the bug**
When opening chatterino, its shows a white screen for 3 seconds and then it closes it self.

**To reproduce**
1. Install chatterino.
2. Run it.

**Screenshots**
![DF8BPW](https://user-images.githubusercontent.com/19285400/105630093-46e47b80-5e47-11eb-9920-28f3bbbac7c8.gif)

**Chatterino version**
V2.2.2-fix and latest nightly.

**Operating system**
Windows 10 Pro 20H2 19042.746

**Additional information**
Tried everything from the wiki, reinstalled, tried on a different user account. Portable install.

**Comment by zneix** [comment]
Duplicate of #2127, #2198, #2229, #2307

**Comment by StephanBruh** [comment]
Decided to reinstall windows, fixed it.
