### ISSUE TITLE
Client not displaying/sending messages, even in slow chats

### ISSUE THREAD

**Issue by alvv-z** [Chatterino/chatterino2#2407]
**Describe the bug**

Messages aren"t appearing in my client and it seems they are not sending, even in slow chats.
**To reproduce**
1. Login
2. send a message
3. message doesn't display.

**Chatterino version**

Chatterino 2.2.3-beta2 (commit 055db0ccf) (also tried on stable 2.2.2)

**Operating system**

Ubuntu 20.10, Kernel 5.8.0-40-generic

**Comment by alazymeme** [comment]
I wouldn't say this is a Chatterino only issue, but more a TMI issue. See below gif of issues I've been having in webchat also:

![webchat LUL](https://i.alazymeme.com/ImplicitConvincingImage.gif)

**Comment by alvv-z** [comment]
I dont use the webchat, but yours does apper after a few seconds, no? Mine doesn't.

**Comment by leon-richardt** [comment]
Do you not see any messages at all? Neither your own nor those of other chatters?

**Comment by alvv-z** [comment]
I see the messages of others, but not my own.

**Comment by alvv-z** [comment]
I'm pretty sure they aren't being sent either because when I use bot commands they don't reply, and neither do other users.

**Comment by sando** [comment]
Just to rule out being shadowbanned - either in the channels, or site-wide - are you able to send messages through webchat, and are other users/bots able to see/respond to it?

**Comment by alvv-z** [comment]
I just checked, and I might be shadowbanned, although I wouldn't know why. I will message twitch support.

**Comment by SLCH** [comment]
Duplicate of #2356 ?

I also experience such issue every other day - on ch2 start can not send any messages. Reconnecting to chat or restarting ch2 1-3 times "solves" this problem.

Prefer to restart ch2 cause on reconnect it will send and deliver all unsent messages but you will not see them and have to try to type again to check.

**Comment by alvv-z** [comment]
Just got a response, I am shadowbanned.
