### ISSUE TITLE
Is there a way to link an imgur account to the Image Uploader?

### ISSUE THREAD

**Issue by bontalor** [Chatterino/chatterino2#2408]
**What should be added?**
If there isn't a way already, there should be a way to link an imgur account to the image uploader

**Why should it be added?**
Linking an account would be useful because you can see all of your previous posts in imgur.

**Comment by Mm2PL** [comment]
I think it is possible to do this by using OAuth tokens instead of Client-ID Authentication

**Comment by emoneyLW** [comment]
Yeah, this is possible if you put a ouath bearer token in the extra headers field. Didn't find the imgur docs useful when I did it, this guide pretty much runs you through it: https://planspace.org/2013/01/13/upload-images-to-your-imgur-account/

**Comment by bontalor** [comment]
> Yeah, this is possible if you put a ouath bearer token in the extra headers field. Didn't find the imgur docs useful when I did it, this guide pretty much runs you through it: https://planspace.org/2013/01/13/upload-images-to-your-imgur-account/

Thank you man I actually got it to work, you are a life saver.

**Comment by zneix** [comment]
As a follow-up to this issue, I made a simple website hosted [here](https://imgurauth.zneix.eu) ([source](https://gitea.ivr.fi/zneix/imgur-auth-site)) to simplify the process of obtaining Imgur Bearer Token.
If @pajlada wants to, I can polish this tool and he can host it as Chatterino, which will be followed by documentation update on the wiki with an entry linking to the page saying you can authenticate there, get the token and use it to upload photos to your Imgur account. That would ultimately close this issue.

**Comment by pajlada** [comment]
> As a follow-up to this issue, I made a simple website hosted [here](https://imgurauth.zneix.eu) ([source](https://gitea.ivr.fi/zneix/imgur-auth-site)) to simplify the process of obtaining Imgur Bearer Token.
> If @pajlada wants to, I can polish this tool and he can host it as Chatterino, which will be followed by documentation update on the wiki with an entry linking to the page saying you can authenticate there, get the token and use it to upload photos to your Imgur account. That would ultimately close this issue.

Looks good to me, I'd be down for that
