### ISSUE TITLE
VOD chat

### ISSUE THREAD

**Issue by alvv-z** [Chatterino/chatterino2#2409]
**What should be added?**

Display chat when watching a vod.
**Why should it be added?**

Would be nice to see chat during a vod.

Sorry for asking if this has already been implemented, I couldn't find any mention of it anywhere.

**Comment by Mm2PL** [comment]
Duplicate of #292 

> I couldn't find any mention of it anywhere.
That's because of @fourtf closing all out-of-scope issues in the repo.

**Comment by alvv-z** [comment]
Ok, thanks for the info.
