### ISSUE TITLE
Arabic Language issue

### ISSUE THREAD

**Issue by IlJonIl** [Chatterino/chatterino2#2414]
**Describe the bug**
Arabic language is being sent like its English from left to right but Arabic is typed from right to left 

**Screenshots**
https://i.imgur.com/wx9a7kF.png this is it is the app
https://i.imgur.com/yJ0Tmnp.png this is how it should be 

**Chatterino version**
 Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

**Comment by killertofus** [comment]
#720
