### ISSUE TITLE
Link to download OpenSSL 1.1.1h is down

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#2415]
It's 404, in BUILDING_ON_WINDOWS.md - https://slproweb.com/download/Win64OpenSSL-1_1_1h.exe

**Comment by alazymeme** [comment]
The same version is available on alternate websites: https://packages.icinga.com/windows/dependencies/
Else they don't have the `h` version of the installer (which I have no idea what it does). Only `i` or `i light`: https://slproweb.com/products/Win32OpenSSL.html

**Comment by SLCH** [comment]
Make an orphan branch in this repo and `raw.githubusercontent.com` the file?

**Comment by pajlada** [comment]
The link can be updated to https://slproweb.com/download/Win64OpenSSL-1_1_1i.exe
