### ISSUE TITLE
Chatterino logging out and settings resetting

### ISSUE THREAD

**Issue by yungrandd** [Chatterino/chatterino2#2425]
Seems to happen almost randomly, tried reinistalling and clearing settings folder in appdata, not sure what is the issue.

**Comment by Mm2PL** [comment]
Please use the issue template:
```md
​<!-- **Before opening a bug report, please check out the help page of the Chatterino wiki for possible common issues. https://wiki.chatterino.com/Help** -->

**Describe the bug**
<!-- A clear and concise description of what the bug is. -->

**To reproduce**
<!-- Steps to reproduce the behavior -->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. Use the integrated uploader of the issue form to upload images, or copy an image to the clipboard and paste it in the input box -->

**Chatterino version**
<!-- Copy the version information from the "About" page in the Settings, e.g. `Chatterino 2.1.4 (commit 35c7853c4, 16.09.2019)` -->

**Operating system**
<!-- E.g. Windows 10 -->

**Additional information**
<!-- If applicable, add additional context. -->
```
Without steps to reproduce no one will be able to fix the issue.

**Comment by leon-richardt** [comment]
If anything, it sounds like it could be a permission issue. Maybe a more experienced Windows user can give pointers on how to investigate this further. For starters, I would try running the application as an administrator.

**Comment by fabianzimber** [comment]
I have the same issue, it happend multiple times, after restart.
Had tons of highlights, pings and stuff setup and was logged in.
Usally it worked everything right but this time it was resetted.

Is it possible, that there is a relation between not properly shutting down Chatterino and resetting the settings?

The last days it never reset, i always shut down my pc properly.
Yesterday i shut the pc down via pressing the button, so chatterino wasn't closed by windows shutdown.

**Comment by yungrandd** [comment]
Running as adminstrator didnt help, the exact same issue as the user above describe occured as i restarted my PC too.
 Im using 2.2.3 beta, win10 OS, but chatterino version seems to not affect the issue.

**Comment by apa420** [comment]
Chatterino occasionally saves it's settings to the settings.json file. If you forcefully (or not forcefully (unsure how windows does it )) turn off your pc while chatterino didn't finish writing to the file it's left blank. You can delete the current settings.json file and rename one of the settings.json.bkp- files to just settings.json and you should have your old setup back. (Keep in mind the settings.json.bkp do frequently update so don't wait too long. To avoid this close chatterino.exe before turning off windows.

I'm unsure if there's a real fix to this. Except maybe in ui load backup settings.
Created issue #2751 for it.
