### ISSUE TITLE
chat function

### ISSUE THREAD

**Issue by C9Chris** [Chatterino/chatterino2#2431]
**What should be added?**
hey guys, awesome work. Would it be possible to add a feature that would react on statements from the chat? e.g. someone writes in the chat: "hello" and my chat would automatically react on the hello with a message like "hello, how are you?", but i don't want to use a command for that, it should be done automatically.

**Why should it be added?**
This would allow me to respond to some chat messages automatically without additional bots etc. For me this would be a big relief but I don't know how hard it is to implement such a function.

**Comment by zneix** [comment]
I'm pretty sure it duplicates some other issue (which I can't find at the moment) that has been closed and it was advised to rather use a chat bot or something similar.

**Comment by TETYYS** [comment]
Chatterino is not a chat bot project

**Comment by apa420** [comment]
You could add your own command 

![](https://i.nuuls.com/vL2bk.png)

so you simply have to type `/h`.

**Comment by C9Chris** [comment]
>  but i don't want to use a command for that

just saying ^^

**Comment by alazymeme** [comment]
> > but i don't want to use a command for that
> 
> just saying ^^

Chatterino is a chat client, not a chatbot. If you want features that resemble that of a chatbot, then I suggest you use a chatbot. Fossabot can do exactly what you are asking, I suggest you check it out: https://fossabot.com/

**Comment by C9Chris** [comment]
> > > but i don't want to use a command for that
> > 
> > 
> > just saying ^^
> 
> Just saying that chatterino is a chat client, not a chatbot. If you want features that resemble that of a chatbot, then I suggest you use a chatbot. Fossabot can do exactly what you are asking, I suggest you check it out: https://fossabot.com/

Thank you very much!

**Comment by dijikul** [comment]
> > > but i don't want to use a command for that
> > 
> > 
> > just saying ^^
> 
> Chatterino is a chat client, not a chatbot. If you want features that resemble that of a chatbot, then I suggest you use a chatbot. Fossabot can do exactly what you are asking, you should check it out: https://fossabot.com/

Realistically, why can't chatterino be both?  mIRC had a proficient scripting language that allowed for such customization on IRC; imagine what Chatterino _could_ be, with similar.

**Comment by Felanbird** [comment]
> Realistically, why can't chatterino be both? mIRC had a proficient scripting language that allowed for such customization on IRC; imagine what Chatterino _could_ be, with similar.

Because the main function of Chatterino is connecting to a single website, not all IRC servers, we don't want to be the vehicle of possible abuse against Twitch.

**Comment by dijikul** [comment]
>  not all IRC servers, we don't want to be the vehicle of possible abuse against Twitch.

Thank you - that had not been in my mind as a consideration.
