### ISSUE TITLE
Load settings backup in ui

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#2433]
**What should be added?**
A way to load a backup of settings if something goes wrong in the ui.

**Why should it be added?**
Sometimes settings in chatterino get reset without user interaction and you have to load a backup. Some users don't know these backups exist and how they work.

sidenote:
An ability to load a file as settings so you could share chatterino configuration.

**Comment by leon-richardt** [comment]
Isn't this basically a duplicate of #1989? Or am I missing something?
