### ISSUE TITLE
Highlight mute for a certain period of time

### ISSUE THREAD

**Issue by MPH2210** [Chatterino/chatterino2#2445]
I would like to suggest a timeout button for highlight sounds (and taskbar flashes) for a certain time, like i.e. WhatsApp has. Either with given values like whatsapp, or a custom timer, or both.

Especially when in online meetings, I often run Chatterino in the background and get distracted by ping sounds once in a while, and disabling the sound manually would need you to enable them by hand again.

Would be a nice QOL feature.

**Comment by leon-richardt** [comment]
Might not be quite what you want, but in recent nightly builds, you have the option to mute highlight sounds in Streamer Mode. So, when you're in a meeting, you could just enable Streamer Mode to not be bothered by pings.

**Comment by MPH2210** [comment]
Oh, I didn't know that! It really does exactly what I suggested, just under a different name. Thanks!

**Comment by pajlada** [comment]
Closing this for now - feel free to open a new issue if you feel like this is still needed.
