### ISSUE TITLE
Copying selection adds an extra space at the end

### ISSUE THREAD

**Issue by TroyKomodo** [Chatterino/chatterino2#2449]
**Describe the bug**
Copying a selection of text with control + c adds a space at the end of the selection

**To reproduce**
Copy any text 

**Chatterino version**
2.2.2-fix

**Operating system**
Windows 10

**Additional information**
Not sure if intended or bug, but I find it annoying

**Comment by TranRed** [comment]
Also happens when using all copy options from the context menu
