### ISSUE TITLE
Option to respect windows internal light and dark mode and switch accordingly

### ISSUE THREAD

**Issue by SmaltParrot50** [Chatterino/chatterino2#2452]
Enable a mode to automatically switch from Light to Dark Mode according to the system setting. I have a neat little app called Auto Dark Mode which automatically switches the Windows setting to Dark mode I use it in conjecture with Dark Reader to automatically enable Dark Mode on the websites I visit, but it doesn't affect the Chatterino Browser Extension and I have to manually switch the theme every time.

**Comment by japie06** [comment]
I second this request for the chatterino desktop program.

**Comment by ALazyMeme** [comment]
> I second this request for the chatterino desktop program.

Please don't make comments that essentially +1 the issue. Please just leave a 👍🏻 reaction on the post.

**Comment by Brog33** [comment]
I would like to see this working on Linux as well. Many Linux apps now has a "System default" when it comes to switching between dark and light modes.

**Comment by Nerixyz** [comment]
Qt 6.5 will support `QStyleHints::colorSchemeChanged` and `QStyleHints::colorScheme` ([Blog post](https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5#the-qt-65-way)) on Windows. As #4393 enabled building on Qt 6, one could add a `System` theme (when Chatterino was built with Qt 6.5 or later). Note that only _building on Qt 6_ is supported, and that there are still visible differences to Qt 5.

**Comment by Mm2PL** [comment]
Blocked until we switch to Qt >= 6.5.
