### ISSUE TITLE
Regex matching filters are not working

### ISSUE THREAD

**Issue by revolter** [Chatterino/chatterino2#2455]
**Describe the bug**

**To reproduce**

Create a filter using the content `message.content match r"\d\d"` (took directly from [the official documentation](https://wiki.chatterino.com/Filters/#simple-matching)).

**Screenshots**

![image](https://user-images.githubusercontent.com/5748627/107858722-65360980-6e3e-11eb-80ad-58da02a51815.png)

**Chatterino version**

Chatterino 2.2.3-beta2 (commit 6499b7c12)

**Operating system**

macOS Big Sur 11.2 (20D64)

**Additional information**

**Comment by dnsge** [comment]
Regex filters were merged into master in 5a29198, while you are only on 6499b7c. I think that the nightly build should include regex filters.

**Comment by revolter** [comment]
Yes, it works in the nightly versions.
