### ISSUE TITLE
Crash upon adding and removing a channel in "Selected Channels"

### ISSUE THREAD

**Issue by piboky** [Chatterino/chatterino2#2465]
**Describe the bug**
There is a crash upon adding and removing a channel in the "Selected Channels" section of Live Notifications.

**To reproduce**
Open settings -> Live Notifications -> Selected Channels.

Click "add", then click on the newly added "channel", then click Remove. The program will instantly close.

**Screenshots**
![image](https://user-images.githubusercontent.com/75762419/108544325-ea407900-72ab-11eb-9a10-bb2347b22804.png)
Clicking on "Remove" crashes the program.

**Chatterino version**
Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

**Additional information**
This was a relatively fresh install, may only happen on blank lists?

**Comment by sando** [comment]
Already fixed in 1ec109748f715cc0150bfd4e75326371a9d82dc5, you can either remove the entries manually in `settings.json` or update to beta/nightly

**Comment by pajlada** [comment]
Please let me know if you encounter the issue after updating to the latest nightly version by reopening the issue
