### ISSUE TITLE
"Clip created!" message not picked up by filter

### ISSUE THREAD

**Issue by Slopz** [Chatterino/chatterino2#2470]
**Describe the bug**
Filter picks up "Creating clip..." message, but not "Clip created! Copy link to clipboard or edit it in browser. "
Weirdly enough it picks it up as a system message without message.content filter, but not with it.

**To reproduce**
(flags.system_message) && (message.content) contains ("clip")
or
(flags.system_message) && (message.content) contains ("created")

**Screenshots**
![image](https://user-images.githubusercontent.com/39817415/108607231-6c6d9200-73bf-11eb-8a77-d7a7698e238d.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 277289db5, )

**Operating system**
Win 10

**Comment by zneix** [comment]
I also noticed that basically all the messages built with `MessageBuilder` functions are not "findable", example: https://github.com/Chatterino/chatterino2/tree/master/src/providers/twitch/IrcMessageHandler.cpp#L699

**Comment by zneix** [comment]
Why was this closed?
