### ISSUE TITLE
Lint CMake files

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#2474]
**What should be added?**
A linter that ensures our cmake files are linted/formatted properly (or consistently at least)

https://github.com/cheshirekow/cmake_format was linked by @AnotherFoxGuy

**Why should it be added?**
Because having strict formatting in files is good. Good reason! xD

**Comment by Mm2PL** [comment]
What is the reason for closure?

**Comment by pajlada** [comment]
To clarify, I don't think there's much value in the formatting of the cmake files. Linting would be useful, but the linter is basically a formatter that just tells you things aren't formatted properly.
If there's a linter available that gives us actual warnings for things we do wrong, I'd be happy to have that implemented still, but it's not something I want to have an open issue for

**Comment by AnotherFoxGuy** [comment]
There is also https://github.com/BlankSpruce/gersemi which allows you to check and format CMake files
You can also make it a git pre-commit hook: https://github.com/BlankSpruce/gersemi#pre-commit-hook
