### ISSUE TITLE
Chatterino not working on Windows Insider build. 

### ISSUE THREAD

**Issue by al11588** [Chatterino/chatterino2#2475]
When I do a fresh install and launch Chatterino in Windows Insider build 21318 it crashes at launch. 

**To reproduce**
I click on the chatterino that I installed and it crashes. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5453240/108636507-a2f4ec80-7453-11eb-9e24-c7103d62ad1a.PNG)
![Capture1](https://user-images.githubusercontent.com/5453240/108636515-b3a56280-7453-11eb-87e7-21bcb8017659.PNG)

**Chatterino version**
Chatterino 2.2.2-fix older and newer versions. In addition, nightly builds.

**Operating system**
Windows Insider build 21318

**Comment by sando** [comment]
Not quite a dupe, but related to #2323, specifically this [comment](https://github.com/Chatterino/chatterino2/issues/2323#issuecomment-771941698) onwards

**Comment by al11588** [comment]
Same issue on the new Windows 10 build 21322 #2323 with the [comment](https://github.com/Chatterino/chatterino2/issues/2323#issuecomment-771941698) 
![Capture](https://user-images.githubusercontent.com/5453240/109108014-b8db0980-7700-11eb-8b29-127794c68c6e.PNG)
![Capture1](https://user-images.githubusercontent.com/5453240/109108017-b8db0980-7700-11eb-833f-69afb99fa311.PNG)

**Comment by Tornhelm** [comment]
It's not a fix, but you can run 1.3 if you don't mind missing out on most of the emotes. Not sure why, but the crash at launch is only affecting the 2.x versions of Chatterino.

**Comment by al11588** [comment]
> It's not a fix, but you can run 1.3 if you don't mind missing out on most of the emotes. Not sure why, but the crash at launch is only affecting the 2.x versions of Chatterino.

I don’t want to loss the ability of seeing most of the emotes.

**Comment by al11588** [comment]
So the newest build Windows 10 build 21327 isn't working for it. 
![Capture](https://user-images.githubusercontent.com/5453240/109924589-81cf9f80-7c8e-11eb-8ce2-a2b7bcd99044.PNG)
![Capture2](https://user-images.githubusercontent.com/5453240/109924590-82683600-7c8e-11eb-92a4-e89ec258eff5.PNG)

**Comment by mueller-alex** [comment]
I'm getting the same issue but Chatterino 2.1.0 seems to mostly work for me (there's some weird look to the windows but everything else works fine).

**Comment by al11588** [comment]
> 
> 
> I'm getting the same issue but Chatterino 2.1.0 seems to mostly work for me (there's some weird look to the windows but everything else works fine).

Yea, you are correct. Hopefully the fix the newest version.

**Comment by al11588** [comment]
The newest version and the nightly version don't work for Windows 10 build 21332. 
![Capture](https://user-images.githubusercontent.com/5453240/110899154-96cfb280-82ce-11eb-9e38-ab523943fdeb.PNG)

**Comment by NeelAPatel** [comment]
Can confirm, didn't work in 21332 either. 
@fourtf any updates on the stuff you mentioned in #2323  (2nd comment)

**Comment by al11588** [comment]
It doesn't work on Windows 10 build 21337.
![Capture](https://user-images.githubusercontent.com/5453240/111898004-971c2c00-89f9-11eb-9a55-878a5b558265.PNG)

**Comment by ADHDDamien** [comment]
Good news to anyone suffering this! Well I hope anyways... I decided to try to build Chatterino2 myself on Insider Build 21313 with the Chatterino2 version 2.2.3-beta2  with the latest commit being #2550 following the guide [here exactly](https://github.com/Chatterino/chatterino2/blob/master/BUILDING_ON_WINDOWS.md) and the build runs without any crashes! No longer does ucrtbase.dll haunt the program, it seems as long as you build Chatterino on an Insider build then it works fine, but any version not built on Insider crashes instantly as reported above and in other issues.

Hopefully this helps anyone else struggling and maybe helps narrow down the problem a bit more.

**Comment by Tornhelm** [comment]
Can someone else test Chatterino on Build 21354? I just got this build and 2.2.3-beta2 nightly (commit  3cfeab6ba) is working on it properly again.

**Comment by ADHDDamien** [comment]
> Can someone else test Chatterino on Build 21354? I just got this build and 2.2.3-beta2 nightly (commits [3cfeab6](https://github.com/Chatterino/chatterino2/commit/3cfeab6ba73563021efbafe49ba4e2435a12eac8) & latest [c9f62fe](https://github.com/Chatterino/chatterino2/commit/c9f62fed4c0d5f9134b9e5ad96eb287eeb0063e5)) is working on it properly again.

Can confirm the 2.2.3-beta2 nightly works for me on insider build 21313 ! I am extremely happy to no longer have to build my own version.

**Comment by alazymeme** [comment]
Oh it's probably a windows issue? Big surprise 🙄

**Comment by alazymeme** [comment]
Based on the thread above, I don't think we should hold any support for insider builds whatsoever. It's incredibly difficult to fix a program on an unstable build of Windows that seems to work on every other stable build of Windows.

**Comment by sando** [comment]
Can confirm that Chatterino works on latest Insider dev channel builds - tested on 10.0.21364.1 with Chatterino Nightly 2.3.0 (commit 2db140d5a). Given the affected Windows builds are effectively depreciated in the dev channel, this issue can be closed.

**Comment by zneix** [comment]
I will close this for now as it seems that Chatterino works on insider builds. @al11588, feel free to reopen the issue if this is still occuring.
