### ISSUE TITLE
Claiming of channel point chest in client

### ISSUE THREAD

**Issue by iFrgot** [Chatterino/chatterino2#2476]
**What should be added?**
Ability to claim channel point chest in chatterino client.

**Why should it be added?**
Adding this feature would allow me to claim chests without having to go onto twitch directly.

**Comment by alazymeme** [comment]
This is not possible due to API limitations. In addition, there have been multiple issues about this that have also been closed. Please search for issues prior to opening one.

**Comment by Mm2PL** [comment]
impossible. dupe

**Comment by pajlada** [comment]
Duplicate of #1455
