### ISSUE TITLE
Twitch emotes do not display properly when following 2 or 3 spaces.

### ISSUE THREAD

**Issue by NotNotQuinn** [Chatterino/chatterino2#2479]
**Describe the bug**

Some messages don't show twitch emotes, or show the first letter of them as well as the emote, in specific circumstances.

**To reproduce**

Send a message that has 2 or 3 spaces before a global emote.

Some examples:
```
two spaces  Kappa 
three spaces   Kappa 
chat, they removed   Jebaited PepeHands
```

**Screenshots**

Linux Ubuntu v20.04 Chatterino2.2.2-fix:
![Linux](https://i.imgur.com/Uoe2oLH.png)
Windows 10 2.2.3-beta2 (commit a4fb20c72): 
![Windows](https://i.imgur.com/2Zqlmql.png)

**Additional information**

Twitch removed Jeb󠀀aite󠀀d ![PepeHands](https://cdn.frankerfacez.com/emote/231552/1)

**Comment by alazymeme** [comment]
This appears to be related to messages sent from Chatterino. If you type a similar message in webchat, it looks normal. First one typed in Chatterino, second one typed in webchat:

![image](https://user-images.githubusercontent.com/12804673/108973052-adbbb580-76cf-11eb-965d-e4cd25e00ad8.png)

**Comment by zneix** [comment]
Related to #1707 (?)
