### ISSUE TITLE
Streamer Mode toggle by chat command such as /streamer

### ISSUE THREAD

**Issue by rumpoldbumbersnudge** [Chatterino/chatterino2#2487]
**What should be added?**
A command in chat to toggle Streamer Mode On/Off
**Why should it be added?**
User would not have to open settings to toggle Streamer Mode. Automatic setting is undesirable because it keeps Streamer Mode on when OBS is running but not streaming.

**Comment by IMNdi** [comment]
Commands that are more than macros seem like a good idea in general. 

Would certainly free up some fiddling with settings window and cascaded menus. Say, clearing chat. Reconnecting. Toggle Always on top. These would be useful if using Chatterino as on-stream chat. Trigger streamlink to reconnect the video.

**Comment by pajlada** [comment]
While the command might be useful, I'm afraid we would deprecate it in favour of some more generic 'set setting' command too soon.

Please checkout the newly created issue #2635 and give your feedback so we know how to proceed with the functionality.

This would be further useful with the soon-to-be-merged PR #2632
