### ISSUE TITLE
Automatically create new AUR release on pushing to master

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#2491]
**What should be added?**
A GitHub action for pushing code to Arch Linux's AUR on every push to master branch, just like with nightly releases.

**Why should it be added?**
A certain someone won't have to remember about reminding certain someone to run a certain script, so certain Arch Linux nerds won't have to wait "ages" for a chatterino release on their bleeding-edge system.

**Comment by SLCH** [comment]
I have a console history thing for ch2 and streamlink.
On yay --aur up arrow it installs latest -git packages.

**Comment by pajlada** [comment]
Some work has been done on the chore/aur-push branch, we are currently waiting for our AUR user **chatterino2-ci** to be added as a contributor to the **chatterino2-git** AUR package before we can continue.

**Comment by pajlada** [comment]
Fixed in #2499

**Comment by micwoj92** [comment]
@zneix Either I misunderstand you or you have 0 idea how AUR vcs packages work. Changes are only needed when the build process changes, no need to bump pkgver every commit, pkgver function in PKGBUILD already does that. Please either provide a valid reason for this change or delte that CI. Thank you.

**Comment by pajlada** [comment]
Currently being handled in https://github.com/Chatterino/chatterino2/discussions/2736
