### ISSUE TITLE
MacOS CI attempts to use Qt6

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2494]
`macos-latest` builds use `qt6` as the default which is not supported. Now Qt5 also seems to do this
https://github.com/Chatterino/chatterino2/runs/2035040185?check_suite_focus=true

~~https://github.com/Chatterino/chatterino2/pull/2340/checks?check_run_id=2032889985~~

@pajlada

**Comment by pajlada** [comment]
Looking into this now - my plan is to remove the "default" qt version and just always specify a version.
