### ISSUE TITLE
It is possible to have two commands named the same

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2497]
**Describe the bug**

You can have two commands named the same string of characters, which is confusing.

**To reproduce**

  1. Add a command (`/test123`)
  2. Add another one with the same name but different output
  3. Observe that the first command in the list will get executed and the second one won't.

**Screenshots**

![2021-03-05_14-31](https://user-images.githubusercontent.com/25011746/110122135-20efb680-7db7-11eb-8078-f745cfce075e.png)
![2021-03-05_14-31_1](https://user-images.githubusercontent.com/25011746/110122132-20572000-7db7-11eb-822a-90dba0f37ebf.png)

**Chatterino version**

Chatterino Nightly + Dankerino patches 2.2.3-beta2 (commit 3a589589) based on upstream b2aa3700

**Operating system**

Ubuntu 20.04.01

**Comment by jammehcow** [comment]
Can reproduce, Chatterino 2.3.4 (commit [baeec59a](https://github.com/Chatterino/chatterino2/commit/baeec59a)). Will look into adding validation before a command is saved/cell is unfocused
