### ISSUE TITLE
[Feature] Toggle capitalisation of channel tab titles

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#2513]
**What should be added?**
Sometime after release `2.2.2-fix` the titles of tab names included capital letters of the channel names. Originally these were all lowercase. It would be great if a toggle could be added in settings to revert this so channel names displayed as all lowercase.

Original behavior:
![Chatterino2_TabTitles_CaseInsensitive](https://user-images.githubusercontent.com/4962764/110720281-32e1b700-8206-11eb-9599-0c2471715e06.png)

New behavior:
![Chatterino2_TabTitles_CaseSensitive](https://user-images.githubusercontent.com/4962764/110720556-b56a7680-8206-11eb-9afe-dde53026080b.png)

**Why should it be added?**
It could be deemed annoying for users who are used to the lowercase format.

I'm interested in implementing this if nobody gets to it first - would be nice to get used to the codebase. A personal peeve of mine but not world-ending.

**Comment by pajlada** [comment]
The change just changes the default naming of the tabs, you could always rename the tab yourself by right-clicking the tab and choosing the rename option. I understand this means an extra step if you want to ensure the tabs are named fully lowercase (or in whatever case you enter the channel), but adding an option for a minimal feature such as this is not something I see us wanting to add.

If you are fine with my reasoning, please go ahead and close this issue, otherwise leave it open and we can discuss it further!

**Comment by jammehcow** [comment]
Sorry, meant to respond yesterday.

I get that it's a tiny feature for something very nitpicky but it's a change in behaviour that users can't opt out of.
It might help me more if you could give me the reason behind the change? It slightly breaks that experience for users who are so used to the lowercase tab names.

For example today I switched someone onto a nightly build due to #2055 and the first comment was about the tab changes. It would be nice for it to be a toggle - ideally opt-in. Just my thoughts and I get your side of it.

**Comment by leon-richardt** [comment]
Context for this change: #2172, #2189 (also see discussion therein). As I see it, the main reason for the change stems from the fact that display name and login name may differ drastically in more than just capitalization (e.g. with Korean or Japanese names).

I'm also going to give my perspective on changes like these. Similar "concerns" have already been raised over the addition of features like the [split input placeholder text](https://github.com/Chatterino/chatterino2/pull/2143). I think Chatterino should move away from [making every little thing customizable](https://github.com/Chatterino/chatterino2/issues/1956). Instead, reasonable basic behavior should be preferred.

Not only is it harder to support and properly maintain every possible settings combination, but it would also alleviate the complexity of the settings menu in the application. See for example the "Miscellaneous" section:
![Settings page](https://user-images.githubusercontent.com/35232120/110925714-d07ed880-8323-11eb-853f-f6420e3027f6.png)
(Again, see #1956 for discussion on this.)
 
In this particular case, there even is a low-effort workaround: Renaming the tab title as one sees fit, like @pajlada suggested.

**Comment by jammehcow** [comment]
A good read and that all makes sense. Closing.
