### ISSUE TITLE
Emote menu snapping to top left, unable to move

### ISSUE THREAD

**Issue by MomsSpag** [Chatterino/chatterino2#2516]
When selecting the emote menu (when Chatterino is either full-screen to pinned to a side of my screen), the emote menu pops up and sticks to the top left of my screen. I'm unable to move it as it very quickly pings back as soon as I release M1. This has only been an issue that I've notice since I've upgraded my main monitor to 1440p, although might just be weird timing. It also snaps on my secondary monitor which is 1080p. 

![image](https://user-images.githubusercontent.com/23405694/111035913-7c075600-8414-11eb-9142-e679bc46b56d.png)

Version: Chatterino 2.2.2-fix (commit a82f57f94)

**Comment by apa420** [comment]
I also have this issue

**Comment by pajlada** [comment]
Should have been resolved by https://github.com/Chatterino/chatterino2/pull/4797
