### ISSUE TITLE
Make unicode emotes not trigger when used without spaces

### ISSUE THREAD

**Issue by emredesu** [Chatterino/chatterino2#2518]
**What should be added?**
Unicode emotes should only trigger when they are typed independently. Currently typing "a:cheese_wedge:b" causes Chatterino to send "a 🧀 b". That should not be the case as the user did not add those spaces.

**Why should it be added?**
Normal Twitch emotes do not trigger when they are used inside a word, for example typing "Kappa123" does not trigger the emote Kappa. This should be handled the same way in Chatterino for the sake of consistency. It can also cause some inconvenience, for example typing `std::thread::join` in chat results in message "std: 🧵 :join ", which is not what is intended at all.

**Comment by pajlada** [comment]
In Discord and GitHub comments this is solved by wrapping the text in backticks (`:joy:`), however we don't have rich formatting so I don't think that would make sense for us as a solution.

How is this handled in BetterTTV or FrankerFaceZ (if at all)?

**Comment by emredesu** [comment]
Ah, I thought this was a Chatterino specific thing, I didn't even realize that my post had the same error at the time of writing. After testing out on bunch of other platforms, I found out that it seems that this is the common way of how unicode emotes work, so there is no point in changing how it works in Chatterino.
