### ISSUE TITLE
Quickswitcher (CTRL+K) results aren't sorted by tab order

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#2519]
**Describe the bug**
When opening the quickswitcher and typing a channel name in, if I have the channel open in two tabs I expect the order of the options in the quickswitcher to be sorted by which tab comes first.

**To reproduce**
Open two tabs **bbb** and **aaa**
In **bbb**, open channel pajlada
In **aaa**, open channel pajlada

Press CTRL+K, type in pajlada.
Options will be listed like this:
pajlada (in tab **aaa**)
pajlada (in tab **bbb**)

**Screenshots**

**Chatterino version**
https://github.com/Chatterino/chatterino2/commit/7002954aa953cc68ed532d20f876250ff31f07cd

**Operating system**
N/A

**Additional information**

**Comment by leon-richardt** [comment]
Preferably, the `Notebook` class could provide a sorted list of `SplitContainer`s. That way all components iterating through `SplitContainer`s can rely on a consistent order,

**Comment by jammehcow** [comment]
@leon-richardt Sorted as in the user's personal arrangement of tabs, right? Might pick this up.

**Comment by leon-richardt** [comment]
> Sorted as in the user's personal arrangement of tabs, right?

I think that would make the most sense, yeah.

When implementing this, you might have to take care what happens with the order when users rearrange their tabs and how that interacts with window layout serialization. Not sure if it's actually going to be a problem but that could be a pitfall I would be on the look-out for

**Comment by pajlada** [comment]
Fixed in #2561
