### ISSUE TITLE
Moderation messages not shown in popup chats

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2520]
**Describe the bug**
When having a chat open as a popup, moderation messages are not seen

**To reproduce**
1. Open a chat
2. Click burger menu > popup
3. Time someone out with a message
4. Notice there's no message shown

**Screenshots**
Popup chat:
![xd](https://i.alazymeme.com/ComparableSatisfiedImage.png)

Normal chat:
![xd2](https://i.alazymeme.com/GreenDifferentImage.png)

**Chatterino version**
Nightly 2.2.3-beta2 (commit efde73e68)

**Operating system**
Windows 10

**Comment by IS2511** [comment]
Fixed by the waves of time?
Chatterino 7.3.5 (commit d2e9c105)

![Screenshot at 2022-05-10 06-57-42](https://user-images.githubusercontent.com/23707032/167540024-8df5e72d-33b7-49a5-ae7d-d2484800c23a.png)

**Comment by Felanbird** [comment]
> Fixed by the waves of time? 

Looks that way.
![image](https://user-images.githubusercontent.com/41973452/167540802-c032f8cb-5749-421d-a80f-b84a2c8720f0.png)
