### ISSUE TITLE
Highlight New Users

### ISSUE THREAD

**Issue by simon-crsshr** [Chatterino/chatterino2#2525]
It would be cool if there would be added a feature to highlight users which are new to Twitch.

It would be really practical for mods, so they can have an extra eye on those users.

**Comment by jammehcow** [comment]
This would require a lookup for each individual user in each channel (or at least the modded ones). Feels like too much network activity; especially in large channels.

**Comment by simon-crsshr** [comment]
As I know it is possible to directly read it out of the user ID, that's how it works with FFZ.

**Comment by Mm2PL** [comment]
You either have to do a network request to know the account's age or use the fact that user IDs are sequential and painfully do the math on how fast new accounts appear. Then you can get a rough estimate of when the user account was created. I'm sorry, but I don't think this is worth the effort.

**Comment by apa420** [comment]
mm2pl's reasoning

**Comment by zneix** [comment]
Also seems like a duplicate of #1784
