### ISSUE TITLE
Clip in '/mentions' crashes app

### ISSUE THREAD

**Issue by EgrorBs** [Chatterino/chatterino2#2527]
**Describe the bug**
Chatterino crashes when I trying make clip in '/mentions' panel

**To reproduce**
1) Open Chatterino
2) Open & select '/mentions'
3) Press Alt+X
4) Crash

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 49bd1bd48, )

**Operating system**
Windows 10 Pro x64 (19042.804)

**Comment by alazymeme** [comment]
Can confirm
Windows 10
efde73e68
