### ISSUE TITLE
macOS Open AppData dir broken

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#2531]
Clicking the "Open AppData directory" button does nothing on macOs Big Sur (and previous versions as well).

Should open finder at `$HOME/Library/Application Support/chatterino`

**Comment by jammehcow** [comment]
Can reproduce on `macOS Catalina 10.15.5` with chatterino `2.2.3-beta2 (commit 6499c7c12)`.

Cache folder link works correctly.

**Comment by jammehcow** [comment]
Happy to pick this one up as I have a working macOS environment.
