### ISSUE TITLE
IRC - Issue joining channels starting with ## instead of #

### ISSUE THREAD

**Issue by jeremgod** [Chatterino/chatterino2#2535]
Enabled Experimental feature in options (restarted chatterino after enabling) - able to join the server/channel

Issue: Not seeing messages from the +newsly user (bot)
Functional: Seeing other users joining the channel however (green square)

![image](https://user-images.githubusercontent.com/15100569/111341201-ad1f9a80-864f-11eb-998a-c5920c08df2a.png)

On the right is what should show up after I join the channel (using kiwiirc.com)

Troubleshooting steps attempted:
- Tried to connect to 6667 without SSL
- Tried different build (Today's nighly)
- Tried ###news because Chatterino seems to drop one of the "#" in the title thought it might be related
- Tried "/join ##news" in the "Send IRC commands on connect:" field -> got error saying not supported or something

Using Windows 11 Pro Version 21H2 Build 22000.100

Steps to reproduce

1. Enable IRC Feature
2. Restart Chatterino
3. Select Irc (Beta) Tab Or Create New Split (Ctrl+T) then select Irc Tab
4. Add Server
5. Fill information with the following 
     Host: irc.libera.chat
     Port: 6697
     SSL: ✓
6. Pick unique User Name
7. Click OK
8. Once server is added put "##news" in "Channel:" field
9. Click OK

Edit 08/03/2021 6:41PM EST: Updated the comment to reflect newsly having moved to irc.libera.chat

**Comment by jeremgod** [comment]
Updated to latest Nightly - issue still present

**Comment by Mm2PL** [comment]
This is a general bug with channels starting with `##` instead of `#`.
