### ISSUE TITLE
Messages from read connection are dropped in some cases

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#2546]
**Describe the bug**
Messages from the read connection seem to be dropped in some cases. Not sure if there is anything we can do about this.

**To reproduce**
Not sure if it's deterministically reproducible.

**Chatterino version**
Commit b02403a7d

**Operating system**
Arch Linux 5.11.7-arch1-1, although this would hardly be relevant

**Additional information**
What it looked like for me:
![image](https://user-images.githubusercontent.com/35232120/111867194-c3409a00-8972-11eb-9650-6d8b5532b072.png)

Corresponding log entries from [justlog](https://logs.ivr.fi/channel/pajlada/2021/3/20):
```
[2021-03-20 10:45:48] #pajlada zneix: oh pepeLaugh
[2021-03-20 10:46:00] #pajlada alazymeme: I have an emote for them to add
[2021-03-20 10:46:03] #pajlada zneix: I know he used to have it, but I don't follow nymn at all really
[2021-03-20 10:46:09] #pajlada flex3rs: ppSlide
[2021-03-20 10:46:10] #pajlada supibot: flex3rs just got up: pepeZ 💤 (10h, 49m ago)
```

Another report of (likely) the same issue:
![image](https://user-images.githubusercontent.com/35232120/111867324-7d380600-8973-11eb-94b8-a0f7ae5835bc.png)

**Comment by apa420** [comment]
I don't think there's anything we could do to not have this happen except maybe have two irc read connections, but that would be a stupid fix. Should be 100% on twitch's end.
