### ISSUE TITLE
(Linux?) Inline emote picker shows when pressing cancel in settings window

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#2551]
**Describe the bug**
After a user has used the inline emoji/emote picket (when typing `:emoteName`) and they've opened the settings window twice, pressing cancel will cause the box to show up again.

**To reproduce**
 1. Open up chatterino
 2. Go to a channel you have permissions to type in
 3. Use the `:` emote picker and enter an emote name
 4. Press enter/use arrow keys to select & send emote
 5. Open up the settings window
 6. Click on a sidebar action (e.g. `External Tools` or `Highlights`)
 7. Click cancel (not Ok)
 8. Repeat steps 6 & 7

The emote picker box from step 3 should who again. It doesn't have any real function as selecting anything in it doesn't insert into the text box. You can also render another emote picket over the top.

**Screenshots**
Here's a recording of it happening on latest master.
https://user-images.githubusercontent.com/4962764/111885134-c6ad4300-89bd-11eb-8dc5-7051d4e91be5.mp4

**Chatterino version**
This bug has also been replicated on `2.2.2-fix`
Chatterino 2.2.3-beta2 (commit b02403a7d)

**Operating system**
Arch Linux, Linux Zen `5.11.7.zen1-1`, BSPWM using picom

**Additional information**
I've had people try to replicate on Windows 10 and I've tried on macOS but couldn't be replicated. Would be good to have another Linux user ( @leon-richardt ?) to test if it's Linux in general or just my WM/compositor.

**Comment by Melonify** [comment]
I can confirm that this issue is observed on Arch Linux using Gnome Shell under X

**Comment by Mm2PL** [comment]
duplicates #1892

**Comment by jammehcow** [comment]
Closing in favour of #1892
