### ISSUE TITLE
Clicking on a mentioned user within someone's usercard does not work 

### ISSUE THREAD

**Issue by Caldohhh** [Chatterino/chatterino2#2555]
**Describe the bug**
When clicking on someone's username to bring up their usercard then clicking on a mentioned users name within the recent messages does not work.

**To reproduce**
-Click on a users name to bring up their usercard
-In their recent messages click on a username they mentioned in their recent messages 
-Then the usercard box should disappear 

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 1f5b62e6e, )

**Operating system**
Windows 10

**Comment by zneix** [comment]
I believve this is the same situation as in #2297, thus this is a duplicate issue.

**Comment by Caldohhh** [comment]
👍 I'll close it
