### ISSUE TITLE
Nightly Release AppImage not launching on Debian

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#2557]
My system is Linux stable Debian Buster x86_64. I usually run `./Chatterino-x86_64.AppImage --appimage-extract` before using the application to insert the nightly modes file.

The AppImage output from bash is:
```
benny@debian:~/.local/bin/Chatterino/usr/bin$ ./chatterino 
./chatterino: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./chatterino)
./chatterino: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/benny/.local/bin/Chatterino/usr/bin/../lib/libpulse.so.0)
./chatterino: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/benny/.local/bin/Chatterino/usr/bin/../lib/libpulsecommon-13.99.so)
./chatterino: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /home/benny/.local/bin/Chatterino/usr/bin/../lib/libsystemd.so.0)
./chatterino: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/benny/.local/bin/Chatterino/usr/bin/../lib/libsndfile.so.1)
./chatterino: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/benny/.local/bin/Chatterino/usr/bin/../lib/libFLAC.so.8)
```

Chatterino version is 1f5b62e6e5e631fa3ce2d6139fa8251a5b466c59. Previous AppImage that i downloaded and worked on my system was f53b0a9e0f262c9a2350575eb60c1a6924527ebc, i don't know if it can help. Also, i don't know if i have to just suck it up because i use Debian and so new things tend to break; right now i am using the older CMake build AppImage which works fortunately.

**Comment by Felanbird** [comment]
2021 issue and we have `.deb` builds now (tho they are technically build for Ubuntu, they'll work on debian)`
