### ISSUE TITLE
Add a open channel when you right click a sub emote.

### ISSUE THREAD

**Issue by Seanc26** [Chatterino/chatterino2#2558]
**What should be added?**
When you right click a bttv/ffz emote there is a link to open the page. It would be handy when you right click a sub emote you get a link for the twitch channel.

**Why should it be added?**
If you like a sub emote you can easily go to the channel its from.

**Comment by sando** [comment]
There's already a link to twitchemotes.com in the context menu for sub emotes in nightly, which links to the associated channel in most cases (see #2214). Is this not sufficient?

**Comment by Seanc26** [comment]
Thanks 👍
