### ISSUE TITLE
Ease of use from emotes window

### ISSUE THREAD

**Issue by dapperdap** [Chatterino/chatterino2#2560]
Although emotes are opened on another window, the main chatterino window must still be in focus in order to send the emote in chat. My feature request to to allow both typing and sending for emotes to be allowed from the emote window. As soon as you click on a emote to auto-fill it the textbox, pressing enter, while the emote window is still up, will allow the message to be sent

This is just another way chatterino can be a high quality substitute from the twitch native chat client. I simply want to allow a faster and easier chatting experience for my viewers ass well, and this would go a long way in making that happen. Thank you.

**Comment by jammehcow** [comment]
Not sure if this is needed (I might not understand the issue) as you can either type + tab complete emotes in the chat input or type a `:` followed by some of an emote name to find it. Let me know if this still doesn't cover your feature.

**Comment by dapperdap** [comment]
Yeah, that also covers the issue. I guess i making a case for those who didnt even know the spelling of emotes, but this also solves the problem. Thanks again for the assist.

**Comment by jammehcow** [comment]
If there's nothing left to add to this could you close this issue? Cheers!
