### ISSUE TITLE
Badges not showing (MacOS Big Sur) 2.2.3-beta2 

### ISSUE THREAD

**Issue by jaytreble** [Chatterino/chatterino2#2562]
Subscriber, VIP, Mod and Bit badges not showing up on MacOS Big Sur. Running version 2.2.3-beta2

**Comment by jammehcow** [comment]
Is this issue ongoing or was it a one-off?

**Comment by jaytreble** [comment]
> Is this issue ongoing or was it a one-off?

On going. Even tried a complete reinstall. Seems all twitch badges are not showing up.

**Comment by zneix** [comment]
This could be an issue with connection to Twitch's CDN. Could you try changing your DNS serevr / restarting your network / checking if you can actually find a route to https://badges.twitch.tv/v1/badges/global/display?language=en

**Comment by jaytreble** [comment]
> This could be an issue with connection to Twitch's CDN. Could you try changing your DNS serevr / restarting your network / checking if you can actually find a route to https://badges.twitch.tv/v1/badges/global/display?language=en

this worked! I wonder if it was my VPN causing the issue... I changed some settings and it came up fine. thanks! :)
