### ISSUE TITLE
Make Chatterino available through the Homebrew package manager (macOS)

### ISSUE THREAD

**Issue by spoergsmaal** [Chatterino/chatterino2#2567]
**What should be added?**
I think it would be great if people were able to install Chatterino on macOS through the [Homebrew package manager](https://brew.sh/).

**Why should it be added?**
Making Chatterino available through the Homebrew package manager would make installing and updating the software as simple as possible (e.g. by running "brew install --cask chatterino" in terminal), and would prevent users from being faced with an update prompt when they launch the application after a while of no use, since Chatterino would automatically get updated whenever the user runs "brew upgrade" in terminal.

**Comment by jammehcow** [comment]
Would it make sense to leave the update popup in but just disable the functionality? That way the user is still alerted but the install is still managed by homebrew.

Would be nice to get this into homebrew - I do agree!

**Comment by leon-richardt** [comment]
I don't think anyone would be opposed to this. For example, Chatterino is already packaged for Fedora, FreeBSD, and Windows (via Chocolatey).
I believe the biggest blocker to this would be finding someone that is willing to own and maintain the package over a long period of time.

**Comment by jammehcow** [comment]
Might be worth seeing how much can be automated. Happy to do some initial work on it but as a non-mac user I'm not sure I'd be the person to own it.

**Comment by jammehcow** [comment]
Associated PR for homebrew cask (stable):
https://github.com/Homebrew/homebrew-cask/pull/102847

**Comment by jammehcow** [comment]
Cask has been merged. Currently offers 2.2.3-beta2 on macOS.

**Comment by spoergsmaal** [comment]
thank you!!
