### ISSUE TITLE
When opening a modified emote's TwitchEmotes link the page can't be found

### ISSUE THREAD

**Issue by MrAuro** [Chatterino/chatterino2#2568]
**Describe the bug**
The TwitchEmotes.com link says "Sorry, the page you are looking for could not be found." when opening a modified emote.

**To reproduce**
Right click and open the TwitchEmotes link of a modified emote

**Screenshots**
Modified emote, pokeWICKED with the horizontal flip modification:
![image](https://user-images.githubusercontent.com/35087590/112709658-be5b7900-8e91-11eb-92d7-92a2fcab2340.png)
Opening the TwitchEmote link gives this error:
![image](https://user-images.githubusercontent.com/35087590/112709705-febaf700-8e91-11eb-8be3-1e6cd7d6c156.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 1f5b62e6e)

**Operating system**
Windows 10

**Additional information**
Removing the modification addon like `_HF`  from the URL works fine
![image](https://user-images.githubusercontent.com/35087590/112709756-65d8ab80-8e92-11eb-95ae-5772b2e46c19.png)

**Comment by jammehcow** [comment]
Can reproduce in `Chatterino 2.2.3-beta2 (commit 1f5b62e6e)`. Note that this is an issue with TwitchEmotes themselves as it doesn't seem like they store modifications (understandably). I wonder if it's worth just sending the user to the base emote's page for now? Thoughts @pajlada @fourtf ?

**Comment by pajlada** [comment]
### Message posting the pajaW sub emote
`@badge-info=subscriber/63;badges=broadcaster/1,subscriber/3060,partner/1;color=#CC44FF;display-name=pajlada;emote-only=1;emotes=80481:0-4;flags=;id=3fc46182-c105-4666-8af5-60a1aa7adcef;mod=0;room-id=11148817;subscriber=1;tmi-sent-ts=1616937942185;turbo=0;user-id=11148817;user-type= :pajlada!pajlada@pajlada.tmi.twitch.tv PRIVMSG #pajlada :pajaW`

### Message posting the pajaW sub emote with the sunglasses emote modifier
`@badge-info=subscriber/63;badges=broadcaster/1,subscriber/3060,partner/1;color=#CC44FF;display-name=pajlada;emote-only=1;emotes=80481_SG:0-7;flags=;id=feb420da-e42e-4fa1-bf9e-cced8d0d3b6f;mod=0;room-id=11148817;subscriber=1;tmi-sent-ts=1616937943809;turbo=0;user-id=11148817;user-type= :pajlada!pajlada@pajlada.tmi.twitch.tv PRIVMSG #pajlada :pajaW_SG`

### Message posting the pajaPants bit emote
`@badge-info=subscriber/63;badges=broadcaster/1,subscriber/3060,partner/1;color=#CC44FF;display-name=pajlada;emote-only=1;emotes=emotesv2_56124b6ee48c47778de1a922e93d7848:0-8;flags=;id=f7d415ac-f088-4577-9bc6-a91b280a2ffc;mod=0;room-id=11148817;subscriber=1;tmi-sent-ts=1616937999027;turbo=0;user-id=11148817;user-type= :pajlada!pajlada@pajlada.tmi.twitch.tv PRIVMSG #pajlada :pajaPants`


Note the various emote keys in use right now:
 * `80481`
 * `80481_SG`
 * `emotesv2_56124b6ee48c47778de1a922e93d7848`

Any sort of "trying to be smart" parsing from our end will most likely not hold the test of time, so the way I see it there's not much we can do
