### ISSUE TITLE
Sounds from chatterino won't play without `pulseaudio-qt` package on Arch Linux

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#2577]
Opening this issue since I've got myself a very barebones, fresh Arch installation and tried building from source while following docs in the repo. While I've configured audio properly for all other apps, chatterino couldn't play my highlight sounds due to `pulseaudio-qt` package not being installed.
I am asking whether we should we add this to building docs or make a wiki entry about it since not everyone builds from source, but they might be missing the package.

**Comment by apa420** [comment]
If this is an issue for arch linux it's going to affect the aur package since that one does build chatterino from scratch afaik. So it should also be included in the aur package.

**Comment by pajlada** [comment]
Need to investigate this a bit further since this is not a package I have installed on my Arch Linux install btw

**Comment by apa420** [comment]
Also as a comment I don't have pulseaudio installed at all on my arch installation (I might have the pulseaudio-qt package though).
But I do get the sound from notifications (iirc).
I run JACK + Alsa

**Comment by vhns** [comment]
I wasn't able to reproduce the issue on a fresh arch linux installation, both with plain ALSA and PulseAudio and building with both cmake and qmake.
I am assuming you are not using pipewire, sndio or jack.

@apa420 could you do a 

```pacman -Q pulseaudio-qt```

to check whether you have pulseaudio-qt installed?

**Comment by pajlada** [comment]
```sh
$ pacman -Q pulseaudio-qt
error: package 'pulseaudio-qt' was not found
```

and my audio works

**Comment by jammehcow** [comment]
Also unable to reproduce. I don't have `pulseaudio-qt` installed on my main install and can hear highlights just fine.

**Comment by apa420** [comment]
Close this? this feels like your audio setting might be scuffed and has nothing to do with chatterino?

**Comment by zneix** [comment]
Perhaps you're right. I'll try reinstalling arch again and reopen if I see it occurring.
