### ISSUE TITLE
add ability to enable desktop notifications for highlights

### ISSUE THREAD

**Issue by 0Supa** [Chatterino/chatterino2#2578]
like those ![FeelsDankMan](https://cdn.betterttv.net/emote/5d6209854932b21d9c333195/1x)
![image](https://i.nuuls.com/spKDt.png)

**Comment by jammehcow** [comment]
Should also have a toggle on a per-highlight basis for this. Would reduce spam for users who have word-like names.

As for the layout I'd assume it would be as follows:
Title: #channel-name
Subtext: user + message truncated

**Comment by apa420** [comment]
Duplicate of #398
