### ISSUE TITLE
"Try to find usernames without @ prefix" makes trailing punctuation bold

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#2593]
**Describe the bug**
When typing a username (such as `jammehcow`) suffixed by punctuation characters (like exclamation points), the punctuation characters are made bold along with the username.

**To reproduce**
Using chatterino after commit `b79d5fa`:

Type your username followed by some punctuation: `jammehcow!!!!!!!!`. Trailing punctuation will appear bold.
Punctuation should not be bold but username should still match.

**Screenshots**
![Chatterino2_jammehcow_BoldPunctuation_223b2](https://user-images.githubusercontent.com/4962764/113553146-623fe400-964b-11eb-813c-d944494d0e8f.png)

**Chatterino version**
Chatterino 2.2.3-beta2 `(commit f9246a9e3)`

**Operating system**
Arch Linux, linux-zen `5.11.11.zen1` (none of which is relevant) 

**Additional information**
Appears to be introduced as part of #2212. I guess it could be considered expected behavior but I feel that clicking on `jammehcow!!!` shouldn't open a usercard of a different name. Obviously having those characters is impossible, still from a UX view that's disconnected.

**Comment by Mm2PL** [comment]
Also of note if you have colored usernames enabled the color will apply to the punctuation too.
![2021-04-05_13-29](https://user-images.githubusercontent.com/25011746/113569538-36e4d700-9602-11eb-9bc7-084c802ff708.png)
