### ISSUE TITLE
chat box zoomed in when in 4K resolution

### ISSUE THREAD

**Issue by yungsoul2100** [Chatterino/chatterino2#2598]
![image](https://i.imgur.com/6sqx4nZ.png)

**Comment by jammehcow** [comment]
Could you please follow the template provided in the issue template? See [ISSUE_TEMPLATE/bug_report.md](https://github.com/Chatterino/chatterino2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) if you don't wish to open a new issue.

**Comment by alazymeme** [comment]
This is probably a duplicate of any of the issues linked here: https://github.com/Chatterino/chatterino2/issues?q=is%3Aissue+is%3Aopen+dpi

**Comment by apa420** [comment]
Duplicate of #749
