### ISSUE TITLE
Opening a user history/popup will remove notification for going live

### ISSUE THREAD

**Issue by dpoetzschke** [Chatterino/chatterino2#2610]
**Describe the bug**
When clicking on a user to open chat history/user profile the twitch notification settings will disable.
ie. you follow Summit1g and have notifications for him going live enabled the notification settings will be disabled for his channel when you open said popup.

**To reproduce**
Follow a streamer and enable notifications. 
Check https://www.twitch.tv/settings/notifications -> "Per Channel" if it is enabled
Open popup within Chatterino and go refresh twitch settings (F5) notifications are now disabled for said user

**Screenshots**
![chatterino_bug](https://user-images.githubusercontent.com/16013351/114277486-b243ef80-9a2b-11eb-834c-e6e862bd4281.png)

**Chatterino version**
Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

**Comment by Yoitsu** [comment]
Can reproduce on commit https://github.com/Chatterino/chatterino2/commit/a82f57f94387c8bfc7b8826216fad1253be7cb40 but not on master

Can you try a nightly build (https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) and see if it still happens?

**Comment by TranRed** [comment]
does not happen on nightlies in my experience

**Comment by dpoetzschke** [comment]
Can confirm, seems to be fixed with the nightly.

**Comment by zneix** [comment]
Just for short explanation, this was caused due to an old bug which caused re-following someone every time you open a usercard of a user you're already following (the tickbox updating triggered the follow event, which, by default, was a follow with no notifications). Got fixed along while migrating block methods in #2370

**Comment by dpoetzschke** [comment]
Since this issue is fixed with the next release, i'm closing this issue.
Thanks for the explanation @zneix
