### ISSUE TITLE
Messages do not send

### ISSUE THREAD

**Issue by budwheizzah** [Chatterino/chatterino2#2612]
I open the app, with my Twitch account bound. The tabs I had opened reload and connect. From thereon, none of the messages i type and send ever make it. I need to close and restart the app several times before it finally works, akin to playing a lottery.

**Comment by Mm2PL** [comment]
- Please use issue templates.
- This is a known twitch issue, there is currently no known workaround or way to detect this
- rel or dupe #1831

**Comment by apa420** [comment]
Closing in favor of #2614
