### ISSUE TITLE
Write connection on startup doesn't always work

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#2614]
**Describe the bug**

When starting chatterino I sometimes am not able to send messages in chat and if I restart chatterino it *might* fix it. I get history messages and whatever, but am not able to send messages, waiting some time does not resolve this.

**To reproduce**

Open chatterino.
Try to write in chat -> doesn't send anything.

**Chatterino version**

This happens on basically latest using arch linux as well as `Chatterino Nightly 2.2.2 (commit 3be62c929, )` on windows.

**Operating system**

Windows 8.1 and arch linux.

**Additional information**

Related #1831, #2612

**Comment by pajlada** [comment]
Without investigating, one thing that might be able to break this is if a user sends a message on the write connection before it has been fully connected/authenticated

**Comment by apa420** [comment]
can confirm that is also the case, but even waiting some min before sending it doesn't work

**Comment by apa420** [comment]
Duplicate of #2425

**Comment by apa420** [comment]
Duplicate of #2356
Oops wrong issue sorry

**Comment by apa420** [comment]
Accidently linked wrong issue... Sorry.
