### ISSUE TITLE
Twitch emotes don't work in whispers

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#2616]
**Describe the bug**
Upon sending an emote in a twitch whisper it doesn't appear in chatterino.

**To reproduce**
Recive a whisper with a Twitch emote in it (doesn't matter if it's global emote or sub emote)

**Screenshots**
Chatterino
![chatterino](https://cdn.zneix.eu/L52VctW.png)

Webchat
![webchat](https://cdn.zneix.eu/O43xZjz.png)

**Chatterino version**
49e30e64 and a893cdaeb

**Operating system**
Arch GNU/Linux (btw)

**Additional information**
It's on twitch's end, broken even in DankChat. Opening an issue to prevent further duplicates.

**Comment by Mm2PL** [comment]
Twitch is returning emote id 0 in whispers:
> #pajlada Mm2PL: _mb.eval msg.flags.get('emotes') # :) 
> 1:35-36 

> mm2pl -> mm_sutilitybot: _mb.eval msg.flags.get('emotes') # :) 
> Mm_sUtilityBot -> mm2pl: 0:35-36 

What the fuck twitch

**Comment by zneix** [comment]
Opened a twitchdev issue related to this issue: twitchdev/issues/issues/367

**Comment by iProdigy** [comment]
Note: the whispers pubsub topic does not appear to have this bug

**Comment by zneix** [comment]
Twitch seems to have fixes this issue, closing.
