### ISSUE TITLE
"$" in ignore regex causes Chatterino to stop responding

### ISSUE THREAD

**Issue by MrAuro** [Chatterino/chatterino2#2617]
**Describe the bug**
Having `$` in an ignore's regex causes Chatterino to stop responding

**To reproduce**
- Add a new ignore
- Set the pattern to `$`
- Tick the regex box

**Screenshots**

![image](https://user-images.githubusercontent.com/35087590/114337288-e2b88600-9b1e-11eb-8211-75772b30cf3f.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit e00938d, )

**Operating system**
Windows Ten

**Comment by jammehcow** [comment]
Can reproduce in Arch Linux (linux 5.11.12-zen) using Chatterino 2.2.3-beta2 (commit 24a33709e).

**Comment by jammehcow** [comment]
Also noted that an ignore of `^` using regex produces 3 asterisks at the start of every message.
![Chatterino_jammehcow_startOfLineRegexIgnore](https://user-images.githubusercontent.com/4962764/114347807-aab25100-9bb9-11eb-85f2-a620c5f87f7d.png)

**Comment by zneix** [comment]
> Also noted that an ignore of `^` using regex produces 3 asterisks at the start of every message.

I think this is expected behavior, since every line has a line beginning.

**Comment by zneix** [comment]
Following also causes chatterino to freeze:
![](https://cdn.zneix.eu/8yHohwz.png)

**Comment by jammehcow** [comment]
> Following also causes chatterino to freeze:

Exactly what I tried and got 3 asterisks on latest. I'm wondering if we just blacklist those when used by themselves?

**Comment by Yoitsu** [comment]
After checking with gdb, it's due to this while loop never terminating: https://github.com/Chatterino/chatterino2/blob/c9f62fed4c0d5f9134b9e5ad96eb287eeb0063e5/src/providers/twitch/TwitchMessageBuilder.cpp#L860
