### ISSUE TITLE
Messages from yourself that get caught by AutoMod don't show up in chat at all (it doesn't even tell you it was caught).

### ISSUE THREAD

**Issue by AustinHolderr** [Chatterino/chatterino2#2626]
#  **Describe the bug:**  #
**Messages from yourself that get caught by AutoMod don't tell you that they were OR show up at all in the Chatterino chat client.**

#  **To reproduce:**  #
**Have a message get caught by AutoMod.**

#  **Screenshots:**  #

**Not Applicable.**

#  **Chatterino version:**  #
**Chatterino 2.2.3-beta2 (commit 59afb2b1c)**

#  **Operating system:**  #
**macOS Big Sur Version 11.2.3**

<img width="450" alt="macOS Big Sur Version 11.2.3" src="https://user-images.githubusercontent.com/44728118/114466671-c9fbaf00-9bb6-11eb-9070-0496852e2128.png">

#  **Additional information:**  #
**It should at least tell you that it was caught by AutoMod like it does in the native chat client. It doesn't even tell you that, and just doesn't post anything to chat.**

**Comment by Mm2PL** [comment]
Do you see who timed out users and the reasons? I suspect that your PubSub connection broke (#1022)

**Comment by NYISLANDERFAN** [comment]
what do you mean? i'm talking about in channels where you're not a mod, if a message gets caught by AutoMod, it doesn't tell you your message was caught, nor does it say anything about it in chat, nor does it post it.

**Comment by Mm2PL** [comment]
I misread the issue, sorry. 

Rel: #1710

**Comment by NYISLANDERFAN** [comment]
I don't see that issue being related to this one.

**Comment by Mm2PL** [comment]
That issue is related because automod can drop messages kinda like the TMI bugs described there.

**Comment by jammehcow** [comment]
I don't believe this relates to the TMI bugs. This just seems like chatterino not handling when AutoMod catches a message. Currently there is no output so it *appears* like no message was sent. Definitely a feature.

**Comment by NYISLANDERFAN** [comment]
> I don't believe this relates to the TMI bugs. This just seems like chatterino not handling when AutoMod catches a message. Currently there is no output so it _appears_ like no message was sent. Definitely a feature.

### **agreed.** ###

**Comment by jammehcow** [comment]
Ignore me, this **is** a bug. I wasn't aware AutoMod messages were handled because I've never seen the message show up when message conflicts with AutoMod. Tested and finally saw the AutoMod message.

Related to the #1710

**Comment by NYISLANDERFAN** [comment]
> Ignore me, this **is** a bug. I wasn't aware AutoMod messages were handled because I've never seen the message show up when message conflicts with AutoMod. Tested and finally saw the AutoMod message.
> 
> Related to the #1710

what's the related?

**Comment by NYISLANDERFAN** [comment]
have any chatterino developers seen this?

**Comment by zneix** [comment]
> have any chatterino developers seen this?

yes

**Comment by NYISLANDERFAN** [comment]
> > have any chatterino developers seen this?
> 
> 
> 
> yes

is it being looked in-to?

**Comment by Mm2PL** [comment]
> is this being looked into?

Yes

There is no notice from TMI that indicates a message is being held by automod

**Comment by NYISLANDERFAN** [comment]
> > > have any chatterino developers seen this?
> > 
> > 
> > 
> > yes
> 
> is it being looked in-to?

@zneix

**Comment by Mm2PL** [comment]
We (open source developers) have lives too, don't you know? We'll get to fixing the issue when we get to it.

**Comment by AustinHolderr** [comment]
> We (open source developers) have lives too, don't you know? We'll get to fixing the issue when we get to it.

sorry.

**Comment by zneix** [comment]
It's alright, however I don't think there's much we can do about it at this point. As Mm2PL mentioned, it's an issue with TMI (Twitch Messaging Interface) not giving us any response back.

**Comment by AustinHolderr** [comment]
> It's alright, however I don't think there's much we can do about it at this point. As Mm2PL mentioned, it's an issue with TMI (Twitch Messaging Interface) not giving us any response back.

that's unfortunate :/

**Comment by apa420** [comment]
I might be wrong but isn't the "Your message has be caught by AutoMod" a pubsub message?
Considering other AutoMod messages are done with pubsub this might be the case here.
The pubsub connection might have dropped for one reason or another (it's very unreliable) so it might that.

**Comment by zneix** [comment]
> I might be wrong but isn't the "Your message has be caught by AutoMod" a pubsub message?
> Considering other AutoMod messages are done with pubsub this might be the case here.
> The pubsub connection might have dropped for one reason or another (it's very unreliable) so it might that.

Haven't had a look into pubsub, if anyone smarter than me with pubsub knows something about it please lmk.

**Comment by iProdigy** [comment]
> > I might be wrong but isn't the "Your message has be caught by AutoMod" a pubsub message?
> > Considering other AutoMod messages are done with pubsub this might be the case here.
> > The pubsub connection might have dropped for one reason or another (it's very unreliable) so it might that.
> 
> Haven't had a look into pubsub, if anyone smarter than me with pubsub knows something about it please lmk.

Yes;

`{"type":"MESSAGE","data":{"topic":"chat_moderator_actions.53888434.53482260","message":"{\"type\":\"moderation_action\",\"data\":{\"type\":\"chat_targeted_login_moderation\",\"moderation_action\":\"automod_message_rejected\",\"args\":[\"ogprodigy\"],\"msg_id\":\"44ede2ad-c88e-4038-baee-1ae049437fff\",\"target_user_id\":\"53888434\",\"target_user_login\":\"\"}}"}}`

**Comment by apa420** [comment]
Are these pubsub messages sent when you are a normal viewer in a chat or a mod?
Afaik the automod pubsub messages only show up if you are a mod/broadcaster.

**Comment by Mm2PL** [comment]
> Are these pubsub messages sent when you are a normal viewer in a chat or a mod?
> Afaik the automod pubsub messages only show up if you are a mod/broadcaster and this issue is about the normal user.

Chat moderator actions are sent to normal users if they are the target of the action, that's how viewing your own timeout reasons works. So maybe this could work too.

**Comment by iProdigy** [comment]
> Are these pubsub messages sent when you are a normal viewer in a chat or a mod?
> Afaik the automod pubsub messages only show up if you are a mod/broadcaster and this issue is about the normal user.

The example messages above *are* fired for normal users

& you're correct that the pubsub messages recieved do vary whether you are a mod or not. For example, instead of `automod_message_rejected`, mods recieve `automod_rejected`, which includes more data in `args`: `{"type":"MESSAGE","data":{"topic":"chat_moderator_actions.493418343.53482260","message":"{\"type\":\"moderation_action\",\"data\":{\"type\":\"chat_login_moderation\",\"moderation_action\":\"automod_rejected\",\"args\":[\"ogprodigy\",\"shit\",\"profanity\"],\"created_by\":\"\",\"created_by_user_id\":\"\",\"created_at\":\"\",\"msg_id\":\"44ede2ad-c88e-4038-baee-1ae049437fff\",\"target_user_id\":\"53888434\",\"target_user_login\":\"ogprodigy\",\"from_automod\":false}}"}}`

**Comment by apa420** [comment]
I'll take a look at this as well while I'm at it I guess

**Comment by AustinHolderr** [comment]
@apa420 thank you for your hard work into fixing this issue 💛 i appreciate it
