### ISSUE TITLE
Custom VIP Badges (New FrankerFaceZ Feature)

### ISSUE THREAD

**Issue by SirStendec** [Chatterino/chatterino2#2627]
**What should be added?**
Hello, friends! Yesterday, FrankerFaceZ added a feature that allows broadcasters to set a custom image for VIP badges in their chat. Example:
![image](https://user-images.githubusercontent.com/14036657/114814775-e77d7400-9d82-11eb-9694-3b687994aeaf.png)

These custom badges work like a normal Twitch custom badge, such as sub badges. Just a total image replacement, no background colors or anything like the special way FFZ handles mod badges.

If a channel has a custom VIP badge, there will be URLs for the badge in the APIv1 room response from FrankerFaceZ. For example, from https://api.frankerfacez.com/v1/room/sodapoppin we see:

```json
{
	"room": {
		"id": "sodapoppin",
		...
		"vip_badge": {
			"1": "//cdn.frankerfacez.com/room-badge/vip/sodapoppin/1",
			"2": "//cdn.frankerfacez.com/room-badge/vip/sodapoppin/2",
			"4": "//cdn.frankerfacez.com/room-badge/vip/sodapoppin/4"
		},
		...
	}
}
```

In a channel with no custom VIP badge set, `vip_badge` will be `null`. Additionally, if users don't supply a high enough resolution image, `2` or `4` may be null to indicate their absence. In the future, we'll have our CDN just upscale things on demand, but that isn't happening yet so please don't rely on behavior like that.

**Why should it be added?**
I personally think Twitch should've let people customize their VIP badges from the start, but since they didn't, FFZ is here to help. I believe adding support for this to many different clients will help present a more unified experience to Twitch users, and that is worth it.

Thanks!

**Comment by zneix** [comment]
@SirStendec just wondering why is there no object in the API response as `moderator_badge` which is either string or null. You instead return `vip_badge` which is either a string or an object of strings, which is quite inconsistent.
