### ISSUE TITLE
Username highlights and emotes bug.

### ISSUE THREAD

**Issue by CycIoneTM** [Chatterino/chatterino2#2630]
**Describe the bug**
Usernames highlights are taking prio over emotes.

**To reproduce**
Spam an emote with some that has the same user name as that emote.

**Screenshot**
![](https://i.imgur.com/DBghqhq.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 0a0cfb8e4, )

**Operating system**
Windows 10

**Comment by jammehcow** [comment]
Fixed in nightly/2.3.0 (#2479, #2490)

**Comment by zneix** [comment]
Duplicate of #2479, update to latest nightly.
