### ISSUE TITLE
`/setgame` matching "too loose"

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#2636]
**Describe the bug**
Helix is sometimes horribly incorrect for game titles. This can potentially result in something like `/setgame terraria` actually setting the game to `Sub Terrania` or `Terraria 2`.

**Potential Solution**
Converting game titles from the previous search to lowercase, then best matching according to that. For example...

Below is the response from helix for searching for the game. If we were to convert the game titles to lowercase and compare the user's input to the game titles, we'd find that it best matches to id `31376` as opposed to just matching to the first entry.
![image](https://user-images.githubusercontent.com/12804673/115114822-9369ce00-9fd4-11eb-8727-a1df82cfb4b3.png)

**EDIT**: This issue is actually in reference to the already added `/setgame` feature. Currently it doesn't match some games exactly. The fix to this would be to convert the query to lowercase, search for the game, see which game best matches and use the id to set the game.

**Comment by jammehcow** [comment]
Picking this up.
