### ISSUE TITLE
Disabling Color @username does not disable already colored usernames, unlike Bold @username

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2637]
**Describe the bug**
Disabling Color @username does not disable already colored usernames, unlike Bold @username

**To reproduce**
1. @ yourself
2. turn off the "Color @username" in the settings.
3. color of previous @ usernames does not change.

**Chatterino version**
Chatterino 2.3.0 (commit 58017a754)

**Operating system**
Windows 10 64-Bit

**Comment by Mm2PL** [comment]
Please use issue templates

**Comment by karl-police** [comment]
> Please use issue templates

okay
