### ISSUE TITLE
chatterino native host crashes on most chats and when tabbing in and out it crashes chatterino frequently

### ISSUE THREAD

**Issue by madstingray16** [Chatterino/chatterino2#2640]
cahtterino native wont even load/ crashes instantly on some channels, also crashes a lot when tabbing in and out of twitch when native is active, this problem has become worse with the 2.3.0 update

**Comment by Mm2PL** [comment]
Bugs to do with the Chatterino Native Host / browser extension go in [this repo](https://github.com/chatterino/chatterino-browser-ext)

**Comment by zneix** [comment]
First of all, please use issue templates. Second of all (as mm2pl) has mentioned, issues related to chatterino browser extension should be reported under the repo he linked.
