### ISSUE TITLE
Unfollow confirmation for Chatterino's usercard

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2645]
**What should be added?**
A unfollow confirmation for Chatterino's usercard. Twitch added it aswell and Chatterino does't have it.

**Why should it be added?**
So that people don't mistakly hit that checkbox and unfollow. It is important, see https://twitch.uservoice.com/forums/923383-creators-and-stream-features/suggestions/10197198-get-a-warning-to-follow-and-unfollow-someone

**Comment by jammehcow** [comment]
Being implemented in #2629

**Comment by zneix** [comment]
Duplicate of #1886
