### ISSUE TITLE
Show an indicator in tab for channels casting reruns

### ISSUE THREAD

**Issue by auxtinn** [Chatterino/chatterino2#2648]
#  **Describe the bug:**  #
**Reruns should show up in Chatterino like being live does. When a channel is live it says “(live)” next to the channel name in the title bar, whereas on a Rerun it should not show the channel as being offline, and rather it should say “(rerun)” next to the channel name.**

#  **To reproduce:**  #
**Start or have a rerun going on a channel and go to said channel on Chatterino.**

#  **Screenshots:**  #

<img width="1279" alt="Chatterino Rerun Issue 1" src="https://user-images.githubusercontent.com/44728118/115334202-f42a0f80-a168-11eb-8bea-0a6e2630a1d2.png">

<img width="250" alt="Chatterino Rerun Issue 2" src="https://user-images.githubusercontent.com/44728118/115334466-70245780-a169-11eb-9626-55589b12f28f.png">

#  **Chatterino version:**  #
**Chatterino 2.3.0 (commit 2db140d5a)**

#  **Operating system:**  #
**macOS Big Sur Version 11.2.3**

<img width="450" alt="macOS Big Sur Version 11.2.3" src="https://user-images.githubusercontent.com/44728118/114466671-c9fbaf00-9bb6-11eb-9070-0496852e2128.png">

#  **Additional information:**  #
**View above notes on this issue. Thank you.**

**Comment by jammehcow** [comment]
Not a bug. Reruns technically aren't live.

As for indicating that a rerun is happening in a title `(rerun)` would probably be fine.
Will also need to think about the indicator as using red convinces the user the channel is live when it isn't.

Blue dot instead of red as to not draw the user's attention as much as a live indicator?

![Chatterino_NotebookTab_LiveIndicator](https://user-images.githubusercontent.com/4962764/115338315-b4aa0480-a1f6-11eb-8d9e-a3db9ca98bc1.png)
![Chatterino_NotebookTab_RerunIndicator](https://user-images.githubusercontent.com/4962764/115338318-b5db3180-a1f6-11eb-9e70-52f29ab823db.png)

**Comment by zneix** [comment]
As jammehcow said it's not a bug, but rather a missing feature. Edited your issue a bit to reflect that.

**Comment by AustinHolderr** [comment]
> Not a bug. Reruns technically aren't live.
> 
> As for indicating that a rerun is happening in a title `(rerun)` would probably be fine.
> Will also need to think about the indicator as using red convinces the user the channel is live when it isn't.
> 
> Blue dot instead of red as to not draw the user's attention as much as a live indicator?
> 
> ![Chatterino_NotebookTab_LiveIndicator](https://user-images.githubusercontent.com/4962764/115338315-b4aa0480-a1f6-11eb-8d9e-a3db9ca98bc1.png)
> ![Chatterino_NotebookTab_RerunIndicator](https://user-images.githubusercontent.com/4962764/115338318-b5db3180-a1f6-11eb-9e70-52f29ab823db.png)

i love that idea.
nice work!

**Comment by AustinHolderr** [comment]
> As jammehcow said it's not a bug, but rather a missing feature. Edited your issue a bit to reflect that.

got it, sorry!
thank you!

**Comment by zneix** [comment]
After further investigation I've come to a conclusion that we can't do anything about this since there's no way to determine whether a channel is casting a rerun or is live/offline
See: https://discuss.dev.twitch.tv/t/proper-way-to-determine-if-channel-is-playing-a-rerun/29663

**Comment by alazymeme** [comment]
Classic twitch
Remove them from kraken: https://github.com/twitchdev/issues/issues/39
Don't add them in helix: https://github.com/twitchdev/issues/issues/38
Try to force everyone onto helix

Problem? ![:tf:](https://cdn.betterttv.net/emote/54fa8f1401e468494b85b537/1x)

**Comment by apa420** [comment]
Chatterino used to say (rerun) in the title but after twitch removed the endpoint we can't really do anything about it.

**Comment by zneix** [comment]
> Chatterino used to say (rerun) in the title but after twitch removed the endpoint we can't really do anything about it.

Yes, this is why I added blocked label

**Comment by Mm2PL** [comment]
We could have this work if we could retrieve the stream tags apparently.
