### ISSUE TITLE
Chatterino Not Responding On New Update

### ISSUE THREAD

**Issue by benjiPKS** [Chatterino/chatterino2#2652]
Chatterino not responding

Chatterino on startup stops responding for like a minute and this hasnt happened for me on any other version. 

Chatterino 2.3.0 (commit 58017a754)

Windows 10 Version 20H2

**Comment by alazymeme** [comment]
Cannot reproduce, commit 58017a754

Have you tried running through the [basic troubleshooting](https://wiki.chatterino.com/Help/#basic-troubleshooting)?

**Comment by jammehcow** [comment]
Also cannot reproduce on same commit as @alazymeme.

**Comment by zneix** [comment]
As many users reported already, their issues with chatterino not responding and crashing are gone in 2.3.1. Please update and if this is still a thing, feel free to comment below and reopen the issue.
