### ISSUE TITLE
Emote-Picker context menu like in chat 

### ISSUE THREAD

**Issue by M4tthewDE** [Chatterino/chatterino2#2657]
**What should be added?**
Right now, right clicking on an emote in the emote picker gives the option to copy all emotes in that category. I would like it to work like in chat, where it's possible to copy/open the image link and the bttv/ffz/twitchemotes link.

**Why should it be added?**
I often want to link somebody an emote from another chat, and this change would make it a lot easier. Generally a nice quality of life change.

**Comment by Mm2PL** [comment]
duplicates #1125
