### ISSUE TITLE
Bad settings picker window scaling (window too tall)

### ISSUE THREAD

**Issue by killertofus** [Chatterino/chatterino2#2660]
Describe the bug
when you click on the settings menu when you have chaterino at the top of the screen and click on the emote menu you can't move it until you rescale it

To Reproduce
https://streamable.com/0hervt

Expected behavior
to be able to move the settings menu

Screenshots
https://streamable.com/0hervt

Chatterino version
2.3.0

Additional context
just move it 4Head

**Comment by apa420** [comment]
Can reproduce, this didn't happen on chatterino 2.2.2

**Comment by dojima** [comment]
Still exists on 2.3.2.  Seems to only happen after first closing the settings window with the X in the upper right.  If closing with 'Ok' or 'Cancel', the window remembers its previous position.
