### ISSUE TITLE
Option to hide prediction badges in chat

### ISSUE THREAD

**Issue by LosFarmosCTL** [Chatterino/chatterino2#2664]
**What should be added?**
A new option in settings to hide the prediction badges

**Why should it be added?**
Would really help to clean up the chat during predictions and is afaik the only badge thats not hideable right now

**Comment by zneix** [comment]
@LosFarmosCTL setting to hide prediction badges has now been added in #2668! There's now a new [nightly release](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) which you can download and it will have your requested feature. If you're on Windows, download `test-cmake-chatterino-windows-x86-64.zip`, extract it and import the files in `C:\Program Files\Chatterino` (or whereever is your application installed).
