### ISSUE TITLE
Option to make tab titles lowercase back

### ISSUE THREAD

**Issue by Kurzdor** [Chatterino/chatterino2#2672]
How to make tab titles be in lowercase back? I used to having them in lowercase and this is better for me. 
Any way to make like it was in version ```2.2.2-fix```? 

Using: 
Chatterino 2.3.0
Windows 10 x64 20H2 Build 19042.867

**Comment by leon-richardt** [comment]
Sure, just rename the tab manually

**Comment by zneix** [comment]
It's been discussed to limits in #2513, if you want please have a read for the reasoning behind this change.
