### ISSUE TITLE
Make Usernames Clickable Everywhere (or at least add an option to have them clickable everywhere)

### ISSUE THREAD

**Issue by auxtinn** [Chatterino/chatterino2#2673]
**Describe your issue**

In many places in Chatterino - usernames are not clickable, despite other consistencies leading you to believe this probably wouldn't be the case. Some examples:
 
- Subscription Notifications [Regular & Gift]
- ~Point Redemptions~ Fixed in [??]
- ~User Join/Part messages~ Will be fixed in https://github.com/Chatterino/chatterino2/pull/3358
- ~`/mods` & `/vips`~ Fixed in https://github.com/Chatterino/chatterino2/pull/3187

**Screenshots**

Unclickable
![image](https://user-images.githubusercontent.com/41973452/142694783-804097d3-d035-4dab-9058-90e68b986175.png)
![image](https://user-images.githubusercontent.com/41973452/142694946-af0541d9-fe61-46b4-ab2e-1d9d3d964b1c.png)

Clickable
![image](https://user-images.githubusercontent.com/41973452/142694864-ab79bc4f-c19d-443c-90ed-ffdf03ef6a11.png)
![image](https://user-images.githubusercontent.com/41973452/142694903-3bc4f8e8-13fa-4946-8d97-67398d1f6a7d.png)
![image](https://user-images.githubusercontent.com/41973452/142695553-3d4fefcd-9110-427f-99fb-6d9fa72286b4.png)

**OS and Chatterino Version**

N/A - all versions

**Comment by Mm2PL** [comment]
Could you please reupload the images to github directly since Lightshot's website is so bad?

**Comment by AustinHolderr** [comment]
> Could you please reupload the images to github directly since Lightshot's website is so bad?

yes

**Comment by leon-richardt** [comment]
I agree that this would certainly be useful.

----
> because it would be very helpful for mods instead of having to type out a person's name and/or @ them in chat to be able to view their usercard from said spots.

Are you aware that you can also type `/usercard <username>` to bring up that user's usercard?

**Comment by AustinHolderr** [comment]
> I agree that this would certainly be useful.
> 
> > because it would be very helpful for mods instead of having to type out a person's name and/or @ them in chat to be able to view their usercard from said spots.
> 
> Are you aware that you can also type `/usercard <username>` to bring up that user's usercard?

yes

**Comment by Mm2PL** [comment]
I did some research on the sources of these messages.

1. USERNOTICE (TMI/`TwitchIrcServer`?)
2. locally generated system message (`ChannelChatters`)
3. locally generated message from pubsub (`TwitchMessageBuilder`)
4. USERNOTICE * 6 (TMI/`TwitchIrcServer`?)

The 2 and 3 are the easiest to implement since they are locally generated. Numbers 1 and 4 will probably need to be regenerated client-side (side-note: that is needed for #2026 either way).

**Comment by jammehcow** [comment]
I believe the 'Now hosting xyz' message also has an unclickable username. Would make sense from a continuity perspective to make all of these usernames clickable. If we could get a list of all areas where a username is not clickable that would be useful.

Happy to create individual issues based on each.

**Comment by AustinHolderr** [comment]
> I believe the 'Now hosting xyz' message also has an unclickable username. Would make sense from a continuity perspective to make all of these usernames clickable. If we could get a list of all areas where a username is not clickable that would be useful.
> 
> Happy to create individual issues based on each.
> 
> EDIT: found #2655

good to know, and true!

**Comment by Mm2PL** [comment]
Also missing NOTICE: `/mods` (`room_mods`) and `/vips` (`vips_success`)

**Comment by x9136** [comment]
#5357 — + for the messages about the raid.
