### ISSUE TITLE
Failed to automatically fetch BTTV emotes upon opening client (2.3.0) 

### ISSUE THREAD

**Issue by Vafarien** [Chatterino/chatterino2#2676]
Upon first opening the new version of chatterino 2.3.0 windows client a long wait time for all channels to load and initialize, i navigate to a channel only to find that BTTV emotes failed to load in the channel, only by doing a manual reload (F5) the channels emotes load in propperly, the issue is that to get BTTV wokring on every channel is that you have to manually go to each channel and reload everything.

Steps to reproduce:
1. install 2.3.0 chatterino on windows 64-bit system
2.launch chatterino
3.be in channel and see that BTTV emotes failed to load
4. press F5 to manually reload everytime you open chatterino

Version: Chatterino 2.3.0 (commit 58017a754)

Operating System: Windows 7 64-bit

![image](https://user-images.githubusercontent.com/2349950/115932433-cdf2c100-a441-11eb-8543-b54f13dfbca4.png)
![image](https://user-images.githubusercontent.com/2349950/115932572-0abeb800-a442-11eb-9473-4cc6ad76ad6d.png)

**Comment by jammehcow** [comment]
Can reproduce on Chatterino 2.3.0 (commit `0a51252b7`). Seems to happen at random but definitely exists.

**Comment by jammehcow** [comment]
Appeared to be a genuine timeout from BTTV - cannot reproduce now.

Maybe it's worth putting some focus on the BTTV emote retry mentioned in `BttvEmotes.cpp`.

**Comment by Vafarien** [comment]
No longer able to reproduce issue.

**Comment by jammehcow** [comment]
Could probably be reopened. Seems to be happening across a large set of users.

**Comment by zneix** [comment]
I believe this is a thing just because requests to BTTV API tend to time out sometimes (usually, when you have lots of tabs open and there are concurrent API requests being made at the same time. Worth noting that this was also the case before 2.3.0 was released.

**Comment by jammehcow** [comment]
Should be resolved on the timeout side by #2900 (or I might abandon because of scope and create a new PR) when merged.
