### ISSUE TITLE
macOS app doesn’t have version information

### ISSUE THREAD

**Issue by vitorgalvao** [Chatterino/chatterino2#2678]
**Describe the bug**

There’s no version information inside the app bundle. Neither `CFBundleVersion` nor `CFBundleShortVersionString` are set in `Info.plist`, despite [it looking like they should](https://github.com/Chatterino/chatterino2/blob/0a51252b761ac4a846725ce6b6e8cf8bba5efdf4/cmake/MacOSXBundleInfo.plist.in#L23L28).

**To reproduce**

1. Download the app for macOS.
2. Look at `chatterino.app/Contents/Info.plist`.
3. Note version information is empty. The tags don’t exist.

**Screenshots**

N/A

**Chatterino version**

Chatterino 2.3.0 (commit 2db140d5a)

**Operating system**

macOS 11.2.3.

**Additional information**

N/A

**Comment by pajlada** [comment]
The stable release of Chatterino right now uses the `qmake` build instead of the `cmake` build. The `cmake` build has proper versioning info while the `qmake` build does not.

Once we've phased out `qmake` and `cmake` has proven to be stable enough this will not be a problem.
