### ISSUE TITLE
(As a Moderator in a Channel)–  'Denying' a Message Caught by AutoMod Shows No Confirmation (though it used to)

### ISSUE THREAD

**Issue by AustinHolderr** [Chatterino/chatterino2#2682]
#  **Describe the bug:**  #

**Messages that get caught by AutoMod (as a moderator for the channel) don't tell you that they were OR show up at all in the Chatterino chat client when you deny them. There is no confirmation that your 'Deny' action on AutoMod even did anything...**

#  **To reproduce:**  #

**Have a message get caught by AutoMod and be a moderator for the channel in which the message is caught; Deny the AutoMod-caught message.**

#  **Screenshots:**  #

### **The pop-up from AutoMod saying the message was caught, inside of Chatterino, after I clicked 'Deny' and nothing happened, (when something used to)- to verify and confirm that it was in fact denied and not posted to chat, also showing it doesn't let me delete the message caught, either.** ###
_**(I've blocked out usernames to prevent the users involved from harassment of any sort due to their comments.)**_

<img width="1000" alt="Chatterino AutoMod Deny Issue 2" src="https://user-images.githubusercontent.com/44728118/115971181-f8617e80-a514-11eb-87d8-7550a6f00e1a.png">

### **The completed Mod Action inside of Mod View showing that it did work, and the message caught WAS Denied and not posted to chat.** ###
<img width="300" alt="Chatterino AutoMod Deny Issue 3" src="https://user-images.githubusercontent.com/44728118/115971334-dd433e80-a515-11eb-9993-7fc3f6ef1417.png">

#  **Chatterino version:**  #

**Chatterino 2.3.0 (commit 2db140d5a)**

#  **Operating system:**  #

**macOS Big Sur Version 11.2.3**

<img width="450" alt="macOS Big Sur Version 11.2.3" src="https://user-images.githubusercontent.com/44728118/114466671-c9fbaf00-9bb6-11eb-9070-0496852e2128.png">

#  **Additional information:**  #

**It used to grey-out the caught message under AutoMod and say a local server message in chat confirming to the moderator/user that it was denied, inside of Chatterino; it no longer does this, and can drive moderators crazy because they don't know if denying it worked or not.**

**Comment by Felanbird** [comment]
This is likely to have happened because your connection to pubsub has died, try to replicate testing this by using the automod buttons shortly after starting Chatterino instead.

**Comment by AustinHolderr** [comment]
> This is likely to have happened because your connection to pubsub has died, try to replicate testing this by using the automod buttons shortly after starting Chatterino instead.

i quit and restart chatterino very frequently. it's not that.

**Comment by alazymeme** [comment]
Next thing would be to try re-adding your account.

**Comment by apa420** [comment]
I'm the one who implemented this automod feature. These automod messages you receive are pubsub messages which means that the connection is fine. It might be that twitch changed something about this since chatterino uses some undocumented api to deny and accept messages and if you deny or accept a message it should tell you phrase "x" has been added to the aprove/deny list or something similar. 

https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/PubsubClient.cpp#L533

Code is there for the deny and accept stuff.

I've now tested this and it seems that everything does work, except there's no messages in chat about allowing/denying stuff. I'm unsure if this is because twitch changed something or some other issue.

**Comment by Felanbird** [comment]
> I've now tested this and it seems that everything does work, except there's no messages in chat about allowing/denying stuff. I'm unsure if this is because twitch changed something or some other issue. So if you deny something the message will be marked as deleted. (Approving messages works as well)

There used to be a message that stated the mod in question used the command `/add_blocked_term`, which you are correct no longer shows up, but the command in question was not actually a usable command and seemed to be just a placeholder message.

related code for smart people:

https://github.com/Chatterino/chatterino2/blob/df722a72c18457c71833e03cfad9caccff3cf963/src/providers/twitch/PubsubClient.cpp#L616-L644

**Comment by alazymeme** [comment]
> There used to be a message that stated the mod in question used the command `/add_blocked_term`, which you are correct no longer shows up, but the command in question was not actually a usable command and seemed to be just a placeholder message.

It's possible twitch changed someone and didn't document it (big surprise). cbenni's modlogsbot was working fine for me until recently (I assume these are ban request allows/denies):

![image](https://user-images.githubusercontent.com/12804673/116076738-fa276f80-a6d7-11eb-91a6-ffd411c86183.png)

**Comment by AustinHolderr** [comment]
> I've now tested this and it seems that everything does work, except there's no messages in chat about allowing/denying stuff. I'm unsure if this is because twitch changed something or some other issue. So if you deny something the message will be marked as deleted. (Approving messages works as well)

allowing and denying for me doesnt mark the original automod message as deleted... it just stays lit up..

**Comment by AustinHolderr** [comment]
> > I've now tested this and it seems that everything does work, except there's no messages in chat about allowing/denying stuff. I'm unsure if this is because twitch changed something or some other issue. So if you deny something the message will be marked as deleted. (Approving messages works as well)
> 
> There used to be a message that stated the mod in question used the command `/add_blocked_term`, which you are correct no longer shows up, but the command in question was not actually a usable command and seemed to be just a placeholder message.
> 
> related code for smart people:
> 
> https://github.com/Chatterino/chatterino2/blob/df722a72c18457c71833e03cfad9caccff3cf963/src/providers/twitch/PubsubClient.cpp#L616-L644

yeah, that's part of what's missing.

**Comment by AustinHolderr** [comment]
> > There used to be a message that stated the mod in question used the command `/add_blocked_term`, which you are correct no longer shows up, but the command in question was not actually a usable command and seemed to be just a placeholder message.
> 
> It's possible twitch changed someone and didn't document it (big surprise). cbenni's modlogsbot was working fine for me until recently (I assume these are ban request allows/denies):
> 
> ![image](https://user-images.githubusercontent.com/12804673/116076738-fa276f80-a6d7-11eb-91a6-ffd411c86183.png)

could you link the bot?

**Comment by Felanbird** [comment]
> could you link the bot?

https://github.com/CBenni/modlogsbot

**Comment by apa420** [comment]
"/add_blocked_term" was never a command in normal chat, it was just a pubsub message or whatever and since it seems like twitch has changed something about automod I don't know how much we can do about this. 

> allowing and denying for me doesnt mark the original automod message as deleted... it just stays lit up..
What I meant was just that it doesn't looks like it works in chatterino, but the function of denying or allowing a message does indeed work.

**Comment by iProdigy** [comment]
For `add_blocked_term`, `delete_blocked_term`, `add_permitted_term`, and `delete_permitted_term`, the `type` is no longer `moderation_action` but `channel_terms_action` so the current pubsub client appears to ignore it: https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/PubsubClient.cpp#L1127

Example:
`{"type":"MESSAGE","data":{"topic":"chat_moderator_actions.493418343.612932483","message":"{\"type\":\"channel_terms_action\",\"data\":{\"type\":\"add_blocked_term\",\"id\":\"a59a21f1-36e8-4bb5-ac37-62632d5a8321\",\"text\":\"⢿\",\"requester_id\":\"493418343\",\"requester_login\":\"posadabot\",\"channel_id\":\"612932483\",\"expires_at\":\"\",\"updated_at\":\"2021-05-03T19:46:19.115704756Z\",\"from_automod\":false}}"}}`

**Comment by apa420** [comment]
Thank you for your help @iProdigy I'll look into implementing a fix
