### ISSUE TITLE
Change what side you want tabs  (left, right, up, down)

### ISSUE THREAD

**Issue by WetTortoise** [Chatterino/chatterino2#2685]
**What should be added?**
More options on the positioning of tabs. 

At the  moment In tab layout you can set it to vertical, which will only display on the left side however   I would like to have the tabs on the right side for example. 

**Why should it be added?**

It should be added  to provide more customisation on the look of where  tabs should be instead of it defaulting to the left, I think it would be nice to have  and think it would be useful for other users.

**Comment by zneix** [comment]
Duplicate of #1930
