### ISSUE TITLE
New viewer "rituals" don't show the user's message

### ISSUE THREAD

**Issue by deepy** [Chatterino/chatterino2#2689]
**Describe the bug**
user is new here doesn't show the emote they used for greeting

**Screenshots**
![image](https://user-images.githubusercontent.com/905507/116053752-5019fa00-a67b-11eb-90d8-e7c466e8aa54.png)

**Chatterino version**
Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

**Comment by Mm2PL** [comment]
What channel is this? Does it have a logger set up? Is there any documented examples of a ritual message like this?

**Comment by zneix** [comment]
> What channel is this? Does it have a logger set up? Is there any documented examples of a ritual message like this?

Example raw IRC message of `new_chatter` "ritual" (Sourced from [twitch's documentation](https://dev.twitch.tv/docs/irc/tags#usernotice-twitch-tags)):
```
@badge-info=;badges=;color=;display-name=SevenTest1;emotes=30259:0-6;id=37feed0f-b9c7-4c3a-b475-21c6c6d21c3d;login=seventest1;mod=0;msg-id=ritual;msg-param-ritual-name=new_chatter;room-id=6316121;subscriber=0;system-msg=Seventoes\sis\snew\shere!;tmi-sent-ts=1508363903826;turbo=0;user-id=131260580;user-type= :tmi.twitch.tv USERNOTICE #seventoes :HeyGuys
```
