### ISSUE TITLE
Chatterino closes immediately upon launching

### ISSUE THREAD

**Issue by MariekeCath** [Chatterino/chatterino2#2704]
I am on Windows 10 and I tried installing Chatterino 2.3.0. and the set-up was done succesfully, but whenever I try opening it, it just closes immediately. 
I have tried opening it on another user account with the same role as the account I need it to work on, and it did stay open there, but it does not do so on my account. Trying to launch it as administrator did not work. Nor did reinstalling the program. I do not get a crash log, and the program seems to work for a second but then it's just gone. 
When opening it with task manager open I saw that the entire program just shut down immediately, but it didn't use much any weird amount of CPU power beforehand or anything unexpected. I am genuinely at a loss.

**Comment by HighFive89** [comment]
My problem is similar, it doesn't close when I open it normally, but I have it attached to my browser and anytime I open a stream it closes unless I open the chat also in Chatterino in a new tab. So I can only use Chatterino in my browser if I open the chat seperately on Chatterino beforehand which is obnoxious...

**Comment by nawus** [comment]
> 
> 
> My problem is similar, it doesn't close when I open it normally, but I have it attached to my browser and anytime I open a stream it closes unless I open the chat also in Chatterino in a new tab. So I can only use Chatterino in my browser if I open the chat seperately on Chatterino beforehand which is obnoxious...

Seconded, i have the exact same issue.

**Comment by Jagydvon** [comment]
A workaround for this issue right now is adding the stream as an additional tab in main Chatterino window.

**Comment by robjac** [comment]
Me too -- only crashing on "watching" tab.

**Comment by alazymeme** [comment]
> Me too -- only crashing on "watching" tab.

That's related more-so to the chatterino extension. There aren't really any plans to fix it.

**Comment by fourtf** [comment]
can you try with nightly?

**Comment by Jagydvon** [comment]
Works fine on nightly for me @fourtf

**Comment by fourtf** [comment]
can you try the 2.3.1 beta?

**Comment by Jagydvon** [comment]
There is no released build or I'm blind or you want me to build it myself. Which is it?

**Comment by zneix** [comment]
@Jagydvon you need to opt-in for beta updates in settings: 
![beta in settings](https://cdn.zneix.eu/2jKDqP4.png)

**Comment by Jagydvon** [comment]
Alright did that, "Chatterino 2.3.1 (commit cf33566fd)", and it doesn't crash.

**Comment by almasen** [comment]
Hi, just noting that I have the same issue with latest stable. Nightly and beta 2.3.1 both seem to work fine.

**Comment by tumba00** [comment]
still getting crashes 2.3.1

**Comment by apa420** [comment]
@caneleex try and delete your cache

**Comment by caneleex** [comment]
@apa420 that didn't work, though i suppose it's a whole other issue - sometimes the crashes happen to me after i switch away from a stream with chatterino in my browser. no crash logs, neither as separate files or in the last channel's logs
