### ISSUE TITLE
Show context in rename dialog

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#2709]
**What should be added?**
When renaming a tab, a simple dialog appears with a single text box. This should explain to the user that they are renaming the tab as well as showing the name of the tab in the title/text box placeholder.

**Why should it be added?**
It is not obvious what the dialog does if a user opens it by accident. You could also misclick and believe that you're renaming a different tab than the one being acted on.

**Comment by zneix** [comment]
If you try to rename a tab with custom tab name already assigned to it, it will somewhat tell you which tab you're trying to modify
![fourtf](https://cdn.zneix.eu/wfgyeNg.png)
Although, I like the idea of using placeholder. What should it say exactly? @jammehcow does default tab name (or custom tab name if it's set) as placeholder text make sense to you or should something be added / modified?

When custom tab name is not set (default):
![Farming commits](https://cdn.zneix.eu/quEX9PH.png)

When custom tab name is set (patchloader):
![HonestWork](https://cdn.zneix.eu/z2CzGbw.png)

**Comment by jammehcow** [comment]
I feel like your two examples are great and make sense. Tells you what you're doing as well as what you're acting on.

**Comment by sando** [comment]
IMO, a mix of the two makes the most sense. Keep the same behaviour we have now if the tab name is set, populate the textbox with the set tab name and selected (not as a placeholder). If there's no tab name set, or if the tab name is cleared, display the placeholder with what the default tab name would be.

**Comment by Mm2PL** [comment]
I dont see a placeholder with a custom name being good here since empty has a different meaning than reverting the change.

**Comment by zneix** [comment]
> if the tab name is set, populate the textbox with the set tab name and text selected

My example might've confused you - the tab name still populates the text box and text gets selected. I just removed it for the sake of example.

**Comment by sando** [comment]
> placeholder with the value of currently set custom tab name.

Sorry, my message probably wasn't clear. What @Mm2PL said was what I was trying to express, i.e. the placeholder should *always* display the default tab name, not the custom one if it was set previously, since it implies what the tab name will be now that the custom one has been cleared. 🙂

**Comment by zneix** [comment]
Ah fair, I see what you've meant now - placeholder should always have value of default tab name, right? It makes sense to me, I'll edit the already created PR to reflect changes from your comment. :+1: thanks for explaining.
