### ISSUE TITLE
Chat split not regaining focus after closing search window using ESC

### ISSUE THREAD

**Issue by LosFarmosCTL** [Chatterino/chatterino2#2714]
**Describe the bug**
This bug only occurs when the option "Show input when it's empty" is disabled in settings.

When opening the search window using STRG+F and closing it again using ESC, chatterino doesn't give focus back to the split being searched. Since regaining focus does work when theres something entered in the chat field, this is probably due to it trying to focus the text field, which is at that time still hidden

**To reproduce**
1. Disable "Show input when it's empty"
2. Open the search window while not having anything entered in the input field
3. Close the search window using ESC
4. The currently active split does not regain focus

**Chatterino version**
Chatterino 2.3.0 (commit 9c41adca2)

**Operating system**
macOS Big Sur 11.0.1 (20B50)

**Comment by zneix** [comment]
This is also a case when you, for example close settings dialog and main application window gains focus again - split isn't focused as well.

**Comment by talneoran** [comment]
Does not seem to reproduce on Windows 10 20H2, Chatterino Nightly 2.3.0 (commit ed7d1a8).
With the setting off, after opening any of search, settings, or usercard, the split seems to regain focus and I can write in the input.

**Comment by sando** [comment]
Can reproduce on Windows 10.0.21364, Chatterino Nightly 2.3.0 (commit 2db140d5a).

> With the setting off, after opening any of search, settings, or usercard, the split seems to regain focus and I can write in the input.

Writing input should still be fine after closing search/settings windows, but try opening search again. The text colour of the split header suggests it's not in focus.
