### ISSUE TITLE
Chatterino 2.3.0 randomly closes/crashes

### ISSUE THREAD

**Issue by tumba00** [Chatterino/chatterino2#2719]
This has been going on for about two weeks, I did a fresh install last week but the closes/crashes still  happen.

**Comment by 0xf0f** [comment]
experiencing this too. sometimes it just closes randomly and the 'restart after crash' setting doesnt seem to work at all.

**Comment by fourtf** [comment]
dup https://github.com/Chatterino/chatterino2/issues/2704
