### ISSUE TITLE
Disable /mentions input box

### ISSUE THREAD

**Issue by 21mtd** [Chatterino/chatterino2#2726]
**What should be disabled?**
Input chatbox in mentions tab/split

**Why should it be disabled?**
Because it's useless, you can't send messages there, can't use commands even with /clear or /clearmessage.
Sometimes you send text in it instead of the chat split, pretty annoying and time wasting.

![mentions](https://user-images.githubusercontent.com/75530836/116789024-fb410e00-aad6-11eb-96a1-fe27a95bd3ac.png)

**Comment by zneix** [comment]
You can send whispers from it though, some users might find that useful.

**Comment by apa420** [comment]
Issue #2706 would fix this issue so I'm closing this one.
