### ISSUE TITLE
Hide whispers only in streamer mode

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#2730]
**Describe your issue**
I would like to be able to hide whispers inline when I'm streaming, preferably via a checkbox in the "Streamer Mode" section that overrides the "Show twitch whispers inline" setting.

**OS and Chatterino Version**
Linux, f7506d49

**Comment by zneix** [comment]
I'd be glad to implement this as a Streamer Mode option that changes chatterino's behavoir as you've described.
