### ISSUE TITLE
The oauth expiration message highlights every tab

### ISSUE THREAD

**Issue by somso2e** [Chatterino/chatterino2#2733]
**Describe your issue**
The oauth expiration message (Login expired for user "username"!  Try adding your account again.) highlights every tab.

**Screenshots**
![Before](https://user-images.githubusercontent.com/61581909/116898543-c0acb200-ac4b-11eb-9ee1-cad8dc7b87b1.png)
![After](https://user-images.githubusercontent.com/61581909/116898559-c6a29300-ac4b-11eb-8089-1bf596da8abf.png)

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 2.3.0 (commit 3ad1f10, )

**Comment by fourtf** [comment]
Can we try to renew the tokens instead?

**Comment by zneix** [comment]
This is about "Login expired ..." message having incorrect message flags which leads to highlighting every tab, but sure if that's possible we can try refreshing tokens. That'd be something for another issue though.

**Comment by pajlada** [comment]
> Can we try to renew the tokens instead?

This would be great but we'd have to change the way we request/store tokens, which would have quite a lot of side-effects we'd need to consider.
