### ISSUE TITLE
Add special handling for Twitch bits emotes

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2745]
## Enhancement

**What should be added?**

I would like to have Twitch bits emotes (emotes v2) to have special handling when it comes to `twitchemotes.com` links and possibly a label.

  - The menu item for opening the emote info should not appear because emotes v2 cannot be indexed (thanks Twitch)
  - Potentially updating the `Twitch emote` label to include that it's a bits emote. 

**Why should it be added?**

Non-existent `twitchemotes.com` links suck.

**Comment by zneix** [comment]
Totally agree with you :+1: I'll look into this over the weekend!

**Comment by Mm2PL** [comment]
Apparently new emotes can get `emotesv2` links even if they are not bit emotes. :(

**Comment by pajlada** [comment]
We will not further any functionality related to `twitchemotes.com`

**Comment by zneix** [comment]
From what I saw yesterday twitchemotes.com still provides information about emotes and it seems like they provide information about user's bit emotes too - only URL has changed, see https://twitchemotes.com/channels/99631238 for example and notice how emote links look like now.

**Comment by pajlada** [comment]
To clarify, we shouldn't spend any time working on functionality for a website that isn't yet in a stable phase. We can revisit once they have things actually working, and not in this inbetween zombie state.

**Comment by zneix** [comment]
> To clarify, we shouldn't spend any time working on functionality for a website that isn't yet in a stable phase. We can revisit once they have things actually working, and not in this inbetween zombie state.

Understood. Given your input, should we now remove entry from the context menu that appears upon right-clicking Twitch emotes to open TwirchEmotes page since it's broken?

**Comment by pajlada** [comment]
> > To clarify, we shouldn't spend any time working on functionality for a website that isn't yet in a stable phase. We can revisit once they have things actually working, and not in this inbetween zombie state.
> 
> Understood. Given your input, should we now remove entry from the context menu that appears upon right-clicking Twitch emotes to open TwirchEmotes page since it's broken?

If you want to take the time to do it that's fine by me - yes
