### ISSUE TITLE
Button to clear cache

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#2750]
As part of helping people with issues it's common to ask the user to clear the cache.
Maybe it'd make sense to have a button inside chatterino cache settings to clear the cache (delete the entire folder).
(Unsure if this is possible though)

**Comment by zneix** [comment]
I can have a look into it

**Comment by tumba00** [comment]
maybe that's why i'm getting crashes i had 23,000 files

**Comment by Trung0246** [comment]
Hi, quick question:

Is it really that bad that I have +500k items in the Cache folder? What's the expected size of normal Cache? Should I delete the folder in order to free up space?
![image](https://user-images.githubusercontent.com/11626920/120739697-b9750000-c4a6-11eb-9ca5-997266a940a9.png)

**Comment by tumba00** [comment]
idk, they just came back the next day

**Comment by dojima** [comment]
Having something that automatically clears based on age/size/session/etc would be nice as well.

**Comment by zneix** [comment]
> Having something that automatically clears based on age/size/session/etc would be nice as well.

Chatterino automatically clears files that are older than 14 days, or at least it should - no idea if that may be broken on Windows.
