### ISSUE TITLE
Add folders of channels

### ISSUE THREAD

**Issue by mieshko** [Chatterino/chatterino2#2753]
### Enhancement

Never found possbility to make subfolders in Chatterino so I'm making this issue.

**What should be added?**

It looks like I'd like to sort the channels into some newly created folder on the channel bar, there will be a picture of how I drew it uploaded below this post because putting it into words is a hard thing.
The whole thing is that I want it to be possible to create folders of channels, for example there is some group of streamers and I can put all the members of this group in one folder without taking up a lot of the channel bar.

**Here is an drawing of this idea.**

![image](https://user-images.githubusercontent.com/50804862/117461514-f0aacc80-af4d-11eb-967d-47abe9a05468.png)

**Comment by Mm2PL** [comment]
I believe this idea is probably totally infeasible or really hard to implement. The layouting code for `Notebook`s is already complex enough (192 lines of WAYTOODANK). I don't see any way to contain and then use the data needed for this feature to work.

**Comment by leon-richardt** [comment]
> I believe this idea is probably totally infeasible or really hard to implement. The layouting code for `Notebook`s is already complex enough (192 lines of WAYTOODANK). I don't see any way to contain and then use the data needed for this feature to work.

"Hard to implement" I can see; "infeasible" I'm not sure about. It definitely might require a little bit of a refactor though.

-----

> I don't see any way to contain and then use the data needed for this feature to work.

I'm not sure I understand this part, can you elaborate?
