### ISSUE TITLE
MonkaToS Badge in Chatterino

### ISSUE THREAD

**Issue by xHeaveny** [Chatterino/chatterino2#2758]
**What should be added?**
MonkaToS Badge 

**Why should it be added?**
MonkaToS has a considerably huge user base and a couple of people have asked if there could be support in Chatterino for it.

Code related info
The main endpoint would be:
`https://github.com/Pentalex/MonkaTOS-Ratings`

**Comment by gempir** [comment]
The first step to this would be adding support for it in https://github.com/Chatterino/api/

Create an issue for that.

If the API is found useful and found valuable enough to add to the API and it is then implemented, then the badge implementation here in Chatterino makes sense.

**Comment by xHeaveny** [comment]
> What is MonkaToS (apart from the emote)? Also we don't add badges for services whose services we don't use. See #2289

`https://chrome.google.com/webstore/detail/monkatos-ratings/iecemifilihdioifbjkecacedfgfbfpl` here

**Comment by alazymeme** [comment]
To put it simply:

- Small user base
- No API endpoint that I can see
- As mm2pl mentioned, we don't add badges for services we don't use

Refer to the first point as to why this probably won't be added in Chatterino.

**Comment by Mm2PL** [comment]
I think this person just wants the reward badges.

**Comment by apa420** [comment]
This has nothing to do with chatterino in any context so I'm closing this.
