### ISSUE TITLE
Squelch join/part notifications from blocked users.

### ISSUE THREAD

**Issue by evacfk** [Chatterino/chatterino2#2761]
**Describe your issue**

Not an issue but was unsure on how to add enhancement tag. It would be nice if users were blocked, their join/part notifications could also be squelched. 

I see hundreds of join/parts from bots on a daily basis, this is a Twitchwide issue and not isolated to my channel.

**Screenshots**
http://evac.gg/i/a1fuz.png

**OS and Chatterino Version**
Windows 10, Chatterino 2.3.0

**Comment by Felanbird** [comment]
Duplicate of #2505

**Comment by Felanbird** [comment]
While that issue does specifically state "ignore" I'm willing to bet anyone who implements it would handle both ignore/block, hence the dupe

**Comment by evacfk** [comment]
I actually did not realize I had posted about this before, I apologize that's an oversight on my end.
