### ISSUE TITLE
Block List capped at 100 users

### ISSUE THREAD

**Issue by LeetHaxor** [Chatterino/chatterino2#2767]
Added a bunch of spammers to my block list, but when I go to the block list there's only 20 users listed. If I add more than 20 it shows blank lines as if they were added (but no text on the line), but when I reload chatterino it's capped at 20. They are still ignored on normal twitch chat, but I can see their messages in chatterino (and yes I am using "Enable twitch blocked users"). Is there some limitation in place that prevents more than 20 blocks?

**Comment by LeetHaxor** [comment]
Chatterino Nightly 2.3.1 (commit 2ea233a28, )

**Comment by alazymeme** [comment]
Yes, we don't move past the first page for blocked users.

**Comment by LeetHaxor** [comment]
> 
> 
> Yes, we don't move past the first "page" for blocked users. No idea why

That's unfortunate. I suppose there's not much I can do then. Thanks.

**Comment by LeetHaxor** [comment]
> 
> 
> While the question you asked got an answer, I'd still consider this an issue and something that could be fixed.
Oh okay, reopening for now then!

**Comment by LeetHaxor** [comment]
> 
> 
> Needs to be capped at some level so it doesn't spam too many requests if the user has millions of blocks (maybe ~10000 blocks?).

Makes sense. Currently at 250+, so hopefully something above that is easily achievable. Thanks.

**Comment by zneix** [comment]
A little update on this: on latest nightly block list returns 100 blocks, we'll soon make a fix to respect pagination returned from Twitch's API and try to return all users in the block list.

**Comment by Foretack** [comment]
> Needs to be capped at some level so it doesn't spam too many requests if the user has millions of blocks (maybe ~10000 blocks?).

May I propose adding a setting for users to choose how many blocked users they want to load? Sounds like a good compromise

**Comment by pajlada** [comment]
> > Needs to be capped at some level so it doesn't spam too many requests if the user has millions of blocks (maybe ~10000 blocks?).
> 
> May I propose adding a setting for users to choose how many blocked users they want to load? Sounds like a good compromise

I would rather just increase the amount and cap it somewhere higher. Maybe 1000 (so 10 requests)?
