### ISSUE TITLE
Unable to drag the entire user card box around

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#2768]
**Describe your issue**

Back in 2.2.2, it was possible to use any portion of the top of the user card for dragging the box around.
At some point, this was unfortunately broken.

**Screenshots**

![image](https://user-images.githubusercontent.com/41973452/117794190-00ab0080-b21b-11eb-989e-e249cd810fd7.png)

**OS and Chatterino Version**

Windows 10

d59bb80 current | only had f191de251 to test it's original existance

**Comment by jammehcow** [comment]
Can reproduce, Chatterino 2.3.1 nightly (commit 2ea233a2)

**Comment by jammehcow** [comment]
After taking a look I'm not too sure about what's broken it. @pajlada might've been the QT Dialog changes you made in that commit for `BaseWindow` but changing it hasn't yielded any results for me. Bit lost on this one.

**Comment by Mm2PL** [comment]
Combining this issue with #2170.
