### ISSUE TITLE
Emote picker window stays open when deleting words with Ctrl + Backspace

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#2780]
**Describe your issue**
When using the `:` emote picker and using Ctrl + Backspace to delete the text + colon the emote picker window stays active.
Pressing escape does close the window.

**Screenshots**

https://user-images.githubusercontent.com/4962764/118222668-2282dc80-b4d4-11eb-8306-4247f344ac99.mp4

**OS and Chatterino Version**
Arch Linux (btw), Linux Zen `5.12.3-zen`
Chatterino 2.3.1 (commit 2ea233a2)

**Comment by Felanbird** [comment]
can replicate 

win10 **d59bb805bba6aae3f17472755bd1d0439b05fafe**

**Comment by jammehcow** [comment]
On further investigation it seems that `QTextEdit::cursorPositionChanged` doesn't signal from the input when pressing `Ctrl + Backspace`. Could be a QT quirk I'm not aware of.

**Comment by Mm2PL** [comment]
Can reproduce only when I type an emote prefix that exists, ex:

  - `:penis<C-BS><C-BS>` does not have this behavior
  - while `:sad<C-BS><C-BS>` has

**Comment by Felanbird** [comment]
> Can reproduce only when I type an emote prefix that exists, ex:
> 
> * `:penis<C-BS><C-BS>` does not have this behavior
> * while `:sad<C-BS><C-BS>` has

I'm able to reproduce when using a non existent prefix, even using ~ as the prefix which would obviously have nothing, works.

**Comment by jammehcow** [comment]
> I'm able to reproduce when using a non existent prefix, even using ~ as the prefix which would obviously have nothing, works.

Same here.

**Comment by Mm2PL** [comment]
I retested just to make sure and this time I am able to reproduce with non-existent prefixes ![fuck me.png](https://static-cdn.jtvnw.net/emoticons/v1/301512758/1.0)

**Comment by Felanbird** [comment]
> I retested just to make sure and this time I am able to reproduce with non-existent prefixes ![fuck me.png](https://camo.githubusercontent.com/b3c06739da29347fe02919c9c865f18b95f2570e219955d8e2daf5df9c7b1967/68747470733a2f2f7374617469632d63646e2e6a74766e772e6e65742f656d6f7469636f6e732f76312f3330313531323735382f312e30)

Good I almost said "Ubuntu master race I guess..."
