### ISSUE TITLE
After some time messages do not appear.

### ISSUE THREAD

**Issue by gregtorn** [Chatterino/chatterino2#2789]
After i open Chaterrino all works fine but after 15-20 min all my messages do not appear no matter how many times i write in chat and there no error showed. Just nothing.  Only way is to fix it is restart chaterrino.  And it disconnects and reconnects to chat way often. i use version 2.2.2-fix

**Comment by caneleex** [comment]
same on 2.3.2 nightly

**Comment by Felanbird** [comment]
> After i open Chaterrino all works fine but after 15-20 min all my messages do not appear no matter how many times i write in chat and there no error showed. Just nothing. Only way is to fix it is restart chaterrino. And it disconnects and reconnects to chat way often. i use version 2.2.2-fix

ctrl + f5 instead of restarting

**Comment by caneleex** [comment]
> 
> 
> > After i open Chaterrino all works fine but after 15-20 min all my messages do not appear no matter how many times i write in chat and there no error showed. Just nothing. Only way is to fix it is restart chaterrino. And it disconnects and reconnects to chat way often. i use version 2.2.2-fix
> 
> ctrl + f5 instead of restarting

that only fixes it temporarily

**Comment by Mm2PL** [comment]
> > > After i open Chaterrino all works fine but after 15-20 min all my messages do not appear no matter how many times i write in chat and there no error showed. Just nothing. Only way is to fix it is restart chaterrino. And it disconnects and reconnects to chat way often. i use version 2.2.2-fix
> > ctrl + f5 instead of restarting
> that only fixes it temporarily

Same as restarting...
