### ISSUE TITLE
/live doesn't log properly

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#2791]
**Describe your issue**
Title

1. Navigate to Channels -> live
2. Look at live log file
3. See a log with only timestamps
4. 🙍‍♀️

Also while I have this issue open, should discuss moving /live logs to a main folder along with whispers & mentions just for consistency sake? Since live is it's own custom tab option like whispers/mentions.

**Screenshots**
![image](https://user-images.githubusercontent.com/41973452/118752026-5fcacf80-b830-11eb-9000-864bff149469.png)

**OS and Chatterino Version**
win10 2db50f1

**Comment by Mm2PL** [comment]
Looks like these messages don't have search text, so they can't be searched nor logged.
