### ISSUE TITLE
Moderation Buttons next to "Redeemed with Channel Points"

### ISSUE THREAD

**Issue by xQuai** [Chatterino/chatterino2#2795]
Hello,

it would be really helpful if the moderation buttons are also next to the messages "Redeemed with Channel Points".

Thanks.

**Comment by Felanbird** [comment]
> Hello,
> 
> it would be really helpful if the moderation buttons are also next to the messages "Redeemed with Channel Points".
> 
> Thanks.

Could you please elaborate on this issue, preferably with an image. Sadly I'm unable to replicate the reasoning for your issue, as the only way I can recognize a need for being able to moderate channel point messages, is ones that contain custom responses, which we currently support.
![image](https://user-images.githubusercontent.com/41973452/118974926-65640a80-b941-11eb-9485-d1e4b60d6cf6.png)

Also, when it comes to browser chat, banning the user via their name on the point message, even doing this does not delete the existing notification in chat, so I'm unable to understand the reasoning. 😐 
![image](https://user-images.githubusercontent.com/41973452/118975910-71040100-b942-11eb-924a-a5ad4f3f2092.png)

**Comment by xQuai** [comment]
Hi,

is it possible to have those moderation buttons on channel point messages without custom responses?

**Comment by fourtf** [comment]
There is unfortunately a technical problem here. In the redemption message we receive from twitch there's no way to know if someone is a moderator/staff. So adding moderation buttons here would make it have inconsistently with other messages. So I think the best solution is unfortunately to copy the name and moderate them manually in the edge cases where that is wanted.
