### ISSUE TITLE
freezing at startup

### ISSUE THREAD

**Issue by caneleex** [Chatterino/chatterino2#2796]
**Describe your issue**

sometimes when i open chatterino and a big channel with fast chat is selected (for example xqc), chatterino freezes so i'll have to kill it. i think this can have something to do with the browser extension, but when i disabled it, chatterino was still freezing, but managed to recover after a few seconds while with the extension enabled it didn't most of the time.

this can be fixed temporarily by just reinstalling chatterino (in my case, i deleted chatterino's files in Programs and ran the installer).

[here's the Luke Stackwalker dump](https://mlnr.dev/up/chatterino.lsd) from a session when chatterino froze and recovered after like 30 seconds with the extension enabled. here's a screenshot of the thread with most samples if you don't want to download the software:

![](https://i.imgur.com/koWjYWQ.png)

**OS and Chatterino Version**

Windows 10, Chatterino 2.3.2

**Comment by fourtf** [comment]
out of interest, does this happen when this is disabled? 
![image](https://user-images.githubusercontent.com/6320036/118997974-5bfe9080-b989-11eb-9e94-a091eef86913.png)

**Comment by caneleex** [comment]
> 
> 
> out of interest, does this happen when this is disabled?
> ![image](https://user-images.githubusercontent.com/6320036/118997974-5bfe9080-b989-11eb-9e94-a091eef86913.png)

i've re-enabled that option and it seems to be better now, however it still freezes for like 4 seconds (but then recovers) and also i don't have access to a channel with fast chat so i can test it again when xqc is live again :^)

**Comment by Mm2PL** [comment]
> also i don't have access to a channel with fast chat 

There is `#tmiloadtesting2` and `#twitchmedia_qs_10` (both quite fast, probably not as fast as xqc though)

**Comment by caneleex** [comment]
> 
> 
> > also i don't have access to a channel with fast chat
> 
> There is `#tmiloadtesting2` and `#twitchmedia_qs_10` (both quite fast, probably not as fast as xqc though)

@fourtf tried channel `tmiloadingtesting2` and it seems to be better with just a 4 second freeze with the option both enabled and disabled

**Comment by fourtf** [comment]
ty

**Comment by caneleex** [comment]
update: since xqc is live again, i tried disabling the option and that still freezes but does recover after like 10 seconds, while having it enabled never recovers, so it's probably caused by that

**Comment by jammehcow** [comment]
Not sure how this would work within chatterino's current structure but would it make sense to just load the raw text history messages to begin with and once the connections are established, begin processing the messages for emotes, usernames etc..

Again might not work with c2's current structure.

**Comment by fourtf** [comment]
I found the issue for this and will fix swiftly

**Comment by fourtf** [comment]
quite pathetic that it took me 5 months to react to this though

**Comment by caneleex** [comment]
this has been resolved by #2814, but I'll keep this open until a new release with the fix is published
