### ISSUE TITLE
unsure if people in `/live` already went offline

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2799]
**Describe your issue**
I cannot see when streamers go offline in my `/live` tab. So I sometimes look for a stream and it's already offline.

**Proposed solution**
Just add `%s is offline` messages to `/live`

**Chatterino Version**
Chatterino + Dankerino patches 9e5314fc6a1c237b7f36c97b5ce478739a865673 (based on 2db50f1c)

**OS version**
Ubuntu 20.04.01 LTS

**Comment by fourtf** [comment]
edited title to not propose a solution and focus on the issue
