### ISSUE TITLE
Failing to manage AutoMod messages

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2801]
**Describe your issue**
I get "Failed to allow AutoMod message - message has already been processed." and relogging, reconnecting didn't solve the issue.

This message occurs whenever I press on "Allow" or "Deny".

**OS and Chatterino Version**
Windows 10 64-Bit, Chatterino 2.3.2 (commit 6732b25f3)

**Comment by apa420** [comment]
Other mods might have pressed allow/deny before you had the chance to.

**Comment by karl-police** [comment]
> Other mods might have pressed allow/deny before you had the chance to.

It wasn't in any log 🤔

**Comment by apa420** [comment]
What do you mean, I'm pretty sure that stuff doesn't get logged anywhere.
Denying an automod message doesn't make a message afaik.

**Comment by karl-police** [comment]
> What do you mean, I'm pretty sure that stuff doesn't get logged anywhere.
> Denying an automod message doesn't make a message for all mods afaik.

but why is the error message like that?

**Comment by zneix** [comment]
> but why is the error message like that?

According to [Twitch'd documentation](https://dev.twitch.tv/docs/api/reference#manage-held-automod-messages), status code 400 is being returned because either invalid action has been provided (which can't be the case, becase we explicitly call either "ALLOW" or "DENY") or the message has been already processed.

**Comment by apa420** [comment]
> 
> 
> > What do you mean, I'm pretty sure that stuff doesn't get logged anywhere.
> > Denying an automod message doesn't make a message for all mods afaik.
> 
> but why is the error message like that?

The message is like that because it describes exactly what happened.
The message has already been processed.
In this case most likely by another mod.
