### ISSUE TITLE
emotes are not loading 

### ISSUE THREAD

**Issue by aliihsant** [Chatterino/chatterino2#2806]
Emotes are not loading when i update or reinstall the chatterino. This situation only occurs in versions 2.3.0, 2.3.1 and 2.3.2. I was using 2.2.2-fix before and there was no problem with it. Later, I switched to version 2.3.0 and continued for a while, but when the version 2.3.1 came, it became corrupt and 2.3.0 also broke. Emotes were not loading. I installed the 2.2.2-fix version again and I hoped that this situation would be fixed in the 2.3.2 version, but it still continues. how can i fix this problem ?
![emotemenu](https://user-images.githubusercontent.com/84625432/119226061-1f10d600-bb10-11eb-8e3d-c92fbf6d172a.png) 
![isimliemote](https://user-images.githubusercontent.com/84625432/119226069-29cb6b00-bb10-11eb-8d87-1ae9baf27626.png)

**Comment by apa420** [comment]
Try deleting the Cache folder in the chatterino %APPDATA% folder

**Comment by aliihsant** [comment]
good idea but it didn't work

**Comment by zneix** [comment]
Does this happen only with **emojis** (fourth, tab) or **emotes** (all other tabs) as well?

**Comment by zneix** [comment]
@aliihsant did you find a solution for this? I'm curious whether this was a random issue, something on your end or something that should be fixed on our end to not occur again.
