### ISSUE TITLE
Invalid link to global FFZ emote detail

### ISSUE THREAD

**Issue by Supinic** [Chatterino/chatterino2#2807]
**Describe your issue**
Using the `Open FFZ emote links` action on a global FFZ emote currently opens a link without the emote ID, leading to a 404. 

E.g.: Attempting to open the emote link for the `AndKnuckles` emote opens
`https://www.frankerfacez.com/emoticon/-AndKnuckles` - instead of  `https://www.frankerfacez.com/emoticon/24999-AndKnuckles`. 

**OS and Chatterino Version**
Windows 10, 2.2.3

**Comment by caneleex** [comment]
i think this could be the problem:
https://github.com/Chatterino/chatterino2/blob/14e8a2bf6c163b1a8f09478a7e2bd8a27fcf8911/src/providers/ffz/FfzEmotes.cpp#L70
compared to how the id is parsed for channel emotes:
https://github.com/Chatterino/chatterino2/blob/14e8a2bf6c163b1a8f09478a7e2bd8a27fcf8911/src/providers/ffz/FfzEmotes.cpp#L135
though i'm not proficient enough in C++ to be sure

**Comment by Mm2PL** [comment]
I'll look into this bug.
