### ISSUE TITLE
Flatpak - Unable to launch streamlink / media player

### ISSUE THREAD

**Issue by ThBa** [Chatterino/chatterino2#2809]
**Describe your issue**
I don't this it's a Chatterino issue, but more linked to flatpak packaging. 

While using flatpak version of Chatterino, I'm unable to launch a stream with streamlink. 
- It doesn't work if I install it with host pip ; streamlink custom path `/home/thba/.local/bin`
```bash
Traceback (most recent call last):
  File "/home/thba/.local/bin/streamlink", line 5, in <module>
    from streamlink_cli.main import main
ModuleNotFoundError: No module named 'streamlink_cli'
```
- It doesn't work if I install it with appimage ; streamlink custom path `/home/thba/.local/bin`
```bash
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

I managed to make it work with an exploded appimage (using `--appimage-extract`) and by modifying in streamlink binary the interpreter by the python provided in the exploded appimage. But then I'm having trouble with launching media players; I tried with VLC and MPV.

From my understanding, the issue with media players is because it's looking for libraries (eg: libvlc.so) that can't be found in flatpak's library directories.
```bash
ldd /run/host/usr/bin/vlc
	linux-vdso.so.1 (0x00007ffd98f67000)
	libvlc.so.5 => not found
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f07424ae000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007f07424a8000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f07422dd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f07424eb000)
```

I'm not very confortable with flatpak, and while I tried to tweak it a little I don't know how to add libraries or if it's even possible.

Also, I don't have any issues if I'm running a same-ish config with Chatterino appimage so I guess I will continue to use it this way. But I wanted to report this issue.

**OS and Chatterino Version**
   Ubuntu 20.04, flatpak Chatterino v2.3.2

**Comment by apa420** [comment]
Report this issue to the maintainer of flatpack package or issue tracker for the package (if there is one).

**Comment by ThBa** [comment]
I mindlessly followed the "issues" link on flathub, while there is also a publisher link. Sorry for the trouble!

**Comment by goldbattle** [comment]
Addressed in https://github.com/Chatterino/chatterino2/pull/3178
