### ISSUE TITLE
Multiple spaces being filtered out in received/sent messages

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#2813]
**Describe your issue**
Messages containing more than one spaces in a row are not filtered out by TMI since some time ago now, chatterino still filters them out client-side.

**Screenshots**

![WindowsTerminal_3VnzS5yoMp](https://user-images.githubusercontent.com/3091645/119266343-1b09b480-bbf3-11eb-95b9-b61fdc045c7e.png)

**Comment by leon-richardt** [comment]
IIRC this was done on purpose to match web chat's behavior

**Comment by pajlada** [comment]
The `emotes` IRC tag contains indices where emotes are in the message string, but those indices only work when double-spaces are removed.
So yes, this was an intended change. Is there a scenario that worked before that doesn't work now that has been broken due to this change?

**Comment by TETYYS** [comment]
It doesn't render the message propertly, as it has multiple spaces while one space is displayed. But webchat does the same so I guess that's not really an issue

**Comment by pajlada** [comment]
Even before the fix in #2490 we didn't render things differently if they had multiple spaces, so I will close this as a wont-fix then

**Comment by fourtf** [comment]
I only see one space on normal twitch chat when I post multiple when I tested. Not sure if this is just extremely technical but it doesn't seem like it would make a difference for the user.
