### ISSUE TITLE
AutoMod offender events no longer showing up

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#2818]
**Describe your issue**

As a user, I expect to be notified when AutoMod catches my message. However, as of a few days ago, this no longer happens.

My understanding is that the PubSub topic we used to use for this no longer provides that data, and we have to migrate over to the following PubSub topic to get the functionality back: `user-moderation-notifications.USERID.CHANNELID`

**Comment by pajlada** [comment]
Documentation can be seen [here](https://dev.twitch.tv/docs/pubsub#topics)

**Comment by pajlada** [comment]
This has been fixed 
![image](https://github.com/Chatterino/chatterino2/assets/962989/a9511136-221c-4c0a-a8ac-d5d6154264de)

**Comment by iProdigy** [comment]
Note: we still haven't implemented the `user-moderation-notifications` topic (which is completely fine, especially with an eventsub topic around the corner) -- twitch simply reverted the behavior where they stopped sending `automod_message_rejected` over `chat_moderator_actions` (so our old pubsub handler started working again)
