### ISSUE TITLE
Chat reverse

### ISSUE THREAD

**Issue by wHPcz** [Chatterino/chatterino2#2821]
Can u add reverse chat option in chatterino? That there is a new message at the top of the chat? 
Its verry usefull features.  
Now i solved it with CSS but not through chatterino. :(
Thank you

**Comment by Felanbird** [comment]
That's a pretty interesting suggestion actually, I'm surprised nobody has suggested it before.

**Comment by fourtf** [comment]
Messages appear at the bottom just like they do in any other chat client. Changing the direction is very unconventional and too niche to be included. Get used to how it works instead of hanging yourself up on it.

**Comment by wHPcz** [comment]
> Messages appear at the bottom just like they do in any other chat client. Changing the direction is very unconventional and too niche to be included. Get used to how it works instead of hanging yourself up on it.

So do you want chatterino like any other chat client?  Wtf than why exist if want be like any others.

**Comment by CaptainFlint** [comment]
Not that I would use such a layout myself, but I've seen a similar option in BTTV. That means, that there definitely is an audience for top-to-bottom chat clients, even if it can be considered unconventional.

**Comment by fourtf** [comment]
> 
> 
> > Messages appear at the bottom just like they do in any other chat client. Changing the direction is very unconventional and too niche to be included. Get used to how it works instead of hanging yourself up on it.
> 
> So do you want chatterino like any other chat client? Wtf than why exist if want be like any others.

That's a pretty broad generalization. Not allowing this specific feature obviously doesn't mean that no new features should be added at all.

I have a question. Who's gonna take care of this feature down the road, possibly years into the future? It's not gonna be you. It's gonna be me and other contributors. Any feature is weight on the development at some point, even years down the line. The code constantly changes and having to consider edge cases like this makes changes a burden down the line. So allowing niche features like this that don't like this is not worth it.

**Comment by wHPcz** [comment]
> > > Messages appear at the bottom just like they do in any other chat client. Changing the direction is very unconventional and too niche to be included. Get used to how it works instead of hanging yourself up on it.
> > 
> > 
> > So do you want chatterino like any other chat client? Wtf than why exist if want be like any others.
> 
> That's a pretty broad generalization. Not allowing this specific feature obviously doesn't mean that no new features should be added at all.
> 
> I have a question. Who's gonna take care of this feature down the road, possibly years into the future? It's not gonna be you. It's gonna be me and other contributors. Any feature is weight on the development at some point, even years down the line. The code constantly changes and having to consider edge cases like this makes changes a burden down the line. So allowing niche features like this that don't like this is not worth it.

Ok i understand your reason, BUT if in css is it just this "{ display: flex; flex-direction: column-reverse; top: 0; bottom: unset; }" so how much its hard to care about it. Plus one more button in settings. Is it really still not worth it?

**Comment by Mm2PL** [comment]
> Ok i understand your reason, BUT if in css is it just this "{ display: flex; flex-direction: column-reverse; top: 0; bottom: unset; }" so how much its hard to care about it. Plus one more button in settings. Is it really still not worth it?

It maybe just a little CSS. However this app is not a browser. Chatterino is made in c++ using Qt. From the user's perspective, it is an incredibly simple feature: Just place messages from the bottom, how hard could it be. But when looking at it as a programmer (and contributor) it's not as simple anymore. Updating how messages are placed is way more work here (there is no CSS and messages are placed manually). Ensuring this doesn't break with such a small user base (three potential users) doesn't help either. As with any change Chatterino gets more cluttered code-wise and user interface-wise (the settings already need a search bar!).

**Comment by wHPcz** [comment]
ok thank you for explain so best way for this is still pop up twitch chat. Just offtopic.. what is your vision with chatterino ? or what should be the benefit :)
