### ISSUE TITLE
--channels command does not accept multiple arguments

### ISSUE THREAD

**Issue by easton-bittner** [Chatterino/chatterino2#2823]
**Describe your issue**

When launching chatterino via command line or via streamlink, it will not accept multiple command line arguments in the -c or  -channels command. It will either open the first listed channel ignoring the comma and following arguments, or combine the string into one argument. According to #1940 it should be able to be separated via , allowing multiple arguments.

**Screenshots**

Various methods tried to reproduce this issue.
[Seperate Strings](https://discordjs.moe/r9olzc8c4jbh.png)
[Result](https://discordjs.moe/appihxv8rbxe.png)
[Combined String](https://discordjs.moe/uxn8mwl76gyc.png)
[Result](https://discordjs.moe/oaufno60pvt3.png)

**OS and Chatterino Version**

Windows 10 
Chatterino 2.3.2  #Nightly

**Comment by Mm2PL** [comment]
The help provides an example of how to do this it's `channel_one;channel_two`.

<details>
<summary>chatterino -h</summary>


Usage: bin/chatterino [options]
Chatterino 2 Client for Twitch Chat

Options:
  -h, --help                                  Displays this help.
  -V, --version                               Displays version information.
  -v, --verbose                               Attaches to the Console on
                                              windows, allowing you to see debug
                                              output.
  -c, --channels <t:channel1;t:channel2;...>  Joins only supplied channels on
                                              startup. Use letters with colons
                                              to specify platform. Only twitch
                                              channels are supported at the
                                              moment.
                                              If platform isn't specified,
                                              default is Twitch.

</details>

**Comment by easton-bittner** [comment]
That works perfectly!
