### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by baechu69** [Chatterino/chatterino2#2826]
so when I start up my pc and I open chatterino the shortcut says it won’t work and should I delete it, then I try opening it from the source and it just says the same thing so I have to do a clean uninstall and reinstall of it and have to type out all the channels again it’s done this for 3 days now does anyone know a fix for this any sort of help is much appreciated

**Comment by jammehcow** [comment]
"Need help" isn't the best title. Would recommend something like "Unable to open chatterino after system restart."
Also there's an issue template if you could use that instead of deleting it.

**Comment by jammehcow** [comment]
As for a potential resolution, have you tried uninstalling and removing the folder at `%appdata%\Chatterino2`? Not sure if that's what you meant by clean reinstall.

**Comment by Mm2PL** [comment]
This support thread has been inactive (from OP) for almost two months, it's fair to assume that the issue was resolved.
