### ISSUE TITLE
Historic Messages Api Limit - query parameters building

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#2833]
Currently the code appends a query parameters as a string, rather then properly build url queries
`auto url = QString("%1?limit=%2")`

If the api already has query parameters, then this instead appends to last query parameter's value rather than add a new parameter. And if we manually add & in our API url, then any additional question mark is treated as character literal, therefore parameter keyname is '?limit' instead of 'limit'. Also there's no way to disable this parameter (in case we had our own usage for 'limit' keyname).

https://github.com/Chatterino/chatterino2/blob/3fddafb867c6a1d18bfc4d4deb8fcbba9e540ce8/src/providers/twitch/TwitchChannel.cpp#L728

1) this should probably use real url handling (QUrl class?)
2) add a way to disable this parameter

**Comment by hemirt** [comment]
3) POST parameters inside body would be nice too

**Comment by pajlada** [comment]
1. QUrl doesn't seem to have many nice features to handle this, and in general passing 'objects' or maps as environment variables seem a bit messy
2. Instead of disabling the parameter, you could just add &notused at the end of your custom `CHATTERINO2_RECENT_MESSAGES_URL` environment variable to 'negate' the ?limit=%2 addition. (not 100% sure if this will work)
3. this also feels difficult to control

The idea behind allowing custom URLs for the `CHATTERINO2_RECENT_MESSAGES_URL` is to allow self-hosting of the service. If you are using a wildly different service that required different parameters that you can't control, that may be difficult to solve for.
If you can control the service, my suggestion would be to adapt the service to the way/type of parameters Chatterino can send instead (i.e. send query parameters only)

**Comment by hemirt** [comment]
1) Wouldn't QUrl + QUrlQuery work well for this?
https://doc.qt.io/qt-5/qurlquery.html#addQueryItem
2) yeah just adding & works fine, provided you don't use "?limit" in the api
3) wouldn't just a simple textbox with key-value pairs (or json) be fine?

I'm not sure what the rationale behind the limit and it's max values is anyways.

**Comment by pajlada** [comment]
>     1. Wouldn't QUrl + QUrlQuery work well for this?
>        [doc.qt.io/qt-5/qurlquery.html#addQueryItem](https://doc.qt.io/qt-5/qurlquery.html#addQueryItem)

Reading more into it yes it does seem like this could work. What we could do then is:  
1. Parse `CHATTERINO2_RECENT_MESSAGES_URL` into a QUrl  
https://doc.qt.io/qt-5/qurl.html#QUrl-2
2. Parse query variables from original QUrl into QUrlQuery  
https://doc.qt.io/qt-5/qurlquery.html#QUrlQuery-1
3. Add limit query variable to QUrlQuery if limit key is not already set  
https://doc.qt.io/qt-5/qurlquery.html#hasQueryItem  
https://doc.qt.io/qt-5/qurlquery.html#addQueryItem
4. Attach QUrlQuery to QUrl  
https://doc.qt.io/qt-5/qurl.html#setQuery-1

This would make it so you didn't have to ugly things around with adding a random & at the end of your URL

Would https://github.com/Chatterino/chatterino2/commit/e1b494bebae27eeb953314398278f74df2c49cec help your use case?

> 
>     3. wouldn't just a simple textbox with key-value pairs (or json) be fine?

It would work, yes, I'm hesitant to add settings for controlling custom hosts though so what I mean is it's difficult/unwieldy to control through environment variables


> I'm not sure what the rationale behind the limit and it's max values is anyways and the arbitrary choice of 800, is it to do with the max defaults for everyone to not overload the default service? (If so, then the max limits should rather be enforced on the server, and not the client)

The max number being 800 is there for a reason; a split may only contain 1000 messages, this is a hard coded limit, and adding more than 1000 messages at the same time would cause the application to crash. 800 seemed like a reasonable number under the 1000 message limit. See https://github.com/Chatterino/chatterino2/issues/1421

800 also seems to be the actual max provided by the service we use, see https://recent-messages.robotty.de/
 > The service temporarily saves messages received from all connected channels, for a maximum time of 24 hours. Additionally, on channels with a lot of messages, the service will not store more than 800 messages at once (old messages will be deleted to make room in case the limit is reached).

**Comment by hemirt** [comment]
> The max number being 800 is there for a reason; a split may only contain 1000 messages, this is a hard coded limit, and adding more than 1000 messages at the same time would cause the application to crash. 800 seemed like a reasonable number under the 1000 message limit. See #1421

Ah I see, I upped my limits to 25k so I did not observe any crashes with more messages from my service.

> It would work, yes, I'm hesitant to add settings for controlling custom hosts though so what I mean is it's difficult/unwieldy to control through environment variables

I myself don't really like environment variables, so I would lean towards settings instead, well it's not really a much needed feature anyways.

> Would e1b494b help your use case?

Yeah, it makes more sense to not have a faux & at the end of the api, albeit it's just a cosmetic upgrade anyways, a way to disable the limit parameter altogether would be nice, but it's also possible to just ignore it server-side, is what I do now anyways.

This is just something I encountered when using my own service instead and thought there'd be some merit to have it documented and "fixed", so that maybe if there are new APIs so that they are implemented correctly.

**Comment by hemirt** [comment]
I think it's possible to close this issue then.

On/Off switches for settings that yet do not have them could be its own issue, if need be, and could spark discussion about technicals and how to convey that to user via gui without cluttering the settings (that to me it seems are already somewhat cluttered in the UI sense).

**Comment by hemirt** [comment]
> I myself don't really like environment variables, so I would lean towards settings instead, well it's not really a much needed feature anyways.
> 
> >

A json configuration file would seem better imo, as not everything needs be in the UI.

**Comment by pajlada** [comment]
What do you envision being part of the post body?

**Comment by Mm2PL** [comment]
@zneix, do you consider this fixed in https://github.com/Chatterino/chatterino2/pull/3039?

**Comment by pajlada** [comment]
Fixed in #3039

For further functionality feel free to open up a new discussion or issue referring/quoting any previous comments here.
