### ISSUE TITLE
Chatterino doesnt open/ stuck on no response

### ISSUE THREAD

**Issue by 5434b55634v23v4564** [Chatterino/chatterino2#2838]
Chatterino was suddenly stuck on no response on restart. didnt fix with pc restart. worked after uninstall+reinstall. now stuck on 3min no response, then open. cpu not the problem (doesnt go over 5%)

completely destroys user experience, please fix

**Comment by caneleex** [comment]
try the nightly build, it has been resolved by #2814

**Comment by Mm2PL** [comment]
This support thread has been inactive (from OP) for almost two months, it's fair to assume that the issue was resolved.
