### ISSUE TITLE
Option to lock tabs from being dragged around

### ISSUE THREAD

**Issue by MrAuro** [Chatterino/chatterino2#2843]
**What should be added?**
An option to lock the tabs from being dragged around

**Why should it be added?**
Sometimes I misclick and drag a tab around where I don't want it to be

**Example**
Instead of adding another setting, adding the option next to the hide tabs control would be best
![dank drawing](https://user-images.githubusercontent.com/35087590/120119715-46e2e800-c167-11eb-9c6f-4a704b04d9f2.png)

**Comment by zneix** [comment]
I worked with files responsible for tab behavior and I could add this ~~easy stream content~~ feature later this week 👍

**Comment by MrAuro** [comment]
#3627 closes this
