### ISSUE TITLE
Some keybindings stop working after refocusing chatterino's window

### ISSUE THREAD

**Issue by cWve** [Chatterino/chatterino2#2844]
**Describe your issue**
While the option "Show input when it's empty" is turned OFF in the settings, a few of the keybinds ("F5" to reload emotes, for example) stop working after unfocusing chatterino's window and refocusing.

Steps to reproduce:
- Go to Settings --> General --> Chat and uncheck  "Show input when it's empty"
- Focus on a different window, then regain focus on chatterino's window.
- Try using a keybind like "F5"

The problem can be fixed temporarily by switching to a different tab as shown in the second screencast.

**Screenshots**

Behaviour while setting is turned on: (expected behaviour)

https://user-images.githubusercontent.com/16579297/120122374-b2997500-c1a8-11eb-9efb-90f72e0aef5e.mp4

Behaviour while setting is turned off: 

https://user-images.githubusercontent.com/16579297/120122414-d8267e80-c1a8-11eb-880f-952403814a37.mp4

**OS and Chatterino Version**
Arch Linux, Chatterino Nightly 2.3.2 (commit 57354283)
Dwm 6.2 as the window manager

**Additional information**

List of hotkeys affected by this issue (from the list in Settings --> Keybinds):
- Ctrl+W
- Ctrl+G
- Ctrl+R
- Ctrl+F
- Ctrl+F5
- Alt+X
The ones not mentioned do seem to work

**Comment by jammehcow** [comment]
Can reproduce.
Chatterino 2.3.2 (commit faae2c2e)
Arch Linux (5.12.8-zen1-1-zen) / bspwm + picom

**Comment by Felanbird** [comment]
Cannot replicate
Windows10 | 2db50f1

**Comment by zneix** [comment]
This is highly related to #2714, I sense the same cause here - split not being focused.

**Comment by pajlada** [comment]
@cWve This should be fixed in https://github.com/Chatterino/chatterino2/pull/3838 - any chance you could give this a try?

To test a PR build, you can browse to the linked PR, click the "Checks" tab, then select the "Build" job on the left side, then scroll down to find the build that fits your platform. Note that you need to be signed into GitHub to download from that page.
