### ISSUE TITLE
Remove Visual C++ Installer Dependency

### ISSUE THREAD

**Issue by s-crypt** [Chatterino/chatterino2#2849]
**Describe your issue**

Remove the C++ distributable in the installer process. 
In general, the VC++D isn't needed anymore (please correct me if I'm wrong), and is annoyance in the install. This also blocks some automated install methods like winget because the VC++D does not have a silent install switch.

**OS and Chatterino Version**
Windows 10, any Chatterino 2 version.

**Comment by fourtf** [comment]
Elaborate further why it's "not needed" and link to a source please. Also the vcredist does have a silent switch IIRC.

**Comment by s-crypt** [comment]
Sorry I didn't provide more information. 
I believe now you can statically link the application runtime in Visual Studio under Linker Options
https://t2a.io/blog/visual-c-runtime-and-static-linking-made-simple/
Although there may be an increase in the size of the binary, the install will be simpler, as the runtime is included with the files.

Is this something that could be implemented? This could be useful for automated install/upgrade methods

**Comment by fourtf** [comment]
Not possible because of Qt licensing afaik

**Comment by leon-richardt** [comment]
> Qt licensing

Doesn't the Qt license only forbid statically linking against Qt specifically? Other libraries should fair game by my understanding (not a lawyer though, obviously)

**Comment by fourtf** [comment]
The configuration script of Qt doesn't allow statically linking to the c++ library. If you find a way to get around that in a legal way feel free to make a pull request.

**Comment by Mm2PL** [comment]
> The configuration script of Qt doesn't allow statically linking to the c++ library.

Are you talking about the chatterino.pro project file? If so maybe CMake builds could get static vc runtime?

**Comment by alazymeme** [comment]
Bundling vcredists with the install is not an option. OBS have specifically opted against this due to the licensing issues. I don't understand what the big inconvenience is about it being there.

> the VC++D isn't needed anymore ... and is annoyance in the install.

Other applications will also use the vcredists we suggest users install, won't installing something basic like this only serve to make their experience better?

> This also blocks some automated install methods like winget because the VC++D does not have a silent install switch.

As per the Chatterino Chocolatey project, you can simply skip the vcredist step. In my case, I install it as a Chocolatey dependency: https://community.chocolatey.org/packages/chatterino#files

**Comment by fourtf** [comment]
> 
> 
> > The configuration script of Qt doesn't allow statically linking to the c++ library.
> 
> Are you talking about the chatterino.pro project file? If so maybe CMake builds could get static vc runtime?

no, I mean the configuration script that you use when building Qt itself

**Comment by fourtf** [comment]
well, it's not possible so I'm closing
