### ISSUE TITLE
"Always on top" crashes.

### ISSUE THREAD

**Issue by Zatsando** [Chatterino/chatterino2#2851]
The latest appimage version of chatterino crashes when i try to enable the "always on top" feature. For example toggle on the "on top" and immediately the app shut's down itself and when I open it up again the "always on top" is still off.

My OS is ArchLinux (5.12.8-arch1-1 kernel version) and Gnome 40.1 for de.

**Comment by cWve** [comment]
I can reproduce (ArchLinux 5.12.8). It's not exactly a crash, the chatterino window disappears, but the process is still running silently.
Using git-bisect I've found the bug was introduced in c9f62fed4c0d5f9134b9e5ad96eb287eeb0063e5

**Comment by pajlada** [comment]
@cWve 
Thank you for the information - that helped narrow down the issue.

Could you and @Zatsando please check out [this branch](https://github.com/Chatterino/chatterino2/tree/chore/cache-window-visibility-value-when-toggling-alwaysontop) and see if that solves it for you? If it does, I'll get it tested on Windows and MacOS and if nothing goes wrong we'll get that merged into master.

**Comment by cWve** [comment]
Tested with KDE Plasma and it works perfectly now 👍

**Comment by killertofus** [comment]
still crashes 

https://user-images.githubusercontent.com/16343162/131530676-e365889a-2f6b-46e3-91e7-11d447be3aad.mp4

https://i.imgur.com/vK83ab9.png

**Comment by killertofus** [comment]
a solution I found is to right click and press on always on top 
![image](https://user-images.githubusercontent.com/16343162/143803694-92a87da4-191e-4427-aad9-de2d9d295b10.png)
tested in linux mint  5.4.0-90-generic

**Comment by pajlada** [comment]
If you could get me a stacktrace @killertofus that would be super helpful

**Comment by killertofus** [comment]
PID: 241883 (chatterino)
           UID: 1000 (killertofus)
           GID: 1000 (killertofus)
        Signal: 6 (ABRT)
     Timestamp: Wed 2021-12-01 13:36:20 MST (2 days ago)
  Command Line: chatterino
    Executable: /app/bin/chatterino
 Control Group: /user.slice/user-1000.slice/user@1000.service/flatpak-com.chatterino.chatterino-241872.scope
          Unit: user@1000.service
     User Unit: flatpak-com.chatterino.chatterino-241872.scope
         Slice: user-1000.slice
     Owner UID: 1000 (cinemassacres)
       Boot ID: 2df4f29271bb44558295ba710693bae8
    Machine ID: dafd9a61376b4676aa8b190bc1ed4b43
      Hostname: Pc
       Storage: /var/lib/systemd/coredump/core.chatterino.1000.2df4f29271bb44558295ba710693bae8.241883.1638390980000000000000.lz4
       Message: Process 241883 (chatterino) of user 1000 dumped core.
                
                Stack trace of thread 2:
                #0  0x00007f7942f837f5 n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so + 0x397f5)
                #1  0x00007f7942fce81c n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so + 0x8481c)

**Comment by cWve** [comment]
Keep in mind that the patch that pajlada made was never merged into the master branch, which means that the fix is still not available in any of the chatterino releases. The only way to get the fix as of now is by manually compiling the branch he linked.

I have actually tested a build of chatterino master (2c695a9ac534b) and I cherrypicked the commit that patches the issue (408e8634d43). 
I tested said build on Linux Mint 20.2 Cinnamon as well and it doesn't crash (although I had to restart chatterino for it to actually work, that might deserve its own issue)

**Comment by pajlada** [comment]
thank you, I made a PR to get it merged into the main branch now @cWve

**Comment by pajlada** [comment]
@killertofus once you've updated your flatpak build, feel free to try this out again and open a new issue if the issue still occurs. Make sure that you're on https://github.com/Chatterino/chatterino2/commit/b41df1893319d1f86243eec605ddaf3fe252910d

**Comment by ilyazzz** [comment]
There's a test flatpak build built from https://github.com/Chatterino/chatterino2/commit/51ece94f588a60c578504309f9eeea22a831f0fa. You can install it with `flatpak install https://dl.flathub.org/build-repo/69388/com.chatterino.chatterino.flatpakref`.

**Comment by killertofus** [comment]
@ilyazzz  Can't load uri https://dl.flathub.org/build-repo/69388/com.chatterino.chatterino.flatpakref: Server returned status 404: Not Found

**Comment by ilyazzz** [comment]
@killertofus the test build seems to have expired, if you don't mind using the 7tv build you can install a recent build from flathub-beta:
`flatpak install https://flathub.org/beta-repo/appstream/com.chatterino.chatterino.flatpakref`
