### ISSUE TITLE
I cant whisper using chatterino

### ISSUE THREAD

**Issue by chatterinouser** [Chatterino/chatterino2#2858]
I cannot use the /w <insert username> function on Chatterino. When I do this it says "Your settings prevent you from sending this whisper." I've tried a lot of things to fix it and I've checked all setting that could be affecting this. (both twitch and Chatterino) I've asked a lot of people and no ones really come up with a solution.

https://i.nuuls.com/JLJ3a.jpeg what it shows

Windows 10, Chatterino  7.3.2

**Comment by jammehcow** [comment]
Have you read the wiki entry for this? https://wiki.chatterino.com/Help/#i-am-unable-to-send-whispers-from-chatterino

**Comment by chatterinouser** [comment]
yeah ive done all of that yet it still shows the same message idk what to do tbh

**Comment by zneix** [comment]
Unfortunately there's nothing we can do about this, it's a limitation on Twitch's end.
