### ISSUE TITLE
Channel Filter not working for "hosting" system message in 2.3.2

### ISSUE THREAD

**Issue by RollDaiB** [Chatterino/chatterino2#2859]
The issue is that a specific type of Channel filter seems like stop working in 2.3.2 (worked fine in 2.3.0) the filter is  `(flags.system_message && (message.content) contains ("Now hosting")) ` . 

I have tried changing the message to `"hosting"` or to the filter `(message.content) contains ("Now hosting")`  but doesn't works. 
 
Using only the filter `(flags.system_message)`  works fine but the purpose is only filter hosting messages.

So my idea is that the function `contains` can't read the hosting system messages. 
 
Finally this issue easy recreatable by hosting any channel.

P. D.  First time doing a report, sorry if is not very understandable.

**Comment by Felanbird** [comment]
Related #2470, 
> I also noticed that basically all the messages built with `MessageBuilder` functions are not "findable", example: https://github.com/Chatterino/chatterino2/tree/master/src/providers/twitch/IrcMessageHandler.cpp#L699


#1423
> You are also unable to search for messages that are "custom-built", for example the "system message" sent if token has expired, code snippet:
> 
> https://github.com/Chatterino/chatterino2/blob/a6e23e246864458c9d00c469c3b7306086b8d0ed/src/providers/twitch/IrcMessageHandler.cpp#L702-L713
