### ISSUE TITLE
Show which mod deleted message

### ISSUE THREAD

**Issue by WetTortoise** [Chatterino/chatterino2#2867]
**Describe your issue**

**Screenshots**

**OS and Chatterino Version**

**Comment by WetTortoise** [comment]
I cant see any of the screenshots I added so ill just comment them.  

https://i.imgur.com/24Pt6Lq.png

https://i.imgur.com/fdfLut0.png 

My problem is that I  can't see who deleted the message.

**Comment by M4tthewDE** [comment]
#2841 will improve this a bit by at least showing in chat that a message was deleted, but without showing the mod that did it a good amount of trolling is possible

**Comment by Mm2PL** [comment]
I will take a look at also showing these messages via pubsub, this would allow the app to show *who* deleted the message.
