### ISSUE TITLE
channel history is not loaded at startup

### ISSUE THREAD

**Issue by caneleex** [Chatterino/chatterino2#2868]
**Describe your issue**

On the latest nightly build, the channel history is not loading at startup even though I have it enabled. I've also tried re-enabling it but that didn't help.

**Screenshots**

![](https://i.nuuls.com/tIxwt.gif)

**OS and Chatterino Version**

Windows 10, latest nightly

**Comment by caneleex** [comment]
I think I should split the problems into two issues. What do you think?

**Comment by zneix** [comment]
Please keep in mind that loading message history is being pulled from 3rd party service that may not always be available - at the moment of creating the issue (and writing this comment) service experiences degraded perforance and there's nothing we - Chatteirno people can do about this, just wait a bit until the service restarts.

**Comment by caneleex** [comment]
indicating something with the history API is wrong wouldn't be a bad idea, it could possibly prevent issues like this

**Comment by zneix** [comment]
> indicating something with the history API is wrong wouldn't be a bad idea, it could possibly prevent issues like this

Fully agree, I just had a thought about adding at least a system message informing the user about status of the recent-messages request / response. Something similar to responses that you receive upon refreshing third party emotes.
