### ISSUE TITLE
disconnected at startup

### ISSUE THREAD

**Issue by caneleex** [Chatterino/chatterino2#2869]
**Describe your issue**

Sometimes when launching chatterino, I'm immediately disconnected and then reconnected after a few seconds.

**Screenshots**

**OS and Chatterino Version**

Windows 10, latest nightly

**Comment by apa420** [comment]
Please describe your issue more adequately.
Do you first connect and then disconnect and then reconnect?
Does it just say disconnected and then reconnected?

For me it can take up to 30s for chatterino to connect to twitch chat on arch linux where it says disconnected first and then connects while on windows it's a lot faster. (Both programs are on os ssd).

**Comment by caneleex** [comment]
sorry, could've picked better wording. when I said I'm "immediately disconnected", I meant that the client starts up already with the state of "disconnected" in chat, then reconnects

**Comment by pajlada** [comment]
@caneleex What commit hash are you on?

**Comment by caneleex** [comment]
@pajlada `5512437f1`

**Comment by pajlada** [comment]
> `5512437f1`

Do you generally try to write a message really quickly after starting Chatterino?

**Comment by caneleex** [comment]
> 
> 
> > `5512437f1`
> 
> Do you generally try to write a message really quickly after starting Chatterino?

no, I don't. I don't think this issue is happening to me anymore, but I'm sure I could reproduce it if I really wanted to by spamming reconnects by closing and then opening chatterino

**Comment by pajlada** [comment]
This seems pretty random - the reason it's more noticeable now is that our minimum time to wait before a reconnect is 15 seconds. I'm working on a PR to reduce this and to ensure we back off our reconnect attempts [as expected by Twitch](https://dev.twitch.tv/docs/irc/guide#re-connecting-to-twitch-irc).

PR created over here: #2892
