### ISSUE TITLE
reverse chat vertical options missing

### ISSUE THREAD

**Issue by jackzback** [Chatterino/chatterino2#2872]
**Describe your issue**

hello, this app looks perfect thank for your effort. i just cant find an option to reverse chat for a new message. i wanna see new messages from top not bottom if its possible if not please add <3 <3 <3 <3

-->

    
        Windows 10, Chatterino 2.3.0
       

-->

**Comment by Mm2PL** [comment]
Same thing as #2821

**Comment by pajlada** [comment]
Duplicate of #2821
