### ISSUE TITLE
Migrate Twitch Emotes to Helix API

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#2875]
Freshly announced, there are new endpoints in Helix for getting emotes:

- [Get channel emotes](https://dev.twitch.tv/docs/api/reference#get-channel-emotes)
- [Get global emotes](https://dev.twitch.tv/docs/api/reference#get-global-emotes)

**Comment by zneix** [comment]
The Get channel emotes endpoint currently seems bugged, returns emote id as set id, so I'll wait a bit before working on this

![fix your shit you fucking pepega](https://cdn.zneix.eu/3EBRqB7.png)

**Comment by flex3r** [comment]
It doesn't look like Helix offers a way to get a user's emotes though, which is what Chatterino and DankChat use at the moment. Of course we could just fully switch to the emote sets in the `USERSTATE` irc message but that will lead to the scuffed emote reloading...

**Comment by c0ldplasma** [comment]
Is there any progress on this? Twitch API v5 will be decomissioned on February 28. I think the USERSTATE is the only way to do it currently.

**Comment by zneix** [comment]
We've actually already moved away from Kraken and the only Kraken endpoint that's left is Get User's Emotes which is only used as fallback to get information about some emotes that user can use (e.g. Hype Train and emotes from other 'time-limited' emotesets). This endpoint will however not have a migration path provided and we should perhaps just get rid of it.
Back to this issue though, we currently fetch emoteset data from Ivr, which should most likely be changed to helix anyway. After Kraken mess is purged it will be easier to move the whole thing to Helix from the third-party provider, so I'm leaving this open until that's done.
