### ISSUE TITLE
No User informations available / all channels are offline in the tabs

### ISSUE THREAD

**Issue by Lcqs1** [Chatterino/chatterino2#2883]
![grafik](https://user-images.githubusercontent.com/85742511/121680630-0e71d100-caba-11eb-81ad-bed51d769a25.png)
All Channels are marked as offline and when I try to get some user informations by clicking the Username, there ist no information available. I've tried to reinstall the app, but nothing changed.

**Comment by Mm2PL** [comment]
This is a change twitch made, you have to log in to see this info.

**Comment by Mm2PL** [comment]
Duplicates #1915
