### ISSUE TITLE
First message

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#2884]
**Describe your issue**
It's hard to see new viewers in chat, that's why Twitch has recently implemented an new feature that will highlight the first message of a user in chat.

Chatterino could highlight these messages as well. Maybe something similar to Channel Point Redemption Messages equally configurable.

https://twitter.com/TwitchSupport/status/1403049576278417425

Example first message:

```
@badge-info=;badges=glhf-pledge/1;client-nonce=5d2627b0cbe56fa05faf5420def4807d;color=#1E90FF;display-name=oldcoeur;emote-only=1;emotes=84608:0-7;first-msg=1;flags=;id=7412fea4-8683-4cc9-a506-4228127a5c2d;mod=0;room-id=62300805;subscriber=0;tmi-sent-ts=1623429859222;turbo=0;user-id=139147886;user-type= :oldcoeur!oldcoeur@oldcoeur.tmi.twitch.tv PRIVMSG #nymn :cmonBruh
```

Seems the tag `first-msg=1` can be used to detect this kind of message.

![image](https://user-images.githubusercontent.com/9765622/121725876-1d707780-caea-11eb-8f2a-e37c7996fcc5.png)

**Comment by Mm2PL** [comment]
These are apparently shown to mods only on webchat. [src](https://twitter.com/TwitchSupport/status/1403052620776939520#m) ![nitter screenshot](https://user-images.githubusercontent.com/25011746/121741787-7fcb7700-caee-11eb-8bec-2684ef544ef1.png)

**Comment by gempir** [comment]
Unfortunate, but still interesting though. 

If we ever want to built upon this for moderating purposes, like highlighting new accounts in general, FFZ has a pretty smart implementation based on the incremental way userids are generated currently.

https://github.com/FrankerFaceZ/Add-Ons/blob/master/src/new-account-highlighter/index.js

**Comment by Mm2PL** [comment]
Let's hope that the tag is sent to everyone. Related: https://github.com/Chatterino/chatterino2/issues/2525#issuecomment-804848697

**Comment by gempir** [comment]
Done in #3267
