### ISSUE TITLE
Constantly disconnecting

### ISSUE THREAD

**Issue by Barbiezita** [Chatterino/chatterino2#2888]
for a long time now my Chatterino keeps disconnecting and I don't know what to do to because I don't have many tabs open and even when I have like three it does not work 

![unknown](https://user-images.githubusercontent.com/85805954/121787197-1eadad00-cb9b-11eb-9ead-30eadc7fb4ea.png)

**Comment by Mm2PL** [comment]
> three tabs

How many splits do you have in the tabs?

**Comment by apa420** [comment]
@Barbiezita Is your internet connection steady?
You can test this by simply opening cmd and typing `ping www.twitch.tv /n 100`.
If you have packet loss there's nothing chatterino can do.

Please also change your title to Constantly disconnecting or something similar.

**Comment by Barbiezita** [comment]
> > three tabs
> 
> How many [splits](https://wiki.chatterino.com/Glossary.html#anatomy-of-a-chatterino-window) do you have in the tabs?

I had like 30 but I erased some and I think it's working now tanksss s2

**Comment by apa420** [comment]
I'm marking this issue as solved.
If you keep getting issues like this you could join the chatterino discord and ask for help there.
Otherwise please create an issue with the issue template next time.
