### ISSUE TITLE
Add a option to hide peoples international username 

### ISSUE THREAD

**Issue by jeffboys123** [Chatterino/chatterino2#2889]
FFZ just recently added the option to hide peoples international usernames or hide usernames so only one of them will show instead of having the username in brackets. I think this would be a good feature for most people, as I found out some people I talk to find it very annoying, 
![image](https://user-images.githubusercontent.com/71993748/121788604-685fbd00-cbc6-11eb-9891-f89b853306f5.png)
![image](https://user-images.githubusercontent.com/71993748/121788651-c2f91900-cbc6-11eb-901c-0802cd05cc31.png)

**Comment by Mm2PL** [comment]
This functionality already exists in Chatterino's code.
