### ISSUE TITLE
[IRC] Possible to send >512 byte message

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#2890]
**Describe your issue**
It is possible to send messages that are more than 512 bytes (this includes PRIVMSG and its UTF8), which are considered as malformed by some irc daemons. I suggest chatterino truncates such messages, ~just like twitch does~.

**OS and Chatterino Version**

Win 10 19042.928 Chatterino Nightly 2.3.0 (commit 2dca9a3, )

**Comment by pajlada** [comment]
@TETYYS Is this an IRC only issue? Or does this also apply to Twitch messages

**Comment by TETYYS** [comment]
IRC only

**Comment by hemirt** [comment]
i thought twitch supersets the IRC standard, does it not cut >512B messages either?

**Comment by Mm2PL** [comment]
Twitch generally refuses to send such a message relatively gracefully, by just not sending it, while *at least some* IRC servers can kill your connection.
