### ISSUE TITLE
Add visualization support for Compose Key on Linux

### ISSUE THREAD

**Issue by Chronophylos** [Chatterino/chatterino2#2894]
**Describe your issue**

X Org on Linux has a feature called the Compose Key. It allows you to press a key followed by a sequence of other keys to Unicode Characters or other strings.

see https://man.archlinux.org/man/Compose.5

Programs such as Visual Studio Code, Discord or Firefox show a visualization of your input while Chatterino does not show anything.

**Screenshots**
![firefox](https://0x0.st/-LkW.gif)

**OS and Chatterino Version**

Arch Linux, Chatterino build from 5512437f1bd5b2be7997b52bf36b04930446f3f1

**Comment by apa420** [comment]
Does this work with any other Qt application you have?
Visual Studio Code and Discord are Electron and Firefox is something else.

From what I can gather Qt supports this compose key but I'm unsure if there is a visual cue for it.

**Comment by Mm2PL** [comment]
I'm pretty sure this is a UI toolkit thing rather than application.

**Comment by Chronophylos** [comment]
I couldn't think of any other Qt Application to test this

**Comment by Mm2PL** [comment]
This is a thing on Arch as of 2022-08-12, I am using X11, ibus, chatterino [756bd90b](https://github.com/chatterino/chatterino2/commit/756bd90b) (modified)

Running on Arch Linux, kernel: 5.18.7-arch1-1. 
![2022-08-12_21-32](https://user-images.githubusercontent.com/25011746/184430202-73898010-b37e-41a4-a23d-4dd054206450.png)
