### ISSUE TITLE
Twitchemotes API died making emoteset queries fail to deliver data

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#2904]
**Describe your issue**

Twitchemotes literally just KILLED their entire API about an hour ago. All requests to chatterino-api fail.
This makes it, so all emotesets from Kraken that need to get their emoteset data fetched fail to set extra information about themselves - this results in most (emotesets fetched from IVR API get their emoteset data already, so those are not affected) sub emotes to not show up in emote picker.
You can still tab the Kraken emotes though. It's just emoteset data that's missing.

See related pajbot issue: https://github.com/pajbot/pajbot/issues/1276

**Screenshots**

![](https://cdn.zneix.eu/wcCfhEZ.png)

![pajaS](https://cdn.zneix.eu/UH6Is82.png)

**OS and Chatterino Version**

Arch GNU/Linux 🤓 master

**Comment by Mm2PL** [comment]
oh fuck

**Comment by telvann** [comment]
sub emotes are in the global tab now for me

**Comment by zneix** [comment]
> static sub emotes are in the global tab now for me (with nightly)

Yes, this is because Chatterino fails to set emoteset metadata and dumps them into Global tab assuming they're global.

**Comment by jazzyjae** [comment]
Glad I'm not the only one. Using colon helps, but I can't see newly added emotes when I shortcut.
