### ISSUE TITLE
Character counter font doesn't reset

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2917]
**What is the issue**

Exceeding 500 characters changes the character counter's font. Going back under 500 doesn't reset it. Changing zoom levels does.

**How to reproduce**

1. Set your zoom to 0.9x
2. Open two splits (for comparison)
3. Type 501 characters in one
4. And one in the other one
5. Replace the 501 characters with one
6. Observe that the font looks slightly different

**Screenshots**

![2021-06-24_15-50](https://user-images.githubusercontent.com/25011746/123275084-92cd4680-d4f3-11eb-8ab5-2ec58bb00421.png)

It's easier to see with more characters.
![2021-06-24_15-56](https://user-images.githubusercontent.com/25011746/123275624-02433600-d4f4-11eb-8ef8-7df9902d8100.png)

**OS and Chatterino Version**

Chatterino + Dankerino patches 826c56fe2cec1b1b2a6647ad6a19d3d3b76641c9 (based on upstream 74960bf4)

**Comment by zneix** [comment]
I've seen this issue couple times myself, but couldn't reproduce it properly. Thanks for providing good repro steps :+1:

**Comment by Mm2PL** [comment]
Actually, unsetting the custom font size itself is the cause of this behavior.
