### ISSUE TITLE
Mention users with a comma inconsistency

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#2918]
**Describe your issue**
With the changes implemented in f605221, mentioning a user at the end of a message adds a `,` to the mention, when it didn't do that before.

1. Start off your message with a `@`mention [tab completion]
2. Type something else [optional]
3. Finish your message with a `@`mention [tab completion]

The issue is specific to the actual menu, as disabling it causes the original logic to work again.

As an added note while testing this, it was noticed that right-clicking on a username to `@`mention them does not follow this original logic and the `,` appears at the end of messages, replicable before and after the menu was added.

**Screenshots**

https://i.imgur.com/l3FiISb.gif [ mm2pl/dankerino@59645ab equiv to 9fb5ef6 ]

https://i.imgur.com/CDFNPn8.gif [ 97b9bfb ]

**OS and Chatterino Version**
win10

**Comment by Mm2PL** [comment]
Can only replicate when username completion popup after @ is disabled and mention users with a comma is enabled.

**Comment by Mm2PL** [comment]
Code responsible for this https://github.com/Chatterino/chatterino2/blob/master/src/common/CompletionModel.cpp#L152

**Comment by Felanbird** [comment]
Fixed in #3060

**Comment by ALazyMeme** [comment]
Incorrect phrasing in issue smh
