### ISSUE TITLE
Chatterino for VODs

### ISSUE THREAD

**Issue by ghost** [Chatterino/chatterino2#292]
Using Chatterino for VODs would be amazing, maybe displaying the VOD chat that twitch already has but making it show on the Chatterino app somehow if that is possible. 
Having to link the specific VOD URL in the Chatterino app to just display the chat could work possibly.

**Comment by TETYYS** [comment]
`mpv` with `youtube-dl` already supports twitch VODs and using https://mpv.io/manual/stable/#json-ipc it would be a matter of synchronizing times with mpv playback and chat times

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
