### ISSUE TITLE
Version flag outputs to stderr instead of stdout

### ISSUE THREAD

**Issue by IS2511** [Chatterino/chatterino2#2928]
**Issue:**
When using `--version` flag Chatterino outputs version info to `stderr` instead of `stdout`. Most other programs output their version info to `stdout` (like `git` for example). In Chatterino's case I need to redirect `stderr` to `stdout` to catch the output in a variable. Probably not intended?

**Reproduce:**
```bash
┌─[is2511@mainPC]─[~]
└──╼ $V=`chatterino --version 2>&1`; echo "Var: $V"
Var: Chatterino 2.3.2 (commit 80506a862)
┌─[is2511@mainPC]─[~]
└──╼ $V=`chatterino --version`; echo "Var: $V"
Chatterino 2.3.2 (commit 80506a862)
Var: 

```

**OS and Chatterino version:**
OS: `Linux mainPC 5.10.0-6parrot1-amd64 #1 SMP Debian 5.10.28-6parrot1 (2021-04-12) x86_64 GNU/Linux`
Chatterino: `Chatterino 2.3.2 (commit 80506a862)`

**Comment by zneix** [comment]
We're using native Qt category logging, which uses `stderr` instead of `stdout`.
I believe I had a discussion in Twitch chat about version information using Qt categorized logging after we've introduced it (in #2206) and I personally think that it shouldn't use those categories, but I thought it didn't matter at all - now I see that maybe it's worth fixing :+1:

**Comment by pajlada** [comment]
Does it matter?

**Comment by IS2511** [comment]
> Does it matter?

I mean yeah, for scripting and stuff. Beginners would struggle to figure out this issue. It's inconvenient. Worth a fix imo.

**Comment by pajlada** [comment]
> > Does it matter?
> 
> I mean yeah, for scripting and stuff. Beginners would struggle to figure out this issue. It's inconvenient. Worth a fix imo.

If there's any standard we're missing let me know and I'll consider it a bug, for now I'm just considering this to be intended behaviour. "scripting and stuff" doesn't cut it to make a change for me.

**Comment by leon-richardt** [comment]
> If there's any standard we're missing let me know

Are you aware of any other application that also outputs version information to stderr instead of stdout?

**Comment by pajlada** [comment]
necro bump:

Basically, I didn't want to make an exception for `--version`. I'm doing it anyway since trying to redirect all output loses us Qt's "system logger" logic
