### ISSUE TITLE
Keeps crashing randomly

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#2941]
Chatterino keeps crashing randomly while seemingly not doing anything.
Got 2 dmp's if that is any help. ¯\_(ツ)_/¯
Could have been the chrome extension

[CrashDumps.zip](https://github.com/Chatterino/chatterino2/files/6741776/CrashDumps.zip)

Chatterino Nightly 2.3.3 (commit 6355742b6, )
Windows 10 pro, 21H1 (19043.1052)

**Comment by Trung0246** [comment]
Is this related to https://github.com/Chatterino/chatterino2/issues/2774 ?

**Comment by treuks** [comment]
I looked into the crash dumps. 
One of them is a heap corruption, the other one is about a pointer pointing at something incorrect.

Other than that, these dumps have not provided much information if at all.

**Comment by pajlada** [comment]
Closing this as there's nothing actionable for us at this time - if that changes feel free to re-open or create a new issue with more details.
