### ISSUE TITLE
image uploader

### ISSUE THREAD

**Issue by ukeesz** [Chatterino/chatterino2#2944]
image uploader don't working while link preview is enabled (i think its only with s-ul.eu and imgur, i.nuuls.com is fine)

![image](https://user-images.githubusercontent.com/86529374/124274336-6ba0f580-db41-11eb-9394-faea78eb38fe.png)

Windows 10, Chatterino Nightly 2.3.3

**Comment by Mm2PL** [comment]
Did you follow this guide when setting up the image uploader? https://wiki.chatterino.com/Image%20Uploader/

**Comment by zneix** [comment]
I'll just repost my comment here...

This doesn't seem like an issue with image uploader, but your config. Did you follow the example configuration on Chatterino wiki?

> don't working while link preview is enabled

Could you elaborate on this part? What does link preview has to do with that even?

**Comment by ukeesz** [comment]
idk, when link preveiw is enabled it looks like this 
![image](https://user-images.githubusercontent.com/86529374/124282515-36010a00-db4b-11eb-8375-96f8dfed6103.png)

when it's disabled everything is alright
![image](https://user-images.githubusercontent.com/86529374/124282696-69439900-db4b-11eb-8217-21b1d09a2f04.png)

**Comment by Mm2PL** [comment]
You're taking about the link preview / thumbnails feature, correct? Settings -> general -> Link previews (header) -> Enable and Also show thumbnails if available

2 lip 2021 15:38:32 ukeesz ***@***.***>:

**Comment by zneix** [comment]
Could you describe:
1. How do you take a screenhot?
1. How do you upload images with image uploader?
1. What is the output in the system message you get after uploading an image?

**Comment by zneix** [comment]
I see now that the second image you've posted is missing as well (`https://ukeesz.s-ul.eu/TjPSOO12.png`), this looks like your images are like one-time links and are delete right afterwards?

Regardless, this is not a Chatterino issue, but something on your end so I'm closing the issue however feel free to reply.

**Comment by Mm2PL** [comment]
Could it be that the link resolver checks the deletion link and accidentally deletes the image?

2 lip 2021 15:59:24 Paweł ***@***.***>:

**Comment by zneix** [comment]
> Could it be that the link resolver checks the deletion link and accidentally deletes the image? 2 lip 2021 

Oh yea, you're right. I think s-ul doesn't ask for any sort of confirmation.

**Comment by ukeesz** [comment]
i removed the deletion link and it's working rn tysm
