### ISSUE TITLE
NetworkRequest timeout timer starts before network request is sent

### ISSUE THREAD

**Issue by jupjohn** [Chatterino/chatterino2#2949]
**Describe your issue**
All network requests done via `NetworkRequest` can timeout when the network request hasn't been sent/has just begun.

Discussion took place on #2900 

**OS and Chatterino Version**
N/A

**Comment by jammehcow** [comment]
TL;DR of that PR thread: `QTimer` is started when the request is ready to be sent but the number of workers are limited so the request may not be executed instantly - prematurely marking the request as "timed out".
