### ISSUE TITLE
Add in-app logging of HTTP requests

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2960]
## Describe your issue

It would be nice to debug HTTP requests easely inside of the app.

## Proposed solutions

 - Adding a log into F10 debug popup
 - more logging
 - custom channel (kinda like `$$$`)

**Comment by jammehcow** [comment]
Is it worth adding a general log window to chatterino? Could be useful for debugging when it comes to the average user issue.
