### ISSUE TITLE
General wiki link

### ISSUE THREAD

**Issue by KararTY** [Chatterino/chatterino2#2965]
**Feature request**

Not sure if there's already an existing issue for this, but can there be a link to the Wiki somewhere? Maybe around the About button? 🤔
![image](https://user-images.githubusercontent.com/13697809/124412173-33223700-dd4e-11eb-9463-f07e00ddc0cd.png)

**Comment by Felanbird** [comment]
Probably a good idea, we have a few buttons that direct you to the wiki (filter/regex info) but nothing that specifies "HERE IS THE WIKI"

**Comment by xHeaveny** [comment]
Will be in the in my next PR
