### ISSUE TITLE
Chatterino Nightly Freezing

### ISSUE THREAD

**Issue by NonsoN** [Chatterino/chatterino2#2968]
Is there any fix to the chat freezing and then going super fast at times? It makes it really hard to get messages in on big streams like xqc's. In chats like these, it's much harder to see my own messages or non spam in comparison to the regular twitch chat. 

**OS and Chatterino Version**

        Windows 10, Chatterino Nightly 2

**Comment by leon-richardt** [comment]
https://wiki.chatterino.com/Help/#why-are-my-messages-being-sent-in-webchat-but-not-in-chatterino

**Comment by Mm2PL** [comment]
This is a Twitch issue, not a Chatterino one
