### ISSUE TITLE
What to do with TaggedUsers?

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#2972]
**Describe your issue**

`src/controllers/taggedusers/TaggedUser.{cpp,hpp}`, `src/controllers/taggedusers/TaggedUserModel.{cpp,hpp}` and [some](https://github.com/Chatterino/chatterino2/blob/master/src/singletons/Settings.hpp#L40) [remnants](https://github.com/Chatterino/chatterino2/blob/0a51252b761ac4a846725ce6b6e8cf8bba5efdf4/src/widgets/settingspages/ModerationPage.cpp#L195) (more links: [3/5](https://github.com/Chatterino/chatterino2/blob/f6052210428ee1b24792dfc3d021de37efcde1da/src/CMakeLists.txt#L107-L110) [4/5](https://github.com/Chatterino/chatterino2/blob/6355742b6ed01ff54b66752655e4c5c4290c0231/chatterino.pro#L168L-169) [5/5](https://github.com/Chatterino/chatterino2/blob/6355742b6ed01ff54b66752655e4c5c4290c0231/chatterino.pro#L398-L399)) have been in Chatterino's code since (at least) [2018](https://github.com/Chatterino/Chatterino2/commit/8c9be20f9#diff-531d11139cff54ca9f7790ea4ca28a974748f3aef976d2eb78240f39aff4c5f5R94-R106) if not before. None of this code is used AND even when I uncommented it. It's broken because `src/controllers/taggedusers/TaggedUserController.{cpp,hpp}` files are missing. What should we do with this code? 

@fourtf, since you wrote the code, I believe you should get the final say in this.

**OS and Chatterino Version**

current master cc9d44a0bbb57d2e52093dac37d4506c376170f1

**Comment by fourtf** [comment]
delete it?

**Comment by Felanbird** [comment]
Closed by #3208
