### ISSUE TITLE
New emotes that were added after animated emotes came out are missing. (Missing from emote menu, can't tab complete)

### ISSUE THREAD

**Issue by VulpesHD** [Chatterino/chatterino2#2977]
Tab completion does not work for new static emotes that were added after animated emotes came out.
They don't even show up in the emote menu or when you type "colon text"

Did some testing and it affects animated emotes too, so anything added after a certain point after animated emotes were already out.

Some examples:
[https://i.imgur.com/IMmPB8P.png](https://i.imgur.com/IMmPB8P.png)
[https://i.imgur.com/XJgeVE1.png](https://i.imgur.com/XJgeVE1.png)
[https://i.imgur.com/BDWQZfl.png](https://i.imgur.com/BDWQZfl.png)

**Comment by sando** [comment]
Duplicate of #2935

**Comment by VulpesHD** [comment]
Closing since its a duplicate and an already known issue.
