### ISSUE TITLE
messages not being sent in chatterino app 

### ISSUE THREAD

**Issue by terrarange** [Chatterino/chatterino2#2986]
When I type a message out and send it, it doesn't do anything. I can send messages in the normal twitch chat and they even appear in my chatterino but I can't type in chatterino itself.

**Comment by Felanbird** [comment]
https://wiki.chatterino.com/Help/#why-are-my-messages-being-sent-in-webchat-but-not-in-chatterino

**Comment by Mm2PL** [comment]
Duplicate of #2356
