### ISSUE TITLE
Animated emotes renders on top of emote modifiers.

### ISSUE THREAD

**Issue by williambulin** [Chatterino/chatterino2#2994]
**Describe your issue**
Animated emotes renders on top of emote modifiers.
Expected behavior: Have the animated emotes below emote modifiers, just like normal emotes.

**Screenshots**
Chatterino:
![Chatterino Screenshot](https://i.imgur.com/0bPfXDO.gif)
Web Chat (FFZ extension):
![Chatterino Screenshot](https://i.imgur.com/qUuGBdW.gif)

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 2.3.2

**Comment by Felanbird** [comment]
The implementation of emote modifiers was extremely lidl IIRC, so this being broken doesn't surprise me at all.

see 2d3fb89 & #1613
