### ISSUE TITLE
Animated emotes from Twitch itself (not BTTV) do not animate

### ISSUE THREAD

**Issue by astradamus** [Chatterino/chatterino2#3003]
It's all in the title. These emotes play fine in the web browser but are static (first frame only) in Chatterino. This is true under all conditions and in all chats, I have thoroughly inspected all settings and options, BTTV animated emotes play just fine, but Twitch's do not.

**Comment by Mm2PL** [comment]
This is fixed in latest nightly and (soon to be released) 2.3.3

**Comment by astradamus** [comment]
Whoops, when did Github switch to hiding all closed issues by default? That's... stupid lol. I just saw you have this issue reported lots of times as a result. Sorry about that! Thanks for the quick response :)
