### ISSUE TITLE
[Suggestion] Hide known bots from viewer list

### ISSUE THREAD

**Issue by Celuni** [Chatterino/chatterino2#3012]
Hey is it possible that you add a feature that allows us to hide or fad-out known twitch bots from the viewer list?

There are a few websites that list those bots:
https://twitchinsights.net/bots
https://twitchbots.info/api

**Comment by Mm2PL** [comment]
I wouldn't feel good with my chatterino loading bot lists from some shady websites.

**Comment by apa420** [comment]
I don't see this being useful in any way at all.
If anything it would cause confusion if you didn't see all users who are in chat in the viewer list.
The viewer list should display all chatters connected to chat, which includes the bots you mentioned and I'm unsure why chatterino should exclude them.

**Comment by zneix** [comment]
Aside from other concerns that mm2pl has shared, I don't like the idea of complicating already weird logic related to viewerlist and how it fetches users - what beenfit would it even give? I think such request is very niche and doesn't give any benefit.

Keep in mind that it would only make loading users upon opening a usercard slower, because upon adding them to the list we'd have to first call one or more external APIs and then filter every of those names. Now imagine opening a viewerlist in a channel like #xqcow while he's live with around 70k chatters...

**Comment by Celuni** [comment]
Fair enough I understand the concerns but I mean even if you have a .txt in your github repo there is nothing that leaks.
If you load that .txt at startup of Chatterino it's a matter of finding matching names.
I see like 15 bots in some channels and the real users kinda sink in and you'll only know if they chat.

**Comment by jammehcow** [comment]
> Fair enough I understand the concerns but I mean even if you have a .txt in your github repo there is nothing that leaks.

How it's done technically isn't the main concern people have; it's just not a useful feature for the **average** user. Even if they knew about it, what would be the likelihood that the average chatterino user would care? My educated guess is that it's an extremely small portion and not worth the added complexity in chatterino's codebase.

As 🐍 mentioned, how can we trust the accuracy of those lists? If they falsely identify a user as a bot you've just broke the list for someone wanting to see users in a channel.
You're more than welcome to fork this project and add it to your fork - it just isn't something the mainline chatterino appliciation needs.

Incoherent Friday thoughts finished 🙂

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/126021995-5f156433-3cbf-4142-875b-cfa6c3140a2e.png)
It took me less than 10 minutes to become a "known bot" on this well crafted list of "bots"

**Comment by Celuni** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/41973452/126021995-5f156433-3cbf-4142-875b-cfa6c3140a2e.png)
> It took me less than 10 minutes to become a "known bot" on this well crafted list of "bots"

You realize that felanbird is a bot right?
I don't care about seeing felanbird in my "Viewer list" because it's not a viewer!

**Comment by zneix** [comment]
> You realize that felanbird is a bot right?

But felandbird is a human, who just replied to your GitHub issue, not a bot...
