### ISSUE TITLE
Add Chatterino to the Winget/Window's Store Repository

### ISSUE THREAD

**Issue by Kaosarbitrium** [Chatterino/chatterino2#3020]
Microsoft has made an extension of the Windows Store's framework, presenting it into what is essentially their version of a Linux Package Manager. WinGet, said Package Manager, now past version 1.0 and getting a lot of interest.

So, here's the pitch: throw Chatterino up on the WinGet Package Manager, Microsoft tutorial available here: https://docs.microsoft.com/en-us/windows/package-manager/package/ , and let people download the latest stable release of Chatterino, or even the Beta releases and nightly update releases as well through separate packages, through the windows store and WinGet, vastly expanding the audience that comes across the program.

Only issue I may see with it is it's required, currently anyway, that you have a "Silent Install", ie no user input, for the application to be accepted. Thankfully Chatterino doesn't take up much room, so the biggest thing would be adding a script to auto-install the C++ updates and such from Microsoft if they're not already on the PC, rather than asking the user for input every time

**Comment by jammehcow** [comment]
![pajaDink](https://cdn.betterttv.net/emote/5fedbfca9d7d952e4059e40c/1x) @ALazyMeme do you want to take that as well? Might tie in with the Chocolatey package

**Comment by ALazyMeme** [comment]
I believe there was something in here about this: https://github.com/Chatterino/chatterino2/issues/2849
Chocolatey had it easier as it supports dependencies. This isn't really something I want to do unless winget had support for it: https://github.com/microsoft/winget-cli/issues/163

Other people are willing to try, but I'm too lazy to make a script just to install the vcredists.

**Comment by Felanbird** [comment]
Added in https://github.com/microsoft/winget-pkgs/pull/127421
![image](https://github.com/Chatterino/chatterino2/assets/41973452/ce186ff2-0676-4aec-ac74-9fa763f9be05)

**Comment by jingofett** [comment]
Any chance the updated build can be added?

**Comment by Nerixyz** [comment]
> Any chance the updated build can be added?

I opened https://github.com/Chatterino/chatterino2/pull/5365 to automatically add future releases to WinGet.
