### ISSUE TITLE
Blocking confirmation dialog

### ISSUE THREAD

**Issue by deadclicks** [Chatterino/chatterino2#3023]
Add a confirmation dialog when blocking a certain user from their popup, to avoid accidentally losing the followage (how long you followed a channel) of said user, as blocking also unfollows you from their channel.

**Comment by zneix** [comment]
Unfortunately, (un)following through Chatterino will soon be gone in general, see [Twitchdev forums announcement](https://discuss.dev.twitch.tv/t/deprecation-of-create-and-delete-follows-api-endpoints/32351).

I'm going to close this issue in favour of #1886, as it describes the same - usercard action is just different, but the same rule and request apply.

**Comment by Mm2PL** [comment]
@zneix this is about blocking/ignoring people, not follows.

**Comment by apa420** [comment]
Blocking is not part of the following api endpoint as far as I know.
