### ISSUE TITLE
Chatterino does not show the history of messages after startup.

### ISSUE THREAD

**Issue by lefikov** [Chatterino/chatterino2#3027]
**Describe the bug**
Hi, after starting Chatterino the message history won't load I tried restarting and reinstalling but nothing helped. It happened out of nowhere after I started Chatterino.

Is this a problem on my side? If so is there any way to fix it? :)

Thank you very much

**Chatterino version**
Chatternio 2.3.2

**OS**
Win 10

![Screenshot_1](https://user-images.githubusercontent.com/87543969/125993152-e3778b2e-f999-4ea0-ad60-f3b507951699.png)

**Comment by Mm2PL** [comment]
This is a problem with recent-messages not chatterino itself. I am sure @RAnders00 will resolve the problem as soon as he can.

**Comment by RAnders00** [comment]
I am sorry for the disruption in service. I believe the service should have been restored for everyone now.
