### ISSUE TITLE
Usernames in historic bans / timeouts aren't clickable.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#3030]
**Describe your issue**

Bans / timeouts loaded from recent-messages aren't processed the same way as from chat so they don't have usercard links added.

**Expected behavior**

You can click usernames from bans in historic messages.

**Actual behavior**

You can't

**OS and Chatterino Version**

Chatterino + Dankerino patches 2.3.3 4cc402af9027d0d9e4889673fa5bbcc0f24ce3c4 upstream faafbdaa

**Comment by zneix** [comment]
`CLEARCHAT` messages retrieved from recent-messages are actually converted to a `NOTICE` messages, so we'd need to change that logic first if we want to implement this.

See: https://github.com/Chatterino/chatterino2/blob/a84e62c6bbfdf7491baeeb7c248117db53886962/src/providers/twitch/TwitchChannel.cpp#L54-L95
