### ISSUE TITLE
Crash when typing colon inside whispers tab

### ISSUE THREAD

**Issue by heyimrendy** [Chatterino/chatterino2#3032]
**Describe your issue**
When we type single colon inside whispers tab Chatterino instantly quit, can't even copy paste the colon. I dont know since when the crash happened, just noticed recently. With commit 6022cd86eb655c98c300992e93efacbf0a63da25 also crash.

**Screenshots**

**OS and Chatterino Version**
Windows 10 Version 21H1, Chatterino Nightly 2.3.3 (commit 89b86b94e, )

**Comment by zneix** [comment]
@heyimrendy hey, thanks for the bug report! I've overseen some code in #2951, which was added to Chatterino 6 days ago. I've went ahead and fixed my mistake in #3033 - once checks finish on that PR a new nightly release should release in like 30-40 minutes. You can download it once it releases and it'll not have this bug anymore.
