### ISSUE TITLE
Highlights Crashing Chatterino

### ISSUE THREAD

**Issue by HoopsANZ** [Chatterino/chatterino2#3035]
Adding New Word is fine, changing colour of word will create crash. 

White dialogue box appears then crash happens. 
running 2.3.3

![image](https://user-images.githubusercontent.com/76925309/126054576-47527a59-6ee8-4c07-9db6-b692e5e3dce6.png)
![image](https://user-images.githubusercontent.com/76925309/126054579-35f3961f-20ca-414c-8929-932f3929c4be.png)

I have 38 highlight words. i know this is excessive, but i use it for moderating 4 partners and a bunch of affiliates

**Comment by zneix** [comment]
Please use issue templates, those exist for a reason.
Can you replicate this crash with any other Chatterino version? Please also include the version commit that your application is on. You can find full version information in Settings > About.

**Comment by HoopsANZ** [comment]
I clicked on the link that said "Bug Report" from a thread that i was linked to from the discord. Not my fault it linked me to here. 
![image](https://user-images.githubusercontent.com/76925309/126055493-10564d99-dffb-4b23-b533-6c8e5a1936f3.png)

Chatterino 2.3.3 (commit c8c28d7f5)
Built with Qt 5.15.2, Windows SDK, MSVC 192930038
Windows 21H1 (OS Build 19043.1110)

**Comment by Felanbird** [comment]
> I clicked on the link that said "Bug Report" from a thread that i was linked to from the discord.

I've asked for this comment to be updated to prevent any issues for anybody else in the future and it has been. 🙂

**Comment by Mm2PL** [comment]
Unable to replicate. Closing as stale, please create a new issue if the crash still is still there.
