### ISSUE TITLE
One sub emote from my channel missing

### ISSUE THREAD

**Issue by PilotoF-22** [Chatterino/chatterino2#3040]
Hello,

All emotes from my channel appears (free ones for followers, bits, tier 2 and tier3) but in tier 1 emotes there are only 4 emotes. One is missing. Find attached an image of the issue. 

Thanks!

![issue](https://user-images.githubusercontent.com/44830795/126130487-8275eed7-9069-4597-8783-24d46a2af4ef.PNG)

**Comment by sando** [comment]
Is it a newly created emote? If so, it was recently fixed in 7e13564c24120c4e8e5160d5279510fcda0ee024. You'll need to use the nightly build for now, or wait for the next beta/stable release.

**Comment by PilotoF-22** [comment]
It is, but it was added with other emotes at the same time that appear on the 8th row (free follower emotes, like the facepalm one). How can I download that version? I have the official web one now. Quite new to github haha. Thx btw for the quick answer!

**Comment by apa420** [comment]
From here https://github.com/Chatterino/chatterino2/releases/tag/nightly-build
