### ISSUE TITLE
Light mode optimisation / Fixes i would like to see

### ISSUE THREAD

**Issue by NS2555** [Chatterino/chatterino2#3043]
As a Chatterino light mode user (yes the single one), there were several issues found with the current light mode theme and here they are:

**1:** The color themes have the copy button icons switched, the light theme has the icons for the dark theme, and the dark theme has the icons for the light theme, which is clearly unintended behavior.
⠀
⠀
![qrxFH7VK6y](https://user-images.githubusercontent.com/18615981/126233224-b36db380-ec24-48d3-b4c5-b52a5ec5dc6d.png)

![TtJWRXPDdA](https://user-images.githubusercontent.com/18615981/126233335-8d0da941-e710-445f-afac-b6b3ab8e10b5.png)
⠀
⠀
⠀
**2:** The color for the automod, looks like it was intended for use with the dark themes only, as you can see on those examples below:

Here you can see the way it looks in the dark theme: ⬇️

![chatterino_B6Hzk4Qnh0](https://user-images.githubusercontent.com/18615981/126233828-012f5170-73e8-4f29-a2a5-4b7d628e47db.png) 
Here you can see the way it looks in the light theme: ⬇️

![chatterino_k12LUuqCGP](https://user-images.githubusercontent.com/18615981/126233971-c8739983-5468-42ba-a434-007fbf350922.png)

(Chatterino version: 2.3.3)
(Operating system: Windows 10)

**Comment by NS2555** [comment]
To fix the second part i suggest replacing the default color of #404040, to something more dynamic, and theme dependant, either it is using alpha colors, or using hardwired theme dependant colors, both of those are shown down below: 

The colors that would work with both themes if you use transparency:
(HEX with transparency on the left, RGBA on the right)

![inkscape_XioVYH6Nk3](https://user-images.githubusercontent.com/18615981/126238921-9ca94f67-4f86-4c26-8b06-94051a517151.png)

The separate colors if you CANNOT, or choose not to use transparency, and instead to use light theme colors for light theme and dark theme colors for the dark theme:
(Instead this time there will be 2 separate images)
RGB:

![inkscape_R6L84LNhu8](https://user-images.githubusercontent.com/18615981/126240315-43bf59b5-8a3b-4a86-b966-ebf097bb5a35.png)
HEX:

![inkscape_kQgzTKfvas](https://user-images.githubusercontent.com/18615981/126240748-ad405f4d-fb34-443b-b764-56f58b45d37c.png)

**Comment by jammehcow** [comment]
If you split these into 2 separate issues and close this one that would be much appreciated.
Also please use the issue template that's suggested when creating an issue.

**Comment by NS2555** [comment]
![dankCircle](https://user-images.githubusercontent.com/18615981/126263316-3c0bdc01-6aba-4881-9602-5f6fdf553d31.gif) Closing issue.
