### ISSUE TITLE
Certain message types not being logged to disk

### ISSUE THREAD

**Issue by ConnorKrammer** [Chatterino/chatterino2#3046]
**Overview**
Chatterino is failing to log certain kinds of messages. Specifically I have noticed that the following kinds of messages are affected:
- "{channel} is live" upon connecting
- channel point redemption messages

**Screenshots**
Screenshots of examples comparing Chatterino message list when live and then the log produced on the same messages.

"{channel is live}":
![screenshot  2021-07-20 03-18-59](https://user-images.githubusercontent.com/1044441/126296146-a3ad5a78-013c-494a-ad83-087972ea99c2.png)
![screenshot  2021-07-20 03-10-27](https://user-images.githubusercontent.com/1044441/126296175-7acdfff7-3475-477f-b161-3f706cf320d8.png)

Channel point redemptions:
![screenshot  2021-07-20 03-12-14](https://user-images.githubusercontent.com/1044441/126296283-816b60f8-0e00-4726-8a47-b18523ae507a.png)
![screenshot  2021-07-20 03-12-31](https://user-images.githubusercontent.com/1044441/126296300-59ad3e58-96c9-4d40-bab4-d4fa534f68b2.png)

Notice how a line is still created for each message in the log, and the correct timestamp is written out, even though the message content is not. (This indicates that the logging system is probably still receiving each message, but for some reason isn't writing anything—presumably because it doesn't know how to handle that message type, but it might be surprising that this isn't raising a warning in the process).

Note that I don't have an example of the channel point logging issue for redeems associated with a line of text, such as "highlight this message" or similar redeems, and I am unsure how they are affected.

**OS and Chatterino Version**
Windows 10, Chatterino 2.3.2 (commit 6732b25f3)

**Comment by ConnorKrammer** [comment]
Additional detail: "now hosting" messages are not logged, but "exiting host mode" messages *are*:

"now hosting":
![screenshot  2021-07-20 11-04-49 (1)](https://user-images.githubusercontent.com/1044441/126365937-97ec968a-bbdc-4604-a401-d15ddb16c74f.png)
![screenshot  2021-07-20 11-04-48](https://user-images.githubusercontent.com/1044441/126366180-17b15831-1c3d-41b2-9cb6-fe4d3a1bae33.png)

"exiting host mode":
![screenshot  2021-07-20 11-08-33 (1)](https://user-images.githubusercontent.com/1044441/126366558-970d5dac-4836-4af2-9d9a-27981d82d861.png)
![screenshot  2021-07-20 11-08-33](https://user-images.githubusercontent.com/1044441/126366571-61a894c2-cb23-4289-9c4c-f0a9e326bb19.png)

**Comment by Mm2PL** [comment]
Please update to the latest nightly. I'm pretty sure most of the issues you are talking about are fixed.

**Comment by ConnorKrammer** [comment]
I updated to the nightly and it looks like these issues are indeed fixed. Thanks!
