### ISSUE TITLE
Chatterino will not open

### ISSUE THREAD

**Issue by BigSpinich** [Chatterino/chatterino2#3049]
Chatterino will not open, what's weird is it was working perfectly fine earlier today, I attempted to download the latest version of chatterino and It did not work and my earlier version stopped opening as well.

Screenshots are what happens when I try to open chatterino

![Screenshot (118)](https://user-images.githubusercontent.com/87722496/126382704-a49d25b1-255a-40eb-aeb9-59aba35564f7.png)
![Screenshot (120)](https://user-images.githubusercontent.com/87722496/126382708-24ee3610-676b-4c0b-b9fd-59f586e619ca.png)
![Screenshot (117)](https://user-images.githubusercontent.com/87722496/126382710-780eacd9-fa5a-4565-8634-1e6cd0bf537d.png)
![Screenshot (119)](https://user-images.githubusercontent.com/87722496/126382712-9d3803ab-1799-4ecd-a10c-91597a21075c.png)

        Windows 10, Chatterino 2.3.0

**Comment by zneix** [comment]
@BigSpinich did you try steps from https://wiki.chatterino.com/Help/#basic-troubleshooting?

**Comment by BigSpinich** [comment]
Well it fixed the VCRUNTIME140 error but there are now new ones, thanks for the help though


![Screenshot (122)](https://user-images.githubusercontent.com/87722496/126420042-92239139-964c-40c1-bca8-c7dcf128ddcc.png)
![Screenshot (121)](https://user-images.githubusercontent.com/87722496/126420043-aa4757b0-8493-4f39-8a24-e1bdd7ede194.png)
![Screenshot (124)](https://user-images.githubusercontent.com/87722496/126420044-7c1fd1ac-8cde-4ebb-9139-606cf5d74f79.png)
![Screenshot (123)](https://user-images.githubusercontent.com/87722496/126420047-9a144f45-6be5-473c-b079-af38f52cfa75.png)

**Comment by zneix** [comment]
@BigSpinich how did you obtain the newer version of Chatterino? Did you download nightly from our GitHub? These errors signify that the Chatterino version you're trying to launch is lacking basic libraries that it needs to even start. Can you try downloading installer for Chatterino 2.3.2 from the website, installing it and then see if it works? If 2.3.2 will work after reinstall, you might give nightly a try, but please make sure you'll follow [this guide](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build).

**Comment by BigSpinich** [comment]
oh my ok. yeah tysm it works, i tried to install chatterino nightly without "base" chatterino installed 1st

basically installing the vcredist worked but i was dumb and skipped a step, once again thanks for the help, you are a life saver
<3
