### ISSUE TITLE
Feature request: jump to message context

### ISSUE THREAD

**Issue by ConnorKrammer** [Chatterino/chatterino2#3054]
Certain parts of Chatterino will display filtered messages, removed from their original context. Examples include the messages in the /mentions tab, messages shown when using search, and messages shown in a user card when you click on their username.

It would be nice to be able to jump to the original context of messages like these via the context menu where you also see options like "copy message" and "copy full message". Messages frequently don't make sense out of context and scrolling through a large backlog is largely untenable (it being much easier, though not convenient, to find the log file if you have logging enabled and use a text editor to search through it—though that doesn't work for backlog fetched upon joining a channel for the first time, because that is not logged).

**Comment by jammehcow** [comment]
Could tie into #1912

**Comment by Felanbird** [comment]
Added in #3953
