### ISSUE TITLE
DOSBox stops playing T-Rex - Amigaphile while chatterino is focused

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#3059]
**Describe your issue**
DOSBox loses audio when chatterino is in focus (in my particular case, when playing [T-Rex - Amigaphile](https://www.pouet.net/prod.php?which=514). **This does not happen with any other program I have open**

Animation in DOSBox continues as usual in background, but audio gets muted

**Screenshots**

https://user-images.githubusercontent.com/3091645/126564771-f3497f6d-e481-455e-b319-0b90db3bdccc.mp4

**OS and Chatterino Version**
Win10 20H2 19042.1052
Chatterino Nightly 2.3.2 (commit f9ddd5303, )

**Comment by apa420** [comment]
Not worth fixing :)
