### ISSUE TITLE
Chatterino has a memory usage problem

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#3062]
**Describe your issue**
Chatterino either leaks or retains too much memory for something. Memory usage seems to increase over time, but not linearly - for example my current chatterino instance uses 1.67GB private bytes for 3d3h runtime.

Applications like [MTuner](https://github.com/milostosic/MTuner) might help to find the cause.

**Screenshots**
![ProcessHacker_hkQ4qxOm6F](https://user-images.githubusercontent.com/3091645/126764261-eccc1866-7394-451c-a299-c9ced0db8250.png)

**OS and Chatterino Version**
Win10 20H2 19042.1052
Chatterino Nightly 2.3.2 (commit f9ddd5303, )

**Comment by Mm2PL** [comment]
Maybe the debug popup (F10) can help.
cf. my one, after a day or so of running 
![2021-07-23_13-52](https://user-images.githubusercontent.com/25011746/126778077-542980d3-a6f6-45b6-bc17-72da9cde65aa.png)

**Comment by TETYYS** [comment]
lots of message layout elements

![chatterino_nJs5uu4Kxd](https://user-images.githubusercontent.com/3091645/126778188-48ed8ca0-a373-421b-8fce-cd3755350f71.png)

**Comment by Mm2PL** [comment]
I'm sure messages are leaked somewhere (I had no channels but there were messages) but I can't replicate it consistently.

**Comment by TETYYS** [comment]
Yeah, seems like it. I deleted and recreated a couple of splits and managed to get it down to 700k, but I see the number going down sometimes, so there are situations where layout elements are deleted

**Comment by KararTY** [comment]
Is it maybe related to the amount of loaded animated emotes?

In your screenshot you have 1800 animated emotes, and my own count of 837 animated emotes puts my mem usage at 900 MB.
![image](https://user-images.githubusercontent.com/13697809/126794497-c7f71688-fe1e-45de-8aa5-69aabf48eeec.png)

I test this by going into channels with a lot of animated BTTV emotes and opening up the emote window and my memory usage consistently goes up and stays that high until I close the tab: https://streamable.com/eqxqcn

**Comment by ALazyMeme** [comment]
Yes I'm also experiencing this high ram usage. As noticed today, my ram usage was up to 1.6gb. After restarting, it dropped down to 600mb.

When I started testing it, I was on 400mb after a fresh restart with emote hover and link previews turned off. @KararTY suggested I open emote windows in all splits to load the animated emotes. I'm now at 944mb (this didn't change from me going afk):

![image](https://user-images.githubusercontent.com/12804673/129036073-6f9c224a-863e-4038-ad3e-86d071af9233.png)

**Comment by ALazyMeme** [comment]
I went through all my splits today running the !bttvemotes command. I've been at home all day and had chatterino running. 390mb of ram being used.
After running said commands, I'm now up to 1gb being used.

![image](https://user-images.githubusercontent.com/12804673/129179746-2ba04d7b-62d5-4c55-b261-c1bf3cefe100.png)

![image](https://user-images.githubusercontent.com/12804673/129179766-4045e074-26e7-497a-8a5f-2c6718840f50.png)

**Comment by Mm2PL** [comment]
I reached 1.5G of memory today 

![https://i.imgur.com/dH69KMk.png](https://i.imgur.com/dH69KMk.png)

**Comment by TETYYS** [comment]
1.83GB with lower statistics except drawing buffers
![chatterino_Sw1HUHFGiG](https://user-images.githubusercontent.com/3091645/129461825-9aa81983-19fc-4924-8cb3-5ecf07bd4ea1.png)

**Comment by jammehcow** [comment]
4.3GB, seen it sit around 5GB later on in the day.
![image](https://user-images.githubusercontent.com/4962764/129462155-ccc4422c-d2ab-4e29-85ca-619d26089e9d.png)

**Comment by apa420** [comment]
Isn't most of the memory usage because of animated emotes loaded into ram?
BTTV has a size limit of 1mb (I think) on gifs which would mean having, let's say 1471 animated images, is ~1.44GB of memory if every animted has max size limit.

**Comment by Mm2PL** [comment]
A little bit of a useless bump.
IMO Chatterino should free unused images from memory but keep the cache and just reload from it. This could save us like half the usage of a high-uptime instance by my guesstimating.

**Comment by TETYYS** [comment]
or memory map the files?

**Comment by apa420** [comment]
It might be worth doing something like unloading all emotes in a chat if you haven't looked at a split of that chat in the past 5 min or something similar. This approach might cause too much disk read though. Also might be very hard to implement, unsure.

Memory mapping might also be a good approach, but only really works if emotes have a lot of overlap between channels. I suspect the biggest issue are the animated emotes and do most channels have similar ones?

**Comment by LosFarmosCTL** [comment]
> Memory mapping might also be a good approach, but only really works if emotes have a lot of overlap between channels. I suspect the biggest issue are the animated emotes and do most channels have similar ones?

While there are a lot of channel-unique animated emotes, a lot of the common ones are still shared across hundreds or thousands of chats. I suspect that this would make a pretty noticeable difference.

**Comment by iProdigy** [comment]
Another possible optimization: instead of always pulling `default` for twitch emotes, could just cache `static` if the `animateEmotes` setting is disabled (tho extra logic is needed if the option is toggled)

**Comment by TETYYS** [comment]
with PR #3915 I still have an instance with 1.78GB usage, process started 3 days and 9 hours ago
![chatterino_M3N4Foohhx](https://user-images.githubusercontent.com/3091645/190271150-16973514-a39a-4d3b-9595-1553fec6b963.png)

**Comment by pajlada** [comment]
> with PR #3915 I still have an instance with 1.78GB usage, process started 3 days and 9 hours ago ![chatterino_M3N4Foohhx](https://user-images.githubusercontent.com/3091645/190271150-16973514-a39a-4d3b-9595-1553fec6b963.png)

keep it running and see how it increases :smiling_imp:

**Comment by TETYYS** [comment]
I have reached 2.78GB with 11 days uptime before I wanted to play BeamNG.Drive so I had to restart chatterino

**Comment by pajlada** [comment]
We're more aggressive about releasing emotes now, closing this but feel free to re-open it if you feel like the latest nightly is still eating your memory like crazy.
