### ISSUE TITLE
Feature request:  disable/higher colored username cache

### ISSUE THREAD

**Issue by StephanBruh** [Chatterino/chatterino2#3063]
Would be nice to either disable the colored username cache or set a custom amount of users its caching, to fix the colored username again. Danks like me are very attached to colored usernames. Kind of a scuffed solution to the problem so I can understand if you close this issue, just wanted to maybe suggest a temporary fix.

**Comment by Mm2PL** [comment]
I'd rather like a full fix to the colored @-s feature, rather than a patch like this. Even if it means I'll have to wait longer to have it fully working.

**Comment by StephanBruh** [comment]
Totally understable

**Comment by pajlada** [comment]
I don't think tweaking this value is something we'd want to have as an in-app setting. Once we're bug-free in this area we can look into tweaking it if it still feels off.

Closing in favour of #2822
