### ISSUE TITLE
Whispers don't respect user highlight rules

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3064]
**Describe your issue**

When a user you have highlighted whispers you, it will show up in your mentions despite having "show in mentions" disabled.

1. Add a user to highlights
2. Un-toggle "Show in Mentions"
3. Have said user whisper you
4. See the whisper in #/mentions 
5. 🐧

**Screenshots**
![image](https://user-images.githubusercontent.com/41973452/126842275-611ee23e-1cac-4beb-9a9e-f210fccd902a.png)

**OS and Chatterino Version**
windows 10 ae9f92de

**Comment by leon-richardt** [comment]
Could be possibly be fixed in conjunction with #2731

**Comment by Mm2PL** [comment]
Can reproduce on bdf45c408ac53c5ff843f1949f54d2687fa4641a

**Comment by Felanbird** [comment]
As a bandage fix for this issue, the filter `!(channel.name == "/whispers")` can be applied to your mentions tab, but this will filter out correctly working mentions when a highlighted phrase is triggered in a whisper.

**Comment by Felanbird** [comment]
Probably fixed by #4389
