### ISSUE TITLE
Messages are not separated by line breaks when copied to the clipboard

### ISSUE THREAD

**Issue by ConnorKrammer** [Chatterino/chatterino2#3066]
**Description**
Copying and then pasting multiple messages does not insert newlines between comments. All messages are run together on a single line.

**Proposed fix**
When copying multiple messages, insert line breaks in between messages so that when pasted, each message occupies its own line.

**OS and Chatterino Version**
Windows 10
Chatterino 2.3.3 (commit c8c28d7f5)

**Comment by Felanbird** [comment]
This is the sort of issue that is well known but I assume everybody just accepted, as when I read this issue my first thought was 
"Yeah it's been like that forever".
So opening this issue is a 👍

**Comment by Nerixyz** [comment]
Fixed in https://github.com/Chatterino/chatterino2/pull/4812.
