### ISSUE TITLE
Here is why you can't follow/unfollow from chatterino.

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#3076]
I'm placing this issue here to prevent duplicates. YES WE KNOW ABOUT THIS. we cannot do anything.

Twitch are officially removing this functionality with **no replacement**: https://discuss.dev.twitch.tv/t/deprecation-of-create-and-delete-follows-api-endpoints/32351 apparently to stop follow bots.

**OS and Chatterino Version**

ANY that ever existed.

**Comment by Coldblackice** [comment]
Ahh big RIP ☹️

**Comment by Mm2PL** [comment]
It's been well over a month since I opened this issue to prevent duplicates. It's about time to close it.

**Comment by 12932** [comment]
Implement through GQL?

**Comment by LosFarmosCTL** [comment]
> Implement through GQL?

Using GQL is against Twitch Developer TOS.

**Comment by 12932** [comment]
> > Implement through GQL?
> 
> Using GQL is against Twitch Developer TOS.

Is that something Chatterino/Chatterino developers have agreed to? I certainly don't agree to it

**Comment by LosFarmosCTL** [comment]
https://discuss.dev.twitch.tv/t/is-it-legal-to-use-https-gql-twitch-tv-gql-endpoint/21811

While there is no clear “You cannot use this GQL endpoint” somewhere on Twitch’s website, it is at least in conflict with some of their guidelines and could, if twitch wants to result in actions against your account or you as a person.

Use at your own risk, I have so far not seen Twitch take any specific actions against individuals using it, but definitely not something for chatterino to implement.
