### ISSUE TITLE
Not showing all emotes

### ISSUE THREAD

**Issue by pongosik** [Chatterino/chatterino2#3079]
**Describe your issue**
Chatterino doesn't show all emotes from a channel that im subbed to. It shows only 6 out of 9 emotes that i can use. It's kinda frustrating cuz i can't just type an emote and click TAB to finish the emote.

**Screenshots**

![Screenshot_245](https://user-images.githubusercontent.com/88090970/127318841-19cfaa50-6017-42f0-90ba-9b42e36d148e.png)
![Screenshot_246](https://user-images.githubusercontent.com/88090970/127318866-57d4256b-675d-466b-b31e-ab0f101e20ca.png)

**OS and Chatterino Version**
Windows 7, Chatterino 2.3.3

**Comment by apa420** [comment]
https://github.com/Chatterino/chatterino2/issues/3040#issuecomment-882367611

Duplicate of #3040
