### ISSUE TITLE
Add `channel.live` flag for user defined filters.

### ISSUE THREAD

**Issue by NotNotQuinn** [Chatterino/chatterino2#3087]
**Describe your issue**

There is currently no way to check if a channel is live via filters, I wanted to create a filter to block online chat, as I didn't want to see it. (Just close it 4Head)
I personally think this filter system along with some imagination and more values could work wonders!

https://github.com/Chatterino/chatterino2/blob/770b9f263b947b7fc1b293bcd29878463e97d534/src/controllers/filters/parser/FilterParser.cpp#L65-L84

I propose `channel.live`, a boolean value showing whether the channel is live.

**OS and Chatterino Version**

All verisons please 👍

**Comment by Felanbird** [comment]
I had someone ask me if we had the functionality for something similar to this in the past few days, so I think it is something that would be wanted.

**Comment by Mm2PL** [comment]
Doesn't look too bad to implement.
