### ISSUE TITLE
Blocked users' redemptions are visible in chat

### ISSUE THREAD

**Issue by Supinic** [Chatterino/chatterino2#3098]
If a user is blocked (via Twitch) and uses a redemption without text, the redemption is still visible in chat. For reference, twitch web chat has these redemptions hidden.

This only applies to redemptions without text - if I recall correctly, those are not sent via IRC, unlike those with text. As far as I'm concerned, this behavior is up to clients to implement as the redemptions are sent regardless of blocks.

**Comment by iProdigy** [comment]
This is related to #2767 - fixing this would require paginating through the full list of blocks to determine the `user_id`s whos redemptions should not be shown
