### ISSUE TITLE
Emote/user tab completion completes using wrong word

### ISSUE THREAD

**Issue by jupjohn** [Chatterino/chatterino2#3101]
**Describe your issue**
Tab completion of emotes/usernames can also complete when moving to prior word.

*Steps to reproduce*
 1. Type a single word
 2. Type another word and tab complete to an emote/user
 3. Press left arrow until you are at the last character of the first word
 4. Press tab again

*Expected behaviour*
Previous word tries to complete using the word

*Observed behaviour*
Previous word thinks it's the second word so tried to complete using those characters

**Screenshots**
https://user-images.githubusercontent.com/4962764/127768320-e14afc52-4b84-4ff3-ab03-c604c6f248e0.mp4

**OS and Chatterino Version**
Arch Linux (N/A), Chatterino 2.3.3 (commit ae9f92de)

This is a hard one to explain (and title), hope the vid does it justice.

**Comment by Mm2PL** [comment]
Can reproduce on ae9f92de

**Comment by xHeaveny** [comment]
can also reproduce on `3cb1e51`

**Comment by M4tthewDE** [comment]
I did some investigation and it looks like the completer doesn't respect changing the cursor.
This happens as well if the cursor is changed with the mouse or the entire content of the textbox with up-arrow/down-arrow.
This issue could probably be solved by adding a check inside of `ResizingTextEdit::keyPressEvent` for those specific events.
