### ISSUE TITLE
Disconnecting and Reconnecting on a continuous loop

### ISSUE THREAD

**Issue by stealthytaters** [Chatterino/chatterino2#3106]
Just today, an issue started occurring where all my twitch channel tabs started to reconnect and disconnect on a loop. I know this has been a documented issue before but I have less than 100 twitch tabs (less than 80 in fact) and I didn't add any recently that should have caused this behavior. I also haven't had any changes in network connectivity. It also seems version-less as an older version of Chatterino on my personal laptop also had this start randomly occurring at the same time. So far I've tried restarting my router (even though there has been no network issues), opening Chatterino as an admin, restarting computer, and uninstalling and re-installing Chatterino.

**Screenshots**
![image](https://user-images.githubusercontent.com/88351624/127931422-8086bbc8-bf47-447e-b9d5-7eb786a8a81a.png)
**OS and Chatterino Version**
        Windows 10, Chatterino 2.3.2 on PC and Windows 10, Chatterino 2.2.2-fix on laptop.

**Comment by Mm2PL** [comment]
we know, it's mostly a twitch issue

**Comment by stealthytaters** [comment]
> we know, it's mostly a twitch issue

Oh really? Is this documented somewhere else I could look to understand the situation? Thanks!

**Comment by Mm2PL** [comment]
You can start a Chatterino with a single channel (`-c` CLI argument) and it should work.

**Comment by Mm2PL** [comment]
duplicates #2245

**Comment by zneix** [comment]
> duplicates #2245

Actually false, please see #3107
