### ISSUE TITLE
Keep filters when opening a split as a popout

### ISSUE THREAD

**Issue by LosFarmosCTL** [Chatterino/chatterino2#3113]
**Describe your issue**

When opening a split as a popout by using CTRL/CMD + N right now, the resulting popout window does not keep any filters present in the split before active. Might be an intended behavior, might not be idk, but it would definitely be really handy to have an option to keep filters active.

I have some chats where i have up to 5 or so filters enabled and re-enabling them every time i want that chat as a separate window is really annoying.

**OS and Chatterino Version**

macOS Big Sur, Chatterino 2.3.3

**Comment by LosFarmosCTL** [comment]
Could potentially be an option in settings or a new keybinding like CTRL/CMD + ALT/OPTION + N to keep filters active, if the intended behavior is not to keep them.

**Comment by talneoran** [comment]
This also applies to whether or not moderation mode is active in the split.
Currently popping out a split only creates a new window with a single tab and split with the same channel:
https://github.com/Chatterino/chatterino2/blob/95044efeedd8315ac700c4242e528d203da36a01/src/widgets/splits/Split.cpp#L618-L630

Also, the title should probably be changed to reflect that this is referring to opening a **split** in a popup and not a tab, I'm working on the tab case in #3082 and could look into this as well.

**Comment by LosFarmosCTL** [comment]
> Also, the title should probably be changed to reflect that this is referring to opening a split in a popup and not a tab, I'm working on the tab case in #3082 and could look into this as well.

Oh yeah i definitely meant to write split I think i might have genuinely just written tab because i saw your PR just before writing this issue, thats what made me think about the current behavior in the first place.
