### ISSUE TITLE
Twitchemotes link in emote context menu not working anymore

### ISSUE THREAD

**Issue by LosFarmosCTL** [Chatterino/chatterino2#3114]
**Describe your issue**

The context menu currently appearing when secondary/right clicking on an emote in chat is still using the twitchemotes.com link for subemotes, but due to that site being basically useless now, and the link structure being changed none of the links actually work anymore.
I do not know if there is any discussion internally or something about what to replace it with, but right now the functionality is completely broken.

**OS and Chatterino Version**

macOS Big Sur, Chatterino 2.3.3

**Comment by ALazyMeme** [comment]
To clarify: the 1x, 2x and 3x buttons still work. Just the TwitchEmotes links don't work.

**Comment by ALazyMeme** [comment]
It's possible that twitchemotes have removed v1 fetching altogether. Which would make sense, since a lot of forsen's basic emotes aren't on their website:
![image](https://user-images.githubusercontent.com/12804673/128262243-70ce39d8-64a1-4080-b51c-862eefb737de.png)

The link format has also changed
Current Chatterino Implementation: https://twitchemotes.com/emotes/emotesv2_93c0aa2b0d1f4ab0825a3c83ece9b200
TwitchEmotes: https://twitchemotes.com/channels/22484632/emotes/emotesv2_93c0aa2b0d1f4ab0825a3c83ece9b200

**Comment by LosFarmosCTL** [comment]
> It's possible that twitchemotes have removed v1 fetching altogether. Which would make sense, since a lot of forsen's basic emotes aren't on their website

I am honestly right now completely lost on just how exactly their website is broken.
I.e. for forsen there are only all basic emotes missing right now, while for basically all other channels its just the animated ones that are not there.

I feel like twitchemotes just might not be a reliable source anymore going forward, at least for my personal use, i.e. supibot aliases or bot commands, I have completely replaced it for my personal use, i.e. supibot aliases or bot commands, with cbdg's [emotes.raccatta.cc](emotes.raccatta.cc) but idk if that's a reliable enough source going into the future.

If there was some service the devs could agree upon I could take a look into implementing it.

**Comment by ALazyMeme** [comment]
cbdg's website looks nice, but there's no individual pages for emotes

What if we just removed the twitchemotes link altogether and just left the 3 sized options?

**Comment by LosFarmosCTL** [comment]
> What if we just removed the twitchemotes link altogether and just left the 3 sized options?

Personally i wouldn't have a problem with that, i mostly use bots to look up emotes anyways, i can't remember the last time i used the chatterino menu for it.

Not sure if other people do use it though, but right now i don't really know a good site chatterino could link to.

**Comment by zneix** [comment]
See https://github.com/chatterino/chatterino2/issues/2745#issuecomment-864577886

I'd remove it already but I was just too lazy.
