### ISSUE TITLE
Chatterino doesn't disconnect but only some channels load

### ISSUE THREAD

**Issue by Bushwookie000** [Chatterino/chatterino2#3116]
I have more than 20 tabs and it doesn't disconnect but only some channels actually load.

![VAAfV](https://user-images.githubusercontent.com/88451357/128221706-e06a13ca-de93-426c-9518-48c87ec83c7d.png)

 Windows 10, Chatterino Nightly 7.3.3

**Comment by Mm2PL** [comment]
Same issue as #3107 behavior was changed by twitch.

**Comment by leon-richardt** [comment]
(In particular, see https://github.com/Chatterino/chatterino2/issues/3107#issuecomment-892283337 explaining this in more detail.)
