### ISSUE TITLE
'Show Deletions of Single Messages` not handling mod only versions of the messages.

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3119]
**Describe your issue**

The setting does not handle the variation of the message that mods receive, stating who deleted the message.

1. Delete a message with the setting on - see two messages related to this deletion.
2. Delete a message with the setting off - still see one message related to this deletion.

**Screenshots**

setting on
![image](https://user-images.githubusercontent.com/41973452/128257855-7235832f-aec4-47fc-a31b-27d846e6d51f.png)

setting off
![image](https://user-images.githubusercontent.com/41973452/128257898-1d8fd53e-792d-4454-afc4-7dbba8b1f5c6.png)

Note: `The message from x is deleted` is unrelated and specific to the fact that you pressed the button, only you can see it.

**OS and Chatterino Version**
windows 10 | Tested on ae9f92de & `#3115` checked out and built (Rate Limit JOIN's PR)

**note** 
it was an oversight btw 
![image](https://user-images.githubusercontent.com/41973452/128259467-17e600d7-33e9-44d4-9cb5-d53fa19f19df.png)

**Comment by Mm2PL** [comment]
I would assign myself if i could, github doesn't show me the thing to assign myself xd
