### ISSUE TITLE
Ctrl+Enter not working

### ISSUE THREAD

**Issue by BigSpinich** [Chatterino/chatterino2#3124]
**Describe your issue**
Ctrl+Enter command is not working
- Allow typing duplicate messages is enabled
- Ctrl+Enter does not enter my last typed message

Ctrl+Enter does nothing for me and I've heard its supposed to enter my last typed message

**OS and Chatterino Version**
Windows 10, Chatterino 2.3.0

**Comment by talneoran** [comment]
Just to make sure, the functionality of Ctrl+Enter is to allow sending a message without clearing it from the input box (thus allowing continous sending of the same message). From your description it sounds like you're expecting it to send the previous message you sent, are you trying to do it with the input box empty?

**Comment by Mm2PL** [comment]
You might be misunderstanding the function of <kbd>Ctrl+Return</kbd>. It is supposed to send a message without clearing the input box, not send the last message. So if you press with the input box empty <kbd>Ctrl+Return</kbd> it won't do anything.

**Comment by BigSpinich** [comment]
ah ok im dumb

**Comment by leon-richardt** [comment]
To get the previous message back in the text input, you can press the <kbd>Arrow Up</kbd> while the text input is focused.
