### ISSUE TITLE
Badge highlighting shows wrong colors

### ISSUE THREAD

**Issue by ReggX** [Chatterino/chatterino2#3132]
**Describe your issue**
I have set up badge highlighting to be similar to my FFZ setup.

But as far as I can see different badges all have the same color. (see screenshots)

**Screenshots**
Chatterino
![image](https://user-images.githubusercontent.com/1953510/128564069-021922ce-49a1-4b2d-9256-8753f1713f4f.png)
FFZ
![image](https://user-images.githubusercontent.com/1953510/128564108-03500d74-e99a-4d47-8728-e32fabe43efa.png)
Chatterino chat window
![image](https://user-images.githubusercontent.com/1953510/128564156-87ad9aaf-ae75-49fe-849c-0645af468c45.png)

**OS and Chatterino Version**
Windows 10, Chatterino 2.3.4 (commit 4e5170799)

**Comment by Mm2PL** [comment]
Can reproduce on de4f6a9d
