### ISSUE TITLE
Replace/Hide chatters' usernames

### ISSUE THREAD

**Issue by Chilledwaffles** [Chatterino/chatterino2#3138]
There could be an option in chatterino to hide the usernames of chatters and replace it with a random number or maybe a number of some significance, but it shouldn't be able to give away the identity of the chatter. I watch a streamer who would want this option because they could stop worrying about which user is typing the message.

**Comment by sando** [comment]
IMO, this is too specific/obscure of a function to ever be added into Chatterino.

There's nickname functionality available in the latest build, but probably not quite what you're after.

**Comment by Felanbird** [comment]
I feel like your best bet for this sort of system would be waiting until Nicknames get Regex support, (while I don't have any timeframe for this, I do believe it was discussed during the implementation.) 

With proper regex support it would be extremely easy to change all users to a single phrase, or hide them with an invisible character.

**Comment by Felanbird** [comment]
Regex Nicknames have been added in #3146. 
The update can be obtained by downloading newest nightly found here: https://github.com/Chatterino/chatterino2/releases/tag/nightly-build

**Comment by apa420** [comment]
From pajlada https://github.com/Chatterino/chatterino2/pull/3146#issuecomment-903242434
>Anonymize chat by replacing .+ with User. (New use case)
