### ISSUE TITLE
Channel point rewards not showing in 2.3.4

### ISSUE THREAD

**Issue by BradMcDev** [Chatterino/chatterino2#3163]
**Describe your issue**

When someone uses channel points to request me to do something, it shows up in Twitch chat, but not in Chatterino.

It appears this was an issue once before:
https://github.com/Chatterino/chatterino2/issues/1850

This is the exact issue I'm currently experiencing.

**To reproduce**

-User requests channel points reward through the Twitch interface
-I don't see request in chat in Chatterino

**Screenshots**

![image](https://user-images.githubusercontent.com/3528774/129316233-ccf248af-04cd-4d03-bc39-5276d1883eae.png)

![image](https://user-images.githubusercontent.com/3528774/129316255-3993494f-8ea4-4e50-bdb6-9aacc1d818f9.png)

**OS and Chatterino Version**

Windows 10 Pro, Chatterino 2.3.4, 64-bit

**Comment by sando** [comment]
If you restart Chatterino, do channel point redemptions still not show up? Pubsub might just be disconnected. Channel point redemptions work fine for me on 2.3.4.

Possibly a duplicate of #1022.

**Comment by BradMcDev** [comment]
Ahh lemme try, thanks Sando.

**Comment by ALazyMeme** [comment]
Works fine for me, Chatterino 2.3.4 (commit 4e5170799), Windows 10

**Comment by BradMcDev** [comment]
Yep- was just pubsub disconnect. Good to know that can happen, TYSM @sando.

**Comment by lilbroto** [comment]
> If you restart Chatterino, do channel point redemptions still not show up? Pubsub might just be disconnected. Channel point redemptions work fine for me on 2.3.4.
> 
> Possibly a duplicate of #1022.

Is there any way to prevent it from disconnecting or it will keep happening?

**Comment by Felanbird** [comment]
> Is there any way to prevent it from disconnecting or it will keep happening?

Update to the latest [nightly build](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) - we added proper pubsub reconnecting in #3643

More info on the nightly build can be found [on our wiki](https://wiki.chatterino.com/Help/#what-is-nightly-and-how-to-use-install-it) and full install instructions in case you run into any issues can be found [here](https://felanbird.github.io/Chatterino-Nightly-Install-Guide/)

**Comment by lilbroto** [comment]
I have the last build installed. When i open chatterino the redeem messages
work but after some time it just stops. Is there any way to fix/stop it or
do i need to keep reopening everytime is bugs?

**Comment by Felanbird** [comment]
> I have the last build installed. When i open chatterino the redeem messages work but after some time it just stops. Is there any way to fix/stop it or do i need to keep reopening everytime is bugs?

Does the `last build installed` mean the version you got from the installer, or the version I suggested downloading?
I have personally had 0 issues since the day we added better-pubsub-reconnecting, but that's only available on the nightly build as there has not been a stable release since then.
