### ISSUE TITLE
Implement some form of IPC

### ISSUE THREAD

**Issue by Cranken** [Chatterino/chatterino2#317]
I personally would really like some method of communicating with chatterino from another process to do things like opening/closing tabs, switching tabs, changing channels etc..
And since Windows 10 also has recently gotten support for Unix sockets we could use one approach for all operating systems.
I don't know if this is a feature that many will want to use/need but I'd really like to see some form of IPC.
(If not I can also just fork it and implement it in a private version.)

**Comment by Cranken** [comment]
Yes, I'm aware of this fact, yet I just wanted to name it as a recent example. I personally also like to work with named pipes rather than Unix sockets.

**Comment by fourtf** [comment]
Best way IMO would be to launch chatterino in an ipc-mode that handles all the communication with the actual chatterino instance through stdio.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project. Command line options will be added though.
