### ISSUE TITLE
Channel messages don't load and always shows channel as offline

### ISSUE THREAD

**Issue by arslanyusuf** [Chatterino/chatterino2#3181]
**Describe your issue**
 First time Chatterino user but it doesn't seem to work for me. I've tried adding channels but the messages never load. It always shows the channels as offline. I even tried the firefox browser extension to replace the ini-browser chat with chatterino but it's empty. No messages at all.

**Screenshots**

![image](https://user-images.githubusercontent.com/59586486/130332133-e73a441a-13f7-4830-9cae-412141cbfaf9.png)
![image](https://user-images.githubusercontent.com/59586486/130332165-e9a7f3b4-e462-4ae7-9123-7920a5317e14.png)

**OS and Chatterino Version**
Windows 10, Chatterino 2.3.4

**Comment by Felanbird** [comment]
Do you use a VPN?

**Comment by arslanyusuf** [comment]
I do not. Should I be?

**Comment by Felanbird** [comment]
> I do not. Should I be?

No, this sort of thing usually happens with people who are VPN'd, that being said if you have access to one you could try that, could be the opposite.

**Comment by apa420** [comment]
If you are using a restricted network such as a university network they might have the ports that chatterino uses to connect to twitch blocked which causes you to never be able to connect.
Try and use a VPN if possible and check if that fixes it.

**Comment by arslanyusuf** [comment]
So looks like using a VPN worked but I'm not on a university network (or anything similar). But it does seem to be a ports problem. It might be a firewall issue?

**Comment by apa420** [comment]
I heard someone couldn't access twitch api at all with their ISP.
Your router might also be your issue so try and see if you got any ports blocked or firewall too strong.
