### ISSUE TITLE
Mod Mode not working

### ISSUE THREAD

**Issue by CadesBurgers** [Chatterino/chatterino2#3197]
**Whenever I click the mod mode button on Chatterino it just brings up the mod settings instead of showing the mod buttons in chat. I can still type mod commands manually and click on usernames to timeout/ban it just doesn't allow me the shortcuts to delete messages and such.**

**https://user-images.githubusercontent.com/89472270/130649756-94ef4102-838f-467c-9747-39b771a15df3.mp4**

**Windows 10 and Chatterino 2.3.4**

https://user-images.githubusercontent.com/89472270/130649756-94ef4102-838f-467c-9747-39b771a15df3.mp4

**Comment by sando** [comment]
This isn't a bug - the settings dialog is opened because you don't have any mod buttons defined. See https://wiki.chatterino.com/Moderation/#moderation-mode on how to add them.
