### ISSUE TITLE
Chat wont load when account logged in

### ISSUE THREAD

**Issue by dozzzz02** [Chatterino/chatterino2#3218]
**Describe the bug**
When logged into any account, certain chats wont load. In this case it's only for 1 streamer.

**To reproduce**
Being logged in no chat will load, clicking anonymous as my account will load the chat.

**Screenshots**
https://i.imgur.com/BD2XnnK.png 
^ In this case, account logged in, as you can see, no new chats will load.

https://i.imgur.com/NSFSotP.png 
^ Once switched to anonymous.

**Chatterino version**
Chatterino Nightly 2.3.1 (commit 2ea233a, )

**Operating system**
Win 10

**Comment by Mm2PL** [comment]
Duplicates #3107
