### ISSUE TITLE
Chatterino API `Access-Control-Allow-Origin` header missing

### ISSUE THREAD

**Issue by IS2511** [Chatterino/chatterino2#3228]
**Describe your issue**
The `Access-Control-Allow-Origin` header is missing in https://api.chatterino.com/badges response

**Possible solution**
Probably should be `Access-Control-Allow-Origin: *`?

**Log**
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.chatterino.com/badges. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by Felanbird** [comment]
@fourtf

**Comment by zneix** [comment]
Why do you need that header though? you should describe this a bit more, since that's not needed for Chatterino itself at all.
Since you didn't bother explaining your usecase for that neither this isn't an issue with anything Chatterino-related um closing this.

**Comment by IS2511** [comment]
I want to use the badge API in a chat overlay web app, the CORS policy blocks me from doing ajax requests to the api from js. I've seen it used in a similar use-case with a CORS proxy set up, which should not be required. Most public API endpoints have a `Access-Control-Allow-Origin: *` in response headers

**Comment by fourtf** [comment]
Ye i can add it soon:tm:

**Comment by fourtf** [comment]
should be added now
