### ISSUE TITLE
Settings not saving when restarting

### ISSUE THREAD

**Issue by Derasiel** [Chatterino/chatterino2#3272]
Hello,
I am using the 7tv version chatterino and the settings are not savings, only 2 channels out of 7-8 I added the first time are saved, I have to enter my twitch token everytime I restart the software and add the others channels aswell, everything reset if I restart Chatterino.

I am not having the issue with the normal version of chatterino. I use the 2.3.4 version for both chatterino (7.3.4 for 7TV).

OS: 
Edition	Windows 10 Pro
Version	21H1
Installed on	‎24/‎11/‎2020
OS build	19043.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by LosFarmosCTL** [comment]
If this is an issue with the 7tv version only, please open a report in the 7tv chatterino repository:

[](https://github.com/SevenTV/chatterino7)
