### ISSUE TITLE
Can't login.

### ISSUE THREAD

**Issue by MithrandirSempai** [Chatterino/chatterino2#3275]
I change my twitch password after situatuins with "twitch leaked" and now for some reason I can't login in Chatterino. 
I go to Chatterino Settings - Accounts - Add - Basic - Log in (Opens in browser) - pressing the button (in new oppened page) - and getting error: 
"Loading username and user id
Error getting user ID. Refresh and try again"

Refresh doesn't help

**Comment by gempir** [comment]
Does the URL look special in a way? Could you open the Developer Console (F12) and screenshot the Console?
