### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [Chatterino/chatterino2#3283]
i've downloaded the version 2.3.4 but when selecting it in the Finder the version number is missing

all macOS apps are supposed to have version information

the `CFBundleShortVersionString` and `CFBundleVersion` entries in your `Info.plist` file are missing
<img width="219" alt="Screenshot 2021-10-11 at 16 30 37" src="https://user-images.githubusercontent.com/1261954/136807897-6ca9cdd2-5b69-4ee0-a2c6-78030e597f81.png">
<img width="256" alt="Screenshot 2021-10-11 at 16 28 21" src="https://user-images.githubusercontent.com/1261954/136807900-de98f909-3aa0-4ef8-b313-ca03a8f2a01d.png">

**Comment by leon-richardt** [comment]
It appears the [keys are indeed set in our `plist`](https://github.com/Chatterino/chatterino2/blob/b0e79b603e388912ed58ca2cccb299d03b0116e5/cmake/MacOSXBundleInfo.plist.in) but the variables appear to be empty. Possibly an issue with the build system?

@core-code Did you download Chatterino from https://chatterino.com or somewhere else?

**Comment by core-code** [comment]
i used this URL:

`https://chatterino.fra1.digitaloceanspaces.com/bin/2.3.4/Chatterino.dmg`
