### ISSUE TITLE
Missing standard key combination (Ctrl+Page) for scrolling between tabs

### ISSUE THREAD

**Issue by mj9** [Chatterino/chatterino2#3316]
**Describe your issue**

In most applications that support tabs, there are two key combinations to do so. The first being `Ctrl+Tab` for forward, and `Ctrl+Shift+Tab` for backward. But there is also a second one which is `Ctrl+Page_up` and `Ctrl+Page_down` (try it out!). I do prefer the second one (is anyone even able to comfortably use `Ctrl+Shift+Tab`?), however it is not supported in Chatterino.

**OS and Chatterino Version**

Windows 10, Chatterino 2.3.4

**Comment by Mm2PL** [comment]
On nightly, you can add this as hotkeys, like this:

![2021-12-22_15-51](https://user-images.githubusercontent.com/25011746/147111165-c86e05aa-233a-4c00-b075-ebebbf56446f.png)

**Comment by pajlada** [comment]
As @Mm2PL mentioned above, this is now possible for you to do in the Nightly version.

For suggesting new default key bindings, create a discussion under the Idea section to open the floor for people's opinions.
