### ISSUE TITLE
emotes missing!

### ISSUE THREAD

**Issue by yaestine** [Chatterino/chatterino2#3324]
i'm just having issues where emotes in some channels are no longer showing up in chatterino yet they are still part of that channel on twitch. i'm using chatterino nightly and the latest update. thanks!

**Comment by Mm2PL** [comment]
For support ask on our [Discord](https://discord.com/invite/qq7DDxjste). Your issue provides too little information to properly diagnose your problem, so I can give you just generic tips:
  - Press F5 to reload emotes,
  - if that doesn't work, restart Chatterino,
  - and if that doesn't work, clear the cache (Settings -> General -> AppData & Cache, click the link and delete all the contents manually)
