### ISSUE TITLE
Links are recognized as clickable with invalid characters 

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#3340]
**Describe your issue**

Despite `https://google.com/()()())(()()((()))` having `(` and `)` which are invalid characters in an URL, Chatterino recognizes whole thing as a clickable link

**Screenshots**
![chatterino_kkxDHuAqgd](https://user-images.githubusercontent.com/3091645/140584948-d2f11e9c-2be2-4c96-bad8-59dc4bb2f790.png)

**OS and Chatterino Version**
Windows 10, Chatterino 2.3.4

**Comment by Infinitay** [comment]
>  having `(` and `)` which are invalid characters in an URL


I think those are valid characters as per https://www.rfc-editor.org/rfc/rfc3986#page-13

>       reserved    = gen-delims / sub-delims
> 
>       gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
> 
>       sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
>                   / "*" / "+" / "," / ";" / "="

**Comment by TETYYS** [comment]
alright, it seems that "$-_.+!*'()," are allowed to be used unencoded in an URL. I was under impression that non-reserved characters are allowed normally and other reserved characters that are not used for special meanings in URL are not allowed
