### ISSUE TITLE
Leading space in first user listed in /mods & /vips

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3345]
**Describe your issue**

After #3187 added the functionality to click the users listed in /mods & /vips, I noticed that the very first user listed does not load, and the login name is very slightly off centered. After looking into this I saw that there is a leading space for the very first user.

**Screenshots**
![image](https://user-images.githubusercontent.com/41973452/141181709-e7ea18f8-10f4-446d-bf45-b87810efdaa0.png)
![image](https://user-images.githubusercontent.com/41973452/141181942-01cd6ce1-c84c-47ff-9ed1-079c30e4fe36.png)

**OS and Chatterino Version**
All versions after 5f7caebce0e48f42fd038d4b7fbfd0cd6cf5f66e

**Comment by Mm2PL** [comment]
Looks like I fucked up making this
