### ISSUE TITLE
turning off input box when empty make hotkeys stop working until typing

### ISSUE THREAD

**Issue by hawichii** [Chatterino/chatterino2#3361]
**Describe your issue**

   Turning off "Show input when it's empty" make "Split input box" hotkeys stop working unless i type something in it first

    Examples:
    - I cant use the up arrow key or opening the emotes tab with ctrl+e without first typing something

**OS and Chatterino Version**

    Windows 10, Chatterino Nightly + Dankerino patches 2.3.4

**Comment by Felanbird** [comment]
https://github.com/Mm2PL/dankerino/issues/117

**Comment by LosFarmosCTL** [comment]
@Felanbird this is probably unrelated to the new custom hotkeys, sounds like a duplicate of #2714 and #2844 to me

**Comment by Felanbird** [comment]
My mistake, as I mentioned above I misread this and thought it was a dupe, now I see that while this is probably intended behavior, it does mess with this setting so we'll have to make a decision on it.

**Comment by hawichii** [comment]
here an [example](https://i.imgur.com/1TJBywH.gif)

**Comment by TETYYS** [comment]
i will pay 1 dollar to anyone who fixes this first
