### ISSUE TITLE
Window is to big in fullscreen

### ISSUE THREAD

**Issue by Thesacraft** [Chatterino/chatterino2#3365]
**Describe your issue**

    - Chatterino takes a small part of the second monitor in fullscreen

**Screenshots**

![Screenshot_2](https://user-images.githubusercontent.com/91694323/143294654-b139b128-c4c1-4b7a-b3f5-4d9b2330bc81.png)

**OS and Chatterino Version**

        Windows 10, Chatterino Nightly 7.3.4

**Comment by Felanbird** [comment]
Duplicate of #2205
