### ISSUE TITLE
Ping sound plays when using /history in an IRC channel

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3372]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

This one might be more of a pain, as the behavior works as expected, but it's annoying.

Steps to Reproduce
1. Open an IRC channel
2. Type `/history #channel_name value` `/history #asd 500`
3. Load the last x messages
4. Get pinged by old highlights in said channel
5. 😒

### Screenshots

Also replicated while using built in `commands on connect`
![image](https://user-images.githubusercontent.com/41973452/143725504-21530448-437b-4ba4-9dbb-25d4eb8660af.png)

### OS and Chatterino Version

0deedf0 - Windows 10

**Comment by Mm2PL** [comment]
To me this is a lack of a feature of removing pings from historical messages. The best way of adding such a feature would be supporting [message batches](https://ircv3.net/specs/extensions/batch.html). Fetching chat history from Ergo looks like this:
```
> HISTORY #xd   
< :oragono.test BATCH +2 chathistory #xd
< @msgid=yj2cmcnnmu8tk5ja65tzbarf7e;batch=2 :test!~test@uvhj4khg56fy4.irc JOIN #xd
< @msgid=kx8ecm9wajmjem2r4bwhbi3zqa;batch=2 :Mm2PLS!~Mm2PL@uvhj4khg56fy4.irc JOIN #xd
< @batch=2;msgid=murtzhjm6na7tu7ufuip9mfyde :test!~test@uvhj4khg56fy4.irc PRIVMSG #xd :text xd
< @msgid=ynditt3349wc6r8xpyjaif3ate;batch=2 :Mm2PLS!~Mm2PL@uvhj4khg56fy4.irc PRIVMSG #xd :penis
< @msgid=77qu63e58heg47xcmsrvzewnza;batch=2 :test!~test@uvhj4khg56fy4.irc PRIVMSG #xd :asd
< :oragono.test BATCH -2
```
ZNC looks similar but instead of `chathistory` batch type `znc.in/playback` is used instead.
