### ISSUE TITLE
Builtin chatterino commands don't work on IRC

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#3376]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

`/openurl` command doesn't work in irc, it doesn't open my browser at all
Works just fine in normal twitch chat

### OS and Chatterino Version

Chatterino 7.3.4 (b00bee632) on Windows 10 (21H1)

**Comment by Mm2PL** [comment]
I will check this out when I have time

**Comment by xHeaveny** [comment]
can reproduce
