### ISSUE TITLE
`IRC Commands on Connect` doesn't work

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#3377]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

IRC commands on connect don't work, it doesn't do anything
Typing the command manually works just fine

### Screenshots

![image](https://user-images.githubusercontent.com/12804673/143828679-7bd0fa06-9be9-48db-bdbc-aed15b130cf1.png)

### OS and Chatterino Version

Chatterino 7.3.4 (b00bee632) on Windows 10 (21H1)

**Comment by ALazyMeme** [comment]
Could be specifically Windows related. Need some feedback from people to add the Windows label.

**Comment by Felanbird** [comment]
Pretty sure this only happens because of #1408 - I'm only able to replicate this issue when re-opening one of the IRC channels, not when opening Chatterino. (which is when the connect technically happens.)

**Comment by Mm2PL** [comment]
They do work but /history won't work because it will send messages to a channel which isn't joined yet.

```
2022-01-18T23:03:08.678Z : debug : userinput  : Mm2PL : <-  : PRIVMSG #xd :test
2022-01-18T23:03:08.678Z : debug : useroutput : Mm2PL :  -> : :oragono.test 404 Mm2PL #xd :Cannot send to channel (+n)
```

![2022-01-19_00-04](https://user-images.githubusercontent.com/25011746/150032829-05d32864-4f0a-4e8f-860a-78b9907de969.png)
