### ISSUE TITLE
Chatter Appimage vs Chatterino Flatpak

### ISSUE THREAD

**Issue by msmafra** [Chatterino/chatterino2#3378]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Restoring .local my data is restored, restoring .var nothing but my log in and some settings are restored.
I back up before a full system reinstallation (Fedora Linux), but after reinstalling everything and restoring my flatpak folders, Chatterino did not keep any of my channels related stuff. In .local for the, what I guess is for the AppImage version, everything seems to be back, but the flatpak one that I was using there is only an empty tab.
All channels, old ones, and the recently added ones are gone. I did a grep -r "<channel_name> ~/.var and found some chat logs, but only from two days before my system crash.

### OS and Chatterino Version

Chatterino 2.3.4

**Comment by msmafra** [comment]
Hello there
I opened chatterino (flatpak) today and everything is gone again:

`dez 08 10:23:15 tars chatterino[11106]: Failed to load module "xapp-gtk3-module"
dez 08 10:23:15 tars chatterino[11106]: Failed to load module "canberra-gtk-module"
dez 08 10:23:15 tars chatterino[11106]: Failed to load module "pk-gtk-module"
dez 08 10:23:15 tars chatterino[11106]: Failed to load module "canberra-gtk-module"
dez 08 10:23:15 tars chatterino[11106]: Failed to load module "pk-gtk-module"
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: Qt: Session management error: None of the authentication protocols specified are supported
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: libpng warning: iCCP: known incorrect sRGB profile
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: libpng warning: iCCP: known incorrect sRGB profile
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.update: init UpdateManager
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.windowmanager: init WindowManager
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.pubsub: init PubSub
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: Added user "forgottenmagneticsnake"
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: Twitch user updated to "forgottenmagneticsnake"
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.pubsub: Connection open!
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.pubsub: Start pubsub manager thread
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: logging in as "forgottenmagneticsnake"
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: logging in as "forgottenmagneticsnake"
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.betterttv.net/3/cached/emotes/global"
dez 08 10:23:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.websocket: connect: Successful connection
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users/blocks?broadcaster_id=422971599&first=100"
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.notification: [TwitchChannel "cmoonlightc" ] Refreshing live status
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/streams?user_login=cmoonlightc"
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.chatterino.com/badges"
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.frankerfacez.com/v1/set/global"
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.websocket: connect: "WebSocket Connection 44.238.247.104:443 v-2 \"WebSocket++/0.8.2\" / 101"
dez 08 10:23:16 tars dleyna-renderer-service[11088]: dLeyna: Exit
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: true "@badge-info=;badges=;color=#8A2BE2;display-name=ForgottenMagneticSnake;emote-sets=0,42,19194,19682,180379,301509,324829,382935,854014,1026863,1584750,300295878,300374282,302070887,302386278,302588849,302965180,304905329,335477877,383128538,428095686,469882967,477339272,477766627,478405528,564265402,592920959,610186276;user-id=422971599;user-type= :tmi.twitch.tv GLOBALUSERSTATE"
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: Loading Twitch emotes for user "forgottenmagneticsnake"
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: Cleared emotes!
dez 08 10:23:16 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: "Loading 28 emotesets from IVR; batch 1/1 (28 sets): 0,1026863,1584750,180379,19194,19682,300295878,300374282,301509,302070887,302386278,302588849,302965180,304905329,324829,335477877,382935,383128538,42,428095686,469882967,477339272,477766627,478405528,564265402,592920959,610186276,854014"
dez 08 10:23:17 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.frankerfacez.com/v1/badges/ids"
dez 08 10:23:18 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.ivr.fi/v2/twitch/emotes/sets?set_id=0,1026863,1584750,180379,19194,19682,300295878,300374282,301509,302070887,302386278,302588849,302965180,304905329,324829,335477877,382935,383128538,42,428095686,469882967,477339272,477766627,478405528,564265402,592920959,610186276,854014"
dez 08 10:23:18 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: Finished loading emotes from IVR, attempting to load Kraken emotes now
dez 08 10:23:18 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/kraken/users/422971599/emotes"
dez 08 10:23:18 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=1026863"
dez 08 10:23:18 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=0"
dez 08 10:23:18 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=1584750"
dez 08 10:23:18 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=180379"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=19682"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=19194"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=300295878"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=300374282"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=301509"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=302070887"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=302386278"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=302965180"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=324829"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=382935"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=42"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: "Failed to fetch emoteSetData for 564265402, assuming Twitch is the owner"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=564265402"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: "Failed to fetch emoteSetData for 592920959, assuming Twitch is the owner"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=592920959"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: "Failed to fetch emoteSetData for 610186276, assuming Twitch is the owner"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=610186276"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=854014"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=64343039"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=205580426"
dez 08 10:23:19 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=120702265"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=110496863"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=192794156"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=139075904"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=131291001"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=558359659"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=562219158"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=610025582"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=29788274"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=124158099"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 400 https://api.twitch.tv/helix/users?id=twitch"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.twitch: Failed to query user by id: "twitch" "42"
dez 08 10:23:20 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/users?id=170030392"
dez 08 10:23:25 tars com.chatterino.chatterino.desktop[11106]: chatterino.windowmanager: [WindowManager] Saving
dez 08 10:24:00 tars systemd[2438]: Starting Tracker metadata extractor...
dez 08 10:24:00 tars systemd[2438]: Started Tracker metadata extractor.
dez 08 10:24:00 tars com.chatterino.chatterino.desktop[11106]: chatterino.windowmanager: [WindowManager] Saving
dez 08 10:24:08 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:10 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to chatterino::SettingsPage "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:12 tars com.chatterino.chatterino.desktop[11106]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
dez 08 10:24:14 tars systemd[2438]: dbus-:1.2-org.gnome.Epiphany.SearchProvider@3.service: Unit process 11021 (WebKitNetworkPr) remains running after unit stopped.
dez 08 10:24:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.cache: Deleted 4961 files
dez 08 10:24:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.notification: [TwitchChannel "cmoonlightc" ] Refreshing live status
dez 08 10:24:15 tars com.chatterino.chatterino.desktop[11106]: chatterino.http: "GET 200 https://api.twitch.tv/helix/streams?user_login=cmoonlightc"
dez 08 10:24:22 tars com.chatterino.chatterino.desktop[11106]: chatterino.windowmanager: [WindowManager] Saving
`
Opened the AppImage one, that has some of the channels and they are all there, is just not as updated.

**Comment by pajlada** [comment]
The AppImage version of Chatterino will store its settings in the standard Linux directory: `$HOME/.local/share/chatterino/Settings`
The FlatPak version of Chatterino will store its settings in `$HOME/.var/app/com.chatterino.chatterino/data/chatterino/Settings`

If you want to switch between these versions interchangeably, you'll need to symblink one to the other. Do this at your own risk though.

Please re-open the issue if there's still any confusion.
