### ISSUE TITLE
don't ping that a channel is live when a channel is already live

### ISSUE THREAD

**Issue by killertofus** [Chatterino/chatterino2#3411]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I get a ping that a channel is live when closing chatterino despite that channel being already live, it should only ping when the channel just got live not every time.

### OS and Chatterino Version

Chatterino 2.3.4 (commit 51ece94)

**Comment by Mm2PL** [comment]
What?

**Comment by Felanbird** [comment]
This behavior is intended and shouldn't be changed, it makes no sense to be given zero information when you startup Chatterino "just because" the streamer went live before you opened it.
