### ISSUE TITLE
Unable to find .mods and .vips messages in search function

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#3429]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When using `.mods` and `.vips`, I am unable to search for users within that message using the Ctrl + F function.

### Screenshots

![image](https://user-images.githubusercontent.com/12804673/147422626-702c8d08-e60a-4e41-b2d5-7b6098f11149.png)

### OS and Chatterino Version

Chatterino 7.3.4 on Windows 10 v21H1

**Comment by ALazyMeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/147422648-0012a40d-bac7-40f7-95f1-1ca30f2e768b.png)

**Comment by Mm2PL** [comment]
Include the commit please, this was supposed to be fixed in a recent commit

**Comment by Felanbird** [comment]
This was implemented yesterday via #3426
