### ISSUE TITLE
Fix "version.dateOfBuild" implementation for Nightly builds

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3430]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running a recent nightly build or the *newest* stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

"Under 'Version' in the About tab, there is a very weird comma+space, I looked into this and realized the date of the commit is supposed to be there. 

https://github.com/Chatterino/chatterino2/blob/fc4387014e592e9ec645c6d78add0a5e4691cbe3/src/widgets/settingspages/AboutPage.cpp#L87-L97
I BARELY remember this so it could have been broken for god knows how long.

I see 2 approaches:

1. Fix it
2. Remove it

### Screenshots

![image](https://user-images.githubusercontent.com/41973452/147423731-e6ee0cc9-b72e-4525-8bb6-81204f777a9e.png)
vs

![image](https://user-images.githubusercontent.com/41973452/147423750-5584ed6d-381f-40f5-8ec7-eaee359b712d.png)

### OS and Chatterino Version

Chatterino Nightly 2.3.4 f64047d5 Windows 10

**Comment by Mm2PL** [comment]
I prefer option 1 because support is easier when you know the date and don't have to look it up.

**Comment by leon-richardt** [comment]
https://github.com/Chatterino/chatterino2/blob/fc049d8f4589cfeedbf1542eae2e6a10d6d2a484/src/common/Version.cpp#L19-L24

---

As noted here, the date parsing is depended [sic!] on the `#define` being provided in exactly the right format. As far as I can tell, the date of build is currently not provided anywhere in the build process.
This should probably be done in the `CMakeLists.txt` via an `add_compile_definitions` directive.

**Comment by Mm2PL** [comment]
Old CI used to add the build date. IMO This shouldn't be done in CMakeLists by default because then every date change would mean a full recompile which is very annoying (~10 minutes for me).

**Comment by leon-richardt** [comment]
> every date change would mean a full recompile

No, the timestamp is created once when you run CMake, not when you build the project. Just building (i.e., not re-generating build files) willl **not** update the timestamp.

**Comment by Mm2PL** [comment]
So running `cmake ..` or saving `CMakeLists.txt` will force an update of that define and make you rebuild everything, correct?

**Comment by leon-richardt** [comment]
Correct. I have [created a Gist](https://gist.github.com/leon-richardt/87a8fe0a57f6b9f86134daeaf1d46b24) to demonstrate this. (Build the app as-is and change the source file later on. On recompilations, the timestamp will not have changed.)

**Comment by leon-richardt** [comment]
Another approach could be parsing the date of the commit the build is based on. One could argue that this is more relevant information than the date it was built on.
