### ISSUE TITLE
Consolidate BaseTheme and Theme

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#3449]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

BaseTheme doesn't really have a good reason to exist in its current form. It just makes stuff like custom themes (#2237) harder.
BaseTheme and the Theme singleton should be combined into a single thing.

### Screenshots

https://github.com/Chatterino/chatterino2/blob/master/src/BaseTheme.cpp
https://github.com/Chatterino/chatterino2/blob/master/src/BaseTheme.hpp
https://github.com/Chatterino/chatterino2/blob/master/src/singletons/Theme.cpp
https://github.com/Chatterino/chatterino2/blob/master/src/singletons/Theme.hpp

### OS and Chatterino Version

b031fc4

**Comment by Felanbird** [comment]
Completed in #4132

**Comment by Mm2PL** [comment]
Resolved in #4132.

**Comment by pajlada** [comment]
Triple-completed in #4132

**Comment by nuuls** [comment]
Quadruple-completed in #4132
