### ISSUE TITLE
UI Overflow [Windows 11]

### ISSUE THREAD

**Issue by mfmarlow** [Chatterino/chatterino2#3465]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Issue:
Ever since installing Windows 11, when I use Window's snap feature to snap Chatterino alongside my Streamlink window, the Chatterino window is slightly bigger than it should be by about 5 pixels in every direction (except up).

To recreate: 
In Windows 11, use Window's snap feature to snap Chatterino to any configuration (left, right, fullscreen,..)

### OS and Chatterino Version

Windows 11 (version 21H2 | build # 22000.376), Chatterino Nightly 2.3.4 (commit 79db02aa6, )

**Comment by Felanbird** [comment]
We don't officially support Windows 11 yet, but see https://github.com/Chatterino/chatterino2/issues/2205#issuecomment-868001183
