### ISSUE TITLE
Add a new context menu item that allows you to copy the message-id of the selected message

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#3478]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Something seems to be missing.
I can not use the command /delete because it requires a message-id as an argument, to delete a single message.

Maybe something like "Copy Message ID" when right clicking a message could be added, so that this issue could be solved?

### OS and Chatterino Version

Chatterino Nightly 2.3.4 (commit dfa3818a7, built on Windows 10)

**Comment by Felanbird** [comment]
`Infinitay mentioned this issue in a pull request`

"marks this issue as being closed by `#3481`"

`Infinitay linked a pull request that will close this issue` 

???
