### ISSUE TITLE
FFZ emotes broken on windows 7 and probably linux

### ISSUE THREAD

**Issue by Goran42069** [Chatterino/chatterino2#350]
Today pajlada fixed the bug where FFZ emotes show up as text but like 1 hour after that they broke again for win7 and apparently linux too since danis said they did. The emotes only appear as blank spaces.

**Comment by Yardanico** [comment]
Works for me on Linux

**Comment by pajlada** [comment]
Please try this again with the latest version, I think I fixed it (along with a crash) in ea691635a1c24f52dec859697421171db11bf4f3 and 5f142e8d525281426e5880b8f27c11e3dca4bf45

**Comment by DatGuy1** [comment]
Seems to work now
![image](https://user-images.githubusercontent.com/21079325/38874509-ea8c18f2-4260-11e8-8db5-3520fa990a60.png)
