### ISSUE TITLE
Closing the search popup also closes usercards opened from the popup

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#3512]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When opening usercards from the search popup (default keybinding: Ctrl+F), the usercards will close as soon as the search popup is closed. I do not consider this expected and/or desired behavior and I would like to stay them open until explicitly closed.

### OS and Chatterino Version

Linux balerion 5.16.0-arch1-1, 82009982

**Comment by leon-richardt** [comment]
I suppose this is caused by the setting the usercards's parent to the search popup/the `ChannelView` in it.

**Comment by Mm2PL** [comment]
This also happens when you close a split which has usercards opened from it

**Comment by zneix** [comment]
Do we see this as a bug really? I think it was rather intended according to GH-1843

**Comment by leon-richardt** [comment]
The intent of #1843 was to make windows that are **supposed** to be floating **actually** floating across a range of different window managers and display environments.
While the problem described in this issue is an effect of the changes in #1843, I don't consider it an intentional effect.

**Comment by sando** [comment]
Definitely a bug, or at least very unintuitive behaviour. On Windows, no other application behaves this way unless it's a modal dialog, in which case interaction with the parent window is disabled. 

I suspect this might also be what causes #2297.
