### ISSUE TITLE
Settings window doesn't properly close when using Ok/Cancel

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3516]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When closing the settings window with either Ok or Cancel, the ghost of settings window past still exists via the windows taskbar hover.
This does not happen when closing the settings window with :x:

1. Open Settings Window ⚙️ 
2. Press Ok or Cancel
3. Move your mouse to the Chatterino icon on the taskbar, and then hover the preview that appears above the icon.
4. ponder life

### Screenshots

![ghost_of_settings_window_past](https://user-images.githubusercontent.com/41973452/149642117-481b9865-027a-4ff0-a292-8d5f3392a5f0.png)

### OS and Chatterino Version

Chatterino 2.3.4 (commit e742860af) | Windows 10

**Comment by ALazyMeme** [comment]
can reproduce (8e7fe9910), phantom menu I guess

**Comment by Mm2PL** [comment]
Don't we hide the settings window because it's slow to load? I think this is the direct consequence of that.

**Comment by zneix** [comment]
Related to GH-1892 (?)

**Comment by goldbattle** [comment]
Seems to be reported here: https://bugreports.qt.io/browse/QTBUG-48855

**Comment by Felanbird** [comment]
this doesn't happen on qt6
