### ISSUE TITLE
`/vips` response changes

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3524]
Twitch has changed the response Chatterino receives when using `/vips` to a case-sensitive variation of display names.

The change sort VIPs as follows:
1. 0-9
2. A-Z
3. a-z
4. multi-language characters [Japanese,Korean etc..]

List of things to do:
~1. Figure out if the case-sensitivity is intended (I've already asked a Staff member to see if the case-sensitivity can be changed.)~
	a) ~~If intended,~~ manually sort displaynames to be case-insensitive because it's stupid to be case-sensitive ✅ https://github.com/Chatterino/chatterino2/pull/3696
2. Figure out how the hell we are going to use asian language display names

~~or hopefully have to do nothing. 🙂~~

**Comment by Felanbird** [comment]
It's been 2 months so I'm going to assume we are stuck with these changes.

**Comment by LosFarmosCTL** [comment]
Surely twitch will listen to their 4th most upvoted UserVoice and expose VIPs as an API endpoint at some point ![image](https://user-images.githubusercontent.com/80157503/159415373-aa45fdf4-c3fe-4c02-b5ed-86b5469d5831.png)

**Comment by pajlada** [comment]
The Helix Get Channel VIPs endpoint gives us User ID, User Login, and User Display Name so we can change the formatting. However, the endpoint is limited to broadcaster only :frowning_face: so while it's now possible for us to improve what the list looks like, it'll only be accessible by broadcasters.

**Comment by Felanbird** [comment]
We fixed this issue for the Helix version of `/vips`, unfortunately that's only available for the broadcaster of the channel.

It's not gonna get fixed for the IRC variation, as that will require an internal change from Twitch, to something they are deleting anyway. (aka not going to happen)
