### ISSUE TITLE
Keyboard shortcuts / key binds for moderation commands

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#353]
Allow binding the shortcuts to moderation actions.

Example: :b: to ban someone

**Comment by wigoor** [comment]
Ability to keybind 1->0 on this page, drag and drop in order? 🤔
Big addition for mods. High priority in my opinion
![](https://i.imgur.com/cx2A6CB.png)

**Comment by wigoor** [comment]
![](https://i.imgur.com/DDjUEGI.png)

**Comment by Mm2PL** [comment]
Could be solved with #1592

**Comment by LudwigCodes** [comment]
Its very important to add custom hotkeys to ban or timeout someone

**Comment by Mm2PL** [comment]
I'll be sure to take care of this functionality when i finally finish #2340 LuL
