### ISSUE TITLE
Unnecessary resource usage in channels that I'm not particularly active in

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#3540]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

There are channels - namely channels where I run a pajbot in, that I need open in order to assist users with any issues they may have. However this also comes with unnecessarily high resource usage - namely emote downloading and message history; both of which are a waste of my resources when I don't need either.

### OS and Chatterino Version

Chatterino Nightly 7.3.4 (commit 8e7fe9910) on Windows 10

**Comment by ALazyMeme** [comment]
Namely the way I'd like to see this fixed, is being able to disable such things in certain channels. None of these channels need emotes or message history, being able to completely disable them from starting up would save the internet usage from downloading the message history or emotes, would save the rendering power of my own pc and also reduce the cache size as a result.

**Comment by Felanbird** [comment]
First step towards this was implemented in: https://github.com/Chatterino/chatterino2/pull/3915

**Comment by pajlada** [comment]
The potential gain in performance will likely not outweigh the added complexity of multiple settings for these suggestions.
Your best bet to see improvements for your use-case is to open a discussion for each improvement you'd like to see (e.g. "I want to disable message history for specific channels, this is why")

Let me know if you want this issue converted to a discussion as a start.
