### ISSUE TITLE
Message history service unavailable (Error 500) 

### ISSUE THREAD

**Issue by liansumsian** [Chatterino/chatterino2#3542]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino not loading messages from the past and i got this error Message history service unavailable (Error 500) 

### Screenshots

![image](https://user-images.githubusercontent.com/72678225/150980031-736458f5-d4dc-4734-b504-566c59f3bd4a.png)

### OS and Chatterino Version

Chatterino Nightly 2.3.4 (commit 4bfa56c1, )

**Comment by Mm2PL** [comment]
Not a problem with chatterino, as you can clearly read the Message history service is unavailable at this time.

**Comment by leon-richardt** [comment]
For reference, message history is provided by https://recent-messages.robotty.de/.
