### ISSUE TITLE
Pubsub-based moderation actions are not hidden when disabling `show moderation messages`

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3547]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Moderation messages that are sent via pubsub are not hidden when disabling `show moderation messages`
1. Automod Messages
2. Automod Phrase approvals/denials
3. Unbans

Moderation actions that have a non pubsub variation (timeouts & bans) are properly hidden from users and mods.

### Screenshots

![image](https://user-images.githubusercontent.com/41973452/151617456-6760b52b-5de6-4cc4-86d6-ca0e9861bf4b.png)

left side felanbot w/ setting on & commands executed from there | right side felanbird with setting disabled
![image](https://user-images.githubusercontent.com/41973452/151619255-205798bb-ffaf-497d-bb71-910e6a45d552.png)

### OS and Chatterino Version

Chatterino Nightly 2.3.4 (commit 1d272c39, built on 2022-01-16)

**Comment by Robinlemon** [comment]
she thinkin real hard at the exact moment of screenshot

**Comment by Mm2PL** [comment]
monkaS
