### ISSUE TITLE
[IRC] Despite emote window having emojis in IRC channels, `:` doesn't prompt anything to autocomplete

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#3550]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [ ] I've verified that I'm running **the most** recent nightly build or stable release
- [ ] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

IRC channels do not have autocomplete for any of emojis

### OS and Chatterino Version

Chatterino Nightly + Dankerino patches 2.3.4 (commit 9c5a6bc0e, )

**Comment by Nerixyz** [comment]
I'd like to fix this 🙂 .
