### ISSUE TITLE
how to set uploader account

### ISSUE THREAD

**Issue by subzero1177** [Chatterino/chatterino2#3552]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hello,

I want to get uploads working so I clicked on the instructions  
<img width="347" alt="image" src="https://user-images.githubusercontent.com/98663274/151673826-a1713d7b-c7f3-44ab-9f96-671f64d507a7.png">

it gets me to https://ctrlv.cz/images/chatterino.png but I don't know how to set it for my Chatterino account. Also the "this guide" link is not working - perhaps because it is just image? 

Thanks!

### OS and Chatterino Version

Chatterino 2.3.4 (commit 4e5170799)

**Comment by Mm2PL** [comment]
This is not a support forum for ctrv dot cz service, ask the creator. https://github.com/Chatterino/chatterino2/discussions/3513 https://github.com/Chatterino/wiki/pull/164#issuecomment-1013857434
