### ISSUE TITLE
Workflows are referencing vulnerable actions

### ISSUE THREAD

**Issue by igibek** [Chatterino/chatterino2#3553]
Hello, there! 

As part of the university research we are currently doing regarding the security of Github Actions, we noticed that one or many of the workflows that are part of this repository are referencing vulnerable versions of the third-party actions. As part of a disclosure process, we decided to open issues to notify GitHub Community. 

*Please note that there are could be some false positives in our methodology, thus not all of the open issues could be valid. If that is the case, please let us know, so that we can improve on our approach. You can contact me directly using an email: ikoishy [at] ncsu.edu* 

Thanks in advance
1. The workflow **build.yml** is referencing action **ilammy/msvc-dev-cmd** using references **v1.9.0**. However this reference is missing the commit [74a501b](https://github.com/ilammy/msvc-dev-cmd/commits/74a501b) which may contain fix to the vulnerability.

The vulnerability fix that is missing by actions' versions could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider updating the reference to the action. 

*If you end up updating the reference, please let us know. We need the stats for the paper :-)*

**Comment by fourtf** [comment]
Seems fine to update

**Comment by ALazyMeme** [comment]
This is referencing v1.10.0, which is the latest version: https://github.com/Chatterino/chatterino2/blob/f4c82dfa59d5a5e9adda10d8317ac0eb229bc71c/.github/workflows/build.yml#L77

**Comment by Felanbird** [comment]
@igibek As ALazyMeme has mentioned above, we are currently on the most recent version of `ilammy/msvc-dev-cmd` being `1.10.0` via #3276.

He also mentioned to me his thought that one of our stale branches might have caused the possible FP, but at a quick glance, I'm unable to find any specifically using `1.9.0`

I'll still have pajlada quickly 👁️ this encase he's aware of something we are missing.

**Comment by pajlada** [comment]
@igibek To confirm what Felanbird state above, we don't have any active branches or commits running the vulnerable actions. The only thing I could think of is inactive PRs, which we would make sure is up-to-date with the main branch before allowing their actions to run.

**Comment by igibek** [comment]
Thank you for your quick reply. I appreciate it!

It seems like, one of the limitations of our approach is an outdated dataset. We collected our dataset from GHArchive 5 months ago and worked on it. I am glad that you were faster than us in noticing the issue.
