### ISSUE TITLE
Highlight sound delay for first highlight after application start

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3560]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When chatterino is started, the first highlight can have a noticeable delay before showing & playing sound. I've seen it show up in webchat before chatterino multiple times.

### Screenshots

Unable to reproduce consistently, but will attempt to record each time I open chatterino.

### OS and Chatterino Version

Chatterino 2.3.4 (commit 5490ff50) & Chatterino 7.3.4 (commit 33a8bd48) on Arch Linux (5.16.5), bspwm, Pipewire for audio

**Comment by jammehcow** [comment]
Seems that something hangs the entire application. Noticed that doing a StreamElements command (which pings me) caused the badges next to my name to pause loading. They loaded once the sound played.

**Comment by Fijxu** [comment]
Same error here, first ping sounds well, other pings have like some kind of delay and then they sound all together like they spam your name in a chat, but they don't, **_WAYTOODANK_**
Arch Lonix BTW, Using chatterino compiled by myself with updated packages :)

**Comment by jammehcow** [comment]
Funny you say that @Fijxu, I've seen that weird delay then massping thing in the past month. Tends to happen most days and just assumed it was an audio system issue. Will open another issue for it.

**Comment by jammehcow** [comment]
Context: https://github.com/Chatterino/chatterino2/issues/3807#issuecomment-1151758935

**Comment by jammehcow** [comment]
Created #3823 for the queueing issue
