### ISSUE TITLE
Viewer/chatter list doesn't close when pressing escape

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3569]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When pressing the escape in the viewers list, the window remains open.

### Screenshots

https://user-images.githubusercontent.com/4962764/153733703-fa3444a6-5e37-458c-8e0f-8991948a6f63.mp4

### OS and Chatterino Version

Chatterino 2.3.4 (commit fb9c3ad4) on Arch Linux (irrelevant)

**Comment by jammehcow** [comment]
Ideally this would match the behaviour of the emote picker as they're both popout windows. Noticed the same issue with settings but that sounds problematic to add unless there was some kind of "are you sure you want to discard" prompt.

**Comment by pajlada** [comment]
Yeah the Settings window is intentional in the absence of a more advanced prompt as you suggested, this I can confirm should close with Escape as other popup windows
