### ISSUE TITLE
The notification about window being out of bounds creates a new tab when either option is chosen

### ISSUE THREAD

**Issue by Heryin** [Chatterino/chatterino2#3571]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Sometimes I use RDP. My setup at home has 2 monitors, so chatterino appears out of bounds. After choosing either option, chatterino creates a new, empty tab of top of all others.
Out of curiosity, I've concluded that it happens when you press a button, not when the notification appears (though might still be wrong)
As for reproduction, it's very easy. You can change the position of the window at the end of window-layout.json to something out of bounds. Now just choose either option and the empty tab appears. Repeating it will create multiple tabs, especially when choosing "No" a few times

Note: Ignore the fact that the gif shows a 7.3.4 fork, downloaded the latest nightly to make sure it's still a thing, tested that on it as well.

### Screenshots

![TUgD1lk](https://user-images.githubusercontent.com/54620595/154044008-94ad64ea-caee-4fb1-8376-bdd4e899b061.gif)

### OS and Chatterino Version

Chatterino Nightly 2.3.4 (commit 82196e3e8, built on ) OS: Windows 10 Pro 20H2

**Comment by ALazyMeme** [comment]
Can reproduce, Chatterino Nightly 7.4.5 (commit [3e722661](https://github.com/Chatterino/chatterino2/commit/3e722661))

**Comment by pajlada** [comment]
I forced `outOfBounds` to true, but I'm unable to reproduce this on Linux
