### ISSUE TITLE
sometimes i have to type in my message twice before it gets sent

### ISSUE THREAD

**Issue by BatChestBAAAT** [Chatterino/chatterino2#3579]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

sometimes i have to type in my message twice before it gets sent 

### OS and Chatterino Version

Manjaro Linux - kernel version 5.16.7-1. Chatterino version: Chatterino 7.3.4

**Comment by Felanbird** [comment]
Twitch silently drops messages in fast chats, not a Chatterino issue.
