### ISSUE TITLE
version numbers are missing on macOS

### ISSUE THREAD

**Issue by core-code** [Chatterino/chatterino2#3607]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

i've downloaded version 2.3.4 but when selecting it in the macOS Finder, the version numbers are missing. 

it seems both the `CFBundleVersion` and `CFBundleShortVersionString` entries in your `Info.plist` file are missing. those are mandatory.
<img width="254" alt="Screenshot 2022-03-15 at 22 36 10" src="https://user-images.githubusercontent.com/1261954/158476827-84c1aa47-a97a-43c1-92f4-4e0c4ce5b36d.png">

### OS and Chatterino Version

Chatterino 2.3.4 on macOS 12

**Comment by Mm2PL** [comment]
Duplicates #3283
