### ISSUE TITLE
Mentions don't appear in /mentions tab

### ISSUE THREAD

**Issue by TCGxD** [Chatterino/chatterino2#3610]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Nothing shows when I am mentioned in the mention tab

### OS and Chatterino Version

Chatterino 2.3.4 (commit 4e5170799)

**Comment by TCGxD** [comment]
No it's turned off

**Comment by LosFarmosCTL** [comment]
I think this happens with smooth scrolling enabled in general?

**Comment by TCGxD** [comment]
They are both turned off

**Comment by Felanbird** [comment]
Closing this since no other information has been given in 16 months.
