### ISSUE TITLE
Chatterino Window unresponsive

### ISSUE THREAD

**Issue by perraas** [Chatterino/chatterino2#3618]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I have restarted, cleared the cache file, tried older and newer builds, and have done multiple clean installs in an attempt to fix the problem to no avail.
My chatterino program opens and I am able to view chat but I am unable to use any mod icons and the title bar is almost completely unresponsive to me. The window also looks odd as if enlarged, I've tried zooming out and changing settings in properties and it didn't fix the issue.

What I am able to do:
see current active chat
add a new tab
change account
type in chat

what I cannot do:
close/minimize the window via title bar
click the settings icon
toggle moderator view
add a side chat
moderation actions

### OS and Chatterino Version

Chaterino 2.3.4 on Windows 10

**Comment by perraas** [comment]
I'm not able to screen record but here are the screenshots. Its hard to tell in the images but compared to how it used to look, its very enlarged
<img width="960" alt="image" src="https://user-images.githubusercontent.com/80073008/159290504-57a15056-71f0-41dc-b336-cc357f5ea595.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/80073008/159290634-70628c01-056c-48a3-91c5-20d5fe6d0547.png">

**Comment by kornes** [comment]
first of, check with latest build https://github.com/Chatterino/chatterino2/releases/download/nightly-build/chatterino-windows-x86-64.zip It will also shows as 2.3.4 version but its 50 updates above what you are using.

**Comment by Felanbird** [comment]
> but it's 50 updates above of what you are using.

192*

**Comment by perraas** [comment]
I uninstalled the previous version and ran the new one after a restart. same result

**Comment by pajlada** [comment]
Closing this issue for now - if this still happens with the latest nightly version please re-open this issue
