### ISSUE TITLE
Username cuts off before an underscore

### ISSUE THREAD

**Issue by oscrim** [Chatterino/chatterino2#362]
When adding my account which has an underscore in it, it cuts off the name right before it which makes mentions to my actual username not work but if somebody mentions the cut-off name it does

**Comment by notheowner** [comment]
Can confirm this, both Chatterino 1 and 2

**Comment by TranRed** [comment]
Seems to be fixed ? @fourtf 
![grafik](https://user-images.githubusercontent.com/16636423/61464428-8559ca00-a976-11e9-8d23-17cdfeb1b848.png)

![grafik](https://user-images.githubusercontent.com/16636423/61464535-b33f0e80-a976-11e9-8166-fb52c2844baa.png)

![grafik](https://user-images.githubusercontent.com/16636423/61464445-8d196e80-a976-11e9-8b2a-2d73de5d19a2.png)

![grafik](https://user-images.githubusercontent.com/16636423/61464461-94407c80-a976-11e9-843e-62afe5469cd5.png)

**Comment by pajlada** [comment]
Closing for now since it seems fixed. Please re-open the issue if this still occurs and we can test it further.
