### ISSUE TITLE
Chatterino defaults to Twitch emote instead of BTTV

### ISSUE THREAD

**Issue by raekwon1** [Chatterino/chatterino2#3629]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hello, I'm having an issue where the wrong emote is being posted when I'm chatting. 
Two different emotes with the same name, it used to post the correct one I chose from the menu, but now it just defaults to the twitch emote and not the BTTV one.

Anyone have this issue? Any fixes?

### OS and Chatterino Version

Chatterino Nightly 7.3.4 (commit 9e400c7dc, built on ) Windows 10

**Comment by LosFarmosCTL** [comment]
This has nothing to do with chatterino, selecting an emote from the menu just inserts its name into the message that is sent to twitch servers. Twitch then inserts the emote themselves, there is no way to use BTTV/FFZ/7TV emotes if you own a twitch emote with the same name.

**Comment by Felanbird** [comment]
> This has nothing to do with chatterino, selecting an emote from the menu just inserts its name into the message that is sent to twitch servers. Twitch then inserts the emote themselves, there is no way to use BTTV/FFZ/7TV emotes if you own a twitch emote with the same name.

☝️ - You didn't have this issue before because you didn't have the Twitch emote, now you do.
