### ISSUE TITLE
Live status Helix call now requires displayname capitalization

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3646]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Due to what I can only assume as an internal Twitch change, our `live notifications` no longer work if the account you want notifications for falls into both of the following:
1. Your `live notifications -> selected channels` does not use correct display-name capitalization `e.g. xQcOW`
2. You do not have a tab open with the channel in question.

Due to the fact that when a tab is open, we send `user_id` based helix calls, when a channel is open the issue in question does not arise and the `live notification` is sent correctly.

### Screenshots

Example 1: All 3 channels `bobross`, `lol_nemesis` & `pajlada` are using incorrect display-name capitalization
After the display-name capitalization is fixed, the live status call works and the notifs appear as intended.
![c2_3646_1](https://user-images.githubusercontent.com/41973452/161428093-cd6e0afd-6242-4586-bc75-2e0caf874f50.gif)

Example 2: Channel `BobRoss` has correct capitalization, while `lol_nemesis` & `pajlada` do not, but channel `pajlada` has a tab open.
![c2_3646_2](https://user-images.githubusercontent.com/41973452/161428191-a63237e3-9d9f-4883-9d4f-84a9b1710ddb.gif)

### OS and Chatterino Version

Chatterino 2.3.5-beta1 28fa6b8 | windows 10

**Comment by Mm2PL** [comment]
Wait, so if you have a channel which has a CJK name, now the CJK name should be given to the API instead?

**Comment by iProdigy** [comment]
Probably should:

* Store `userLogin` instead of `userName` from [streams response](https://github.com/Chatterino/chatterino2/blob/67c10fafc759ff72f420b2bb73fb1a5a082069af/src/controllers/notifications/NotificationController.cpp#L181)
* [Lookup](https://github.com/Chatterino/chatterino2/blob/67c10fafc759ff72f420b2bb73fb1a5a082069af/src/controllers/notifications/NotificationController.cpp#L186) _lowercase_ `name` in `liveStreams` set
