### ISSUE TITLE
All Hotkeys unassigned after Update

### ISSUE THREAD

**Issue by tintinmaster** [Chatterino/chatterino2#3652]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I downloaded the newest Chatterino Nightly Version and couldn't use any shortcuts, not even normal Enter. I edited the settings.json to enable the preferences button again and noticed that every hotkey was missing. In the Tab, only the background could be seen. After "Reset to defaults" everything worked again.

I also noticed in the settings bkp files, that in the hotkeys section only the addedDefaults were there but no description/setting of them

### OS and Chatterino Version

Linux Mint 20.2 Chatterino 2.3.5 (commit 81a62764c) AppImage

**Comment by Felanbird** [comment]
Interesting, we've had it happen pre dfa3818 to windows users who's machines were turn off incorrectly, but I don't think we had any Linux users run into this issue during the past 4 months of nightly 🤔.

**Comment by Felanbird** [comment]
This probably doesn't happen anymore, we've had 4 releases since this issue and no other reports, as well as the pool of users updating from before to after the hotkey overhaul being extremely small, so I'm going to go ahead and close this.
