### ISSUE TITLE
Macos - Icon in dock too big

### ISSUE THREAD

**Issue by Swiftpaws** [Chatterino/chatterino2#3667]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The icon in the dock seems to be too big

### Screenshots

<img width="293" alt="image" src="https://user-images.githubusercontent.com/18440081/162581924-590b33d1-dd0c-4ce9-bdc3-1106f9f1b83a.png">

### OS and Chatterino Version

2.3.5 / Macos

**Comment by LosFarmosCTL** [comment]
This is not a bug per se, just chatterino not having an updated icon for the style that Apple introduced in Big Sur.

The icon should probably be changed to an updated one for macOS, but I am currently the only contributor even using macOS and just finished exam periods for university, so I did not really have the time/motivation to look into it. I'll probably get to it in the next time though, macOS icons are currently a bit broken in general (see #3210) and I've been meaning to take a look at that anyways.

What I do right now as a workaround is changing the icon manually after updating using this script: https://github.com/rikumi/iconsur, run `iconsur set /Applications/chatterino.app --local` in terminal and it will swap the icon out with an auto-generated Big Sur style one.

**Comment by donnydark0** [comment]
Bump, important little fix. Would be very much appreciated.

**Comment by donnydark0** [comment]
> Bump, important little fix. Would be very much appreciated.

@Mm2PL Please stop harrassing me

**Comment by Mm2PL** [comment]
@donnydark0 Please tell me how am I harassing you.

> >   Bump, important little fix. Would be very much appreciated.
> @Mm2PL Please stop harrassing me

**Comment by Mm2PL** [comment]
Please tell me how am I harassing you.

18 lip 2022 17:51:01 donnydark0 ***@***.***>:

**Comment by pajlada** [comment]
Please re-open this issue if this still happens with the latest nightly build using the `Chatterino-universal-Qt-6.5.0.dmg` artifact
