### ISSUE TITLE
Font chooser does not bypass Always on top

### ISSUE THREAD

**Issue by ro0odos** [Chatterino/chatterino2#3672]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

[felanbird]: Steps to Reproduce:
1. Enable `Always on top`
2. Attempt to open the Font Chooser (Font -> Choose...)
3. Window appears behind unmovable main and settings windows.

hello, i'm not great with computers and software and whatnot but recently ive been trying to change the font for chatterino by using the integrated font picker menu thing. the issue is that when i open the menu by clicking "Choose..." in the fonts dropdown box, the window doesn't open. i have all the redistributables and everything seems to be working fine in every other aspect of chatterino, is this just a resolution problem with the menu and it is opening very small? or am i just being dumb and theres some easy problem i am missing. Thanks,
Rodos

### OS and Chatterino Version

Chatterino 7.3.5 | Windows 10 Home

**Comment by ro0odos** [comment]
Oh my bad, i apologise for that. I’ll try getting a hold of 7TV

**Comment by Felanbird** [comment]
Can replicate on normal chatterino
