### ISSUE TITLE
Show channel name when hovering over emote

### ISSUE THREAD

**Issue by WetTortoise** [Chatterino/chatterino2#3680]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When hovering over an emote I would like to see the channel where the emote belongs to. For example with bttv and ffz emotes it displays by: username, I would like a similar thing with twitch sub emotes. I

### Screenshots

Twitch using ffz  https://i.imgur.com/2hxTtMi.png
chatterino https://i.imgur.com/pSAsPsZ.png

### OS and Chatterino Version

latest release

**Comment by sando** [comment]
Duplicate of https://github.com/Chatterino/chatterino2/issues/917

**Comment by Mm2PL** [comment]
Duplicate of #917
