### ISSUE TITLE
Settings aren't re-rendered when clearing search term

### ISSUE THREAD

**Issue by jupjohn** [Chatterino/chatterino2#3688]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When clearing a searched term from Chatterino's search bar, there's a chance that settings won't re-render. As far as I can tell there's no easy way to replicate - but the time's I've seen it I either: CTRL + A + Backspace to clear or; CTRL + Backspace to clear.

All settings section separator lines are still shown but have no content.

### Screenshots

Didn't capture any, will try to reproduce to get some details.

### OS and Chatterino Version

Chatterino 2.3.5 (commit [e8c73ba](https://github.com/Chatterino/chatterino2/commit/e8c73ba4afb8e9882480c2d2a4b10e42b283f14e)) on Arch Linux

**Comment by jammehcow** [comment]
Tried to reproduce multiple times last night without success. Created this to track.

**Comment by jammehcow** [comment]
Managed to snip it: 
![image](https://user-images.githubusercontent.com/4962764/164606805-fa46bb3a-5c1f-474e-85eb-647ce45a94e9.png)

**Comment by jupjohn** [comment]
Haven't seen this bug since, maybe it's worth closing this issue :/
