### ISSUE TITLE
Anonymous sub gifts cause blank line wrap when message fills line

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3692]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When a user is gifted a sub anonymously, Twitch sends through the anon sub message with an extra space at the end (see raw msg below). This can cause an extra line of whitespace to appear when the message hits the end of the line but the spaces go over.

### Screenshots

![image](https://user-images.githubusercontent.com/4962764/165001053-1daac589-0bff-4011-a66e-bd0afdae8bbd.png)

Raw anon gift messages:

`@badge-info=;badges=;color=;display-name=AnAnonymousGifter;emotes=;flags=;id=b44fcc5f-89ec-4d7c-857e-4e16ac6eb444;login=ananonymousgifter;mod=0;msg-id=subgift;msg-param-fun-string=FunStringFive;msg-param-gift-months=1;msg-param-months=1;msg-param-origin-id=e5\\s7b\\scc\\s9b\\s8b\\s34\\s0a\\s31\\s62\\sde\\s03\\sad\\s43\\s80\\s80\\s40\\seb\\sa5\\s51\\sa3;msg-param-recipient-display-name=cowzeatchicken;msg-param-recipient-id=446859098;msg-param-recipient-user-name=cowzeatchicken;msg-param-sub-plan-name=Channel\\sSubscription\\s(lisabby);msg-param-sub-plan=1000;room-id=171645549;subscriber=0;system-msg=An\\sanonymous\\suser\\sgifted\\sa\\sTier\\s1\\ssub\\sto\\scowzeatchicken!\\s;tmi-sent-ts=1650841246356;user-id=274598607;user-type= :tmi.twitch.tv USERNOTICE #lisabby"`

`@badge-info=;badges=;color=;display-name=AnAnonymousGifter;emotes=;flags=;id=35b4258f-53e7-443a-9f4c-6b0c6e9aa7c8;login=ananonymousgifter;mod=0;msg-id=subgift;msg-param-fun-string=FunStringFive;msg-param-gift-months=1;msg-param-months=4;msg-param-origin-id=04\\s22\\sf9\\s49\\s61\\s77\\s20\\s76\\sb6\\sf2\\saf\\s7e\\s1b\\s9c\\sd2\\sf2\\s6a\\s9d\\sd8\\s29;msg-param-recipient-display-name=malopalL;msg-param-recipient-id=511022185;msg-param-recipient-user-name=malopall;msg-param-sub-plan=1000;msg-param-sub-plan-name=sleepyhead;rm-received-ts=1650842383524;room-id=135052907;subscriber=0;system-msg=An\\sanonymous\\suser\\sgifted\\sa\\sTier\\s1\\ssub\\sto\\smalopalL!\\s;tmi-sent-ts=1650842383423;user-id=274598607;user-type= :tmi.twitch.tv USERNOTICE #sleepy `

### OS and Chatterino Version

Chatterino 2.3.5 (commit e8c73ba4) running on Arch Linux, kernel: 5.17.4-zen1-1-zen

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/165292515-aec532e1-5931-4139-bf71-0e45369b1b7f.png)

`@badge-info=;badges=;color=;display-name=AnAnonymousGifter;emotes=;flags=;id=65410825-e668-471b-af70-41039ebc5785;login=ananonymousgifter;mod=0;msg-id=subgift;msg-param-fun-string=FunStringTwo;msg-param-gift-months=6;msg-param-months=12;msg-param-origin-id=29\s77\sd8\s41\s8b\s16\saf\s7f\s27\s6f\s6f\sff\s36\s0c\sc4\s48\s37\s5e\sb0\sfb;msg-param-recipient-display-name=ThatAmiko;msg-param-recipient-id=23874811;msg-param-recipient-user-name=thatamiko;msg-param-sub-plan-name=woops\sSubscription\s(woops);msg-param-sub-plan=1000;room-id=38927816;subscriber=0;system-msg=An\sanonymous\suser\sgifted\sa\sTier\s1\ssub\sto\sThatAmiko!\s;tmi-sent-ts=1650973291928;user-id=274598607;user-type= :tmi.twitch.tv USERNOTICE #woops`

bbd40828 - I believe I use default everything, [fonts, zoom] 🤷

**Comment by jammehcow** [comment]
Sorry felan, I should've made it clearer that this only happens when your window width is the same as the message itself. It'll have the text on one line but also wrap the spaces to the next
