### ISSUE TITLE
Flatpak distribution contains 171MB of Boost source files

### ISSUE THREAD

**Issue by chowder** [Chatterino/chatterino2#3706]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I noticed that the Flatpak distribution of Chatterino includes ~171MB of Boost source files:
```
$ du -sh ~/.local/share/flatpak/app/com.chatterino.chatterino/x86_64/stable/active/files/*
7.7M	/home/chowder/.local/share/flatpak/app/com.chatterino.chatterino/x86_64/stable/active/files/bin
171M	/home/chowder/.local/share/flatpak/app/com.chatterino.chatterino/x86_64/stable/active/files/include
6.4M	/home/chowder/.local/share/flatpak/app/com.chatterino.chatterino/x86_64/stable/active/files/lib
4.0K	/home/chowder/.local/share/flatpak/app/com.chatterino.chatterino/x86_64/stable/active/files/manifest.json
100K	/home/chowder/.local/share/flatpak/app/com.chatterino.chatterino/x86_64/stable/active/files/share
```
(Originally installed from [flathub](https://flathub.org/apps/details/com.chatterino.chatterino))

I couldn't figure out where the Flatpak distribution is built & published - happy to have a look if someone could point me in the right place. 

### OS and Chatterino Version

Chatterino 2.3.5 (commit 81a6276)

**Comment by Felanbird** [comment]
cc: @ilyazzz

**Comment by chowder** [comment]
Finally found the Flatpak manifest: https://github.com/flathub/com.chatterino.chatterino/blob/master/com.chatterino.chatterino.yml

Should just be a matter of adding a [cleanup step](https://docs.flatpak.org/en/latest/manifests.html#cleanup), I can have a go at this. :smile:

**Comment by ilyazzz** [comment]
Fixed with https://github.com/flathub/com.chatterino.chatterino/commit/d16c2327a4976c2ddb46c9715b377ff93b9498d2 , the installed package size went from 160mb to 8mb.
