### ISSUE TITLE
Self-highlights possible in resub messages

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3707]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Users can highlight themselves when a phrase is found in a resub message.

### Screenshots

![image](https://user-images.githubusercontent.com/4962764/166177105-23963316-9870-4929-b083-86e0ab9c2330.png)

### OS and Chatterino Version

Chatterino 2.3.5 (commit e8c73ba4) running on Arch Linux, kernel: 5.17.5-zen1-1-zen

**Comment by ALazyMeme** [comment]
yes
![image](https://user-images.githubusercontent.com/12804673/166177741-a5fd9e75-f050-4dbe-a956-6ed15329751a.png)
