### ISSUE TITLE
[Cleanup] Use MessageBuilder's makeSystemMessage(...) in /debug-env

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#3732]
In https://github.com/Chatterino/chatterino2/blob/5ba3ef721f2a70cf12ad5937d523243126ca4e62/src/controllers/commands/CommandController.cpp#L458-L462 we can use `makeSystemMessage(str)` instead of building our own custom message

Originally added in #3727

**Comment by Mm2PL** [comment]
`makeSystemMessage` wasn't used because it parses links while this has to not parse links, so it displays actual values

**Comment by pajlada** [comment]
> `makeSystemMessage` wasn't used because it parses links while this has to not parse links, so it displays actual values

Seems good :+1:
