### ISSUE TITLE
Add a popup that allows searching and inserting emotes while typing (autocomplete)

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#375]
Pressing a hotkey (e.g. ctrl+space) while typing opens a popup that allows you to search for emotes/emojis. 

example:
![](https://i.fourtf.com/PrincipalCarefulImage.png)

**Comment by alazymeme** [comment]
Looks like the image is missing, but something similar to dankchat would be cool:

![image](https://user-images.githubusercontent.com/12804673/77837668-1ee8a500-71af-11ea-9ea5-89a8508715c3.png)

**Comment by zneix** [comment]
Is functionality from f7237dc sufficient for the topic of this issue?

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/92294188-fc806200-ef6c-11ea-92d4-b134ade796e4.png) Close it

**Comment by apa420** [comment]
I would like to see a hotkey for this.
I like typing emojis with : but I don't want the emote popup when I type it.

**Comment by zneix** [comment]
I think what apa says could also go nicely with #1592
