### ISSUE TITLE
[2.3.5] [MacOS] Enter doesn't send message but goes to new line

### ISSUE THREAD

**Issue by haruiswaifu** [Chatterino/chatterino2#3755]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Since the switch to 2.3.5 or any nightly version, when I press enter in the chat box, it goes to a new line instead of sending the message. I'm not pressing ctrl + enter.

I'm running on MacOS, Apple Silicon (ARM) which might be related.

### OS and Chatterino Version

Chatterino 2.3.5 (commit b14bfd2aad3ef730bf9e4e50b4ab0997b2f5b6ef), MacOS, Apple Silicon (ARM)

**Comment by Mm2PL** [comment]
Duplicates #3619. Reset your hotkeys, there is a bug where they disappear: #3652 
![image](https://user-images.githubusercontent.com/25011746/169666320-71968f2e-6e04-46a6-93ea-fae82992c4fc.png)
