### ISSUE TITLE
Incorrect link previews when a preview doesn't load

### ISSUE THREAD

**Issue by Infinitay** [Chatterino/chatterino2#3803]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

_It's easier to understand the bug with the video below than I can explain with words, though I'll try._

When a link's preview can not be rendered, instead the previous preview is used.

Hover over a badge > Hover over a link that has no preview > That link's preview will be of the badge
Hover over an emote > Hover over a link that has no preview > That link's preview will be of the emote

Though it seems to only be the case if the preview window doesn't dispose/go away as you can see towards the end of the second video.

### Screenshots

https://user-images.githubusercontent.com/6964154/172160069-38a8fe0d-6c03-41d7-aa02-ab79a8ec53f7.mp4

https://user-images.githubusercontent.com/6964154/172161226-c03c4016-d5a7-4474-81ba-3ec4acc73581.mp4

### OS and Chatterino Version

Chatterino Nightly + Dankerino patches 2.3.5 (commit b75d96a3c, built on ) running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Mm2PL** [comment]
This was fixed in #3720. I will merge master soon after #3801 is merged.
