### ISSUE TITLE
Not getting sound notification when I am pinged

### ISSUE THREAD

**Issue by PrestonALewis** [Chatterino/chatterino2#3807]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hey,

I've just had issues getting a ping sound when I'm tagged in the chat, both with my username and any nicknames. I believe this started happening when I updated my chatterino to 7.3.5 (from an original version that didn't include 7tv emotes), and it's just been very random. I did see that from previous threads there was some underlying problem that makes Chatterino not appear in the Volume Mixer, and that is true for me as well. I haven't seen anything else that has gotten a solution but if there's any kind of other details I need to include or if there's anything anyone would recommend, I'd be happy to do either. Thanks.

### Screenshots

![image](https://user-images.githubusercontent.com/75079081/172752454-7a76f48e-91f0-4b86-9cda-974ecd4bc532.png)

### OS and Chatterino Version

Chatterino 7.3.5 (commit 132b406cc), Windows 10 Version 21H2

**Comment by Felanbird** [comment]
There's no real fix, it just requires restarting Chatterino until it works.

**Comment by PrestonALewis** [comment]
> There's no real fix, it just requires restarting Chatterino until it works.

Ok, thanks for the heads up. I'll just restart a few times & see if it fixes itself.

**Comment by jammehcow** [comment]
I've noticed specifically with the 7tv fork that my highlight sounds can be delayed for a few hours, then all play in quick succession. Haven't tested with c2 using my profile but the test profile didn't have these issues.
