### ISSUE TITLE
Chatterino making a new shortcut if old shortcut is renamed

### ISSUE THREAD

**Issue by Nerxxy** [Chatterino/chatterino2#3817]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When changing the name of Chatterino shortcut in _"AppData\Roaming\Microsoft\Windows\Start Menu\Programs"_ it makes a new shortcut with the old name when I start the program, I just want it to be "Chatterino" and not "Chatterino2".

P.S
I found the issue using 7tv Chatterino but is also present on normal Chatterino.

### Screenshots

https://user-images.githubusercontent.com/37718547/173380167-cdcb9d90-0ccf-4734-9472-6ff1fd32be93.mp4

### OS and Chatterino Version

Chatterino 2.3.5 (commit 132b406cc) Windows 10 21H2

**Comment by Felanbird** [comment]
Is this specifically an installer issue? I cannot replicate on nightly.
For starters the program name is `chatterino` vs `Chatterino2`, also changing the shortcut name to `ChatterinoButWithSex` does nothing unexpected.

**Comment by Nerxxy** [comment]
Idk what you mean? I use the installer from latest release.

In the program folder it makes, the exe is the same as its always been, the only thing I change is the name of the shortcut.

![image](https://user-images.githubusercontent.com/37718547/173389329-53ab2d0c-9889-4b1a-8732-861f60a2c1ec.png)

even if i make a shortcut from the exe in Drive: Program Files\Chatterino and put it in the appdata it will make a new shortcut named Chatterino2.

I just want a different name, that's all.

**Comment by Felanbird** [comment]
Try downloading [nightly](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) and use the exe in that folder as your new start point for shortcut renaming.

(My first comment was more or less speaking into the wind for other Chatterino people)

**Comment by Nerxxy** [comment]
nightly also made a new shortcut called chatterino2

**Comment by sando** [comment]
I can't replicate this with latest stable Chatterino (2.3.5), or the latest stable 7tv fork either, both via installer. Both installers created a "Chatterino" shortcut at `%ProgramData%\Microsoft\Windows\Start Menu\Programs\Chatterino.lnk`. AFAIK, there's no mechanism within Chatterino itself to replace shortcuts like that. 

Is there another application creating this shortcut? Maybe [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) can yield some clues here.

**Comment by Nerxxy** [comment]
> I can't replicate this with latest stable Chatterino (2.3.5), or the latest stable 7tv fork either, both via installer. Both installers created a "Chatterino" shortcut at `%ProgramData%\Microsoft\Windows\Start Menu\Programs\Chatterino.lnk`. Renaming or deleting the shortcut worked as expected. AFAIK, there's no mechanism within Chatterino itself to replace shortcuts like that.
> 
> Is there another application creating this shortcut? Maybe [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) can yield some clues here.

not as far as i know. it never used to do this but it has been as of recently

**Comment by brian6932** [comment]
I believe this has something to do with signing up for `Live Notifications` in Chatterino.
When you add a new channel under `Live Notifications` -> `Selected Channels`, it seems to somehow trigger the creation of a `Chatterino2.lnk`
Something to do with the version of the Windows toasts library that is currently used:
https://github.com/mohabouje/WinToast/blob/ce441336ef057576dfb377be754bc5357a04ff85/src/wintoastlib.h#L28
Maybe it should be updated as the current version of it has no `.lnk` or shortcuts path references:
https://github.com/mohabouje/WinToast/blob/master/src/wintoastlib.h

**Comment by Felanbird** [comment]
> I believe this has something to do with signing up for `Live Notifications` in Chatterino. 

Makes sense, I had a Live Notification fire at that exact time my renamed shortcut was generated `2:14 PM`

**Comment by brian6932** [comment]
https://github.com/mohabouje/WinToast/pull/61 It seems like this has been patched in the newest version of the library

**Comment by Nerxxy** [comment]
> I believe this has something to do with signing up for `Live Notifications` in Chatterino.

Makes sense as I only recently started to use the toast and it started around the same time. Thanks!

> https://github.com/mohabouje/WinToast/pull/61 It seems like this has been patched in the newest version of the library

hopefully we get an update soon 🙏

**Comment by pajlada** [comment]
Someone on Windows, please try out [this PR](https://github.com/Chatterino/chatterino2/pull/3834) to see if solves the issue for you.

To test a PR build, you can browse to the linked PR, click the "Checks" tab, then select the "Build" job on the left side, then scroll down to find the build that fits your platform. Note that you need to be signed into GitHub to download from that page.
