### ISSUE TITLE
Highlight sounds "queue up" before all playing in rapid sucession

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3823]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When I am highlighted and a sound should play, there's a 90% chance I won't hear anything. From that point onwards the pings "queue up" until they eventually all play in rapid succession. This can be anywhere between a few minutes after to a few hours.

Have not tested on c2 yet but I do not believe this to be a c7-specific bug. Will attempt to test with c2

### OS and Chatterino Version

Chatterino 7.3.5 DEBUG (commit 652859cc) built with Qt 5.15.4 Running on Arch Linux, kernel: 5.18.3-zen1-1-zen

**Comment by jammehcow** [comment]
@fijxu are you by chance using pipewire as your audio backend? I've noticed chatterino fucks with my audio to the point of stopping audio from all apps until I restart the subsystem.

**Comment by Mm2PL** [comment]
I suspect GStreamer + PipeWire for being the cause of this issue.

**Comment by jammehcow** [comment]
I'll do some digging and chase it up with pipewire if required

**Comment by jammehcow** [comment]
Should mention from the brief bit of debugging I did yesterday it's overflow related.

**Comment by jammehcow** [comment]
@Fijxu most likely a regression in pipewire 0.3.52. Issue can be found here: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2457

As for a workaround (yet to do), downgrade to 0.3.51 or lower.
