### ISSUE TITLE
Quick Switcher adds tabs to main window instead of popup window

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#3826]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Description
When opening the Quick Switcher via a popup window and adding channels with it, tabs are always added to the main window instead of the popup window.

### Steps to Reproduce
1. Open a popup window (e.g., via the <kbd>Ctrl + Shift + N</kbd> keybind).
2. Open the Quick Switcher (<kbd>Ctrl + K</kbd>).
3. Enter a channel name and confirm the "Open in new tab" item.

### Expected Behaviour
The channel is added to the popup window the Quick Switcher was opened from.

### OS and Chatterino Version

Chatterino 2.3.5 (commit 57783c747) running on Arch Linux, kernel: 5.18.5-arch1-1

**Comment by pajlada** [comment]
Fixed in https://github.com/Chatterino/chatterino2/pull/4819
