### ISSUE TITLE
Quick Switcher does not focus correct window when opened from a popup window

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#3827]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Description
When opening the Quick Switcher via a popup window and switching splits with it, focus is not transferred to the window the split resides in.

### Steps to Reproduce
1. Open a popup window (e.g., via the Ctrl + Shift + N popup).
2. Open the Quick Switcher (Ctrl + K).
3. Enter the name of an existing channel and confirm the "Switch to tab" item.

### Expected Behaviour
Focus is transferred to the window the selected split/tab resides in.

**Note:** I'm not sure if OS/WM policies allow applications to transfer focus between windows like that. But I would assume so.

### OS and Chatterino Version

Chatterino 2.3.5 (commit 57783c7) running on Arch Linux, kernel: 5.18.5-arch1-1

**Comment by pajlada** [comment]
Fixed in https://github.com/Chatterino/chatterino2/pull/4819 
The highlight stays with the correct window, popup or main window
