### ISSUE TITLE
Wrong context menu for chat input messages

### ISSUE THREAD

**Issue by heyimrendy** [Chatterino/chatterino2#3844]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chat input messages shows tab context menu instead cut, copy, paste delete

### Screenshots

![chatterino_QfIEHDxwfB](https://user-images.githubusercontent.com/61161733/176571904-30ee8b32-4105-4827-bb4a-e0ff5bc34cbd.gif)

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 0ab53d62e modified) built on with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Felanbird** [comment]
Can replicate 

Thank for you the useful GIF, this issue was reported elsewhere and the way the images were cropped contradicted the report which made me think that I couldn't replicate the issue.

**Comment by Mm2PL** [comment]
I think this has something to do with paj's recent rework of split input event filters and focus

30 cze 2022 03:16:21 heyimrendy ***@***.***>:

> 
> *Checklist*
> 
* > I'm reporting a problem with Chatterino
* > I've verified that I'm running *the most* recent nightly build or stable release
* > I've looked for my problem on the wiki[https://wiki.chatterino.com/Help/]
* > I've searched the issues and pull requests[https://github.com/Chatterino/chatterino2/issues?q=] for similar looking reports

**Comment by ALazyMeme** [comment]
Can reproduce, also 2 more people
![image](https://user-images.githubusercontent.com/12804673/185789709-dd8d960c-7336-4653-b03f-a7625e1c6788.png)
