### ISSUE TITLE
Closing and reopening a split, and then typing /clearmessages crashes chatterino.

### ISSUE THREAD

**Issue by treuks** [Chatterino/chatterino2#3846]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Closing and reopening a split, and then typing /clearmessages crashes chatterino.

**How to reproduce:**
1. Press ctrl + w, and then quickly ctrl + g to "restart" a split
2. Enter the /clearmessages command.
3. Chatterino should crash

### Screenshots

Here's a video on how it's reproduced
https://user-images.githubusercontent.com/18615981/176706578-70e671a1-5b1c-4e28-9a0e-492e8ac93792.mp4

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 0ab53d62 modified) built on 2022-06-29 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Mm2PL** [comment]
Can reproduce on my dev build (6de84a971d49cfbe03e8c0afa3fdf13d74a23429)

My stack was:
- https://github.com/Chatterino/chatterino2/blob/master/src/widgets/splits/Split.cpp#L578
- https://github.com/Chatterino/chatterino2/blob/master/src/controllers/commands/CommandController.cpp#L939
- [irrelevant]
