### ISSUE TITLE
Nightly builds use outdated branch?

### ISSUE THREAD

**Issue by mjeveritt** [Chatterino/chatterino2#3854]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Nightly builds are using a branch 'nightly-builds' which hasn't been updated since Nov 2021 (?) .. surely it would be more helpful to use the master branch, either that or fix merging of commits into the nightly branch perhaps?

### OS and Chatterino Version

Chatterino AppImage 2.3.5 on Kubuntu 18.04 LTS

**Comment by mjeveritt** [comment]
Not a branch, on checking, it's actually a very old tag .. but same problem! :grinning:

**Comment by Felanbird** [comment]
It used to be automatically updated, github changed something that we were too lazy to fix, it's purely a visual issue. Nightly builds are built from master.

**Comment by mjeveritt** [comment]
Can confirm correct:
```
Chatterino 2.3.5 (commit [e1b512a37](https://github.com/Chatterino/chatterino2/commit/e1b512a37) modified) built with Qt 5.15.2
Running on Ubuntu 18.04.6 LTS, kernel: 5.4.106-rt54-xanmod1-mje03rt
```
