### ISSUE TITLE
Latest nightly doesn't display popup windows on the taskbar preview

### ISSUE THREAD

**Issue by jateuu** [Chatterino/chatterino2#3863]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

New popup windows don't display on taskbar previews. It also seems like they aren't treated as separate windows since PowerToys FancyZones don't let them snap to layouts. 

This issue appears on the latest 7TV nightly versions too. 

### Screenshots

![image](https://user-images.githubusercontent.com/32791182/179290838-2c172acf-d7da-41b6-9ae4-f618a44640aa.png)
![image](https://user-images.githubusercontent.com/32791182/179290856-f89115ea-4e24-4f2f-8093-68627d24f4f9.png)

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 965b0667 modified) built on 2022-07-10 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.22000

**Comment by Felanbird** [comment]
Can replicate - side effect of #3836 which granted a parent to the orphaned popup window. I'm unsure if this side-effect is intentional or not.

cc @leon-richardt

**Comment by leon-richardt** [comment]
Thanks for the mention.

Definitely not intended in the sense of "I was aware this behavior happens on Windows". Frankly, this just seems to be an effect of how Windows interprets parented windows. A way to achieve the desired behavior on Windows and tiling WMs would be to have platform-specific code regarding window parents obviously. Would only like to if I can't find a nicer way though, will have to conduct some research.

**Comment by leon-richardt** [comment]
Also, it would be interesting to hear about behavior on other platforms/DEs/WMs so feel free to post it in this issue as well. 🙂
