### ISSUE TITLE
/live not working 

### ISSUE THREAD

**Issue by Nerxxy** [Chatterino/chatterino2#3873]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I have a lot of channels in the Live Notification setting and I know at least one of the channels in there are currently live but I didn't get a notification.

### Screenshots

![live2](https://user-images.githubusercontent.com/37718547/180584531-d1fd5574-4733-41d5-ae6a-49c672c385ef.png)
I'm not entirely sure if the "------------" *channels* have broken anything? I put them there as sub categories, they are not really need just thought it would be a nice addition.

![image](https://user-images.githubusercontent.com/37718547/180584556-b5c1c649-2197-4eeb-8a5d-615de674486a.png)
As you can see in the first image there is a channel called "BigPurpin" and in this image you can see that hes live and not showing in the /Live tab.

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 683701623 modified) built on with Qt 5.15.2, Windows SDK, MSVC 193231329 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Felanbird** [comment]
Try re-logging into Chatterino, your oauth probably expired which is causing helix calls to fail.
![image](https://user-images.githubusercontent.com/41973452/180584707-32379afa-95d1-4224-b7d9-3141e9c85058.png)

**Comment by Nerxxy** [comment]
> Try re-logging into Chatterino, your oauth probably expired which is causing helix calls to fail. ![image](https://user-images.githubusercontent.com/41973452/180584707-32379afa-95d1-4224-b7d9-3141e9c85058.png)

I have tried that already.

**Comment by Nerxxy** [comment]
Lemme see if its because of the "--------" channels

**Comment by Nerxxy** [comment]
its because of the "----------" channels....

**Comment by Felanbird** [comment]
If it is you can just rename the tab nickname instead of attempting to connect to that non-existent channel.

**Comment by Nerxxy** [comment]
I just removed all of the ----- channels and restarted chatterino and got a notif for bigpurpin

**Comment by Nerxxy** [comment]
![image](https://user-images.githubusercontent.com/37718547/180585065-a0687870-ab9a-45b4-a554-d821aa712286.png)

**Comment by Nerxxy** [comment]
I guess the --------- channels are throwing some sort of error?

**Comment by Nerxxy** [comment]
just tried with ______ instead and still didnt get a notif

**Comment by Mm2PL** [comment]
Helix returns an error if one of the nicknames is malformed iirc. This is probably why. I suggest you just remove these channels from your list.

23 lip 2022 03:27:26 Nerxxy ***@***.***>:

**Comment by Nerxxy** [comment]
Is there any symbol that doesn't throw back an error?

The "sub category channels" aren't really needed, just nice to have imo.

**Comment by Mm2PL** [comment]
> Is there any symbol that doesn't throw back an error?


We don't use c++ exceptions for non-200 error codes. Look at the logs it should show an error probably a 400 every so often fetching these channels by name.

**Comment by Nerxxy** [comment]
> We don't use c++ exceptions for non-200 error codes. Look at the logs it should show an error probably a 400 every so often fetching these channels by name.

I wouldn't even know how to see the logs.

Another thing I found, is that say these are my life notification channels:

- xqc
- summit1g
- halo
- zooma
- ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ friends
- helixladder
- bigpurpin
- spiccytacos

I would get notifications from the bottom 3 but not the top 4

**Comment by Felanbird** [comment]
> I would get notifications from the bottom 3 but not the top 4

This should be happening because you have the bottom 3 channels open, but not the top 4, so the fallback of checking the channels you actually have open is covering the live notification. If you added summit1g's chat to Chatterino his `/live` notif would work, or if you removed bigpurpin's chat you would lose his notif.

**Comment by Felanbird** [comment]
> just tried with ______ instead and still didnt get a notif

How did you test it with _____ if you are on https://github.com/Chatterino/chatterino2/commit/683701623a0c6f86b27f25f50bb46a2bf2bd64cc? 
You should be forbidden from entering that character combination due to the changes implemented in 07dd8c560bcb73d0e1a76bf330771624cca82f47

**Comment by Felanbird** [comment]
Either way, If you want to continue to using live notifications in this way, you'll have to build your placeholder channels to respect Twitch's naming structure.

- no special characters at position 0 `usernames cannot start with _`
- following, only 0-9 A-Z a-z and _ 

For example, `FRIENDS______` should be a valid live notification, but obviously if that user ever goes live you'll get a notif, but that seems unlikely.

**Comment by Nerxxy** [comment]
> How did you test it with _____ if you are on [6837016](https://github.com/Chatterino/chatterino2/commit/683701623a0c6f86b27f25f50bb46a2bf2bd64cc)? You should be forbidden from entering that character combination due to the changes implemented in [07dd8c5](https://github.com/Chatterino/chatterino2/commit/07dd8c560bcb73d0e1a76bf330771624cca82f47)

I just put the underscores in...

![image](https://user-images.githubusercontent.com/37718547/180657533-3f6e171b-d454-4ca2-ab66-a742c30830a8.png)

**Comment by Mm2PL** [comment]
Since #3715 it is impossible to type an invalid username into the list.

> Prevent user from entering incorrect characters in Live Notifications channels list (#3715)

This should no longer happen.
