### ISSUE TITLE
Move scrollbar to the left when right tab layout is selected 

### ISSUE THREAD

**Issue by badoge** [Chatterino/chatterino2#3874]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The scrollbar expands every time you hover over it which can be quite annoying when the tabs are on the right :)

Other possible solutions:
Add an option to hide the scrollbar
Add a hover delay 

### Screenshots

https://user-images.githubusercontent.com/18620902/180620033-d20ccf97-6a97-4e76-9611-0a35fe97ec50.mp4

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit c5855278 modified) built on 2022-07-23 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by pajlada** [comment]
I've gone with the `Add an option to hide the scrollbar` solution for this issue in #5731
