### ISSUE TITLE
Allow to have the tabs on the left side

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#388]
This would be useful if you have a lot of tabs open and don't want multiple lines of tabs.

Example:
![](https://i.fourtf.com/SpiritualUnchangedImage.png)

**Comment by gempir** [comment]
What this about? It's kinda unclear to me now. The Example is also broken

**Comment by apa420** [comment]
Having tabs on the left side of the screen instead of on the top.
(it looked like this but way nicer iirc)

![](https://i.nuuls.com/lxunr.png)
