### ISSUE TITLE
Channel point redemptions stop showing after a while

### ISSUE THREAD

**Issue by rodrigo-borges** [Chatterino/chatterino2#3880]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Channel point redemptions appear in Chatterino for a few minutes after I open the client, and then they stop showing. Normal chat messages work fine all the time.

So far I have tried:
- Disconnecting and reconnecting to the channel
- Restarting my computer
- Uninstalling and reinstalling Chatterino

### Screenshots

Here are some screenshots of the problem happening (Twitch chat prespective vs Chatterino):

![image](https://user-images.githubusercontent.com/15786333/181261209-fe2ca2c6-3cc0-4872-8000-9e5562266729.png)
![image](https://user-images.githubusercontent.com/15786333/181261081-dc8aa2d6-5669-4588-b9d1-e674eea99b62.png)

### OS and Chatterino Version

Chatterino 2.3.5 (commit 81a62764c) on Windows 10 version 21H1

**Comment by sando** [comment]
PubSub reliability (i.e. channel point redemption messages, mod action messages) was significantly improved in https://github.com/Chatterino/chatterino2/commit/f97780d84ef0b8040ebc46792c82fceb465f5fe8 - this isn't in the current release (2.3.5), but it is in nightly. Could you try to reproduce in the nightly release?

**Comment by rodrigo-borges** [comment]
I tested the nightly release yesterday and it worked great. Over three hours since launching the client and I was still receiving ponit redemption prompts. Thanks, @sando (:

Is there an estimation for the merge on stable?

**Comment by Felanbird** [comment]
> Is there an estimation for the merge on stable?

no
