### ISSUE TITLE
Non-regex nickname entry allows leading/trailing whitespace in username

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3887]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When editing a nickname, whitespace can be prepended/appended to the username field which is invalid as part of a Twitch/IRC username. This can be confusing to users that paste usernames with trailing spaces as nothing indicates that the whitespace exists outside of the edit mode.

### Screenshots

Username with whitespace (nickname does not work):
![image](https://user-images.githubusercontent.com/4962764/182008775-b2cea51d-9afe-43e4-af25-90b493e3c034.png)

### OS and Chatterino Version

Chatterino 2.3.5 (commit 965b06677) built with Qt 5.15.5 Running on Arch Linux, kernel: 5.18.14-zen1-1-zen

**Comment by jammehcow** [comment]
My suggested fix for this is to strip leading/trailing whitespace on settings save. I see no impact implementing this as no username on Twitch/IRC should start or end with a space.

**Comment by Felanbird** [comment]
Fixed by #3946
