### ISSUE TITLE
Slow GIF emote playback speed

### ISSUE THREAD

**Issue by badoge** [Chatterino/chatterino2#3898]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Issue is on the nightly that came out after #3886 

### Screenshots

https://user-images.githubusercontent.com/18620902/182053509-72719d26-0a9d-4ea6-b277-16b3989080e6.mp4

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit ebc7852f modified) built on 2022-07-31 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by TroyKomodo** [comment]
can u send the emote this happens on and ill look into it

**Comment by brian6932** [comment]
https://i.alienpls.org/rYj.apng
Can reproduce on Windows 10

**Comment by pajlada** [comment]
We have reverted the change that changed this behaviour in https://github.com/Chatterino/chatterino2/commit/76a891c5de1ca181328b61539e1acad3c25b793c
