### ISSUE TITLE
announcments circumvent blacklisted user list

### ISSUE THREAD

**Issue by candybomberz** [Chatterino/chatterino2#3909]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Announcments ("/announce [message]") circumvent blacklisted user list.

Add any highlight word or regex and enable it to be in mentions.

For example ".*code.*" as a regex

Add "Nightbot" to blacklist.

Trigger some nightbot command with the word or regex.

For example "/announce test code test".

The nightbot announcment messages will still show up in the mention tab and play any sounds associated etc..

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 76a891c5 modified) built on 2022-08-06 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Felanbird** [comment]
Duplicate of #3412
