### ISSUE TITLE
Emote button is too wide.

### ISSUE THREAD

**Issue by Ashdemai** [Chatterino/chatterino2#3920]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I have no idea how it became so wide, the font isn't the reason. I just want it to be the size of the icon again.

### Screenshots

![Screenshot from 2022-08-11 21-40-57](https://user-images.githubusercontent.com/74661175/184215415-6b6ad7d0-9892-4605-b108-aa3cb0ef5e7d.png)

### OS and Chatterino Version

Chatterino 2.3.5

**Comment by pajlada** [comment]
Can you resetting your config? This can be done by closing down Chatterino, open up your [Chatterino folder](https://wiki.chatterino.com/Settings/#where-is-my-chatterino-folder-located), go to Settings and rename your `settings` or `settings.json` file to `my-backup-settings.json`, then start Chatterino up again

**Comment by Ashdemai** [comment]
> Can you resetting your config? This can be done by closing down Chatterino, open up your [Chatterino folder](https://wiki.chatterino.com/Settings/#where-is-my-chatterino-folder-located), go to Settings and rename your `settings` or `settings.json` file to `my-backup-settings.json`, then start Chatterino up again
Oh yeah, that fixes it. Thanks.
