### ISSUE TITLE
Add a setting to minimize to tray instead of closing

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#393]

**Comment by huti26** [comment]
Hey, did you decide to not add this feature?

**Comment by busheezy** [comment]
Where is the other issue?

**Comment by fourtf** [comment]
@busheezy Can't seem to find it so I'll reopen.

**Comment by busheezy** [comment]
I appreciate it. Thanks for everything.

**Comment by fourtf** [comment]
https://github.com/Chatterino/chatterino2/issues/393
