### ISSUE TITLE
Crash when reloading message history

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3930]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Steps to Reproduce
1. Reconnect due to either an account switch or Twitch deploy
2. crash

stacktrace:
https://paste.ivr.fi/wigozyxoge.rs
Points to https://github.com/Chatterino/chatterino2/blob/8ea5b49/src/common/Channel.cpp#L262 `corrected by dnsge`

~~My assumption is that it's just not liking how many channels need to be reconnected to at once, as I was unable to replicate the issue when just using `-c pajlada` or a short list of channels.~~ see below comment

(note): This crash happened sometime after the first set of changes, as I had a user testing the PR as of 4a7d1cc and they had no problems or crashes, but switching to the recent nightly causes them to crash on reconnects as well.
PR: Chatterino/chatterino2/pull/3878

### Screenshots

![image](https://user-images.githubusercontent.com/41973452/185235191-02c8e6a1-af48-4e28-835b-aed4f1da770f.png)

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 8ea5b49c modified) built on 2022-08-14 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.19043

**Comment by dnsge** [comment]
Looking at the stack trace, the critical issue seems to occur here:
https://github.com/Chatterino/chatterino2/blob/8ea5b49c52ed726b6a1f258a94ea5d1fb1a38ae1/src/common/Channel.cpp#L262

My guess is that the `LimitedSnapshotQueue` is empty, and this leads to a bad access. (Is the part of the stacktrace stating ```unsigned int64 index = 0xffffffff`ffffffff``` actually giving the index being accessed? If so, that supports this hypothesis).

I'm pretty sure I had looked at this as a potential issue but forgot about it (?) before.

We can probably just add a 

```c++
if (snapshot.size() == 0)
{
    return;
}
```

**Comment by dnsge** [comment]
Actually ignore the fix I suggested, we would actually need to do something like 
```c++
if (snapshot.size() == 0 && !messages.empty())
{
	this->messages_.pushFront(messages);
    this->filledInMessages.invoke(messages);
    return;
}
```
to actually still see the newly added recent messages

**Comment by Felanbird** [comment]
I asked the other issue holder to close their tabs with no message history (as I have too many) and they confirm no longer crashing.
