### ISSUE TITLE
Splits gone?

### ISSUE THREAD

**Issue by PepeTheCommie** [Chatterino/chatterino2#3936]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Sometimes after I boot up chatterino after having shut down my pc it removes all of my splits as well as the dimensions I kept the chatterino in (not sure if relevant).
It has only done this twice so far and each time with a big gap in between doing this. I have ~30 splits normally in my chatterino.

Don't think my images attached show much but maybe it helps?

### Screenshots

![image](https://user-images.githubusercontent.com/96117163/186909857-792943fe-b053-41b3-8e52-4975111f9a7e.png)
![image](https://user-images.githubusercontent.com/96117163/186910482-b01b04c4-97c5-48b7-95b1-935ada106e0e.png)

### OS and Chatterino Version

Chatterino 7.3.5 (commit 132b406cc) on Windows 10

**Comment by Mm2PL** [comment]
Merging into #2235.
