### ISSUE TITLE
Deprecation of IRC commands

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#3956]
On or around Feb 18th, 2023, Twitch will deprecate all commands currently executed through IRC, `excluding /disconnect & /me`
More information on this can be found [here.](https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486) 

This will mean the following commands will need to be transferred from IRC to Helix, in Chatterino:
<details>
  <summary>Command List</summary>

| Completed     | Command | Documentation |
| ----------- | ----------- | ----------- |
| ❌ | `/announce` | https://dev.twitch.tv/docs/api/reference#send-chat-announcement |
| ❌ | `/ban` | https://dev.twitch.tv/docs/api/reference#ban-user ³|
| ❌ | `/unban` | https://dev.twitch.tv/docs/api/reference#unban-user ⁴|
| ❌ | `/clear` | https://dev.twitch.tv/docs/api/reference#delete-chat-messages ¹|
| ❌ | `/color` | https://dev.twitch.tv/docs/api/reference#update-user-chat-color |
| ❌ | `/commercial` | https://dev.twitch.tv/docs/api/reference#start-commercial |
| ❌ | `/delete` | https://dev.twitch.tv/docs/api/reference#delete-chat-messages ¹|
| ❌ | `/emoteonly` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ❌ | `/emoteonlyoff` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ❌ | `/followers` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ❌ | `/followersoff` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ✅ | `/marker` | https://dev.twitch.tv/docs/api/reference#create-stream-marker |
| ❌ | `/mod` | https://dev.twitch.tv/docs/api/reference#add-channel-moderator |
| ❌ | `/mods` | https://dev.twitch.tv/docs/api/reference#get-moderators ⁵|
| ❌ | `/unmod` | https://dev.twitch.tv/docs/api/reference#remove-channel-moderator |
| ❌ | `/raid` | https://dev.twitch.tv/docs/api/reference#start-a-raid ⁵|
| ❌ | `/unraid` | https://dev.twitch.tv/docs/api/reference#cancel-a-raid ⁵|
| ❌ | `/slow` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ❌ | `/slowoff` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ❌ | `/subscribers` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ❌ | `/subscribersoff` | https://dev.twitch.tv/docs/api/reference#update-chat-settings ²|
| ❌ | `/timeout` | https://dev.twitch.tv/docs/api/reference#ban-user ³|
| ❌ | `/untimeout` | https://dev.twitch.tv/docs/api/reference#unban-user ⁴|
| ❌ | `/uniquechat` | https://dev.twitch.tv/docs/api/reference#update-chat-settings |
| ❌ | `/uniquechatoff` | https://dev.twitch.tv/docs/api/reference#update-chat-settings |
| ❌ | `/vip` | https://dev.twitch.tv/docs/api/reference#add-channel-vip |
| ❌ | `/vips` | https://dev.twitch.tv/docs/api/reference#get-vips ⁵|
| ❌ | `/unvip` | https://dev.twitch.tv/docs/api/reference#remove-channel-vip |
| ❌ | `/w` | https://dev.twitch.tv/docs/api/reference#send-whisper ⁶|

1. `/clear` & `/delete` use the same API call
2. `/emoteonly`, `/emoteonlyoff`, `/followers`, `/followersoff`, `/slow`, `/slowoff`, `/subscribers`, `/subscribersoff`, `/uniquechat`, `/uniquechatoff` all use the same API call
3. `/ban` & `/timeout` use the same API call
4. `/unban` & `/untimeout` use the same API call
5. `/mods`, `/vips`, `/raid`, and `/unraid` are now broadcaster only commands
6. `/w` now requires Twitch phone number verification `This is not the same as 2FA`

</details>

The newly required scopes have already been handled in Chatterino/website#77

As noted from the list above, the following commands will need custom error handling
- `/mods` - Will need a custom error for non-broadcasters stating they are no longer able use this command.
- `/vips`     - ""
- `/raid`     - ""
- `/unraid` - ""
- `/w` - Will require custom error handling when receiving back an error code 401, which will indicate the user has not verified their phone number with Twitch. 
- Likely will point to the whisper section of the wiki, which will need to be updated showing where to add said phone number. `settings -> security`

**Comment by Mm2PL** [comment]
IMO for /w we should still allow to use the real IRC /w

**Comment by pajlada** [comment]
Where possible, the migration of commands should happen one command at a time to make testing easier. `/unmod` and `/mod` can be the same PR ofc

**Comment by iProdigy** [comment]
7. `/raid` & `/unraid` are now broadcaster only commands (rip channel editors)

**Comment by Felanbird** [comment]
> 7. `/raid` & `/unraid` are now broadcaster only commands (rip channel editors)

Good point, I had heard that already but the information wasn't in the normal spot
![image](https://user-images.githubusercontent.com/41973452/189229915-65af879b-73bf-431b-94dd-79390497c7af.png)

**Comment by jammehcow** [comment]
Since there are quite a few to get through, would it be helpful for me to create issues for each command so they can be split between people?

Forgive me for I am going _agile_

**Comment by pajlada** [comment]
> Since there are quite a few to get through, would it be helpful for me to create issues for each command so they can be split between people?
> 
> Forgive me for I am going _agile_

I would be OK with this

**Comment by pajlada** [comment]
Closing this issue in favour of the individually created issues
