### ISSUE TITLE
Migrate /mods command to Helix API

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3971]
As part of Twitch's announced deprecation of IRC-based commands ([see here for more info](https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486), the `/mods` command needs to be migrated to use the relevant Helix API endpoint.

Helix API reference: https://dev.twitch.tv/docs/api/reference#get-moderators

Split from #3956

## Consequence
**Only** broadcasters can now list moderators in their own channel

**Comment by iProdigy** [comment]
> > non-broadcasters stating they are no longer able use this command.

Relevant uservoice: https://twitch.uservoice.com/forums/310213-developers/suggestions/41061373-get-moderators-endpoint-remove-need-for-broadcas

**Comment by jammehcow** [comment]
Keen to pick this one up, could I get this assigned to me please?

**Comment by jammehcow** [comment]
Will piggyback off of #4053

**Comment by jammehcow** [comment]
Handing over to @cbclemmer

**Comment by cbclemmer** [comment]
New PR is up https://github.com/Chatterino/chatterino2/pull/4088

**Comment by cbclemmer** [comment]
Scratch the above comment. A separate pr will be made for /mods after the pr for #4019 is merged.

**Comment by cbclemmer** [comment]
Ok, now it's up #4103
