### ISSUE TITLE
Migrate /subscribers command to Helix API

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3977]
As part of Twitch's announced deprecation of IRC-based commands ([see here for more info](https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486), the `/subscribers` command needs to be migrated to use the relevant Helix API endpoint.

Helix API reference: https://dev.twitch.tv/docs/api/reference#update-chat-settings

Split from #3956

**Comment by Nerixyz** [comment]
I'd like to migrate this command (see #3966).
