### ISSUE TITLE
Migrate /vip command to Helix API

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3983]
As part of Twitch's announced deprecation of IRC-based commands ([see here for more info](https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486), the `/vip` command needs to be migrated to use the relevant Helix API endpoint.

Helix API reference: https://dev.twitch.tv/docs/api/reference#add-channel-vip

Split from #3956

**Comment by aidenwallis** [comment]
I can take this
