### ISSUE TITLE
Allow negation of search predicates

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/chatterino2#3998]
As described by @zneix in https://github.com/Chatterino/chatterino2/issues/458#issuecomment-655120637 (slightly abridged):

> option to just exclude some stuff but keep the rest - can be achieved like on GitHub, e.g.:
>   * `has:-link` would only show messages without links
>   * `from:-weeb123` would show everyone's messages but weeb123's

**Comment by jammehcow** [comment]
Curious as to why the syntax of `-` over something like `!`. I'd prefer the latter but maybe there's a reason.

**Comment by leon-richardt** [comment]
> Curious as to why the syntax of `-` over something like `!`. I'd prefer the latter but maybe there's a reason. 

One notable example for this syntax would be GitHub. For example, try searching for `-label:enhancement` in this repo to only display issues without the "enhancement" label.

**Comment by pajlada** [comment]
For "previous art", google also uses `-` to negate search terms
e.g. `nymn -forsen`

**Comment by leon-richardt** [comment]
In contrast to the examples in the quote of the original post, I think that the syntax of `-from:foo` makes more sense to `from:-foo`

**Comment by zneix** [comment]
> Curious as to why the syntax of `-` over something like `!`. I'd prefer the latter but maybe there's a reason.

It's simply what I suggested...(?) the linked original comment explains my thought process - it's just what seems straightforward and **just** one potential solution that I've suggested back then...
Do I need to give full research paper as to why thing A is suggested over thing B or anything else in a draft comment for something that could've as well not be implemented if it wasn't for this reanimation issue we're in right now? :roll_eyes: 

And to actually reply to this instead of crying ~~like I usually do~~, I'd never like the latter. Unless you write code, you have no idea what `!` does/means; while `-` is both quite intuitive and also used in similar things, at least in what yunglpr has brought up. so well, that is the reason, I guess...

**Comment by Felanbird** [comment]
> Unless you write code, you have no idea what ! does/means;

We have already exposed Chatterino users to `!`, so it's a fair thought process to use instead of a new one.

**Comment by zneix** [comment]
i dont care

**Comment by jammehcow** [comment]
> It's simply what I suggested...(?) the linked original comment explains my thought process - it's just what seems straightforward and **just** one potential solution that I've suggested back then... Do I need to give full research paper as to why thing A is suggested over thing B or anything else in a draft comment for something that could've as well not be implemented if it wasn't for this reanimation issue we're in right now? 🙄

I was attempting to spark a discussion around syntax - I'm not asking for you or anyone else to 'defend' their thought process nor is it a personal attack. If we're unable to have constructive discussions around features/issues then this issue tracker should be locked down to just bugs. 

> And to actually reply to this instead of crying ~like I usually do~, I'd never like the latter. Unless you write code, you have no idea what `!` does/means; while `-` is both quite intuitive and also used in similar things, at least in what yunglpr has brought up. so well, that is the reason, I guess...

So a better way to reply to my comment without bringing emotions into it would be something like "I don't feel that the average user would understand `!x` more than `-x`, so I'd rather we stick with `-x`". That's all you had to say to get your point across and it would've been reasonable. I'm not saying my opinion is correct, I'm simply through ideas out there for others to consider/comment on.

> i dont care

This response doesn't add anything to this discussion.
