### ISSUE TITLE
[IRC] A sent message doesn't look like a received one

### ISSUE THREAD

**Issue by Nerixyz** [Chatterino/chatterino2#4020]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

* The username of the sender isn't colored
* Emojis aren't added as emote elements

I'd like to fix this 🙂 .

I think I'll might fix #3570 on the way since the crash is because `this->server() == nullptr` and it's just a matter of extending the `if`-block:

https://github.com/Chatterino/chatterino2/blob/d9e17e69cff5c1f0259f12d1181d2166ca7dc528/src/providers/irc/IrcChannel2.cpp#L36-L49

### Screenshots

![](https://user-images.githubusercontent.com/19953266/193243943-7d09d636-f9ae-43f8-87c6-0f5276946f25.png)

### OS and Chatterino Version

Chatterino Nightly 7.3.5 DEBUG (commit 1af89041 modified) built on 2022-09-27 with Qt 5.15.2, Windows SDK, MSVC 192428314

**Comment by Mm2PL** [comment]
> I think I'll might fix https://github.com/Chatterino/chatterino2/issues/3570 on the way since the crash is because this->server() == nullptr and it's just a matter of extending the if-block:

There's more where that came from. It's better to leave this be in this pr. I am working on a better solution.

**Comment by Nerixyz** [comment]
> There's more where that came from. It's better to leave this be in this pr. I am working on a better solution.

Oh thanks for double-checking, I didn't notice that. I just saw this access there and thought it would be enough.
