### ISSUE TITLE
Show custom hotkeys all over the application

### ISSUE THREAD

**Issue by 8thony** [Chatterino/chatterino2#4039]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Instead of showing the default hotkey, show the custom one if it exists.
Some lines I found, but probably there are more.

https://github.com/Chatterino/chatterino2/blob/4c2e97bea68f2c13031f5125f4c17f3e0142a8f9/src/widgets/settingspages/GeneralPage.cpp#L562-L563
https://github.com/Chatterino/chatterino2/blob/4c2e97bea68f2c13031f5125f4c17f3e0142a8f9/src/widgets/settingspages/GeneralPage.cpp#L196
https://github.com/Chatterino/chatterino2/blob/4c2e97bea68f2c13031f5125f4c17f3e0142a8f9/src/widgets/dialogs/SettingsDialog.cpp#L88
https://github.com/Chatterino/chatterino2/blob/4c2e97bea68f2c13031f5125f4c17f3e0142a8f9/src/widgets/Notebook.cpp#L380-L383

### Screenshots

N/A

### OS and Chatterino Version

Chatterino Nightly 2.3.5 (commit 4c2e97be) Windows 10

**Comment by Mm2PL** [comment]
Custom hotkeys pr two: the electric boogaloo incoming
