### ISSUE TITLE
Wrongfully showing all channel emotes unlocked via new cheer system

### ISSUE THREAD

**Issue by Infinitay** [Chatterino/chatterino2#4043]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

With the addition of the new cheering system being pushed slowly by Twitch, they are making it so the supporter can choose an emote to unlock for all the chatters in that stream. I had this happen to me a few days ago and was able to use a certain subscriber emote from another channel. C2 auto-populated and showed the emote just fine as did webchat. However, apparently C2 is listing all the emotes from that channel despite not all of them being unlocked from that mentioned cheering system.

I can't really re-create this because not everyone has the cheering system, and if you don't want to cheer to test it, you'll have to wait for someone else to do so. As I said previously, it happened to me before, but I can't recall if it showed **all** the subscriber emotes. However, a friend just experienced the same thing now and they are saying that C2 auto-populates and displays all the emotes while only one of the emotes are unlocked. Web chat doesn't show them all.

### OS and Chatterino Version

Chatterino Nightly + Dankerino patches 2.3.5 (commit b75d96a3c, built on ) running on Windows 10

**Comment by Felanbird** [comment]
Ugh

**Comment by Mm2PL** [comment]
We cannot really do anything to fix this because twitch doesn't provide us any useful info on cheer emotes, we just extrapolate them from your cheer badge.

**Comment by Mm2PL** [comment]
@Infinitay Is this still a problem? I think I've heard of some cheer experiment getting binned.

**Comment by Mm2PL** [comment]
This will be completely fixed when #5239 lands.
