### ISSUE TITLE
Regex not working for chat highlights.

### ISSUE THREAD

**Issue by uilson** [Chatterino/chatterino2#4054]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The highlight and play a sound isnt working for the regex messages, this regex is correct for the 2 phrases below it and works with the "Ignores" messages, but nothing happens when i use it to try and highlight/play a sound for it

Both Regexes tried:
(^TwitchLit A wild ([a-zA-Z]+) appears TwitchLit Catch it using !pokecatch \(winners revealed in 90s\))
(^TwitchLit\sA\swild\s([a-zA-Z]+)\sappears\sTwitchLit\sCatch\sit\susing\s!pokecatch\s\(winners\srevealed\sin\s90s\))

Messages:
TwitchLit A wild Delibird appears TwitchLit Catch it using !pokecatch (winners revealed in 90s)
TwitchLit A wild Aipom appears TwitchLit Catch it using !pokecatch (winners revealed in 90s)

### Screenshots

![image](https://user-images.githubusercontent.com/3997415/194802609-7ff53a60-f2bb-48b7-b06e-5137d7e8ed37.png)

### OS and Chatterino Version

Chatterino 2.3.5 (commit 81a62764c) , Windows 10 Pro up to date

**Comment by Felanbird** [comment]
https://regex101.com/r/RRNoMM/1
You need to escape `(` and `)` because they have a job to do already in regex

**Comment by uilson** [comment]
another question, have you tested this in Chatterino? 
because either you did and im really dumb or you didnt and it is still not working even with the escaped (  )..

**Comment by uilson** [comment]
thanks, for some reason its working fine today, but it wasnt before, still doesnt play the sound but that may be a sound file problem.
