### ISSUE TITLE
Show the title of the website when hovering a link.

### ISSUE THREAD

**Issue by LajamerrMittesdine** [Chatterino/chatterino2#407]
Would it be possible to pull titles from webpages when you hover over a link in Chatterino 2?

Like when go over a emote it brings up a text overlay.

Edit: Maybe also add a thumbnail preview of the page when you hover over a link.

**Comment by fourtf** [comment]
Definitely shouldn't be the default as some users don't want that the server hosts know their ip and other metadata about them

**Comment by LajamerrMittesdine** [comment]
An acceptable compromise would be only trying to get the title from known websites. A whitelist. Probably number 1 would be YouTube as I see it having the most value.

**Comment by RAnders00** [comment]
@pajlada close this?

**Comment by pajlada** [comment]
Already implemented. Setting exists under General > Miscellaneous > Show link info when hovering

**Comment by cforno12** [comment]
For future users, this option was moved under General > Link Information > Enable :)
