### ISSUE TITLE
Advanced login method Helix requests fail

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#4073]
Bug report from Discord:
When logging into an account with the Advanced method, the live status blip didn't update (making me think Helix requests failed)

This should be investigated

Discord logs: https://discord.com/channels/253897423439659008/459650160658481152/1032790471937888307

**Comment by iProdigy** [comment]
Resolved: user did not enter the correct client_id associated with the auth token https://discord.com/channels/253897423439659008/459650160658481152/1032807581120471040
