### ISSUE TITLE
Portable creates "chatterino_gui" on "C:\ProgramData\boost_interprocess\"

### ISSUE THREAD

**Issue by hellishvictor** [Chatterino/chatterino2#4084]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hi, today I've noticed that Chatterino portable creates a file named "**chatterino_gu**i" on "**C:\ProgramData\boost_interprocess\25020000" (with padlock included). Since is portable, it would be better keep everything on the folder where it's loaded.
Cheers.

### Screenshots

![sshot-1](https://user-images.githubusercontent.com/34694956/197962691-4a706ac2-87f3-4a1b-a894-0051efdd1488.jpg)

### OS and Chatterino Version

Chatterino 2.3.5 (commit 81a62764c) on Win 7 SP1 x64

**Comment by jammehcow** [comment]
Just checking, does this directory persist after chatterino portable is closed? I'd imagine it would disappear but would like confirmation.

**Comment by htmlboss** [comment]
Directory in question persists for me. The file is about 102kb in size.

Chatterino 2.4.0 portable on Win 10 Pro 22H2 (build 19045.2251)

**Comment by pajlada** [comment]
It's possible to customize where we create this file with our version of Boost Interprocess, but we would need to be careful where we decide to do it.
Happy to assign someone to the task.

**Comment by BernardoGrigiastro** [comment]
What does it do? Its ok to remove "old folders"? I have 600 folders inside it wasting 2Gb, 315 of those folders have 4 files inside (2 being something like tbwcmdmsgQueuexxxxx) and the other folders have the single chatterino_gui. Latest one is from march 2023, its not a thing anymore on newer versions (I am on 2.4.6 btw)? Can I remove all of them?

**Comment by Nerixyz** [comment]
It's fine to remove the folder. You might need to close chatterino if it has some file open.

**Comment by BernardoGrigiastro** [comment]
Thx!

Well... I never use/used the extension but even though I use portable to NOT have folders outside its own, where that folder is is not really the problem, problem is that the old folders should be deleted when a new one is created as 6Gb is a bit much for basically nothing and a "nothing" one would never know about if I wasnt doing a "regular" inspection.

> I think we should be able to use the Windows IPC only, which doesn't create this folder, but we'd need to implement the message queue ourselves (e.g. https://gist.github.com/OmerRaviv/3171076).
This would be great!
