### ISSUE TITLE
Chatterino Closes when I am mentioned in a channel

### ISSUE THREAD

**Issue by GodOfKnockers** [Chatterino/chatterino2#4104]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When I am mentioned in a channel, the program freezes and closes without any notice or error messages. It doesn't matter how many channel tabs I have open or which channel I am in. 

### OS and Chatterino Version

Chatterino 2.3.5 (commit 81a62764c) on Windows 11

**Comment by pajlada** [comment]
Could you try using the Nightly version and seeing if you still encounter the same issue? You can find the download [here](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build).
For Windows, you'll want the `chatterino-windows-x86-64.zip` file. After you've downloaded it, extract it, go to the extracted folder, find the `chatterino.exe` file and run it.
More detailed instructions and information about what Nightly is can be found [on the wiki](https://wiki.chatterino.com/Help/#what-is-nightly-and-how-to-use-install-it)

**Comment by GodOfKnockers** [comment]
I just tried the nighty, and the problem occurs.

**Comment by pajlada** [comment]
Looking for help from someone who is able to reproduce this issue & provide a stacktrace

**Comment by Felanbird** [comment]
Never ran into this issue personally, but I'm still on windows 10, maybe @ALazyMeme will run into it as he's recently upgraded to windows 11.

My immediate assumption would be some god of war issue with a custom playsound,

**Comment by GodOfKnockers** [comment]
> 

You are right. I checked the settings and saw that mentions were set to play a sound, and I do not use sounds. Just tested it and the program is still running. Screenshot of the settings before I turned them off.
![chatterino_Y920R07FN3](https://user-images.githubusercontent.com/34841801/199835099-4bc2c205-0260-4fd3-9c13-9aec3745d311.png)

**Comment by Felanbird** [comment]
> You are right. I checked the settings and saw that mentions were set to play a sound, and I do not use sounds. Just tested it and the program is still running. Screenshot of the settings before I turned them off. 

I actually thought it was something specific to this box, but it's good that the issue was pin-pointed.
![image](https://user-images.githubusercontent.com/41973452/199836981-f7c204a1-055e-437d-8468-a7d4196b588d.png)

**Comment by kornes** [comment]
couldn't reproduce, tested cases:
- mention by @ and without
- with / without same tab focus
- with / without chatterino window focus
- with / without custom .wav file for mentions
- with corrupted .wav for mentions
on both 2.3.5 and last nightly. Win11 22H2, 22621.521

@GodOfKnockers try to disable all checkboxes in Play sound column, and see if it still crashes

**Comment by Felanbird** [comment]
> @GodOfKnockers try to disable all checkboxes in Play sound column, and see if it still crashes

Pretty sure their reply confirmed that was the issue, `Just tested it and the program is still running.` I believe meant they didn't crash with play-sound disabled.

**Comment by kornes** [comment]
oh misunderstood last msg.
did some more tests with incorrect custom sounds file path but couldn't reproduce crash. The only odd thing i noticed on my win11 machine is delay before playback of first sound notification (default or custom) which takes ~7sec, but following pings have no such delay.

**Comment by pajlada** [comment]
I suspect this issue has been fixed.
If you encounter this issue again, feel free to re-open the issue!
