### ISSUE TITLE
Bump CI actions using Node 12 to Node 16

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4105]
Github has begun [the deprecation process for actions running Node 12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), this deprecation is scheduled to take place on <date_unknown>.

The following will need to be done:

- [x] Bump `jurplel/install-qt-action` from `v2` to `v3` - This should handle most of the warnings for the `Build` action https://github.com/Chatterino/chatterino2/pull/4106
	- update `cached` references to just `cache` 
- [x] The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
	- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
	- `note:` This warning was also included in the `Build` actions, but went away when bumping to `v3`, but I'm unsure if it's properly handled with only a version bump.
- [x]  `create-release` - The following use node12
	- [x] `pajlada/create-release` https://github.com/Chatterino/chatterino2/pull/4123
	- [x] `actions/upload-release-asset` https://github.com/Chatterino/chatterino2/pull/4125
- [ ] `lint`
	- `actionsx/prettier` https://github.com/Chatterino/chatterino2/pull/4318
- [x] `macos-latest` our runners have already auto-bumped to `macos-12` despite the warning not going away

**Comment by Wissididom** [comment]
I did https://github.com/pajlada/create-release/pull/1 2 days ago for a part of the checkbox 2 and 3
