### ISSUE TITLE
Twitch channel-specific filters do not properly recieve the information they need

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4112]
Filter variables such as `channel.live` never receive the information they need to function.
So in `channel.live`'s case, a channel's live status is always `offline`, even when the channel is live.

Attempted to fix in #4107 - but that caused Chatterino to completely freeze on startup if you had any filter applied.

**Comment by gzachariadis** [comment]
Same problem here. Seems to not work, even with the chrome extension on and the chat on "Live".
