### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by TomGameZ** [Chatterino/chatterino2#4115]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [ ] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino keeps constantly crashing.

I have tried a full fresh install.

Im Running on 7.3.5 (7TV Addon)

Tried after Windows update, restart and waited for 1 hour.

Looked through Windows Event viewer without finding anything.

Cant provide any logs cause i dont know where chatterino saves them.

### OS and Chatterino Version

Chatterino 7.3.5 | Windows 10 Home (22H2)

**Comment by pajlada** [comment]
You could try using the latest Chatterino2 (not the 7TV edition) Nightly and seeing if you still encounter the same issue? You can find the download [here](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build).
For Windows, you'll want the `chatterino-windows-x86-64.zip` file. After you've downloaded it, extract it, go to the extracted folder, find the `chatterino.exe` file and run it.
More detailed instructions and information about what Nightly is can be found [on the wiki](https://wiki.chatterino.com/Help/#what-is-nightly-and-how-to-use-install-it)

If this doesn't work, the best I can offer you is help setting up the development environment or advice you to look at the other crash reports to see if any of them look similar. https://github.com/Chatterino/chatterino2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Acrash as Chatterino does not create or save crash logs.

**Comment by TomGameZ** [comment]
Well i figured out a clean install of the Chatterino2 Build works fine so i will open a issue report on Chatterino7 Github instead.
