### ISSUE TITLE
`/watching` Tab Parts Channels Even Though Browser Tab Is Still Open

### ISSUE THREAD

**Issue by Nerixyz** [Chatterino/chatterino2#4146]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When opening two (or more) streams in the browser and switching between them, the channel used in the `/watching` tab is updated. If one of the channels isn't open in any split, Chatterino needs to rejoin the channel and load recent-messages and emotes. This can take some time and puts load on recent-messages and the emote-providers, especially when switching quickly. It would be nice if the switch was quicker. 

My idea is that Chatterino could avoid parting a channel for some time if it was displayed in `/watching` or even sync the open tabs between the extension and Chatterino.

_Non-Windows users should be able to test this as well._

### OS and Chatterino Version

Chatterino Nightly 7.3.5 (commit f2f18ba5 modified) built on 2022-10-16 with Qt 5.15.2, Windows SDK, MSVC 193331630

**Comment by LosFarmosCTL** [comment]
I don't really have experience with web extensions, but it should be possible to get a list of open tabs, right?
So maybe it would make sense to keep a chat loaded as long as the corresponding browser tab is still opened. Not sure if there are maybe events for closing a tab, or how that would be implemented but seems like a sensible way to do this if possible.
