### ISSUE TITLE
7tv emotes not showing 

### ISSUE THREAD

**Issue by mrtzzzz** [Chatterino/chatterino2#4148]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I just downloaded Chatterino. I've never used it, but what I immediately noticed is that I can't see emotes like "OMEGALUL", "GIGACHAD" (xqc Channel). 

I also haven't found a "enable 7tv emotes" in the options. 

Am I missing an option? Or is it a known problem? 

### Screenshots

![Screenshot 2022-11-13 155717](https://user-images.githubusercontent.com/118119004/201528610-425d2d5b-4b20-4cb7-9ca0-8984b7701624.png)

### OS and Chatterino Version

Chatterino 2.3.5 (commit 81a62764c) on Windows 10

**Comment by pajlada** [comment]
7TV is only available in the Nightly release - there has been no stable release made yet. The nightly build can be found [here](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build).

More info on the nightly build can be found [on our wiki](https://wiki.chatterino.com/Help/#what-is-nightly-and-how-to-use-install-it) and full install instructions in case you run into any issues can be found [here](https://felanbird.github.io/Chatterino-Nightly-Install-Guide/)
