### ISSUE TITLE
Feature request: Clientside r9k mode

### ISSUE THREAD

**Issue by Nafrayu** [Chatterino/chatterino2#416]
It would be awesome to have a clientside r9k mode that allows the user to completely hide similiar messages if they already have been posted within the last x seconds (The user should be able to configure the amount of seconds)

One problem is, these kind of messages are hard to deal with, a simple levenshtein distance won't help here:

![image](https://user-images.githubusercontent.com/3629228/40316769-a795bba0-5d1f-11e8-97a2-1eaa4f5244fc.png)

I hope you can come up with something amazing!

**Comment by TETYYS** [comment]
https://ideone.com/1TaJjw ?

**Comment by Nafrayu** [comment]
I was thinking something along the lines of this:

https://github.com/nhatbui/compakt

**Comment by alazymeme** [comment]
Would you say that this issue was fixed by https://github.com/Chatterino/chatterino2/pull/1496?

**Comment by Nafrayu** [comment]
Almost, can we also get an option to make it apply to the messages of multiple users? That would be amazing

**Comment by alazymeme** [comment]
So just like a spam blocker in general? I feel like you might be better off just closing chat instead 🤔

**Comment by pajlada** [comment]
> Almost, can we also get an option to make it apply to the messages of multiple users? That would be amazing

It makes more sense to make a new issue with a small feature request to an existing system. I'll mark this as closed
