### ISSUE TITLE
Mac CI for nightlies 

### ISSUE THREAD

**Issue by gempir** [Chatterino/chatterino2#418]
Similar to Windows Builds, Mac should also get automated CI Builds so everyone can use the latest version of chatterino 2.

**Comment by Yardanico** [comment]
I think this should be fixed in order to build for Mac without Qt Creator - https://github.com/fourtf/chatterino2/issues/415

**Comment by fourtf** [comment]
Will not happen unless someone is willing to pay for it and set it up.

**Comment by Yardanico** [comment]
@fourtf what about Travis? It supports macOS

**Comment by fourtf** [comment]
are mac builds for open source projects free on macos?

**Comment by Yardanico** [comment]
@fourtf yes, macOS build can be used by open-source projects too.

**Comment by Yardanico** [comment]
@fourtf just an example:
https://travis-ci.org/nim-lang/Nim/jobs/388407266
