### ISSUE TITLE
Settings tooltips have almost unreadable colors

### ISSUE THREAD

**Issue by CaptainFlint** [Chatterino/chatterino2#4195]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

There is a new feature of 2.4.0 with tooltips for some settings. But when I hover over these settings, the text is displayed as black on dark grey, which makes it barely readable. I tried removing the Settings folder to see if it's some configuration that affects it, but even with default settings it looks the same.

### Screenshots

![image](https://user-images.githubusercontent.com/6475044/204139014-58b06f4d-87ff-4e7b-b8fa-dc0434676372.png)

### OS and Chatterino Version

Chatterino 2.4.0-beta (commit 82797898 modified) built with Qt 5.15.2, Windows SDK, MSVC 193331630 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by pajlada** [comment]
Fixed in https://github.com/Chatterino/chatterino2/pull/4188 - will be available in the full 2.4.0 release
