### ISSUE TITLE
The Deprecation of IRC Commands

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4214]
# (2023-02-24) UPDATE:

As of a few hours ago IRC commands have been disabled permanently, in https://github.com/Chatterino/chatterino2/releases/tag/v2.4.1 we migrated the mod commands in the usercard which were originally forgotten. So if you have an issues using these buttons on `2.4.0`, update to `2.4.1`

Otherwise everything else should work more-or-less as expected, the next loss of feature wont be until next month when they remove the viewerlist for non-mods. 
https://discuss.dev.twitch.tv/t/legacy-chatters-endpoint-shutdown-details-and-timeline-april-2023/43161

# (2023-02-11) UPDATE:

As of a few minutes ago the clock has passed 06:00:00 GMT which means the Timegate feature in Chatterino has rolled over to use the new version of commands.
For those who have not yet updated, Twitch has extended the shutdown date to Feb 24th 2023, and has announced a phased shutdown where old commands will not function, before the schedule shutdown. 
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486/82

If you would like to continue using IRC commands for the duration of the life of IRC commands, you can toggle the respective settings to `Always use IRC` for the following commands: `/w` `/mods` `/vips` `/raid` `/commercial`
![image](https://user-images.githubusercontent.com/41973452/218243278-5ed22ea7-14f3-494b-80e6-de1f2dce4904.png)

## NOTE: If you make this change, you will have to change back in the future to regain functionality after the shutdown.

# (2022-12-03) ORIGINAL POST:
On or about Feb 18th 2023, Twitch will deprecate IRC commands.
For more information see: https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486

## What does this mean for Chatterino?
When this change kicks in, all **OLD** versions of Chatterino using IRC commands, will no longer be able to use said commands, the list of commands can be found below.
<details>
  <summary>Commands List</summary>

| Command | Summary |
| ----------- | ----------- |
| `/announce` | Announces a message to chat |
| `/ban` | Ban a user |
| `/unban` | Unban a user |
| `/clear` | Clear the chat of messages |
| `/color` | Change your chat color |
| `/commercial` | Run a commercial |
| `/delete` | Delete a specific message from a user |
| `/emoteonly` | Turn on emote-only mode |
| `/emoteonlyoff` | Turn off emote-only mode |
| `/followers` | Turn on follower-only mode |
| `/followersoff` | Turn off Follower-only mode |
| `/marker` | Add a "marker" to keep track of something that happened during a stream |
| `/mod` | Add a channel moderator |
| `/mods` | See the list of channel moderators |
| `/unmod` | Remove a channel moderator |
| `/raid` | Start a raid |
| `/unraid` | Cancel an on-going raid |
| `/slow` | Turn on slow-mode |
| `/slowoff` | Turn off slow-mode |
| `/subscribers` | Turn on subscriber-only mode |
| `/subscribersoff` | Turn off subscriber-only mode |
| `/timeout` | Timeout a user |
| `/untimeout` | Remove a timeout from a user |
| `/uniquechat` | Turn on unique-chat mode |
| `/uniquechatoff` | Turn off unique-chat mode |
| `/vip` | Add a VIP |
| `/vips` | See the list of channel VIPs |
| `/unvip` | Remove a VIP |
| `/w` | Send a whisper to another Twitch user |

</details>

## What do I do?
Due to the changes made by Chatterino developers over the course of September & October, all you need to do as the user is update to `2.4.0` 
On Feb 11 2023, at 06:00 GMT - the "timegate" feature implemented in your Chatterino will trigger, and your Chatterino will know it's now time to use the new commands. 
This is about a week before the announced deprecation date, but allows for less disruption if Twitch changes the date.

## What has changed?
Unfortunately due to these changes, some users will experience reduced functionality from certain commands.
The following commands have had a reduction in functionality:

- The `/mods` & `/vips` commands will only be available to the channel broadcaster, which will remove functionality from all regular users & moderators of the channel.
- The `/raid` & `unraid` command will only be available to the channel broadcaster, which will remove functionality from channel editors.
- The `/commercial` command will be only available to the channel broadcaster, which will remove functionality from channel editors.
- The `/w` command will require **ALL** users to have a verified phone number attached to their Twitch account to send a whisper.
`This is **NOT** the same thing as Two-Factor Authentication`
	- Due to these changes, if were previously able to send whispers via Chatterino, you will be required to add a phone number to your Twitch account to continue doing so.
	- If you were previously **UNABLE** to send whispers via Chatterino, adding a phone number to your Twitch account will allow you to start sending whispers.
	- You can add a phone number to your Twitch account in [Twitch Settings.](https://www.twitch.tv/settings/security)
![twitch_phone_auth_2](https://user-images.githubusercontent.com/41973452/205412423-15a99293-9416-4a87-bb7d-22039c290a2e.png)

All of these commands will continue to work as they currently do, on the Twitch website.

`TL;DR: update your Chatterino to 2.4.0 before Feb 2023 or your Twitch /slash commands wont work`

**Comment by Felanbird** [comment]
As there have been no updates to the announcement, that should confirm the deprecation date to still be `February 18th`, which is exactly 1 month away

**Comment by Felanbird** [comment]
🧍 📣 TWO WEEK WARNING

**Comment by Mm2PL** [comment]
The final sendoff date has been changed to `2023-02-24`. And 2023-02-14 is the start of the API ~~shitting itself to annoy us~~  dying.
