### ISSUE TITLE
Window gests closed

### ISSUE THREAD

**Issue by Evoynox** [Chatterino/chatterino2#4228]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

when I open a new window and minimize the first one I cant open the first one anymore, it acts as only one window.

### OS and Chatterino Version

Chatterino 2.4.0-beta (commit 82797898 modified) built with Qt 5.15.2, Windows SDK, MSVC 193331630 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment]
Fixed by #4181

Update from `2.4.0-beta` to `2.4.0`
