### ISSUE TITLE
zero-width emotes are right-aligned on Chatterino

### ISSUE THREAD

**Issue by Johnnycyan** [Chatterino/chatterino2#4232]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When looking at zero-width emotes, they appear to be right aligned to the emote they are above whereas with FFZ they are centered. Is this on purpose? Or an oversight? I personally think it looks weird being right-aligned instead of centered.

### Screenshots

Top is chatterino, bottom is Twitch chat with FFZ

https://user-images.githubusercontent.com/24556317/207401105-7d74b75a-54ee-41f0-aebf-ed7c25e294cd.mp4

### OS and Chatterino Version

Chatterino 2.4.0 (commit a0f93100 modified) on Windows 11

**Comment by Felanbird** [comment]
It's on purpose in the sense of we just tell Chatterino that emotes should be `-1` in positioning, and it just goes from there.

The code was done very quickly the first year BTTV released these emotes, and not really touched besides minor fixes, as they only appear 1/12 months.

**Comment by Johnnycyan** [comment]
Well that particular emote that I used was a 7tv zero-width not bttv. But I'm assuming the same goes?

**Comment by Felanbird** [comment]
> Well that particular emote that I used was a 7tv zero-width not bttv. But I'm assuming the same goes?

Yes

**Comment by pajlada** [comment]
More of an implementation difference - we don't rely on the previous emote for alignment.
I'm open to chatting about different desired behaviours but that'd be best served in a new Discussion to figure out what the right approach is.
