### ISSUE TITLE
Can't disable global filtering.

### ISSUE THREAD

**Issue by XsFrozdY** [Chatterino/chatterino2#4237]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I'm not a snowflake, I can take ANY word thrown at me and I don't appreciate that you FORCE these filters on us... stop it... ad a toggle somewhere, please...

### OS and Chatterino Version

Chatterino 2.4.0

**Comment by Felanbird** [comment]
What are you talking about

**Comment by XsFrozdY** [comment]
what I mean is that words like "tranny" is blocked and censored on chatterino, but NOT on twitch.... not for me at least

**Comment by XsFrozdY** [comment]
there's no setting that I can change to show those words...

**Comment by Felanbird** [comment]
That's a Twitch feature, Chatterino never even receives the uncensored version of those messages. Take it up with them.

**Comment by MiahFuta** [comment]
The global twitch chat filters, can't be disabled in chatterino. This is annoying, because for example....
Me, I'm a tranny and I can't say the word tranny in my own chat and see it in chatterino
See Screen Shot Example
![image](https://user-images.githubusercontent.com/5152979/208029257-705f5c9f-fcaa-4c1c-8e15-99d3c10fe6fb.png)

**Comment by MiahFuta** [comment]
NOT CLOSED!

**Comment by Felanbird** [comment]
`@badge-info=;badges=broadcaster/1,bits-charity/1;color=#666666;display-name=Felanbird;emotes=;first-msg=0;flags=19-27:P.6;id=1ab021ba-0125-45d6-b009-c4e741256061;mod=0;returning-chatter=0;room-id=22524109;subscriber=0;tmi-sent-ts=1671168846212;turbo=0;user-id=22524109;user-type= :felanbird!felanbird@felanbird.tmi.twitch.tv PRIVMSG #felanbird :*** dont mind this fucked up message I have to test stupid people`

This is the raw message Chatterino recieves, as I explained above there is nothing we can do to change this, take it up with Twitch.
https://twitch.uservoice.com/forums/310201-chat
