### ISSUE TITLE
Pasting cells from Excel misbehaving

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#4245]
Original conversation here: https://discord.com/channels/253897423439659008/459650160658481152/1054159287087276062

Original post:
> Excel has... weird... copy + paste shenanigans it does to try and maintain cell information. When I try to copy from Excel to Chatterino the paste just doesn't show up at all. My workaround for this is to use office.com which has a browser-based version of Excel that works fine. Google Sheets works fine as well. Also, copying from Excel to other stuff (say, Notepad) works fine. But I was curious if anyone knew of a way that I could use Excel and paste into Chatterino?

Single-cell & multi-cell copying fails with no error message.
Potentially due to us trying to upload it as an image but image uploading is disabled

OS: Windows

Application: Excel Version: Microsoft® Excel® for Microsoft 365 MSO (Version 2211 Build 16.0.15831.20098) 64-bit

Example file: [TestBook1.xlsx](https://github.com/Chatterino/chatterino2/files/10254877/TestBook1.xlsx)

**Comment by pajlada** [comment]
Confirmed the user had no image uploader configured - with an image uploader configured, pasting a single cell resulted in an image being uploaded

**Comment by Mm2PL** [comment]
Libreoffice (on linux x11) seems to exhibit the same behavior as MS Excel.
```
$ xclip -o -t TARGETS -selection clipboard
TIMESTAMP
TARGETS
MULTIPLE
SAVE_TARGETS
application/x-openoffice-embed-source-xml;windows_formatname="Star Embed Source (XML)"
application/x-openoffice-objectdescriptor-xml;windows_formatname="Star Object Descriptor (XML)";classname="47BBB4CB-CE4C-4E80-a591-42d9ae74950f";typename="LibreOffice 7.4 Arkusz kalkulacyjny";displayname="file:///[snip]/TestBook1.xlsx";viewaspect="1";width="26385";height="1589";posx="0";posy="0"
application/x-openoffice-gdimetafile;windows_formatname="GDIMetaFile"
application/x-openoffice-emf;windows_formatname="Image EMF"
application/x-openoffice-wmf;windows_formatname="Image WMF"
image/png
application/x-openoffice-bitmap;windows_formatname="Bitmap"
image/bmp
text/html
application/x-openoffice-sylk;windows_formatname="Sylk"
application/x-openoffice-link;windows_formatname="Link"
application/x-openoffice-dif;windows_formatname="DIF"
text/plain;charset=utf-16
application/x-libreoffice-tsvc
text/rtf
text/richtext
text/plain;charset=utf-8
UTF8_STRING
STRING
application/x-libreoffice-internal-id-2765303
```
