### ISSUE TITLE
Allow use of filter variables inside regex

### ISSUE THREAD

**Issue by gzachariadis** [Chatterino/chatterino2#4249]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I am trying to filter out messages that match the following criteria : 

> 1. Tagging the broadcaster.

> 2. Contain certain text based on a regex. 

Think, for example, a broadcaster tag followed by the word "hi". A filter that would catch that would look like this `!(message.content match r"^@(channel.name)\s+(?i)h+i+.*$` if filter variables where allowed in regex.

For now, I am implementing this in a non-universal way, but adding the name of the broadcaster into the regex, but I think using variable inside regex would be useful in many ways.

### OS and Chatterino Version

All Versions

**Comment by Felanbird** [comment]
`!((message.content contains channel.name) && (message.content match r"\bhi\b"))` would fit your use case, but you might have to play around more with a better regex than I used.

**Comment by gzachariadis** [comment]
Ohh wow I didn't think of that. I am gonna try it and report back!

**Comment by pajlada** [comment]
Closing as fixed, feel free to re-open if it didn't work
