### ISSUE TITLE
wrong WM class when running under wayland

### ISSUE THREAD

**Issue by sheybey** [Chatterino/chatterino2#4253]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The wayland QT backend sets the WM class using the organization domain if it's set, which in chatterino includes the https:// protocol. This causes the window class to include the protocol and therefore not match the .application file (#1863, #2587).

This issue does not happen under X11.

### Screenshots

![Screenshot from 2022-12-23 14-03-41](https://user-images.githubusercontent.com/9370747/209412707-e3891e9f-9f33-4d4e-aa66-80a0e491e6a3.png)

### OS and Chatterino Version

Chatterino 2.4.0 (commit a0f93100) built with Qt 5.15.6 Running on Debian GNU/Linux bookworm/sid, kernel: 6.0.0-6-amd64

**Comment by sheybey** [comment]
Debian has only very recently started shipping the wayland backend for QT, which indirectly surfaced this problem for me. I think this would have always been the case if running under wayland, but I didn't notice when I wrote #2587 because I didn't have the wayland backend for QT installed then.

This can be resolved by changing the `organizationDomain` property to not include `https://www`, which results in gnome correctly mapping the .application file again. I believe this is how the organizationDomain is intended to be used, since the example in the docs also does not include a protocol.

https://doc.qt.io/qt-5/qcoreapplication.html#organizationDomain-prop

However, since this property is used to create a configuration file name on macOS, I don't know if changing it would cause problems for macOS users, and I don't have a Mac to test.

I've published a fork with the above change made if anyone wants to give it a shot.

https://github.com/sheybey/chatterino2/tree/remove-protocol-from-domain

**Comment by LosFarmosCTL** [comment]
> However, since this property is used to create a configuration file name on macOS, I don't know if changing it would cause problems for macOS users, and I don't have a Mac to test.
> 
> 

I can try to look at that tomorrow if I get around to it between work and christmas. But afaik c2 doesn't use QSettings anyways so I am guessing it should be fine?

**Comment by pajlada** [comment]
I took your branch, added a changelog entry, and made it into a PR https://github.com/Chatterino/chatterino2/pull/4256
It should work as expected everywhere, so I'll merge it in. Thanks for the heads up!
