### ISSUE TITLE
Message highlights taking priority over user highlights

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4259]
### Discussed in https://github.com/Chatterino/chatterino2/discussions/3865

<div type='discussions-op-text'>

<sup>Originally posted by **LosFarmosCTL** July 17, 2022</sup>
Was there a specific reason to make user highlights take priority over message/phrase highlights?

IMO it would make more sense the other way around, highlight all messages from one user, but i.e. if that one user pings me I'd still want that to take priority.</div>

`felanbird:`
I'm moving this to an issue, in hopes it gets more traction. Since the release of 2.4.0, the most common deterrent to updating in certain areas of Twitch, is this functionality change. 
Due to the issues with 7.4.0's release, the discussion of updating happens way more often, and due to this, other chatters are able to give their opinion, which is to not update.
I'd say out of every 10 users, 4 of them update, 2 are too lazy, and the other 4 either experienced the change, or were deterred by another who did.

pajlada's comment:
![image](https://user-images.githubusercontent.com/41973452/209446512-1fb2e876-8c31-4292-b542-3d4d11042a5a.png)

**Comment by 8thony** [comment]
Similar problem with badges since version 2.4.0, as discussed in #4191
