### ISSUE TITLE
Linux: Undocumented (runtime) dependency on qt5-qtimageformats

### ISSUE THREAD

**Issue by mforsb** [Chatterino/chatterino2#4264]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino won't load webp images (i.e. 7tv emotes) without it, but otherwise runs fine. This is on Fedora 37, the package might have other names on different distributions.

### OS and Chatterino Version

Chatterino 2.4.0 (commit a9a985bd modified) built with Qt 5.15.7 Running on Fedora Linux 37 (Workstation Edition), kernel: 6.0.14-300.fc37.x86_64

**Comment by Felanbird** [comment]
We have `qt5-image-formats-plugins` documented for Arch for webp's, is `qt5-qtimageformats` required for Fedora?

**Comment by mforsb** [comment]
Yes
