### ISSUE TITLE
Crash when all tabs are closed

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4269]
### Steps to Reproduce
1. Open any amount of tabs, or utilize the single default tab
2. Close all tabs (CTRL+SHIFT+W)
3. Attempt to open a new tab (➕ or CTRL+SHIFT+T)
4. ⚰️ 

stacktrace(s):
https://paste.ivr.fi/catemuryvu // this one happens when pressing `➕ or CTRL+SHIFT+T`
https://paste.ivr.fi/sijuxunegu.r // this one happens when pressing `CTRL+T` in the same scenario

Explicitly tested on 2ba4da02aecf937c740ef9b0a9f7bd7b8c3ef256 but I doubt we've fixed this issue since last week

**Comment by pajlada** [comment]
Crash introduced in https://github.com/Chatterino/chatterino2/pull/4187
