### ISSUE TITLE
Links present in IRC NOTICEs are passed all the way down to LinkResolver

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#4298]
That shouldn't be done. Sometimes there might be FPs, see dirty example with debug prints below, which could also contain sensitive information.
A message of this NOTICE will never be seen anyway so there's no point in resolving stuff for links in there, but I'm unsure what should be the approach here; a potential solution should make these NOTICEs be ignored... or perhaps tweak `LinkResolver` class to not resolve link information for things that cannot be seen. Thoughts @mm2pl @pajlada?

![fdm](https://cdn.zneix.eu/nimau8q.png)

NOTE: incoming NOTICEs are received because we always connect to all IRC servers from settings on application's startup, even if no channels from within an IRC network are present in the window layout (or any IRC channels at all), but that's a whole another story/issue.

**Comment by Mm2PL** [comment]
This could be solved with that old image uploader issue with stupid GET deletion links, have some links not get previews. 
I'm thinking of only resolving links for chat messages generated by users, not system messages and the like. What do you think?

**Comment by pajlada** [comment]
We could also move to only resolve links upon hover - that will solve this issue in a different way.
It may slow down the tooltip generation for the first user to resolve a link but long-term I believe it will provide on average faster responses anyway

**Comment by Mm2PL** [comment]
This does not apply to local system messages anymore. 
IRC support was removed.

##### F
