### ISSUE TITLE
Commandline options

### ISSUE THREAD

**Issue by Bur0k** [Chatterino/chatterino2#43]
suggested:
-join CHANNEL1,CHANNEL2,....

**Comment by pajlada** [comment]
Note to self for command line arguments: check out boost program options http://www.boost.org/doc/libs/1_64_0/doc/html/program_options/tutorial.html#idp435720656

**Comment by Icarus77** [comment]
Does removing the "wontfix" tag mean you'll add this eventually? Great software, but it not working with things like SL Twitch GUI kind of sucks.

**Comment by azizLIGHT** [comment]
Any progress on this front?

**Comment by jp1995** [comment]
Yearly Jeping. Would be awesome to open specific channels for my lidl script

**Comment by zneix** [comment]
If I read correctly, this should have more priority than settings, right?  
For example, running `chatterino --channels=pajlada,zneix,mm2pl` would only open those 3 channels, regardless if I have 0, 10 or 100 channels in settings - and preferrably all of them would open in the new tabs, right?

**Comment by omrisim210** [comment]
Boost is mentioned in a comment from a few years ago, and I wonder why not just use `QCommandLineParser` since Chatterino already uses Qt?

**Comment by fourtf** [comment]
There's a PR for this and other issues so I'll close
