### ISSUE TITLE
"open in streamlink" no longer works...does not open up VLC

### ISSUE THREAD

**Issue by badbabykosh** [Chatterino/chatterino2#4326]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Right selecting a channel's name to click "open in streamlink" no longer opens vlc. Streamlink setting can be found in preferences/external tools. Streamlink will work from command line and will open VLC. But using this feature via right clicking a channel's name will no longer works in Chatterino

### OS and Chatterino Version

Chatterino 2.4.0 (commit 2ba4da0 modified) built with Qt 5.15.7 Running on KDE Flatpak runtime, kernel: 6.0.12-76060006-generic, running from Flatpak

**Comment by Felanbird** [comment]
It still works for me on Windows, but it opens an audio-only stream in VLC

Opening from command line crashes as expected due to all the changes Twitch added.

**Comment by tintinmaster** [comment]
I have the same problem on
Chatterino 2.4.2 (commit [c8204ef7](https://github.com/Chatterino/chatterino2/commit/c8204ef7)) built with Qt 5.12.12
Running on Linux Mint 21.1, kernel: 5.19.0-38-generic
Using the latest streamlink version 5.3.1

The output in the terminal when trying this is:
```
chatterino.streamlink: Got error code 1
[cli][info] Found matching plugin twitch for URL twitch.tv/forsen
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: "vlc"
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 2)
[plugins.twitch][info] Waiting for pre-roll ads to finish, be patient
[stream.hls][info] Filtering out segments and pausing stream output
[cli][info] Player closed
[stream.hls][info] Resuming stream output
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

When using streamlink manually via the command line:
```
~ streamlink twitch.tv/forsen 1080p
[cli][info] Found matching plugin twitch for URL twitch.tv/forsen
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: "vlc"
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 2)
[plugins.twitch][info] Waiting for pre-roll ads to finish, be patient
[stream.hls][info] Filtering out segments and pausing stream output
[stream.hls][info] Resuming stream output
```

The process of streamlink looks the same for both cases when seeing it via htop, but VLC is never started when opening it via Chatterino.

**Comment by pajlada** [comment]
Works fine for me with default settings on Arch Linux

![image](https://github.com/Chatterino/chatterino2/assets/962989/3a2b976c-f79c-424f-83c5-e09e4b042ed6)

![image](https://github.com/Chatterino/chatterino2/assets/962989/7b5b4019-378f-4138-b726-12464b8e1041)

If this is still an issue, please try it on a fresh installation or VM. If you can reproduce it there, re-open the issue and I will investigate this further.
