### ISSUE TITLE
The beta version is newer than the actual release version

### ISSUE THREAD

**Issue by 8thony** [Chatterino/chatterino2#4327]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I am on version 2.4.0.
If receiving Beta updates is enabled, the updater shows that version 2.4.0-beta is available, which is older than the actual 2.4.0 release.
Below is the result with different versions.
| | 2.4.0-beta |  2.4.0 |
| ------------- | ------------- | ------------- |
|  on version x with beta enabled | | |
| 2.3.5  | :heavy_check_mark: | :heavy_multiplication_x:  |
| 2.4.0-beta  | :heavy_multiplication_x: | :heavy_multiplication_x:  |
| 2.4.0  | :heavy_check_mark:  | :heavy_multiplication_x:  |
| | | |
| on version x with beta disabled | | |
| 2.3.5 | :heavy_multiplication_x:  | :heavy_check_mark:|
| 2.4.0-beta | :heavy_multiplication_x: | :heavy_check_mark:|
| 2.4.0 | :heavy_multiplication_x: | :heavy_multiplication_x: |

### Screenshots

N/A

### OS and Chatterino Version

Chatterino 2.4.0 (commit a0f9310) Windows 10

**Comment by fourtf** [comment]
fixed now?

**Comment by Felanbird** [comment]
> fixed now?

yes
![image](https://user-images.githubusercontent.com/41973452/214141610-5a77eafb-7a0a-4b47-8f3a-4a79a40f25a4.png)
![image](https://user-images.githubusercontent.com/41973452/214141367-fcb342cd-ee2a-43a7-ab9b-6f743c3b5bc5.png)

**Comment by fourtf** [comment]
at last I pog
