### ISSUE TITLE
Not Logging

### ISSUE THREAD

**Issue by josencarnacao** [Chatterino/chatterino2#4330]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Moderation / Logs / Enable Logging == CHECKED

Your logs currently take up 0.00 Bytes of space.

I had a previous version that would log chat from channels I follow via Chatterino, on the same Win11 version.
Reinstalled Windows 11, etc. and now Chatterino does not save chat into Log files.

### Screenshots

![230126 175229 Settings](https://user-images.githubusercontent.com/55637758/214911762-8fb30c1a-7c44-477d-a28c-ff67fdc3376e.png)

### OS and Chatterino Version

Chatterino 2.4.0 (commit a0f93100 modified) built with Qt 5.15.2, Windows SDK, MSVC 193331631 Running on Windows 10 Version 2009, kernel: 10.0.22000

**Comment by Felanbird** [comment]
That's probably just a visual bug, windows has not yet indexed today's logs so they appear as 0KB - I have the same visual issue if I go into the folder for any channel, today's logs are 0KB but if you open them in a text editor it fixes them.

![image](https://user-images.githubusercontent.com/41973452/214915506-357e9091-ed8c-4a82-843b-4e571f445bd3.png)
![image](https://user-images.githubusercontent.com/41973452/214915573-37a65c4b-10c3-4819-b075-f53772c9ff99.png)

**Comment by Felanbird** [comment]
As I mentioned above this is just a visual bug due to a minor thing on windows.
