### ISSUE TITLE
Chatterino randomly closes

### ISSUE THREAD

**Issue by MatthewSH** [Chatterino/chatterino2#4332]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I don't know why it happens, but I'll come back to Chatterino randomly closed. I have to manually re-open it.
I'm in about 40 channels, but only 5ish are live at any given moment. There's no "crash" window and I can't see any logs. I don't close Chatterino myself ever. It just randomly closes.

This didn't start happening till the past few months, even on my new build.

### OS and Chatterino Version

2.4.0 / 2.4.0-beta

**Comment by Felanbird** [comment]
It's probably #2432

**Comment by MatthewSH** [comment]
Thanks, I was searching for different keywords so that didn't show up for me.
