### ISSUE TITLE
"QBuffer::seek: Invalid pos" log spam on stderr

### ISSUE THREAD

**Issue by Muzuwi** [Chatterino/chatterino2#4337]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino is spamming "QBuffer::seek: Invalid pos: <offset>" to stderr while running. The offsets are random every time, and this happens roughly every minute (sometimes longer), spamming about 200 lines at a time. No particular actions were being done at that time, just chatterino running in the background. However, it seems to also randomly happen on joining any channel (not always, might require multiple tries). 

### Screenshots

[stderr.log](https://github.com/Chatterino/chatterino2/files/10529533/stderr.log)

### OS and Chatterino Version

Chatterino 2.4.0 (commit 4958d0803) built with Qt 5.15.8 Running on Manjaro Linux, kernel: 5.15.89-1-MANJARO

**Comment by pajlada** [comment]
Without more information, there's nothing I can do as I cannot reproduce this

Please create a new issue if you're able to pin down how to recreate this or how to stop it from happening.
You might be able to figure out where `QBuffer::seek: Invalid pos` is printed in Qt and set a breakpoint there to maybe bubble up to C2 code.

**Comment by Muzuwi** [comment]
For future reference, I managed to pin this down to kimageformats (after a recent update, v5.102.0) doing something weird with the Qt image decoders. Not sure what exactly, but removing it made the log spam issue go away so there's probably some weird compatibility issue in there.

**Comment by zer** [comment]
I'm experiencing the same issue as Muzuwi on Fedora 38 with Qt 5.15.10. Uninstalling `kf5-kimageformats` did work.
If someone still needs the support for the specific image formats it adds to QImage then maybe using the logging rules that #4637 added is the way to go.
I simply start chatterino with this environment now: `'QT_LOGGING_RULES=*=false'`
But careful, this disables all logging.
