### ISSUE TITLE
Chatterino having server connection issue

### ISSUE THREAD

**Issue by liansumsian** [Chatterino/chatterino2#4338]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Application having server connection timed out.

### Screenshots

![Capture](https://user-images.githubusercontent.com/72678225/215326067-1f2deaf7-0751-4869-837b-6020e796ec4b.JPG)

### OS and Chatterino Version

Chatterino 2.4.0 (commit a0f93100 modified) built with Qt 5.15.2, Windows SDK, MSVC 193331631 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by pajlada** [comment]
This is the only report that's coming in about connectivity issues, this is most likely an issue on your end.
You can experiment with the `CHATTERINO2_TWITCH_SERVER_` environment variables to try to force which IRC server to connect to

Read more here https://wiki.chatterino.com/Environment%20Variables/#chatterino2_twitch_server_host
