### ISSUE TITLE
Image uploader imgur not working

### ISSUE THREAD

**Issue by doomtrigger** [Chatterino/chatterino2#4396]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

images are not uploading i had it working before but chatterino randomly decided to wipe my account pretty sure everything is correct
![54364356](https://user-images.githubusercontent.com/41402593/220061097-b96732e7-00df-40b1-b4c5-be8dbadefe9c.png)

### OS and Chatterino Version

Chatterino Nightly 2.4.0 (commit 6380fb51) built on 2023-02-16 with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by doomtrigger** [comment]
![image](https://user-images.githubusercontent.com/41402593/220063046-b4b3baee-ea0b-4b49-be37-c64e9cddb745.png)
sorry

**Comment by Felanbird** [comment]
So it's very likely there's a trailing space in both the `Image Link` and `Deletion Link` boxes

**Comment by doomtrigger** [comment]
found one in image link but now its doing this 
![image](https://user-images.githubusercontent.com/41402593/220064432-d147d690-8f62-4650-83f0-df6d6c4893e6.png)

**Comment by Felanbird** [comment]
`403` is the error code for `Forbidden` meaning your authorization token is incorrect

**Comment by Coldblackice** [comment]
Old thread, but looks like Imgur's API is down for the count for pasting images in Chatterino ☹️

Googling this issue reveals it's a worldwide issue on Imgur's side with their API, and apparently it is not likely to get fixed by them. FYI
