### ISSUE TITLE
AppImage 2.4.1 doesn't connect

### ISSUE THREAD

**Issue by KaMyKaSii** [Chatterino/chatterino2#4397]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

It was working normally yesterday while I was still on v2.4.0. Chatterino is not retrieving previous chat messages, is not showing stream information, and is not connecting with third-party emote services. I tried removing my account and adding it again but it stayed the same. I can delete Chatterino configuration files if needed.
[log.txt](https://github.com/Chatterino/chatterino2/files/10785204/log.txt)

### Screenshots

![Screenshot from 2023-02-20 11-05-11](https://user-images.githubusercontent.com/17092335/220128903-2f108a11-03ae-4ab3-a853-7bfff27f2d98.png)

### OS and Chatterino Version

Chatterino 2.4.1 (commit 5ed4a21d) built with Qt 5.15.2 Running on Linux Mint 21.1, kernel: 5.15.0-60-generic

**Comment by Lem** [comment]
Tried to use AppImage on an up to date ArchLinux. Getting same error in UI and these errors on stdout:

`qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate`

Somehow 2.4.0 as AppImage worked for me.

**Comment by pajlada** [comment]
@Lem For now you can use [chatterino2-git](https://aur.archlinux.org/packages/chatterino2-git) from AUR

**Comment by KaMyKaSii** [comment]
> Could you try using the Ubuntu 22.04 `.deb` file instead of the AppImage? https://github.com/Chatterino/chatterino2/releases/tag/v2.4.1

Thank you, it's working!

**Comment by pajlada** [comment]
It has to do with the AppImage linking to `libssl-1` but not including it in the appimage

**Comment by pajlada** [comment]
I have updated the 2.4.1 release AppImage

**Comment by Lem** [comment]
@pajlada Sorry for the noise, but thank you very much for the fix.
