### ISSUE TITLE
Expired login Suggestion

### ISSUE THREAD

**Issue by CycIoneTM** [Chatterino/chatterino2#4399]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Once login has expired I am required to click the remove button before I can click add and paste login info. In my ideal world you'd be able to readd the old account that has the expired login by just pasting login info and not having to click the remove button it seems like an unnecessary step.

### Screenshots

(Don't have an expired login to give an example)

### OS and Chatterino Version

Chatterino Nightly 7.4.1 (commit [f6c90d99](https://github.com/Chatterino/chatterino2/commit/f6c90d99)) built on 2023-02-20 with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad
Running on Windows 10 Version 2009, kernel: 10.0.22621

**Comment by Felanbird** [comment]
> Once login has expired I am required to click the remove button before I can click add and paste login info. 

This is not true
![qtcreator_2023-02-20_12-29-26](https://user-images.githubusercontent.com/41973452/220170087-62ed21f9-bd40-40f7-9162-15e378d0711b.gif)
