### ISSUE TITLE
"Log In (Opens in browser)" does not open anything

### ISSUE THREAD

**Issue by Sithrazer** [Chatterino/chatterino2#4401]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I can't log in to twitch through chatterino.

I'm using the AppImage nightly release on OpenSUSE Tumbleweed KDE (X11 session but Wayland is available)

Going to 'Options > Account > Add > Log In (Opens in browser)' fails to open a browser window (even with a browser already open) and throws the following error in the terminal:

`chatterino.widget: open login in browser
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/tmp/.mount_ChatteIZKpcM/usr/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.`

### OS and Chatterino Version

Chatterino 2.4.1 (commit 7e005ba6) built with Qt 5.12.12 Running on openSUSE Tumbleweed, kernel: 6.1.12-1-default

**Comment by pajlada** [comment]
Right now you have two workaround options:
1) Use the flatpak release
2) Open https://chatterino.com/client_login manually and copy your token from there into your Chatterino

I'll need some further time to investigate these AppImage issues since it works on my machine.

**Comment by pajlada** [comment]
Tested on my super bare-bones Arch Linux installation, with only X11, i3, firefox, and fuse installed and ran the appimage and it works.

**Comment by Sithrazer** [comment]
Opening the link directly worked, the paste button worked and added my account to the chatterino appimage.

The flatpak version worked correctly and opened a browser tab for the login page. Flatpak also installed several KDE components from versions older than what ships with OpenSUSE, I wouldn't think that would matter but here's what flatpack installed

    ID                                              Branch                Op            Remote             Download
    1. [✓] com.chatterino.chatterino.Locale                nightly               i             flathub              5.1 kB / 51.4 kB
    2. [✓] org.freedesktop.Platform.GL.default             21.08                 i             flathub            129.6 MB / 129.8 MB
    3. [✓] org.freedesktop.Platform.VAAPI.Intel            21.08                 i             flathub             11.8 MB / 11.9 MB
    4. [✓] org.freedesktop.Platform.openh264               2.0                   i             flathub              1.8 MB / 1.5 MB
    5. [✓] org.gtk.Gtk3theme.Breeze                        3.22                  i             flathub            228.3 kB / 190.8 kB
    6. [✓] org.kde.Platform.Locale                         5.15-21.08            i             flathub             17.9 kB / 347.9 MB
    7. [✓] org.kde.Platform                                5.15-21.08            i             flathub            361.4 MB / 310.6 MB
    8. [✓] com.chatterino.chatterino                       nightly               i             flathub              5.0 MB / 4.8 MB

and what my current OS/DE info as reported by OpenSUSE

    Operating System: openSUSE Tumbleweed 20230219
    KDE Plasma Version: 5.27.0
    KDE Frameworks Version: 5.103.0
    Qt Version: 5.15.8
    Kernel Version: 6.1.12-1-default (64-bit)
    Graphics Platform: X11

I'm going to close this as the workarounds work. Thanks for the assistance!

**Comment by pajlada** [comment]
After testing, this has to do with `libxcb` on opensuse vs arch linux/ubuntu etc. The optimal solution in my books will be to use flatpak (it's ok if the version it installs is different from your system version), or to provide an rpm or whatever opensuse uses for a native installation.
