### ISSUE TITLE
Include normally-stripped mention in replies in logs

### ISSUE THREAD

**Issue by ScrubN** [Chatterino/chatterino2#4419]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When a reply to a message gets logged, only the body contents of the message is logged, meaning the context that it was a reply to a specific user is lost.

For example, the following chat:
```
UserA: Foobar!
┌ Replying to @UserA: Foobar!
UserB: Baz!
```
when logged becomes:
```
[00:00:00]  UserA: Foobar!
[00:00:00]  UserB: Baz!
```

---

My proposed solution is to do what both the Twitch mobile app and VOD player do, which is to prefix the message body with the @ mention of the user being replied to.

For example, the following chat:
```
UserA: Foobar!
┌ Replying to @UserA: Foobar!
UserB: Baz!
```
when logged would become:
```
[00:00:00]  UserA: Foobar!
[00:00:00]  UserB: @UserA Baz!
```

### Screenshots

In chatterino:
![image](https://user-images.githubusercontent.com/72096833/221771872-202ffe08-f38f-4786-92e8-64f6e95d285d.png)

Currently logged:
![image](https://user-images.githubusercontent.com/72096833/221771917-4d84eaa9-492b-4d9b-a13f-f425b373ecc3.png)

Proposed solution:
![image](https://user-images.githubusercontent.com/72096833/221772100-ef26a7de-5168-4728-80ed-981632954bb9.png)

VOD player:
![image](https://user-images.githubusercontent.com/72096833/221785149-fc2b4d98-9a14-46c9-bc78-f4e5742b16f9.png)

### OS and Chatterino Version

Chatterino 2.4.1 (commit 5ed4a21d) built with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by pajlada** [comment]
I would be fine with a PR that ensures the mention is included in the logged message.
