### ISSUE TITLE
FFZ emotes no longer work

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4430]
FFZ used to send us API responses as follows `//cdn.frankerfacez.com/xddddd` without the necessary `https:`, so we manually added the `https:` so we could correctly display emotes.

As of a few hours ago, FFZ has resolved this, but unfortunately we did not want this resolved, and as a result chatterino now sends requests to `https:https://cdn.frankerfacez.com/xddddd` and said requests fail.

https://github.com/Chatterino/chatterino2/blob/1dc2bcc445d50378ed6c6664cf009373cbf7b0a7/src/providers/ffz/FfzBadges.cpp#L70-L77
https://github.com/Chatterino/chatterino2/blob/1dc2bcc445d50378ed6c6664cf009373cbf7b0a7/src/providers/ffz/FfzEmotes.cpp#L19-L29

**Comment by Felanbird** [comment]
Fixed in #4432 - when this comment is about 30 minutes old you can get the fix in the latest [nightly build](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build), 2.4.2 will probably have to come out tomorrow. 🧘‍♂️

**Comment by theonefoster** [comment]
https://xkcd.com/1172/

**Comment by Felanbird** [comment]
2.4.2 is out now https://github.com/Chatterino/chatterino2/releases/tag/v2.4.2
