### ISSUE TITLE
Highlight audio breaks on Windows

### ISSUE THREAD

**Issue by Greenlandicsmiley** [Chatterino/chatterino2#4457]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Description:
Chatterino highlight audio dissappears sometimes. What exactly causes it have yet to be determined. This is definitely something to do with miniaudio.

Examples:

- I've had Chatterino open for longer than 3 days and at some point audio stopped playing. Discoord voice chat was not used at all during those 3 days.
- I was playing a game (specifically Minecraft, but definitely not the only game) with friends while on Discord voice chat, and highlight audio stopped playing after at least 2 hours.

I do not have a debug log, so if you can tell me which debugging tool to use I will provide a log.

### OS and Chatterino Version

Chatterino Nightly 2.4.2 (commit 0acbc0d2) on Windows 10 version 22H2 (build 19045.2728)

**Comment by Dolev24** [comment]
ping sound disappears after pc comes back from sleep mode

**Comment by pajlada** [comment]
Tried reproducing on my Windows system but it wasn't easy to reproduce, will be continuing to look into this

**Comment by pajlada** [comment]
I was able to reproduce this by changing user in Windows, a fix is in place in #4549
