### ISSUE TITLE
FrankerFaceZ animated emotes not showing up as animated

### ISSUE THREAD

**Issue by apa420** [Chatterino/chatterino2#4464]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

FrankerFaceZ got a big update with some extra features ![added](https://twitter.com/FrankerFaceZ/status/1633990233577648128).
The main feature chatterino doesn't seem to support (as of Chatterion 2.4.2) is animated emotes such as https://www.frankerfacez.com/emoticon/722120-WidezyzzPls which can be found for example at my twitch chat (my username).
The emote is instead using the static version as seen in the video.

Docs for ffz can be found https://api.frankerfacez.com/docs/ which do seem to be updated since there is a new "animated" field.

### Screenshots

https://user-images.githubusercontent.com/17131426/226175979-0c18bfab-02f6-43c1-8b57-f7299134792f.mp4

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 8.1 Version 6.3 (Build 9600), kernel: 6.3.9600

**Comment by leon-richardt** [comment]
https://github.com/Chatterino/chatterino2/pull/4434 ?

**Comment by apa420** [comment]
yes, didn't show up since I only searched for issues
