### ISSUE TITLE
Font rendering issues when built with Qt 6

### ISSUE THREAD

**Issue by brian6932** [Chatterino/chatterino2#4467]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Weird font rendering (left Qt 6.5.0, right Qt 5.15.2) Font used: [FantasqueSansMono-NoLoopK](https://github.com/belluzj/fantasque-sans) (1.8.0)
![image_83](https://user-images.githubusercontent.com/18603393/226489554-05cd31b1-f308-41f4-bbd3-f60fd19b5105.png)
~~- windeployqt says `Cannot open .: Access is denied.`, it still works, just odd error, this did not happen with Qt 5.15.2 (maybe related? not sure, not sure even if anything could be done for something like this, just reporting findings)~~

While these screenshots are for `dankerino`, the same issues occurred with c2
I used the dankerino screenshots, as it made the differences clearer with `Gray-out recent messages` disabled
cmake flags used: `cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_QT6=ON -DQT_DEBUG_FIND_PACKAGE=ON -DCMAKE_DISABLE_FIND_PACKAGE_WrapVulkanHeaders=TRUE -DCHATTERINO_LTO=ON`

### OS and Chatterino Version

Chatterino 2.4.2 (commit 7b609490) built with Qt 6.5.0, Windows SDK, MSVC 193532215 Running on Windows 10, kernel: 10.0.20152

**Comment by Nerixyz** [comment]
> * windeployqt says `Cannot open .: Access is denied.`, it still works, just odd error, this did not happen with Qt 5.15.2 (maybe related? not sure, not sure even if anything could be done for something like this, just reporting findings)
> [...]
> ```
> ❯ windeployqt chatterino.exe
> ```

You're running incorrectly for chatterino ([take a look at how it's done in CI](https://github.com/Chatterino/chatterino2/blob/7b6094909ee807558263c30a5ebc97fa968ce170/.github/workflows/build.yml#L175) and [the official documentation](https://doc.qt.io/qt-6/windows-deployment.html)). 

For chatterino, you want to disable translations (`--no-translations`, the feature causing your invocation to fail). CI also doesn't include the software rasterization library (`--no-opengl-sw`) and omits deploying the VC runtime (`--no-compiler-runtime`).

**Comment by brian6932** [comment]
@Nerixyz Ty that works, however the font rendering issue still exists, I'll update the post accordingly
```
❯ & "$env:Qt6_DIR\bin\windeployqt.exe" bin/chatterino.exe --no-translations --no-opengl-sw --no-compiler-runtime
QCommandLineParser: already having an option named "no-virtualkeyboard"
C:\Users\brian\Documents\GitHub\dankerino\build\bin\chatterino.exe 64 bit, release executable
Adding Qt6Svg for qsvgicon.dll
Adding Qt6Pdf for qpdf.dll
Skipping plugin qtvirtualkeyboardplugin.dll due to disabled dependencies (Qt6Qml Qt6Quick).
Direct dependencies: Qt6Core Qt6Core5Compat Qt6Gui Qt6Network Qt6Widgets
All dependencies   : Qt6Core Qt6Core5Compat Qt6Gui Qt6Network Qt6Widgets
To be deployed     : Qt6Core Qt6Core5Compat Qt6Gui Qt6Network Qt6Pdf Qt6Svg Qt6Widgets
Updating Qt6Core.dll.
Updating Qt6Core5Compat.dll.
Updating Qt6Gui.dll.
Updating Qt6Network.dll.
Updating Qt6Pdf.dll.
Updating Qt6Svg.dll.
Updating Qt6Widgets.dll.
Updating d3dcompiler_47.dll.
Creating directory ~/Documents/GitHub/dankerino/build/bin/generic.
Updating qtuiotouchplugin.dll.
Creating directory ~/Documents/GitHub/dankerino/build/bin/iconengines.
Updating qsvgicon.dll.
Creating directory ~/Documents/GitHub/dankerino/build/bin/imageformats.
Updating qgif.dll.
Updating qicns.dll.
Updating qico.dll.
Updating qjpeg.dll.
Updating qpdf.dll.
Updating qsvg.dll.
Updating qtga.dll.
Updating qtiff.dll.
Updating qwbmp.dll.
Updating qwebp.dll.
Creating directory ~/Documents/GitHub/dankerino/build/bin/networkinformation.
Updating qnetworklistmanager.dll.
Creating directory ~/Documents/GitHub/dankerino/build/bin/platforms.
Updating qwindows.dll.
Creating directory ~/Documents/GitHub/dankerino/build/bin/styles.
Updating qwindowsvistastyle.dll.
Creating directory ~/Documents/GitHub/dankerino/build/bin/tls.
Updating qcertonlybackend.dll.
Updating qopensslbackend.dll.
Updating qschannelbackend.dll.
```

**Comment by brian6932** [comment]
Post PR (left Qt 6.5.0, right Qt 5.15.2):
![image](https://user-images.githubusercontent.com/18603393/228436383-4293207c-18f9-4a80-8d8a-8a6463854032.png)
It is a bit different, but much better than before
