### ISSUE TITLE
Reply context doesn't respect the block list

### ISSUE THREAD

**Issue by BrotherJohn1** [Chatterino/chatterino2#4481]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When a chatter replies to someone you have blocked it will show the message that the blocked person said.

### OS and Chatterino Version

Chatterino 7.4.2 (commit c140c88) on Windows 10

**Comment by 2547techno** [comment]
Which would be the best option?
1. ignore the entire message that is replying to the blocked user
2. censor the text of the blocked user if "Show message reply context" settings is enabled
3. do not show reply context is it from the blocked user
