### ISSUE TITLE
Viewer list does not load

### ISSUE THREAD

**Issue by cavrt** [Chatterino/chatterino2#4491]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

This seems like it could be a network related issue. I have two separate portable Chatterino installations and both will occasionally simultaneously not allow me to load any viewer lists from any channels, it only shows 'Loading...'

This recent time it has stopped working for hours straight, usually it's only a number of minutes. It doesn't show viewer count either. This is for live and offline channels.

I have tried clearing the cache. The logs folder is empty. Launching each portable version independently of another doesn't fix it. Both installs are the same version. Everything else works fine, not sure what other info I can provide.

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19042

**Comment by Felanbird** [comment]
It's intentional see - https://discuss.dev.twitch.tv/t/legacy-chatters-endpoint-shutdown-details-and-timeline-april-2023/43161

Download the latest [nightly build](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) if you are a mod and require the viewerlist.

I'll add it to the pins at the top of issues later

**Comment by cavrt** [comment]
Do you think they're ever going to allow non-moderators to use Get Chatters?

**Comment by Felanbird** [comment]
> Do you think they're ever going to allow non-moderators to use Get Chatters?

Probably not, it would likely require a major system implemented by us, and then opted into by basically every streamer, to properly restore functionality.

**Comment by LosFarmosCTL** [comment]
> Do you think they're ever going to allow non-moderators to use Get Chatters?

They even removed the ability for non-mods to see the full user list from their 1st party website, so I'd give the endpoint being available for normal chatters a practically nonexistent chance of happening.

**Comment by cavrt** [comment]
Thank for for the responses. One more question: why would a moderator token be required for the API but not for the viewer list on their website?

**Comment by Felanbird** [comment]
> Thank for for the responses. One more question: why would a moderator token be required for the API but not for the viewer list on their website?

Technically it _is_, you are given only a section of the viewer list as a pleb in browser chat, as a VIP or mod you can keep scrolling until you've loaded everybody
