### ISSUE TITLE
Migrate Twitch badges to Helix

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4492]
As part of Twitch's announced deprecation of ~~IRC commands~~ everything, the endpoint we get badges from is being deprecated and will need to be migrated to the relevant Helix API endpoint.

As far as I can see from the documentation, there are no restrictions like most other deprecation, and functionality should continue to work as expected. (or even better if you were effected by #4071 or #4456)

Announcement:
https://discuss.dev.twitch.tv/t/legacy-badges-endpoint-shutdown-details-and-timeline-june-2023/44621

Relevant documentation:
https://dev.twitch.tv/docs/api/reference/#get-global-chat-badges
https://dev.twitch.tv/docs/api/reference/#get-channel-chat-badges

**Comment by pajlada** [comment]
This is a pretty easy fix, it would be a good match for any new contributors that have been looking to do something for Chatterino.

If you're interested in working on this issue, please say so in this issue and we'll assign you to the issue & help you out with any questions you might have.

**Comment by ZonianMidian** [comment]
> If you're interested in working on this issue, please say so in this issue and we'll assign you to the issue & help you out with any questions you might have.

I would like to work on this issue
![image](https://user-images.githubusercontent.com/57513632/229309508-4bca32da-4fcc-444d-8776-105e3a21a633.png)
