### ISSUE TITLE
Ctrl+F Not Searching Extended Message History

### ISSUE THREAD

**Issue by RyanPotat** [Chatterino/chatterino2#4495]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

After increasing 'Split message scrollback limit', Ctrl+F or Ctrl+Shift+F will not search the extended history, and only search through the standard 1k messages.

### Screenshots

![image](https://user-images.githubusercontent.com/127474225/228997644-6c24d35f-ebac-4720-853e-f4b06fcb3c14.png)

### OS and Chatterino Version

Technorino Nightly 7.4.2 (commit 00f00e23) built on 2023-03-24 with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Felanbird** [comment]
While this isn't the first time I've heard about this, I'm wondering _when_ it broke, as I'm fairly sure it was confirmed in the PR adding this functionality, as I know I wanted to make sure searching an insane amount of messages would not cause any stability issues.
