### ISSUE TITLE
Memory leak due to loading recent messages on reconnects.

### ISSUE THREAD

**Issue by somso2e** [Chatterino/chatterino2#4497]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

There is about 100MB -150MB of memory leak after each reconnect and loading recent messages.

How to reproduce:
* Turn on load history messages and just spam ctrl+f5 to reconnect a bunch of times then disable it and do the same thing. Now compare memory usage.

### Screenshots

Here it is after 15-16 reconnects:
![image](https://user-images.githubusercontent.com/61581909/229278342-468f43fd-79f3-4430-a935-a0b11a3d45ea.png)
And here its before any reconnects:
![im![image](https://user-images.githubusercontent.com/61581909/229278440-469c5bf0-0e37-4df6-ba49-bd31dc875837.png)
age](https://user-images.githubusercontent.com/61581909/229278440-469c5bf0-0e37-4df6-ba49-bd31dc875837.png)

### OS and Chatterino Version

Chatterino Nightly 2.4.2 (commit 7a081fdc) built on 2023-03-30 with Qt 5.15.2, Windows SDK, MSVC 193431943, Crashpad, Running Windows 11 Pro Version 22H2

**Comment by leon-richardt** [comment]
Can reproduce this on Arch, commit [b9e87dcd2](https://github.com/Chatterino/chatterino2/commit/b9e87dcd2)
