### ISSUE TITLE
Viewer List stuck with "Loading..."

### ISSUE THREAD

**Issue by miqheil** [Chatterino/chatterino2#4511]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Regardless of channel, administration permit or way of starting Chatterino (I usually use it with streamlink-for-twitch), Viewer List stuck with "Loading...". That's it.

### Screenshots

![gUROPSTTOQ](https://user-images.githubusercontent.com/68017913/229613336-0c531381-35ca-406a-9eb8-9a66a18401e7.png)

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/229614005-b8821a40-41d4-4312-a298-77099d4b81be.png)
