### ISSUE TITLE
Add missing periods after mod-related messages (e.g. untimeouts)

### ISSUE THREAD

**Issue by Nerixyz** [Chatterino/chatterino2#4515]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

A timeout message is formatted like this: `Mod timed out User for 1s.`. An untimeout message is formatted like this: `Mod untimedout User`. **⚠️  NOTICE THE MISSING DOT!! ⚠️**

The fix should be pretty simple. After the following...

https://github.com/Chatterino/chatterino2/blob/5c08e996c6a8ed01edae9ac4a882eb935fc570c4/src/messages/MessageBuilder.cpp#L459-L464

...add:

```cpp
this->emplaceSystemTextAndUpdate(QStringLiteral("."), text);
```

### Screenshots

![image](https://user-images.githubusercontent.com/19953266/230205597-2a173055-f801-4845-ba5d-2950c0794be6.png)

### OS and Chatterino Version

Chatterino Nightly 7.4.1 (commit 4d593837 modified) built on 2023-03-05 with Qt 5.15.2, Windows SDK, MSVC 193431937, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment]
It's like that for all mod-only notices 
![image](https://user-images.githubusercontent.com/41973452/230207210-47976f3d-a741-4df9-bcda-ff51169b70d8.png)

**Comment by Nerixyz** [comment]
> It's like that for all mod-only notices

Then all of them should have a dot at the end.
