### ISSUE TITLE
Invisible usercard button icons

### ISSUE THREAD

**Issue by badoge** [Chatterino/chatterino2#4532]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The icons for the copy and pin buttons are invisible :)

Probably related to #4471 

### Screenshots

![image](https://user-images.githubusercontent.com/18620902/230810444-e61a49f9-75f0-4623-82ed-08b0925fd4bd.png)

### OS and Chatterino Version

Chatterino Nightly 2.4.2 (commit 00642ef7) built on 2023-04-09 with Qt 5.15.2, Windows SDK, MSVC 193431943, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by dnsge** [comment]
Can confirm this was introduced by 4e3433e96672e861d08f88813c12b6b442654b2f #4471
