### ISSUE TITLE
viewer list does not load list

### ISSUE THREAD

**Issue by faulconershelby** [Chatterino/chatterino2#4538]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

hello!
for the past two weeks, myself and two other friends who use chatterino on twitch are experiencing a bug in which the Viewer List that pops up when selecting the viewer panel never loads users, but displays the text, "Search User... Loading...". We are all using 2.4.2 version of chatterino and I have experienced this bug on both mac and windows computers. Thank you for investigating this. 

### Screenshots

![image](https://user-images.githubusercontent.com/97708148/231903119-73afb1f3-e91f-4633-8be8-f41e774e7590.png)
image of  the loading message

### OS and Chatterino Version

2.4.2

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/231903345-2b24a98c-c359-4e20-b3fe-4473d13f0d3b.png)

Twitch deleted it #4538

**Comment by Mm2PL** [comment]
Twitch shut it down.
See https://github.com/Chatterino/chatterino2/issues/4494

**Comment by faulconershelby** [comment]
> ![image](https://user-images.githubusercontent.com/41973452/231903345-2b24a98c-c359-4e20-b3fe-4473d13f0d3b.png)
> 
> Twitch deleted it #4494



> Twitch shut it down. See #4494

ty both
