### ISSUE TITLE
Cannot Load Viewer List

### ISSUE THREAD

**Issue by P0PPINVAL** [Chatterino/chatterino2#4544]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

For some reason when I open the viewer list it just continues to load non stop.

### Screenshots

![chatterino issue](https://user-images.githubusercontent.com/130831469/232203173-f31820c5-85b3-4226-9cc0-1752fa944dd3.png)

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) Windows 10

**Comment by pajlada** [comment]
Please read https://github.com/Chatterino/chatterino2/issues/4494 - it contains answers to the questions that you seek.
