### ISSUE TITLE
Twitch subscription emotes are not showing but other emotes are showing. 

### ISSUE THREAD

**Issue by chmelodyreal** [Chatterino/chatterino2#4562]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hi,

I cannot see nor use my twitch subscription emotes. There is no problem with other emotes (BTTV, 7TV or FFZ). I have 5+ subs and none of them is showing. There is a screenshot added.

I tried;
1- Removing Chatterino completely then reinstalling it.
2- Using different versions.
3- Using other twitch accounts.

I've tried using sub emotes in different channels too, but nothing has changed.

It was working fine then just stop working one day. I'm experiencing this issue for almost a week now. 

Is there anyone have/had this issue too?

### Screenshots

![1111](https://user-images.githubusercontent.com/86209978/233158835-e54141ae-340f-423f-81d9-e34731fb7eb3.png)

### OS and Chatterino Version

Chatterino 7.4.2 on Windows 10

**Comment by chmelodyreal** [comment]
> 

Yes, i do live in Turkey... is it because of that?

**Comment by Felanbird** [comment]
Yes unfortunately your ISP is blocking our emote proxy server, which is why it's failing to load, you aren't the only one in Turkey having this issue.

**Comment by chmelodyreal** [comment]
> 

Is there something i can do to fix this?

**Comment by Felanbird** [comment]
Not unless you are proficient in networking, the domain you want to access is https://api.ivr.fi/v2/

**Comment by chmelodyreal** [comment]
> Not unless you are proficient in networking, the domain you want to access is https://api.ivr.fi/v2/

I tried using VPN and i can see and use sub emotes now. Thank you for helping.
