### ISSUE TITLE
Qt6 Chatterino highlight settings menu crash

### ISSUE THREAD

**Issue by KararTY** [Chatterino/chatterino2#4563]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [x] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino crashes when I use mouse to reorder the highlight entries under the highlights settings.

### Screenshots

https://user-images.githubusercontent.com/13697809/233389950-7481193a-4c36-410f-9abb-84ff853c65eb.mp4

### OS and Chatterino Version

Chatterino Nightly 2.4.2 (commit cb0ab90f) built on 2023-04-17 with Qt 6.5.0, Windows SDK, MSVC 193431943, Crashpad Running on Windows 10 Version 1809, kernel: 10.0.17763

**Comment by Mm2PL** [comment]
Unable to reproduce on:
Chatterino 2.4.2 DEBUG (commit [cb0ab90f](https://github.com/Chatterino/chatterino2/commit/cb0ab90f)) built with Qt 5.15.8
Running on Arch Linux, kernel: 6.2.10-arch1-1

**Comment by KararTY** [comment]
Retested on non-experimental version, **doesn't crash**. Will stick to Qt5 version for now.

Chatterino Nightly 2.4.2 (commit [32499f0e](https://github.com/Chatterino/chatterino2/commit/32499f0e)) built on 2023-04-19 with Qt 5.15.2, Windows SDK, MSVC 193431943, Crashpad
Running on Windows 10 Version 1809, kernel: 10.0.17763
