### ISSUE TITLE
Proper ffz and bttw emote modifiers display

### ISSUE THREAD

**Issue by braintweak** [Chatterino/chatterino2#4566]
Bttw and FFZ has emote modifiers, that allow the emote to widen/flip horisontally/flip vertically/become cursed etc.
For now those don't get shown properly in chatterino, but do show in web chat with frankerfacez/bttw/7tv extensions (all to a different degree, but anyway).

The modifiers are:
w!, z!, v!, h! for bttw, 
ffzX, ffzY, ffzW, ffzCursed for ffz.
In browser chat the w! looks like this:
![изображение](https://user-images.githubusercontent.com/9693830/233591718-e2534901-4ebd-488f-8722-744b34aca763.png)

How they look in chatterino currently:
![изображение](https://user-images.githubusercontent.com/9693830/233593166-10847876-9729-4e40-8cf4-47674437f750.png)

### OS and Chatterino Version

Chatterino Nightly 2.4.2 (commit 32499f0e) Windows 10 2009

**Comment by pajlada** [comment]
Duplicate https://github.com/Chatterino/chatterino2/discussions?discussions_q=is%3Aopen+modifier
