### ISSUE TITLE
Split header tooltip shows on the wrong screen / monitor

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#4572]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The "live preview" image snaps to your main screen if it doesn't have room on the left most edge of your screen setup.

https://user-images.githubusercontent.com/26260419/233793643-877d8ee9-a140-4756-b8ce-51ce470e81e8.mp4

### OS and Chatterino Version

Chatterino Nightly 2.4.2 (commit 6d2605d4) built on 2023-04-21 with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 11 Version 2009, kernel: 10.0.22621

**Comment by mannin1337** [comment]
I have the same problem. Usercards also show on the primary monitor for me.
