### ISSUE TITLE
7TV animated emotes trailing effect on AppImage

### ISSUE THREAD

**Issue by Galtsuu** [Chatterino/chatterino2#4579]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

7TV animated emotes with transparent backgrounds have a trailing effect on v2.4.1 and v2.4.2 AppImages, issue is not present in v2.4.0
BTTV and Twitch animated emotes are unaffected, issue only with 7TV ones.

Below couple of examples with version 2.4.0, 2.4.1 and 2.4.2 from left to right respectively

### Screenshots

[Screencast from 25.04.2023 20.26.11.webm](https://user-images.githubusercontent.com/131803007/234355700-e8d46a41-8b8b-41b5-8f90-3f9b6057baff.webm)

[Screencast from 25.04.2023 20.32.37.webm](https://user-images.githubusercontent.com/131803007/234356738-ccb82aa0-f709-4e18-add0-99ee4d7fa823.webm)

Also visible in emote menu

[Screencast from 25.04.2023 20.49.04.webm](https://user-images.githubusercontent.com/131803007/234360376-0a22d832-11ca-4c35-ba2e-54e1f7eeda5d.webm)

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.12.12 Running on Ubuntu 22.04.2 LTS, kernel: 5.19.0-38-generic

**Comment by Felanbird** [comment]
Reminds me of the issue with 7TV animated PFP's https://github.com/SevenTV/chatterino7/pull/69#issuecomment-1079402996 - which turned out to be an issue with QT 5.12.12 

I wonder if this is the same style of issue, but it presents differently, as we switched the appimage from QT 5.15.2 because of https://github.com/Chatterino/chatterino2/issues/4397

**Comment by pajlada** [comment]
Can you try using the [flathub](https://flathub.org/apps/com.chatterino.chatterino) version or the [Ubuntu 22.04 .deb](https://github.com/Chatterino/chatterino2/releases/download/nightly-build/Chatterino-ubuntu-22.04-x86_64.deb)?
AppImage support is being phased out to a 'last resort' kind of distribution.
