### ISSUE TITLE
[Feature Request] Add more filters to find

### ISSUE THREAD

**Issue by DatGuy1** [Chatterino/chatterino2#458]
Maybe add an option to filter stuff, like in discord search. eg from:Ampzyh before:2018-06-05

**Comment by Yardanico** [comment]
Do you run your chatterino instance 24/7 to be able to do this ? :D

**Comment by DatGuy1** [comment]
eShrug just use the same system there is now that it indexes through the results that it can find

**Comment by SLCH** [comment]
Chatterino doesnt store all chat messages (like when program is off) and (should / does?) clear history after a while.
With that in mind adding a filter to look for message history sounds unnecessary.
eShrug

**Comment by Chronophylos** [comment]
well chatterino optionally logs all messages to a file. It could use them for the search as well

**Comment by zneix** [comment]
A few ideas for this issue:
- badge-specific search, e.g.: `badge:staff`, `badge:mod`
- subtier-specific search, e.g.: `subtier:3` (or `tier:3`)
- option to include multiple badges, tiers just like in `from:zneix,pajlada`, e.g.: `badge:mod,staff` `tier:2,3`
- option to just exclude some stuff but keep the rest, e.g.:
  - `badge:-sub` would only show pleb messages
  - `user:-weeb123` would show everyone's messages but weeb123's
  - `badge:staff user:-aidenwallis` would show all staff's messages excluding ones from aidenwallis

**Comment by fourtf** [comment]
Since there is no real usecase provided I'll close

**Comment by zneix** [comment]
can we reopen this? I kinda wanted to add some stuff from my last comment, I'd find that useful
