### ISSUE TITLE
Messages aren't saved in the history when sent via the command

### ISSUE THREAD

**Issue by x9136** [Chatterino/chatterino2#4592]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

<img width="723" alt="Screenshot 2023-05-02 at 07 45 51" src="https://user-images.githubusercontent.com/60105060/235581306-52569003-d8f2-44d3-a0a9-f31edaa9a85a.png">

Hello! I send some messages using the command. If you press the up arrow after using the command, the message won't be in the list. I think all sent messages should be available through the up arrow.

What could be the problem?

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.15.2 Running on macOS 13.2, kernel: 22.3.0

**Comment by Mm2PL** [comment]
Works As Intended. If you believe this needs changing please open a discussion.
