### ISSUE TITLE
Occasionally a new line is created instead of sending a message if you use a colon to select emotes

### ISSUE THREAD

**Issue by x9136** [Chatterino/chatterino2#4600]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Occasionally [Return] fails to send a message if you use a colon and select an emote from the drop-down list. Instead, [Return] moves the caret to the next line. It's not clear why this happens and how to get out of this mode.

**How I reproduce this**
Open a chat → Enter ":" and the beginning of an emote → Select an emote from the list → Press [Return] to send the message → A new line appears instead of sending the message.

This isn't always the case. There're times when everything is fine. Sometimes the sending is restored without rebooting the app. Nevertheless, this happens 10-20 times a day. Any idea why?

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.15.2 Running on macOS 13.2, kernel: 22.3.0

**Comment by Felanbird** [comment]
> and how to get out of this mode.

try clicking the client next time it happens

**Comment by x9136** [comment]
@Felanbird In my case, it doesn't work. But I found that if I open the popup window with all the emotes, then sending messages will work as usual.

**Comment by x9136** [comment]
This problem no longer exists since v 2.4.3.
