### ISSUE TITLE
Viewer List should be renamed to Chatter List

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#4640]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The name we use for the list is "Viewer List" but it's not really what the list contains.
Renaming it to "Chatter List" would also make it more in-line what Twitch calls it in web chat: "Users in Chat"

Most important is that the user-facing usage of the word is changed, this includes the wiki glossary.

Another separate refactor can then be made in code to rename internal references from Viewer ... to Chatter ... 

- [x] User facing changes #4732
- [ ] Code changes

### OS and Chatterino Version

N/A

**Comment by SputNikPlop** [comment]
I am happy to take this up if no one else is working on this right now.

**Comment by pajlada** [comment]
> I am happy to take this up if no one else is working on this right now.

I don't think anyone is, I'll assign you the issue. Thank you!
Let us know here if you run into any issues or have any questions

**Comment by SputNikPlop** [comment]
@pajlada Would you prefer I break what the user sees into one PR then move onto doing an internal refactor?

**Comment by pajlada** [comment]
> @pajlada Would you prefer I break what the user sees into one PR then move onto doing an internal refactor?

Splitting it up into two PRs like that sounds like a good idea, yeah!

**Comment by SputNikPlop** [comment]
@pajlada I think I got it, just one thing I had to install Rosetta 2 to make it work on my Mac
