### ISSUE TITLE
Imgur image previews not working

### ISSUE THREAD

**Issue by MCJack123** [Chatterino/chatterino2#4647]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Since a few weeks ago, I'm no longer able to see previews for any Imgur link. Instead, Chatterino just shows the standard "Could not fetch link info: No link info found" that appears on URLs that don't exist. To reproduce, simply type any `i.imgur.com` URL in chat, and then hover over it (with link previews enabled). I expect the image to appear as a preview, but instead nothing shows up.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/6236912/a55104e0-d284-4c7b-8d99-16508fa3b264)

### OS and Chatterino Version

Chatterino 2.4.4 (commit e9f300b76) built with Qt 5.15.9 Running on Arch Linux, kernel: 6.3.2-arch1-1

**Comment by Felanbird** [comment]
Probably imgur's fault, it started happening during the end of the previous month when people were rushing to archive the entire website. I meant to ask pajlada if he was getting any fixable errors but I forgot to.

**Comment by Mm2PL** [comment]
Either imgur issue or chatterino api issue. Probably should be moved to https://github.com/Chatterino/api/. I don't have perms to do that.

Can reproduce.

**Comment by Felanbird** [comment]
We looked into it and confirmed it is indeed on imgur's end, they are aggressively rate-limiting us and probably all servers on our server hoster (hetzner). We were able to confirm this due to a server hosted by hetzner also being blocked, despite not being used to interact with imgur at all.
