### ISSUE TITLE
Messages not appearing in any chats besides one.

### ISSUE THREAD

**Issue by Jawman2000** [Chatterino/chatterino2#4649]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I can't type messages in any chats/channels besides one, aka the main one I chat in.

-Type a message in the main _x_ chat and I can see it in Chatterino and people respond like normal.

-Type a message in _y, z, etc_ chats and it does not appear in chat (native or Chatterino) and no one sees it.

-When I type in native chat the message appears in native chat but does not appear in Chatterino and no one can see it.

I tried installing the most recent version of Chatterino from 7.4.2 to 7.4.4 and no change. I also tried signing out of Chatterino and native Twitch and re-logging in and no fix/change. 

### OS and Chatterino Version

Chatterino 7.4.4 (commit 90ee0afd) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.22000

**Comment by sando** [comment]
If you can chat in channels where you are mod/VIP/sub but not in others, you are likely shadowbanned by Twitch. This can happen if you've spammed too much in chat, or if you're logging in from a bad IP (e.g. from VPN). It usually goes away after a few hours.

See https://wiki.chatterino.com/Help/#why-are-my-messages-being-sent-in-webchat-but-not-in-chatterino.

**Comment by Felanbird** [comment]
What sando said ☝️ - not a Chatterino issue.
