### ISSUE TITLE
Menu shortcut indicators don't show on Mac

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#4657]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

We were informed that menu shortcuts don't work on Mac. This is both a Qt5 and Qt6 issue.

### Screenshots

> ![image](https://github.com/Chatterino/chatterino2/assets/25011746/19b8add6-c72e-41f5-afaf-8f7910063779)
https://github.com/Chatterino/chatterino2/discussions/4627#discussioncomment-6019447

### OS and Chatterino Version

Chatterino 2.4.4 (commit 29a14627) built with Qt 6.5.0 Running on macOS Ventura (13.2), kernel: 22.3.0

**Comment by PsycloneTM** [comment]
Tested on Chatterino 2.4.1 (commit [5ed4a21d](https://github.com/Chatterino/chatterino2/commit/5ed4a21d)) built with Qt 5.15.2 Running on macOS 12.5, kernel: 21.6.0 

Menu shortcut hotkeys aren't showing.
![Screen Shot 2023-05-30 at 1 59 21 PM](https://github.com/Chatterino/chatterino2/assets/27637025/95477a35-7fcb-4c3d-8af5-1056a0ef2925)
