### ISSUE TITLE
Highlight sound stops playing over time

### ISSUE THREAD

**Issue by x9136** [Chatterino/chatterino2#4662]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hello!

Starting with v2.4.3 I have problems with the highlight sound. I select an mp3 file to hear it when people contact me in chats. Eventually it stops playing until I re-select it in the settings.

Before that, the selected mp3 file worked the whole time. I can't tell if the built-in highlight sound is working properly.

What could be the problem?

### OS and Chatterino Version

Chatterino 2.4.4 (commit 29a14627) built with Qt 6.5.0 Running on macOS Ventura (13.2), kernel: 22.3.0

**Comment by pajlada** [comment]
Will have the same fix as https://github.com/Chatterino/chatterino2/issues/4613
