### ISSUE TITLE
Streamer mode button shows on restart even though it's disabled

### ISSUE THREAD

**Issue by sando** [Chatterino/chatterino2#4682]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

If streamer mode is set to disabled, the title bar button is still shown at startup.

![chatterino_niMnXaoJoN](https://github.com/Chatterino/chatterino2/assets/58441/a8c07731-ebd0-4099-be9e-bfd9d1f90d98)

The button will disappear if you change from disabled -> auto -> disabled, but when Chatterino is restarted, it'll appear again.

If set to auto and restarted, it behaves as expected (although it does appear briefly while Chatterino is starting).

### OS and Chatterino Version

Chatterino Nightly 2.4.4 (commit a045d3ee) built on 2023-06-11 with Qt 6.5.0, Windows SDK, MSVC 193532217, Crashpad Running on Windows 11 Version 23H2, kernel: 10.0.25381

**Comment by Felanbird** [comment]
I saw this at some point while testing some other PR, I don't specifically remember screwing with that setting but I can also replicate said fact from this report.

It's also possibly a windows only issue since I visually confirmed the icon wasn't there but didn't confirm by scrolling my mouse over the area, when reviewing the PR.

**Comment by Nerixyz** [comment]
Can reproduce on Windows as well. Seems like `streamerModeChanged` isn't invoked after the window is created, causing `Window::updateStreamerModeIcon` to never be called.
Calling `updateStreamerModeIcon` after the button is created works for me.

```diff
diff --git a/src/widgets/Window.cpp b/src/widgets/Window.cpp
index d3687281..f4a99184 100644
--- a/src/widgets/Window.cpp
+++ b/src/widgets/Window.cpp
@@ -194,6 +194,7 @@ void Window::addCustomTitlebarButtons()
             getApp()->windows->showSettingsDialog(
                 this, SettingsDialogPreference::StreamerMode);
         });
+    this->updateStreamerModeIcon();
     this->signalHolder_.managedConnect(getApp()->streamerModeChanged, [this]() {
         this->updateStreamerModeIcon();
     });
```
