### ISSUE TITLE
7tv Transparent Animated Emotes scuffed on Linux - in AppImage

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#4701]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The transparent emotes dont seem to be deleting 'old' frames and overlap instead, and it seems to be happening only to 7tv emotes.

e.g. the cat emote https://7tv.app/emotes/63acb7b5acef59270e7cf4b0

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/1310440/ec9d683e-8ce3-4c8d-b507-dadeaf11a1f7)

### OS and Chatterino Version

Chatterino 2.4.4 (commit 53b044c4) built with Qt 5.12.12 Running on Debian GNU/Linux trixie/sid, kernel: 6.1.0-7-amd64

**Comment by Felanbird** [comment]
are you using the appimage

**Comment by hemirt** [comment]
> are you using the appimage

yes

**Comment by Felanbird** [comment]
> yes 

use the deb

**Comment by hemirt** [comment]
> > yes
> 
> use the deb

that one works, although I had to manully download and install the old package of libboost-filesystem-1.71.0, is there any reason why 1.74 or 1.81 aren't supported

**Comment by pajlada** [comment]
It's built specifically for Ubuntu 20.04, and it's built in a bit of a special way. We're working on PPAs for Ubuntu, and I would be open to have a PPA for debian too if that's not too much extra effort. Your best bet being on Debian might be to just build it from source.

You can explore the source package & launchpad recipe [here](https://launchpad.net/chatterino) if that is useful to build with

**Comment by hemirt** [comment]
> It's built specifically for Ubuntu 20.04, and it's built in a bit of a special way. We're working on PPAs for Ubuntu, and I would be open to have a PPA for debian too if that's not too much extra effort. Your best bet being on Debian might be to just build it from source.
> 
> You can explore the source package & launchpad recipe [here](https://launchpad.net/chatterino) if that is useful to build with

This is meant for the .deb package right? Is there any way to fix the AppImge one, or is it also somehow built for ubuntu?  (I'm not really familiar with AppImages)

**Comment by pajlada** [comment]
the appimage is also built for ubuntu, and I'm not looking to support the appimage very much going forward. There's flatpak you can try too, it will probably work better than the appimage

**Comment by hemirt** [comment]
Okay, I guess I'll keep using the .deb one until it stops working, gotta remember to add the proxy settings into .desktop file (there's imo no need for global environment clutter).

In-app setting of the env-vars would be nice tho.

I'll close the issue then if there's nothing much to add.
