### ISSUE TITLE
Espanso Emote replace dont work

### ISSUE THREAD

**Issue by wuast94** [Chatterino/chatterino2#4709]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Im using espanso for replacing characters with emotes, for example: :D gets replaced with 😂
in chatterino this function is not working

### OS and Chatterino Version

Windows. Chatterino 2.4.4

**Comment by Felanbird** [comment]
Use our native `ignore` feature
![image](https://github.com/Chatterino/chatterino2/assets/41973452/15313d10-da2c-4998-8a7d-ffffe5029005)

**Comment by fourtf** [comment]
> Use our native `ignore` feature ![image](https://user-images.githubusercontent.com/41973452/250145501-15313d10-da2c-4998-8a7d-ffffe5029005.png)

I believe this references the https://espanso.org/ tool which allows you to type shorthand cues which get replaced with a different text. You could make e.g. LGTM become "Looks good to me".

The user seems to be suggesting that this functionality somehow doesn't work with out text input.

**Comment by wuast94** [comment]
> > Use our native `ignore` feature ![image](https://user-images.githubusercontent.com/41973452/250145501-15313d10-da2c-4998-8a7d-ffffe5029005.png)
> 
> I believe this references the [espanso.org](https://espanso.org/) tool which allows you to type shorthand cues which get replaced with a different text. You could make e.g. LGTM become "Looks good to me".
> 
> The user seems to be suggesting that this functionality somehow doesn't work with out text input.

exactly, tried the ignore filter but didnt work.

**Comment by Felanbird** [comment]
> I believe this references the [espanso.org](https://espanso.org/) tool which allows you to type shorthand cues which get replaced with a different text. You could make e.g. LGTM become "Looks good to me".
> 
> The user seems to be suggesting that this functionality somehow doesn't work with our text input.

I wasn't aware we did anything abnormal with the text box. 🤔

**Comment by wuast94** [comment]
something abnormal must be there, anywhere else in apps and systems its working fine (steam is more a day to day thing). 

i disabled the : emote setting too

**Comment by wuast94** [comment]
intresting, on linux (arch) its working just fine, so its a windows special thing?

**Comment by Nerixyz** [comment]
> for example: :D gets replaced with 😂

I tested this on Windows 10 and Qt 6 with:

```yaml
matches:
  - trigger: ':D'
    replace: '😂'
```

This worked fine for me.

**Comment by wuast94** [comment]
Im on Win11 Qt5 

Normally i use this:
  - trigger: ':)'
    replace: "\U0001F60A"

Just for completness i used this now
  - trigger: ':D'
    replace: "😂"
    
all the same problem

**Comment by Nerixyz** [comment]
Can you try it on the Qt 6 build?

**Comment by wuast94** [comment]
Chatterino Nightly 2.4.4 (commit [76527073](https://github.com/Chatterino/chatterino2/commit/76527073)) built on 2023-07-02 with Qt 6.5.0, MSVC 193532217
Running on Windows 11 Version 22H2, kernel: 10.0.22621

its the same issue i have

**Comment by Felanbird** [comment]
Alright so I am able to replicate your issue only when using unicode, but I do have a workaround.

Due to the way we handle unicode, you'll need to replace `:D` with `:joy:` - since that's obviously an inconvenience for the other applications you likely use, I went ahead and read over Espanso's documentation and found the following solution.

You'll want to go ahead and make a `chatterino.yml` file in your config folder, and put the following in it:
```
filter_exec: Chatterino

extra_includes:
  - "../match/_chatterino.yml"
  
extra_excludes:
  - "../match/base.yml"
```
> If your main config is no longer called `base.yml`, replace it with the name of your config in that file.

As well as that, you'll add a file called `_chatterino.yml` to your `match` folder, and put the following in that:

```
matches:
  - trigger: ':D'
    replace: ':joy:'
```

This setup will allow you to have both a working `:D` -> `😂` setup in Chatterino, but without it causing issues in your other programs.

**Comment by wuast94** [comment]
ok feels wired while typing but works 😊 thanks for your workaround 😊
