### ISSUE TITLE
Usercard & emote picker appear on the wrong screen / monitor

### ISSUE THREAD

**Issue by mannin1337** [Chatterino/chatterino2#4733]
### Checklist

- [x] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

**Describe the bug**
Whenever I stream and I try to ban people it always shows up on the main screen and it's not the best to show those words on the screen most of the time. 
The emote picker also happens to do the same thing.
I tried moving it to the chat monitor, but it always opens up on my main monitor for some reason.

**I can reproduce it the other way around**
If I move Chatterino to the side of my main monitor, the pop-up windows will always open up on the screen next to Chatterino.
This is weird because popups will only appear on a wrong screen when Chatterino is close to the side of the screen, on my third screenshot you can see, the pop-up opened on the correct monitor but the window position of Chatterino is off.

### Screenshots

**Video of me reproducing the bug:** https://streamable.com/07w515

I think it has to do something with the length between the names on chat and the side of the screen.
(Because when I clicked on my own name with 5 badges in front of it it appeared on the right screen)

**Screenshots taken after clicking on someones nickname:**  

![DQH5zIMLhl](https://github.com/Chatterino/chatterino2/assets/25119727/e4bf5c5f-7cf4-4313-bdc5-ee23e845d7bb)
![5BTXB8nIe2](https://github.com/Chatterino/chatterino2/assets/25119727/9b4aca5a-22b6-48aa-b5f4-1de2c0979eff)
![uv5hDNoVjU](https://github.com/Chatterino/chatterino2/assets/25119727/8f420f2d-0853-4d6c-8d09-d83a1db7b517)
![XW2gg8Va7D](https://github.com/Chatterino/chatterino2/assets/25119727/b8516182-d6ea-482d-85fa-2cc3da71108b)

### OS and Chatterino Version

Chatterino 2.4.4 (commit 29a14627) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by lathlaszlo** [comment]
yeah, i'm experiencing the same thing.
when the chatterino window is near the edge of my screen, it goes onto my primary one.

pls fix <3

**Comment by pajlada** [comment]
Related to #4572
