### ISSUE TITLE
Username tab autocompletion changes to an emote written after it

### ISSUE THREAD

**Issue by TparT** [Chatterino/chatterino2#4734]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Its related to the tabbing auto completion thing,

steps to reproduce:
1. basically you type a user's uncompleted name and then an uncompleted emote (bttv, faze, 7tv, etc)
2. and then you tab to autocomplete on the uncompleted emote
3. and then after that you tab to autocomplete the user's uncompleted name

expected result: autocompletion of the username and emote name should be seperated and work just autocomplete to what they should be

actual current result: the username just changes to the name of the emote it autocompleted previously on step 2.

Adding a GIF to visualize to the bug.

### Screenshots

Here you can see that im first showing that the user AppleDna is a present chatter,
I then demonstrate how when I type their non full name, followed by the OMEGALUL emote,
when I tried to tab to autocomplete AppleDna's name from just 'apple' it got autocompleted from what it autocompleted previously, by autocompleting from OMEGALUL to OMEGALULiguess (another emote).

And then finally, i delete the autocompleted OMEGALULiguess emote and retry to autocomplete AppleDna's from 'apple', it actually autocompletes correctly this time.

![chatterino tab wrong autocomplete bug](https://github.com/Chatterino/chatterino2/assets/66745515/bda58943-2e1f-435e-a051-daca5b8c86ce)

### OS and Chatterino Version

Chatterino 7.4.4 (commit 90ee0afd) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by TparT** [comment]
It's such a dumb bug honestly lmaooo, IDK how I even found it lol

**Comment by Mm2PL** [comment]
Duplicates https://github.com/Chatterino/chatterino2/issues/3101
