### ISSUE TITLE
There is presently no way of disabling all audio in Chatterino.

### ISSUE THREAD

**Issue by KynikossDragonn** [Chatterino/chatterino2#4768]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When Chatterino is started, it immediately opens up whatever available audio device (in my case PulseAudio over PipeWire) and will continue to have this open despite having every single sound notification turned off.

You can use "Terminate Playback" in `pavucontrol` to kill this audio client connection with no ill-effect on Chatterino even if some sort of notification occurs during usage. This not only does not keep the audio device needlessly open but will also reduce Chatterino's overall CPU usage even further. Having audio open all the time even if one disables all sound events is probably the reason why #4613 is preventing proper system idle.

But, this is not a very ideal thing to just boot Chatterino off of the audio server. It should be possible to just launch Chatterino without any audio support whatsoever.

"miniaudio" has a `ma_backend_null` backend that could be selected if the "Settings" menu allowed selecting any backends manually, but if the end-user does not want any sort of audio handling whatsoever in Chatterino it shouldn't initialize any audio whatsoever in the entire process when launched.

### OS and Chatterino Version

Chatterino 2.4.4 (commit e7281b03) built with Qt 5.15.7 Running on Void Linux, kernel: 6.1.44_1

**Comment by pajlada** [comment]
Having the audio device open as soon as the application is started has seemed like the preference for most users since it allows you to modify its volume & output device without having to do it as a sound effect plays.
I would still like that behaviour to be default, but I could see a few settings change how the sound controller works solve most of these options.

Would these three behaviour types solve all use cases you could think of?
1. Open sound device at startup (Current behaviour, opens the sound device, and doesn't close it)
2. Open & close sound device on-demand (Opens the sound device when a sound effect is played, and close it again after no sound has been played for a while)
3. Disabled (Never open a sound device, skip any incoming requests to play sound notifications)

Not sure what the setting name would be, maybe "Sound playback behaviour"?

**Comment by KynikossDragonn** [comment]
> Having the audio device open as soon as the application is started has seemed like the preference for most users since it allows you to modify its volume & output device without having to do it as a sound effect plays. I would still like that behaviour to be default, but I could see a few settings change how the sound controller works solve most of these options.
> 
> Would these three behaviour types solve all use cases you could think of?
> 
>     1. Open sound device at startup (Current behaviour, opens the sound device, and doesn't close it)
> 
>     2. Open & close sound device on-demand (Opens the sound device when a sound effect is played, and close it again after no sound has been played for a while)
> 
>     3. Disabled (Never open a sound device, skip any incoming requests to play sound notifications)
> 
> 
> Not sure what the setting name would be, maybe "Sound playback behaviour"?

The second behavior type listed is more in line with how most programs I've used behave, especially web browsers. They don't see any sound playback activity after a period of time and will close the related audio clients as a result of idleness.

This is especially true for sound servers on Linux like PulseAudio and PipeWire, if there's no sound playback occurring, then after a few seconds it'll just close the handle on the audio hardware and allow proper system idle without needlessly feeding silence to the sound device in question.

The only issue I can see with the behavior listed in option two, is latency/overhead as a result of having to open the sound handle again once something happens, which is why I can sort of understand why Chatterino presently just starts up with audio constantly being driven to avoid that sort of hiccup.

The third behavior is currently something I'm specifically wishing for since I never really have audible notifications in anything whatsoever in the first place.

**Comment by ashugg** [comment]
Chatterino 2.5.0 introduced the ability to set the "Sound backend" to Null, which closed out #4978. Does it not address this issue too?

**Comment by pajlada** [comment]
@ashugg Yep! It does. Thank you!
