### ISSUE TITLE
7TV TeaTime emote broken on linux (AppImage), rendering all frames of gif layered over one another instead of cycling them

### ISSUE THREAD

**Issue by bjotte** [Chatterino/chatterino2#4777]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

# 7TV TeaTime emote broken on linux (AppImage), rendering all frames of gif layered over one another instead of cycling them

## My setup:
- Running the appimage version of Chatterino 2.4.4
- Multiple PCs with several Linux distros, Mainly Arch based and Fedora.
- DE: KDE plasma.

-----------------------

For several versions of Chatterino on Linux, the 7TV TeaTime emote has been broken, it looks like it is layering all the frames of the GIF on top of each other instead of cycling through them one by one, making it look like a mess. 
Don't know if this issue affects more than this one emote, but it is possible.

This issue has persisted through several system updates and re-installations of Linux on multiple PCs and across distros, tho all with KDE plasma as the DE.

--------
I'm open for questions if needed.
Link to emote: [TeaTime](https://7tv.app/emotes/62e5c88ba1a665fe6efd5aa2)
### Screenshots

![Screenshot_20230820_131241](https://github.com/Chatterino/chatterino2/assets/45982502/45818392-1522-4a19-8ad4-789ceb7aaf40)
![Screenshot_20230820_131228](https://github.com/Chatterino/chatterino2/assets/45982502/3f7eab04-b460-4228-95f7-b3c00b98428a)
![teatimebug](https://github.com/Chatterino/chatterino2/assets/45982502/bfc5e65f-61c9-4a2a-a048-fa6808cd9baf)

### OS and Chatterino Version

Chatterino 2.4.4 (commit 29a14627) built with Qt 5.12.12 Running on EndeavourOS, kernel: 6.4.11-arch1-1

**Comment by Nerixyz** [comment]
This seems to be an issue in Qt 5.12.12 (not on 5.15 or 6.x). See https://github.com/Chatterino/chatterino2/issues/4701.

**Comment by pajlada** [comment]
You're best off using Chatterino from AUR if possible, rather than using the AppImage.
Or, use the flatpak version from flathub: `flatpak install chatterino`
