### ISSUE TITLE
Open the update dialog the same way you open all dialogs

### ISSUE THREAD

**Issue by x9136** [Chatterino/chatterino2#4790]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

If the chat occupies a large part of the screen in height, you have to resize the window to go to the update.

I propose to make the behavior the same as for other dialogs - open in the center of the Chatterino window.

### Screenshots

<img width="617" alt="Screenshot 2023-08-26 at 19 22 56" src="https://github.com/Chatterino/chatterino2/assets/60105060/d020135e-4dc8-412b-95f7-cc7a6f8df8ac">

### OS and Chatterino Version

Chatterino 2.4.4 (Impossible to show the bug after update to 2.4.5) • Running on macOS Ventura (13.5), kernel: 22.6.0

**Comment by x9136** [comment]
A similar problem appeared when trying to open a thread.
<img width="363" alt="Screenshot 2023-08-26 at 19 45 18" src="https://github.com/Chatterino/chatterino2/assets/60105060/3fd3cda8-00f1-4074-b8a9-05b03e76c23c">

**Comment by testicularthunder** [comment]
I have the same problem, with thread, update, and settings windows not respecting screen boundaries and going off-screen.  Somehow, the user card window (clicking on a username) still works ok. Chatterino 2.4.5 on Windows 10, OS Build 19045.3324
