### ISSUE TITLE
Emoji Inconsistancies 

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4792]
When it comes to how emojis are handled on Chatterino, we have no issues displaying the emojis we send and are sent from Twitch, but there are problems on Twitch with the emojis we send.

In certain cases such as 🏴󠁧󠁢󠁳󠁣󠁴󠁿 - this is the fault of Twitch and documented via https://togithub.com/twitchdev/issues/issues/307

In other cases, it falls to https://github.com/iamcal/emoji-data not using `U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}`
###### I'm unsure if this is an error on their end, or just something Twitch expects that this db didn't automatically provide.

Some examples of this are as follows:

| Emoji     | Twitch outcome | Chatterino outcome |
| ------------- |:-------------:| -----:|
| ❤️ | `❤◌️` | `❤` |
| 🛏️ | `🛏◌️`| `🛏`|
| 🗑 | `🗑◌️` | `🗑` |
| ☄️ | `☄◌️` | `☄` |
| 🏖️ | `🏖◌️` | `🏖` |
| 🛩 | | 

<details>
<summary>Raw unicode</summary>

```
❤️
Twitch:
U+2764 : HEAVY BLACK HEART
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}

Chatterino:
U+2764 : HEAVY BLACK HEART
```
```
🛏
Twitch:
U+1F6CF : BED
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}

Chatterino:
U+1F6CF : BED
```
```
🗑️
Twitch:
U+1F5D1 : WASTEBASKET {trashcan}
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}

Chatterino:
U+1F5D1 : WASTEBASKET {trashcan}
```
```
☄️ 
Twitch:
U+2604 : COMET
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}

Chatterino: 
U+2604 : COMET
```
```
🏖️ 
Twitch: 
U+1F3D6 : BEACH WITH UMBRELLA
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}

Chatterino: 
U+1F3D6 : BEACH WITH UMBRELLA
```
```
🛩
Twitch: 
U+1F6E9 : SMALL AIRPLANE
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}

Chatterino: 
U+1F6E9 : SMALL AIRPLANE

```

</details>

Options:

1. Fix and PR to https://github.com/iamcal/emoji-data
2. Fork and modify for our usage where necessary
3. Do nothing and continue to annoy browser chatters

I'm leaning towards option 2 for the following reasons:
- The list of problematic emojis is basically unknown from our PoV, it relies on users reporting the problem. Whether or not this is the correct standard is also unknown, but necessary for the purpose of arguing the change.
- Forking it ourselves seems like less work with the exception of learning _how_ to fix this problem, from what I can gather we'd probably just need to make a file similar to https://github.com/iamcal/emoji-data/blob/master/build/unicode/emoji-zwj-sequences.txt for our applicable situation.
- Doing nothing is a little toxic, I've been gaslighting moonmoon's mods about it but it does seem to be a problem outside of Twitch's normal emoji issues

**Comment by pajlada** [comment]
https://github.com/Chatterino/chatterino2/pull/4840 *should* fix this, but it will require more testing
