### ISSUE TITLE
Newer stable release not available while in beta channel

### ISSUE THREAD

**Issue by 8thony** [Chatterino/chatterino2#4793]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

If the setting <code>Receive beta updates</code> is checked, the new stable version is not available to download due to the update response 

https://notitia.chatterino.com/version/chatterino/win/stable
```json
{
  "download": "https://chatterino.com/download/Chatterino%20Installer.exe",
  "portable_download": "https://chatterino.fra1.digitaloceanspaces.com/bin/2.4.5/Chatterino%20Portable.zip",
  "update": "https://chatterino.com/download/update2.zip",
  "updateexe": "https://chatterino.fra1.digitaloceanspaces.com/bin/2.4.5/Chatterino%20Installer.exe",
  "version": "2.4.5"
}
```

https://notitia.chatterino.com/version/chatterino/win/beta
```json
{
  "portable_download": "https://chatterino.fra1.digitaloceanspaces.com/bin/2.4.4/Chatterino%20Portable.zip",
  "updateexe": "https://chatterino.fra1.digitaloceanspaces.com/bin/2.4.4/Chatterino%20Installer.exe",
  "version": "2.4.4"
}
```

@pajlada There should be a check if the stable channel is higher than the beta channel
Just noticed some links in the stable response are broken or no longer needed.

- [x] Manually have fourtf fix this release
- [ ] Change the related code to check stable -> beta when the beta setting is enabled

### Screenshots

N/A

### OS and Chatterino Version

Chatterino 2.4.4 (commit 29a14627) Windows 10

**Comment by Felanbird** [comment]
he fixed it
