### ISSUE TITLE
AppImage Wayland support on Linux

### ISSUE THREAD

**Issue by Eilyra** [Chatterino/chatterino2#4803]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The AppImage fails to launch under Wayland, with the following error message:

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in "/tmp/.mount_Chatte3dJJEB/usr/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

### OS and Chatterino Version

Chatterino 2.4.5 on openSUSE Tumbleweed

**Comment by Felanbird** [comment]
Use the flatpak

**Comment by Mm2PL** [comment]
If you must use the AppImage, you can try installing xwayland as a workaround.

**Comment by Daniel6372** [comment]
`QT_QPA_PLATFORM=xcb`

**Comment by pajlada** [comment]
The AppImage is on its way out, and won't be particularly supported. Either get Chatterino into tne OpenSUSE package manager (with our help if necessary) or use flatpak.

Feel free to start a Discussion if you're interested in starting the OpenSUSE packaging conversation
