### ISSUE TITLE
User input prevents a Redemption from being searched by it's title

### ISSUE THREAD

**Issue by ScrubN** [Chatterino/chatterino2#4804]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

While watching a livestream, I decided to count the number of times a newly added redeem had been used. Unfortunately, the redeem did not appear when performing either a local or a global channel search, unless a user had typed a used keyword.

- The redeem in question was added within about 20 minutes of me attempting to search for it and allows for a user text input.
- Using both <kbd>F5</kbd> and <kbd>Ctrl</kbd>+<kbd>F5</kbd> to refresh Chatterino did not make a difference.
- Restarting Chatterino also did not make a difference.
- Restarting Chatterino after the stream ended and redeeming did not make a difference.

I was unable to test if the channel going live again made a difference.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/72096833/b53bcde0-f96d-47f9-986b-23b72ba65e48)
![image](https://github.com/Chatterino/chatterino2/assets/72096833/5354ed94-6282-401a-a2a7-6b5ad8843582)
![image](https://github.com/Chatterino/chatterino2/assets/72096833/bbc2b52f-4f33-4ec4-a132-5dadb6f329da)

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) built with Qt 5.15.2, MSVC 193532217 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment]
This is the problem I outlined in this comment while creating a filter. https://github.com/Chatterino/chatterino2/discussions/4587#discussioncomment-5768201
When user-input is available, the title of a redemption is thrown out the window and cannot be searched for.


For your use-case tho you just wanted to search `is:redemption`
