### ISSUE TITLE
User card followers count using the deprecated helix endpoint

### ISSUE THREAD

**Issue by badoge** [Chatterino/chatterino2#4808]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The follower count in the user cards is using the users/follows endpoint which is getting shutdown on Sept 12
It should be using the new channels/followers endpoint
https://dev.twitch.tv/docs/api/reference/#get-channel-followers

### Screenshots

follow count not loading because of the 24-hour shutdown window today 
![image](https://github.com/Chatterino/chatterino2/assets/18620902/e0b72392-6ae4-4ab1-a496-8e0f09d110a7)

### OS and Chatterino Version

Chatterino Nightly 2.4.5 (commit ba440e0c) built on 2023-08-28 with Qt 6.5.0, MSVC 193632538 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by pajlada** [comment]
Thanks for reporting this!
