### ISSUE TITLE
Usercards now longer showing number of followers.

### ISSUE THREAD

**Issue by Zeyyagga** [Chatterino/chatterino2#4810]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

For about 2 weeks now no usercards have been displaying a number for followers.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/46742062/8e07616d-811b-4882-a9e3-4c91e3b04da5)

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) built with Qt 5.15.2, MSVC 193532217 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Wissididom** [comment]
https://github.com/Chatterino/chatterino2/pull/4809
https://github.com/Chatterino/chatterino2/issues/4808

**Comment by Zeyyagga** [comment]
> Fixed in #4809 about an hour ago (You can get the Nightly build to have it fixed) Duplicate Issue of #4808 (It's already closed tho)

Oh thank-q for the reply I'll grab the nightly.

**Comment by Felanbird** [comment]
Fixed in #4809
