### ISSUE TITLE
Emotes and badges unload when hovering over window

### ISSUE THREAD

**Issue by badoge** [Chatterino/chatterino2#4827]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Channel needs to be open for more than 10 minutes and without any new messages according to nerixyz.

Not sure if the window needs to be in or out of focus, the example below happened while it was out of focus.

### Screenshots

https://github.com/Chatterino/chatterino2/assets/18620902/809811a5-b296-409f-8d38-bfd2591302b5

### OS and Chatterino Version

Chatterino Nightly 2.4.5 (commit 89b915ba) built on 2023-09-18 with Qt 6.5.0, MSVC 193532217 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by pajlada** [comment]
I suspect this has been fixed. If you still have this issue, please comment on the issue.

**Comment by Nerixyz** [comment]
This can still happen. The re-layout won't be that visible, but you can see a short flash of images.
