### ISSUE TITLE
Chatterino freezing whenever a sound is played, but only after a fresh boot

### ISSUE THREAD

**Issue by ajojoreference** [Chatterino/chatterino2#4832]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

After a fresh reboot of my laptop, chatterino always freezes whenever a notification/mention/chat highlight with a sound is supposed to play, on both the default sound and any custom sound I add. Waiting never helps and the only way to restart it is to end task via task manager. This also only happens after I log into an account.

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Nerixyz** [comment]
> whenever a notification/mention/chat highlight with a sound is supposed to play, on both the default sound and any custom sound I add

Did you try it with sound for the highlight disabled? Does it not freeze in that case?

**Comment by pajlada** [comment]
Could you clarify what you mean by "but only after a fresh boot"?

**Comment by ajojoreference** [comment]
> Could you clarify what you mean by "but only after a fresh boot"?

It only happens the first time I use chatterino after turning my laptop on, and I've been able to reproduce the freeze by doing a full reboot.

**Comment by pajlada** [comment]
After Chatterino freezes, and you start Chatterino again, do sounds play back as expected?

**Comment by ajojoreference** [comment]
> After Chatterino freezes after that full reboot, and you start Chatterino again, do sounds play back as expected?

Yes, but I'm not 100% sure if it won't freeze again after a few hours

**Comment by pajlada** [comment]
Could you try starting up a browser & start playing a youtube clip with sound before starting chatterino & see if a highlight still freezes?

And what model is your laptop?

**Comment by Nerixyz** [comment]
Could you try getting logs or generate a crashdump?

To get logs, you can use [Nerixyz/c2-logs](https://github.com/nerixyz/c2-logs). Follow the instructions there. We're (mostly) looking for `chatterino.sound` here. You can just paste the logs here (preferably in a [`<details>` block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections)).

To get a crashdump, you can try using [Nerixyz/crashy](https://github.com/Nerixyz/crashy) to crash Chatterino (when the window is frozen, run `.\crashy.exe chatterino.exe`). Chatterino will then generate a crashdump in `%APPDATA%/Chatterino2/Crashes/reports` (see [Crash Analysis](https://wiki.chatterino.com/Crash%20Analysis/) for more background). The crashdumps don't contain the entire memory but only a minimal view (mostly just the stack). If you don't want to upload it here on GitHub, you can alternatively send a crashdump to pajlada on discord (link is on the website) or via mail.

**Comment by ajojoreference** [comment]
I've got the crashdump here [67d89ec5-bb4b-45aa-920f-70494bb4756f.zip](https://github.com/Chatterino/chatterino2/files/12675975/67d89ec5-bb4b-45aa-920f-70494bb4756f.zip)
, but I've got no idea where c2-logs stores chatterino.sound

**Comment by Nerixyz** [comment]
Thank you! The crashdump is probably enough to narrow the problem down:

Main Thread:
```
[0x0]   ntdll!NtWaitForSingleObject+0x14
[0x1]   KERNELBASE!WaitForSingleObjectEx+0x8e
[0x2]   chatterino!ma_event_wait__win32+0xe
[0x3]   chatterino!ma_event_wait+0x13
[0x4]   chatterino!ma_device_start+0xea
```

Some audio thread:
```
[0x0]   ntdll!NtWaitForSingleObject+0x14
[0x1]   KERNELBASE!WaitForSingleObjectEx+0x8e
[0x2]   MMDevApi!AXB::WaitForOperations+0x20e29
[0x3]   MMDevApi!CMediaNotifications::UnregisterMediaCallback+0xf8
[0x4]   MMDevApi!UnregisterMediaCallback+0x30
[0x5]   AUDIOSES!<lambda_d5b3f95b82e2c7512d1b98221445511f>::operator()+0x6b
[0x6]   AUDIOSES!CAudioClient::SetupAudioStreamWithAudioSrv+0x21290
[0x7]   AUDIOSES!CAudioClient::InitializeInternalHelper+0x105
[0x8]   AUDIOSES!CAudioClient::InitializeInternal+0x8a
[0x9]   AUDIOSES!CAudioClient::InitializeSharedAudioStream+0xf8
[0xa]   AUDIOSES!CAudioClient::InitializeSharedAudioStream+0x24
[0xb]   chatterino!ma_IAudioClient3_InitializeSharedAudioStream+0x27
[0xc]   chatterino!ma_device_init_internal__wasapi+0x9e5
```

There are a few other threads running miniaudio and/or audio related code. Maybe it's a deadlock in miniaudio?

> but I've got no idea where c2-logs stores chatterino.sound

All the logs should be written to the console, you can redirect the execution into a file, like `.\c2-logs.exe > logs.txt`.

**Comment by pajlada** [comment]
@ajojoreference Could you download the windows build from here: https://github.com/Chatterino/chatterino2/actions/runs/6283029704?pr=4836 and reproduce the issue, give us the crashdump, and the logs?
We've added some more logs that will come in handy for the debugging

**Comment by ajojoreference** [comment]
I've been testing it for a while and the freeze has gotten rare. I've only had it happen two times, and both were before I hooked c2-logs up to chatterino.exe. Only thing I could think that maybe effected it was that I changed some services in windows from automatic startup to manual, but I switched them back and it doesnt seem to have done anything. I'll keep trying though.

**Comment by ajojoreference** [comment]
I finally got a freeze to happen with c2-logs open, but for some reason crashy didn't generate a crash dump file, at least in the location it usually does.
[C2-logs.txt](https://github.com/Chatterino/chatterino2/files/12732806/C2-logs.txt)

**Comment by ajojoreference** [comment]
Got another freeze happened with the same sound device restart line in the log, but I was able to get a crash dump this time. It seems like I didn't get one last time because c2-logs was open, while I closed it down before using crashy this time.

[1906823c-24b2-4be4-88df-3c26b9c0df53.zip](https://github.com/Chatterino/chatterino2/files/12744500/1906823c-24b2-4be4-88df-3c26b9c0df53.zip)

**Comment by pajlada** [comment]
We did a decent amount of changes to our sound backend, hopefully this should have been resolved.
If that's not the case, feel free to re-open this issue.
