### ISSUE TITLE
Capitalizing channel names breaks the logger

### ISSUE THREAD

**Issue by ScrubN** [Chatterino/chatterino2#4835]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Spelling channels in the log inclusion list with any form of capitalization causes them to not be logged at all.

When "Only log channels listed below" is disabled all channels, even those with capitalization in the tab names, are logged as expected.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/72096833/563a559d-d3f2-4b00-811d-b5ba17ce08dd)

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) built with Qt 5.15.2, MSVC 193532217 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment]
> When "Only log channels listed below" is disabled all channels, even those with capitalization in the tab names, are logged as expected.

That's because the tab name is not relevant, `xQc` is not his username `xqc` is, but the input should be interpreted as lowercase either way.

**Comment by ScrubN** [comment]
> That's because the tab name is not relevant, `xQc` is not his username `xqc` is

I figured as such, though I am not very familiar with the Chatterino codebase so I figured it was still worth mentioning.
