### ISSUE TITLE
Recent nightly changes message layout padding

### ISSUE THREAD

**Issue by RandomGOTI** [Chatterino/chatterino2#4838]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The previous nightly had the message layout more compact and cleaner apperance , same config file without any changes between versions
For example a screenshot of live tab : 
Chatterino Nightly 2.4.5 (commit [89b915ba](https://github.com/Chatterino/chatterino2/commit/89b915ba)) built on 2023-09-18 with Qt 5.15.2, MSVC 193532217
Running on Windows 7 Version 6.1 (Build 7601: SP 1), kernel: 6.1.7601
![1](https://github.com/Chatterino/chatterino2/assets/19516333/f94084dd-3d75-4cc5-a8a7-27ed5fc60bb0)
^ would fit 4 more lines compared to current

Chatterino Nightly 2.4.5 (commit [6860c700](https://github.com/Chatterino/chatterino2/commit/6860c700)) built on 2023-09-23 with Qt 5.15.2, MSVC 193532217
Running on Windows 7 Version 6.1 (Build 7601: SP 1), kernel: 6.1.7601
![2](https://github.com/Chatterino/chatterino2/assets/19516333/2c05f0d0-dfa3-4d00-99d9-edabf1b851de)

### OS and Chatterino Version

Chatterino Nightly 2.4.5 (commit 6860c700) built on 2023-09-23 with Qt 5.15.2, MSVC 193532217 Running on Windows 7 Version 6.1 (Build 7601: SP 1), kernel: 6.1.7601

**Comment by pajlada** [comment]
thanks for the keen :eye: and quick report! Will be fixed by https://github.com/Chatterino/chatterino2/pull/4839
