### ISSUE TITLE
Command tab completion no longer works when a command does not start with `/`

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#4842]
Steps to replicate:

1. Make a command 
2. Set the trigger to anything that doesn't start with `/` ( e.g `command` )
3. Attempt to use tab-completion to complete the command
4. guh
5. Notice that once failing to tab complete the command, tab completion _with_ a `/` works, despite the command not having a `/` 

almost certainly caused by #4639

originally reported in discord: https://discord.com/channels/253897423439659008/459650160658481152/1156813105528061992

**Comment by Mm2PL** [comment]
https://github.com/Chatterino/chatterino2/pull/4639/files#diff-a1f6c3a68ede506e1729224bde149ba0014e9cf11d55315eecb63a3119bcc5aaR75-R78

**Comment by Felanbird** [comment]
Unlucky but we definitely can't do that, since we have both #3583 and #4233 - both of which use commands as their workaround.

**Comment by Mm2PL** [comment]
Yeah, tab completion needs to go back to querying everything or most things for this to work.

**Comment by dnsge** [comment]
If I'm understanding the original behavior, it should be trivial to fix:

https://github.com/Chatterino/chatterino2/blob/783c7530f3aedcdf493e508549b4082b13610cf9/src/controllers/completion/sources/UnifiedSource.cpp#L18-L19

can be updated to also use the command source.

I'll do some tinkering to see if this restores the original behavior.
