### ISSUE TITLE
Replace twitch emotes with dark borders with dark mode ones

### ISSUE THREAD

**Issue by TranRed** [Chatterino/chatterino2#485]
Replace scuffed emotes with white outlines with the ones used in chatterino 1. (couldn't find existing issues with search terms: "darkmode" or "emote")

![grafik](https://user-images.githubusercontent.com/16636423/41773622-f26fec20-761c-11e8-8e0d-37f2ec29aa24.png)

**Comment by fourtf** [comment]
This is the worst issue title that I have seen (probably in my entire life).

**Comment by gempir** [comment]
I think what TranRed want here is the FFZ Feature of improved Global Emotes. 

![image](https://user-images.githubusercontent.com/9765622/80921830-0739a900-8d79-11ea-8fd2-ff758ad19dd4.png)

And I agree that they are nicer

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
