### ISSUE TITLE
Scaling broken for message and emote context menus in 2.4.6

### ISSUE THREAD

**Issue by ccerbusca** [Chatterino/chatterino2#4862]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I am using Chatterino on a display with 125% scaling. As of 2.4.6 the scaling for context menus for messages and emotes is broken. See screenshots for examples. Changing scaling to 100% fixes it, but it is not ideal.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/23035489/ab655862-ef68-4585-8c7d-ea506417a7b3)

![image](https://github.com/Chatterino/chatterino2/assets/23035489/828d390e-a26a-484c-9f78-456eeb281fdd)

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2d) built with Qt 6.5.0, MSVC 193532217 Running on Windows 11 Version 22H2, kernel: 10.0.22621

**Comment by Nerixyz** [comment]
I have a slight feeling Qt was right with _This variable is intended for testing purposes only, and we do not recommend setting it on a permanent basis_. On the upside, I wasn't able to reproduce https://github.com/Chatterino/chatterino2/issues/4552, but I don't really know why. There are still some bugs with High-DPI scaling, though. Mainly, calling [`QWidget::mapToGlobal`](https://doc.qt.io/qt-6/qwidget.html#mapToGlobal) in a `BaseWindow` seems to return wrong results (in a regular window, this works fine).
