### ISSUE TITLE
Antivirus false positive megathread

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#487]
If your antivirus software sees the Chatterino2 beta as a virus, please post it as a comment below with the following information:

> 
> Operating system: Windows 10 Home 64-bit
> Antivirus software: Norton Antivirus 2016
> Chatterino version: 2.0.0

During the beta we will not take action, but commenting below will help us know which vendors to contact once we're getting ready for release.
Until then, you can add Chatterino2 to your anti virus' exception/whitelist

**Comment by fourtf** [comment]
Antivirus software: 360 total security
Chatterino version: 2.0.4

![monkas](https://user-images.githubusercontent.com/6320036/42656429-8f777300-861f-11e8-8c8e-219031a86d10.png)

**Comment by alazymeme** [comment]
Is this still applicable? Isn't the exe signed now?

**Comment by dnsge** [comment]
The application still isn't signed on macOS

**Comment by alazymeme** [comment]
> The application still isn't signed on macOS

So are there any false positives on macos?

**Comment by dnsge** [comment]
Not that I'm aware of, but when opening the program for the first time macOS warns you that the program may be malicious.

**Comment by apa420** [comment]
Isn't that the case for any 3rd party program that's not from the app store? That's what I remember from using mac 6 years ago. Correct me if I'm wrong. Even installing steam and such will give those warnings afaik.

**Comment by dnsge** [comment]
If the application is signed with a [Developer ID](https://developer.apple.com/developer-id/), then the application can be opened with two clicks. For unsigned applications, users have to right-click on the application and then shift-click on open.

Chatterino: https://i.nuuls.com/EVwgv.mp4
Steam: https://i.nuuls.com/giZ-m.mp4

I guess the question is whether it's worth the $100 a year for signing. Probably not because no one seems to be having issues.

**Comment by alazymeme** [comment]
The Devs already support the servers for this. I don't think it's justifiable just to confirm to apple's restricted ecosystem (considering that nobody has complained).

In saying that, this issue can probably be closed.

**Comment by fourtf** [comment]
Only way to fix this is to sign the application, I tried some time ago but didn;t gheoijppafsjdijasop;fhadsf

**Comment by FOSS-Archives** [comment]
<img width="1833" height="738" alt="Image" src="https://github.com/user-attachments/assets/24466681-eb45-44f0-9352-dff777954b59" /> Just incase its relevant
