### ISSUE TITLE
Replying to a message with an emoji followed by any text, without any spaces, will cause the text following the emoji to be eaten in the reply

### ISSUE THREAD

**Issue by brian6932** [Chatterino/chatterino2#4874]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

```
▪pajaDank
▪ pajaDank test with a space
pajaDank test with no emoji
```

### Screenshots

![](https://github.com/Chatterino/chatterino2/assets/18603393/7cfa67b8-8731-4a73-9aae-2eda32c64125)

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit 75282579) built on 2023-10-06 with Qt 6.5.0, MSVC 193532217 Running on Windows 10 Version 21H2, kernel: 10.0.19044

**Comment by Felanbird** [comment]
Issue seems to be because of how emojiAnyText touching eachother is handled, 
![image](https://github.com/Chatterino/chatterino2/assets/41973452/c669f374-7961-4008-90eb-9564c5cc2f4d)
![image](https://github.com/Chatterino/chatterino2/assets/41973452/fa717c5f-6cb1-4169-bd25-2df989ae3f01)
