### ISSUE TITLE
Runtimes for Chatterino Flatpak are marked as EOL

### ISSUE THREAD

**Issue by 3ship** [Chatterino/chatterino2#4888]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Running Flatpak updates shows the following error message:

```
Info: runtime org.kde.Platform branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.chatterino.chatterino, com.chatterino.chatterino

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.chatterino.chatterino, com.chatterino.chatterino
```

This is with both stable and nightly installed.

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2 modified) built with Qt 5.15.8 Running on KDE Flatpak runtime, kernel: 6.5.6-arch2-1, running from Flatpak

**Comment by pajlada** [comment]
CC @ilya-zlobintsev - I think just updating to Qt6 should be good

**Comment by 3ship** [comment]
Was fixed in https://github.com/flathub/com.chatterino.chatterino/pull/245
