### ISSUE TITLE
Some channels dont have third party emotes.

### ISSUE THREAD

**Issue by MicroWazzle** [Chatterino/chatterino2#4901]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino doesnt show that some channels have third party emotes. Even when typed out no emotes show.

### OS and Chatterino Version

Chatterino 2.4.6 - Windows 11 pro version 10.0.22621 Build 22621

**Comment by Felanbird** [comment]
![image](https://github.com/Chatterino/chatterino2/assets/41973452/e4291946-a716-4154-9179-35db1907e930)

I have no idea if you mean 7TV emotes, since you did not include any screenshots or any info about what 3rd party emotes are missing, but since I saw these messages about 30 seconds before your issue was opened, I'm going to assume it's this.

**Comment by MicroWazzle** [comment]
> ![image](https://user-images.githubusercontent.com/41973452/275282817-e4291946-a716-4154-9179-35db1907e930.png)
> 
> I have no idea if you mean 7TV emotes, since you did not include any screenshots or any info about what 3rd party emotes are missing, but since I saw these messages about 30 seconds before your issue was opened, I'm going to assume it's this.

Its ALL 3rd party emotes including BTTV, FFZ, and 7tv yes i cant screenshot as there is nothing to screenshot if there is no emotes but here's one when I press F5 in my own channel which has 7tv emotes and bttv emotes.
[https://kappa.lol/0z4Jl](url)

**Comment by MicroWazzle** [comment]
OK it seems to be fixed now for some reason maybe 7tv api was having issues?
