### ISSUE TITLE
Emojis not Loading

### ISSUE THREAD

**Issue by lucas19961** [Chatterino/chatterino2#4907]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

In the Emotes Menu The Emojis wont load and i dont see them in the Chat. I tried all 4 Emoji Styles and reinstalling/ cache clear wont help.

### Screenshots

![276725283-92513c78-7711-4aff-a695-525224d5b531](https://github.com/Chatterino/chatterino2/assets/17136546/377a9ee8-0815-4faf-a1f1-4261d586a4c0)
![276725379-cad12ea8-97d9-498c-9ed6-783c5930dd91](https://github.com/Chatterino/chatterino2/assets/17136546/3bf2f7bc-f398-453e-a320-908fa757a475)
![276725332-1a5f4414-40b7-40d2-8791-24da2f10e0b9](https://github.com/Chatterino/chatterino2/assets/17136546/f65010f7-674c-4c60-94af-7338ef96fd98)

### OS and Chatterino Version

Chatterino Nightly 7.4.6 (commit c7a11ebc) built on 2023-10-16 with Qt 6.5.0, MSVC 193532217 Running on Windows 11 Version 22H2, kernel: 10.0.22621

**Comment by Felanbird** [comment]
ye the server is dying/died

**Comment by Nerixyz** [comment]
As a sidenote: https://github.com/Chatterino/chatterino2/blob/12808d3154349f6e3eed3ce3f8ebacfe02c1fc2e/src/common/NetworkPrivate.cpp#L202-L220 should log the error instead of `0` (see https://github.com/Chatterino/chatterino2/pull/4704).

**Comment by CaptainFlint** [comment]
For me it did report a code. 523 it was, I think.

**Comment by francorz** [comment]
also happen to me, weird thing is that some people that i talk about this, they can see emojis, but don't work for me

**Comment by pajlada** [comment]
Should work after your next Chatterino reboot now. Thanks for the report!
