### ISSUE TITLE
Windows SmartScreen alert

### ISSUE THREAD

**Issue by Snipy2k4** [Chatterino/chatterino2#4908]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hello,

I downloaded Chatterino today from the homepage (chatterino.com) and here from github. For both installers, Windows SmartScreen prevents the installation or warns about it?!

Is there an error here or can I ignore it?

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2) installer - Windows 10 22H2

**Comment by Felanbird** [comment]
It started happening after we built the installer exe's via [github actions](https://github.com/Chatterino/chatterino2/blob/master/.github/workflows/create-installer.yml) (version 2.4.5 onwards) - we would need someone to go through and debug the building to find what's causing the FP, it also doesn't happen to everyone.

Here's the virustotal for 2.4.5 https://www.virustotal.com/gui/file/60fbcd77d637b529e0a056e7c743c819e1bdb5ab376c0da27b6df3f167ca8767
You can go ahead and upload the 2.4.6 exe as well if you're still worried.

**Comment by 8thony** [comment]
It's about a blue SmartScreen warning, right?
https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/
> Checking downloaded files against a list of files that are well known and downloaded frequently. If the file isn't on that list, Microsoft Defender SmartScreen shows a warning, advising caution.

Running the 2.4.4 installer will automatically unblock it, but running the 2.4.6 installer will show the SmartScreen warning.

If you disconnect your network and than run the 2.4.4 Installer a SmartScreen warning will appear saying: 
> "SmartScreen can't be reached right now"

Note: already unblocked installer won't show a SmartScreen warning

Unblock  a file manually: https://www.tenforums.com/tutorials/5357-unblock-file-windows-10-a.html

Additional Information:
https://security.stackexchange.com/a/139520
https://security.stackexchange.com/a/242626

**Comment by kornes** [comment]
Smartscreen is based on reputation of binary, if enough people runs it it will go away, but nothing we can change in code to make it faster. After installer changed recently, likely we are gaining reputation from 0 because change was big enough.

The only shortcut would be signing all binaries we ship (~$200/y iirc), then smartscreen will use cert for reputation. This should make warning go away slightly faster and hopefully never come back.

**Comment by Felanbird** [comment]
kornes explained this problem well, the issue should eventually resolve itself and we already need to pay Apple to fix their version of this that never-goes-away-until-you-pay, so I'll close this and mention it in the FAQ issue.

**Comment by Nerixyz** [comment]
I'll link https://github.com/ImageMagick/ImageMagick/discussions/6826 for reference, as they're discussing code-signing as well.
