### ISSUE TITLE
BTTV live emote updates

### ISSUE THREAD

**Issue by francorz** [Chatterino/chatterino2#4916]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

BTTV live emote updates don't work for me. Using a bot that adds and removes emotes i can show how I remove the emote "catRave" and I still can see it, when I go to [BTTV page](https://betterttv.com/) I confirm that the emote is not in my channel anymore. But works if I do F5.

![image](https://github.com/Chatterino/chatterino2/assets/83022459/bbf264bf-f380-4964-b7df-bec58a737814)

btw, on settings it's activated:
![image](https://github.com/Chatterino/chatterino2/assets/83022459/9448576c-b3a7-4059-998a-fae8eaa7855f)

I already tried to restart chatterino, clear cache and also restart my pc, none of these options worked.

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit da31e47f) built on 2023-10-23 with Qt 6.5.0, MSVC 193532217 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by pajlada** [comment]
Works as expected for me when manually adding or removing emotes from my emote set
![image](https://github.com/Chatterino/chatterino2/assets/962989/2887b2b8-7e66-44a9-956a-3e5450767baa)

Works in user's chat for me on Chatterino that has been open for a while & Chatterino that was just opened
![image](https://github.com/Chatterino/chatterino2/assets/962989/1cad11d0-86af-4d08-9ed2-9e7012775d93)

**Comment by Felanbird** [comment]
This is the fault of BTTV, when there's too many active websockets, cloudflare will block _all_ requests for new ones, meaning there are time periods where the feature appears as if it just doesn't work.

There's nothing we can about this.
