### ISSUE TITLE
Weird bug with gif emote

### ISSUE THREAD

**Issue by DatGuy1** [Chatterino/chatterino2#492]
See https://youtu.be/6r5Z9Z7sLYM. Left chatterino2 on the right chatterino 1. Seems like the frames freeze or something (emote is https://manage.betterttv.net/emotes/5accc4b5c21edd1f504a70f1#)

![direct link to emote](https://cdn.betterttv.net/emote/5accc4b5c21edd1f504a70f1/3x)

**Comment by notheowner** [comment]
I can confirm this one, on that specific emote, haven't seen it happen on something else though

**Comment by LajamerrMittesdine** [comment]
This also happens with WanWan emote https://manage.betterttv.net/emotes/566462e07fc3c70d30096e2d

So it's not an isolated case.

**Comment by pajlada** [comment]
Seems to be fixed. Please re-open if this still occurs.
