### ISSUE TITLE
Chatterino emotes and chat history not working after install

### ISSUE THREAD

**Issue by kidcore3** [Chatterino/chatterino2#4941]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I reset my computer and i reinstalled chatterino but emotes and chat history won't load. no matter how many times i open and close chatterino or restart my stystem i get these two error messages 

1. Failed to fetch FrankerFaceZ channel emotes. (Error: SslHandshakeFailedError) 
2. Message history service unavailable (Error: SslHandshakeFailedError) 

please help
![Screenshot_10400000](https://github.com/Chatterino/chatterino2/assets/149905877/60f9b557-3100-4cf9-8148-cc2a01bfc893)

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2d) built with Qt 6.5.0, MSVC 193532217 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by Wissididom** [comment]
Can you try opening https://valid-isrgrootx1.letsencrypt.org/ and https://valid-isrgrootx2.letsencrypt.org/ in your browser (preferably Edge, it's what I've tested), then restarting Chatterino?
(Source: pajlada in Discord at 29/07/2023)

**Comment by kidcore3** [comment]
That doesn't really make sense but I did what you told me to do anyway. I opened those two web pages and restarted chatterino and....nothing
![Screenshot_364](https://github.com/Chatterino/chatterino2/assets/149905877/fc300b2e-c865-4e94-ba98-2be0155cb959)

**Comment by Felanbird** [comment]
You can probably just skip to the last part, you probably have the same issue.

![image](https://github.com/Chatterino/chatterino2/assets/41973452/5ef182fc-628c-420a-962b-b510130cca98)

https://letsencrypt.org/certs/isrgrootx1.der

**Comment by kidcore3** [comment]
Oh my god it works! You all are breath-taking! thank you!
