### ISSUE TITLE
Issue connecting to chat

### ISSUE THREAD

**Issue by anoversizedbathroomrug** [Chatterino/chatterino2#4976]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When I try connecting to the chat I wish to have open on Chatterino, I get told that I am being repeatedly disconnected (without pressing anything, too). I have tried reinstalling, updating, and restarting my computer. I've checked both the Chattering and Mac settings and everything seems to be fine. (I know it says 2.4.5, but the newest version--2.4.6--says Windows only, and this is a Mac). The only similar issue I've seen is one saying this is due to having too many tabs/channels open, but this is only 1 of 2 I have open.

### Screenshots

<img width="703" alt="Screenshot 2023-11-25 at 3 59 47 PM" src="https://github.com/Chatterino/chatterino2/assets/152034300/6d77c779-5193-41bb-94bf-241f523dc0f5">

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) built with Qt 6.5.0 Running on macOS 14.1, kernel: 23.1.0

**Comment by Felanbird** [comment]
You get the `disconnected` message when you are disconnected, you also got an error from 7TV which does not make sense to receive on 2.4.5, so it's my strong belief you're having an internet issue.
