### ISSUE TITLE
Ctrl+Backspace not working properly in Emote Search and Settings after Select All

### ISSUE THREAD

**Issue by 21mtd** [Chatterino/chatterino2#5004]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

This problem happened and fixed in the past (#4461) but still occurred in Emote Menu and Settings. The last keyword remain undeleted after Select All then Ctrl + Backspace.

***Reproduction steps:***

- Open a Emote Menu or Settings
- Type random letters in input box
- Ctrl+A to select all then Ctrl+Backspace

### Screenshots

https://github.com/Chatterino/chatterino2/assets/75530836/1e2c1f50-2073-4f18-b98c-35ffb12b351c

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit c3d3903b) built on 2023-12-05 with Qt 6.5.0, MSVC 193732826 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by Mm2PL** [comment]
Can confirm. Similar to #4461. Probably will need a patch similar to #4536.

**Comment by Mm2PL** [comment]
This was fixed in #5013.
