### ISSUE TITLE
Cannot drag the main Chatterino window

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#5006]
1. Open Chatterino
2. Don't move the window for 4 days, use your computer as normal
3. Attempt to move the window, see it not work

TODO: figure out actual steps to reproduce why this happened
![firefox_2023-12-07_10-46-42](https://github.com/Chatterino/chatterino2/assets/41973452/18b1fbb8-2c62-4054-aa6e-d52923e60a3a)

It never possible to drag the window from the buttons, but showing icons that actually change when interacted with helps to display the issue not being hardware. The moveable window was generated with `ctrl+N`.

Very clearly caused by https://github.com/Chatterino/chatterino2/pull/4994 whatever the problem is

As a note: I now notice that when attempting to use ShareX to screenshot the window, previously the entire window would be the only option to quick-screenshot, now every single section of the window is available, preventing a full-app screenshot from being possible. 
(when Chatterino does not have the tabs hidden, each individual split is also an option now)

https://github.com/Chatterino/chatterino2/assets/41973452/5d8572eb-424c-417b-a0b5-e7b24f1b1d9c
```
Chatterino Nightly 2.4.6 commit 44abe6b4 built on 2023-12-03 with Qt 6.5.0, MSVC 193732826
Running on Windows 10 Version 22H2, kernel: 10.0.19045
```

**Comment by Nerixyz** [comment]
A log of the Window messages would be helpful, in particular the messages that the PR handles (the non-client events). You can use Spy++ for this (`<VS-Installation>\Common7\Tools\spyxx_amd64.exe`), make sure you check `Parent Windows`.

**Comment by Felanbird** [comment]
I was going to close this a few weeks ago but as I was typing the comment I decided to actually check my window and it was in fact stuck. Currently I don't have the issue but I'll probably leave this open just because (idk when I last opened Chatterino)

As a note for the future, while Spy++-ing this issue, I was getting `HTCLIENT` instead of `HTCAPTION` when attempting to move the client, opening a ctrl+N popup correctly gave `HTCAPTION`'s and was movable

**Comment by Felanbird** [comment]
this hasn't happened since, I honestly do think it was related to some other app I had opened in this time-frame, 🤷
