### ISSUE TITLE
Test historic messages on computer sleep with latest nightly

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#5009]
Some changes we've made might lead to very few messages being loaded when waking the computer from sleep.

**Comment by dnsge** [comment]
Just woke my computer from sleep after a couple of hours. No reloading of recent messages occurred as far as I can tell:

![image](https://github.com/Chatterino/chatterino2/assets/24928223/39caf534-b099-4470-9f6e-979f5364d03b)

1st reconnect is from waking the computer, 2nd reconnect is from me manually reconnecting. Neither triggered the recent messages API.

Build info:
```
Chatterino Nightly 2.4.6 (commit [c3d3903b](https://github.com/Chatterino/chatterino2/commit/c3d3903b)) built on 2023-12-05 with Qt 6.5.0, MSVC 193732826
Running on Windows 10 Version 22H2, kernel: 10.0.19045
```

**Comment by iProdigy** [comment]
Thanks for the confirmation @dnsge

I'm working on a patch that solves this by tracking the last known timestamp the chat socket was definitely connected (unless we have a better way to detect wake from sleep)

**Comment by Nerixyz** [comment]
On Windows, there's [`WM_POWERBROADCAST`](https://learn.microsoft.com/windows/win32/power/wm-powerbroadcast).

**Comment by RAnders00** [comment]
> ~Thanks for the confirmation @dnsge~ nvm, you're on an older commit
> 
> I'm working on a patch that solves this by tracking the last known timestamp the chat socket was definitely connected (unless we have a better way to detect wake from sleep)

You can use the time that the last message was received from the Twitch server, and then directly use that timestamp as `?after`. I intentionally made `?after` do a Strictly-Greater-Than check, for exactly this use case
