### ISSUE TITLE
Moving over different windows' popups automatically switches focus

### ISSUE THREAD

**Issue by Supinic** [Chatterino/chatterino2#5019]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

**Describe the bug**
When multiple Chatterino windows are opened and overlaid on top of each other, moving the cursor over another one's popups (hovers) will automatically move the focus over to the other window.

**To reproduce**
- Open two windows of Chatterino 
- Overlay them on top of each other partially
- Mouse over different popups (e.g. stream title, link preview, emote detail, badge detail, etc.)
- Observe windows switching focus
- Likely only observable on Windows

### Screenshots

**Video preview**
- In this video preview, I do not press any keys or any mouse buttons

https://github.com/Chatterino/chatterino2/assets/7684273/c7934cb3-607b-4e17-88ef-25888b31e47e

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit fd4cac2c) built on 2023-12-10 with Qt 6.5.0, MSVC 193732826 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by pajlada** [comment]
Can't reproduce on Linux with X11 or Wayland - macOS TBD

**Comment by Nerixyz** [comment]
https://github.com/Chatterino/chatterino2/pull/4998 introduced this by setting a parent on the tooltip:

> If _parent_ is `nullptr`, the new widget becomes a window. If _parent_ is another widget, this widget becomes a child window inside _parent_. 
[docs](https://doc.qt.io/qt-6/qwidget.html#QWidget)

The PR fixing this should remember to delete the window if no parent is set ([`deleteLater`](https://doc.qt.io/qt-6/qobject.html#deleteLater)).

**Comment by pajlada** [comment]
I suspect we'll need to do platform specific code here and leave the tooltip parentless on Windows, while leaving macOS & Linux the same.
Would be good to test the bug on Linux with a non-tiling window manager too

**Comment by Nerixyz** [comment]
My guess is that the bug is some result of bad window flags, and we're patching around that.
