### ISSUE TITLE
Usercard regressions

### ISSUE THREAD

**Issue by brian6932** [Chatterino/chatterino2#5050]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

aa11a241639094818f43898c9ad8910e689c1d8b makes dragging the usercard laggy (a bit hard to display, my monitor's 165Hz and the recording's only set to 60fps, may not look like it, but IRL it's very noticeable, can try recording at a higher framerate if necessary), and no longer responds to the context of the display's bounds.

### Screenshots

Left is before the commit, right is after (The recording was done at the top of my monitor/display)
![](https://github.com/Chatterino/chatterino2/assets/18603393/177b19f1-b641-46d6-b63e-3160bb1c91fc)
Using a wm that doesn't respect the Qt limitations, like AltSnap, doesn't exhibit the lag, feels about the same as the left side/before the commit.

### OS and Chatterino Version

built on 2023-12-28 with Qt 6.6.0, MSVC 193833133 Running on Windows 10 Version 21H2, kernel: 10.0.19044

**Comment by pajlada** [comment]
What commit are you on now? The relevant changes have been reverted for Windows with https://github.com/Chatterino/chatterino2/pull/5040 & https://github.com/Chatterino/chatterino2/commit/485fc5cdb4c474274ea0fcb6184d38a092628539

**Comment by brian6932** [comment]
Well what I'm currently using is 04a46f60dc26bc0ef56a2318624fae754cff4765 with aa11a241639094818f43898c9ad8910e689c1d8b reverted.
Left on the recording is one commit before aa11a241639094818f43898c9ad8910e689c1d8b and right is exactly on it.

**Comment by pajlada** [comment]
The change is: User cards now have a Split as their parent, instead of the main window. This was done so that the User card would automatically close when the split is closed (which is expected behaviour)

**Comment by brian6932** [comment]
Setting https://github.com/Chatterino/chatterino2/blob/04a46f60dc26bc0ef56a2318624fae754cff4765/src/widgets/DraggablePopup.cpp#L78 to 0 seems to remove the lag
But doesn't fix the issue with the usercard going out of display/monitor bounds

**Comment by Nerixyz** [comment]
I'm not sure why this timer exists in the first place (would be cool if there were some comments 🙃). But the timer wasn't assed in the mentioned commit. Did this issue exist before too?

Linking https://github.com/Chatterino/chatterino2/issues/5019 as this sounds similar (parenting popup to widget inside another window).

**Comment by pajlada** [comment]
Please confirm that this is fixed in the latest commit @brian6932

**Comment by brian6932** [comment]
Looks fixed 👍
