### ISSUE TITLE
`Send IRC Commands on Connect` not working

### ISSUE THREAD

**Issue by 2547techno** [Chatterino/chatterino2#5065]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Specified commands are not sent to server upon connection.

This is the NodeJS script I used to host a tcp server to see what is being sent from chatterino:

```js

const net = require("net")
const PORT = 1234

const server = net.createServer((socket) => {
	console.log(`[${socket.remoteAddress}] connected`)

	socket.on("data", (data) => {
		console.log(`[${socket.remoteAddress}] ${data.toString()}`)
	})

	socket.on("end", () => {
		console.log(`[${socket.remoteAddress}] disconnected`)
	})
})

server.listen(PORT, () => {
	console.log(`Listening on ${PORT}`)
})
```

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/109011672/1e51d6d3-a33a-4d2d-b0fd-cec8d528bf8a)

![image](https://github.com/Chatterino/chatterino2/assets/109011672/53ac8a3d-6a60-44e4-a1bc-317305929cd7)

### OS and Chatterino Version

Chatterino 2.4.6 DEBUG (commit 77eb9cc1) built with Qt 5.15.3 Running on Ubuntu 22.04.3 LTS, kernel: 5.15.133.1-microsoft-standard-WSL2

**Comment by Felanbird** [comment]
can replicate, must have broke at some point

**Comment by 2547techno** [comment]
If it helps, this method doesn't seem to ever be called:
https://github.com/Chatterino/chatterino2/blob/77eb9cc1e9835af9bfd7fb2eee7b40538fa68077/src/providers/irc/IrcServer.cpp#L181-L193

**Comment by 2547techno** [comment]
Seems I was wrong. I was reading the libcommuni docs to see when the `connected()` signal is triggered and it seems that it's when a [`RPL_WELCOME`](https://datatracker.ietf.org/doc/html/rfc2812#section-5.1) IRC message is received. I changed the script to send that on connect and the signal now triggers and the specified commands are sent. I also tried connecting to a public IRC server and it also works correctly.

@Felanbird I'm guessing you used my script to replicate? If so, I can close this issue.

**Comment by Felanbird** [comment]
> Seems I was wrong. I was reading the libcommuni docs to see when the `connected()` signal is triggered and it seems that it's when a [`RPL_WELCOME`](https://datatracker.ietf.org/doc/html/rfc2812#section-5.1) IRC message is received. I changed the script to send that on connect and the signal now triggers and the specified commands are sent. I also tried connecting to a public IRC server and it also works correctly.
> 
> @Felanbird I'm guessing you used my script to replicate? If so, I can close this issue.

I did not, I used the `/history` command in a server I'm in, and it did not render history on connect. Manually sending the command afterwards rendered history
