### ISSUE TITLE
Setting path to streamlink's executable AppImage only works without filename extension

### ISSUE THREAD

**Issue by SchimmelGelenk** [Chatterino/chatterino2#5073]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

After an excruciating amount of time trying to get streamlink work I realized the problem as stated in the title. So setting custom streamlink path in Chatterino lead to behaviour:

First:
"/home/schim/AppImages/streamlink.AppImage" -> chatterino.streamlink: Got error code 1

Then renaming the AppImage:
"/home/schim/AppImages/streamlink" -> works as intended 

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2 modified) built with Qt 6.5.3 Running on KDE Flatpak runtime, kernel: 6.6.6-76060606-generic, running from Flatpak

**Comment by SchimmelGelenk** [comment]
While this can be expected behaviour, it did not occur to me as Streamlink Twitch GUI recognizes the executable regardless of the filename extension. Maybe adding a note in above the custom path box would suffice as the user is not aware how Chatterino handles the executable

**Comment by pajlada** [comment]
The StreamLink errors/messaging can mention what the default binary path is, and what it expects the binary's name to be :+1: This would be a good first issue for someone looking to contribute

**Comment by pajlada** [comment]
I'd say this is resolved by the improved documentation in #5076
