### ISSUE TITLE
Double click link pause visually sticks around too long

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#5088]
Originally reported in Discord here https://discord.com/channels/253897423439659008/459650160658481152/1196382733291765790

<details>
<summary>Discord convo</summary>

- ![image](https://github.com/Chatterino/chatterino2/assets/25011746/3d8f6ff4-188e-40c3-b529-40a6f0223da9)
- ![image](https://github.com/Chatterino/chatterino2/assets/25011746/c910d143-d8cb-402d-abe3-e3d445b87876)
- ![image](https://github.com/Chatterino/chatterino2/assets/25011746/3f77569e-353d-4718-bfba-ca2194a1ecf9)

</details>

Pausing in general feels a bit off, should be looked into

**Comment by Felanbird** [comment]
Doesn't seem to _actually_ be paused, just appears to be if you click in a dead channel. 
Any message sent in the channel will correctly remove the pause, as well as removing your mouse from Chatterino's boundries at a normal speed (moving the mouse very fast will sometimes not remove the cosmetic pause)

Also correctly double-clicking a link like the setting expects clears the cosmetic pause.
