### ISSUE TITLE
Bump CI actions using Node 16 to Node 20

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#5152]
[they deprecating node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

- [x] Bump `jurplel/install-qt-action` https://togithub.com/jurplel/install-qt-action/pull/222 - #5408
- [x] Bump `ncipollo/release-action` https://github.com/Chatterino/chatterino2/pull/5160
- [x] Bump `dangoslen/changelog-enforcer` https://togithub.com/dangoslen/changelog-enforcer/pull/280 - resolved itself due to versioning magic
- [x] Bump `nerixyz/ccache-action` upstream project seems to be active again https://github.com/hendrikmuhs/ccache-action
- [ ] Bump `actionsx/prettier` #5618

I think that's it

**Comment by Nerixyz** [comment]
> Bump nerixyz/ccache-action upstream project seems to be active again [hendrikmuhs/ccache-action](https://github.com/hendrikmuhs/ccache-action)

Yes, upstream updated sccache (and node), so we can switch back.
