### ISSUE TITLE
`/live` channels never resolve when the channel was populated before displayname casing could be obtained

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#5158]
The `/live` tab uses display name casing, which is fair since we use it to populate the tab name as well.

The problem is the `/live` tab will sometimes populate the channels before the displayname casing is loaded, and due to this the channel will never gray out.

![image](https://github.com/Chatterino/chatterino2/assets/41973452/fe638a03-2b51-4b94-8aa1-3496b3fae27b)
These are the `/live` tabs for me from 2024-1-28, the ones that did not get displayname casing never resolved themselves.

Probably could be fixed by just accepting case-insensitive resolving, if we're watching `bobross` but `BobRoss` goes offline, that's good enough.

**Comment by Mm2PL** [comment]
This is because the search string uses display name. IMO this  whole logic should be changed to use a message id instead of search text.
 https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchChannel.cpp#L200
