### ISSUE TITLE
Reply does not work if you already have @name, inside chatbox

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#5171]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Right click on a name of person to insert @name, (or just type @name, ) and then when you try right click and reply to a message of his, it does not switch to the reply message/context, and the message is sent as normal message instead of a reply.

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit fe1e498a) built on 2024-02-11 with Qt 6.5.0, MSVC 193732826 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by Felanbird** [comment]
It doesn't work on the first press, but it works on the second

**Comment by KleberPF** [comment]
Should it keep the reply mention and the regular mention or get rid of the regular one? What if the user was mentioned multiple times prior to the reply?

**Comment by KleberPF** [comment]
> basically what happens when you try to reply the second time.

The problem is that for mentions you can keep right clicking and keep adding them, so I'm not sure if it should replace just the first one or all of them. I'd assume the first one.
