### ISSUE TITLE
Filterable /mentions tab

### ISSUE THREAD

**Issue by SFFan123** [Chatterino/chatterino2#518]
When you open  /mentions it would be neat if you could set chatterino set to just post the mentionings of a specific channel. (The channel has to be open) 
It would be neat if you are mod/caster and could filter the mentions to his channel/the channel he mods/watches.
![suggest mention](https://user-images.githubusercontent.com/38184195/41821611-cce98e7a-77e3-11e8-857d-84fd85a88e6a.PNG)

**Comment by fourtf** [comment]
Filters have their own issue
