### ISSUE TITLE
Split header tooltips sometimes show up in the wrong position

### ISSUE THREAD

**Issue by 8thony** [Chatterino/chatterino2#5189]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hovering over the split header, the tooltip appears, sometimes off centered or in the wrong position.
This only happens on the first hover of the channel split header (if you move your mouse off and back on, the tooltip is rendered correctly)
With a bigger thumbnail size or longer stream title, it's better to see, but it's not necessary.
I tested this on ffa63f0, but I think it is since fec8f8c. On eb8c7f2 and 3ad2e4b, i am not having his bug.

Steps to reproduce:
- put c2 to right monitor border
- make c2 window width like normal twitch chat or even smaller
- click a tab with a channel and hover over the channel split header
- repeat last step until the tooltip moves out of the main window or looks off centered (different channel each time)

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/114905842/78451456-4a14-4e47-9dd1-fb29a09d1acb)

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit ffa63f0) Windows 10

**Comment by notheowner** [comment]
It would be helpful if you provided an image or a video clip of the "wrong position" .

**Comment by Nerixyz** [comment]
Could reproduce after hovering over a split header of an active stream (with a thumbnail) and then hovering over a split header of an offline stream that hasn't been hovered since starting the app.

**Comment by 8thony** [comment]
Thanks for testing and confirming the bug @Nerixyz 
I think the other bug you mentioned is also possible on 2.4.6.
