### ISSUE TITLE
@ing tab autocomplete to streamer username

### ISSUE THREAD

**Issue by bmundt** [Chatterino/chatterino2#5190]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I cannot @ tab autocomplete the streamer. I see from other issues that the @ autocomplete has issues pulling from the whole chat and only pulls recent chatters. But, I feel like there should be an exception to this for the streamer, so you can @ them easily. Maybe even a shortcut to go to the streamer, since often people like to mimic the name of the streamer.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/11317863/c0acc327-1668-4b9f-ba33-7395e66d525b)

![image](https://github.com/Chatterino/chatterino2/assets/11317863/5ae17d0c-b781-4b25-b293-def63b0b9577)

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2d) built with Qt 6.5.0, MSVC 193532217 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by Felanbird** [comment]
Non-mods can't access the viewerlist anymore so we cannot confirm the streamer has the chat open, Hasan may be an exception to this logic due to the fact that he often has Chatterino on screen, but we can't magically use that information for every channel.

I'm not sure if I like the idea of faking a broadcaster into the `@mention` list

**Comment by bmundt** [comment]
Or perhaps just having it at the top of the mention list like in the normal twitch website.

![image](https://github.com/Chatterino/chatterino2/assets/11317863/4c351302-3a65-4fd4-a396-29b729855c5e)

**Comment by Felanbird** [comment]
He's at the top of the mention list because you are still allowed to view the viewerlist in browser chat, that suggestion doesn't change my previous answer

**Comment by KleberPF** [comment]
On the browser chat, even when the streamer is offline, they are the first option when typing @. I agree that it would be nice to also do this on Chatterino.

**Comment by pajlada** [comment]
I am fine with adding the streamer to the user autocomplete list, even if they're not in the chatters list or among the recent chatters.
When added, there should be a setting that can be disable this behaviour.

If my memory isn't failing me, I believe we did this before - prior to the chatter list changes

**Comment by Felanbird** [comment]
> If my memory isn't failing me, I believe we did this before - prior to the chatter list changes

I think we do have that feature still but Hasan has too many active chatters that he's eventually kicked out of the list

**Comment by bmundt** [comment]
Yeah you're right he is getting kicked out. I went to a smaller streamer, and can see their name right away when I hit @. Although, after sitting in that chat for a minute and having about 15 messages come through, their name is no longer at the top, but at the bottom, it is still there at least.
