### ISSUE TITLE
Make "AutoMod Caught Messages" highlight color & "show in mentions" configurable

### ISSUE THREAD

**Issue by djinnet** [Chatterino/chatterino2#5206]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I cannot change the highlight color to any other colors in highlight page under messages tab. 
Its color picker is disabled for no reasons and it makes it harder to spot monitored or restricted users when it is blended with the background.  

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/9974608/3a871e6a-4993-40f1-adaa-6a56dfe09306)

As you can see here; A has a color picker that allowed them to have different colors.
However B is disabled and has the same color as the darkmode's background and if the user of the program did not pay attention to this behavior, they can missed the message entirely. 

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit 0f42df78) built on 2024-02-26 with Qt 6.5.0, MSVC 193833135 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by pajlada** [comment]
I saw 3 separate feature requests here so I split your issue up
1) Make "AutoMod Caught Messages" configurable (highlight color & show in mentions)
2) Make "Restricted users" similary configurable #5207
3) Add support for "Monitored users" #5208

In the interim for this issue, there's a separate split called "AutoMod" that shows auto mod messages from every channel you have open that might be helpful

**Comment by KleberPF** [comment]
Should the allow/deny message also show up in /mentions? If so, should the added/removed term messages also appear?

**Comment by pajlada** [comment]
> Should the allow/deny message also show up in /mentions?

I think yes

> If so, should the added/removed term messages also appear?

I don't think this is important, no

Do you have any thoughts on this @djinnet?

**Comment by djinnet** [comment]
I 100% agreed on the first one. @pajlada That could make life easier for moderation purpose in a massive community.

But for second one; I honestly dont know. 
That depends on if it is easy to implemented, but perhaps that could be a choice for the end-user to have that appear or not.
After all many people are using chatterino with different setups and perhaps some may need it. 
But that is a "nice-to-have" from my point of view if that makes sense? I would love to hear more thoughts on that.

**Comment by KleberPF** [comment]
@djinnet It shouldn't be too hard to include it there. My PR for now doesn't include it, but I will probably add it later if pajlada wants.

**Comment by pajlada** [comment]
Let's leave it out for now & wait if people think it's missing
