### ISSUE TITLE
Scaling issue on macbook air 

### ISSUE THREAD

**Issue by Phi211** [Chatterino/chatterino2#5211]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The scale of the window is way too small. I've tried restarting the application, and deleting it and reinstalling it. 

### Screenshots

<img width="299" alt="2bf48eeb-2001-4648-9a9d-980605a31b9d" src="https://github.com/Chatterino/chatterino2/assets/161379146/fa3b6129-d75a-4dc3-a56f-b0ec3f56b3df">

### OS and Chatterino Version

Chatterino 2.4.5 on MacOS sonoma 14.1.1

Note: reverted edit which removed the entire text of the issue.

**Comment by Mm2PL** [comment]
Chatterino does not automatically scale I don't think. You can change the sizes of various app elements by:
 - changing the `Zoom` setting (affects all fonts and images), also bound to `Ctrl++`, `Ctrl+-` (is that the standard zoom out key binding on mac?)
 - changing the `Font Size` setting (affects only chat fonts)
 - changing the Emote `Size` setting (affects only emotes, not other images)

**Comment by Mm2PL** [comment]
Very similar to/duplicates https://github.com/Chatterino/chatterino2/issues/2412. 
[List of High DPI related issues](https://github.com/Chatterino/chatterino2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+dpi+label%3A%22high+dpi%22)

If you still have any questions about this feel free to ask here.
