### ISSUE TITLE
Commands not saving when pasting

### ISSUE THREAD

**Issue by LadoN15** [Chatterino/chatterino2#5235]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

_Disclaimer: English is not my first language. Also no computer geek._

Yesterday I noticed, that my command list is unexpectedly empty. 
Not that big problem, happened before. After my new PC setup a few months ago, I replaced the existing commands.json with my backup file in the appdata-folder without a problem. 

Now I tried two things:
1. As usal, I just replaced the whole file with filled one.
2. I copy pasted just the text.

But everytime after re-launching Chatterino, the filled command-file gets replaced with a new, empty file. And the filled file gets changed to a bkp-file.

WHAT WORKS:
Adding new commands in Chattrino itself, then they get saved. But I refuse to manually add all my existing 94 commands...

Thanks for your help in advance!

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2d) built with Qt 6.5.0, MSVC 193532217 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by pajlada** [comment]
Most likely what's happening is that the commands file you're trying to save is not valid JSON
You can validate your custom written commands file on this website: https://jsonlint.com/

Remember that the process for editing these files needs to be
1) Close down Chatterino
2) Make a backup of your existing file (optional if you don't care)
3) Make the changes you want in the file
4) Launch Chatterino

**Comment by Mm2PL** [comment]
I believe this is what happens when the library fails to parse the commands file, it silently fails and saves an empty file. Your `commands.json` is probably fixable.

**Comment by LadoN15** [comment]
@pajlada It worked wonderful, thank you!

**Comment by Mm2PL** [comment]
On a related note: Chatterino should fail louder if this happens. I would honestly expect a dialog box or a global system message explaining that `commands.json` is corrupted, same for `settings.json`. It's probably also a good idea to keep corrupted files separate from regular backups, to ensure the user will be able to fix their data even if it gets corrupted.
