### ISSUE TITLE
Automatic streamer mode detection does not work on macOS

### ISSUE THREAD

**Issue by MrPandir** [Chatterino/chatterino2#5259]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Today I started receiving notifications in the chatterino chat:
`Streamer Mode is set to Automatic, but pgrep is missing. Install it to fix the issue or set Streamer Mode to Enabled or Disabled in the Settings`.
But I have `pgrep` and it is available in `$PATH` at `/usr/bin/pgrep`.
I also downloaded OBS to check if this function works at all, and it turns out it doesn't work.
I downloaded the previous version `2.4.4` and the function still doesn't work there either.
`pgrep` works correctly for me:
```zsh
user@MacBook-Air ~ % pgrep obs
80118
```

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) built with Qt 6.5.0 Running on macOS 14.2, kernel: 23.2.0

**Comment by KleberPF** [comment]
What's the return of `pgrep -x obs`?

**Comment by Nerixyz** [comment]
You could also try `pgrep -x "obs|Twitch Studio|Streamlabs Desktop"` and `time pgrep -x "obs|Twitch Studio|Streamlabs Desktop"`.

My guess is that it's timing out. We might want to include the exit status of `QProcess` in [the warning](https://github.com/Chatterino/chatterino2/blob/ed20e71db4c957d3b2a8ce9350b847f4c805cb83/src/singletons/StreamerMode.cpp#L70-L75). I think if the command timed out, we shouldn't output an error.

**Comment by MrPandir** [comment]
No result:
```zch
user@MacBook-Air ~ % time pgrep -x "obs|Twitch Studio|Streamlabs Desktop"
pgrep -x "obs|Twitch Studio|Streamlabs Desktop"  0.00s user 0.00s system 25% cpu 0.032 total
```

However, if used in **upper case** it works:
```zch
user@MacBook-Air ~ % time pgrep -x "OBS|Twitch Studio|Streamlabs Desktop"
88726
pgrep -x "OBS|Twitch Studio|Streamlabs Desktop"  0.00s user 0.01s system 31% cpu 0.030 total
```

**Comment by pajlada** [comment]
This should be fixed with the latest nightly version, available to download for github releases in about 30 minutes from this comment @MrPandir
