### ISSUE TITLE
BTTV and 7TV emotes don't work + slow chat history load

### ISSUE THREAD

**Issue by Larsenay** [Chatterino/chatterino2#5268]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

For the past 3 days 7TV and BTTV emotes have stopped working for me. Chat history also takes 15-20 seconds to load (was instant before). I can see Twitch emotes and FFZ emotes just fine. I noticed this only happens on my PC. My laptop works completely fine and is on the same Chatterino version.

Pressing F5 gives me:
-FrankerFaceZ channel emotes reloaded
and then after 15-20 seconds I get:
-Failed to fetch 7TV channel emotes. (Error: TimeoutError)
-Failed to fetch BetterTTV channel emotes. (Error: TimeoutError)

Things I have tried:
-Cleared cache and hit "reset"
-Running as administrator
-Complete reinstall of Chattterino, removing everything
-Tried the 7TV chatterino (same issue)

No idea what could be the issue as it only happens on my PC and I haven't changed any settings.

### OS and Chatterino Version

Chatterino 2.4.6 (commit eb8c7f2d) built with Qt 6.5.0, MSVC 193532217 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by Felanbird** [comment]
We have a fairly short, but reasonable, time set of 5 seconds before we accept that the emote response isn't coming, so it's very likely you are having some issue getting the response from BTTV/7TV, likely due to some connection issue.

**Comment by Nerixyz** [comment]
As for the timeouts, that's probably 7TV images clogging the network access manager (it has some internal limit). Since we have no timeout for images, these will stay in there for quite some time (until the transport times out after about 1-2min).
I think loading images needs to be refactored. maybe it needs to be decoupled from the main network access manager (this might come with more memory usage though).

**Comment by Larsenay** [comment]
Just tried to renew my IP and that fixed it. Is it possible for my IP to have been blacklisted in some way?

**Comment by pajlada** [comment]
> Just tried to renew my IP and that fixed it. Is it possible for my IP to have been blacklisted in some way?

Questionable but who really knows when it comes to network issues
