### ISSUE TITLE
Highlight sound randomly bugs

### ISSUE THREAD

**Issue by DatGuy1** [Chatterino/chatterino2#529]
The highlight sound randomly bugs after a mention and starts constantly playing the same sound, starting later and later. For example, my custom highlight sound is 'action is coming,' I recorded this halfway in (sorry for bad quality) https://vocaroo.com/i/s0i0NNp6MFqV

**Comment by fourtf** [comment]
Add cooldown for ping sound.

**Comment by pajlada** [comment]
Closing in favour of #1736
