### ISSUE TITLE
Chatterino won't connect and repeatedly disconnects 

### ISSUE THREAD

**Issue by schmiddi312** [Chatterino/chatterino2#5290]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I have only one tab open. Same issue on my PC as here on my laptop. 
Wiki and previous reports mostly state that users should not have too many tabs open (I think the limit is 20). But I have only one tab open and this issue: 

![grafik](https://github.com/Chatterino/chatterino2/assets/154901169/34028b92-5bd2-40b3-9647-df4efcf8ab33)

Tried it in different channels etc. 
Tried different versions, adminisrator mode etc. 
The only thing I did not try is using it with a different Twitch account, but I currently have only one and only want to use that one. 

Running Chatterino Nightly 7.4.6 on Windows 11. 
Latest Version of x64 Visual C++ Redistributable is also installed. 

### OS and Chatterino Version

Chatterino Nightly 7.4.6 (commit 1d715c14) built on 2024-04-01 with Qt 6.5.0, MSVC 193833135 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by pajlada** [comment]
This sounds like a network issue on your end. Are you connected to a VPN, or maybe on a school network that might be a bit more locked down?

**Comment by schmiddi312** [comment]
> This sounds like a network issue on our end. Are you connected to a VPN, or maybe on a school network that might be a bit more locked down?
Thank you very much, it was not any of the possible issues you mentioned, but I used a program which is I think similar to a VPN or firewall or something like this. I disabled it and now everything works. 
Thank you!
