### ISSUE TITLE
Split header tooltip sometimes gets stuck

### ISSUE THREAD

**Issue by sando** [Chatterino/chatterino2#5308]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Right-clicking on a split header while the Chatterino window is inactive causes the split header tooltip stay visible until you hover over the split header again. Normally, the tooltip should disappear as soon as you right-click.

To reproduce:
1. Focus any other window than Chatterino
2. Right-click on the split header (this might take a few tries)
3. Split header tooltip stays stuck until the split header is hovered over again

### Screenshots

https://github.com/Chatterino/chatterino2/assets/58441/0dc78732-6c5f-4aea-8127-d25a0a283013

### OS and Chatterino Version

Chatterino Nightly 2.5.0-beta.1 (commit 25a69fd1) built on 2024-04-07 with Qt 6.5.0, MSVC 193833135 Running on Windows 11 Version 24H2, kernel: 10.0.26090

**Comment by Felanbird** [comment]
can replicate 
![image](https://github.com/Chatterino/chatterino2/assets/41973452/5c9d291d-2500-4c06-895f-85626852a4d3)
