### ISSUE TITLE
Notitia chatterino returns `522` error

### ISSUE THREAD

**Issue by MrPandir** [Chatterino/chatterino2#5310]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

It seems like something is broken 🫠

### Screenshots

<img width="923" alt="Screenshot 2024-04-09 at 12 50 15" src="https://github.com/Chatterino/chatterino2/assets/137798474/ebbbccbc-9ed5-4c57-97c3-05279eb7b61d">

**Comment by Felanbird** [comment]
this is fixed
