### ISSUE TITLE
All tabs deleting themselves besides online tabs

### ISSUE THREAD

**Issue by Jawman2000** [Chatterino/chatterino2#5315]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Only tabs of streamers that are live stay open. Any other tabs i.e. offline chat rooms, /whispers, /mentions all remove themselves.

### Screenshots

https://github.com/Chatterino/chatterino2/assets/109163523/0c9c407b-c632-485a-ba37-f61c3531082d

### OS and Chatterino Version

Chatterino 7.4.6 (commit f2d677b2) built with Qt 6.5.0, MSVC 193532217 Running on Windows 11 Version 21H2, kernel: 10.0.22000

**Comment by Wissididom** [comment]
Try pressing Ctrl+Shift+L :thinking:

**Comment by Nerixyz** [comment]
> Try pressing Ctrl+Shift+L 🤔

This should probably be in the context menu of the notebook for better discoverability.

**Comment by KleberPF** [comment]
Considering how often this gets asked, would a pop-up (with the option to hide next time) explaining why the new tab got hidden be a good idea? There is also the context menu option missing, as pointed out by Nerixyz.
