### ISSUE TITLE
Using filters on a Watching tab with a pre-existing chat open. Creates a unresponsive, unremovable box at the bottom of chat.

### ISSUE THREAD

**Issue by melon095** [Chatterino/chatterino2#5327]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Opening a normal tab, then adding the same channel to the _Watching_ tab, with a filter enabled creates a unclickable, unremovable black box at the bottom of chat.

Chatterino commit c391ff97. 

Issue has been observed on Qt _6.7.0_ and Qt _6.5.2_ which was downloaded with the provided vcpkg.json file.

Im not entirely sure which commit made this occure. I previously used a build from a few months ago and just recently updated my build which is when this issue occured.

From my extensive testing, i've narrowed the issue down to having a _semi_ large regex as a filter.

For example i used `(message.content match r"^(?!.*(?:my|complex|(re.*x))).*$")`.

And every time i reloaded the _Watching_ tab the issue would appear. Disabling filters or using something simpler as an empty regex or just `message.length > 0` made this issue never appear.

### Steps to reproduce

1. Create a regex, for example `(message.content match r"^(?!.*(?:my|complex|(re.*x))).*$")`
2. Create a tab with a live channel. (Issue wasn't observed on a offline chat).
3. Create a _Watching_ tab and apply the filter you created in step 1.
4. Make the _Watching_ tab open any random chat. Just not the one from step 2.
5. Open the chat from step 2 in the _Watching_ tab.
6. The box should show up.

### Screenshots

![Animation](https://github.com/Chatterino/chatterino2/assets/24413121/5e2d0e2c-65f8-4773-825d-53c8b25d2cfd)

### OS and Chatterino Version

Chatterino 2.5.0-beta.1 (commit c391ff97 modified) built with Qt 6.7.0, MSVC 193933523 Running on Windows 10 Version 21H1, kernel: 10.0.19043

**Comment by pajlada** [comment]
Thanks for the informative report!
