### ISSUE TITLE
Show chatter list button still available for non-moderators

### ISSUE THREAD

**Issue by 4rneee** [Chatterino/chatterino2#5335]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

https://github.com/Chatterino/chatterino2/pull/5245 hid the chatter list button for non-moderators because non-moderators don't have access to the chatter list anymore. However, the button `three dots -> more -> Show chatter list` still exists even for non-moderators.  
I am not sure if this is intentional or not but if not it should be removed.

### Screenshots

The chatter list button next to the three dots is no there but in the menu the button still exists.
![Show chatter list button](https://github.com/Chatterino/chatterino2/assets/78976058/73c36979-ca7f-4e4d-96a4-02a4dc2c3820)

### OS and Chatterino Version

Chatterino 2.5.0-beta.1 (commit 7c97e6bc modified) built with Qt 6.7.0 Running on Arch Linux, kernel: 6.8.7-arch1-1

**Comment by pajlada** [comment]
Thanks for the report!

**Comment by arconom** [comment]
Why should a viewer not be able to open the viewer list?

**Comment by pajlada** [comment]
> Why should a viewer not be able to open the viewer list?

Twitch's API does not allow for a regular viewer to query the viewer list, so us showing the button doesn't make sense.

**Comment by arconom** [comment]
> > Why should a viewer not be able to open the viewer list?
> 
> Twitch's API does not allow for a regular viewer to query the viewer list, so us showing the button doesn't make sense.

Oh that is strange.   I wonder why I can see the viewer list in the browser.

**Comment by iProdigy** [comment]
> Oh that is strange. I wonder why I can see the viewer list in the browser.

Twitch uses a separate first-party API to power the front-end, which abides by separate rules. As a result, we're effectively punished for using the official API while motivated actors can easily bypass this restriction
