### ISSUE TITLE
Doxygen SSL handshake failed Error code `525`

### ISSUE THREAD

**Issue by MrPandir** [Chatterino/chatterino2#5338]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

[doxygen.chatterino.com](https://doxygen.chatterino.com)

### Screenshots

<img width="995" alt="Screenshot 2024-04-20 at 21 29 17" src="https://github.com/Chatterino/chatterino2/assets/137798474/a6a04e46-d039-4bbb-b12f-e8a542dec8a4">

**Comment by fourtf** [comment]
Hi, I fixed the website. Although no new doxygen documentation will be generated at this moment until I fix the compilation as well. Perhaps I can move it to GitHub Actions?

**Comment by Nerixyz** [comment]
> Perhaps I can move it to GitHub Actions?

https://github.com/Chatterino/chatterino2/pull/5334 kinda enables that.
