### ISSUE TITLE
Toggle visibility of tabs hotkey behaves differently than right click when used with Show live tabs only

### ISSUE THREAD

**Issue by bontalor** [Chatterino/chatterino2#5341]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When using Show live tabs only, using right click to toggle visibility of tabs will toggle back to only showing live channels, but when using the Ctrl+U hotkey it toggles back to showing all tabs regardless of live or not.

### Screenshots

right click example:

https://github.com/Chatterino/chatterino2/assets/62087307/5e0b3ca2-f73a-4019-8cf9-1a9e91194088

hotkey example:

https://github.com/Chatterino/chatterino2/assets/62087307/6e1212f9-c3c6-458a-a7c7-a255ecdaff11

### OS and Chatterino Version

Chatterino Nightly 2.5.0 (commit 3aead093) built on 2024-04-21 with Qt 6.5.0, MSVC 193833135 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by Nerixyz** [comment]
I'd say this is a bug with the <kbd>CTRL</kbd>+<kbd>U</kbd> hotkey, as it will always show all tabs: https://github.com/Chatterino/chatterino2/blob/3aead09339ffff0fbfd9f8a7a5ea9eb551ad8fb8/src/widgets/Window.cpp#L648-L653

The menu action is identical to pressing <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> (toggle live tabs only).

**Comment by gerbsec** [comment]
I believe this is a bug...

**Comment by Felanbird** [comment]
> I believe this is a bug...

Yes Neri's comment right above yours indicates this and also points to where the problem is.
