### ISSUE TITLE
Chatterino windows freeze when holding close button in search pop-up

### ISSUE THREAD

**Issue by clevernt** [Chatterino/chatterino2#5342]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Pressing and holding the close button in the chat search pop-up freezes all windows until the left mouse button is released.

### Screenshots

![chatterino_O6WQWE61h2](https://github.com/Chatterino/chatterino2/assets/61787059/1efe471f-e23e-4be7-a107-1bfe4ae3311b)

### OS and Chatterino Version

Chatterino 2.5.0 (commit 3aead093) built with Qt 6.5.0, MSVC 193833135 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by Nerixyz** [comment]
This happens for all windows that don't use our custom frame (e.g. the settings window), so it might be something with Qt.

**Comment by Nerixyz** [comment]
I'm inclined to say, "that's how Windows works". You can notice the same in other (not all) apps - for example, Task Manager won't update if you hold the close button. If that's still not enough, it's rather a "bug" in Qt, not in Chatterino.
