### ISSUE TITLE
Unable to open links without protocol

### ISSUE THREAD

**Issue by M4tthewDE** [Chatterino/chatterino2#5343]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I can't open links that don't have a protocol (http/https). I can click them, but nothing happens.

Links that work:
http://www.google.com
https://www.google.com

Links that do not work:
www.google.com
google.com

The link preview also does not work for these links.

![image](https://github.com/Chatterino/chatterino2/assets/30239653/b510e89d-36ab-48b0-b35b-f804ac7f6d2f)

### OS and Chatterino Version

Chatterino 2.5.0 DEBUG (commit 1a04bda5 modified) built with Qt 5.15.13 Running on Arch Linux, kernel: 6.8.5-arch1-1

**Comment by clevernt** [comment]
same here.

**Comment by M4tthewDE** [comment]
The issue was introduced with https://github.com/Chatterino/chatterino2/pull/5323, it does not exist in bf8266e9b3fbf3e68166bdc90038cf848a9f4bf9
