### ISSUE TITLE
2.5.0 is a pre-release or stable?

### ISSUE THREAD

**Issue by core-code** [Chatterino/chatterino2#5344]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

i am confused about 2.5.0 - on github it is marked as a prerelease, on chatterino.com it is the default download

### Screenshots

none

### OS and Chatterino Version

any

**Comment by pajlada** [comment]
Fixed, thanks. 2.5.0 is the latest stable release
