### ISSUE TITLE
Dismiss Chatterino update until the next version

### ISSUE THREAD

**Issue by x9136** [Chatterino/chatterino2#5372]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

If I am not interested in updating, then I remove the update button so that there is more space for tabs. But if you restart Chatterino, the update button appears again. You have to remove it every time, just because that's how it works.

My desire to update Chatterino does not depend on the update button in any way — it depends on whether there are changes in the update that I am interested in. This behavior looks ill-conceived or like a bug, because it is weird to update only to remove the update button. By the way, when I was on the beta version before the 2.5.0 release, the update button suggested that I downgrade the version and did not disappear either (for what?).

I suggest that after clicking "Dismiss", do not show the update button until the next version is available. For example, if I dismissed 2.5.1, then the update button should appear only when a version newer than 2.5.1 appears.

### Screenshots

![Screenshot 2024-04-30 at 11 47 10](https://github.com/Chatterino/chatterino2/assets/60105060/62d6c29b-f781-4aa3-b054-641cd23ff3b7)

### OS and Chatterino Version

Chatterino 2.5.0 (commit 3aead093 modified) built with Qt 6.5.0 Running on macOS 14.4, kernel: 23.4.0

**Comment by Felanbird** [comment]
I don't like the idea of locking someone out of updating because they clicked dismiss, you can already add `portable` to your modes file to avoid update prompts

**Comment by x9136** [comment]
> I don't like the idea of locking someone out of updating because they clicked dismiss

It's unclear why you decided to defend the current solution, but ok.

To make it clearer to you, I will explain the issue from the other side. In order for the update button not to interfere with the tabs and not constantly remind you of what is clear after 1 time, you need to do one of the following actions:
1. Update Chatterino, even if you don't need it.
2. "add `nightly` to your modes file to avoid update prompts".

Seriously? Let me create the same issue every day until you solve it. It's the same thing. 

I can think of a bunch of solutions to fix this issue. For example, you can simply make 3 buttons instead of 2, since you are so attached to the current solution: **Postpone this version** — **Dismiss** — **Install**. There are several solutions that are so simple, others are a little more complicated.

If you don't really see an issue in the current solution, or you're not interested in finding a better solution for it, then I suggest you close this issue as **Not planned** and that's it.

**Comment by x9136** [comment]
I Googled what the "model file" is and found that this issue was raised more than 3 years ago. #2163

Then of course I wrote in vain. Obviously, it will not be corrected.

**Comment by Felanbird** [comment]
I'm going to ask you to please stop opening issues and discussion if you can't handle responses that aren't exactly what you want. You very often open discussions and close them when _you_ feel like enough time has passed without a response or implementation. This is an open source application and features are added if/when someone does it, not when someone passive-aggressively bumps it.

**Comment by x9136** [comment]
>  if you can't handle responses that aren't exactly what you want.

What does this mean? Could you give examples, because now your claim seems to me to be something personal, and not to talk about Chatterino.

> You very often open discussions and close them when you feel like enough time has passed without a response or implementation.

We have a different understanding of what "very often" is. I don't think that opening 20-30 issues and discussions in a year is often or very often. I don't think there is any problem in closing some of them after some time for one of the following reasons:
- there was a similar issue/discussion, so I created a duplicate;
- during our discussions, it became clear that my suggestion is useless — there is no point in keeping it open;
- while a suggestion was open and time passed, I decided that it wasn't really useful. I have the right to reject it = close it.

As I said before, you have the right to reopen anything.

Your claims are incomprehensible and not close to me. I don't understand why you don't like everything all the time, and I don't want to deal with it. If we still have to talk, then I suggest we talk about those topics in which there will be a dialogue about Chatterino.

I have nothing more to add on this, because it is weird to waste time on such explanations.
