### ISSUE TITLE
Flatpak version seems to be broken everywhere when trying a fresh install

### ISSUE THREAD

**Issue by whoami1i1i1i** [Chatterino/chatterino2#5373]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino has been working fine, however recently after reinstalling my OS (Linux Mint Cinnamon 21.3) I've noticed that the size of Chatterino flatpak is unusually small (11mb or so, the size before was much, much bigger)
After trying to install it, nothing happens when I try to open it
The bugged size is even on flathub: https://flathub.org/apps/com.chatterino.chatterino
I've tested it across multiple distros both on real hardware and in virtual machines, the result is the same everywhere
I think this only affects trying to freshly install Chatterino since it's been fine a few days ago, OS was fully updated, and the 2.5.0 update which seems to have caused this was 10 days ago
Fresh installs of other flatpak applications were without issues

### OS and Chatterino Version

Chatterino 2.5.0 Flatpak on Linux Mint Cinnamon 21.3

**Comment by Felanbird** [comment]
@ilya-zlobintsev thoughts?

**Comment by ilya-zlobintsev** [comment]
I'll take a look at it tomorrow. Though 11mb is a normal size for chatterino itself.

**Comment by ilya-zlobintsev** [comment]
I cannot reproduce this, I just booted a fresh Linux Mint 21.3 VM, installed latest stable Chatterino, and it works fine:
![image](https://github.com/Chatterino/chatterino2/assets/22796665/c121d0c8-656a-4bc2-b910-861014a6d2f3)


Could you be more specific of how it doesn't work? What are the logs when you try to run it?
```
flatpak run com.chatterino.chatterino 
```

**Comment by whoami1i1i1i** [comment]
> I cannot reproduce this, I just booted a fresh Linux Mint 21.3 VM, installed latest stable Chatterino, and it works fine: ![image](https://private-user-images.githubusercontent.com/22796665/327065493-c121d0c8-656a-4bc2-b910-861014a6d2f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NTE1OTMsIm5iZiI6MTcxNDk1MTI5MywicGF0aCI6Ii8yMjc5NjY2NS8zMjcwNjU0OTMtYzEyMWQwYzgtNjU2YS00YmMyLWI5MTAtODYxMDE0YTZkMmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDIzMjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDk4NjdjOTk1YTljM2U5M2QyN2U0M2FlNDM4N2ZlMTYzN2Y4YmE1M2YxZDU4NDZkNGFiY2EwNWY0ZDAzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Of-hSfUm8cwbmld1srnZBotjrfeCdVUbmBQaC-16zYo)
> 
> Could you be more specific of how it doesn't work? What are the logs when you try to run it?
> 
> ```
> flatpak run com.chatterino.chatterino 
> ```

Sorry for the delay, I didn't have access to my PC past few days

When I try to launch it I get the "error: runtime/org.kde.Platform/x86_64/6.5 not installed" error

It was installed through the linux mint software center, however after trying installing it through the command like in your screenshot it does install the kde runtime and everything works

It used to install that runtime earlier in the mint store though, that's weird...

**Comment by pajlada** [comment]
I suspect this is some misconfiguration of some other software, not an issue on our end.
If it turns it it is something on our end, please re-open the issue
