### ISSUE TITLE
Failed to build new v2.5.0 on Fedora

### ISSUE THREAD

**Issue by tim77** [Chatterino/chatterino2#5376]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Since chatterino2 version `2.5.0` failed to build from source on Fedora Linux. Previous chatterino2 versions compiles fine.

```
/builddir/build/BUILD/chatterino2-2.5.0/src/common/network/NetworkPrivate.cpp:204:1: internal compiler error: in streamer_write_chain, at tree-streamer-out.cc:536
  204 | }  // namespace chatterino
      | ^
```

- Full [build log](https://kojipkgs.fedoraproject.org//work/tasks/1442/117021442/build.log)
- [Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=117196315)
- [PR](https://src.fedoraproject.org/rpms/chatterino2/pull-request/9#request_diff) with diff changes from `v2.4.6` to `v2.5.1`

Help wanted.

### OS and Chatterino Version

Chatterino 2.5.1

**Comment by pajlada** [comment]
Could you try building with clang or with lto disabled?

**Comment by Nerixyz** [comment]
You're running into [Bug 114501](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114501) because LTO is enabled.

**Comment by tim77** [comment]
> You're running into [Bug 114501](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114501) because LTO is enabled.

It compiles fine if LTO disabled, thanks!

@pajlada i'll try to build with Clang also. I need your recommendation here: what is preferable choice, build chatterino2 with Clang or GCC in Fedora?

**Comment by pajlada** [comment]
I aim to support both, so the choice is up to you. It's probably easier to temporarily disable LTO until the bug is fixed so that's what I would've personally done

**Comment by tim77** [comment]
Understood, thanks. `chatterino2` [built](https://bodhi.fedoraproject.org/updates/?packages=chatterino2) for Fedora >=39 branches.
