### ISSUE TITLE
Subscriber emotes do not appear after updating

### ISSUE THREAD

**Issue by aandreysr** [Chatterino/chatterino2#5384]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

After updating to version 2.5.1, all emotes from the channels I'm subscribed to no longer appear in the emotes' "subs" tab, and of course, I have active subscription

### Screenshots

![Captura de tela 2024-05-07 000055](https://github.com/Chatterino/chatterino2/assets/22335271/6c2b160e-9d15-4b73-9bfa-fd5b726590f7)

### OS and Chatterino Version

Chatterino 2.5.1 (commit eafcb941) built with Qt 6.5.0, MSVC 193833135 Running on Windows 10 Version 22H2

**Comment by brian6932** [comment]
Currently the server Chatterino uses is experiencing some failures. Chatterino doesn't control it, I've informed the server owner (they're not awake yet). The issue you're experiencing should be unrelated to the client update.

**Comment by aandreysr** [comment]
Ah, that explains a lot. I found it strange because some people aren't facing the issue. Anyway, thank you very much

**Comment by Felanbird** [comment]
> I found it strange because some people aren't facing the issue. Anyway, thank you very much

they already loaded their sub emotes before the service went down
