### ISSUE TITLE
[Nightly] chatterino-windows-old-x86-64-Qt-5.15.2 GetDpiForWindow on older OS

### ISSUE THREAD

**Issue by UnfortunateLiama** [Chatterino/chatterino2#5390]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Entry point not found

https://github.com/Chatterino/chatterino2/commit/febcf464fe9f9caa78fbfb0d3fb2db8cb372ee22

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow#requirements

### OS and Chatterino Version

title

**Comment by pajlada** [comment]
What OS are you on?
