### ISSUE TITLE
Emotes starting with a colon (':') can't be tab-completed

### ISSUE THREAD

**Issue by Nerixyz** [Chatterino/chatterino2#5399]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

- type `:tf:`
- press <kbd>ESC</kbd> to close the popup
- press <kbd>TAB</kbd> (or whatever key you set completion to)

**Expected**: A space is inserted.
**Actual**: No space is inserted.

This worked in Chatterino 2.4.6 and broke in 2.5.0-beta.1. Enabling "smarter" emote completion **does not** fix this.

### OS and Chatterino Version

Chatterino Nightly 7.5.1 (commit 0668f29d) built on 2024-05-12 with Qt 6.5.0, MSVC 193933521

**Comment by Mm2PL** [comment]
For completeness' sake smarter emote completion is just sorting of completion
