### ISSUE TITLE
Outdated flatpak version

### ISSUE THREAD

**Issue by eldiosx** [Chatterino/chatterino2#5403]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

its so sad :sad

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/61506276/76e65029-da04-4cec-b4a7-0d4b98a52069)

### OS and Chatterino Version

Chatterino 2.4.6 LInux - Flatpak

**Comment by Felanbird** [comment]
https://flathub.org/apps/com.chatterino.chatterino
