### ISSUE TITLE
7TV and BTTV live emote updates are not proxied

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#5416]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When using socks proxy that is reachable, starting the app, everything loads and works, when you make said proxy unreachable (e.g. disable VPN connection), chatterino disconnects (as it should), but 7TV and BTTV emote updates still get received.

![image](https://github.com/Chatterino/chatterino2/assets/1310440/8692dbc0-0221-4531-82ce-a5d49514dfed)

I'm not familiar with websockets (which seems to be the case for this usage), but shouldnt they still be proxied?

(When using socks proxy and starting the app with connection to proxy disabled, obviously nothing shows up, no "connected message" nothing loads, and emote live updates dont show up (but I could not confirm whether they are transmitted or not).)

### OS and Chatterino Version

Chatterino Nightly 2.5.1 (commit c3b84cb4) built on 2024-05-11 with Qt 6.5.0, MSVC 193833135 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by pajlada** [comment]
This is a known limitation, and is documented on the wiki

https://wiki.chatterino.com/Environment%20Variables/#chatterino2_proxy_url

**Comment by pajlada** [comment]
It's a pretty heavy lift atm, so it won't be fixed specifically to fix this, no. You can use HTTP proxy to work around it.
