### ISSUE TITLE
[Wayland] Drag and Drop breaks tooltips

### ISSUE THREAD

**Issue by fruzitent** [Chatterino/chatterino2#5432]
### Checklist

- [ ] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Hyprland (broken)

```shell
$ hyprctl version
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
```

https://github.com/Chatterino/chatterino2/assets/40008647/a03a3f63-7283-4372-8774-99fb91a3b6a5

### Sway (works)

```shell
$ sway --version
sway version 1.9
```

https://github.com/Chatterino/chatterino2/assets/40008647/141e25d7-e483-44b9-b522-3c626932ff05

### OS and Chatterino Version

Chatterino 2.5.1 (commit 9ec102240) built with Qt 6.7.1 Running on Arch Linux, kernel: 6.9.2-arch1-1

**Comment by pajlada** [comment]
On X11, the tooltip instead disappears. Some investigations I've made seems to imply the issue here is changing the parent of the tooltip, which is reparented when the Split is reparented.

If you comment out `split->setParent(nullptr);` in `SplitContainer::releaseSplit`, the bug will only show up when moving the split inbetween split containers instead, since the parent of the split stays the same.

**Comment by kornes** [comment]
windows is also affected by this bug,
detaching split for drag/drop breaks all current child windows, confirmed with: select channel, pinned usercard, search popup

**Comment by JCRouzer29** [comment]
The drag/drop appears to also break emote and username autocompletion popup menus.  Once moved they cease to appear.

**Comment by JCRouzer29** [comment]
Unfortunately, the pinned usercard windows are still being lost upon drag/drop logic.  

Other child windows appear to be working as intended as well as emote and username completion.

https://github.com/user-attachments/assets/522d42df-37de-453b-9bda-602205f482e4

**Comment by pajlada** [comment]
> Unfortunately, the pinned usercard windows are still being lost upon drag/drop logic.
> 
> Other child windows appear to be working as intended as well as emote and username completion.
> Usercard.Still.Not.Working.as.Intended.mp4

Could you make a new issue to track this?

**Comment by Nerixyz** [comment]
> Unfortunately, the pinned usercard windows are still being lost upon drag/drop logic.

Can replicate on 6.7.1 and 6.7.2 but not on 6.8.0 (beta3) which should be out in about a month.
