### ISSUE TITLE
Replying Issue

### ISSUE THREAD

**Issue by EinfachMxrc** [Chatterino/chatterino2#5433]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The first image illustrates the problem where I want to reply to a message that was sent in response to my initial message. However, instead of replying to their message, I'm inadvertently responding to my own message, even though I clicked on their reply.

The second image shows me on Twitch in the dashboard, where I click on the reply from someone who responded to me, and it works perfectly there. The issue is that if I accidentally respond to myself, the intended recipients don't get notified about my response.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/94084058/42ec2da2-5878-404d-af09-a6e3668e98a3) 
![image](https://github.com/Chatterino/chatterino2/assets/94084058/8fee3984-edb4-47de-85e5-a33e5f6185d5)

### OS and Chatterino Version

Chatterino 2.5.1 Windows 11

**Comment by Mm2PL** [comment]
> I'm inadvertently responding to my own message, even though I clicked on their reply.

You are replying to the thread that message is in, not a message. Reply threads just work this way on twitch. Pretty sure even webchat does it this way. We could technically change it to reply to every message creating a new thread each time, not sure how it will work with our threads gui implementation.

> The issue is that if I accidentally respond to myself, the intended recipients don't get notified about my response.

When it comes to Chatterino users, if you reply in a thread all replies to the thread will be highlighted for you. You can change reply threads notifications for yourself in the highlight settings.

If you want to create a new reply thread you can do that from the right click menu using the *Reply to message* option (not *Reply to original message*)

**Comment by Felanbird** [comment]
The above comment comment would be correct from Aug 2022 - Nov 2023 but is no longer the case.

We already do reply to the message you intend to reply to, but you have to click the `Reply to message` button, if you click the `Reply to original thread` button, you will reply to the original message at the top of the thread.

![image](https://github.com/Chatterino/chatterino2/assets/41973452/c3007a8e-4da0-45c3-b388-349a98b3c9a5)
First reply from me was from clicking `Reply to message` on magichackbot's message, the second reply came from clicking `Reply to original thread` on pajbot's message

**Comment by Felanbird** [comment]
As mentioned in combination with myself and mm2pl, what you've reported is not an issue just how reply thread popups have to work, if you want to reply directly to a message, right-click it and use the normal input box to send your reply.
