### ISSUE TITLE
3rd Party Global Emotes not loading on app launch

### ISSUE THREAD

**Issue by notheowner** [Chatterino/chatterino2#5434]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

As of nightly `d00cadf4` Chatterino2 is not showing 3rd Party Global Emotes on app startup.
Reconnecting or restarting doesn't seem to load them either.

Seems toggling global emotes in settings off and back on, fixes this.
So maybe emotes are loaded but Chatterino boots up with the global settings off even though they appear as on.

### Screenshots

![image](https://github.com/Chatterino/chatterino2/assets/86596679/a4123ba9-b17e-4dc7-8048-4a54454e0210)

### OS and Chatterino Version

Chatterino Nightly 2.5.1 (commit [d00cadf4](https://github.com/Chatterino/chatterino2/commit/d00cadf4)) built on 2024-06-02 with Qt 6.7.1, MSVC 193933523
Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by brian6932** [comment]
Reverting b6dc5d9e03aad21f1b8c76c588a1a627fbe41c9e fixes it for me.
