### ISSUE TITLE
Live Channels appears offline

### ISSUE THREAD

**Issue by shuffgy** [Chatterino/chatterino2#5437]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Every Live Channel appears offline.

- I reinstalled Chatterino,
- I reinstalled the [VC++ Redistributables](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- i relogged in

Still, every **Live** Channel appears offline. Everthing else is loaded (chat messages by example).

### OS and Chatterino Version

Chatterino 2.5.1 (commit eafcb941f57011358d63c76de6bee38ca1ba, 2024-04-28), Windows 11

**Comment by Felanbird** [comment]
This description does not describe anything about the issue, in the title you say `channels` but in the description you say `channel`, report information needs to be specific as one other person reported this, but only for a single _channel_

Also it's preferred if you follow the suggested instructions for filling out the OS and Chatterino version, as that information is often useful for debugging a problem
![image](https://github.com/Chatterino/chatterino2/assets/41973452/2bf363fc-ad65-44ae-b2db-f4cd4f3568bf)

**Comment by shuffgy** [comment]
> This description does not describe anything about the issue, in the title you say `channels` but in the description you say `channel`, report information needs to be specific as one other person reported this, but only for a single _channel_
> 
> Also it's preferred if you follow the suggested instructions for filling out the OS and Chatterino version, as that information is often useful for debugging a problem ![image](https://private-user-images.githubusercontent.com/41973452/336572506-56363848-9415-4811-b840-a6aa211760bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Mjc0MjcsIm5iZiI6MTcxNzUyNzEyNywicGF0aCI6Ii80MTk3MzQ1Mi8zMzY1NzI1MDYtNTYzNjM4NDgtOTQxNS00ODExLWI4NDAtYTZhYTIxMTc2MGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDE4NTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZGUyN2U1NzcwOWZjNzgzYjQ1ZDE4M2E3MDliN2MzMWEzMjFiNTYxZWM3OGY2YzZjMjBhNjg5MTk2NmE2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t1Rle3hTMQPVpyIQ1iLNYUIVJaxY8obDYoBeLUskyU0)

Well, yes i forgot an `s` in the description. I'm sorry. But i think the issue is well described: Live channels appears offline. There is nothing to add, except the steps i tried to fix it myself.
I re-downloaded the commit that is tagged as 2.5.1, but i added the commit hash.

I had multiple tabs, a few of them where live but chatterino showes every channel as offline. Do we need some more informations?

**Comment by Felanbird** [comment]
Try re-logging

**Comment by shuffgy** [comment]
> Try re-logging

as already described, i did that..

**Comment by Felanbird** [comment]
> as already described, i did that..

I stopped reading after `I tried some stuff` as I didn't expect any useful information to be mentioned after that

**Comment by shuffgy** [comment]
> > as already described, i did that..
> 
> I stopped reading after `I tried some stuff` as I didn't expect any useful information to be mentioned after that

I happy that i teached you wrong for the next time.

**Comment by Felanbird** [comment]
Live status information comes from Twitch's Helix API so the main assumption is you can't receive the information bounced back from those requests, either you're having an internet issue or you've hit the ratelimits for the Helix API.

**Comment by Nerixyz** [comment]
Shameless ad: Since you're on Windows, you can try to capture logs with https://github.com/nerixyz/c2-logs (or you can attach a debugger manually if you don't trust it). You can run it with `c2-logs chatterino.*.debug=true` (or put a `-o file` in between to output to a file - see the README for more info).

Live channels recheck periodically, so we only need the logs when that happens. The [LiveController](https://github.com/Chatterino/chatterino2/blob/248cd46eb7cc3954b6cabed1769edf563ef24879/src/controllers/twitch/LiveController.cpp#L94) logs something like `chatterino.twitch.livecontroller: Make {n} requests`.

**Comment by pajlada** [comment]
Could you verify that all of your content preferences are unchecked? https://www.twitch.tv/settings/content-preferences

**Comment by ptkato** [comment]
I have the same problem, some live channels (always the same ones) appear as offline.

> Could you verify that all of your content preferences are unchecked? https://www.twitch.tv/settings/content-preferences

However after enabling everything in my content preferences, one of the problematic channels came back showing as live properly (after I logged in again).
