### ISSUE TITLE
New Warn Feature

### ISSUE THREAD

**Issue by 19Topgun93** [Chatterino/chatterino2#5439]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hello :)

Twitch has a new "Warn" Feature. "Unrecognized command: /warn".

I cannot figure out if I can resolve this issue alone. .warn also not Function.

### OS and Chatterino Version

Chatterino 2.5.1 (commit 248cd46eb) built with Qt 6.7.1 Running on Garuda Linux, kernel: 6.9.3-zen1-1-zen

**Comment by pajlada** [comment]
This is a new Twitch feature, we need to implement the API(s), depending on their scope requirements & availability. There's nothing you can do (short of submitting a PR fixing it in our code)

**Comment by iProdigy** [comment]
for now you can upvote https://twitch.uservoice.com/forums/310213-developers/suggestions/48491402-provide-an-api-to-trigger-the-new-warning-system-t

**Comment by iProdigy** [comment]
endpoint to warn users is now in open beta https://dev.twitch.tv/docs/api/reference/#warn-chat-user
