### ISSUE TITLE
Dragging tab across lines may cause empty space between tabs

### ISSUE THREAD

**Issue by jupjohn** [Chatterino/chatterino2#5450]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

While I haven't found a way to replicate this issue, here's my rough memory of how I caused it:

1. Have multiple lines of tabs
2. Drag the first tab on the second row up into the first row (unsure if it was left or right of the first row's first tab)
3. Maybe drag the tab back down to the second row in the same movement
4. First row's first tab is now pushed out by a tab width???

### Screenshots

God I wish I had the sense to screenshot instead of try to reproduce straight away, but I did not... so here's an artistic rendition of the before & after:

Before:
![image](https://github.com/Chatterino/chatterino2/assets/4962764/f7c61b51-92ab-4c88-8a3d-4deb5cfcad6b)

After:
![image](https://github.com/Chatterino/chatterino2/assets/4962764/fd65c995-62d7-48a4-9fd2-e8bd67aa6dca)

### OS and Chatterino Version

Chatterino 2.5.1 (commit d2316af70) built with Qt 6.7.1 Running on Arch Linux, kernel: 6.9.3-zen1-1-zen

**Comment by 8thony** [comment]
Can reproduce
![chatterino](https://github.com/Chatterino/chatterino2/assets/114905842/1669a30e-f8e3-4b1a-be61-f78c14c40b7f)
Chatterino Nightly 2.5.1 (commit 25284fc7) Qt 6.7.1 Running on Windows 10

**Comment by kornes** [comment]
https://github.com/Chatterino/chatterino2/blob/25284fc7034f143966b98917ff4a31f0e540b1e0/src/widgets/helper/NotebookTab.cpp#L415-L418
early return i added recently seems to be a reason, removing it masks the issue and it works as before. 
Notebook layouting needs some love and refactoring which i dont have time to commit to, so for now suggest to just remove above change.
