### ISSUE TITLE
Links to logs in user info popup

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#546]
Add a shortcut to view the logs of a certain user in the user info popup (could support sites like cbenni, overrustle, etc.).

**Comment by DatGuy1** [comment]
I am working on incorporating cbenni's logviewer. Not sure how to use overrustle though since they have no sort of API endpoint.

**Comment by devolution2409** [comment]
Could access overrustle log in txt format for the selected channel 🙂

**Comment by 23rd** [comment]
Is it still considered not fully implemented?
