### ISSUE TITLE
View previous names of a user in the user info popup

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#547]
asdf

**Comment by DatGuy1** [comment]
I'm working on this using https://twitch-tools.rootonline.de/docs.php

**Comment by gempir** [comment]
Can we close this? Twitch offers no API for this and The referenced API here got taken down for legal reasons. So it's unrealstic that we ever get the data for this.

**Comment by apa420** [comment]
Closed due to twitch restrictions
