### ISSUE TITLE
Channel-specific user info popup actions don't work in special channels

### ISSUE THREAD

**Issue by DatGuy1** [Chatterino/chatterino2#550]

**Comment by pajlada** [comment]
For `/mentions`, I think the message should be able to be linked to the channel, so I can time people out from the split. Same thing with the Search window, if the messages are linked to a channel you can have moderation actions in there

**Comment by fourtf** [comment]
Edited to give a choice between fixing it or removing it.

**Comment by zneix** [comment]
This has been fixed in #2088, but do we care about showing channel actions when opening a usercard from channels such as whispers or mentions? @fourtf what's your input on this?

**Comment by jammehcow** [comment]
Also resolved in #3623, can we close this? I don't see anything else to be implemented.

**Comment by Felanbird** [comment]
Only thing I can think of would be whispers actually appearing in the usercard popup, but I assume that would require a full-on refactor from IRC whispers to pubsub whispers, since channel context in `/whispers` would just be `#jtv`.

**Comment by Mm2PL** [comment]
For `Usercard` button in `/whispers` and `/live`, I think we should just hide the button. I can't see any other things to do in this area.
