### ISSUE TITLE
Chat pauses after alt-tabbing with "Pause while holding a key: Alt" enabled

### ISSUE THREAD

**Issue by 00050** [Chatterino/chatterino2#5502]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I have option `Pause while holding a key: Alt` enabled and when I alt-tab from chatterino to another window my chat pauses.
To resume chat auto-scrolling I have to hover over chat my mouse or focus back to it.

I can't really use any other key out of provided options, alt is my only choice.

### Screenshots

Demo: https://kappa.lol/3eSSZ

### OS and Chatterino Version

Chatterino 2.5.1 (commit eafcb941) built with Qt 6.5.0, MSVC 193833135 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by Mm2PL** [comment]
Can replicate.
