### ISSUE TITLE
Drag and Drop Causing Child Windows to Disappear

### ISSUE THREAD

**Issue by JCRouzer29** [Chatterino/chatterino2#5521]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Opening a search window or pinning open a usercard on a chat behaves as normal until the parent chat is directly moved using the drag and drop system.  After which any and all such windows belonging to that chat will disappear but still exist.  Even if the chat is returned to it's starting position. These windows are all completely inaccessible and will only appear again when trying to move the same chat again, disappearing once dropped into place.

Moving other chats via the drag/drop system does not affect the child windows of other chats.

### Screenshots

https://github.com/user-attachments/assets/0307e3ec-308f-4740-ad4a-72b8a8ffc40a

### OS and Chatterino Version

commit 44abb190 from 2024-07-20 running on Windows 10 version 22H2

**Comment by pajlada** [comment]
I suspect this is related to https://github.com/Chatterino/chatterino2/issues/5432
