### ISSUE TITLE
IRC (beta) PASS gets sent with extra colon

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#5546]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Despite me writing just "test" into the password field, the server receives "PASS :test", instead of "PASS test", I don't think this is the expected behaviour.

![image](https://github.com/user-attachments/assets/a086ddf1-2853-474f-aca4-fe153fbfddec)
![image](https://github.com/user-attachments/assets/560c1d6a-3c58-4e70-ac3a-43a6dd511a94)

![image](https://github.com/user-attachments/assets/570a0dfe-7c7f-4f6e-a837-06df5a993df0)

### OS and Chatterino Version

Chatterino 2.5.1 (commit 7a00ae16 modified) built with Qt 6.5.2, MSVC 193933523 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by Nerixyz** [comment]
> Despite me writing just "test" into the password field, the server receives "PASS :test", instead of "PASS test", I don't think this is the expected behaviour.

This indicates you're parsing IRC messages incorrectly. Both `PASS test` and `PASS :test` are identical (see [Message format in Augmented BNF](https://www.rfc-editor.org/rfc/rfc2812#section-2.3.1)).

> NOTES:
      1) After extracting the parameter list, all parameters are equal
         whether matched by <middle> or <trailing>. <trailing> is just a
         syntactic trick to allow SPACE within the parameter.
