### ISSUE TITLE
Pinned Usercard Child Window Losing Parent Connection on Drag/Drop

### ISSUE THREAD

**Issue by JCRouzer29** [Chatterino/chatterino2#5574]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Upon using drag/drop feature on a chat window, any pinned usercards will become invisible and incapable of interaction.  They will appear visible again upon further movement of the source chat window but only during the process. 

Likely a leftover from #5432 

https://github.com/user-attachments/assets/48717dc0-f93a-4793-af75-6385794cbb84

### OS and Chatterino Version

commit f3cae76a from 2024-08-17 running on Windows 10 version 22H2

**Comment by pajlada** [comment]
This should hopefully be fixed in the latest nightly version. If it doesn't work, let me know here and I'll re-open this issue.

**Comment by JCRouzer29** [comment]
Confirmed it's fixed on the Nightly build with #5578 

Thank you
