### ISSUE TITLE
Clip edit button no longer works (thanks twitch)

### ISSUE THREAD

**Issue by JunkiEDM** [Chatterino/chatterino2#5575]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Recently Twitch overhauled their clip editor, and now the `https://clips.twitch.tv/<slug>/edit` that the "edit in browser" button links to just redirects to `https://clips.twitch.tv/<slug>` without any editor. 
Feel free to close this as out-of-scope if you want since this seems like more of an issue on Twitch's side if they still give `https://clips.twitch.tv/<slug>/edit` links that don't work.

You *could* link to the new editor with `https://clips.twitch.tv/create?broadcastID/vodID=<int>&broadcasterLogin=<username>&offsetSeconds=<int>` but this would result in duplicate clips being made with different slugs when used alongside the API for making a clip.

### Screenshots

https://github.com/user-attachments/assets/150761ec-da4a-4e0d-a752-1c144470b69e

### OS and Chatterino Version

Chatterino Nightly 2.5.1 (commit 1c423b5c) on Windows 11 Version 23H2, kernel: 10.0.22635

**Comment by Felanbird** [comment]
There's an `edit` button on that page you are linked to, which opens the editor, is that not good enough?

**Comment by JunkiEDM** [comment]
> There's an `edit` button on that page you are directed* to, which opens the editor, is that not good enough?

When making a clip you get the last 90 seconds to trim down to a maximum 30 seconds, the edit button only lets you trim the last 30 seconds

**Comment by sando** [comment]
I noticed Twitch brought back `https://clips.twitch.tv/<slug>/edit` page with the old clips editor UI, and it seems to work the same as before.

Can probably close this for this now, and reopen if they decide to break it again.

**Comment by Coldblackice** [comment]
> I noticed Twitch brought back `https://clips.twitch.tv/<slug>/edit` page with the old clips editor UI, and it seems to work the same as before.
> 
> Can probably close this for now, and reopen if they decide to break it again.

Speak of the devil, this just stopped working once again as of yesterday. Curious that it's exactly a year ago this same issue occurred, albeit in the opposite direction.

Now clips taken via Chatterino and opened in the browser editor (appending `/edit` to the URL) can only see the tail 30-seconds of clip, instead of the usual 90-second buffer with rolling selector (to create a max 60-second clip). Clips initiated via Twitch's site player can still access the full 90-sec clip buffer.

Really hoping Twitch doesn't make this permanent, and reverts it again as they did last year. It's super handy being able to clip form inside Chatterino and trim clips later in the website editor, especially during high-action/content segments of streams.

**Comment by CaptainFlint** [comment]
For me clicking the "edit it in browser" link opens a completely black video preview. It's still 90 seconds, but no video is shown or played, the pause/play button does not have any visible effects. So, the clip is created (accessible by the "Copy link to clipboard" link), but I cannot edit it.

A couple of days ago Twitch rolled out the new pause+rewind feature, and along the way moved the clip button from its normal location to where it's nearly impossible to find it (although, some viewers reported that they still see the old interface, without rewind but with the clip button). Maybe, breaking the old clipping interface was also a part of the change.

**Comment by Coldblackice** [comment]
@CaptainFlint 

If you're willing to troubleshoot, when you open a Chatterino-clipped URL in a browser, open browser developer-tools (beforehand), switch to the "Network(ing)" tab, then load the clip/edit URL. Look for "Media" assets in the list of GETs, click on any, and see what the request/response headers were, and any responses (including proximity GQL requests).

My hunch is that this is fixable, given the full 90-sec clip video is still accessible.

**Comment by Coldblackice** [comment]
Would it be possible to update how Chatterino initiates clips in order for them to be editable via browser? Appending the "/edit" no longer works: it loads the usual clip editor with the rolling 90-seconds bar, however no matter the position of timeline sliders, it only is able to use that final 30-second (base) clip.

**Comment by pajlada** [comment]
Feel free to explore this if you'd like yeah, we're open to making changes if things seem changes for everyone
