### ISSUE TITLE
Tooltip does not show anything in usercard

### ISSUE THREAD

**Issue by felyp7** [Chatterino/chatterino2#5577]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The tooltip in the usercard doesn't seem to show anything on newer Qt versions, it works on 5.15.2 and 6.5.0.

### Screenshots

![Screenshot_2](https://github.com/user-attachments/assets/2b7f3eed-bd6e-4805-8e32-20ee9d34ead2)
![Screenshot_3](https://github.com/user-attachments/assets/3e0e4294-3ad5-40d2-becf-14ae53823b55)

### OS and Chatterino Version

Chatterino Nightly 2.5.1 (commit cda8fa2a) built on 2024-08-30 with Qt 6.7.1, MSVC 194134120, Crashpad Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by pajlada** [comment]
Fixed by #5578
