### ISSUE TITLE
Automod "action" messages cause subresub messages to be disabled

### ISSUE THREAD

**Issue by jupjohn** [Chatterino/chatterino2#5589]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When an automod action message is received, the last laid out non-PRIVMSG message will be disabled (greyed out)

### Screenshots

![image](https://github.com/user-attachments/assets/fdccde8e-a2f5-4e1c-b3d6-00e229edfe28)

### OS and Chatterino Version

Chatterino 2.5.1 DEBUG (commit 2afa2271 modified) built with Qt 5.15.15 Running on Arch Linux, kernel: 6.10.8-zen1-1-zen

**Comment by jupjohn** [comment]
This deletion behaviour was originally implemented in #1012. I suspect it was to "delete" (disable) the newly added automod message, but those messages have a defaulted empty message ID so the internal `findMessage` call just finds the last message that didn't have a message ID. That could be anything from another automod message, an emote add event, or a resub to name a few.

The two solutions I see here are:
1. If this was intended to delete the new message (which makes sense because of what message ID it's trying to pass), the `deleteMessage` call can be moved into the `postToThread` callback (tested & works)
2. If we don't care about deleting these messages (leaving them as normal system messages), might as well just drop the delete call

**Comment by iProdigy** [comment]
for option 1, we can rely on the term `id` present in the pubsub payload

**Comment by Nerixyz** [comment]
> I suspect it was to "delete" (disable) the newly added automod message

In my opinion, we shouldn't try to delete any message there (option 2). We don't delete any other automod messages either.

**Comment by pajlada** [comment]
The idea behind the feature is to delete "Block"/"Delete" message iirc
A message comes in to all moderators, and they're given the choice to allow the message or to disallow the message.
If you or another moderator picks allow or disallow, the message prompting you to action should be grayed out.

**Comment by jupjohn** [comment]
Thanks guys,

If the original reason was to just disable the auto mod action messages, I'm happy to make the code match.

**Comment by jupjohn** [comment]
Slight issue with using the ID from the PubSub messages: the `add_permitted_term` message contains a different AutoMod message ID than the `pending` message. It does come through on the `allowed` message, but [we don't handle that message](https://github.com/Chatterino/chatterino2/blob/055f6741b8e38e41b36d296feb0dc5198ce94aee/src/providers/twitch/TwitchIrcServer.cpp#L583) from PubSub.

Given that PubSub is on the way out, I'd say it's not worth fixing this until AutoMod messages are ported to EventSub (which looks to have 100% parity to my untrained eye.) I'll spend tonight figuring out how EventSub works in c2 and see if it's something I feel like putting time into - otherwise this can be shelved until a danker gets around to EventSub.

Example:
```json
[
    {
        "type": "MESSAGE",
        "data": {
            "topic": "automod-queue.82674227.82674227",
            "message": "{\"type\":\"automod_caught_message\",\"data\":{\"id\":\"2fbf6ea3-26cc-4358-a57b-3b606822ac5a\",\"content_classification\":{\"category\":\"swearing\",\"level\":4},\"message\":{\"content\":{\"text\":\"bugger\",\"fragments\":[{\"text\":\"bugger\",\"automod\":{\"topics\":{\"vulgar\":3}}}]},\"id\":\"2fbf6ea3-26cc-4358-a57b-3b606822ac5a\",\"channel_id\":\"82674227\",\"channel_login\":\"jammehge\",\"sender\":{\"user_id\":\"726078183\",\"login\":\"jammeheg\",\"display_name\":\"jammeheg\",\"chat_color\":\"#8A2BE2\"},\"sent_at\":\"2024-10-01T06:40:00.183214834Z\"},\"reason_code\":\"AutoModCaughtMessageReason\",\"resolver_id\":\"\",\"resolver_login\":\"\",\"status\":\"PENDING\",\"caught_message_reason\":{\"reason\":\"AutoModCaughtMessageReason\",\"automod_failure\":{\"category\":\"swearing\",\"level\":4,\"positions_in_message\":[{\"start_pos\":0,\"end_pos\":5}]},\"blocked_term_failure\":{\"contains_private_term\":false,\"terms_found\":null}}}}"
        }
    },
    {
        "type": "MESSAGE",
        "data": {
            "topic": "automod-queue.82674227.82674227",
            "message": "{\"type\":\"automod_caught_message\",\"data\":{\"id\":\"2fbf6ea3-26cc-4358-a57b-3b606822ac5a\",\"content_classification\":{\"category\":\"swearing\",\"level\":4},\"message\":{\"content\":{\"text\":\"bugger\",\"fragments\":[{\"text\":\"bugger\",\"automod\":{\"topics\":{\"vulgar\":3}}}]},\"id\":\"2fbf6ea3-26cc-4358-a57b-3b606822ac5a\",\"channel_id\":\"82674227\",\"channel_login\":\"jammehge\",\"sender\":{\"user_id\":\"726078183\",\"login\":\"jammeheg\",\"display_name\":\"jammeheg\",\"chat_color\":\"#8A2BE2\"},\"sent_at\":\"2024-10-01T06:40:00.183214834Z\"},\"reason_code\":\"\",\"resolver_id\":\"82674227\",\"resolver_login\":\"jammehge\",\"status\":\"ALLOWED\",\"caught_message_reason\":{\"reason\":\"AutoModCaughtMessageReason\",\"automod_failure\":{\"category\":\"swearing\",\"level\":4,\"positions_in_message\":[{\"start_pos\":0,\"end_pos\":5}]},\"blocked_term_failure\":{\"contains_private_term\":false,\"terms_found\":null}}}}"
        }
    },
    {
        "type": "MESSAGE",
        "data": {
            "topic": "chat_moderator_actions.82674227.82674227",
            "message": "{\"type\":\"channel_terms_action\",\"data\":{\"type\":\"add_permitted_term\",\"id\":\"d44b3c6b-4aec-4ebf-a029-bd93165a4e9c\",\"text\":\"bugger\",\"requester_id\":\"82674227\",\"requester_login\":\"jammehge\",\"channel_id\":\"82674227\",\"expires_at\":\"2024-10-01T07:40:58.393080886Z\",\"updated_at\":\"2024-10-01T06:40:58.393080128Z\",\"from_automod\":true}}"
        }
    }
]
```

**Comment by iProdigy** [comment]
See #4962 for eventsub - I can take a stab at adding those pubsub branches if you'd like
