### ISSUE TITLE
Crash if no tab exists

### ISSUE THREAD

**Issue by 8thony** [Chatterino/chatterino2#5636]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Steps to reproduce:
- remove all tabs
- click on desktop or try open settings menu

### Screenshots

![crash](https://github.com/user-attachments/assets/b176d953-9bbe-4100-8351-68e5a64a8785)

### OS and Chatterino Version

Chatterino Nightly 2.5.1 (commit afa8067a) Qt 6.7.1 Running on Windows 10

**Comment by Nerixyz** [comment]
Thank you for reporting this crash!
