### ISSUE TITLE
Sometimes last message disappears on reconnect

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#5681]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

<img width="374" alt="{A1324004-4434-47AE-A58D-3B5794368DA0}" src="https://github.com/user-attachments/assets/f0e04113-9e77-4655-ab21-092d1e1878a2"> 

(left new chatterino opened, right the chatterino that was open during the reconnect)

Sometimes the last message disappears on reconnect, ive had this usually happen when switching vpn servers, but its not happening consistently.

There's probably some check missing to replace only system messages, though I tried to take a look and could not find anything obviously wrong.

### OS and Chatterino Version

Chatterino 2.5.1 (commit 7844a3b9 modified) built with Qt 6.8.0, MSVC 194134123 Running on Windows 11 Version 24H2, kernel: 10.0.26120

(running on my PR, but I've had this happen consistently on stable release and since then on multiple nightly versions)

**Comment by Felanbird** [comment]
Is this just #2804 but it happens with this message too

**Comment by hemirt** [comment]
> Is this just #2804 but it happens with this message too

It does seem like it has the same core problem with the replacing messages thing.
