### ISSUE TITLE
fast message

### ISSUE THREAD

**Issue by zzzzzzaaaaaaaaaaaaeeeeeEE** [Chatterino/chatterino2#5696]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When trying to write messages quickly it gives a bar (You are sending messages too quickly.) Regardless of my role it can be seen on the screenshot as much as not searched in the settings or another solution to the problem and did not find it
![image](https://github.com/user-attachments/assets/2ca16546-bf02-495b-9d1d-6c6c6668ecc7)

### OS and Chatterino Version

2.5.1 (windows)

**Comment by Mm2PL** [comment]
We limit the rate you are allowed to send messages to ten per second in channels where you are mod/vip and to one every 1.1s everywhere else. 
This is intended behavior, if you're trying to send more than ten per second like holding Ctrl+Enter with high repeat rate, the client will inform you.
