### ISSUE TITLE
Whispers appearing in channel

### ISSUE THREAD

**Issue by MorisMandria** [Chatterino/chatterino2#5706]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When receiving a whisper on Twitch, this whisper also appears in every chat for some reason, instead of only in /whispers. Any idea how to fix this issue? :)

### Screenshots

![Schermafbeelding 2024-11-09 211643](https://github.com/user-attachments/assets/80074d66-7dbd-4885-ac14-5c2bba105b0c)

### OS and Chatterino Version

Chatterino 2.5.1 (commit eafcb941) built with Qt 6.5.0, MSVC 193833135 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by Wissididom** [comment]
Have you tried turning off the setting "Show Twitch whsipers inline"?

**Comment by MorisMandria** [comment]
> Have you tried turning off the setting "Show Twitch whsipers inline"?

Really? It was that easy?? 😭 Thanks! <3
