### ISSUE TITLE
Sub badges not showing

### ISSUE THREAD

**Issue by Iceman130** [Chatterino/chatterino2#5712]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Whenever I open Chatterino I get "Failed to load channel badges - OAuth token is missing ". 

I've tried clearing cache, I've reinstalled 2.5.1 multiple times. Now I've tried 2.4.3 which makes me able to see every other badge besides sub badges.

### OS and Chatterino Version

Chatterino 2.4.3 (commit 379cc576) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.22631

**Comment by Wissididom** [comment]
Just login. OAuth token missing means that you are not logged in. Twitch made badges require authentication

**Comment by Iceman130** [comment]
When im using 2.5.1 instead of 2.4.3 while logged in, I still cant see any badges, it will only show the Chatterino Supporter badge and the FFZ Supporter badge
