### ISSUE TITLE
AutoMod Allow/Deny message spam

### ISSUE THREAD

**Issue by devilinherdemeanour** [Chatterino/chatterino2#5714]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When AutoMod detects a message from the user that is not sent (due to conflict or something else), the pop that Allows/Denies sending the messages does not disappear after click either of the options. As a result the message from the user can be spammed infinite times and also there is no delay on posting the message. It is more of a Twitch bug but, as mister Paj said, it would be good to keep track of it in Katterino! thank you for your attention

### OS and Chatterino Version

Chatterino 2.5.1 (commit fb35be0d) built with Qt 6.4.3 Running on macOS 15.0, kernel: 24.0.0

**Comment by pajlada** [comment]
Looks like this has been fixed by Twitch, so I'll close this.
