### ISSUE TITLE
Failed to fetch 7TV, BetterTTV and FrankerFaceZ emotes (Error: TimeoutError)

### ISSUE THREAD

**Issue by kamild1996** [Chatterino/chatterino2#5753]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

After reinstalling Windows and Chatterino, any of the custom emotes don't load because of the TimeoutError. When using browser extensions such as BetterTTV, all emotes incl. 7TV and FFZ ones do work.

### Screenshots

![image](https://github.com/user-attachments/assets/39e91c8a-1319-46e3-9b60-c8189a5c17dc)

### OS and Chatterino Version

Chatterino 2.5.1 (commit eafcb941) on Windows 11 Version 24H2

**Comment by pajlada** [comment]
Can you test using the latest nightly build from https://github.com/Chatterino/chatterino2/releases/tag/nightly-build to see if that fixes your issue?
https://wiki.chatterino.com/Help/#what-is-nightly-and-how-to-use-install-it has some info about what nightly is

**Comment by kamild1996** [comment]
On the latest nightly (commit [3c2a4222]), the issue seems to present differently - I see no errors on chat, but emotes are instead blank:
![image](https://github.com/user-attachments/assets/f1289073-2354-4dfb-b7d1-d56977056f7d)

**Comment by pajlada** [comment]
Could you try clearing the cache?
Open settings (CTRL+P), search for "clear cache", click the "Clear Cache" button, restart Chatterino

**Comment by kamild1996** [comment]
> Could you try clearing the cache? Open settings (CTRL+P), search for "clear cache", click the "Clear Cache" button, restart Chatterino

Just tried it, unfortunately it did not change anything.

**Comment by pajlada** [comment]
If you press F10 it will open a debug window with some information about network requests & images. Can you copy the output from that here?

**Comment by kamild1996** [comment]
> If you press F10 it will open a debug window with some information about network requests & images. Can you copy the output from that here?

```BaseWindow: 4
LiveUpdates failed connections: 10
LiveUpdates subscription backlog: 5
NetworkData: 63
PubSub connections: 1
PubSub topic backlog: 0
PubSub topic listening: 2
PubSub topic pending listens: 0
http request started: 82
http request success: 19
image bytes: 16.00 KiB
image bytes (ever loaded): 16.00 KiB
image bytes (ever unloaded): 0 bytes
images: 6,758
loaded images: 1
message drawing buffers: 12
message elements: 16,512
message layout: 1,000
message layout elements: 4,644
messages: 1,001
```

**Comment by pajlada** [comment]
It looks to me like you have some network requests that have been fired and are never succeeding. Your live updates connection seems to be failing too - are you using some sort of firewall that might block non-browser traffic? Or maybe some exotic kind of networking (e.g. starlink)?

**Comment by kamild1996** [comment]
> It looks to me like you have some network requests that have been fired and are never succeeding. Your live updates connection seems to be failing too - are you using some sort of firewall that might block non-browser traffic? Or maybe some exotic kind of networking (e.g. starlink)?

I only have Windows Firewall enabled. I have added a rule for Chatterino to allow all traffic just in case. I have a Pi-hole adblocker running, I tried pausing protection for a moment. I also have a third party antivirus (ESET NOD32 Antivirus), tried adding Chatterino to exclusions and pausing protection. None of it helped, and none of it was needed before reinstalling Windows.

My network is probably standard, using an LTE internet connection.

**Comment by Nerixyz** [comment]
We might have too many requests in flight at once (we don't limit them). I notice this in local debug builds too. When opening the emote popup without a cache will take about a minute until all requests complete (for me). We might want to add some limiter on that - maybe per origin or even globally.

**Comment by Linaryx** [comment]
maybe block by russian Federal Service for Supervision in the Sphere of Communications ? (7tv has been banned on russia)

**Comment by kamild1996** [comment]
> maybe block by russian Federal Service for Supervision in the Sphere of Communications ? (7tv has been banned on russia)

No, I'm from Poland, and emotes from all three custom emote providers work fine outside of Chatterino for me

**Comment by Linaryx** [comment]
> No, I'm from Poland, and emotes from all three custom emote providers work fine outside of Chatterino for me

lol

**Comment by kamild1996** [comment]
I don't know what happened, but today after not using Chatterino ever since reporting this issue, emotes today work just fine on the latest stable release of Chatterino. 🤷

**Comment by pajlada** [comment]
> I don't know what happened, but today after not using Chatterino ever since reporting this issue, emotes today work just fine on the latest stable release of Chatterino. 🤷

Are you using 2.5.2-beta.1 @kamild1996?

**Comment by pajlada** [comment]
Glad it's fixed!
