### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by stormtrooperdan11** [Chatterino/chatterino2#5767]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

update today got flagged as a drop trojan by F-Secure total it also flagged another file that I use regularly and recently downloaded as one. I am guessing it's a false positive.

### Screenshots

![Screenshot 2024-12-15 144829](https://github.com/user-attachments/assets/656c5eef-f5c2-47c8-9da0-cfa3ac5e164f)

### OS and Chatterino Version

unable to access but just updated today when update was showing

**Comment by pajlada** [comment]
Hey, yeah generally anti-virus software takes some time for software to be "known" and trusted. The `Update.exe` is the in-progress update file used during an upgrade like this.
What you can do is upload the new `chatterino.exe` or any of the other files in your chatterino folder onto VirusTotal.

For more context, see https://github.com/Chatterino/chatterino2/issues/487
