### ISSUE TITLE
Chatterino pastes link to temp file location when copying image from browser

### ISSUE THREAD

**Issue by TranRed** [Chatterino/chatterino2#635]
If you accidently select "copy image" instead of "copy file location" in firefox, chatterino 2 will paste the temp location of the image. It should post nothing. (like c1 does)

![2018-07-21_15-07-04](https://user-images.githubusercontent.com/16636423/43035973-46b08244-8cf8-11e8-8fea-14838a19ba65.png)

![grafik](https://user-images.githubusercontent.com/16636423/43035980-721507de-8cf8-11e8-9fec-22a284882e8a.png)

**Comment by fourtf** [comment]
Currywurst mit Brötchen ![3](https://user-images.githubusercontent.com/6320036/43078516-00b233e8-8e8b-11e8-8f06-2b6810fa2a8a.png)

**Comment by TranRed** [comment]
idk what I'm doing in github rn pajaL

**Comment by pajlada** [comment]
Fixed by #1096
