### ISSUE TITLE
make a /notifications <username> tab

### ISSUE THREAD

**Issue by ThePridestalker** [Chatterino/chatterino2#654]
make a /notifications \<username\> tab that shows only the subs and maybe cheers too

**Comment by alazymeme** [comment]
Related to https://github.com/Chatterino/chatterino2/issues/518

**Comment by Mm2PL** [comment]
They are similar, i wouldn't call this a dup of the other. Maybe we could combine them into one bigger feature.
This one focuses on mentions of an account, while the other mentions in a channel.

**Comment by Mm2PL** [comment]
Semi doable with #1748 `flags.sub_message && (message.content contains "Cheer")`
