### ISSUE TITLE
[Request] Allow directory wildcards like %USERPROFILE% in Windows for Cache dir

### ISSUE THREAD

**Issue by Evanito** [Chatterino/chatterino2#681]
I would like to set my cache folder to `%USERPROFILE%/AppData/Local/Temp/ChatterinoCache` because I use the portable feature to run on multiple machines via a Google Drive Sync.

Currently just creates a subfolder named %USERPROFILE%

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
