### ISSUE TITLE
Better user cards

### ISSUE THREAD

**Issue by seriousm4x** [Chatterino/chatterino2#683]
* add support to make the buttons on the user card customizable https://imgur.com/a/TXgcz5w
* show previous messages inside the user card from that user (like in bttv) https://imgur.com/a/81A1CCQ

**Comment by Chronophylos** [comment]
you can use `![](link_to_image)` to embed an image

**Comment by fourtf** [comment]
customization of timeout buttons and previous messages is being developed here: https://github.com/Chatterino/chatterino2/pull/1238
