### ISSUE TITLE
Add variables for commands like counting or random message

### ISSUE THREAD

**Issue by derLesh** [Chatterino/chatterino2#688]
The current command system only allows {1+} etc. 
It would be better if there would be more variables for counting or random messages. Some variables like Nightbot and other bots offer.

**Comment by ThePridestalker** [comment]
This is a chat client not a bot.

**Comment by pajlada** [comment]
I could see the use in similar features at least allowing things like `{channel}` to be able to make context-based commands

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
