### ISSUE TITLE
Loaded logs are not populated with FFZ emotes if logs load before FFZ emotes

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#727]
This issue is probably related to #709. Loading times for FFZ emotes seem to vary greatly depending on factors we seem to have no influence on. In some instances FFZ emotes can load very slowly, causing them to be loaded _after_ old logs for a channel are loaded in. In that instance, the loaded logs will not be populated with FFZ emotes.

One solution would either to re-run emote replacement on already present emotes the moment FFZ loads or to have the logs wait until all emotes are loaded. (preferrably option no. 1 for the faster loading)

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/61123210-1c420480-a4e7-11e9-950e-7e03c47e232a.png)
Looks like the loading of custom mod icons in recent message history is also not working

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
