### ISSUE TITLE
Can't copy single surrogate pair unicode character

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#730]
Single unicode charater with codepoint of > 0xFFFF cannot be copied from chat if it's surrounded by other charaters, instead the high surrogate part is copied.

Steps to reproduce:

1. Post "A􁈴A" (\U00000041\U00101234\U00000041)
2. Try to copy 2nd (middle) character
3. \U0000DBC4 is copied instead.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

**Comment by TETYYS** [comment]
is it a Qt bug?

**Comment by apa420** [comment]
Probably
