### ISSUE TITLE
Customize mod icons

### ISSUE THREAD

**Issue by seriousm4x** [Chatterino/chatterino2#737]
make the mod buttons customizable. give the user an icon set to pick a custom icon.
timout buttons look rather ugly. ban buttons look good.
![2018-09-28 22_49_18](https://user-images.githubusercontent.com/23456686/46232826-c8f43080-c370-11e8-8839-1f34dc69a77c.png)

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

**Comment by michaelowens** [comment]
I'd like to ask for this to be reconsidered. With timeouts being able to have a reason it can be useful to be able to differentiate between timeouts of the same duration.

It could be nice to have something similar to FFZ, where you can choose an icon override from e.g. FontAwesome. If no icon override was entered it could fallback to the current icons. It makes it more clear what we would be timing out for, as can be seen in the following screenshots:

Chatterino:
![Chatterino](https://i.imgur.com/yU1oGRk.png)

FFZ:
![FFZ](https://i.imgur.com/kA6mNNr.png)

I don't know if this is any good, but could be of interest:
https://github.com/gamecreature/QtAwesome/tree/fontawesome-5

Thank you for your time!

**Comment by Mm2PL** [comment]
We have added support for custom themes, we should at least be able to change the color of the moderation buttons separately from the system message text color. It would also be nice if themes could provide icon packs or recolor existing icons. Although I'd like to see users being able to pick the icon themselves.
