### ISSUE TITLE
"smoothScrollingNewMessages" hides initial messages in channels

### ISSUE THREAD

**Issue by ThePridestalker** [Chatterino/chatterino2#779]
If you start chatterino but you don't focus the tab /mentions, you get a highlight in that tab but you don't get the messages there until you focus it first.

To test, open chatterino, get pinged by a bot or something and see the /mentions tab highlight.
Click it and it has no message.

**Comment by pajlada** [comment]
You'll need to be more specific about how to set up the test. I tried with 2 separate tabs. one with channel pajlada, and one with only a /mentions
I started chatterino with the pajlada tab active, let someone type my name, then I switched to the /mentions tab and the message was there

**Comment by ThePridestalker** [comment]
I was using 4270c402fb6ca3e81d5f685ad2f36b90414ede24 in the video

**Comment by ThePridestalker** [comment]
Removing this line in my settings.json fixes it:

"smoothScrollingNewMessages": true

**Comment by wigoor** [comment]
still exists in Chatterino Nightly 2.1.5 (commit 367b1970f, 22.09.2019)
quick fix is to disable Smooth scrolling on new messages

**Comment by pajlada** [comment]
Brought up again in #1617 so it's definitely still relevant

**Comment by zneix** [comment]
Yes, I wanted to post that proof on #1617 but I'll do that here instead https://i.nuuls.com/kepuX.mp4
