### ISSUE TITLE
Emotes dosent load on Reconnect if started offline

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#780]
Channel/global/bttv/ffz emotes does not reload with the Reconnect button if you start the client when you are offline, happens to me about 50% of my days :(((
https://i.imgur.com/AvIkRW7.png

The reload channel emotes works to get back channel specific ones but not the global + sub emotes.
https://i.imgur.com/DT433XX.gifv

Not a mayor thing since its fixed by a restart of chatterino.

c872db3-1
win10

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
