### ISSUE TITLE
REQUEST: Add the "someone went live" notification to /mentions

### ISSUE THREAD

**Issue by ThePridestalker** [Chatterino/chatterino2#786]
By default, if you have the windows toasts disable and the other types of alert (the sound and the highlight in the taskbar) active, you will hear the sound but will have no idea which stream is live. If the text alert appears in the /mentions tab, its a 100% sure place to look up.

**Comment by 23rd** [comment]
I think it is better to create new type of tab, for example "/online".

**Comment by TranRed** [comment]
Is this solved with the new live indicator?

**Comment by ThePridestalker** [comment]
No because you can have 1 tab with more than 1 split and the tab will have the dot if any of the streams in the splits is live.

**Comment by Mm2PL** [comment]
How about we make a tab called /notifications or /pings where all pings/events are combined?

**Comment by fourtf** [comment]
doesn't make sense in mentions, other solutions have been suggested in other issues
