### ISSUE TITLE
Upload images through chatterino2

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#79]

**Comment by pajlada** [comment]
This should probably be made through the QTextEdit if an image is pasted into it

**Comment by gempir** [comment]
What exactly is the goal of this? Drop and image into chatterino and chatterino will upload it to some image hosting site (imgur, ...) and paste the url?

**Comment by pajlada** [comment]
That was the idea yeah, to make image/file uploading/sharing easier.
