### ISSUE TITLE
Show "last message read marker" in scrollbar

### ISSUE THREAD

**Issue by ThePridestalker** [Chatterino/chatterino2#793]
That line was red and showed in the scrollbar in chaterino1 but in chaterino2 it is grey, doesnt show up in the scrollbar and hard to see if the chat gets scrolled up a lot.

fourtf edit (ty @hemirt):
- [x] the line should reset when switching tabs
- [ ] the line should be shown in the scrollbar
- [x] customizable color

**Comment by ThePridestalker** [comment]
Also, in chatterino1 the line is invisible when it resets and only displayed when the window loses focus, but in chatterino 2 it is visible all the time and changing window doesnt reset it, you have to put chatterino2 in the background to make the line reset.

**Comment by ThePridestalker** [comment]
left is chatterino1 right is chatterino2.
chatterino1: 
you change tab and the red line goes to the bottom. (so much to the bottom that it is hidden)
![demo](https://i.nuuls.com/fzDN3.gif)
chatterino2:
you change tab and the line doesnt reset, even if new people come and type you still have the grey line where it was before. It only gets back to the bottom if the entire chatterino2, not the tab, loses focus.
![demo](https://i.nuuls.com/Aebn_.gif)

**Comment by hemirt** [comment]
I think this sums it up
- [ ] the line should reset when switching tabs
- [ ] the line should be shown in the scrollbar
- [ ] customizable color

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

**Comment by zneix** [comment]
> 
> 
> This issue is out of scope of the Chatterino project.

It was a thing in Chatterino1, so is it hard to "reimplelent" in ch2? I'd reopen and add backlog instead.
