### ISSUE TITLE
Chatterino sometimes crashes when clicking 'mark all whispers as read'

### ISSUE THREAD

**Issue by DatGuy1** [Chatterino/chatterino2#794]
Occasionally when clicking the 'mark all whispers as read' button in the whispers tab chatterino crashes.

Error message: https://i.nuuls.com/ungzy.png
Button location: https://i.nuuls.com/10YsZ.png

**Comment by alazymeme** [comment]
@DatGuy1 Are you able to reproduce this in the latest nightly?

**Comment by pajlada** [comment]
This was fixed a while back, discussion was had in a duplicate issue #1550
