### ISSUE TITLE
Open in streamlink not working?

### ISSUE THREAD

**Issue by ghost** [Chatterino/chatterino2#860]
Windows 7 nightly-build d3003c1-1

When I click open in streamlink and select quality nothing happens. 
Changing to 'Source' or anything else in settings doesn't help. 
Changing path doesn't help. 
Different channels doesn't help.

Streamlink works fine on it's own and with streamlink-twitch-gui.

**Comment by pajlada** [comment]
What version of Streamlink do you have? `streamlink --version`

**Comment by walkingpc** [comment]
streamlink 0.14.2

**Comment by pajlada** [comment]
ok I have a fresh installation of streamlink, so version 0.14.2.
I have it installed in a custom path, `C:\dev\bin\streamlink`
In Chatterino, I have set the custom streamlink path to `C:\dev\bin\streamlink\bin`
I have VLC installed, and no streamlinkrc, and it works for me.
If you don't have VLC installed, I think you might need to configure your default player in streamlinkrc

Does typing `streamlink twitch.tv/monstercat best` in a terminal work for you? if so, what video player does it open?

**Comment by walkingpc** [comment]
https://pastebin.com/raw/5sz53yLt

**Comment by apa420** [comment]
is this still an issue?

**Comment by bapsaru** [comment]
op here, had to make a new account, yes this is still happening.

i'm on a new windows 7 install and still the same issue. chatterino titlebar says b7372c9-
streamlink and mpv are in PATH

using this streamlink https://github.com/streamlink/streamlink/issues/2402 but issues is present on default streamlink aswell 

using streamlink in cmd or streamlink-twitch-gui works as expected

attached config files in zip
[conf.zip](https://github.com/Chatterino/chatterino2/files/3305836/conf.zip)

let me know if more info is needed

**Comment by pajlada** [comment]
Looks to still be an issue, will close this one in favour of the new one made today #1114
