### ISSUE TITLE
Cannot load or save commands if path to chatterino2 directory contains scandinavian characters

### ISSUE THREAD

**Issue by Leppunen** [Chatterino/chatterino2#866]
commands.json is not loaded nor saved if directory path to chatterino2's config folder contains scandinavian letters. My username has the letter Ä in it and that seems to cause the problem.

Tried moving chatterino2 configs to it's own folder and the issue is gone.

**Comment by pajlada** [comment]
This bug is related to my settings library, so I've assigned myself.

**Comment by pajlada** [comment]
Being worked on in https://github.com/pajlada/settings/tree/pajlada-use-filesystem-path

**Comment by fourtf** [comment]
is this fixed?
