### ISSUE TITLE
Seperate "Hide input box when empty" setting for /mentions and /whispers

### ISSUE THREAD

**Issue by cineafx** [Chatterino/chatterino2#868]
It is rarely needed to type in the /mentions and /whispers split (except maybe replying to whispers).
I know you can just disable it for all input boxes but some people like having the empty input box in _normal_ chats.
Quite a few people have /mentions as a seperate split in their chats.
![image](https://user-images.githubusercontent.com/7873738/48195199-412a1a80-e34f-11e8-9203-7e2f0acefb9e.png)

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
