### ISSUE TITLE
Support Emoji 11.0

### ISSUE THREAD

**Issue by LeaPhant** [Chatterino/chatterino2#869]
Emoji 11.0 has been released in June 2018 and is supported by Apple, Google, Twitter and EmojiOne.
Would be nice to have the all the new emoji that have been added! 🐘

**Comment by pajlada** [comment]
One issue with supporting the new emoji data is that the emoji data provider we rely on has been forced to remove support for EmojiOne

https://github.com/iamcal/emoji-data

so it's unfortunately not as easy as just running a script

This is definitely something we would want to be able to keep up with though, so maybe it's just a matter of making a smarter script

**Comment by TranRed** [comment]
They also haven an issue over there, maybe we can have an eye on that.

https://github.com/iamcal/emoji-data/issues/145

**Comment by savabozo** [comment]
https://github.com/iamcal/emoji-data/issues/145#issuecomment-493588183
avaliable on master

**Comment by alazymeme** [comment]
![jif](https://cdn.betterttv.net/emote/5fedbfca9d7d952e4059e40c/1x) @zneix

**Comment by pajlada** [comment]
Fixed in 6b0ce396d6f8d727aa641273d00e1013b86c2f3a (#1555 )
