### ISSUE TITLE
Show timeout timer

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#870]
If you're timed out, show timeout timer in the input box, preferably next to the label of current character count.

This could also include a slowmode timer.

**Comment by gempir** [comment]
Insperation for timer 
![image](https://user-images.githubusercontent.com/9765622/86518421-4f854e00-be32-11ea-81df-315ec4430de7.png)

**Comment by gempir** [comment]
Would be interesting how this could look when hiding input box. Personally I think it might be cool to just have a progress bar then at the bottom of the chat.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

**Comment by x9136** [comment]
Yo!

There are chats in which timeouts are given no longer than half an hour. Also, there are chats where you can fight with each other through the bots and the loser gets a timeout for 10-20 mins. It would be useful to be notified when you are allowed to send messages after a timeout. The notifications should work the same way as when your nickname is highlighted.

I might consider such a feature to be out of scope of the Chatterino as well?
