### ISSUE TITLE
/version command

### ISSUE THREAD

**Issue by pajlada** [Chatterino/chatterino2#874]
Built-in command to print the version of chatterino you're using.
Not sure whether it should print a system-message, or actually print the message in chat.

Example output would be something like:
`Chatterino 2.0.4 Nightly (dcda714), built January 3rd 2015 16:05:21`

**Comment by fourtf** [comment]
This should only happen if a lot more features (such as settings) are exposed through text commands. Just having this one command would feel out of place.

**Comment by TranRed** [comment]
I would expect to see this information in the "about" tab.

**Comment by pajlada** [comment]
Version information is available in the About tab now, which is fine by me :ok_hand:
