### ISSUE TITLE
Channels not loading correctly

### ISSUE THREAD

**Issue by Chronophylos** [Chatterino/chatterino2#876]
Sometimes messages don't get displayed but the tab get highlighted, as if there is a new message.
I can fix this by opening every tab and manually reconnecting after doing this.

Version: c11d151

**Comment by hemirt** [comment]
Can you try on **latest build** and provide few pictures? I haven't had any problems with channel messages not being displayed while actually being connected to the channel and the tab being highlighted by messagesm. Does it happen to every single channel/split/tab?

**Comment by Chronophylos** [comment]
![](https://i.imgur.com/XbfmOYi.png) it looks like this; no connected message no hosting message.

the latest build has the same problem.

all these channels dont have a lot of traffic.

> Btw, the tab should get highlighted on any message from any splits inside, arent there other splits getting messages?

no i can't see any messages.

**Comment by alazymeme** [comment]
Is this still bugged on the latest nightly? https://github.com/Chatterino/chatterino2/releases/tag/nightly-build

**Comment by Chronophylos** [comment]
Tested on 6d5ba0c442681fb30afd01f787a10cd3922c10aa: I still don't get a connect message on every channel

**Comment by alazymeme** [comment]
> Tested on [6d5ba0c](https://github.com/Chatterino/chatterino2/commit/6d5ba0c442681fb30afd01f787a10cd3922c10aa): I still don't get a connect message on every channel

Do you have another PC/internet connection to test this on? I haven't seen this from anyone else. Perhaps try changing DNS? Do you have more than 100 channels open?

**Comment by Chronophylos** [comment]
I can see new messages and everything seems to be working, except the missing `connected` message.

**Comment by fourtf** [comment]
I'll close this since another issue is tracking the same bug
