### ISSUE TITLE
Invalid behavior when selecting characters/emotes

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#879]
When selecting characters in chatterino, the character that user starts selecting text with is always discarded. OS behavior (at least on Windows) is to include the character that user starts selecting from if the cursor is on the >50% part of width of the character. 

![OS behavior](https://user-images.githubusercontent.com/3091645/48636813-a081cd80-e9d4-11e8-8396-d049d9f75d5d.gif)

![chatterino behavior](https://user-images.githubusercontent.com/3091645/48636887-d030d580-e9d4-11e8-9047-ad9bd3d6546d.gif)

Emotes, on other hand are always included in the selection, no matter if they're highlighted visually or not.

![2018-11-16_19-24-09](https://user-images.githubusercontent.com/3091645/48637066-48979680-e9d5-11e8-998c-1f2edec8776a.gif)

Also, a space is always added at the end.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.

**Comment by TETYYS** [comment]
what about space always being there at the end?
