### ISSUE TITLE
Text selection causes full core usage

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#882]
![See gif](https://user-images.githubusercontent.com/3091645/48723873-7e848700-ec30-11e8-9d2b-f2511b40efe0.gif)

**Comment by wigoor** [comment]
Unable to reproduce in latest nightly 9472283-1 on Windows10 (v1803)
![](https://i.imgur.com/ws2qbkM.gif)

**Comment by TETYYS** [comment]
I'm on 90309d00, which is one commit away which is related to tooltips, so it probably doesn't matter much, maybe it's related to some kind of setting?

**Comment by Chronophylos** [comment]
all I noticed is a small increase in CPU usage
![](https://i.imgur.com/gTUaJu9.gif)
3 small spikes ~4% more usage compared to normal
![](https://i.imgur.com/FU8pqoa.png)

**Comment by gapbl4** [comment]
@Chronophylos I think he meant single core usage, so depending on how many cores/threads you have, you'll see different numbers

**Comment by TETYYS** [comment]
cannot reproduce on Chatterino Nightly 2.1.5 (commit 6111985b7, 26.12.2019)
