### ISSUE TITLE
The invisible character is not being added for identical messages if user performs a whisper in-between

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#884]

**Comment by apa420** [comment]
I can't replicate

**Comment by TETYYS** [comment]
Looks like it's fixed

**Comment by hemirt** [comment]
Seems fixed

**Comment by RAnders00** [comment]
:NaM:

**Comment by TETYYS** [comment]
It works normally when you write:

```
asd
/w testtest_ asd
asd
```

But if you have a command that performs a whisper, it doesn't:
```
asd
/dowhisper
asd
> Your message was not sent because it is identical to the previous one you sent, less than 30 seconds ago. 
```

**Comment by RAnders00** [comment]
As a suggestion: Chatterino should not consider "sent" messages for this feature, but rather messages it sees from its own account in chat. Consider this example:

    > send message: "asd"
    < message arrives in chat: "asd"
    [ fast chat buffers (pauses) ]
    > send message: "asd" (chatterino appends the invisible character now)
    (no message arrives in chat)
    [ fast chat unpauses ]
    > send message: "asd" (chatterino *does not* append the invisible character now)
    < "Your message was not sent because it is identical to the previous one you sent, less than 30 seconds ago."

If chatterino would simply save the last message received by a user (per-channel), the issue described by TETYYS (above) and this issue additionally would be fixed.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
