### ISSUE TITLE
Empty tab appears 'randomly' when opening the app

### ISSUE THREAD

**Issue by gapbl4** [Chatterino/chatterino2#886]
Sometimes when I open chatterino I get an new empty tab at the beginning of tab bar (top left)
It started happening about a week ago or so

**Comment by pphop** [comment]
This happens to me too, but cant reproduce it by closing/opening chatterino, seems to appear after shutting down pc with chatterino open on win 10. Also whenever that happens the window moves 1 pixel to the right.

**Comment by apa420** [comment]
I also get this issue on win 8.1

**Comment by fourtf** [comment]
I attempted to fix this. However, I don't get the error myself.

Closing this for now.
