### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by maith1** [Chatterino/chatterino2#889]
Every time I start Chatterino 2 Beta, it opens a window that is pure white and then a few seconds later, it crashes entirely. Starting it up as admin results in the same thing. I also tried reinstalling it and the same thing happened.

**Comment by hemirt** [comment]
try deleting or moving outside %appdata%/chatterino2 folder (I believe if you have used chatterino 1, there might also be a "chatterino" folder which is used by ch1, but you can try deleting or moving outside this too)

**Comment by Seqularise** [comment]
I`m experiencing this problem right now, how can i provide any logs? 
Terminal output gives me this, seems like nothing interesting
arch, latest chatterino2-git package
> [seqularise@seqularise ~]$ chatterino 
> init UpdateManager
> Using Wayland-EGL
> Using the 'xdg-shell-v6' shell integration
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> init WindowManager
> init TwitchServer
> init PubSub
> 12:04:04.866 [TwitchChannel:gleborg] Opened
> 12:04:04.866 [FFZEmotes] Reload FFZ Channel Emotes for channel gleborg
> 
> QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://tmi.twitch.tv/group/user/gleborg/chatters")
> 12:04:04.872 [TwitchChannel:dotacapitalist] Opened
> 12:04:04.872 [FFZEmotes] Reload FFZ Channel Emotes for channel dotacapitalist
> 
> 12:04:04.873 Added user seqularise
> 12:04:04.873 [AccountManager:currentUsernameChanged] User successfully updated to seqularise
> 12:04:04.873 Loading Twitch emotes for user seqularise
> 12:04:04.873 Connection open!
> 12:04:04.873 tryListen with 0 clients
> 12:04:04.873 Added to the back of the queue
> logging in as "seqularise"
> logging in as "seqularise"
> 12:04:04.873 Start pubsub manager thread
> [2018-12-16 12:04:05] [connect] Successful connection
> Segmentation fault (core dumped)
>

**Comment by fourtf** [comment]
I would imagine that this doesn't happen anymore
