### ISSUE TITLE
Ability to prevent certain emotes or username from going through auto tab

### ISSUE THREAD

**Issue by nitrousGranola** [Chatterino/chatterino2#894]
Ex: Blacklist or lower priority of 'TransgenderPride' on auto tab so I can auto tab 'TranRed' first.

Or the ability to move a certain emote or username to the top of tab priority.

**Comment by Evanito** [comment]
Just use @ dude

**Comment by alazymeme** [comment]
Would you say this was fixed in https://github.com/Chatterino/chatterino2/commit/82354327e5f7dd075b2aec98c9dbdad9cd7390df ?

**Comment by apa420** [comment]
Custom priority list is still a good addition.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
