### ISSUE TITLE
Strawpoll

### ISSUE THREAD

**Issue by Sealthrux** [Chatterino/chatterino2#895]
So i have an idea. Twitch currently creates a little window at the top of the chat when the broadcaster posts a strawpool link. Maybe you could try to implement this into chatterino ?

**Comment by alazymeme** [comment]
Twitch has a new polls feature, perhaps we could look at implementing this instead?

**Comment by apa420** [comment]
Twitch has no api for this currently.

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
