### ISSUE TITLE
ffz emotes that are higher than wide will get cut off

### ISSUE THREAD

**Issue by cineafx** [Chatterino/chatterino2#897]
Seems to be unaffected by emote size or UI scale
![image](https://user-images.githubusercontent.com/7873738/49506262-ee744d80-f87d-11e8-9b4e-912e7d1af763.png)

**Comment by TranRed** [comment]
solved in #1003 (?)

They still kinda overlap
![grafik](https://user-images.githubusercontent.com/16636423/57023735-1ac8a600-6c33-11e9-95f9-69f5f31f98b8.png)

**Comment by fourtf** [comment]
this was fixed
