### ISSUE TITLE
Autocomplete global and subscribers emotes in /whispers tab.

### ISSUE THREAD

**Issue by gapbl4** [Chatterino/chatterino2#900]
Would be nice to be able to autocomplete sub and global emotes in whispers tab ![1](https://user-images.githubusercontent.com/14076068/49685928-0823c800-fafe-11e8-8e55-19570ec0bd05.png)

**Comment by TranRed** [comment]
Update: this does work with the : feature already, but not with normal autocompletion

**Comment by zneix** [comment]
Accidentally stumbled upon code responsible for this and I've found a very easy way to fix it. Honestly just surprised that nobody found this before.
