### ISSUE TITLE
hide settings button and account button settings missing

### ISSUE THREAD

**Issue by Ckath** [Chatterino/chatterino2#907]
There used to be a 'hide pref button' and 'hide account button' or something along those lines in the settings, I know the functionality is still there because on the client I have set it to hide they are still hidden. not sure if this is intentional and either the functionality should be gone or the settings should exist.
![image](https://user-images.githubusercontent.com/15038414/50053789-2495b500-013b-11e9-916a-8ec366235a68.png)
![image](https://user-images.githubusercontent.com/15038414/50053784-16e02f80-013b-11e9-860d-9573763b091e.png)

Either way I'm pretty sure its not supposed to be the way it is now

**Comment by apa420** [comment]
@fourtf close issue :)

**Comment by Ckath** [comment]
2slow
