### ISSUE TITLE
Switching accounts causes messages to be lost during reconnect

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#915]
When reconnecting, there is a short pause where chatterino is not connected to IRC. Messages that are sent during this time are missed by chatterino. Maybe chatterino could keep the old connection alive (maybe for a maximum of 5-10 seconds) OR until the new one is connected and has received the first message? Or maybe consult the endpoint for getting the last messages in a chat like it does on the initial connect, and merge the chat messages with the existing ones.

**Comment by TETYYS** [comment]
I think account connections should be kept alive for a minute or two of no usage, this would prevent rapid reconnections if user wants to switch between two accounts multiple times.
