### ISSUE TITLE
Some person emojis will append sex symbols after the emoji 

### ISSUE THREAD

**Issue by nitrousGranola** [Chatterino/chatterino2#916]
https://i.nuuls.com/a8pIp.mp4

for example, using `:walking_tone2:` would show the `:male_sign:` next to the emoji after it was sent as well with some other ones like `:person_in_lotus_position:`, although when I copy and paste the emoji from a website straight into the text box, I can't get the signs to append at all, even if I type the emojis out, but copying them from chatternio copies both the emoji and sex symbol. Doesn't seem to matter weather or not the emoji contains `man` or `woman` in the name, although that is how this issue was first noticed, with `:woman_walking_toneX:`, though note how the female image of `:shrug_tone1:` and `:person_in_lotus_position:` has `:female_sign:` next to it, although `:person_in_lotus_position_tone2:` (not shown) which is also female has `:male_sign:` next to it.

**Comment by fourtf** [comment]
I'll leave this open instead since we can't fix it for these manually. https://github.com/Chatterino/chatterino2/issues/869

**Comment by pajlada** [comment]
Our emoji set has been updated, however, a lot of these issues still persist due to the following issue: https://github.com/twitchdev/issues/issues/307
