### ISSUE TITLE
Selected Users Category

### ISSUE THREAD

**Issue by EdenOfTheWest** [Chatterino/chatterino2#918]
Would be a nice feature to have a tab for specified users, in a channel. Much like a VIP list, or even add a VIP/Mod option, so all VIPs/Mod's messages of a channel are placed here.

**Comment by apa420** [comment]
You can achieve this through other means, by example you could add all the vips and moderators to highlight you and then all the messages would appear in /mentions, I know this isn't the most elegant solution, but what you want seams like an edge-case tbh
Example: https://i.nuuls.com/kqPA6.png

**Comment by hemirt** [comment]
do mind that /mentions is one per app

**Comment by fourtf** [comment]
check the filters issue instead
