### ISSUE TITLE
A way to sort the channels

### ISSUE THREAD

**Issue by YostyLad** [Chatterino/chatterino2#920]
I would like a way of sorting the chats/channels I have open. In my case I watch a fair few channels 30+ at a time and have sorted them all alphabetically so I can see them more clearly when trying to find the correct channel.

I would love if there would be a sort function so when I create a channel I do not have to drag it when I find a new channel I like/it's annoying to set up at first.

**Comment by apa420** [comment]
You can now use a quickswitch feature implemented here #1588 
Usage: `ctrl+k` (in the newest version of chatterino)
