### ISSUE TITLE
Easier multi accounting 

### ISSUE THREAD

**Issue by suroa** [Chatterino/chatterino2#926]
If possible I'd like to have a better way to do multi accounting on chatterino other than having multiple instances open. What I have in mind is something that could be triggered by a command so let's say I'm logged in the account "thesuroa" and want to type something in chat using a different account for example "thesuroa1" all I'd have to do would be type "/account thesuroa1 message". This wouldn't necessarily log me into that account, just use it for that specific message.

**Comment by alazymeme** [comment]
adding to this: maybe when you click the down arrow, give the option to popout chat > as <user>

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
