### ISSUE TITLE
Hebrew and Arabic are reversed 

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#930]
for example in english, if i write "Hey how are you" its comes out as "you are how hey"

**Comment by TranRed** [comment]
duplicate of #720 NaM

**Comment by RAnders00** [comment]
@fourtf close as duplicate please and rename the linked issue to have the title `Hebrew and Arabic are reversed`

**Comment by pajlada** [comment]
Duplicate of #720

**Comment by LeopardFMZ** [comment]
Came back three years later to see if a fix is possible to this issue of reversed Arabic/Hebrew language  :(

**Comment by killertofus** [comment]
@LeopardFMZ #720 also #1970
