### ISSUE TITLE
Emote picker not spawning as floating window

### ISSUE THREAD

**Issue by ef4203** [Chatterino/chatterino2#934]
When opening the emote picker, on some tiling window manager it's not shown as a floating (popup) window, rather it spawns a new tile.

**Affected systems**
- Linux
- Tiling Window manager (dwm, i3, awesomewm...)

**Steps to reproduce bug**
- Open a channel
- Click on the emote picker next to the input field
- Emote picker pops up as new window, instead of floating window

**Comment by fourtf** [comment]
I believe this will fix it https://github.com/Chatterino/chatterino2/pull/1843
