### ISSUE TITLE
Mentions are hard to read in light themes

### ISSUE THREAD

**Issue by CaptainFlint** [Chatterino/chatterino2#939]
Mentions are now very hard to read in light/white theme:

![image](https://user-images.githubusercontent.com/6475044/52069663-41256980-2590-11e9-9198-b28efbd9036d.png)

Nightly v1.0.876 built 2019-01-31T07:32:25.0000000Z

**Comment by apa420** [comment]
This seems to be fixed in the latest version @fourtf
