### ISSUE TITLE
Ch2 chrome extension hooking onto a security warning

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#944]
https://i.nuuls.com/qhVew.mp4

As shown there. I've done some quick testing and it appears to only to happen with installer security warnings.

Reproduction steps (in this scenario I was downloading the latest version of virtualbox):
1. Run said installer
2. Drag browser window until the ch2 window hooks onto the security warning for the installer

Ch2 Native Host v1.0
Chrome Version 71.0.3578.98
Ch2 v2.0.4

**Comment by fourtf** [comment]
should be fixed
