### ISSUE TITLE
i open chatterino, but the program it self does not open

### ISSUE THREAD

**Issue by maywedda** [Chatterino/chatterino2#947]
when i downloaded chatterino it worked just fine, but no i open it but i cant actually see it. when i hold alt-tab it appears there but i cant seem to open it.

**Comment by gapbl4** [comment]
try win+shift+left/right arrow

**Comment by RAnders00** [comment]
This could be fixed by ensuring the saved window location/dimensions from the window layout dont exceed the monitor

**Comment by 161134050** [comment]
I unplugged my leftmost monitor when my PC was turned off, and indeed, when I turned my PC back on and opened chatterino It was off the screen to the left.

**Comment by Audisek** [comment]
When I close Chatterino on my 2nd monitor and then switch to only using 1, Chatterino still opens outside of the first screen, and Win+Shift+Arrow or Win+Arrow don't do anything.

The window is just lost in space-time until I swap to 2 monitors again to free it.

**Comment by fourtf** [comment]
fixed
