### ISSUE TITLE
Every split gone after BSOD

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#953]
Got a BSOD Win 10 "memory_management" watching youtube and having ch2 and discord open.
All splits and tabs got deleted

**Comment by fourtf** [comment]
should :b:  fixed

**Comment by Mawntee** [comment]
Just happened to me...

**Comment by breezytreesy** [comment]
Has happened to me multiple times whenever I get a video driver crash. Is there no way to back up your splits?

**Comment by breezytreesy** [comment]
Thank you @Mm2PL, I missed that in the wiki. That should be a perfect workaround, much appreciated!
