### ISSUE TITLE
Colon in input box becomes black if written after \u07EE

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#954]
A strange issue for sure, but if you write "\u07EE :", the colon becomes black (doesn't matter if you put space in between). For copy:

`߮ :`

![chatterino_2019-02-10_01-17-41](https://user-images.githubusercontent.com/3091645/52527476-b9e39e80-2cd1-11e9-9096-b715f5bb4172.png)

**Comment by TranRed** [comment]
This seems to be the case for other "special" characters aswell, like ; - + # ~ $ etc. Also numbers.
Letters seem to be fine.

Additionally I need to press backspace twice to delete the character.

**Comment by hemirt** [comment]
cannot replicate anymore in nightly

@pajlada close?

**Comment by apa420** [comment]
Does this still happen? I tried it but I can see the : maybe it had to do with an old qt version or something

**Comment by TranRed** [comment]
yeah seems to be solved somehow

**Comment by RAnders00** [comment]
@TETYYS close please
