### ISSUE TITLE
Does not submit my text/chat

### ISSUE THREAD

**Issue by Quantummmm** [Chatterino/chatterino2#958]
Chatterino does not let me type, if i open the stream and type in the chatbox on a web browser then it works, but nothing from chatterino and does the same when you try to use commands.

**Comment by TETYYS** [comment]
Web browser will display your chat message even if it was not actually sent out. Do any other users see your message when you send it over a web browser?

**Comment by Quantummmm** [comment]
I tested that, I probably should have mentioned that it does not show when I have both open and chat on chatterino and it does not show on the web browser.

**Comment by Quantummmm** [comment]
Still happening on a daily basis, does this happen to anyone else? Is there a way to troubleshoot this type of situation?

**Comment by hemirt** [comment]
chatterino only shows messages that are sent from the server, that is if your message arrived at server, it will be sent by the server back and you will see it in chatterino

maybe try relogging in

**Comment by alazymeme** [comment]
Was this fixed? Perhaps try the latest nightly: https://github.com/Chatterino/chatterino2/releases/tag/nightly-build
Otherwise you may have been banned on another account in that channel.
