### ISSUE TITLE
Pause on hover + trying to highlight text 

### ISSUE THREAD

**Issue by VulpesHD** [Chatterino/chatterino2#963]
When I try to highlight text in chatterino (pause on hover is enabled), the selection keeps on moving with the chat and it selects everything else, therefore I am not able to copy paste the text I want.

https://i.imgur.com/VvrSMLO.gifv

**Comment by VulpesHD** [comment]
The issue has been fixed, thank you very much :)

**Comment by apa420** [comment]
Seems to be an issue with the message buffer filling up (1000 messages) and removing messages, this makes the chat scroll down even though on hover is enabled, if the chat isn't full it's not an issue
