### ISSUE TITLE
Last viewed message options in the preferences are not present right now

### ISSUE THREAD

**Issue by bennyhillthebest** [Chatterino/chatterino2#964]
I looked inside settings.json and was able to modify "lastMessageColor" and "lastMessagePattern" to my liking, but the options at the moment are not present in the preferences.
Thanks for everything.

**Comment by apa420** [comment]
A better way of doing it was added,
or did I misunderstand your comment?
![](https://i.nuuls.com/2GQia.png)

**Comment by bennyhillthebest** [comment]
I'm talking about this red line that appears when Chatterino is not in focus, that make you see which is your last read message

![istantanea_2019-03-08_16-35-53](https://user-images.githubusercontent.com/5823707/54038308-83118300-41c0-11e9-88b7-1edd44f5d3eb.png)

**Comment by apa420** [comment]
You can still change the values in the settings.json, but there is no option to edit it in the normal settings page atm. (It's one of the few, you have to know the setting to edit it there is in chatterino)

**Comment by Mm2PL** [comment]
Another setting exists that is not mentioned here: `showLastMessageIndicator`
