### ISSUE TITLE
[Useless QoL] Add detection for using custom afk commands to display status in header

### ISSUE THREAD

**Issue by nitrousGranola** [Chatterino/chatterino2#972]
Adding a menu where you say which afk command you use so it knows what to listen for, and what bot to check. 
Whilst checking the bot(s) of choice it will see if it's in another channel to also label you as afk there.
Depending on which bots you use, you might want to have a system to show colors or text for different bots, such as supibot having a blue icon, and pajbot instances (however these might be able to get hooked together in the client) have a green icon.

Examples
cmd: `$afk`
bot: `supibot`

#pajlada: nitrousgranola: $afk
would show an afk icon or text in #pajlada near the top, as well as in #nymn, since they share the same bot, and remove it on both headers when typing in either channel.

------

cmd: `!afk`
bots: `pajbot, botnextdoor, snusbot` (once the afk system is released for pb2)

#pajlada: nitrousgranola: !afk
would show an afk icon in each channel, provided that the user has specified that these bots are linked in their afk system.

**Comment by hemirt** [comment]
this could be resolved with multiple commands and sending them to each bot's channel or whispers (beware the minimal whisper / message delay)

**Comment by Mm2PL** [comment]
There is an API for checking AFK status in Supibot. That might help :)

**Comment by fourtf** [comment]
This issue is out of scope of the Chatterino project.
