### ISSUE TITLE
Show 3x size emote picture on hover 

### ISSUE THREAD

**Issue by ThePridestalker** [Chatterino/chatterino2#976]

**Comment by rexim** [comment]
@pajlada I wanna contribute to Chatterino. May I take this issue?

**Comment by pajlada** [comment]
@rexim absolutely - go ahead!
A few initial opinions/pointers I have:
 - Should probably be opt-in
 - Will need to check "max size" of an emote. Some FFZ emotes don't serve their max size version

**Comment by pajlada** [comment]
Fixed in latest nightly through #1091
