### ISSUE TITLE
Hovering over some monkey twitch emotes displays the regex that can be used to produce them, not the text that was used

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#995]
![chatterino_2019-04-06_12-53-59](https://user-images.githubusercontent.com/3091645/55667896-0fb86b00-586b-11e9-9781-879fd128982b.png)

**Comment by RAnders00** [comment]
Chatterino should pull the text segment that the IRC server gave it, not the regex gotten from the twitch API.

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/111777569-33add380-88ff-11eb-8251-16e4664f4c53.png)

sus

**Comment by Mm2PL** [comment]
resolved by twitch i guess? ![peepoZoom](https://cdn.betterttv.net/emote/5e879f2cacae25096140c8a9/1x)
